ibis-project/ibis

docs/tutorial/06-ComplexFiltering.ipynb
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/tests/execution/test_join.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/dask/tests/execution/test_strings.py
ibis/backends/dask/tests/execution/test_structs.py
ibis/backends/dask/tests/test_udf.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/impala/tests/test_sql.py
ibis/backends/pandas/tests/execution/conftest.py
ibis/backends/pandas/tests/execution/test_join.py
ibis/backends/pandas/tests/execution/test_operations.py
ibis/backends/pandas/tests/execution/test_structs.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/backends/pandas/tests/test_udf.py
ibis/backends/pyspark/tests/test_basic.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_array.py
ibis/backends/tests/test_temporal.py
ibis/backends/tests/test_vectorized_udf.py
ibis/expr/types/relations.py
ibis/expr/visualize.py
ibis/tests/benchmarks/test_benchmarks.py
ibis/tests/expr/test_table.py
ibis/tests/expr/test_visualize.py
ibis/tests/sql/test_compiler.py
ibis/udf/vectorized.py

Follow up from #4600.
- Deprecates `Table.groupby` in favor of `Table.group_by`. Previously both versions existed.
- Adds a nicer error message for users trying to access methods on `Table` using common misspellings. For example
```python
In [2]: t = ibis.table({"x": "int", "y": "float"})
In [3]: t.sort()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 t.sort()
File ~/Code/ibis/ibis/expr/types/relations.py:187, in Table.__getattr__(self, key)
185 if key in common_typos:
186     hint = common_typos[key]
--> 187     raise AttributeError(
188         f"'Table' object has no attribute {key!r},"
189         f"did you mean …
```

depr: deprecate `Table.groupby` alias in favor of `Table.group_by`

---

.github/workflows/ci-data.yml

This PR fixes GCS insert to only exit when an actual error occurs

ci: don't exit with non-zero code always [skip ci]

---

ibis/expr/analysis.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

Fixes a bug in `Table.mutate` where deferred named expressions weren't being handled properly.
Fixes #4629.

fix: fix `table.mutate` with deferred named expressions

---

docs/backends/Impala.md
poetry.lock
pyproject.toml
requirements.txt

BREAKING CHANGE: kerberos support is no longer installed by default for the `impala` backend. To add support you'll need to install the `kerberos` package separately.
Fixes #4666.

fix: remove kerberos extra for impala dialect

---

poetry-overrides.nix

DuckDB makes use of `multiprocessing.cpu_count()` and it locks up my machine whenever it has to build by very efficiently consuming all my cores.  This hack-patch makes it respect `NIX_BUILD_CORES` so that doesn't happen.

chore(nix): override duckdb to respect NIX_BUILD_CORES

---

ibis/backends/dask/__init__.py
ibis/backends/dask/tests/test_client.py

Follow-up for #4678 as suggested in https://github.com/ibis-project/ibis/pull/4678#pullrequestreview-1148271519.

fix(dask): raise TypeError with informative message in ibis.dask.connect

---

ibis/backends/duckdb/__init__.py

`duckdb-engine` version 0.6.4 added a warning when loading tables that indices aren't properly reflected. This warning shouldn't affect our users, this PR silences it.

fix(duckdb): silence duckdb-engine warnings

---

ibis/backends/dask/__init__.py

Passing `str` values of parquet or CSV files to `ibis.dask.connect` does not work as currently documented in the example of the docstring. Instead, it raises a very confusing error message:
```python-traceback
Traceback (most recent call last):
File "/Users/ogrisel/tmp/ibis_sandbox.py", line 34, in <module>
t_dask = ibis.dask.connect({"t": "test.parquet"}).table("t")
File "/Users/ogrisel/code/ibis/ibis/backends/pandas/__init__.py", line 102, in table
schema = sch.infer(df, schema=schema or self.schemas.get(name, None))
File "/Users/ogrisel/mambaforge/envs/dev/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 273, in __call__
raise NotImplementedError(
NotImplementedError: Could not find signature for infer: <str>
```
This PR documents how to create a dask connection with …

docs: fix the inline example for ibis.dask.do_connect

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/tests/test_client.py

The docstring of `create` indicates this should work but it relies on
there being a `schema` method, which isn't true of dataframes.
If it's a dataframe, we wrap it in a `memtable` and then continue.
xref #4683 -- although this doesn't handle the other inconsistency raised there

fix(sqlalchemy): allow passing pd.DataFrame to create

---

docs/index.md

docs: fix typo in first example of the homepage

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-main.yml

This PR removes the install of krb5 system dependencies which should buy back a bit of our CI time.

ci: remove krb5 system dependency installs from ci

---

codecov.yml
dev/update-lock-files.sh

The current codecov checks have a lot of false positives (one recent PR for example failed because it resulted in a large decrease in lines of code, yielding a net decrease in codecov even though all the touched lines were covered). This PR loosens the codecov checks in the following ways:
- Loosen the threshold for the `project` check. Failures recently that we deemed fine were all below a 1% threshold but slightly above a 0.5% threshold.
- ~Disables the `patch` check completely. Sometimes a patch won't hit 90-some-percent coverage (the current threshold), due to either math oddness (as detailed above) or testing restrictions. Several other projects I interact with have completely disabled this check, we do so here as well.~ *edit: disabling `patch` checks disable coverage annotations, …

ci: relax codecov checks

---

ibis/backends/tests/test_join.py
ibis/expr/operations/relations.py
ibis/tests/expr/test_table.py

Previously all column names that collided between `left` and `right` tables were renamed with an appended suffix. Now for the case of inner joins with only equality predicates, colliding columns that are known to be equal due to the join predicates aren't renamed.
Fixes #4618.
```python
In [2]: t = ibis.table({"id": "int", "name": "string"})
In [3]: t2 = ibis.table({"id": "int", "a": "double", "b": "double"})
In [4]: result = t.join(t2, "id")
In [5]: result.columns  # previously this would be ["id_x", "name", "id_y", "a", "b"]
Out[5]: ['id', 'name', 'a', 'b']
```

fix: avoid renaming known equal columns for inner joins with equality predicates

---

ibis/expr/builders.py
ibis/expr/operations/logical.py
ibis/expr/rules.py
ibis/tests/expr/test_value_exprs.py

Provides a little more information to the user about which expressions are causing the rule failure in logical comparisons and the Simple and Searched case builders.
Resolves #4710

fix(ux): improve error messages for rlz.comparable failures

---

ibis/backends/dask/execution/strings.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/test_string.py

fix(pandas): support `substr` with no `length`

---

ibis/backends/duckdb/registry.py
ibis/backends/sqlite/tests/test_client.py
ibis/config.py
ibis/tests/test_config.py

Previously Table/Column expressions had a default limit of 10,000 rows applied when `execute` was called. The existence of this limit was easy for users to miss (it's not obvious that it's applied, and the effects won't be seen for small data), leading to results sometimes being silently truncated to the first 10,000 rows.
We now change the default limit to `None`, meaning no limit. This seems like a safer default value, as it won't result in silent truncation. With the new support for streaming results back (e.g. `to_pyarrow_batches`) we also expect users will want to pull back larger result sets, the presence of a limit seems to harm more than help.
**This doesn't remove the presence of a default limit, just changes the default value**. Downstream systems relying on the presence of this …

fix: change default limit to None

---

ibis/expr/types/pretty.py
ibis/tests/expr/test_pretty.py

This PR fixes an issue with the interactive repr that manifests as an infinite loop when printing a column whose values are all non-finite.
The issue was the use of `all` on an empty sequence in a `while` loop to check whether a list contained only elements whose values end with `"0"`.
That condition was based on a variable whose value is a list of finite values, which is empty (thus causing the infinite loop) because `nan` is the value
of an aggregate (when printing) with no elements.
The solution was to check whether the list of finites values is non-empty.

fix(ux): fix infinite loop in interactive repr

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This is helpful for when you have a weird CSV file and want to specify
some of the additional arguments to DuckDB's `read_csv` function.
Note that the default behavior is still to run `read_csv_auto`, but we
are running it as `read_csv(AUTO_DETECT=True)`.

feat(duckdb): pass through kwargs to file loaders

---

ibis/backends/tests/test_string.py

Fixes failing master pyspark tests.

test(pyspark): `notimpl` substr test

---

ibis/backends/base/__init__.py
ibis/backends/tests/test_client.py

This PR does a few things:
- Enables support for using `ibis.connect` to connect to postgres URLs starting with either `postgres://` or `postgresql://`, since postgres itself accepts both forms.
- Simplifies the implementation of `ibis.connect`. The previous tiered dispatch system was hard to read IMO and hid several bugs ("ravioli code").
- Expands the test suite for `ibis.connect` to better cover the functionality here.
I recognize the removal of the dispatch system may not be desired, since it forces external backends to only work with a standardized URL scheme (which honestly may be fine). I'm fine with reverting that change, but would like us to then be clear about which parts of `ibis.connect`'s dispatch system are intended to be a public extension interface rather than just an …

feat: support both `postgresql://` and `postgres://` in `ibis.connect`

---

ibis/backends/clickhouse/__init__.py
ibis/backends/impala/__init__.py
ibis/common/pretty.py

We use `sqlglot` for pretty-printing SQL. Not all backends are directly supported by sqlglot, but most have a dialect that sqlglot supports that's close enough.
Instead of hardcoding a mapping in the `pretty.py` module, we now add a private optional attribute on the backend, and check there first.

feat: add way to specify sqlglot dialect on backend

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/clickhouse/registry.py
ibis/backends/dask/execution/reductions.py
ibis/backends/pandas/execution/generic.py
ibis/backends/polars/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_window.py
ibis/expr/operations/core.py
ibis/expr/operations/generic.py
ibis/expr/operations/strings.py
ibis/expr/types/generic.py
ibis/expr/types/strings.py
ibis/tests/expr/test_operations.py

This PR fixes window function propagation.
I had to refactor some of the operations to be variadic, so that I didn't have
to hack in support for `NodeList` inside of `propagate_down_window`.
Resolves #4722.

fix(api): ensure that window functions are propagated

---

README.md

the link to the doc points to `/latest/`, which 404s. change to `/dev/` to fix

docs: fix snowflake doc link in readme.md

---

.pre-commit-config.yaml

Ignores poetry check in ci so that we do not have to deal with broken upgrades. See https://github.com/pre-commit/pre-commit/issues/2507 for details.

ci: ignore `poetry-check`

---

.github/workflows/ibis-snowflake.yml

Our snowflake credits are out, so we cannot successfully run these tests in CI anymore. I've reached out to someone at snowflake to see what we can do about this.

ci: allow snowflake to fail

---

.github/workflows/ibis-snowflake.yml
ibis/backends/tests/test_numeric.py

Our snowflake credits are re-upd, so can now run these tests in CI again. Also fixed a bug when running tests in parallel where an existing table was recreated without first checking if it exists.

ci: re-enable snowflake tests

---

ibis/expr/types/relations.py

Add an `agg` alias for `aggregate`. I am really tired of typing out the entire word.

feat(api): add `agg` alias for `aggregate`

---

.github/workflows/conda-lock.yml

This PR removes datafusion from conda lockfile generation. We can reenable it if the package ever starts working again.

ci: remove `datafusion` from conda-lock file gen for windows

---

ibis/expr/types/groupby.py

Follow up to the previous PR (#4765) that added agg to `Table`.

feat(api): add `agg` alias to `group_by`

---

ibis/expr/types/pretty.py

The repr is currently including the "test" row that we use to determine whether an ellipsis is necessary. This PR fixes that.
```
In [5]: import ibis, pandas as pd, numpy as np; ibis.options.interactive = True; from ibis import _
In [6]: t = ibis.memtable(pd.DataFrame({'a': list(range(1, 16))}))
In [7]: t
Out[7]:
┏━━━━━━━┓
┃ a     ┃
┡━━━━━━━┩
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
│     4 │
│     5 │
│     6 │
│     7 │
│     8 │
│     9 │
│    10 │
│    11 │
│     … │
└───────┘
```
```
In [1]: import ibis, pandas as pd, numpy as np; ibis.options.interactive = True; from ibis import _
In [2]: t = ibis.memtable(pd.DataFrame({'a': list(range(1, 16))}))
In [3]: t
Out[3]:
┏━━━━━━━┓
┃ a     ┃
┡━━━━━━━┩
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
│     4 │
│     5 │
│     6 │
│ …
```

fix(repr): fix off by one in repr

---

poetry-overrides.nix

This PR gives the mkdocs program access to the ibis path for development.

build: give `mkdocs` program access to the local ibis path

---

ibis/backends/base/__init__.py

Fixes #2877 -- most of the differing signatures were removed in earlier refactors -- this is the only one left (except for a mock fixture in the test suite)

fix: standardize list_tables signature everywhere

---

.pre-commit-config.yaml

There's an ideological divide that prevents poetry and pre-commit from
collaborating effectively to allow poetry pre-commit hooks to be updated
by pre-commit. This check isn't that useful so I'm removing it.

chore(dev-deps): remove poetry check pre-commit hook

---

docs/api/expressions/top_level.md
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py
ibis/expr/api.py

This PR adds a `read` top level API function for reading the following kinds of things:
1. Local CSV, TSV, TXT and Parquet files. CSV/TSV/TXT files can be gzip compressed
1. Remote versions of any of those
1. Globs of 1., mixing compressed/uncompressed is allowed.

feat(api): add `read` top level function for interactive analysis with CSV and Parquet files

---

.github/workflows/ibis-tpch-queries.yml

The tpch tests have been failing *very* frequently lately during the codecov upload step. Since these tests are extra and shouldn't be testing any specific functionality, I don't feel like we really need coverage here - dropping coverage entirely for tpch rather than debugging the cause of the failures.

ci: drop coverage from tpch tests

---

ibis/backends/mysql/registry.py
ibis/backends/polars/compiler.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_string.py

- Improve the tests for `startswith`/`endswith`; previously the test case resulted in a fully `False` series, letting several bugs slip through.
- Fix `sqlite` and `mysql` implementations of `startswith`/`endswith` to be case sensitive
- Fix bug in `polars` implementation of `startswith` to call the proper method

fix: a few `startswith`/`endswith` fixes

---

ibis/backends/snowflake/__init__.py

The current implementation relies on the base sqlalchemy backend implementation which returns schemas, instead of databases. This PR fixes this by implementing a custom function for the Snowflake backend, which utilizes the `information_schema.databases` view ([docs](https://docs.snowflake.com/en/sql-reference/info-schema/databases.html))

fix(snowflake): fix snowflake list_databases

---

ibis/backends/snowflake/__init__.py

The current implementation of `_get_sqla_table` does not  handle different schemas properly. This PR fixes  this.
This should fix issue https://github.com/ibis-project/ibis/issues/4801

fix(snowflake): handle schema when getting table

---

ibis/backends/clickhouse/registry.py
ibis/backends/dask/execution/arrays.py
ibis/backends/pandas/execution/arrays.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_aggregation.py
ibis/expr/operations/reductions.py
ibis/expr/types/generic.py

This PR makes `ArrayCollect` a filterable reduction, which adds support for the `where` argument similar to other reductions.

feat(backend): make `ArrayCollect` filterable

---

docs/install.md

This PR fixes the link to the tutorial and centers and primary-izes the button. I also removed the nav and toc from the install page since neither of those sidebars is providing any value there. Fixes #4814.

docs: fix tutorial button link

---

.pre-commit-config.yaml

h/t to @ncclementi for telling me about this thing I wish I had a year ago.

chore(pre-commit): add hook to check for leftover breakpoints

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/tests/test_generic.py
ibis/expr/operations/generic.py
ibis/expr/types/relations.py
ibis/tests/expr/test_format.py

This also fixes an incompatibility bug when passing in incompatibly typed scalars to `Table.fillna` (e.g. `table.fillna(0)` in a table containing string columns). Previously the output was backend defined - pandas, for example, would happily return a column mixing strings and integers.
We now allow casting of the fill value, but only between different numeric types. All other fill values must be of the proper column type, otherwise a nice error message is raised explaining the issue.

feat: support `Table.fillna` for SQL backends

---

ibis/backends/dask/tests/test_client.py
ibis/backends/pandas/__init__.py
ibis/backends/pandas/tests/test_client.py
ibis/backends/polars/__init__.py
ibis/backends/tests/test_client.py

fix: exclude geospatial ops from pandas/dask/polars `has_operation`

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_numeric.py

Hello,
``ibis.random()`` will be expressed as the following SQL:
````sql
SELECT uniform(CAST(0.0 AS FLOAT), CAST(1.0 AS FLOAT), random()) AS "RandomScalar()"
````
Best regards,

feat(snowflake): implement  `random` scalar

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_column.py

Hello,
The follwoing code:
```python
t = con.table('functional_alltypes')
result = t[t.rowid()].execute()
```
io translated to the following SQL:
```sql
SELECT seq8() + 1 AS number 
FROM functional_alltypes AS t0
```

feat(snowflake): implement `rowid` scalar

---

ibis/backends/tests/test_client.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py

Previously the `__array__` methods were missing this parameter, causing `np.asarray(table, dtype="some_dtype")` to fail.
Also changes up the `__array__` test a bit so it works on all backends.

fix: support dtype in `__array__` methods

---

ibis/backends/tests/test_api.py
ibis/expr/analysis.py
ibis/expr/types/core.py

Calling `unbind()` on an expression returns an equivalent expression but
with all references to backend-specific tables, e.g. `AlchemyTable`,
`PandasTable`... translated into `UnboundTable`.
Should help with serialization of expressions and ease execution of
expressions across backends.
Resolves #4536
``` python
[ins] In [2]: topfilms
Out[2]: 
r0 := AlchemyTable: ratings
tconst        string
averageRating string
numVotes      string
r1 := AlchemyTable: basics
tconst         string
titleType      string
primaryTitle   string
originalTitle  string
isAdult        string
startYear      string
endYear        string
runtimeMinutes string
genres         string
r2 := Selection[r1]
predicates:
Contains(value=r1.titleType, options=['movie', 'tvMovie'])
r1.isAdult == '0'
r3 := Selection[r0] …
```

feat: add unbind method to expressions

---

ibis/backends/pandas/client.py
ibis/backends/pyarrow/datatypes.py
ibis/expr/datatypes/core.py
ibis/expr/schema.py

Previously these were being monkeypatched onto the classes only if the submodules were imported. This leads to these methods not always existing (the pandas ones were always added, the pyarrow ones were only added if the user ever imported `ibis.backends.pyarrow.datatypes` themselves). Better to define them directly on the classes and avoid this complication.

fix: define `to_pandas`/`to_pyarrow` on DataType/Schema classes directly

---

ibis/expr/analysis.py
ibis/tests/sql/snapshots/test_select_sql/test_sort_then_group_by_propagates_keys/result1.sql
ibis/tests/sql/snapshots/test_select_sql/test_sort_then_group_by_propagates_keys/result2.sql
ibis/tests/sql/test_select_sql.py

This PR fixes a bug where we incorrectly aggressively push sort keys into aggregations even if the aggregation output schema does not contain the sort keys.

fix(analysis): only propagate sort keys that are in an agg's output

---

docs/community/contribute/01_environment.md

`duckdb-engine` is a `noarch`, so with the recent addition of a windows
build for `python-duckdb`, this warning no longer applies.

docs(dev): python-duckdb now available for windows with conda

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/tests/test_client.py

Now if a user passes a `memtable` to `insert`` we'll pull out the
underlying dataframe and use that to update the table.
Resolves #4683

fix: allow inserting memtable with alchemy backends

---

ibis/backends/snowflake/tests/conftest.py
ibis/backends/tests/test_client.py

This PR disables a failing snowflake test case due to the way that pandas to_sql works.

chore: disable snowflake for memtable test

---

ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_assign_labels/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/close_extreme_false/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/close_extreme_false_closed_right/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/close_extreme_false_include_under_include_over/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/closed_right/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/closed_right_close_extreme_false_include_under/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/closed_right_include_over_include_under/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/default/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_over_include_under0/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_over_include_under1/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_over_include_under2/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_under/out.sql
ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_under_include_over/out.sql
ibis/backends/impala/tests/test_bucket_histogram.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/value.py
ibis/expr/types/collections.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_rules.py

This PR aliases Enum to String. See commit messages for details. Closes #4477.

refactor(ir): replace enum functionality with string

---

.github/workflows/nix.yml
shell.nix

This PR adds a branch to the nix workflow that builds the nix shell environment nightly so that the
full development environment for 3.8, 3.9 and 3.10 is in cache.

ci: run nix builds nightly to populate the cachix cache

---

ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/snapshots/test_functions/test_column_regexp_extract/out.sql
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/datafusion/compiler.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/tests/test_string.py
ibis/expr/types/strings.py

This PR makes `StringValue.re_extract` conform to the semantics of `re.match` in the Python standard library.
Fixes #4593.

bug: `re_extract` behavior differs between backends

---

ibis/backends/impala/tests/conftest.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/pyspark/tests/conftest.py

This PR removes some duplicate test related code used to generate random identifiers.

refactor: remove duplicate `_random_identifier` calls

---

ibis/expr/analysis.py
ibis/expr/operations/relations.py
ibis/expr/types/groupby.py
ibis/tests/sql/snapshots/test_sqlalchemy/test_no_cart_join/out.sql
ibis/tests/sql/test_sqlalchemy.py

This fixes a bug where we allow users to pass in non-immediate-child group by keys but then do not correctly substitute the immediate child in. There are probably other places where this can happen. Fixes #4854.

fix(sql): fix generated cartesian join

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml
nix/default.nix
shell.nix

This PR attempts to remove a workaround for `mike` failing to work out of the box in the isolation of the nix environment. Locally at least, I am able to run mike deploy without any failures.

chore(devtools): remove special case `mic` tool

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/tests/sql/snapshots/test_sqlalchemy/test_order_by_expr/out.sql
ibis/tests/sql/test_sqlalchemy.py

This PR fixes an issue where arbitrary expressions failed to compile with the sqlalchemy backend because we were incorrectly lowering sort keys.
Closes #4886.

fix(sqlalchemy): ensure that arbitrary expressions are valid sort keys

---

.gitignore
ibis/tests/benchmarks/test_benchmarks.py

This PR adds a benchmark for a known-slow-to-compile expression. I have the fix in another branch, but want to get a benchmark run in to have a record of the change from the subsequent PR.

perf: add drop compilation benchmark

---

ibis/backends/base/sql/compiler/select_builder.py

This PR addresses the performance issue in #4911. The issue is repeated traversal of the same node in an expression during the correlated ref check. For example, if two columns share the same child table that table will be traversed twice. Let's wait until #4911 is merged before merging this one.

perf(expr): traverse nodes only once during compilation

---

ibis/tests/benchmarks/test_benchmarks.py

This PR adds a benchmark for Node repring, which is very slow on medium to large expressions and makes error reporting for validation unusably slow. I'll follow up with a PR to remove the automatic repr.

test(perf): add Node repr benchmark

---

ibis/expr/operations/relations.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR fixes a bug where we currently do not allow bool literals in `Table.__getitem__` or  `Table.filter` APIs.

fix(api): allow boolean scalars in predicate APIs

---

ibis/expr/operations/core.py
ibis/tests/benchmarks/test_benchmarks.py
justfile

This PR removes the Node repr to alleviate performance problems when validation fails.

perf(node): give `Node`s the default Python repr

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/clickhouse/registry.py
ibis/backends/dask/execution/generic.py
ibis/backends/dask/execution/numeric.py
ibis/backends/dask/execution/strings.py
ibis/backends/datafusion/compiler.py
ibis/backends/pandas/execution/generic.py
ibis/backends/polars/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/sqlite/registry.py
ibis/common/annotations.py
ibis/common/grounds.py
ibis/common/tests/test_annotations.py
ibis/common/tests/test_grounds.py
ibis/expr/analysis.py
ibis/expr/operations/core.py
ibis/expr/operations/generic.py
ibis/expr/operations/strings.py
ibis/expr/rules.py
ibis/expr/types/generic.py
ibis/expr/types/strings.py
ibis/tests/expr/test_operations.py

Since the removal of `ops.NodeList` where we implicitly traverse tuples, the variadic annotation mostly provides syntax sugar. In addition to that `rlz.variadic` hasn't been released yet, so it's better to prefer a simpler approach to reconstruct nodes using purely keyword arguments rather than tracking both `*args` and `**kwargs`.
depends on #4891

refactor(ir): remove unnecessary complexity introduced by variadic annotation

---

codecov.yml

This PR removes the reach part of the codecov report. I personally never click on it and when I do it does not take me to anything useful. If others like it, I am happy to leave it as is.

ci: remove reach section of codecov report

---

codecov.yml

This PR removes the GH status check for project code coverage. After merging in the bigquery backend which requires creds to run its backend suite, PRs will always appear to decrease coverage. I think we really only care about the patch status check, namely that the code that was changed has coverage. Coverage should still show up in the readme badge with the full set of backends covered, as that is published on every merge to master.

ci: remove `project` coverage from CI status checks

---

ibis/backends/duckdb/registry.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/test_string.py

This PR fixes an issue where the DuckDB backend was not using global regex replacement behavior. I also added an implementation of `RegexReplace` for `str` for the pandas backend.

fix(duckdb): replace all in `re_replace`

---

docs/community/contribute/01_environment.md

Add a additional step when using `pip` of installing poetry.

docs: add `pip install poetry` dev env setup step

---

.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-backends.yml
codecov.yml

This PR *actually* removes the GH status check for project code coverage. Turns out you need to explicitly disable it.

ci: actually disable project coverage

---

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_string.py

The implementation of `translate` for `duckdb` was incorrect, but appeared to work correctly in tests since only a single character string was tested. This PR updates the test to better cover this functionality, and drops the implementation for duckdb. Duckdb doesn't appear to have a way to support this operation natively and efficiently.

fix(duckdb): drop incorrect `translate` implementation

---

ibis/backends/dask/execution/generic.py
ibis/backends/dask/tests/execution/test_cast.py
ibis/backends/dask/tests/execution/test_temporal.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/execution/test_cast.py
ibis/backends/pandas/tests/execution/test_temporal.py
ibis/backends/tests/test_temporal.py

The Pandas and Dask backends now interpret casting ints to/from timestamps as seconds since the unix epoch, matching other backends.
Fixes #4062.

fix: pandas/dask now cast int<->timestamp as seconds since epoch

---

pyproject.toml
setup.cfg

- `just fmt`: isort updated the generated python files
- `just lint`: flake8 complained about a couple of generated python files

chore: skip flake8 and isort checks on python files generated by the decompiler

---

default.nix
flake.lock
flake.nix
shell.nix

Allows existing uses of `nix-shell` and `nix build -f .` to continue to work.

chore(dev-deps): add flake compatibility for nix-shell et al

---

ibis/backends/pandas/dispatch.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/test_core.py

The previous dispatch just raised an error saying it wasn't implemented, better to do this as the base implementation of `execute_node`.
Fixes #4945.

fix(pandas): drop `RowID` implementation

---

.github/workflows/ibis-backends.yml

Runs the pyspark backend tests in parallel in CI. This works locally now.

chore: run pyspark tests in parallel

---

docs/backends/Pandas.md

Documentation for UDFs in Python instruct users to import the `udf` class via the following statement:
```python
from ibis.backends.pandas import udf
```
It should actually be:
```python
from ibis.backends.pandas.udf import udf
```

docs(pandas-udf-examples): UDF Examples for Pandas have the incorrect import path.

---

ibis/backends/mssql/compiler.py
ibis/backends/mssql/registry.py
ibis/backends/tests/test_window.py

This PR adds support for a subset of window functions to the `mssql` backend. This is necessary to support the backwards-compatible refactoring of the `histogram` API.

feat(mssql): add window function support

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_window.py
ibis/expr/operations/histograms.py
ibis/expr/types/generic.py
ibis/expr/types/numeric.py
ibis/tests/expr/test_analytics.py
ibis/tests/expr/test_table.py
ibis/tests/sql/snapshots/test_select_sql/test_sort_then_group_by_propagates_keys/result1.sql
ibis/tests/sql/snapshots/test_select_sql/test_sort_then_group_by_propagates_keys/result2.sql

This PR rewrites the current histogram API to use window functions instead of a cross join, in an effort to further simplify the compiler and avoid having expressions or their construction tied to the internal details of the compiler. Depends on #4962.

refactor: reimplement `histogram` API in terms of window functions

---

.github/workflows/ibis-backends.yml

This PR removes the no longer extant `python-dev` package from our CI setup. I am not sure if we still need it, buf if we do, apaprently it is merged into the vanilla `python` package.

ci: remove `python-dev`

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/tests/test_export.py

This fixes two issues with the clickhouse backend:
- `raw_sql` returns a nonstandard object (a tuple of results and other info), rather than a `dbapi` cursor object.
- because of this, the generic implementation of `to_pyarrow_batches` doesn't work.
However, clickhouse's `dbapi` starts a new connection for every `cursor`, which adds some overhead. To remedy this, we:
- Continue to use a single `Client` for all ibis-internal calls
- Implement `raw_sql` using the `dbapi`, which creates a new connection for every cursor
- Implement `_cursor_batches` manually calling `raw_sql` instead of `_safe_raw_sql` since `_safe_raw_sql` continues to use the old `client.execute` code path (which shares a connection).
All of this is gross, but functional. If people have suggestions for a cleaner approach …

fix(clickhouse): use clickhouse's dbapi

---

README.md
docs/backends/Trino.md

This PR adds the bare minimum documentation for the trino backend.

docs(trino): add backend docs

---

ibis/backends/base/__init__.py
ibis/backends/tests/test_client.py

Previously `ibis.connect` would return a `Table` object when calling `connect` on a parquet/csv file. This now returns a backend containing a single table created from that file. This fixes an inconsistency with the current interface, where the return type depended on the value of the connection string, making it hard to type check. When possible users may use `ibis.read` instead to read files into ibis tables.
I went with a clean break here rather than a deprecation because:
- This feature hasn't been out that long anyway, I doubt a breaking change now will affect that many users
- 4.0 has other breaking changes
Happy to move to a deprecation if needed.

fix: `ibis.connect` always returns a backend

---

ibis/backends/tests/test_join.py

This PR speeds up a very slow test (~100s for the execute call for the MySQL backend alone) likely introduced when the default limit of execute was set to `None`, since this expression returns a large number of rows (around 5.5MM).

test(perf): speed up extremely slow join test

---

ibis/backends/pandas/execution/strings.py
ibis/backends/sqlite/udf.py
poetry.lock
pyproject.toml
requirements.txt

This PR moves the `regex` package to an optional dependency, since only the sqlite, pandas and dask backends require it (for posix regexen support).

chore(deps): make the `regex` dep optional

---

ibis/backends/duckdb/registry.py
poetry.lock
pyproject.toml

This PR bumps the minimum duckdb version to 0.3.3 so we can remove a dependency and some old compatibility code.

chore(deps): bump duckdb lower bound

---

.github/workflows/ibis-backends.yml

It seems like running pyspark tests in parallel in CI is flaky, so this PR reverts back to serial tests for pyspark.

ci: reduce pyspark flakiness by running tests serially

---

ci/release/dry_run.sh

When this was ported to use `nix develop` we had to remove `--pure`,
since we removed `nix-shell` usage here, and the `GITHUB_ACTIONS`
variable used by `semantic-release` crept in. We `unset` it so that it
has no effect.

ci: re-enable release notes in `simulate_release`

---

.github/workflows/update-deps.yml

This PR gives the nix updates workflow a higher GH API rate limit, which typically is not necessary, but a recent failure indicate an API limit likely due to a bunch of other concurrent jobs and workflows also hitting the GH API at the same time. Since it is easy to increase the limit we might as well do it.

ci: increase GH API rate limit for nix updates and don't `fail-fast`

---

ibis/backends/clickhouse/tests/conftest.py
ibis/backends/clickhouse/tests/test_client.py

Apparently it is possible for clickhouse parallel testing to trigger a case where occasionally between two `list_tables` calls a fixture that creates a temporary table in the same database as the `list_tables` calls is called and is not dropped before the second `list_tables` calls leading to the occasional (and common enough to warrant this PR) failure.

test: prevent clickhouse test `list_tables` flakiness

---

ibis/expr/types/pretty.py

Previously the pretty printer would never truncate column names. This meant that if a column had a name that exceeded the width of the terminal, the repr would call `table.select([])` then try to repr that (leading to weirdness sometimes).
This PR amends the rules to be:
- Always display at least one column
- If more than one column is displayed, the column names will never be truncated
- If only a single column is displayed, that column name may be truncated to fill the available space
We currently have no tests for the complete repr. In lieu of figuring out a good way to test this, I have manually confirmed this fixes the issue:
```python
In [1]: import ibis                            
...: import pandas as pd                                                                   
...: …
```

fix: always display at least one column in the table repr

---

ibis/backends/postgres/registry.py
ibis/backends/tests/test_array.py

Hi.
Small fix for Postgres backend.
Now the `ibis/backends/tests/test_array.py` tests for Postgres look like below
```
ibis/backends/tests/test_array.py::test_array_discovery_clickhouse[postgres] XFAIL (backend supports nullable nested types)           [  5%]
ibis/backends/tests/test_array.py::test_array_scalar[postgres] PASSED                                                                 [ 11%]
ibis/backends/tests/test_array.py::test_list_literal[postgres] PASSED                                                                 [ 16%]
ibis/backends/tests/test_array.py::test_array_concat[postgres] PASSED                                                                 [ 22%]
ibis/backends/tests/test_array.py::test_unnest_no_nulls[postgres] PASSED …
```

fix(postgres): fix array_index operation

---

flake.lock
poetry-overrides.nix

This PR removes some unnecessary poetry2nix overrides that are now upstream.

refactor(dev-deps): remove unnecessary `poetry2nix` overrides

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml
.github/workflows/nix.yml
.github/workflows/update-deps.yml
ci/release/dry_run.sh
ci/release/prepare.sh
ci/release/publish.sh
ci/release/run.sh
ci/release/verify.sh
flake.lock
flake.nix
nix/ibis.nix
nix/overlay.nix

This PR splits up some of our code in `flake.nix` to a few distinct files under `nix/`.
The upshot here is that we will spend much less time downloading/building dependencies that are never used for certain tasks, for example, building pyarrow before running `pre-commit`.
The new shells `.#release`, `.#docs`, etc only contain the dependencies needed to perform the specific task.
This PR is in draft mode until https://github.com/nix-community/poetry2nix/pull/867 is merged.

refactor: split up custom nix code; remove unused derivations

---

ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/tests/test_aggregation.py
ibis/expr/operations/reductions.py
ibis/expr/types/generic.py
ibis/tests/expr/test_value_exprs.py

Previously the default value for `how` was `None`, which was appears to have been intended to mean `"first"`. The test suite always specified `how` explicitly though, which meant most backends failed to supported the default `how=None`. This PR changes the default to `"first"`, and updates the test suite to include a no-args version of `arbitrary`.

fix: support `arbitrary` with no arguments

---

ibis/backends/dask/tests/conftest.py
ibis/backends/datafusion/tests/conftest.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/polars/tests/conftest.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/test_api.py
pyproject.toml

Occasionally a CI job fails because of a temporary table popping into existence in between one call to `con.list_tables()` and a second call to `con.list_tables()`, making the assertion that the list of tables in the second is equal to the first fail.
This test fails often enough that it annoys me, so I am relaxing the check.

test: relax the assertion on `list_tables` content vs accessor

---

codecov.yml

The numbers in the comment are highly variable in their accuracy given
the coverage that runs on the cloud backends, which makes the PR
comments pretty useless.

chore(dev): remove codecov PR comments

---

nix/overlay.nix

Turns out we were not building the nix derivations with the right corresponding Python version. This PR fixes that.

build(nix): use the right python version for nix builds

---

ibis/backends/base/sql/alchemy/query_builder.py

Hello,
This doesn't change the behavior, but it does make the SQL a bit more readable because the column names are explicitly specified in the VALUES clause.
```python
import sqlalchemy as sa
value_expr_before = sa.values(
sa.column('id', sa.Integer),
sa.column('name', sa.String),
name=None
).data(
[(1, 'name1'), (2, 'name2'), (3, 'name3')]
)
value_expr_after = sa.values(
sa.column('id', sa.Integer),
sa.column('name', sa.String),
name='my_values'
).data(
[(1, 'name1'), (2, 'name2'), (3, 'name3')]
)
print("Before:")
print(str(sa.select(value_expr_before)))
print("After:")
print(str(sa.select(value_expr_after)))
```
Output:
```
Before:
SELECT id, name 
FROM (VALUES (:param_1, :param_2), (:param_3, :param_4), (:param_5, :param_6))
After:
SELECT my_values.id, my_values.name 
FROM (VALUES …
```

feat(sqlalchemy): in-memory tables have name in generated SQL

---

ibis/backends/sqlite/registry.py
ibis/backends/tests/test_window.py
ibis/expr/analysis.py

Since window functions act on multiple rows, fusing a `filter` operation with a prior selection that contained a window function can result in incorrect results.
This came up when doing today's [Hanukkah of Data](https://hanukkah.bluebird.sh/5783/) puzzle.

fix: don't fuse filters & selections that contain window functions

---

ibis/tests/conftest.py

This seems to make tests flaky in some cases, in particular the macos
nix builds. We only test macos on nix, so that's likely why we don't see
it in the non-nix builds.

ci: disable hypothesis too-slow healthcheck

---

ibis/backends/tests/test_client.py
ibis/expr/types/pretty.py

Previously this option was accidentally ignored. This fixes the bug and adds a test.

fix: fix bug when disabling `show_types` in interactive repr

---

.github/workflows/ibis-backends.yml
docker-compose.yml

Hello,
We have a password set as an environment variable in the container, so we need to use a double-dollar sign. Otherwise, the password is read from the host.
Best regards,
Kamil Breguła

fix(mssql): use double-dollar sign to prevent from interpolating a value

---

ibis/backends/tests/test_struct.py

This PR fixes an issue with comparing results in the `test_all_fields` struct type test for the snowflake backend.

test(snowflake): fix failing snowflake struct test

---

ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/tests/test_array.py
ibis/backends/trino/registry.py

This PR adds support for array slicing to the Trino backend, and fixes a bug in negative slicing in the postgres and duckdb backends.

feat(trino): add array slicing support

---

ibis/backends/mssql/registry.py
ibis/backends/tests/test_temporal.py

Hello,
In PR: https://github.com/ibis-project/ibis/pull/5089/files I implemented `ops.TimeFromHMS` and  `ops.TimestampFromUNIX:` but when I looked at it again in the morning I saw that it wasn't working.
I also added `ops.TimestampTruncate` and `ops.DateTruncate`.
Now I want to add dot_sql support. For now I found that the metadata about the query can be fetched like below:
```python
result = bind.execute(
f"DECLARE @query nvarchar(max) = 'SELECT 1 as tmp'; "
f"EXEC sp_describe_first_result_set @query, null, 0; "
)
```
Best regards,

feat/fix(mssql): fix and implement some operations

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/trino/registry.py

ops.TimestampFromYMDHMS doesn't have timezone field, so these checks are redundant.
https://github.com/ibis-project/ibis/blob/26ca1e4f3160de594c8bb3047a3588e607385ad1/ibis/expr/operations/temporal.py#L239-L249

refactor: clean up timezone support in ops.TimestampFromYMDHMS

---

flake.nix

This PR automatically names the nix shell derivations, removing an unnecessary argument from the mkDevEnv invocation.

chore(dev): automatically name the nix shell derivation

---

ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/datatypes.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/test_struct.py

This PR adds support for struct operations to pyspark. The `broken`-marked tests will be fixed by #5097.

feat(pyspark): add support for struct operations

---

ibis/backends/tests/test_client.py

Relax a test that checks for exact contents of `list_databases()` in case upstream vendors add or remove databases.

test(snowflake): relax `test_list_databases`

---

ibis/backends/bigquery/udf/core.py
ibis/backends/dask/execution/maps.py
ibis/backends/dask/execution/strings.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_client.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/mysql/datatypes.py
ibis/backends/pandas/execution/maps.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/base.py
ibis/backends/tests/test_api.py
ibis/common/dispatch.py
ibis/common/tests/test_grounds.py
ibis/expr/format.py
ibis/expr/types/relations.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_string.py
ibis/tests/expr/test_value_exprs.py
ibis/tests/expr/test_window_functions.py
ibis/tests/strategies.py
ibis/udf/vectorized.py
pyproject.toml

This PR enables the flake8-bugbear plugin and fixes associated lints, most of which are `assert False` usage and calling functions in default arguments. `flake8-2020` is also enabled, and there were no existing violations thereof.

chore: enable `flake-bugbear` and `flake8-2020` and fix lints

---

ci/schema/clickhouse.sql
ci/schema/duckdb.sql
ci/schema/mssql.sql
ci/schema/mysql.sql
ci/schema/postgresql.sql
ci/schema/snowflake.sql
ci/schema/sqlite.sql
ibis/backends/bigquery/tests/conftest.py
ibis/backends/bigquery/tests/unit/udf/test_core.py
ibis/backends/bigquery/udf/core.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/dask/tests/conftest.py
ibis/backends/impala/pandas_interop.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/pandas/execution/window.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/polars/tests/conftest.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/data.py
ibis/backends/tests/test_temporal.py
ibis/backends/tests/test_window.py
pyproject.toml

This PR fixes an issue with the pandas backend where the `Transform`
aggregation context was being used instead of the `Moving` context. `Transform`
should only be used when there's a `group_by` present, and no `order_by`.
A backend test and associated data was is also added to catch regressions.
Closes #4676.

fix(pandas): use the correct aggregation context for window functions

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/dask/execution/numeric.py
ibis/backends/datafusion/compiler.py
ibis/backends/pandas/execution/generic.py
ibis/backends/polars/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/sqlite/udf.py
ibis/backends/tests/test_numeric.py

This PR makes all cotangent implementations use `1 / tan(x)` instead of wasting a function call by using `cos(x) / sin(x)`.

refactor: clean up `cot` implementations to have one less function call

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/expr/operations/reductions.py

This PR removes some deprecated aliases for `ApproxCountDistinct` and `ApproxMedian`.

refactor: remove deprecated approximate aggregation classes

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/dask/execution/aggregations.py
ibis/backends/dask/execution/numeric.py
ibis/backends/pandas/execution/generic.py
ibis/backends/postgres/registry.py
ibis/backends/tests/test_aggregation.py
ibis/backends/trino/registry.py
ibis/expr/analysis.py
ibis/expr/operations/reductions.py
ibis/expr/types/logical.py
ibis/expr/types/numeric.py

This PR makes the remaining not filterable reductions filterable. I still need to add tests that hit the filtering branches of these aggs.

refactor: make `Any`/`All`/`Quantile` subclass from `Filterable`

---

ibis/backends/polars/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_struct.py
poetry.lock

Fixes a bug with newer versions of polars that are currently segfaulting when casting a null literal to struct.

fix(polars): workaround failing cast of null to struct

---

docs/user_guide/extending/elementwise.ipynb

It was easier for me to just make a new PR from #5151 than to actuall pull locally and `git commit --amend`.
Before, I would get
```
/var/folders/nz/wfwcn6md1796t48tx9dhf0v40000gn/T/ipykernel_98244/3752312616.py:26: FutureWarning: `Node.op` is deprecated as of v4.0; remove intermediate .op() calls
(arg,) = expr.op().args
```
After this change, I don't.

chore: remove warning in extending tutorial

---

ibis/expr/operations/reductions.py

This PR uncouples `MultiQuantile` from `Quantile`. Since the MultiQuantile class shares nothing with Quantile, there is no reason for it to subclass Quantile.

refactor: uncouple `MultiQuantile` class from `Quantile`

---

ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_numeric.py
ibis/backends/trino/datatypes.py
ibis/backends/trino/registry.py

Add some more missing operations for the trino backend.

feat(trino): add `approx_median`, math ops and `ifnull`-like operations

---

ibis/backends/tests/test_client.py
ibis/expr/sql.py

Add a custom `SQLString` object that formats with syntax highlighting in the notebook.

feat(api): return object from `to_sql` to support notebook syntax highlighting

---

ibis/backends/base/sql/registry/main.py
ibis/backends/impala/tests/test_value_exprs.py
ibis/expr/operations/generic.py
ibis/expr/types/numeric.py
ibis/tests/expr/test_decimal.py

Hello,
This API is only implemented by one backend, and there is an alternative method to obtain this information.
See: https://github.com/ibis-project/ibis/pull/5156#discussion_r1064000868
Best regards,

refactor(ir): remove DecimalValue.precision(), DecimalValue.scale() method

---

ibis/backends/bigquery/registry.py
ibis/backends/tests/test_temporal.py

Hello,
Fix for two tests. 
I'm still working on other things related to the interval support in BigQuery, but I don't know what the final outcome will be, so I'm pushing it for now.
Best regards, 
Kamil Breguła

fix(bigquery): fix integer to timestamp casting

---

poetry-overrides.nix

Looks like the runner upgrade caught a bug. Living on the edge.

ci: fix failing macos nix builds

---

docs/backends/support_matrix.md
ibis/backends/snowflake/registry.py

Hello,
Deleting these operations does not affect the result of the tests, so it looks like they are invalid. When we exclude them from the register, the operation matrix will show a more realistic coverage and we will also know where a contribution is needed.

fix(snowflake): Remove invalid operations from registry

---

ci/schema/mssql.sql
ibis/backends/conftest.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/tests/conftest.py
ibis/backends/postgres/__init__.py
ibis/backends/snowflake/tests/conftest.py

This PR removes the use of concurrent.futures for data loading in the mssql backend, in an attempt simplify debugging the flaky schema-getting test. I also moved some things that should be in transactions but are not to be so.

test(mssql): simplify test data setup

---

ibis/common/tests/test_validators.py
ibis/common/typing.py
ibis/common/validators.py
ibis/tests/test_util.py
ibis/util.py

- now frozendict instances are truly immutable using the builtin dictproxy which only provides a read-only view to the underlying mapping
- support validator construction from `UnionType` (`type1 | type2 | ...`) which is different from `typing.Union`
- add a `Coercible` abstract base class for marking types which can be constructed from differently typed object, this makes type annotation based validations more flexible

feat(common): make frozendict truly immutable 

---

ibis/backends/tests/test_set_ops.py
ibis/expr/types/relations.py

Raises if no tables are passed to set operations that require tables to execute against (`union`, `intersect`, `difference`)

fix(set ops): raise if no tables passed to set operations

---

ibis/backends/base/sql/alchemy/registry.py
ibis/tests/sql/test_sqlalchemy.py

Removes use of `is_not`, based on https://github.com/ibis-project/ibis/issues/5202#issuecomment-1379472037.

refactor(sqlalchemy): remove use of deprecated `isnot`

---

.github/workflows/ibis-docs-lint.yml
docker-compose.yml
ibis/backends/mssql/tests/conftest.py

I'm not sure, but I suspect that MSSQL sometimes performs some maintenance operations after creating the database, which makes the database unavailable.
Let's analyze the log.
At the beginning, we see that the user cannot log and we even have an error code
```
2023-01-11 22:29:11.77 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-11 22:29:11.77 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'ibis_testing'. [CLIENT: 172.23.0.1]
```
According to [Stackoverflow](https://dba.stackexchange.com/questions/29613/login-failed-for-user-error-18456-severity-14-state-38), this error mens:
```
38     'Login valid but database unavailable (or login not permissioned)'
```
After 32 seconds, we have next entries:
```
2023-01-11 22:29:43.03 …
```

ci(mssql): dont recreate database in MSSQL

---

.github/workflows/ci-data.yml

This PR removes the `bq load` invocation in our GCS nightly CI data upload because it is not robust to schema changes, whereas querying a bucket directly is.

ci: stop running `bq load` in gcs insert job

---

.github/renovate.json

Before this PR renovate was not looking at Dockerfiles. Now that we have a few, we should let try to submit update PRs for those as well.

chore: tell renovate to also look at `Dockerfile`s

---

ibis/backends/snowflake/registry.py

This PR re-enables `ops.TableArrayView` for the snowflake backend.

fix(snowflake): re-enable `ops.TableArrayView`

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/postgres/registry.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/registry.py
ibis/tests/sql/snapshots/test_sqlalchemy/test_no_cart_join/out.sql
ibis/tests/sql/test_sqlalchemy.py

While adding test coverage for ExistsSubquery and NotExistsSubquery I discovered that basic execution of correlated subqueries does not work. This PR fixes that. A couple of tests are still failing, hence the draft.

fix(sqlalchemy): fix correlated subqueries on projections

---

docs/stylesheets/extra.css

This PR fixes an issue showing up on Firefox where the streamlit app does not expand to the space of the containing div.

docs: make firefox render the proper iframe height

---

docs/backends/app/backend_info_app.py

This PR adds a checkbox for including/excluding geospatial operations from the matrix.

docs: allow deselecting geospatial ops in backend support matrix

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/duckdb/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/registry.py

Bring back the `typeof` method. Closes #5231.

fix(sql): add `typeof` test and bring back implementations

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_dot_sql.py

This PR fixes an issue where expressions that generate code with bind parameters flat out did not work. We were incorrectly using text + bindparams and then calling execute, when we should have been doing what I am doing here, which is passing the compiled params to an execute call.
Closes #5216.

fix(sqlalchemy): fix view creation with select stmts that have bind parameters

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/base/sql/registry/binary_infix.py
ibis/backends/datafusion/__init__.py
ibis/backends/pandas/core.py
ibis/backends/polars/__init__.py
ibis/expr/types/generic.py
ibis/tests/expr/mocks.py

Deprecate the `.to_projection()` API in favor of the more concise and descriptive `.as_table()` API.

depr(api): deprecate `.to_projection` in favor of `.as_table`

---

ibis/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/version.py

Hello,
I checked and we still had some references from ibis-bigquery which is no longer maintained.
Now we still have one reference, but it's only in tests, so it's okay.
```
git ls-files -z | xargs -0 grep 'ibis.bigquery' | grep -v "ibis\.bigquery\.\(connect\|compile\)"
docs/release_notes.md:* Move BigQuery backend to a `separate repository <https://github.com/ibis-project/ibis-bigquery>`_. The backend will be released separately, use `pip install ibis-bigquery` or `conda install ibis-bigquery` to install it, and then use as before. ([#2665](https://github.com/ibis-project/ibis/issues/2665))
ibis/backends/bigquery/tests/conftest.py:    # https://github.com/ibis-project/ibis-bigquery/issues/30
```
Best regards

chore: remove reference to ibis-bigquery package

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/trino/__init__.py

This PR moves `_get_schema_using_query` to the base sqlalchemy backend class.

refactor(sqlalchemy): move `_get_schema_using_query` to base class

---

.pre-commit-config.yaml
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/tests/system/udf/test_udf_execute.py
ibis/backends/bigquery/tests/unit/test_datatypes.py
ibis/backends/bigquery/tests/unit/udf/snapshots/test_usage/test_multiple_calls_redefinition/out.sql
ibis/backends/bigquery/tests/unit/udf/snapshots/test_usage/test_udf_determinism/False/out.sql
ibis/backends/bigquery/tests/unit/udf/snapshots/test_usage/test_udf_determinism/None/out.sql
ibis/backends/bigquery/tests/unit/udf/snapshots/test_usage/test_udf_determinism/True/out.sql
ibis/backends/bigquery/tests/unit/udf/test_usage.py
ibis/backends/bigquery/udf/__init__.py

Hello,
Our Python to Javascript translation is awesome, but I'm sure there are users who have existing Javascript functions that they would like to use, so I'm adding a new `udf_js` function that adds Javascript functions.
As the next step, I will want to add support for SQL functions, which may be easier to use than adding new operations to add custom business logic.
Best regards,
Kamil Breguła

feat(bigquery): add JS UDF support

---

docs/api/expressions/top_level.md
ibis/backends/tests/test_client.py
ibis/expr/api.py
ibis/expr/types/core.py
ibis/tests/expr/test_table.py

This PR adds a new `ibis.get_backend` function for finding the current execution backend for an expression, or the default backend if no expression is provided.
```python
ibis.get_backend() 
ibis.get_backend(some_expr)
```
Also fixes a small bug where `to_pyarrow`/`to_pyarrow_batches` wouldn't fallback to using the default backend if no bound tables were found (while `.execute` would).
Fixes #5064.

feat: add new `ibis.get_backend` function

---

ibis/expr/rules.py
ibis/tests/expr/test_table.py

fix(ir): error for `order_by` on nonexistent column

---

ibis/backends/postgres/registry.py
ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_temporal.py

This PR fixes the `ibis.now()` implementation for the Snowflake backend.

fix(snowflake): implement working `TimestampNow`

---

ibis/backends/duckdb/datatypes.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/pyspark/__init__.py
ibis/expr/operations/core.py
ibis/expr/operations/relations.py
ibis/expr/operations/strings.py
ibis/expr/sql.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/expr/types/strings.py
ibis/util.py

Deprecate `get_column`-style API in favor of `col`/`cols`. Open to other naming suggestions!

depr(api): deprecate table `get_column`/`s` in favor of `__getitem__`

---

docs/backends/app/backend_info_app.py

This data never refreshes now, so I set the cache TTL to 1h so that we don't have old data.

chore: refresh cache after 1 hour in backend matrix app

---

docs/CONTRIBUTING.md
docs/community/contribute/02_workflow.md

First, the worflow and backend_tests guides were merged together,
so delete the link to the one of them.
Second, these links were going to the 3.2.0 docs,
so update to the new path.

docs: Update links to contributing guides

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/pyarrow/datatypes.py
ibis/expr/schema.py

This PR simplifies a bit of the code around getting schemas for pyarrow batching, and adds a new `Schema.as_struct` method to convert `Schema` objects into `Struct` types.

refactor(backend): simplify pyarrow batching code

---

ibis/backends/polars/__init__.py

Adds functionality to Polars backend so `ibis.polars.connect()` yields a Polars connection with nothing in it.

feat(polars): allow ibis.polars.connect() to function without any passed arguments

---

ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/snowflake/__init__.py

This PR removes `finally:` block that tries to reset the session time zone. This is mostly useless since the entire block is happening inside of a transaction and will be rolleed back if an exception is thrown.

chore(ux): let the transaction error bubble up to avoid nested useless tracebacks

---

docs/api/expressions/top_level.md
ibis/backends/tests/test_client.py
ibis/expr/api.py

This adds a new `ibis.set_backend` utility for setting the default backend, for parity with `ibis.get_backend` added in #5260.
This function can take:
- A backend name (in which case it's created as `ibis.{name}.connect()`
- A backend URL (in which case it's created as `ibis.connect(url)`
- An existing backend instance
In all cases the backend is set as `ibis.options.default_backend`.
The goal here is to make it more ergonomic for use cases where the user doesn't need to explicitly create a backend instance (say, if they're using `ibis.read_parquet` or something). They can then start their scripts as:
```python
import ibis
ibis.set_backend("polars")
t = ibis.read_parquet("path/to/data.parquet")
```

feat(api): add `ibis.set_backend` function

---

.pre-commit-config.yaml
ibis/expr/operations/analytic.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/types/groupby.py
ibis/expr/types/logical.py
ibis/expr/types/numeric.py
ibis/expr/types/relations.py
ibis/expr/types/ruff.toml
pyproject.toml

This PR documents more public expression APIs. I did not document deprecated methods (`to_projection`) or methods that are public but not typically used by analytics end users (`op`). Closes #5263.

docs(api): document more public expression APIs

---

ibis/backends/snowflake/registry.py

This PR removes an unnecessary `parse_json` call for the Snowflake backend implementation of StructField.

refactor(snowflake): remove unnecessary `parse_json` call in `ops.StructField` impl

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/tests/test_client.py
ibis/backends/mysql/tests/test_client.py
ibis/backends/postgres/__init__.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/sqlite/__init__.py

This PR moves quoting to the base SQLAlchemy backend.

refactor(sqlalchemy): clean up quoting implementation

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/clickhouse/datatypes.py
ibis/backends/clickhouse/tests/test_types.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/polars/datatypes.py
ibis/backends/pyarrow/datatypes.py
ibis/backends/pyspark/datatypes.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_struct.py
ibis/backends/tests/test_vectorized_udf.py
ibis/backends/trino/datatypes.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/value.py
ibis/expr/types/structs.py
ibis/tests/benchmarks/test_benchmarks.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_format.py
ibis/tests/expr/test_literal.py
ibis/tests/expr/test_sql.py
ibis/tests/sql/test_sqlalchemy.py
ibis/tests/strategies.py

BREAKING CHANGE: Struct(names, types) is not supported anymore, pass a dictionary to Struct constructor instead

refactor(datatype): use a dictionary to store `StructType` fields rather than `names` and `types` tuples

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/sqlite/__init__.py

This PR seems to fix the current flakiness in `test_dot_sql.py`.
While I'm not 100% sure it does, I was able to reproduce the [current flakiness](https://github.com/ibis-project/ibis/actions/runs/3968820831/jobs/6802496984)
by running the tests locally like so:
```
pytest -n 4 -m postgres -x --dist=loadgroup
```
When I run the tests without `--dist=loadgroup` I cannot reproduce the issue. This isn't viable generally because 
some backends cannot run queries across processes (which is the concurrency model for `pytest-xdist`).
This change moves the `xdist_group` marker to decorate each test instead of being a module level marker, which doesn't seem to work.
Things I tried:
1. A larger number of processes seems cause fewer failures, much to my surprise.
2. Running the `dot_sql` tests in …

test(dot-sql): make `dot_sql` tests less flaky

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_struct.py

This PR implements the `ops.StructColumn` and `ops.Time` operations for the Snowflake backend.

feat(snowflake): add struct column operation

---

ibis/backends/tests/test_generic.py
ibis/expr/operations/generic.py
ibis/expr/types/relations.py

Hello,
Now, the complete schema is unreadable if the exception content is displayed on one line.
Now I'm just displaying the column names so it's easier to read in one line context.
Best regards

feat(ux): improve error message when column is not found

---

ci/schema/snowflake.sql
ibis/backends/base/sql/registry/literal.py
ibis/backends/bigquery/compiler.py
ibis/backends/bigquery/custom_udfs.py
ibis/backends/pandas/execution/decimal.py
ibis/backends/pandas/execution/generic.py
ibis/backends/polars/compiler.py
ibis/backends/polars/datatypes.py
ibis/backends/tests/test_generic.py

Hello,
I decided to implement these operations as a UDF so that the SQL code is still readable when the Ibiis expression contains several use of ops.Typeof.
Best regards,

feat(bigquery): implement `typeof` using SQL UDF

---

ibis/backends/tests/test_generic.py

This PR fixes two `typeof` tests that [failing](https://github.com/ibis-project/ibis/actions/runs/3982108632/jobs/6826285184) against the Snowflake backend.

test(snowflake): fix xpassing typeof date and typeof timestamp tests

---

ci/schema/postgresql.sql
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/tests/test_map.py
ibis/backends/tests/test_param.py

This PR adds support for a subset of map types supported by postgres via the [`HSTORE`](https://www.postgresql.org/docs/current/hstore.html) type.

feat(postgres): add `Map(string, string)` support via the built-in `HSTORE` extension

---

ibis/backends/tests/test_map.py

This PR fixes an issue with creating a test table that doesn't get automatically quoted when using `con.create_table`
Test run looks good:
```
…/ibis on  fix-snowflake-create-map-table is 📦 v4.0.0 via 🐍 v3.10.9 via ❄️  impure (ibis-3.10.9) took 21s
❯ pytest ibis/backends/tests/test_map.py::test_map_create_table -m snowflake
======================================================================================== test session starts =========================================================================================
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=574689024 …
```

test(snowflake): use an always-valid identifier in testing map table creation

---

docker-compose.yml
ibis/backends/mysql/tests/conftest.py
ibis/backends/postgres/tests/conftest.py

This PR tries to address an issue observed in [this comment](https://github.com/ibis-project/ibis/pull/5297#issuecomment-1400400732) where the ibis_testing database is trying to be dropped while another process is using it. The approach here is to simply not try to drop databases that are created by the container on startup.

chore(dev): don't try to drop databases that are automatically created

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/clickhouse/datatypes.py
ibis/backends/clickhouse/tests/test_types.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/polars/datatypes.py
ibis/backends/pyarrow/datatypes.py
ibis/backends/pyspark/datatypes.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_struct.py
ibis/backends/tests/test_vectorized_udf.py
ibis/backends/trino/datatypes.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/value.py
ibis/expr/schema.py
ibis/expr/types/structs.py
ibis/tests/benchmarks/test_benchmarks.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_format.py
ibis/tests/expr/test_literal.py
ibis/tests/expr/test_sql.py
ibis/tests/sql/test_sqlalchemy.py
ibis/tests/strategies.py

These are going to be removed in `5.0` via #5288 
I ended up applying most of the changes of the previous PR in a backward compatible fashion.

depr(datatype): schedule `Struct.from_dict()`, `Struct.pairs` and `Struct(names, types)` constructor for removal

---

docs/SUMMARY.md
docs/api/selectors.md
ibis/expr/api.py
ibis/expr/selectors.py
ibis/expr/types/relations.py
ibis/tests/expr/test_selectors.py
mkdocs.yml

Convenient columnn selectors, shamelessly cribbed from https://dplyr.tidyverse.org/reference/select.html.

feat(api): add selectors for easier selection of columns

---

ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py

This PR fixes an issue where the plain text repr has an additional newline. It appears to be coming from rich, and this is a workaround until upstream can be fixed.

fix(ux): remove extra trailing newline in expression repr

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/client.py
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/tests/conftest.py

fix(bigquery): resolve deprecation warnings for `StructType` and `Schema`

---

ibis/backends/bigquery/client.py
ibis/backends/bigquery/tests/unit/test_compiler.py
ibis/expr/schema.py

This fixes a few remaing fail-on-warning errors for the BigQuery backend and corrects a misspelling in the warning for Schema.

test(bigquery): fix struct/schema deprecation warnings

---

ibis/backends/conftest.py
ibis/backends/snowflake/tests/conftest.py

This fixes an test issue where an invalid `isolation_level` argument was passed to `sa.create_engine`.

test(snowflake): ignore `isolation_level` for the snowflake backend tests

---

ibis/backends/base/__init__.py
ibis/backends/tests/test_api.py

In a notebook I want to see the names of the tables in the database.
Before I would get
'<ibis.backends.base.TablesAccessor object at 0x118321c90>'
Now I get
```
[
"df",
"df0",
"df1",
"df10",
"df11",
"df12"
]
```
I considered just doing `return repr(list(self))`,
but I wanted the tables to be in sorted order,
and I wanted them to be indented so they'd be
easier to scan with your eyes.
The test is a bit lax, but I wanted it to be future-proof.

feat: make Backend.tables.__repr__ look like list

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py
ibis/expr/api.py

This PR adds experimental support for reading newline delimited JSON files using duckdb.

feat(duckdb): add `read_json` function for consuming newline-delimited JSON files

---

ibis/backends/dask/__init__.py
ibis/backends/dask/tests/test_client.py
ibis/backends/pandas/__init__.py
ibis/backends/pandas/tests/test_client.py
ibis/backends/polars/__init__.py

A minor UX improvement, following up from #5275.

feat: support `connect()` with no arguments for dask and pandas

---

ibis/backends/bigquery/registry.py

We should add support for these operations, but we can do it later. For now, I'd like the operation matrix to have real coverage.
If someone is interested in implementing it, they can do it based on this code.
https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/community/url_parse.sqlx

fix(bigquery): remove invalid operations from registry

---

ci/schema/snowflake.sql
ibis/backends/snowflake/tests/conftest.py

This PR fixes an issue where multiple users were running the Snowflake test suite at the same time and clobbering each other's databases. I address this by creating a schema per user. Additionally, I've moved all the test tables to be `TEMP` tables which ties their lifetime to the client and provides another level of isolation. Two connections using the same credentials will only be able to see the temporary tables of the individual connection and so multiple connections running at the same time can't clobber each other's tables.

test(snowflake): create a testing schema per-user to avoid clobbering

---

ci/schema/snowflake.sql

This PR reverts the temp table testing for the Snowflake backend, which was perhaps a bit too optimisitic on my end :) Without this change I am unable to run the snowflake tests in parallel with 32 physical cores, with it there are no problems.

test(snowflake): revert temp table usage

---

ibis/expr/datatypes/core.py
ibis/expr/schema.py
ibis/tests/expr/test_schema.py

BREAKING CHANGE: `Schema.from_dict()`, `.delete()` and `.append()` methods are removed

refactor(schema): remove deprecated `Schema.from_dict()`, `.delete()` and `.append()` methods

---

docs/backends/Impala.md
ibis/backends/base/sql/compiler/translator.py
ibis/backends/conftest.py
ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_client.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/tests/conftest.py
ibis/expr/operations/relations.py
ibis/expr/operations/strings.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/expr/types/strings.py
pyproject.toml

BREAKING CHANGE: removed the following symbols:
- `ibis.backends.duckdb.parse_type()` function
- `ibis.backends.impala.Backend.set_database()` method
- `ibis.backends.pyspark.Backend.set_database()` method
- `ibis.backends.impala.ImpalaConnection.ping()` method
- `ibis.expr.operations.DatabaseTable.change_name()` method
- `ibis.expr.operations.ParseURL` class
- `ibis.expr.operations.Value.to_projection()` method
- `ibis.expr.types.Table.get_column()` method
- `ibis.expr.types.Table.get_columns()` method
- `ibis.expr.types.StringValue.parse_url()` method

refactor(ir/backends): remove various deprecated functions and methods

---

ibis/expr/datatypes/core.py
ibis/tests/expr/test_datatypes.py

- refactor(schema): remove deprecated `Schema.from_dict()`, `.delete()` and `.append()` methods
- feat(datatype): implement `Mapping` abstract base class for `StructType`
https://github.com/ibis-project/ibis/pull/5323 should be merged first

feat(datatype): implement `Mapping` abstract base class for `StructType`

---

ibis/backends/postgres/registry.py
ibis/backends/tests/test_sql.py
ibis/expr/sql.py

This PR cleans up literal arrays in postgres. We were working around literal arrays just for SQL pretty-printing, which it turns out can be avoided by using the `"qmark"` parameter-style so that sqlglot does not fail.

refactor(postgres): clean up literal arrays

---

ibis/expr/datatypes/core.py
ibis/expr/schema.py
ibis/tests/expr/test_schema.py

- refactor(schema): remove deprecated `Schema.from_dict()`, `.delete()` and `.append()` methods
- feat(datatype): implement `Mapping` abstract base class for `StructType`
- feat(schema): implement `Mapping` abstract base class for `Schema`

feat(schema): implement `Mapping` abstract base class for `Schema`

---

ibis/expr/types/relations.py
ibis/expr/types/structs.py
ibis/tests/expr/test_struct.py
ibis/tests/expr/test_table.py

Previously getattr tab completion would include things that weren't valid python identifiers (e.g. column names including spaces/python keywords).
Also adds getitem completion for structs, previously these only supported getattr completion.

fix: only include valid python identifiers in table/struct tab completion

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/mssql/datatypes.py
ibis/backends/mysql/__init__.py
ibis/backends/mysql/datatypes.py
ibis/backends/postgres/datatypes.py
ibis/backends/sqlite/datatypes.py

This PR moves the respective backend data type dispatch to individual `backends/<backend>/datatypes.py` modules.

refactor(sqlalchemy): split data type dispatches into backend specific modules

---

ibis/backends/tests/test_client.py

Fixes a failing upstream test.

test(sqlalchemy): fix previously-untested failing unsigned integer test

---

ibis/backends/duckdb/tests/test_register.py
ibis/backends/pandas/client.py
ibis/backends/pandas/tests/test_client.py

This PR adds support for inferring ibis data types from pandas nullable types as well as pandas wrapper around arrow types. Execution is supported only for the pandas types, not the arrow ones and the returned types remain unchanged. This feature allows users to be unblocked from consuming these pandas types.
Closes #5343.

feat(pandas): support more pandas extension dtypes

---

ibis/backends/tests/test_client.py

This PR fixes an xpassing test from the trino backend.

test(trino): fix xpassing `load_data` test

---

ibis/backends/base/sql/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py
ibis/backends/pandas/client.py
ibis/backends/pyspark/__init__.py
ibis/util.py

This PR works around an apparent lifetime issue where reads of pandas.DataFrame with pyarrow-dtype columns through duckdb exit with a segmentation fault.
Here's an example CI run that shows the issue: https://github.com/ibis-project/ibis/actions/runs/4036380326/jobs/6938934300.
I was able to reproduce the issue by repeating the failing test case a large-ish number of times:
```shell
pytest ibis/backends/duckdb/tests/test_register.py::test_memtable_with_nullable_pyarrow_string --count=10000
```
I cannot reproduce it with this fix.

fix(duckdb): workaround an ownership bug at the interaction of duckdb, pandas and pyarrow

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This PR fixes an issue where a non-existent directory can be used for out of core processing. The solution is to create the directory and its parents.

fix(duckdb): ensure that `temp_directory` exists

---

ibis/expr/datatypes/cast.py
ibis/expr/datatypes/core.py
ibis/expr/schema.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_rules.py
ibis/tests/expr/test_schema.py

The point here is to support more declarative schema and table definitions, example:
```py
import datetime
import ibis
import ibis.expr.datatypes as dt
class FooSchema:
a: int
b: str
c: float
d: tuple[str]
e: list[int]
f: dict[str, int]
g: datetime.date
class BarSchema:
a: dt.int64
b: dt.string
c: dt.float64
d: dt.Array(dt.string)
e: dt.Array(dt.int64)
f: dt.Map(dt.string, dt.string)
g: dt.Date
class BazSchema:
a: dt.Int64
b: dt.String
c: dt.Float64
d: dt.Array[dt.String]
e: dt.Array[dt.Int64]
f: dt.Map[dt.String, dt.String]
g: dt.Date
foo = ibis.table(name="foo", schema=FooSchema)
```
Nested types and annotations are also supported, tested for plain classes, dataclasses and namedtuples.
`NamedTuple` and various `dataclasses` are gaining tractions with more recent python versions so we …

feat(datatype/schema): support datatype and schema declaration using type annotated classes

---

nix/ibis.nix

This PR fixes an issue where `$HOME` needs to be writable but is not by default in nix builds. We use a temporary directory as `$HOME` to make it writable.

build(nix): fix nix tests

---

.pre-commit-config.yaml
ibis/backends/bigquery/tests/unit/test_compiler.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/tests/sql/test_compiler.py
pyproject.toml

This PR reverts some ruff style changes introduced by our use of `--fix` in pre-commit. I reverted those changes and disable the corresponding rule (SIM300) and removed automatic fixing for now.

chore: disable ruff autofixing and revert SIM300 changes

---

ibis/expr/types/pretty.py

On dark theme screens it was very hard to read the dtype text. The `dim`
style is what is used by the null symbol
"∅", and that looks great in both
white and dark mode
on my machine.

feat: change Rich repr of dtypes from blue to dim

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py
ibis/backends/trino/compiler.py
ibis/backends/trino/registry.py
ibis/expr/analysis.py

This PR (finally) generalizes the unnest implementation to handle the case where unnest is not supported in a `SELECT` statement, but must come after a cross join in a `FROM` clause.

feat(sqlalchemy): generalize unnest to work on backends that don't currently support it

---

ibis/backends/bigquery/compiler.py
ibis/backends/bigquery/tests/system/udf/test_udf_execute.py
ibis/backends/dask/__init__.py
ibis/backends/dask/core.py
ibis/backends/dask/tests/execution/test_strings.py
ibis/backends/pandas/__init__.py
ibis/backends/pandas/core.py
ibis/backends/pandas/tests/execution/test_strings.py
ibis/backends/postgres/tests/test_postgis.py
pyproject.toml

This PR removes some defunct warning handlers from `pyproject.toml` and updates our codebase to avoid internal APIs that trigger them.

chore(dev): remove dead warning handlers

---

ibis/backends/snowflake/registry.py

This is somewhat niche, as you only hit this when you have snowflake installed with at least one of trino or duckdb. This scenario is common in development, but not in end user workflows.

fix(snowflake): use `_flatten` to avoid overriding unrelated function in other backends

---

docs/ibis-for-sql-programmers.ipynb

Instead of mentioning the Impala SQL compiler, use `ibis.show_sql` to show sql examples.

docs(tutorial): remove impala from sql tutorial

---

ibis/backends/base/sql/__init__.py

I noticed that the `bigquery` extra didn't require `sqlalchemy` but I
hit an import error for `sqlalchemy` via `base/sql/__init__.py`.
Most of our sql backends make use of sqlalchemy, but not all, and so it
seems odd to require it.  Moving it inside the single function call that
makes use of it.

fix(imports): remove top-level import of sqlalchemy from base backend

---

ibis/backends/tests/test_client.py
ibis/backends/tests/test_numeric.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py

This PR adds a `to_pandas()`, which the `plotnine` library uses to turn non-DataFrame objects into pandas objects, providing lightweight compatibility with an ecosystem project.

feat(api): implement `to_pandas()` API for ecosystem compatibility

---

ibis/backends/postgres/registry.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py

This PR adds argmin and argmax implementations for th snowflake and postgres backends.

feat(snowflake/postgres): implement argmin/argmax operations

---

.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-main-skip-helper.yml
.github/workflows/ibis-tpch-queries-skip-helper.yml

Follow up from #5414. This is a hack that we have in a couple other places, [endorsed by GitHub](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks), to allow workflows that allow required status checks to be "skipped" when none of their files match. It is not pretty, but it works.

ci: add github actions helper hack to satisfy the required tpch check

---

docs/tutorial/04-More-Value-Expressions.ipynb
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/pandas/tests/execution/test_operations.py
ibis/expr/types/generic.py
ibis/tests/expr/test_table.py
ibis/tests/sql/snapshots/test_select_sql/test_sort_then_group_by_propagates_keys/result1.sql
ibis/tests/sql/snapshots/test_select_sql/test_sort_then_group_by_propagates_keys/result2.sql

This PR gives a name to the aggregation in the result of `value_counts` a name that doesn't conflict with any existing method names, making the output a bit mroe join friendly.
Closes #5062.

fix(ux): give the `value_counts` aggregate column a better name

---

docs/install.md
ibis/config.py
ibis/expr/api.py

xref #5420
Default to `duckdb` in the install doc, fix the API doc of
`default_backend`, and note that the `read_*` functions passthrough to
the default backend.

docs(io): doc/ux improvements for read_parquet and friends

---

ibis/backends/polars/compiler.py
ibis/backends/tests/test_aggregation.py

All the other backends do this, but polars was missing the alias.
Fixes #5421

fix(polars): use metric name in aggregate output to dedupe columns

---

README.md

Follow up on #5423 
xref #5420
This also adds single quotes around bracketed pip install commands to make sure they work with zsh which is the default shell on macOS.

docs(io): update README.md to recommand installing duckdb as default backend

---

ibis/backends/conftest.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_export.py
ibis/config.py

If a user installs only `ibis-framework` and then tries to run `ibis.read_parquet` or similar, they get an unhelpful error message. This tries to guide them in a helpful direction.

fix(backend): provide useful error if default backend is unavailable

---

ibis/backends/base/__init__.py

xref #5420
This adds `read_parquet` and `read_csv` as methods to the `FileIOHandler` mixin (renamed from `ResultHandler`).
Now every backend will have these two `read_` methods and will raise a `NotImplementedError`.

fix(io): add `read_parquet` and `read_csv` to base backend mixin

---

.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml
ibis/backends/conftest.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_export.py
nix/ibis.nix

Enable nix builds in CI again. Previously we disabled them because they built things from source, but now that they are using wheels they are well within reasonable CI times.

ci: renable nix builds

---

ibis/backends/tests/test_array.py
ibis/expr/types/arrays.py

This PR fixes a broken implementation of `__radd__` array concatenation.

fix(api): fix broken `__radd__` array concat operation

---

mkdocs.yml

This PR enables rendering dunder methods in API documentation.
Closes #5424.

docs: render dunder methods

---

ibis/expr/types/generic.py
ibis/expr/types/groupby.py
ibis/tests/expr/test_window_functions.py

feat(ux): expose `rows` and `range` keyword arguments in `value.over()`

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/impala/tests/snapshots/test_sql/test_nested_join_multiple_ctes/out.sql
ibis/backends/tests/test_generic.py
ibis/expr/analysis.py

This PR allows `isin` to work for column expressions that do not share a child table. Closes #5228.

feat(api): allow `isin` to work across expressions that don't share a table

---

docs/backends/index.md
docs/user_guide/configuration.md

Closes #5420.
Addresses the last two TODO items about documenting how to configure the default backend with an example on its impact on the table expression returned by `ibis.memtable`.

Doc default backend config

---

ibis/backends/base/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/tests/test_export.py
ibis/expr/types/core.py

`to_csv` and `to_parquet` seem self-evidently necessary.  ~PyArrow makes adding `to_orc` very easy, so I thought why not?~  because of windows, that's why not.
Also adding in a slightly silly `to_pyarrow_batches` method for the Pandas backend -- for CSV and parquet, I'm writing out the results of an expression as batches so we don't blow up memory.  I can either override `to_csv` and `to_parquet` in the pandas backend, or add in the slightly roundabout recordbatch producer.

feat(io): add to_parquet, to_csv to backends

---

ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/tests/test_generic.py

Implement isin-in-select-position for BigQuery

feat(bigquery): implement `isin` in select position

---

ibis/backends/base/__init__.py
ibis/backends/tests/test_export.py
ibis/expr/types/core.py

refactor: drop `limit` kwarg from `to_parquet`/`to_csv`

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_export.py

Previously memtables weren't being properly registered for `to_pyarrow`/`to_pyarrow_batches` for `duckdb`. This adds a test for that and fixes the issue. Fixes #5471.

fix(duckdb): fix memtable `to_pyarrow`/`to_pyarrow_batches`

---

ibis/backends/clickhouse/datatypes.py
ibis/backends/duckdb/datatypes.py
ibis/backends/postgres/datatypes.py
ibis/backends/trino/datatypes.py
ibis/expr/datatypes/parse.py

This PR cleans up the parsing rules to remove `parsy.generate` usage.

refactor(datatype): clean up parsing rules

---

ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_string.py
ibis/backends/trino/registry.py
ibis/expr/operations/strings.py
ibis/expr/types/arrays.py
ibis/expr/types/strings.py

This PR adds the ability to join an array of strings with a separator. Two methods are added, one Pythonic `literal.join(array)` and one for convenience `array.join(literal)`. They both use the same underlying operation.

feat(api): add array to string join operation

---

ibis/__init__.py
ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/dask/tests/test_client.py
ibis/backends/dask/tests/test_core.py
ibis/backends/pandas/tests/execution/test_functions.py
ibis/backends/tests/test_temporal.py
ibis/expr/sql.py
ibis/tests/test_api.py

Previously all methods on a backend were also exposed via the backend's pseudomodule (i.e. `ibis.<backend>.<method>` instead of `ibis.<backend>.connect().<method>`). This was an implementation detail of how backends were registered, most of these methods didn't work without an explicit `connect` call beforehand, and should not (and could not) work properly when called on the `ibis.<backend>` directly.
We now expose only `connect`, `compile`, `add_operation`, and `has_operation` on the backend module namespace, all other methods require a connected backend to work.
Fixes #5436.

fix: don't expose backend methods on `ibis.<backend>` directly

---

ibis/__init__.py
ibis/backends/tests/test_client.py
ibis/tests/test_api.py

Fixes a small bug where the `name` attribute on backend modules was expected to exist.

fix(api): add a `name` attribute to backend proxy modules

---

ibis/backends/base/sql/__init__.py
ibis/backends/snowflake/__init__.py
ibis/expr/api.py

implemented _register_in_memory_table to create temp table. 
in addition, modified generated table name to use uuid4 instead of a per-process counter which can be potentially fragile ,  (will be happy for your thoughts about it, and of course will be happy to revert if needed)

feat(snowflake): Add support for bulk upload for large memtable

---

.github/workflows/ibis-backends-cloud.yml

Snowflake uses the `random` module to generate temporary stage names.
When the random seed is reset to a fixed value for each test, the
`CREATE TEMP STAGE` step that is part of the `write_pandas` call will
fail because a duplicate stage is being created. In practice this is not
a huge problem because most users aren't setting the random seed and
this is also a `snowflake-connector-python` problem: they should
probably be generating names using UUIDs instead of an arbitrary length
string.

ci(snowflake): don't reset the random number seed for every test

---

ibis/backends/mysql/registry.py
ibis/backends/postgres/registry.py
ibis/expr/types/strings.py

This PR adds examples to almost every user-facing string API. I did not add examples where the duckdb backend does not implement a particular API.

docs(api): add string api examples

---

ibis/expr/types/generic.py

I changed the type annotation, but it looks like mypy currently spits out a ton of errors, so verifying with mypy was useless. Mostly I changed the type for the benefit of the web docs

docs: improve Expr.substitute() docstring

---

ibis/backends/tests/test_column.py

It is redundant.
https://github.com/ibis-project/ibis/blob/c2e50651763841fc9ce4518a6a6f3546b03337ce/ibis/backends/tests/test_temporal.py#L20-L39

test(backends): remove test_column::test_date_extract_field

---

ibis/expr/api.py
ibis/expr/operations/relations.py
ibis/expr/rules.py
ibis/expr/schema.py
ibis/tests/expr/test_schema.py
ibis/tests/expr/test_table.py

Examples:
```python
class MyTable:
a: int
b: str
c: list[float]
t = ibis.table(MyTable, name="MyCustomName")
```
As an extra implemented the `Coercible` interface for `Schema`, so `Annotable` supports it as type annotation:
```py
class ObjectWithSchema(Annotable):
schema: sch.Schema
```

feat(ux): allow creating unbound tables using annotated class definitions

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/tests/test_map.py
ibis/backends/trino/registry.py

Removes some implemented operations from the invalid ops registry. Adds a test for map length and implements it for clickhouse.

feat: implement map length for trino/clickhouse

---

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_string.py

Fixes an issue where parameter substitution occurs in the wrong order when using the numeric bindparam style. Closes #5522.

fix(duckdb): fix bind param usage in `regexp_replace`

---

ibis/backends/tests/test_set_ops.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/tests/test_core.py
ibis/expr/operations/relations.py
ibis/expr/schema.py
ibis/tests/expr/test_schema.py
ibis/tests/expr/test_set_operations.py
ibis/tests/test_util.py

If we consider two schemas equivalent with identical fields but in different order (ref https://github.com/ibis-project/ibis/pull/5526#issuecomment-1427893522), then the set operations just need to ensure that both sides have the same schema - not considering the field order. 
Ideally all backends should ensure to handle set operations properly by adding an extra projection if the backend needs reordered fields. Another option is to do that operation-wise, implemented by this PR which should offload that extra work from the backends. 
While it should fix the problem, I think the internal representation was correct earlier as well since the two schema were *equal*. This fix is a band aid to overcome the semantical difference how ibis' IR and certain backends' implementation treat schema …

fix(ir): reorder the right schema of set operations to align with the left schema

---

ibis/backends/bigquery/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_string.py
ibis/backends/trino/registry.py

This PR uses backend specific implementations of startswith/endswith operations, which generates cleaner SQL. I also fixed a bug in the pyspark backend where we were translating endswith to startswith.

refactor: use backend specific startswith/endswith implementations where possible

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py
ibis/expr/api.py
poetry.lock
pyproject.toml

This PR changes the duckdb read_json implementation to use the new-in-duckdb-0.7.0 function `read_json_auto`. Depends on #5545.

feat(duckdb): use `read_json_auto` when reading json

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/datatypes.py
ibis/backends/tests/test_generic.py

This PR fixes an issue where the bool type we are currently using is not compatible with the `clickhouse_driver` library. We use `Bool` (which is the only supported spelling) instead of the others that are supported by ClickHouse server.

fix(clickhouse): use a bool type that is compatible with `clickhouse_driver`

---

ibis/backends/mssql/__init__.py
ibis/backends/tests/test_sql.py

This PR properly sets `_sqlglot_dialect` for the MS SQL Server backend, enabling `show_sql`/`to_sql` to work.

fix(mssql): set sqlglot to tsql

---

ibis/common/annotations.py
ibis/common/grounds.py
ibis/common/tests/test_annotations.py
ibis/common/tests/test_grounds.py
ibis/common/tests/test_validators.py

The main motivation for this change was to not limit `callable_with` support for functions with either variadic positional or variadic keyword arguments. `callable_with` converts the passed callable into an `@annotated` function which hasn't been supporting variadic arguments. 
To be precise, the annotation system used to support variadic arguments but we removed it due to implementation complications around node traversal (e.g. `NodeList`) and confusion when reconstructing annotable nodes. This time I managed to come up with a simpler and more complete implementation supporting variadic arguments for both function annotations via `@annotated`, variadic arguments for `Annotable` using `rlz.varargs()` and `rlz.varkwds()`.

feat(common): add support for variadic positional and variadic keyword annotations

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/tests/snapshots/test_generic/test_many_subqueries/snowflake/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/bigquery/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/clickhouse/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/duckdb/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/impala/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/mssql/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/mysql/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/postgres/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/snowflake/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/sqlite/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/trino/out.sql
ibis/backends/tests/test_sql.py
ibis/tests/sql/snapshots/test_sqlalchemy/test_where_uncorrelated_subquery/out.sql

This PR fixes an issue where we failed to compile the entire right-hand-side
expression of a `Contains` operation when the operation was a non-trivial
query.
Fixes #5553.

fix(sqlalchemy): ensure that isin contains full column expression

---

.github/workflows/ibis-backends-cloud.yml

It looks like the imports are now further delayed when calling `write_pandas`, so the call makes it all the way to creating a stage and triggers the error that was previously triggered only by the `pyarrow` run.

ci(snowflake): don't set the random seed for snowflake tests

---

ci/schema/snowflake.sql
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/conftest.py
ibis/backends/snowflake/tests/test_client.py

Adds support for working across databases/schemas to the snowflake backend. Closes #5566.

feat(snowflake): support cross-database table access

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/tests/test_register.py
ibis/backends/tests/test_register.py

This may be too coarse of a method for this.
This is a fix for creating a table or view with the same name as an existing table or view.  This is most likely to occur when using the various `parquet` and `csv` registration features, because we do a lot of `CREATE OR REPLACE VIEW`.
Before this, the ibis table would reflect the schema of the initial registration, but would not update if you try to re-use the same view name for a different file (with a different schema).
Other fixes I tried:
`sa.table(..., extend_existing=True)`
This works if the subsequently registered schema is a superset of the existing schema, but if it's a subset, then you end up with a union of the two registration runs.
Calling `reflect_table`
This is actually already happening, but it refers to the contents of …

fix(sqlalchemy): reflect most recent schema when view is replaced

---

ibis/backends/pandas/client.py
ibis/backends/pandas/execution/arrays.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/selection.py
ibis/backends/tests/test_array.py

~This will not pass the basic unnest test for reasons discussed in #5478~ (this now passes!), but I wanted to share the initial progress. For simpler cases, it worked for me. Also not sure if the changes to `build_df_from_projection` will cause problems.
Closes #5478.

feat(pandas): add unnest support

---

.pre-commit-config.yaml
pyproject.toml

This PR bumps ruff in pre-commit and fixes the resulting issues, mostly by ignoring the new lints.

chore(deps): bump ruff version in pre-commit-config

---

docs/SUMMARY.md
docs/blog/selectors.md
ibis/common/annotations.py
ibis/expr/schema.py
ibis/expr/selectors.py
ibis/expr/types/groupby.py
ibis/expr/types/relations.py
ibis/tests/expr/test_selectors.py
pyproject.toml

This PR adds `dplyr`-style [`across`, `if_any` and `if_all` selectors](https://dplyr.tidyverse.org/reference/across.html).
The goal here is to add the ability to execute table-wide operations, where "table-wide" means some subset of the existing table's columns.
The model is very different from pandas. You can't simply subtract two tables like you can with pandas, because such an operation is not well defined
for two arbitrary relations.
However, it's well within the realm of ibis to make doing operations like normalization and scaling much much more concise.
Check out the blog entry for more details.
Closes #5422.

feat(ux): `across`/`if_any`/`if_all` selectors for whole-table operations

---

ibis/common/annotations.py
ibis/common/grounds.py
ibis/common/tests/test_annotations.py
ibis/common/tests/test_grounds.py
ibis/common/tests/test_validators.py
ibis/common/validators.py
ibis/expr/operations/temporal.py
ibis/expr/tests/test_rules.py

The argument annotation hasn't been holding the passed typehint, just the validator created from it. While experimenting with `egg-smol` I had to create a parallel type system to feed the library with but I didn't want to repeat every definitions. 
In order to do that I needed the actual types, not the validators. In addition to that discovered that we haven't been properly supporting generic type coercions.

feat(common): hold typehint in the annotation objects

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml
.github/workflows/nix.yml
.github/workflows/release.yml
.github/workflows/update-deps.yml

This PR works around https://github.com/cachix/cachix-action/issues/138.

ci: pin nix version to workaround upstream bug

---

.github/workflows/conda-lock.yml
.github/workflows/update-deps.yml

We removed the autorebase action a while ago. This removes the use of it
in CI.

ci: remove use of `autorebase:opt-in` label

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/duckdb/__init__.py
ibis/expr/sql.py

This PR uses the native parquet and csv writing functionality built into duckdb for some nice speedups.

perf(duckdb): faster `to_parquet`/`to_csv` implementations

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_client.py
ibis/tests/benchmarks/test_benchmarks.py
justfile

This PR fixes a performance issue with duckdb insert-from-dataframe. Previously we used the base class implementation which is generic and uses `DataFrame.to_sql` to insert and is very slow compared to using the DuckDB directly.
Fixes #5638.
There's still a little bit of performance left to eek out here, but we're very close to parity with duckdb:
**ibis**:
```
❯ time python /tmp/ddb_ibis.py
...
inserted_rows: 9700000, mem_usage: 0.242 GB, wal_size: 0.000 MB, db_size: 5.779 MB, throughput: 3685.7 krows/s
inserted_rows: 9800000, mem_usage: 0.242 GB, wal_size: 2.403 MB, db_size: 5.779 MB, throughput: 17497.0 krows/s
inserted_rows: 9900000, mem_usage: 0.242 GB, wal_size: 4.807 MB, db_size: 5.779 MB, throughput: 17703.5 krows/s
inserted_rows: 10000000, mem_usage: 0.242 GB, wal_size: 7.210 MB, …
```

perf(duckdb): fix dataframe insertion performance

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_client.py

Initial commit for allowing to create temp table which is a first step towards ` .persist()` https://github.com/ibis-project/ibis/issues/5393 
My current dilemmas -
* Still looking for a way to prove a table is temporary in tests without performing introspection on schemas. my first thought is opening two connections one after the other. not sure how it works with transactions.
* sqlite limits temp tables to temp databases only, I wonder what is the best approach to handle this limitation, one approach can be to transfer the responsibility for that to the end user, or to block this capability all together with a nice error. 
Will be happy for your thoughts.

feat(sql): create temp table

---

docs/install.md

This PR removes the `pip install ibis-framework[spark]` instructions since it is redundant with pyspark.

docs: remove duplicate spark backend in install docs

---

README.md

This PR bumps the 10+ number to 15+ and changes various Apache projects to use their full name.

docs: bump query engine count in README and use project-preferred names

---

ci/schema/postgresql.sql
ibis/backends/postgres/datatypes.py
ibis/backends/postgres/tests/test_string.py

Fixes #5402
The `tsvector` type is a postgres-specific type for fast text search --
this doesn't add support for using any of the specific features
associated with `tsvector` but it will let a user load a table that
contains them, instead of erroring out.

feat(postgres): parse tsvector columns as strings

---

ibis/backends/conftest.py
ibis/backends/tests/test_binary.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_set_ops.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_uuid.py

Hello.
We already have 4 files that have all (or almost all) xfail tests with strict exception validation, but it wasn't enforced so that future changes wouldn't cause regression.
What do you think to force this and then iteratively fix all the other tests? Does it make sense? Does it have value?
CC: @cpcloud

chore: enforce raises in xfail tests

---

.github/workflows/ibis-backends.yml
ibis/backends/conftest.py
ibis/backends/tests/test_client.py

This PR adds xfails and CI back for Python 3.11 on PySpark so that when pyspark 3.4.0 is released we will know. This also lets devs run tests locally without having to attach `not pyspark` to every backend test suite invocation that might pyspark tests.

tests(pyspark): xfail pyspark on python311

---

gen_matrix.py
ibis/backends/conftest.py
ibis/tests/benchmarks/test_benchmarks.py
pyproject.toml

This PR removes the spark plugin alias and associated workarounds and cruft.

chore: remove spark alias to pyspark and associated cruft

---

ibis/backends/conftest.py

This PR fixes an issue where pyspark doctests were marked as xfail but do not actually fail.

test(pyspark): allow doctests to pass

---

flake.lock

This commit picks up the change to remove the `makeSetupHook` warning spam.

chore(deps): bump poetry2nix

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-main-skip-helper.yml
.github/workflows/ibis-main.yml

This PR removes an unnecessary cache key element from the key used to refer to a virtualenv cache in CI. Previously we did this because the action did not store the patch version of Python, resulting in a broken environment.. The action is now encoding this information so we no longer need to do it ourselves.

ci: remove unnecessary Python version in custom venv cache key

---

ibis/backends/polars/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_set_ops.py
ibis/expr/types/relations.py
pyproject.toml

This PR changes the `Table.info` method to be just a regular old expression like everything else.

refactor(ux): return expression from `Table.info`

---

ibis/backends/sqlite/registry.py
ibis/common/graph.py
ibis/expr/analysis.py
ibis/tests/expr/test_analysis.py
ibis/tests/sql/snapshots/test_select_sql/test_filter_predicates/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_incorrect_predicate_pushdown/result.sql
ibis/tests/sql/snapshots/test_select_sql/test_incorrect_predicate_pushdown_with_literal/result.sql
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_select_sql.py

Resolving the following bug:
Before the change:
```py
In [8]: from ibis.interactive import *
In [9]: t = ibis.memtable({"x": [-1, 0, 1]})
In [10]: t.mutate(x=_.x + 1).filter(_.x > 1)
Out[10]:
┏━━━━━━━━━━━━━━━━━━━━━━┓
┃ x                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━┩
│ int64                │
└──────────────────────┘
In [11]: ibis.show_sql(t.mutate(x=_.x + 1).filter(_.x > 1))
SELECT
t0.x + CAST(1 AS SMALLINT) AS x
FROM _ibis_memtable_d692nuec3bmu33xtftptv69rp AS t0
WHERE
t0.x > CAST(1 AS SMALLINT)
```
After the change:
```py
In [4]: ibis.show_sql(t.mutate(x=_.x + 1).filter(_.x > 1))
SELECT
t0.x
FROM (
SELECT
t1.x + CAST(1 AS SMALLINT) AS x
FROM _ibis_memtable_ajp35yxzg6njjurxoh69r0g6d AS t1
) AS t0
WHERE
t0.x > CAST(1 AS SMALLINT)
```

fix(ir): incorrect predicate pushdown

---

ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_projection_fusion_only_peeks_at_immediate_parent/out.sql

Quick follow up to the recent predicate pushdown fix to regenerate some test SQL for the BigQuery backend.

fix(bigquery): regenerate sql for predicate pushdown fix

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/tests/test_client.py
ibis/expr/api.py
ibis/expr/types/relations.py
ibis/util.py

adding `persist()` API to table  expression to solve https://github.com/ibis-project/ibis/issues/5393 
Currently it works for pandas,dask,polars and sqlalchemy backends which support temp tables.
I believe I can make it work for spark with a little bit of tweaking.

feat: Add 'cache' API to table

---

ibis/backends/tests/test_temporal.py

```
$ pytest -m 'bigquery or snowflake' ibis/backends/tests/test_temporal.py --numprocesses auto --dist=loadgroup
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=1661456192
rootdir: /ibis/ibis, configfile: pyproject.toml
plugins: snapshot-0.9.0, xdist-3.1.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, profiling-1.7.0, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0, hypothesis-6.65.2
gw0 …
```

test(backends): fix strict validate exception in test_temporal for cloud backends

---

ibis/backends/conftest.py
ibis/backends/tests/test_column.py

```
$ pytest -m 'bigquery or dask or datafusion or pandas or polars or snowflake' ibis/backends/tests/test_column.py
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=1769460373
rootdir: /ibis/ibis, configfile: pyproject.toml
plugins: snapshot-0.9.0, xdist-3.1.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, profiling-1.7.0, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0, hypothesis-6.65.2 …
```

test(backends): strict validate exception in test_column

---

ibis/backends/druid/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/trino/__init__.py

This PR changes all SQLAlchemy engines to use the [`StaticPool`](https://docs.sqlalchemy.org/en/20/core/pooling.html#sqlalchemy.pool.StaticPool) connection pool.
`StaticPool` uses one connection for all operations.
The reason this is desirable--and necessary if we ever want to have predictably
accessible `TEMP` tables--is that we don't want a new connection created from the connection pool
to appear to discard the state associated with a user's session. It doesn't actually do that, but the new connection lacks any session-specific state from the previous one.
It's not clear to me what the downsides are here except perhaps that a use case
where ibis is part of a server application that fields a large number of
concurrent requests can be bottlenecked by any long running queries.

fix(ir): use static connection pooling to prevent dropping temporary state

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/dask/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_client.py
ibis/expr/api.py
ibis/expr/types/relations.py
ibis/util.py

This PR reverts the revert of the `cache()` PR and adds a second commit that fixes the snowflake backend implementation.

fix(snowflake): bring back `cache` and always quote column names in expressions

---

ibis/backends/base/sql/compiler/base.py
ibis/tests/sql/snapshots/test_compiler/test_difference_project_column/out.sql
ibis/tests/sql/snapshots/test_compiler/test_intersect_project_column/out.sql
ibis/tests/sql/snapshots/test_compiler/test_table_difference/out.sql
ibis/tests/sql/snapshots/test_compiler/test_table_intersect/out.sql
ibis/tests/sql/snapshots/test_compiler/test_union/out.sql
ibis/tests/sql/snapshots/test_compiler/test_union_order_by/decompiled.py
ibis/tests/sql/snapshots/test_compiler/test_union_order_by/out.sql
ibis/tests/sql/snapshots/test_compiler/test_union_project_column/out.sql
ibis/tests/sql/test_compiler.py

This PR address an issue with generating invalid SQL when a projection of a set operation contains sort keys. I addressed this by simply treating subqueries of a union as extractable so they become CTEs in the output.
Fixes #5696.

fix(sql): make set operations produce valid sql in the presence of sort keys

---

ibis/common/typing.py
ibis/expr/api.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR implements casting columns of a table per #5610. Closes #5610.

feat(tables): cast table using schema

---

docs/backends/index.md

This PR adds the druid backend to the backends index page, and also sorts the backends in the index by name.

docs: add druid to the backends index docs page

---

ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/tests/test_ddl.py

A grep for this shows it only appears in these
two places, and it's a private method so
it shouldn't be used by anyone.

chore: remove unused _create_table_or_temp_view_from_csv()

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/impala/tests/test_ddl.py
ibis/backends/pandas/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/tests/test_ddl.py
ibis/backends/sqlite/tests/test_client.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_dot_sql.py
ibis/backends/tests/test_map.py

Closes https://github.com/ibis-project/ibis/issues/5693
I didn't add any tests sepcific to this,
because I modified some existing tests so that
they relied on this new behavior, so this new
behavior is getting tested as a side benefit.
The tests are also clearer now because of this.
I did NOT adjust some tests that I thought would
more clear to have two separate steps of
creating the table/view and accessing it later.

feat: return Table from `create_table()` and `create_view()`

---

ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/tests/test_ddl.py

Similar to
https://github.com/ibis-project/ibis/pull/5704

refactor(pyspark): remove another private function

---

docs/SUMMARY.md
docs/blog/ibis-to-file.md

This PR adds a sneak peek blog for the to_csv and to_parquet functionality coming in 5.0. As yesterday, due to my ARM setup, I will need a reviewer to check to ensure it looks right on the site.

docs(blog): adds to file sneak peek blog

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_export.py
ibis/expr/types/core.py

Following up on some comments in #5532 
Skipping the doctests that generate output since they don't clean up after themselves, but I've verified that they run.

docs(parquet): add docstring examples for to_parquet incl. partitioning

---

ibis/backends/base/sql/alchemy/query_builder.py

Removes an unused argument in the SQLAlchemy query builder.

chore: remove unused zip argument

---

ibis/backends/tests/test_export.py

Fixes the failing parquet partitioning tests for BigQuery and Snowflake

test(bigquery/snowflake): xfail cloud partitioning tests

---

ibis/backends/clickhouse/tests/test_aggregations.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/pandas/tests/execution/test_operations.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/tests/test_aggregation.py
ibis/expr/types/generic.py
ibis/expr/types/groupby.py
ibis/expr/types/numeric.py
ibis/tests/expr/test_table.py

Deprecate the `summary` API as of 5.0, remove in 6.0. Closes #5676.

depr(api): deprecate `summary` API

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/base/sql/alchemy/__init__.py

Fixes an invalid call to self.table when looking up a cached expression.

fix(cache): do not pass invalid arguments to table method

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/pandas/client.py
ibis/backends/pandas/tests/test_datatypes.py
ibis/backends/pyarrow/datatypes.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/expr/datatypes/value.py
ibis/expr/rules.py
ibis/util.py

This PR allows using a DataFrame wherever an operation accepts a table via `ibis.expr.rules.table`.

feat(api): upcast pandas DataFrames to memtables in `rlz.table` rule

---

flake.nix

Primarily for the ability to test PySpark integration, which is tied to Python 3.10 until PySpark 3.4.

chore(dev-deps): set the default nix environment python version to 3.10

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py

```
$ pytest -m 'snowflake' ibis/backends/tests/ --numprocesses 6 --dist=loadgroup
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=2765027542
rootdir: /ibis/ibis, configfile: pyproject.toml
plugins: snapshot-0.9.0, xdist-3.1.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, profiling-1.7.0, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0, hypothesis-6.65.2
gw0 [871] / gw1 [871] / gw2 [871] …
```

feat(snowflake): implement ops.GroupConcat

---

ibis/backends/postgres/registry.py
ibis/backends/tests/test_aggregation.py

```
$ pytest -m 'snowflake' ibis/backends/tests/test_aggregation.py --numprocesses 6 --dist=loadgroup
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.7, pytest-7.2.1, pluggy-1.0.0
Using --randomly-seed=3146864476
rootdir: /ibis/ibis, configfile: pyproject.toml
plugins: snapshot-0.9.0, xdist-3.1.0, mock-3.10.0, clarity-1.0.1, randomly-3.12.0, profiling-1.7.0, cov-4.0.0, repeat-0.9.1, benchmark-4.0.0, hypothesis-6.65.2
gw0 [112] / gw1 …
```

feat(snowflake): support binary variance reduction with filters

---

.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml

This PR cuts our nix CI jobs for macos down to one. These jobs are good for catching issues on osx, but we only need one of those to do that right now. The other jobs would be useful for caching packages, but I do not think anyone is taking advantage of that at the moment.

ci: include only a single macos nix job

---

mkdocs.yml

Previously we disable this toggle because it did not work with mkdocs-jupyter. This is apparently now working, so I enable it here.

docs: enable light/dark mode toggle in docs

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/conftest.py
ibis/backends/snowflake/tests/test_client.py
ibis/backends/tests/base.py
ibis/backends/tests/test_api.py
ibis/backends/tests/test_array.py
ibis/backends/tests/test_column.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_map.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_sql.py
ibis/backends/tests/test_window.py
ibis/backends/trino/tests/conftest.py

This PR addresses broken snowflake-sqlalchemy behavior that appears to have been stuck in open source limbo
for over three years. Numerous issues related to the snowflake-sqlalchemy dialect's broken quoting behavior exist:
- https://github.com/snowflakedb/snowflake-sqlalchemy/issues/157
- https://github.com/snowflakedb/snowflake-sqlalchemy/issues/276
- https://github.com/snowflakedb/snowflake-sqlalchemy/issues/388
with no obvious traction or clear effort towards addressing them.
So, in this PR I just disable snowflake-sqlalchemy's broken case-guessing and
let snowflake do what it will, and return what it will.

fix(snowflake): ensure that quoting matches snowflake behavior, not sqlalchemy

---

mkdocs.yml

This makes the header the same color for both light and dark themes. It also uses `teal` for the accent color as well. mkdocs-material adjusts this to be a slightly lighter teal, which I think looks better than the previous lime green on both dark & light backgrounds.

docs: use teal for primary & accent colors

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/clickhouse/tests/snapshots/test_functions/test_string_column_substring/out1.sql
ibis/backends/clickhouse/tests/snapshots/test_functions/test_string_column_substring/out2.sql
ibis/backends/mssql/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_string.py

This fixes `substr` to support negative string indices properly (e.g. `t.string_col[-2]`). Fixes #5037.
The current implementation includes a branch for handling the case where the index is a literal (meaning we can avoid using a case statement to branch at runtime), and a fallback for using a case statement to branch at runtime. I've tested that this logic is valid (and included a kinda weird test for it here). However, we currently have expr-level checks that basically mandate that string indexes are literal ints only (can't do `t.string_col[t.int_col]`), so this extra complication is unlikely to be hit by users as is. I haven't taken steps to relax these checks here, but I suppose that could also be done.

fix: support negative string indices

---

ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_substring/out.sql

Fix the generated SQL for bigquery negative string indexing

fix(bigquery): regenerate negative string index sql snapshots

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/dask/tests/test_client.py
ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/mssql/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/pandas/tests/test_client.py
ibis/backends/polars/__init__.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/tests/test_ddl.py
ibis/backends/snowflake/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_map.py
ibis/tests/expr/mocks.py
ibis/tests/sql/test_sqlalchemy.py
poetry.lock
pyproject.toml

This PR address recent issues created around DDL.
Notes
- I didn't deprecate `ImpalaTable.load_data`. I'm not entirely what should be done with it.
- For clickhouse's `create_table`, since clickhouse itself doesn't have a default
table engine, I preserved that: you have to pass `engine="Something"` to its
create_table. It breaks the uniformity, but I'm not sure how else to handle
it.
TODO
- Implement `create_view` for pandas/dask/polars
- Implement `create_view`/`drop_table`/`truncate_table` for clickhouse
- Review/implement `truncate_table` (I don't think these makes sense for the in-memory backends, so those'll raise an exception)
Closes #5394
Closes #5392
Closes #5390
Closes #4316
Closes #2339

feat(api): make create_table uniform

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/tests/test_window.py

This PR is a small fix to enable a few backend implementations of cumulative `notany`/`notall`. The SQL generated is accepted by the backend but we were hitting an inconsistency in SQLAlchemy that prevented the SQL from ever getting to the backend.

fix(trino,duckdb,postgres): make cumulative `notany`/`notall` aggregations work

---

ibis/backends/snowflake/__init__.py

This allows for example the specifying of a private key.
See example on https://github.com/snowflakedb/snowflake-sqlalchemy.

Add optional 'connect_args' to Snowflake connection method

---

poetry-overrides.nix

This is a temporary workaround to get our docs anchor links working. We can remove it once a new version of mkdocs-jupyter is released.
Closes #5776.

docs: patch docs build to fix anchor links

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/pandas/client.py
ibis/backends/pyarrow/__init__.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_array.py
ibis/backends/tests/test_generic.py
ibis/expr/api.py
ibis/expr/operations/relations.py
ibis/util.py

This PR adds support to `ibis.memtable` for pyarrow Table objects. Closes #5782.

feat(api): implement pyarrow memtables

---

ibis/backends/base/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/tests/test_client.py
ibis/common/caching.py
ibis/tests/expr/mocks.py

This PR is a follow up to #5699 to refactor the query cache out into a separate class for easier maintenance and code clarity.

refactor(cache): pull out ref counted cache into a separate class

---

ibis/backends/sqlite/registry.py
ibis/backends/sqlite/udf.py
ibis/backends/tests/test_aggregation.py

This PR adds support for `ops.Arbitrary` to the SQLite backend.
The motivation for this is to support the upcoming [additional arguments to `Table.distinct()`](https://github.com/ibis-project/ibis/pull/5769).

feat(sqlite): implement `ops.Arbitrary`

---

ibis/backends/tests/test_client.py

This PR fixes an issue with snowflake testing where the exception raised is incorrect.

test(snowflake): catch the right error when accessing tables in view test

---

ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_export.py

This PR implements native `to_pyarrow` and `to_pyarrow_batches` methods for the snowflake backend.

feat(snowflake): native pyarrow support

---

ibis/backends/clickhouse/compiler/relations.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR expands our existing `distinct` method to support row deduplication based on a subset of columns.
Closes #5509.

feat(api): expand `distinct` API to support dropping duplicates based on a column subset

---

ibis/backends/tests/snapshots/test_string/test_rlike/snowflake/out.sql
ibis/backends/tests/test_string.py

This PR fixes a failing snowflake test that is sensitive to the database and schema used for testing.

test(snowflake): skip local test of schema-dependent database

---

.github/workflows/nix.yml
flake.lock
flake.nix
nix/overlay.nix

This PR reverts two `poetry2nix` bumps that upgrade our poetry version to 1.4.1
and break lockfile parsing because of an issue in poetry2nix itself.
See https://github.com/nix-community/poetry2nix/pull/1082 for details.

build: revert poetry version in nix setup and enforce it

---

ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/tests/test_array.py
ibis/backends/tests/test_array.py

This PR adds `ops.ArrayFilter` support to pyspark backend. 
Both Ibis and PySpark use lambdas as a way to provide a predicate, so there needs to be a function-to-function translation. Function argument resolution looks a bit hacky, but I don't think it could have been done simpler.

feat(pyspark): add ArrayFilter operation

---

ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_array.py

This PR adds support for `ops.ArrayMap` operation in pyspark backend, similar approach to #5825.

feat(pyspark): add ArrayMap operation

---

ibis/backends/pyspark/datatypes.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/pyspark/tests/test_basic.py

This PR adds partial support for Ibis `Interval` types by mapping pyspark `DayTimeIntervalType` to appropriate Ibis types. Only four `DayTimeIntervalType` interval types are supported as part of this PR:
- INTERVAL DAY
- INTERVAL HOUR
- INTERVAL MINUTE
- INTERVAL SECOND
types with several units at once (e.g. `INTERVAL DAY TO HOUR`) still lead to an error, as well as types with a different time unit.
P.S. Spark also has a `YearMonthIntervalType`, but it's not yet exposed in pyspark.

feat(pyspark): add partial support for interval types

---

ibis/backends/conftest.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/tests/test_client.py

This PR moves our duckdb test suite to be based entirely on an in-memory database which lets us run the test suite in parallel. On a 16 core machine I see about a 5.7x speed up versus upstream.

test(duckdb): run tests in parallel using an in-memory database

---

ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_temporal.py

This PR adds support for `ops.DateDiff` in pyspark backend. Wraps the function with the same name in pyspark, but returns `Interval('D')` type instead of an integer.

feat(pyspark): add DateDiff operation

---

.github/workflows/ibis-backends.yml
ci/schema/postgresql.sql
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/postgres/datatypes.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/pyarrow/datatypes.py
ibis/expr/datatypes/core.py
ibis/expr/types/generic.py
poetry.lock
pyproject.toml

This PR unifies handling of unknown types into a single `Unknown` type and
corresponding expression classes. These are user facing, but have extremely limited value.
The primary use case is to allow people to access known-type column in tables
that contain columns whose type we can't map into ibis. We shouldn't fail in
that case, and this PR addresses that more uniformly. Previously we had
tsvectors returning as strings and vectors returning as null types, which
causes problems when converting these data to arrow objects.
~I factored out the API I think these should have into `MinimalValue` et al base
classes, to allow only accessing valid APIs on expressions with unknown type.~
~The idea is to limit all unknown type operations to only pass through, and to treat
these passed-through …

feat(types): support unknown types in sqlalchemy backends

---

ibis/backends/polars/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/expr/analysis.py
ibis/expr/selectors.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR implements `pivot_wider`, sometimes referred to as just "pivot" in other systems such as SQL.
The fundamental operation here is turning column values into column names.
This cannot be done without computation, to retrieve the new column names by
computing the distinct values of the to-pivot columns.
To that end, to get this information ibis *does* incur the overhead of computing these values.
While this behavior does deviate from other APIs in that it is not fully lazy,
I believe that the ability to express this computation concisely outweighs the
API deviance. There's _some_ precedent from `.cache()` as well which computes immediately.
However, if a user decides that they cannot live with this overhead then
another argument, `names` exists to allow someone to specify the specific …

feat(table): implement `pivot_wider` API

---

ibis/backends/impala/tests/test_udf.py
ibis/expr/datatypes/core.py
ibis/expr/operations/core.py

Previously we had a dependency circle:
- datatypes used ir
- operations used datatypes
- ir used both operations and datatypes
depends on https://github.com/ibis-project/ibis/pull/5848

refactor(datatypes): remove direct `ir` dependency from `datatypes`

---

docs/getting_started.md
docs/index.md

A draft that needs more work, but putting it up so we can iterate on it.
My thought was that we should have a sample DB to download and then connect to, as opposed to using `examples` (just for this, the examples are great)

docs: add a getting started guide

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

BREAKING CHANGE: removed `Table.sort_by()` and `Table.groupby()`, use `.order_by()` and `.group_by()` respectively

refactor(api): remove deprecated `Table.sort_by()` and `Table.groupby()` methods

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This adds support for passing a format string to `Table.relabel`, to allow relabeling all columns with a particular format. This is most useful for adding a common prefix or suffix, possibly before forwarding to a `join` call.

feat(api): support passing a format string to `Table.relabel`

---

.github/workflows/conda-lock.yml

This PR constrains mamba to a version that works for me to generate lock files. The current version running in CI seems to be broken.

ci: constrain mamba because later versions are broken

---

.github/workflows/nix.yml

Avoid build the nix macos devShell so that CI finishes faster. Right now the job is building duckdb, and it is not clear that anyone is using the nix setup for macos. The devShell step is intended to populate the environment cache, so we do not need it for macos, but we should keep the previous test step so that we have some coverage of macos.

ci: avoid building macos nix devShell

---

ibis/backends/duckdb/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/sqlite/__init__.py

feat(sql): move to temporary views for `con.read_x` APIs to avoid view proliferation

---

ibis/backends/conftest.py
ibis/backends/tests/test_client.py

Prior to this PR, we were not successfully cleaning up temporary tables from testing.

test(snowflake): ensure that tables are always cleaned up

---

docker-compose.yml

This PR reduces the minimum amount of time spent waiting for containers to boot by reducing the amount of time between successive health checks, allowing containers that boot quickly to satisfy the health check earlier than they currently are.

ci: reduce the minimum amount of time spent waiting for containers to start

---

ibis/backends/duckdb/__init__.py
ibis/backends/trino/__init__.py

This PR removes a small amount of dead code.

refactor(sqlalchemy): remove unused `_meta` instance attributes

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/snowflake/__init__.py
ibis/backends/tests/snapshots/test_generic/test_many_subqueries/snowflake/out.sql
ibis/backends/tests/snapshots/test_sql/test_cte_refs_in_topo_order/snowflake/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/snowflake/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/snowflake/out.sql

This PR fixes an issue where we were not threading the quoting parameters through to the various places where ephemeral tables are being created. This manifests mostly in the snowflake backend due to broken quoting behavior in `snowflake-sqlalchemy`.

fix(snowflake): make sure ephemeral tables following backend quoting rules

---

.github/workflows/ibis-backends.yml
ibis/backends/conftest.py

The issue is that pyspark does not always hit the code path that causes it to break with numpy 1.24, so here I just skip pyspark tests if numpy >= 1.24 is installed.

ci(pyspark): fix numpy 1.24 ci

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/datatypes.py
ibis/backends/trino/registry.py
ibis/expr/types/relations.py

Fixes #5855.
This PR fixes an issue caused by the difference in behavior between multiple
unnest calls in a projection.
In the duckdb and postgres backends
```
t.select(t.x.unnest(), t.y.unnest())
```
is analogous to Python's zip, and will perform a pairwise unnest.
In the snowflake and trino backends, we desugar that into a series of cross joins
which generates the Cartesian product of the unnest calls.
This PR doesn't take a position on that, but fixes `pivot_longer` to have the
desired pairwise behavior regardless of backend.
We **do** need to address the difference in behavior I mention, but that should
be done in 6.0.
I created https://github.com/ibis-project/ibis/issues/5913 to discuss options.

fix(sql): generate consistent `pivot_longer` semantics in the presence of multiple `unnest`s

---

.github/workflows/conda-lock.yml

chore: remove unused comment step in `condalock_push` CI job

---

docs/ibis-for-sql-programmers.ipynb
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/clickhouse/tests/test_operators.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/dask/tests/execution/test_arrays.py
ibis/backends/impala/client.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/impala/tests/test_sql.py
ibis/backends/impala/tests/test_window.py
ibis/backends/pandas/tests/execution/test_arrays.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/tests/test_array.py
ibis/backends/sqlite/tests/test_functions.py
ibis/expr/analysis.py
ibis/expr/operations/relations.py
ibis/expr/types/groupby.py
ibis/tests/expr/test_analysis.py
ibis/tests/expr/test_table.py
ibis/tests/expr/test_window_frames.py
ibis/tests/sql/conftest.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_select_sql.py
ibis/tests/sql/test_sqlalchemy.py
mkdocs.yml

Remove internal use of `.projection` in favor of `.select`. `.projection` has been around forever, so I do not think we should ever deprecate it, but making it mostly invisible should serve the purpose of emphasizing select instead.

refactor(api): remove explicit use of `.projection` in favor of the shorter `.select`

---

ibis/backends/impala/tests/test_exprs.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

depr(api): deprecate `Table.set_column` in favor of `Table.mutate`

---

ibis/backends/duckdb/__init__.py

I just spent the last 30 minutes debugging why a query would succeed in the duckdb CLI, but fail in ibis - ended up tracking the issue down to the use of the parallel csv reader.
For now I'm removing the use of this option by default. If needed, users can always manually reenable it. We also heard from the duckdb team that this option will be going away next release anyway.

fix(duckdb): drop use of experimental parallel csv reader

---

.github/workflows/ibis-backends.yml

These seem to be a source of flakiness

ci(pyspark): disable parallel test runs

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/compiler/relations.py
ibis/backends/clickhouse/tests/snapshots/test_select/test_complex_array_expr_projection/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_isin_notin_in_select/out1.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_isin_notin_in_select/out2.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_isnull_case_expr_rewrite_failure/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_join_self_reference/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_physical_table_reference_translate/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_self_reference_simple/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-any_inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-any_left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-any_inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-any_left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_scalar_aggregates/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_table_column_unbox/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_timestamp_extract_field/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_where_simple_comparisons/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_where_with_between/out.sql
ibis/backends/clickhouse/tests/test_client.py
ibis/backends/tests/snapshots/test_string/test_rlike/clickhouse/out.sql

This PR fixes a number of issues with the ClickHouse backend's new-in-5.0
`create_table` method.
1. Usage of `pd` without importing it. This is fixed by changing the
`isinstance` to check for objects that aren't expressions.
1. CTAS (create-table-as-select queries) had the `SELECT` query in the wrong position
1. Temporary tables don't work due to their lack of persistence across cursor instances. I think this is a bug in how ibis is using `clickhouse_driver`. For now, I'm going to disable `temp=True` until we can figure out what's going on there.
1. `truncate_table` was also broken, since clickhouse requires a predicate for `DELETE FROM`, which we were using to implement `truncate_table`. However, ClickHouse supports `TRUNCATE TABLE`, so I switched to that.
Closes #5937.

fix(clickhouse): fix `create_table` implementation

---

poetry.lock
pyproject.toml

We use sqlalchemy for its URLs, but the clickhouse extra does not currently include it as a dependency. This PR fixes that.

fix(clickhouse): ensure that clickhouse depends on sqlalchemy for `make_url` usage

---

ibis/conftest.py
ibis/selectors.py

Make our selectors docstring examples actually run with doctests and make them a bit more complete.

docs(selectors): make doctests more complete and actually run them

---

docs/community/contribute/01_environment.md

Most python devs are more familiar with conda than with nix. Since not everyone may notice the tabs in our setup instructions, we move `conda` to be the first tab in the list.

docs: move conda before nix in dev setup instructions

---

ibis/backends/tests/test_client.py

`ibis/backends/tests/test_client.py::test_interactive_repr_max_columns[duckdb-False] ` has been consistently failing for me locally on macOS with alacritty terminal. Rich used the inferred console width.
The following patch resolved the issue for me.

test(ir): fix maximum console width

---

pyproject.toml

A lot of third party dependencies (e.g.
https://github.com/matplotlib/matplotlib/issues/25244) are still using it. Helpful to ignore for now.

test: ignore all DeprecatedWarning calls for pkg_resources.declare_namespace

---

ci/schema/snowflake.sql
ibis/backends/duckdb/registry.py
ibis/backends/tests/test_map.py

fix(duckdb): disable map values and map merge for columns

---

.github/workflows/ibis-backends.yml

This PR ensures that we do not try to look at docker compose logs when no services are running.
Example failure: https://github.com/ibis-project/ibis/actions/runs/4685649902/jobs/8302958023?pr=5990

ci: only show docker compose logs if job requires services

---

poetry.lock
pyproject.toml

We had a contributor run into issues with a very old version of
`prompt_toolkit` (3.0.4, ~3 years old) in the conda-lock files cause
trouble.
This bumps the lower bound of `ipython` (which is the package that pulls
in `prompt_toolkit`) so that we get a less-old version.
I don't think this counts as a breaking change in that it only impacts
dev dependencies.

chore(deps): bump lower bound of ipython in dev dependencies

---

ibis/backends/base/sql/compiler/translator.py
ibis/backends/bigquery/compiler.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/impala/tests/snapshots/test_value_exprs/test_any_all/not_all/out.sql
ibis/backends/impala/tests/snapshots/test_value_exprs/test_any_all/not_any/out.sql
ibis/backends/pandas/execution/generic.py
ibis/backends/postgres/registry.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_window.py
ibis/backends/trino/registry.py

Fixes #5988. There were multiple issues here, but the primary problem was that we needed to thread the `where` argument through to a few places and enable tests for these APIs.

fix(backends): make notany/notall work with the `where` argument

---

docs/community/contribute/01_environment.md

Fixes #5985.
I could go either way on this one, but think something like this is the most we should change. The tabs above are maybe not the most obvious, so reiterating that the code is for a specific platform seems maybe useful.

docs: add platform comment in conda env creation

---

ibis/backends/sqlite/registry.py
ibis/backends/tests/test_temporal.py

A few missing ops to help clean up some of our TPC-H queries.

feat(sqlite): add ops.DateSub, ops.DateAdd, ops.DateDiff

---

ibis/backends/duckdb/registry.py
ibis/expr/types/maps.py
ibis/expr/types/structs.py

Changes included:
* Fixed the docstrings for `ibis.struct` and `ibis.map` to say they create literals *or* columns, instead of just literals.
* Added more specific type hint to `ibis.map`.
* Moved docstrings to use memtable for struct and map, so they are similar to the array doc strings. There are some that I couldn't, such as `Map.values()` and `Map.__add__()` since those operations aren't supported by DuckDB.

docs: improve docstrings for map value and struct value

---

ibis/conftest.py

test(docs): explicitly set column width for doctests

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/druid/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_client.py
ibis/backends/trino/__init__.py
ibis/tests/conftest.py

This PR fixes an issue where we are currently deleting an existing table when
asked to overwrite that table, before executing an expression that may depend
on that table.
The solution is a bit complex, but is robust and takes advantage of `CREATE OR REPLACE` syntax
in backends that support it.
The way the backends that don't support `CREATE OR REPLACE` work is that they:
1. create a temporary table with the input expression's data
1. recreate the target table
1. insert the temp table's data into the target table
1. drop the temp table
Fixes #6014.

fix(sql): ensure that overwrite is valid when clobbering an existing table

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/pyarrow/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/datatypes.py
ibis/backends/snowflake/tests/test_client.py

Fixes the failing Snowflake backend tests against `master`.
Originally, I implemented just the quoting fixes, but this turned out to expose
some annoyances with quoting in `write_pandas` that were a pain to workaround.
`write_pandas` is overkill for our needs, so I went ahead implemented similar
functionality directly in the Snowflake backend's `_register_in_memory_table`
method. The result is relatively easy to understand compared to what is going
on in `write_pandas`.
It also turned out that we can use this code path regardless of whether a
version of PyArrow is installed that is compatible with bringing back results
from Snowflake in pandas/arrow format. This is because we're only using pyarrow
to write parquet

fix(snowflake): always use pyarrow for memtables

---

ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
pyproject.toml

This PR moves a not-so-useful warning to a more informative error message. Previously this would be a `KeyError`.
xref: #6038

chore(windows): move warning to error on locale-specific format string usage

---

ibis/backends/duckdb/__init__.py
ibis/examples/tests/test_examples.py

This PR changes the default value of `header` to be `True` for the DuckDB
backend's `read_csv` API.

feat(duckdb): set `header=True` by default

---

ibis/common/annotations.py
ibis/common/caching.py
ibis/common/collections.py
ibis/common/grounds.py
ibis/common/patterns.py
ibis/common/tests/test_collections.py
ibis/common/tests/test_patterns.py
ibis/common/tests/test_typing.py
ibis/common/typing.py
ibis/common/validators.py

Converted the previous validator system into a pattern matching system.
The previously used validator system had the following problems:
- Used curried functions which was error prone to missing arguments and was hard to debug.
- Used exceptions for control flow which raising exceptions from the innermost function call giving cryptic error messages.
- While it was similarly composable it was hard to see whether the validator was fully constructed or not.
- We wasn't able traverse the nested validators due to the curried functions.
In addition to those the new approach has the following advantages:
- The pattern matching system is fully composable.
- Not we support syntax sugar for combining patterns using & and |.
- We can capture values at mutiple levels using either `>>` or `@` syntax. …

feat(common): add pattern matchers

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/mysql/tests/test_client.py

Fixes a bug in the sqlalchemy backends where the schema was not prepended to a table in metadata queries. Fixes #6054.

fix(sqlalchemy): ensure that a table's schema is threaded through type inference

---

ibis/backends/impala/__init__.py

Fixes a spurious cast to string in the impala backend. Closes #6052.

fix(impala): do not cast `ca_cert` `None` value to string

---

ibis/common/patterns.py

refactor(common): use an enum as a sentinel value instead of NoMatch class

---

ibis/backends/pandas/execution/window.py
ibis/backends/pandas/tests/execution/test_window.py

In the case of the first function, I chose to implement it with np.repeat as opposed to np.zeros for two reasons:
1. To use the same function as for the last.
2. Using repeat avoids the need for specifying a dtype.
fixes #4918

fix(pandas): solve problem with first and last window function

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/test_client.py

This PR ensures that we only create temp tables from dataframes in snowflake once.

fix(snowflake): ensure that temp tables are only created once

---

ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/tests/test_aggregation.py

Changed the function in `test_interactive_repr_shows_error` from `double_col.approx_median()` to `int_col.convert_base(10, 2)` to keep the error showing.

feat(postgres): add ApproxMedian aggregation

---

ibis/expr/operations/temporal.py

These are leftovers from a previous refactor.

chore(ir): remove unused time unit mappings

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py

After #6081, the Snowflake backend test for `approx_median` is passing, but returns the exact median. This PR changes that API to use the proper approximate version.

feat(snowflake): implement proper approx median

---

ibis/expr/types/maps.py

This is a proposed docstring change, and I am very much open to this PR being rejected.
While working on this: https://github.com/ibis-project/ibis/issues/5982 it took me a bit of time to understand the behaviour of `ibis.map` because there exists an [expr.types.ArrayValue.map](https://ibis-project.org/api/expressions/collections/?h=map#ibis.expr.types.arrays.ArrayValue.map) that has different behaviour.
The [docstring for ibis.map](https://ibis-project.org/api/expressions/top_level/?h=mapscalar#ibis.map) confused me more. Where was the lambda?
Speaking with a colleague, I learned about `mapping` being used as a concept to describe an object where there is a mapping between keys and values: https://docs.python.org/3/glossary.html#term-mapping. I have only been familiar with the functional …

docs: clarify map refers to Python Mapping container

---

.github/workflows/ibis-backends.yml

This PR works around failing CI while we figure out what the issue is with MySQL. For duckdb I opened https://github.com/Mause/duckdb_engine/issues/632.

ci: skip sqlalchemy 2.0.11 to workaround broken ci

---

docs/ibis-for-pandas-users.ipynb
docs/ibis-for-sql-programmers.ipynb

We got a bit of feedback from a user who landed on the Ibis for Pandas
page via a deep link, and then ran into an issue because they tried to
install `ibis` from PyPI.

docs(guides): add brief installation instructions at top of notebooks

---

ibis/backends/clickhouse/compiler/relations.py
ibis/backends/clickhouse/tests/snapshots/test_select/test_complex_array_expr_projection/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_named_from_filter_groupby/out1.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_named_from_filter_groupby/out2.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_table_column_unbox/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_where_with_timestamp/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/clickhouse/out.sql
ibis/backends/tests/snapshots/test_sql/test_union_aliasing/clickhouse/out.sql

Closes: https://github.com/ibis-project/ibis/issues/6101

fix(clickhouse): use named rather than positional group by

---

docs/SUMMARY.md
docs/ibis-for-dplyr-users.ipynb

Addresses https://github.com/ibis-project/ibis/issues/5922.
@fmichonneau and I paired up on https://github.com/ibis-project/ibis/issues/5922 during the recent Ibis doc-a-thon. To keep the work in scope for the doc-a-thon, we decided to start small and base the content on https://dplyr.tidyverse.org/articles/dplyr.html. @fmichonneau brought that content in and developed Ibis equivalents for each bit. I then extended that by adding a section at the top highlighting major differences and also added in joins and pivoting to make it more comprehensive.
@fmichonneau could you take a look, especially at the content I added?
After that, I think it'd be good to get @ianmcook to review and also a core Ibis dev.
Specific bits of feedback I'm interested in are:
- Is the size/scope of this enough? The …

docs: Create Ibis for dplyr users document

---

ibis/backends/bigquery/registry.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_cast_float_to_int/out.sql
ibis/backends/bigquery/tests/unit/test_compiler.py

BREAKING CHANGE: when using the bigquery backend, floats will be truncated instead of rounded to the nearest integer

fix(bigquery): truncate when casting float to int

---

ibis/backends/clickhouse/__init__.py
ibis/backends/dask/tests/conftest.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py

This PR fixes a bug in snowflake where we were not calling `parse_json` when unnesting a struct. I also managed to simplify the flatten implementation by removing our custom flatten sqlalchemy operator entirely.
Fixing this exposed a bug in the clickhouse backend where external tables were being propagated across queries. That is fixed by clearing external tables before discovering them.

fix(snowflake): ensure unnest works for nested struct/object types

---

ibis/backends/snowflake/__init__.py

This PR fixes a bug where the snowflake backend with pyarrow installed incorrectly accesses an attribute on a SQLAlchemy engine object.

fix(snowflake): fix invalid attribute access when using pyarrow

---

docs/ibis-for-dplyr-users.ipynb

docs(guides): update ibis-for-dplyr-users.ipynb with latest

---

ibis/backends/pandas/core.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/selection.py
ibis/backends/pandas/tests/execution/test_operations.py

`Expr` are hashable, introduced in the commit c6fb0c040 
`JSON` is no longer a child from `String`, introduced in the commit 34f389825
pandas now return `float64` columns

refactor(pandas): solve and remove stale TODOs

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/window.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/dask/execution/reductions.py
ibis/backends/duckdb/registry.py
ibis/backends/impala/tests/snapshots/test_analytic_functions/test_analytic_exprs/first/out.sql
ibis/backends/impala/tests/snapshots/test_analytic_functions/test_analytic_exprs/last/out.sql
ibis/backends/impala/tests/test_analytic_functions.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/sqlite/tests/snapshots/test_functions/test_count_on_order_by/out.sql
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/registry.py
ibis/expr/analysis.py
ibis/expr/operations/analytic.py
ibis/expr/operations/reductions.py
ibis/expr/types/generic.py

This PR extends the `first` and `last` methods to operate in a reduction
context, as well as their existing window context.
**BREAKING CHANGE:** All `Column.first()`/`Column.last()` expressions are now reductions and return a single value, where previously they would return the first value replicated over the number of rows of the child table.
Notes:
- Performance likely varies a lot between backends. Some have native first/last
support and some don't. For the ones that don't, I've implemented the
operations as an array agg followed by an array index of the first or last
element. If the query planner isn't smart enough to realize it doesn't
actually need to aggregate the entire array then for large columns we'll see a performance hit.
- To support the reduction API I added a `where` …

feat(api): add first/last reduction APIs

---

ibis/tests/benchmarks/test_benchmarks.py

This PR removes usage of "now"  for date_range calls in benchmarking, which causes the rare but still annoying flaky benchmark run.

ci: avoid `now` in benchmarks

---

ibis/backends/base/sql/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_client.py
ibis/backends/impala/tests/test_ddl.py

This PR tries to address #6128 by more aggressively cleaning up our use of raw_sql internally. Closes #6128.

fix(impala): clean up internal cursor usage

---

ci/schema/oracle/awards_players.ctl
ci/schema/oracle/batting.ctl
ci/schema/oracle/diamonds.ctl
ci/schema/oracle/functional_alltypes.ctl
docker-compose.yml
ibis/backends/clickhouse/tests/conftest.py
ibis/backends/druid/tests/conftest.py
ibis/backends/mssql/tests/conftest.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/oracle/tests/conftest.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/tests/base.py
ibis/backends/trino/tests/conftest.py

Previously I changed our compose services to use a volume mount in an effort to simplify data loading.
While in some ways the result was simplier, data loading became more difficult to understand because a
`git clean -fdx` would remove the mounted files from the containers, and they would start to fail.
The `ServiceSpec` test functionality addresses this by copying the data files
into the running containers at test suite startup.
This has some overhead but not much (it's a local -> local filesystem copy),
and is robust to cleanup of untracked files in the repo.

ci: bring back service spec to relevant backends

---

ibis/backends/pandas/execution/strings.py
ibis/backends/pandas/tests/execution/conftest.py
ibis/backends/pandas/tests/execution/test_strings.py

- use list comprehension in execute_substring_series_series, which is slightly faster and removes the use of the stateful function
- use str.contains in execute_string_like_series_string, which is supported by pandas
- remove the duplicated implementation of EndsWith and StartsWith
fixes #6157

fix(pandas): fix string translate function

---

ibis/backends/bigquery/client.py
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/registry.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/bigquery/tests/unit/test_compiler.py
ibis/backends/bigquery/tests/unit/test_datatypes.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_temporal.py

Fixes #6143 
BREAKING CHANGE:
Before this change, ibis `timestamp` is mapping to Bigquery `TIMESTAMP` type and no timezone supports. However, it's not correct, BigQuery `TIMESTAMP` type should have `UTC` timezone, while `DATETIME` type is the no timezone version. Hence, this change is breaking the ibis `timestamp` mapping to BigQuery:
- If ibis `timestamp` has the `UTC` timezone, will map to BigQuery `TIMESTAMP` type 
- If ibis `timestamp` has no timezone, will map to BigQuery `DATETIME` type

fix(bigquery): bigquery timestamp and datetime dtypes

---

ci/schema/postgresql.sql
ibis/backends/postgres/tests/test_client.py

This PR moves the two special types we test in postgres to their own view, to avoid polluting the `awards_players` table.

test(postgres): move special types to their own view

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/sqlite/tests/test_functions.py

This PR fixes a small bug where the names of columns generated for a `union_all`-style memtable did not match the memtable schema.

fix(sqlalchemy): ensure that union_all-generated memtables use the correct column names

---

ibis/backends/mysql/registry.py
ibis/backends/tests/test_binary.py

Fixes binary literals for the MySQL backend. Discovered in #6179. Split out here for ease of review.

fix(mysql): fix binary literals

---

ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/expr/operations/relations.py

This PR allows use of more complex join predicates in the pyspark backend.

fix(pyspark): enable joining on columns with different names as well as complex predicates

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/literal.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/mysql/datatypes.py
ibis/backends/mysql/registry.py
ibis/backends/mysql/tests/test_client.py
ibis/backends/postgres/registry.py
ibis/backends/pyarrow/datatypes.py
ibis/expr/datatypes/cast.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/parse.py
ibis/expr/datatypes/tests/test_core.py
ibis/expr/datatypes/tests/test_value.py
ibis/expr/datatypes/value.py
ibis/expr/operations/logical.py
ibis/expr/rules.py
ibis/tests/expr/test_value_exprs.py
ibis/tests/strategies.py
ibis/tests/test_strategies.py

BREAKING CHANGE: `dt.Set` is now an alias for `dt.Array`

refactor(datatypes): remove `Set()` in favor of `Array()` datatype

---

ibis/backends/tests/test_array.py
ibis/backends/trino/__init__.py

Fixes an issue with trino array types where we were not inferring the number of dimensions

fix(trino): ensure that nested array types are inferred correctly

---

ibis/backends/tests/test_temporal.py
ibis/expr/operations/temporal.py
ibis/expr/rules.py
ibis/tests/expr/test_temporal.py

Inspired by pandas [resolution_string](https://github.com/pandas-dev/pandas/blob/e19ceb76a4c5903469fea93040c174633c84b9b9/pandas/_libs/tslibs/timedeltas.pyx#L1383)
fixes #6139

fix(core): interval resolution should upcast to smallest unit

---

poetry.lock
pyproject.toml

The recent `poetry-core` release dropped support for `|` constraints, which from the docs appears to have never been explicitly supported. Since `shapely` 2.0 has been out for a while now, we just drop support the `|` constraint entirely.

chore(deps): drop invalid `|` constraint on shapely in `pyproject.toml`

---

ibis/backends/polars/compiler.py
ibis/backends/polars/datatypes.py
ibis/backends/polars/tests/test_datatypes.py

The new convention for datatype conversions is to have two simple functions:
- `dtype_from_<target>(typ, nullable=True)`
- `dtype_to_<target>(dtype)`

refactor(polars): align datatype conversion functions with the new convention

---

ibis/backends/bigquery/registry.py
ibis/backends/tests/test_temporal.py

Fixes the recently introduced bigquery build error: https://github.com/ibis-project/ibis/actions/runs/4982484931/jobs/8918214842

fix(bigquery): raise `OperationNotDefinedError` for `IntervalAdd` and `IntervalSubtract`

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_generic.py

xref #6148 
This is a DuckDB-specific fix, and I'm not entirely certain it's without side-effects, but I like this:
```python
[ins] In [1]: import ibis
[ins] In [2]: ibis.literal(None, type="string").execute() is None
Out[2]: True
[ins] In [3]: ibis.literal(None, type="float").execute()
Out[3]: nan
```
much more than this:
```python
[ins] In [1]: import ibis
[ins] In [2]: ibis.literal(None, type="string").execute()
Out[2]: nan
[ins] In [3]: ibis.literal(None, type="float").execute()
Out[3]: nan
```
Note that `is_null` is a pre-populated attribute, so I think this is a fairly cheap check to perform, and it has the benefit of fixing a broken test.

fix(duckdb): better types for null literals

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/datafusion/tests/conftest.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_array.py
ibis/backends/trino/datatypes.py
ibis/backends/trino/registry.py
ibis/expr/operations/arrays.py
ibis/expr/types/arrays.py

This PR implements a `.zip` method for array expressions and adds implementations for:
* clickhouse
* pyspark
* trino

feat(api): add array zip method and implementations

---

ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py

fix(duckdb): ensure that quoted struct field names work

---

ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/client.py
ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/datatypes.py
ibis/backends/pyspark/tests/test_basic.py

The new convention for datatype conversions is to have to simple functions:
- `dtype_from_<target>(typ, nullable=True)`
- `dtype_to_<target>(dtype)`
depends on #6184

refactor(pyspark): align datatype conversion functions with the new convention

---

ibis/common/temporal.py
ibis/expr/api.py
ibis/expr/tests/test_api.py
ibis/expr/types/core.py
ibis/tests/expr/test_timestamp.py
ibis/tests/expr/test_value_exprs.py

Prefer using simpler functions over dispatched ones with just a few branches.

refactor(api): consolidate `ibis.date()`, `ibis.time()` and `ibis.timestamp()` functions

---

.github/workflows/ibis-docs-lint.yml

It looks like our benchmarks have not been visible since we removed versioned docs. This PR brings them back.

ci: make sure benchmark data are included in the mkdocs commit

---

ibis/expr/operations/relations.py
ibis/tests/expr/test_table.py

Sometimes a renaming scheme with `lname`/`rname` can result in name collisions even after renaming. Previously the default `IntegrityError` was raised informing the user. We now detect the collisions in the join code itself, and raise a more helpful error message.
Fixes #5953.

feat(api): raise better error on column name collision in joins

---

poetry-overrides.nix

Deletes some dead poetry2nix code.

build: remove no longer necessary pydruid poetry2nix override

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/trino/__init__.py
poetry.lock
pyproject.toml

This PR speeds up connecting to backends where `sqlalchemy.inspect` executes a
significant amount of code/traverses the network.
Snowflake is one such backend.
Before:
```
In [1]: from ibis.interactive import *
In [2]: import os
In [3]: %time con = ibis.connect(os.environ["SNOWFLAKE_URL"])
CPU times: user 574 ms, sys: 56.6 ms, total: 630 ms
Wall time: 1.88 s
```
After:
```
In [1]: from ibis.interactive import *
In [2]: import os
In [3]: %time con = ibis.connect(os.environ["SNOWFLAKE_URL"])
CPU times: user 475 ms, sys: 36.9 ms, total: 512 ms
Wall time: 514 ms
```

perf(sqlalchemy): lazily construct the inspector object

---

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_map.py
ibis/expr/types/maps.py

Expands support for map operations that landed in DuckDB 0.8.0.

feat(duckdb): expand map support to `.values()` and map concatenation

---

ibis/tests/expr/test_format.py

Small PR to add missing test coverage for `DummyTable` repring.

test(repr): add test for `DummyTable` repr

---

docs/community/contribute/01_environment.md

This is no longer needed with the builtin `docker compose` command.

docs: drop `docker-compose` install for conda dev env setup

---

.github/workflows/ibis-backends.yml

The backend tests do a `pip install` to update deps after the lockfile is installed. Debugging how this changes the installed deps can be tricky, so we add a `pip list` afterwards to show what's actually installed.

chore(ci): list installed deps in backend tests

---

ibis/tests/expr/conftest.py
ibis/tests/expr/test_interactive.py
ibis/tests/expr/test_visualize.py

Previously these tests would fail if `graphviz` or the corresponding CLI weren't installed.

test(graphviz): make graphviz CLI optional for tests

---

ibis/backends/base/sql/compiler/translator.py
ibis/backends/base/sql/registry/window.py
ibis/backends/bigquery/compiler.py
ibis/backends/impala/compiler.py
ibis/backends/tests/test_aggregation.py

This "just worked" once I removed `ops.GroupConcat` from the list of
unsupported reductions in the base sql window registry.
Fixes #6272

feat(bigquery): enable group_concat over windows

---

ibis/expr/api.py
ibis/expr/datatypes/cast.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/parse.py
ibis/expr/datatypes/tests/test_cast.py
ibis/expr/datatypes/tests/test_core.py
ibis/expr/datatypes/tests/test_parse.py
ibis/expr/operations/temporal.py
ibis/tests/expr/test_temporal.py
ibis/tests/expr/test_window_frames.py
ibis/tests/strategies.py

none of the backends support the definition of the underlying phyisical type
BREAKING CHANGE: `dt.Interval.value_type` attribute is removed

refactor(datatypes): remove `value_type` parametrization of the `Interval` datatype

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_string.py

Fixes the incorrect usage of [`REGEXP_SUBSTR`](https://docs.snowflake.com/en/sql-reference/functions/regexp_substr).

fix(snowflake): fix incorrect arguments to snowflake regexp_substr

---

ibis/backends/pandas/__init__.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_examples.py
ibis/examples/__init__.py
ibis/examples/tests/test_examples.py
ibis/expr/api.py
ibis/expr/types/relations.py

This changes the loading of examples data to use `pyarrow.csv`/`pyarrow.parquet` to read the local data files, and `Backend.create_table(..., temp=True)` to create a table in the backend with this data for *most* backends. This lets our examples data work with most of our backends, making it easier to demo/try out ibis on a specific backend.
Some backends (duckdb & polars) will continue to read from the source files directly. We do this because these backends are local *and* support creating tables from views of source files (avoiding the need to store the data in memory). Since we have a few larger example datasets (e.g. IMDB) we want to use the `read_csv`/`read_parquet` methods for these backends to reduce memory usage, and make working with these larger example datasets smoother.

feat(api): use `create_table` to load example data

---

docs/index.md
mkdocs.yml

- update copyright notice to 2023
- add period for consistency
This PR makes very minor edits on the homepage to update the copyright year and add a period at the end of a sentence in the bullet points for consistency
I'm not sure if there's a way to automatically use the current year in the `mkdocs.yml`?

docs: update copyright year and add a period (minor docs nits)

---

ibis/backends/snowflake/registry.py
ibis/backends/snowflake/tests/test_client.py

Partially addresses #6292 by using the correct syntax for timezone conversion.

fix(snowflake): use `convert_timezone` for timezone conversion instead of invalid postgres `AT TIME ZONE` syntax

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/client.py
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/registry.py
ibis/backends/bigquery/tests/conftest.py
ibis/backends/bigquery/tests/unit/test_datatypes.py
ibis/backends/bigquery/udf/__init__.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_temporal.py

Refactor the bigquery backends to *not* use the overloaded `sch.schema` and `dt.dtype` functions but rather bigquery specific conversion functions.

refactor(bigquery): align datatype conversions with the new convention

---

.github/workflows/assign.yml

workflow is failing for `/take` in comments, e.g.: https://github.com/ibis-project/ibis/actions/runs/5084258325
this simply adds the write issue permission, hopefully fixing
not 100% sure this is the problem

fix: add issue write permission to assign.yml

---

ci/schema/oracle.sql

Oracle 23 has `DROP TABLE IF EXISTS` so using that for our test suite so
we don't get errors on re-runs

chore(oracle): update oracle schema DROP TABLE

---

pyproject.toml

Ignores a new warning from a dependency of `snowflake-connector-python's` vendored requests library

test(snowflake): ignore deprecation warning from old vendored requests

---

ibis/backends/tests/test_client.py

This PR fixes an issue with a ClickHouse backend test that assumes the `ibis_testing` database exists when in fact it might not. Test failure observed in the wild here: https://github.com/ibis-project/ibis/actions/runs/5093340617/jobs/9155829965?pr=6298. There may be similar issues with other backends. We can fix those as they arise.

test(clickhouse): avoid running tests that depend on `ibis_testing` existing

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/conftest.py
ibis/backends/bigquery/tests/system/conftest.py
ibis/backends/bigquery/tests/system/test_connect.py

This allows for fine-grained customization, such as connecting to regional endpoints.
Closes #6288

feat(bigquery): add client and storage_client params to connect

---

ibis/backends/oracle/tests/conftest.py

Now that we are using the `DROP TABLE IF EXISTS` we don't need to catch
the `DROP TABLE`

chore(oracle): remove error suppression from ci data load

---

nix/ibis.nix
pyproject.toml

This should, hopefully, enable more detailed versions when installing from git / github.
Fixes #6346

chore(versioning): use poetry dynamic versioning as build backend

---

docs/backends/BigQuery.md
docs/backends/ClickHouse.md
docs/backends/Datafusion.md
docs/backends/Druid.md
docs/backends/DuckDB.md
docs/backends/MSSQL.md
docs/backends/MySQL.md
docs/backends/Oracle.md
docs/backends/Polars.md
docs/backends/PostgreSQL.md
docs/backends/PySpark.md
docs/backends/SQLite.md
docs/backends/Snowflake.md
docs/backends/Trino.md
docs/backends/badges.md
docs/how_to/duckdb_register.md
docs/stylesheets/code_select.css
mkdocs.yml

xref #5923 
Adding non-templated backend doc pages for Datafusion, DuckDB, Polars, and PySpark.
What do y'all think of having a few badges at the top of each backend page?  I added the ones here for the backends that have some notion of local file support.  It could also get crowded very quickly.

docs(file support): add badge and docstrings for read_* methods

---

nix/overlay.nix

This PR sets the ibis-testing-data commit hash to the specific commit of the `master` branch so that in the future when devs need to checkout a past version of ibis, this derivation is still valid. Without this, if `master` changes, the derivation will produce a different output hash and fail to build.

chore(testing-data): use a specific to allow reliable checkouts in the past

---

docs/backends/BigQuery.md
docs/backends/ClickHouse.md
docs/backends/Datafusion.md
docs/backends/Druid.md
docs/backends/DuckDB.md
docs/backends/MSSQL.md
docs/backends/MySQL.md
docs/backends/Oracle.md
docs/backends/PostgreSQL.md
docs/backends/PySpark.md
docs/backends/SQLite.md

Hi,
I'm not sure if PRs like this are welcome or not, feel free to ignore if not. While installing ibis with a duckdb backend I had an issue using the provided command [here](https://ibis-project.org/backends/DuckDB/): `` pip install 'ibis-framework[duckdb]` ``, the closing tilde is wrong. I found the same in a lot of the other backend documentation, so I changed it for all of them.

docs(backends): fix typo in pip install command

---

flake.nix
nix/ibis.nix
nix/overlay.nix

This PR removes the local rsync-ing of data from the nix store, which was done to allow writing to the data directory which we do not do anymore. Instead of `rsync`, a symlink directly to the nix store is created.

build(nix): replace `rsync` with `ln`

---

ibis/backends/polars/__init__.py
ibis/backends/polars/compiler.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_dot_sql.py

This PR implements `con.sql` and `Table.sql` support for the polars backends. ~A lot of functionality~ subqueries are not implemented yet (and we generate a lot of them), but the various `test_dot_sql.py` tests should start to `XPASS` once support is implemented upstream.

feat(polars): implement `.sql` methods

---

ibis/__init__.py
ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_dot_sql.py
ibis/expr/types/relations.py

This PR adds support for passing SQL with any sqlglot-supported dialect to the `con.sql` and `Table.sql` methods.

feat(sql): allow any SQL dialect accepted by sqlglot in `Table.sql` and `Backend.sql`

---

.github/workflows/ibis-backends-cloud.yml

`name` is never null, so checking it first leads to testing against the same schema, the prevention of which is the whole point of using name/key to specify the schema.

ci(snowflake): check `matrix.backend.key` before `matrix.backend.name`

---

ibis/backends/tests/test_set_ops.py
ibis/expr/api.py
ibis/expr/types/relations.py

Previously it was possible to call: `table.difference|union|intersect()` without any argument which doesn't make sense.

refactor(api): enforce at least one argument for `Table` set operations

---

ibis/backends/dask/execution/join.py
ibis/backends/dask/tests/execution/test_join.py
ibis/backends/pandas/execution/join.py
ibis/backends/pandas/tests/execution/test_join.py

Fixes #6360
In the example in #6360, the columns in the predicates aren't sorted, which
isn't supported by pandas, so the example as written in that issue still won't
work, but it should throw an error that the columns need to be sorted.
I duplicated the test except for the execution in the `dask` backend test suite, which I'm not thrilled with, but this isn't the time to refactor the entire `dask` test suite.

fix(pandas, dask): allow overlapping non-predicate columns in asof join

---

ibis/backends/pandas/execution/join.py
ibis/backends/pandas/tests/execution/test_join.py

Fixes #6080 
`pandas.merge_asof` loses information when any of the grouping or predicate columns share the same name.  It outputs a single column (e.g. `time`) instead of two columns (`time`, `time_right`).
Ibis attempts to recover the now "missing" column, but previously, we were simply creating a copy of the LHS `time` column and then renaming it to be `time_right`.
This behavior also occurred in grouping columns if the names match.
Now, we add default join suffixes to predicates and groups and rename the corresponding columns before the `merge_asof`.
Before:
```python
[ins] In [10]: left_df
Out[10]: 
time  cc_num
0 2023-04-16 09:30:00       1
1 2023-04-16 10:30:00       1
2 2023-04-16 11:30:00       2
3 2023-04-16 12:30:00       3
[ins] In [11]: right_df
Out[11]: 
time  value1  cc_num …
```

fix(pandas): preserve RHS values in asof join when column names collide

---

ibis/backends/tests/test_export.py
ibis/backends/tests/test_temporal.py
ibis/expr/datatypes/tests/test_value.py
ibis/formats/pyarrow.py
ibis/formats/tests/test_pyarrow.py

This PR brings back timestamp scale round tripping, which allows delta timestamp writing, and gives a couple new xpasses from datafusion. Huzzah!

feat(formats): support timestamps in delta output; default to micros for pyarrow conversion

---

ibis/util.py

The objective is to remove the hard numpy dependency from `ibis.util`.

refactor(util): use base64 to compress uuid table names

---

.github/workflows/ibis-backends-cloud.yml
ibis/backends/snowflake/__init__.py

Fixes a bug where we are using Python 3.10-only APIs (the `ignore_cleanup_errors` in the `tempfile.TemporaryDirectory` constructor)

fix(snowflake): fix `tmpdir` construction for python <3.10

---

codecov.yml

codecov patch coverage fails all the time because we don't run all
backends on CI (and lots of other reasons, too), but we don't want to
kill the patch job entirely because we want the coverage annotations.
but codecov won't provide those annotations if you turn off patch
coverage, so instead, we'll make it so loose it will never fail.
xref #5601
xref #4693

chore(ci): set a silly threshold for codecov to avoid spurious failures

---

poetry.lock
pyproject.toml

There is a vulnerability in snowflake-connector-python in versions below v3.0.2: <https://github.com/advisories/GHSA-5w5m-pfw9-c8fp>
I'm not so sure what are the considerations going into this lower pin, so if this isn't viable, feel free to just close. I mainly wanted to bring attention to this vulnerability.

fix(deps): prevent vulnerable snowflake-connector-python versions

---

poetry.lock
pyproject.toml

Looks like deltalake is released at least once a month, and since we are using a small number of APIs in deltalake we should allow users to upgrade to versions that will almost certtainly work without having to cut a new release of ibis to pick up the deltalake version bumps.

chore(deps): allow wider range of `deltalake` versions

---

ibis/backends/bigquery/tests/unit/test_compiler.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_temporal.py

Small PR to remove use of explicit values of `datetime.now` to avoid test flakiness.

test: remove use of specific now comparisons in tests

---

ibis/backends/base/sql/alchemy/geospatial.py

This PR speeds up one of the sources of slow backend module import times without needing to rewrite all imports to the call site or change a lot of existing code.

perf(imports): speed up checking for geospatial support

---

.github/workflows/pre-release.yml

Turns on publishing pre-releases to pypi proper.

ci: publish pre-release dists to pypi

---

ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_export.py

closes #6384
one question is noted in the TODO -- my understanding is for csv and parquet we're using a native datafusion function for de-registering the files from the database, but we can't do that with delta yet?
datafusion has an issue open for native support: https://github.com/apache/arrow-datafusion/issues/2025
also cleaned up a docstring issue I noticed in duckdb

feat: implement read_delta for datafusion

---

.github/renovate.json
poetry.lock
pyproject.toml

This PR partially reverts the specific ruff pin, so that conda has time to catch up and we can still generate conda lock files.

chore(deps): remove ruff pin for conda lock files

---

ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/tests/test_client.py

Avoids failing a test due to temp tables being created by another process in between assertions

test(bigquery): make `list_tables` test using a guaranteed subset of tables

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/polars/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/registry.py
ibis/expr/operations/generic.py
ibis/expr/types/generic.py

closes #6009 
this is an attempt at impelementing try_cast in a few backends. PR needs some feedback, particularly around:
- varying behavior between try_cast (and cast) between backends
- how to test properly
as you can see in the tests, I started branching based off the connection. some of the differences in behavior were unexepected -- for instance, in clickhouse cast seems to behave like try_cast by default (e.g. `ibis.literal("a").cast("date").execute` returns `NaT` of type `pandas._libs.tslibs.nattype.NatType`). also in clickhouse, it seems there is no interval type (see message inline with the test)
some other observed behavior that could be confusing:
<details>
```ipython
[ins] In [2]: import ibis
[ins] In [3]: ibis.set_backend("duckdb")
[ins] In [4]: …
```

feat: implement try_cast for a few backends

---

justfile

chore(dev): remove use of mapfile because macOS ships with a very old version of bash

---

.github/workflows/ibis-backends.yml
ibis/backends/flink/compiler/__init__.py
ibis/backends/flink/compiler/core.py
ibis/backends/flink/registry.py
ibis/backends/flink/tests/snapshots/test_translator/test_translate_count_star/out.sql
ibis/backends/flink/tests/snapshots/test_translator/test_translate_sum/out.sql
ibis/backends/flink/tests/snapshots/test_translator/test_translate_timestamp_from_unix/timestamp_ms/out.sql
ibis/backends/flink/tests/snapshots/test_translator/test_translate_timestamp_from_unix/timestamp_s/out.sql
ibis/backends/flink/tests/test_translator.py
ibis/backends/flink/translator.py
poetry.lock
pyproject.toml

This PR looks to add support for Apache Flink (streaming) in Ibis.
As data grows, developers want to do increasingly sophisticated data science, as well as reduce the end-to-end time to value. There has been an explosion of tools, libraries, and frameworks to democratize the performance and functionality needed to create increasingly complex data systems that address these new data science demands. That said, the combinatorics of tools has forced developers to spend an increasing amount of their time rewriting code or learning new APIs. Building and extending existing standards would ameliorate much of this pain by allowing developers to write code once and use it across a myriad of tools in the data tool chain. Ibis already works with numerous backends for batch analytics, and we want to …

feat(flink): introduce Apache Flink backend

---

nix/overlay.nix

Small PR to reuse the logic in our justfile for relocking files with nix.

chore(dev-deps): dedup nix code for locking dependencies

---

docs/backends/Datafusion.md
docs/backends/DuckDB.md
docs/backends/Polars.md
docs/backends/badges.md
ibis/backends/duckdb/__init__.py

adds the `read_delta` docstrings to the relevant backend docs and add in the badges
minor consistency in DuckDB docstrings with `**kwargs` instead of `kwargs`
~~in the top-level API doc, move `read_delta` to after `read_parquet` for consistency~~

docs: add read_delta and related to backends docs

---

mkdocs.yml

small little quality-of-life change for the docs.  autolinks the type references in API signatures.

docs(intersphinx): add mapping to autolink pyarrow and pandas refs

---

docs/backends/Impala.md
docs/backends/app/backend_info_app.py
docs/example_streamlit_app/example_streamlit_app.py
docs/getting_started.md
docs/how_to/memtable-join.md
docs/how_to/sessionize.md
docs/ibis-for-dplyr-users.ipynb
docs/ibis-for-pandas-users.ipynb
docs/index.md
docs/user_guide/extending/elementwise.ipynb
docs/user_guide/extending/reduction.ipynb
docs/user_guide/self_joins.md

fixes #6445 (at least partially)
ignoring blogs, only looking in `docs/` folder

docs: use to_pandas instead of execute

---

ibis/backends/snowflake/__init__.py

Correcting the spelling of the word "additional" in Snowflake `do_connect` docs. 
```
Additiional ==> Additional
```
This is actually what caught my original attention with https://github.com/ibis-project/ibis/pull/6398 to look into spelling fixes. It seems as if this correction isn't available in codespell's [dictionary](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt).

fix(docs): typo in snowflake do_connect kwargs

---

ibis/backends/tests/test_export.py
ibis/expr/types/relations.py

This PR adds support for the `__dataframe__` interchange protocol. Closes #6343.

feat(api): add `__dataframe__` implementation

---

ibis/backends/bigquery/registry.py
ibis/backends/bigquery/tests/unit/test_compiler.py
ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/postgres/datatypes.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/tests/test_temporal.py
ibis/backends/trino/datatypes.py
ibis/common/temporal.py
ibis/common/tests/test_temporal.py
ibis/common/validators.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/tests/test_cast.py
ibis/expr/datatypes/tests/test_core.py
ibis/expr/datatypes/tests/test_parse.py
ibis/expr/datatypes/tests/test_value.py
ibis/expr/datatypes/value.py
ibis/expr/operations/temporal.py
ibis/expr/types/temporal.py
ibis/formats/tests/test_numpy.py
ibis/tests/expr/test_pretty_repr.py
ibis/tests/expr/test_temporal.py
ibis/util.py

BREAKING CHANGE: `dt.Interval` has no longer a default unit, `dt.interval` is removed
Xpassing tests for:
- Clickhouse
- BigQuery
- Snowflake
- Polars
- Impala
- MySQL
Should resolve https://github.com/ibis-project/ibis/issues/6457

refactor(datatypes): normalize interval values to integers

---

.github/actionlint.yaml
.github/workflows/nix.yml
.pre-commit-config.yaml

Fixes an issue with GitHub changing their macos deployments to include SIP on macos and nix failing to work with that. xref https://github.com/cachix/install-nix-action/issues/183

ci: run nix macos jobs on macos-13 to try and avoid SIP

---

ibis/common/egraph.py

Mypy expects the type to be annotated as `object`.
This will cause an error in the next release due to `__eq__()` being added to Mapping in typeshed:
https://github.com/python/typeshed/pull/10297#issuecomment-1585653511

fix upcoming type error

---

ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/datatypes.py
ibis/backends/sqlite/registry.py
ibis/backends/sqlite/tests/test_types.py

Fixes a flaky sqlite test observed in [this CI run](https://github.com/ibis-project/ibis/actions/runs/5283213529/jobs/9559162456?pr=6456).

test(sqlite): use `ISODATETIME` type for now output to avoid pandas flaky format inference

---

ibis/expr/deferred.py
ibis/expr/tests/test_deferred.py
ibis/expr/types/generic.py

This is a major refactor of the `Deferred` implementation, with the following goals:
- Better repr. The previous repr was just the default python object repr, making it impossible to see what the underlying deferred expression represented. The new repr attempts to mimic the python syntax used to generate the deferred expression.
- Pickleability. The previous expressions weren't pickleable, which prevented using them in place of lambdas for certain workflows. They now are pickleable.
```python
In [1]: from ibis import _
In [2]: _.x.log(1)
Out[2]: _.x.log(1)
In [3]: _.x.log(1) + _.y
Out[3]: (_.x.log(1) + _.y)
```

feat(api): better repr and pickle support for deferred expressions

---

.github/actionlint.yaml
.github/workflows/nix.yml

macOS nix build is fixed by updating cachix-install-action (https://github.com/cachix/install-nix-action/pull/184)

ci: bring back `macos-latest`

---

ibis/selectors.py
ibis/tests/expr/test_selectors.py

Adds conveniences for iterables of strings and single strings in the across selector so that `s.c` is not necessary for simple selections

feat(api): support list of strings and single strings in the `across` selector

---

ibis/backends/polars/compiler.py
ibis/backends/tests/test_generic.py

Added polars support for `identical_to`, and tweaked some `@pytest.mark` designations relating to window functions; polars has support for these, but `ops.WindowFunction` hasn't been implemented yet (I might have a crack at that later), so I moved the label into the more appropriate message.

feat(polars): add support for `identical_to`

---

ibis/backends/polars/__init__.py

Micro-optimisation; no need to eat the frame-construction overhead on `Column` return (except for temporal results, where polars can return py-native datetimes instead of Timestamp).
To illustrate the difference:
```python
from datetime import datetime
import polars as pl
df = pl.DataFrame( {"colx":range(1_000_000)} )
```
_Before_
```python
start = datetime.now()    
for i in range(50):
x = df.to_pandas().iloc[:, 0]
print( datetime.now() - start )
```
_After_
```python
start = datetime.now()        
for i in range(50):
y = df.to_series().to_pandas()
print( datetime.now() - start )
```
While ~20x faster in the above example it's not a lot of "real" time saved, but why not... ;)

feat(polars): lower-latency column return for non-temporal results

---

ibis/backends/polars/__init__.py
ibis/backends/tests/test_register.py

Added support for registering a single table from multiple parquet files (when passed as an iterable of individual paths - It already handles a directory or file path glob).

feat(polars): support table registration from multiple parquet files

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/tests/test_client.py
ibis/backends/pandas/__init__.py
ibis/backends/pandas/tests/test_client.py
ibis/backends/polars/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_client.py
pyproject.toml

Some backends already supported this, but a bunch didn't only because of `isinstance` checks.
The remaining backends that don't have support for pyarrow tables in `create_table` are `dask`, `datafusion`, `druid`, and `impala`.  
I also ran into a big in the bigquery backend, where passing both `obj` and `schema` to `create_table` led to `obj` being ignored entirely.  
Also there's probably some import cost to this, although it should all be inlined and will only hit at the `create_table` call.

feat(create_table): support pyarrow Table in table creation

---

docs/SUMMARY.md
docs/supported_python_versions.md

Adds docs that reference NEP29 to loudly document how we deal with Python versions support.

docs(python-versions): document how we decide to drop support for Python versions

---

ibis/backends/tests/test_export.py

This has (I think) fixed the flaky `mssql` tests on my machine -- I don't think this is a robust solution to the problem, but I'm partially pushing it up to see if CI runs without issue.
xref #6503

test(mssql): add explicit close for record batch reader

---

docker-compose.yml

[Some flaky tests due to dropped connections](https://github.com/ibis-project/ibis/actions/runs/5347300828/jobs/9695717144?pr=6500) are are popping up in the mysql CI suite more often than usual. This PR moves us back to MariaDB 10.11, which is an LTS release and hopefully much less flaky.

ci(mysql): revert the mariadb image version to see if it results in less flaky tests

---

ibis/backends/base/sql/__init__.py
ibis/backends/bigquery/__init__.py
mkdocs.yml

This PR removes the public (and therefore breaking) but likely unused (it is not rendered in the docs) `ast_schema` method in favor of `expr.as_table().schema()`.

refactor(backends): remove `ast_schema` method

---

ibis/backends/tests/test_join.py

As I was replicating logic in `test_join.py` for manual testing of a new backend, I couldn't figure out how the result would be different than vanilla `pd.merge`, because the replacement conditions should never trigger for the respective joins. Tests seem to pass after simplification.

refactor: replace custom `_merge` using `pd.merge`

---

.github/workflows/ibis-backends.yml
ibis/backends/base/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_export.py
ibis/expr/types/core.py

This PR adds a `to_torch` method that returns a dict of column name to torch tensor. This came up during experimentation with DuckDB pyarrow UDFs where I wanted to pass some training data to a model. I am opening this PR to discuss the API, and am not strongly opinionated about whether this should be merged or not. The API copies what DuckDB does and uses its implementation in the DuckDB backend.

feat(io): add `to_torch` API

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_udf.py

This PR adds support for pyarrow UDFs to datafusion using the new UDF API.

feat(datafusion): add support for pyarrow UDFs

---

ibis/backends/conftest.py
ibis/examples/__init__.py
ibis/examples/tests/test_examples.py
poetry.lock
pyproject.toml

This PR addresses recentish test flakiness with examples that are used in both doctests and the `test_examples` test. The solution here is to avoid testing the shared tables in both doctests and `test_examples`. This may seem fragile, but in practice the number of unique example tables used in doctests does not vary much at all. Fixes #6533.

ci(examples): address flakiness in `test_examples`

---

ibis/backends/duckdb/__init__.py

This PR adds support for connecting to motherduck. Not sure if adding a secret just to test motherduck connection is worth it given the small amount of code.
```
In [1]: from ibis.interactive import *
In [2]: con = ibis.duckdb.connect("md:")
In [3]: con.list_tables()
Out[3]: ['tpc_h01_lineitem']
In [4]: con2 = ibis.duckdb.connect("motherduck:")
In [5]: con2.list_tables()
Out[5]: ['tpc_h01_lineitem']
```

feat(duckdb): support motherduck

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

The intent of the change is to add another shorthand in addition to "snake_case" for relabeling. I wanted to add support for "SCREAMING_SNAKE_CASE". Some systems, such as Snowflake, Oracle SQL, and PL/SQL, follow this convention. This would be a worthwhile addition that might help with different backends or databases that treat double-quoted identifiers as case-insensitive.
https://github.com/ibis-project/ibis/pull/6532 was the original PR for this, but it was closed upon resyncing the fork and discarding changes. After the soft reset and force push of accidentally going back too far, I branched off the fork and redid the changes for ALL_CAPS as the table relabeling option on a separate branch.

feat(api): add ALL_CAPS option to Table.relabel

---

ibis/backends/conftest.py
ibis/backends/tests/test_sql.py

This PR removes fixtures that could in rare cases try to simultaneously install extensions. The typical backend-with-data fixtures do not have this problem because we use filelock to prevent concurrent data loading (connecting for tests is contained within that as well). Fixes #6520.

ci(duckdb): remove `backend_nodata`/`con_nodata` to avoid `TestConf()` extension install race condition

---

.github/workflows/ibis-backends.yml
ibis/examples/__init__.py
ibis/examples/tests/test_examples.py

This PR makes sure that examples lock files are created next to the data instead of in `$PWD`.

fix(examples): move lockfile creation to data directory

---

ibis/backends/tests/test_generic.py
ibis/expr/types/relations.py

I ran into this the other day and it seems like a nice convenience to also have a table-level `try_cast` -- I'm happy to add it as a separate method (which is probably better for consistency with the column methods).

feat(cast): add table-level try_cast

---

ibis/backends/base/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/tests/test_export.py

This PR addresses the recent test flakiness seen in the MySQL backend.
The manifestation of the flakiness (dropped connection) was a bit of a red
herring.
The dropped connection was ultimately due to a connection that was
indeterminately closed, usually at some point later during interpreter GC but
not always (leading to the flakiness) because the batch producer for the
`RecordBatchReader` uses a connection in a context manager and it was left open
because of the **failure during the attempt by pyarrow to cast Python
`decimal.Decimal` objects to `float`s**.
The cast itself was the result of SQLAlchemy automatically returning
`decimal.Decimal` objects by default for columns whose type was
`mysql.DOUBLE`/`mysql.FLOAT`. The solution was to prevent that automatic
conversion during table …

fix(mysql): ensure that floats and double do not come back as Python Decimal objects

---

ibis/backends/tests/test_temporal.py

It seems extracting microseconds from a timestamp column using the impala backend can [fail with multiple exception types](https://github.com/ibis-project/ibis/actions/runs/5428150874/jobs/9872172582). This PR adds `HiveServer2Error` to the list of xfail exception types.

test(impala): xfail with additional error type

---

.github/renovate.json

Add labels instead of overwriting them when running renovate.

ci(renovate): add labels instead of overwriting them

---

.github/workflows/ibis-docs-lint.yml
flake.nix
nix/overlay.nix

Adds a CI check for spelling in release notes. This will only check commits that are as-of-the-PR unreleased.

ci: check release notes spelling in ci

---

ibis/backends/datafusion/tests/conftest.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/conftest.py
ibis/backends/tests/base.py
ibis/backends/tests/test_api.py

This PR cleans up a bit of testing code for datafusion and enables multi statement execution for the snowflake backend.

test(snowflake/datafusion): add multi-statement support and move datafusion test tables all to parquet

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_export.py

DataFusion normalizes unquoted identifiers to lowercase. This PR quotes all `TableColumn` references during compilation to avoid normalizing names that are case sensitive.

fix(datafusion): always quote column names to prevent datafusion from normalizing case

---

ibis/expr/sql.py

This makes it easier to immediately pass the output to some other tool for execution.

feat: make output of `to_sql` a proper `str` subclass

---

ibis/backends/mysql/datatypes.py

The recent sqlalchemy 2.0.18 release added reflection support for UUID types for mysql, which broke a test for us.
This also turned up a bug in the type mapping refactor where the `super().to_ibis` call could never be called (which is intended to handle fallback cases like this). That fix should definitely go in.
The `mysql uuid <-> ibis str` type fix here I'm less sure about. Only mysql 2.0.18+ supports properly reflecting these types, and a bit of rudimentary testing seems to indicate that swapping to `mysql uuid <-> ibis uuid` may not fully work yet. I opted for the fix that keeps the same behavior for now.

fix(mysql): fix UUID type reflection for sqlalchemy 2.0.18

---

ibis/backends/duckdb/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/udf.py
ibis/backends/tests/test_udf.py

This PR adds support for scalar Python UDFs to the SQLite backend using the new UDF API.

feat(sqlite): add scalar python UDF support

---

flake.lock
poetry-overrides.nix

Per the FIXMEs in the deleted code, the necessary changes are now upstream in poetry2nix.

chore(dev-deps): remove upstreamed cairocffi poetry2nix overrides

---

flake.nix

Removes some unused nix derivations related to python 3.8 support.

chore(dev-deps): remove ibis38 nix derivation

---

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_string.py

fix(duckdb): use regexp_matches to ensure that matching checks containment instead of a full match

---

ibis/backends/snowflake/registry.py

Fixes regexp search for snowflake.

fix(snowflake): use `regexp_instr > 0` instead of `REGEXP` keyword

---

ibis/backends/mysql/__init__.py

This is in response to saulpw/visidata#1929 in which a mysql user needed to pass a different charset to the mysql backend.

fix(mysql): pass-through kwargs to connect_args

---

docs/backends/pyspark.md

removes "CSV" which isn't actually supported; adds "Delta Lake" for import and export per #6603

docs: update imports/exports for pyspark backend

---

.releaserc.js
ci/release/dry_run.sh
ci/release/run.sh

This is a PR to update the semantic-release-replace-plugin to the [new package](https://www.npmjs.com/package/semantic-release-replace-plugin) from the [deprecated version](https://www.npmjs.com/package/@google/semantic-release-replace-plugin).

chore: update plugin

---

.conventionalcommits.js
.prettierrc.toml

Small PR to set the trailing comma style for JS code to the new `prettier` default.

style(js): set trailing comma style config to new default

---

docs/install.md

This adds install instructions for installing specific backends with `conda` and `mamba`. Previously we only had backend install instructions for `pip`.
I tried putting all this under nested tabs, but I found it harder to read. Splitting `pip` and `conda`/`mamba` into separate sections felt cleaner IMO.

docs: add conda/mamba install instructions for specific backends

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_export.py

We weren't running these hooks before, which meant that a `memtable`
that hadn't been executed yet (via interactive mode or otherwise) would
not be registered with DuckDB at export time.
Fixes #6091 
While I was adding a test, I noticed that the partitioned parquet roundtripping test was comparing the same table to itself.  Made a few tweaks there.

fix(duckdb): run pre-execute-hooks in duckdb before file export

---

ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py

Fixes #6632 
I'm not sure how to test this because I can't figure out why `duckdb_engine` sometimes gives us a `UInt8` vs a `UTinyInteger`.
@NickCrews -- this should fix up the issue you were running into.  Thanks for providing the "problem" parquet file!

fix(duckdb): handle conversion from duckdb_engine unsigned int aliases

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/tests/test_dot_sql.py
ibis/backends/trino/__init__.py

This PR implements support for `.sql` on the Trino backend.

feat(trino): implement support for `.sql`

---

ibis/backends/tests/test_join.py
ibis/expr/types/relations.py

This PR fixes an issue where we were not treating `how="semi"` and `how="left_semi"` the same WRT deduplicating columns.

fix(exprs): ensure that `how="left_semi"` and `how="semi"` are equivalent

---

ibis/backends/clickhouse/compiler/values.py

Works around broken sqlglot version that cannot compile XOR for clickhouse.
Upstream bug report: https://github.com/tobymao/sqlglot/issues/1936

chore(clickhouse): workaround broken sqlglot

---

ibis/backends/dask/execution/util.py
ibis/backends/pandas/execution/util.py
ibis/backends/tests/test_window.py
ibis/expr/builders.py
ibis/expr/operations/sortkeys.py
ibis/tests/expr/test_operations.py
ibis/tests/expr/test_window_frames.py

previously the builder API disallowed passing scalar order keys like ibis.NA and ibis.random()

fix(api): allow scalar window order keys

---

ibis/backends/sqlite/registry.py
ibis/backends/sqlite/udf.py
ibis/backends/tests/test_string.py

This PR adds the following operations to the sqlite backend:
1. ExtractFragment
2. ExtractProtocol
3. ExtractAuthority
4. ExtractPath
5. ExtractHost
6. ExtractQuery
7. ExtractUserInfo

feat(sqlite): implement extract url field functions

---

ibis/backends/polars/compiler.py
ibis/backends/tests/test_array.py
ibis/backends/tests/test_generic.py

This PR addresses an issue where the polars backend was not able to handle pivoting on more than one column, due to its `explode()` idiosyncracies, namely that there are some hoops to jump through to get it to do a pairwise unnest. Fixes #5795.
Additionally, this appears to have exposed https://github.com/pola-rs/polars/issues/10017.

fix(polars): ensure that `pivot_longer` works with more than one column

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/tests/test_client.py

The Oracle backend did not survive first contact with real data -- this is a hacky branch to try to resolve.

fix(oracle): add support for oracle LONG types

---

ibis/backends/duckdb/__init__.py

fixes #6671
casts to `str()` before the `captialize()` call

fix(duckdb): cast read_only to string for connection

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_aggregation.py

This PR adds the following functions for the datafusion backend:
- count_distinct
- median
- approx_median
- stddev (pop and sample)
- var (pop and sample)

feat(datafusion): add aggregation functions

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_string.py

This pull request introduces new string functions to the DataFusion backend: 
- re_search
- join
- contains.

feat(datafusion): add RegexSearch, StringContains and StringJoin

---

.github/workflows/ibis-backends.yml
ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/datafusion/__init__.py
ibis/backends/datafusion/compiler.py
ibis/backends/duckdb/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/polars/compiler.py
ibis/backends/polars/tests/conftest.py
ibis/backends/pyspark/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_array.py
ibis/backends/tests/test_export.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/backends/tests/test_temporal.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/formats/pandas.py
ibis/formats/pyarrow.py
poetry.lock
pyproject.toml

This PR removes our ad-hoc `result_handler`-based shape reconciliation (Table
-> DataFrame | PyArrow Table, etc) in favor of two new methods:
* `__pandas_result__`
* `__pyarrow_result__`
each implemented on `ir.Table`, `ir.Column` and `ir.Scalar`. This has the benefit of removing quite a bit
of duplicated handling of expression-shape-to-in-memory-result-shape conversion.

refactor(conversion): replace adhoc result handling with dunder methods specific to the `Expr` subclass

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_numeric.py

This PR adds the following functions to the DataFusion backend:
- sign
- power
- nullifzero
- log

feat(datafusion): add functions sign, power, nullifzero, log

---

.github/workflows/ibis-backends.yml

This PR is a band-aid for https://github.com/pytest-dev/pytest/issues/10874 which seems to only happen on Python 3.11 + Impala + only **some** test runs.

ci(impala): avoid random test ordering on the impala backend

---

docs/tutorial/ibis-for-dplyr-users.ipynb

* Removing the use of the word `method` w.r.t. R generics
* Calling out tidyr in the intro
* Added in a bit more explanation around aggregate function methods
* Added a missing snippet about ibis `order_by` vs. dplyr `arrange`

docs(dplyr): small fixes to the dplyr getting started guide

---

ibis/__init__.py

This catches import errors when loading an ibis backend and raises a nicer error message to the user telling them how they may resolve the issue.
Fixes #6695.

feat: improved error messages when missing backend dependencies

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_client.py

This PR fixes a few issues with `has_operation`:
1. The PySpark backend implementation didn't have a `@classmethod` decorator, so it didn't follow the base class definition and every other backend's implementation.
1. The ClickHouse backend was looking up operands using the mapping that backs the singledispatch registry, so `Backend.has_operation(object)` returned `True`.
Tests are included.

fix(backends): fix pyspark `has_operation` definition; test that `has_operation` doesn't return `True` spuriously

---

docs/backends/app/backend_info_app.py

Add the ability to select a subset of backends in the backend support matrix

docs(backend-matrix): allow selection of a subset of backends in the operations matrix app

---

docs/concept/backends.md
docs/concept/why_ibis.md
docs/how_to/streamlit.md
docs/index.md
docs/tutorial/getting_started.md
docs/tutorial/index.md
mkdocs.yml

This PR fixes some doc build warnings introduced in mkdocs 1.5.0

ci(docs): fix warnings coming from new version of mkdocs

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql
ibis/backends/bigquery/tests/system/snapshots/test_client/test_subquery_scalar_params/out.sql
ibis/backends/bigquery/tests/system/test_client.py

Dear maintainers
This PR is a simple fix to the https://github.com/ibis-project/ibis/issues/6715 opened by myself.  To be detailed it adds a check on the input table name while initing a Bigquery Table object. If the input name is a fully qualified one, it will use it as it is w/o bothering add the connection default proj and dataset.
To simplify the fix, this PR reused the `_full_qualified_name` method and compare its return with the input name to confirm if the input is fully qualified or not.
Please kindly have a review if it is good to fix #6715 
Thanks
Closes #6715.

fix(bigquery): respect the fully qualified table name at the init

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/tests/test_client.py

This PR fills out the remaining options for `create_table`, including support for `overwrite=True`. Closes #6706.

feat(bigquery): fill out `CREATE TABLE` DDL options including support for `overwrite`

---

ibis/expr/sql.py
ibis/tests/expr/test_sql.py

fix(sql): handle aliases when parsing sql into ibis code

---

ibis/backends/conftest.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/duckdb/tests/test_register.py
ibis/backends/sqlite/tests/test_types.py
ibis/backends/tests/test_examples.py
ibis/common/tests/test_temporal.py
ibis/conftest.py
ibis/examples/tests/test_examples.py

This PR makes a couple of tests compatible with pandas < 2, for package managers that have not yet upgraded to pandas >= 2.

test(common, sqlite): make tests pandas<2 compatible

---

ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/dask/execution/arrays.py
ibis/backends/duckdb/compiler.py
ibis/backends/duckdb/registry.py
ibis/backends/pandas/dispatch.py
ibis/backends/pandas/execution/arrays.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py
ibis/backends/trino/registry.py
ibis/expr/operations/arrays.py
ibis/expr/types/arrays.py

Make array concatenation and repetition easier to discover.
Closes #6720.

feat(api): add `concat` and `repeat` methods for easier array operation discovery

---

ibis/backends/pandas/execution/arrays.py
ibis/backends/tests/test_map.py
ibis/expr/operations/logical.py
ibis/expr/types/generic.py
ibis/tests/expr/test_value_exprs.py

`ops.Contains` support three kind of haystack arguments, one is `Value[dt.Array]` where the expression is identical with `arr.contains(value)`

refactor(ir): construct `ArrayContains` instead of `Contains` for `value.isin(array_value)`

---

ibis/backends/conftest.py
ibis/backends/polars/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/backends/tests/test_json.py
ibis/backends/tests/test_timecontext.py
ibis/backends/tests/test_vectorized_udf.py
ibis/backends/tests/test_window.py
ibis/expr/operations/relations.py
pyproject.toml

This PR adds support for literal `True` and `False` join predicates, which are supported across most backends. Closes #6696.

feat(api): support boolean literals in join API

---

ci/udf/CMakeLists.txt
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/dask/execution/generic.py
ibis/backends/duckdb/compiler.py
ibis/backends/pandas/execution/generic.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_aggregation.py
ibis/backends/trino/compiler.py
ibis/expr/operations/reductions.py
ibis/expr/types/relations.py

Add support for `table_expr.nunique(where=...)`. Closes #6683.

feat(api): add support for `table_expr.nunique(where=...)`

---

ibis/backends/tests/test_dataframe_interchange.py
ibis/backends/tests/test_export.py
ibis/expr/types/dataframe_interchange.py
ibis/expr/types/relations.py
ibis/expr/types/ruff.toml

This improves the efficiency and usability of the `__dataframe__` protocol in a few ways:
- It avoids executing the wrapped query for operations where that's not strictly required. This allows fetching things like column names and types, or subselecting columns to occur without executing the query first.
- Given a single `__dataframe__()` output (an `IbisDataFrame` instance), the wrapped query will execute at most once for all methods called. Once executed, the resulting `pyarrow.Table` is stored on the `IbisDataFrame` instance to be reused by subsequent access.
- If column subselection is done on an already executed `IbisDataFrame`, no computation results.
Given these improvements, an `ibis.Table` passed to `altair` (dev) now results in only one execution, rather than potentially several …

feat(api): improve efficiency of `__dataframe__` protocol

---

ibis/expr/datatypes/core.py

Just adds a short docstring to each so they show up in the reference docs.

docs: add docstrings to `DataType.is_*` methods

---

docker-compose.yml
docker/trino/Dockerfile
docker/trino/catalog/hive.properties
docker/trino/entrypoint.sh
docker/trino/metastore-site.xml
ibis/backends/trino/__init__.py
ibis/backends/trino/tests/test_client.py

This PR adds support for `create_table` with table properties to the Trino backend.
I don't like that for just a single test, I'm having to add three new containers
to our CI setup.
However, as far as I can tell Hive is only connector that has table properties.
If there are other connectors that are easier to setup that have any table
properties, I'm all ears.
There's some additional utility in having a functioning Hive connector around
which is that I plan to use it to test the cross-schema functionality as a
follow-up to this PR.
Ideally we can also get rid of our additional `trino-postgres` container but
after trying that locally it's going to be a bit more work and worth a separate PR.
Closes #6488.

feat(trino): add support for table properties

---

ibis/common/annotations.py
ibis/common/collections.py
ibis/common/tests/test_collections.py

The hybrid getitem/getattr access to the validation context is not
necessary since the move from the previous rule-based validation
to the current pattern matching system.

refactor(common): remove `ibis.collections.DotDict`

---

docs/reference/expressions/top_level.md
ibis/expr/api.py
ibis/expr/datatypes/core.py

This:
- improves the docstring for the `dtype` function
- Adds `dtype` to the public top-level API
Since we already expose `ibis.schema`, having `ibis.dtype` makes sense. It can also be useful when building larger APIs based on ibis, where you might want to coerce something to a `DataType` alone, rather than as part of a schema.

feat: add dtype to top level api

---

ibis/expr/operations/relations.py

Depends on https://github.com/ibis-project/ibis/pull/6743
Prefer not to manually validate the input arguments.

refactor(ir): use @annotated decorator to coerce Selection.order_by and Aggregation.order_by arguments

---

ibis/backends/tests/test_api.py

Fixes the single test that is failing because of a warning

test(bigquery): xfail the warning for BigQuery `list_databases`

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/tests/test_client.py
ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/trino/__init__.py

Make all of the `current_database` implementations consistent with each other.

fix(backends): make `current_database` implementation and API consistent across all backends

---

docs/backends/postgresql.md

it's a fallback, not a native implementation.

docs(postgres): fix postgres memtable docs

---

.github/workflows/ibis-backends-cloud.yml
ibis/backends/snowflake/__init__.py

I'm not sure what's going on here, but occasionally the snowflake test suite fails due to `SELECT current_database()` returning `None`.
Since we never test without first connecting to a database with a specific schema, this is extremely strange.
Running the tests in series, while frustratingly slow, doesn't seem to have this problem.

test(snowflake): revert db/schema prepending; run tests in series

---

ibis/backends/postgres/__init__.py
ibis/backends/postgres/tests/test_client.py

postgres:///dbname tries to connect via localhost, which may not be
allowed.  With localhost as the default parameter, there is no way to
force it to use the local unix domain socket.  This would make the
default using the domain socket, and then connecting via localhost
can be used via "postgres://localhost/dbname".

fix(postgres): by default use domain socket

---

ibis/backends/polars/__init__.py
ibis/common/graph.py
ibis/common/patterns.py
ibis/common/tests/test_patterns.py
ibis/expr/analysis.py
ibis/tests/expr/test_operations.py
ibis/util.py

This PR adds a `Node.match()` and `Node.replace()` methods to do search and replace tasks on node/operation trees. 
While `Node.match()` can return with nodes rewritten by the pattern, `Node.replace()` actually rebuilds the whole expression so the first is suitable for matching tasks while the latter is to rewrite operation trees.
Examples:
```py
from ibis.common.patterns import Replace
rule = Replace(
ops.ScalarParameter,
lambda op, ctx: ops.Literal(value=params[op], dtype=op.dtype),
)
node = node.replace(rule)
```
```py
from ibis.common.patterns import EqualTo
class Aliased: ...
class Name: ...
ketto = Aliased(one, "ketto")
first_rule = EqualTo(Name("one")) >> Name("zero")
second_rule = EqualTo(two) >> ketto
new_values = values.replace(first_rule | second_rule)
```
```py
from …
```

feat(common): match and replace graph nodes

---

ibis/backends/base/sql/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/expr/analysis.py

The `ibis.expr.analysis.find_memtables(node)` function is semantically equivalent with `node.find(ops.InMemoryTable)`

refactor(analysis): remove `find_memtables` function in favor of `node.find()`

---

ibis/backends/duckdb/__init__.py
ibis/expr/analysis.py

The `ibis.expr.analysis.find_phyisical_tables(node)` function is semantically equivalent with `node.find(ops.PhyisicalTable)`

refactor(analysis): remove `find_phyisical_tables()` function in favor of `node.find()`

---

ibis/backends/tests/test_string.py

test(bigquery): xfail `levenshtein` implementation

---

ibis/expr/builders.py
ibis/expr/types/generic.py

Unrelated to this, but I noticed that the exposed API of the CaseBuilders is probably a little more than we want. We probably just want people to have access to .when(), .else_(), and .end(), but since CaseBuilder inherits from Concrete, users get type hint suggestions for .copy(), and the other Expr internals. But that is separate from this issue

refactor: add types to Case and Window Builders

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py
ibis/backends/trino/registry.py
ibis/expr/operations/arrays.py
ibis/expr/types/arrays.py

This PR adds an `intersection` method to arrays.

feat(api): add `ArrayIntersect` operation and corresponding `ArrayValue.intersect` API

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py

Looks like `array_sort` is not actually release upstream. I define `array_sort` here as a JavaScript UDF in the meantime.

fix(snowflake): use ibis-defined `array_sort` until upstream lands

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/tests/test_array.py
ibis/expr/types/arrays.py

Fixes an inconsistency regarding null handling in computing distinct array elements. In this PR, NULL is treated as a unique value instead of being disarded.

fix: make sure that `array1.union(array2)` null handling matches across backends

---

ibis/backends/snowflake/registry.py

Disable array filter and map operations for the snowflake backend.

fix(snowflake): disable filter and map

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/tests/test_struct.py
ibis/expr/operations/structs.py
ibis/expr/operations/tests/test_structs.py

Fixes an incorrect modeling of the `StructColumn` operation dshape: it should depend on the dshape of the inputs.

fix(struct-column): make `ops.StructColumn` dshape depend on its input
