ibis/filesystems.py

BUG: WebHDFS.put can now handle general handle types

---

ibis/impala/tests/test_udf.py
ibis/tests/util.py

Fix pytest.mark.udf changes

---

ibis/__init__.py
ibis/client.py
ibis/config_init.py
ibis/expr/analysis.py
ibis/expr/types.py
ibis/filesystems.py
ibis/impala/tests/test_client.py
ibis/tasks.py
ibis/tests/util.py

Add default backend option

---

ibis/expr/api.py
ibis/expr/operations.py
ibis/impala/tests/test_exprs.py
ibis/sql/exprs.py
ibis/sql/tests/test_exprs.py

Add std dev / variance aggregate functions

---

ibis/impala/tests/common.py
ibis/impala/tests/test_ddl.py
scripts/run_jenkins.sh
scripts/test_data_admin.py

BUG: fix test_data_admin.py table creation

---

ibis/expr/types.py
ibis/sql/sqlite/tests/test_functions.py

Add exception into to repr on failure in interactive mode

---

ibis/expr/groupby.py
ibis/expr/tests/test_table.py

Function-based composability in group_by(...).mutate/projection

---

ibis/__init__.py
ibis/impala/api.py

DOC: Improve docstrings for connecting to Ibis

---

ibis/client.py
ibis/impala/client.py
ibis/impala/tests/test_client.py
ibis/sql/alchemy.py
ibis/sql/sqlite/client.py
ibis/sql/sqlite/tests/test_client.py

Enable Database usability layer to work with SQLite, more usability

---

.landscape.yaml
ibis/impala/compiler.py
ibis/impala/tests/test_pandas_interop.py
scripts/run_jenkins.sh

TST: Jenkins script must pass prospector (flake8) or fail

---

ibis/sql/compiler.py
ibis/sql/sqlite/tests/test_functions.py
ibis/sql/tests/test_compiler.py
ibis/sql/tests/test_sqlalchemy.py
ibis/sql/transforms.py

This had never been tested. Added Impala and SQLAlchemy tests

Fix foreign reference analysis bug with self references

---

ibis/sql/alchemy.py
ibis/sql/tests/test_sqlalchemy.py

Fixes #647. Also handles (but does not yet test) converting to Decimal type from SQLA schemas

Address post-join use cases with SQLAlchemy

---

docs/source/api.rst
ibis/expr/api.py
ibis/expr/operations.py
ibis/impala/compiler.py
ibis/impala/tests/test_exprs.py
ibis/sql/alchemy.py
ibis/sql/compiler.py
ibis/sql/sqlite/api.py
ibis/sql/sqlite/compiler.py
ibis/sql/sqlite/tests/test_functions.py

Add nullifzero numeric API and some light refactoring

---

docs/source/api.rst
ibis/impala/client.py
ibis/impala/tests/test_ddl.py
ibis/impala/tests/test_partition.py

Also renames a couple `ImpalaTable` APIs that weren't shipped yet

Add SHOW TABLE STATS / SHOW COLUMN STATS API wrappers

---

docs/source/api.rst
ibis/expr/api.py
ibis/expr/tests/test_value_exprs.py
ibis/impala/tests/test_client.py
ibis/impala/tests/test_exprs.py
ibis/sql/sqlite/tests/test_functions.py

This works similarly to functionality in pandas's `Series.replace`. See #259 for example

Add a replace values convenience API

---

ibis/impala/client.py
ibis/impala/tests/common.py
ibis/impala/tests/test_client.py

See #733. Will add more helpful configuration functions as they come up.

Add get_options/set_options to ImpalaClient, configurable compression codec

---

ibis/impala/client.py
ibis/impala/tests/test_client.py

ImpalaCursor.cursor is not a public attribute

---

ibis/impala/ddl.py
ibis/impala/tests/test_ddl.py
ibis/impala/tests/test_partition.py

Fix Impala DDL generation bug with string partition key

---

ibis/expr/rules.py
ibis/expr/tests/test_datatypes.py
ibis/expr/tests/test_timestamp.py
ibis/impala/tests/test_exprs.py

BUG: Fix timestamp precedence bug

---

circle.yml
dev/merge-pr.py
ibis/compat.py
ibis/config.py
ibis/expr/api.py
ibis/expr/temporal.py
ibis/impala/client.py
ibis/impala/compiler.py
ibis/impala/metadata.py
ibis/impala/udf.py
ibis/tests/test_comms.py
ibis/tests/test_filesystems.py
ibis/tests/test_server.py
ibis/tests/test_tasks.py
ibis/util.py
ibis/wire.py
scripts/airline.py
scripts/semaphore_perf.py
scripts/test_data_admin.py
setup.py

Fix remaining flake8 warnings and add flake8 to CircleCI

---

ibis/expr/format.py
ibis/expr/tests/test_format.py
ibis/expr/types.py

ENH: Show argument names in repr

---

ibis/expr/rules.py
ibis/expr/tests/test_rules.py

BUG: Conform raw enum values

---

ibis/expr/tests/test_datatypes.py
ibis/expr/types.py

BUG: Fix mixed type list literals

---

ibis/impala/tests/test_pandas_interop.py
ibis/impala/tests/test_partition.py

See [the JIRA](https://issues.cloudera.org/browse/IMPALA-2750)

TST: IMPALA-2750 tests no longer need to be skipped

---

ibis/mapd/client.py
ibis/tests/all/test_client.py

[MAPD] Added SQL method for mapd backend

---

.circleci/config.yml
azure-pipelines.yml

CI: Re-enabled CI for building step.

---

ci/datamgr.py
ci/schema/postgresql.sql
ibis/sql/alchemy.py
ibis/sql/postgres/tests/conftest.py
ibis/sql/postgres/tests/test_client.py

BUG: PostgreSQL interval type not recognized

---

ibis/mapd/ddl.py
ibis/mapd/operations.py
ibis/mapd/tests/test_client.py

FEAT: [mapd] Added float32 and geospatial types for create table from schema

---

ibis/pandas/core.py
ibis/pandas/tests/test_core.py
ibis/util.py

ENH: is_computable_arg dispatcher

---

ibis/mapd/operations.py

Added StringToTimestamp as unsupported

---

ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml

BUG/CI: Constrain PyMapD version to get passing builds

---

ibis/impala/compiler.py
ibis/tests/all/conftest.py
ibis/tests/all/test_window.py

Add marker for xfailing specific backends

---

ibis/expr/operations.py
ibis/expr/tests/test_value_exprs.py
ibis/impala/tests/test_exprs.py

BUG: NullIf should enforce that its arguments are castable to a common type

---

ibis/pandas/tests/test_udf.py
ibis/pandas/udf.py

ENH: Allow strings for types in pandas UDFs

---

.pep8speaks.yml

Add pep8speaks integration

---

ibis/expr/analysis.py
ibis/expr/tests/test_value_exprs.py
ibis/pandas/execution/tests/test_join.py

BUG: Allow projections from joins to attempt fusion

---

Makefile
ibis/bigquery/compiler.py
ibis/expr/rules.py
ibis/pandas/execution/generic.py
ibis/pandas/execution/temporal.py
ibis/sql/compiler.py
ibis/sql/mysql/compiler.py
ibis/tests/all/test_temporal.py

ENH: Call to_interval when casting integers to intervals

---

ci/requirements-docs.yml

BUG/DOC/CI: Pin sphinx version to 2.0.1

---

ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
setup.py

This PR moves some packages that were previously being installed with pip to be
installed by conda.
It also adds pre-commit, black and isort to `setup.py`.
Closes #1814

PKG: Add pre-commit, black and isort to setup.py

---

README.md
ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
ibis/impala/compiler.py
ibis/sql/alchemy.py
ibis/sql/postgres/tests/test_functions.py
setup.py

BUG: Do not give a frame clause where not necessary in window functions

---

ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
setup.py

SUPP: Tighter version spec for pytest

---

ibis/file/client.py
ibis/file/tests/test_csv.py
ibis/file/tests/test_hdf5.py
ibis/file/tests/test_parquet.py
ibis/pandas/client.py
ibis/pandas/core.py
ibis/pandas/dispatch.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/execution/window.py
ibis/pandas/tests/test_udf.py

This caused a few failures with downstream code, so I've reverted the changes
to ibis/pandas/core.py.
I've left other fixes from #1758 unchanged.
I'll revisit the reimplementation in the near future.

BUG: Partially revert #1758

---

ibis/expr/schema.py
ibis/expr/tests/test_schema.py

BUG: Fix repr of empty schema

---

ibis/tests/all/conftest.py
ibis/tests/all/test_client.py
ibis/tests/backends.py
setup.cfg

Also did some refactoring of `backends.py`.
Closes #1846

SUPP: Skip SQLAlchemy backend tests in connect method in backends.py

---

ibis/pandas/aggcontext.py
ibis/pandas/execution/tests/test_window.py

Small bug in the pandas backend when ordering by a particular key and not grouping.

BUG: Fix the case where we do not have an index when using preceding with intervals

---

docs/source/contributing.rst

This PR:
- Adds a CoC section into contribution doc page.
Related to #1881

Added CoC section

---

docs/source/contributing.rst

@cpcloud I sent link in MD format, sorry ... this PR fix this link issue.

Fix link to NUMFOCUS CoC

---

ibis/mapd/operations.py
ibis/mapd/tests/test_operations.py

BUG: OmniSci/MapD - Fix reduction for bool

---

ibis/spark/tests/test_udf.py
ibis/spark/udf.py

Fixes failing builds on master.

BUG: Fix failing com imports on master

---

ibis/pandas/execution/generic.py
ibis/pandas/execution/tests/test_operations.py

BUG: Fix union implementation

---

ibis/file/parquet.py
ibis/file/tests/test_schema.py

ENH: Support timezone aware arrow timestamps

---

ibis/mapd/operations.py
ibis/mapd/tests/test_operations.py
ibis/tests/all/test_aggregation.py
ibis/tests/all/test_generic.py

Added missing null literal op

---

ci/Dockerfile.dev
ci/Dockerfile.docs
ci/azure/windows.yml
ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml

BUG: Upgrade to JDK11

---

ibis/pandas/execution/temporal.py
ibis/pandas/execution/tests/test_temporal.py

FEAT: Implement IntervalSub for pandas backend

---

ci/azure/linux.yml

SUPP: Disable codecov report upload during CI builds

---

ci/azure/linux.yml
ci/check-services.sh

SUPP: Add log for database services

---

ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
setup.py

Resolves #2005 
It would be good in a near future to find the reason of this problem.

BUG: Pinning clickhouse-driver<0.1.2

---

Makefile
ci/azure/linux.yml
ci/docker-compose.yml

SUPP: Fix impala start up issues

---

docs/source/release.rst
ibis/expr/tests/test_visualize.py
ibis/expr/visualize.py

Escape column names and types in png_repr.

---

ci/datamgr.py
docs/source/release.rst

Omnisci raises an exception if you try to drop a non-existing table

CI: [Omnisci] Drop table only if it exists

---

docs/source/release.rst
ibis/omniscidb/client.py
ibis/omniscidb/operations.py
ibis/omniscidb/tests/test_client.py

This PR fix data map int8 on OmniSciDB

BUG: Fix data map for int8 on OmniSciDB

---

.pre-commit-config.yaml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml

Now release versions of tools are used.

SUPP: use conda for installation black and isort tools

---

docs/source/release.rst

RLS: Add release notes for release 1.3.0

---

Makefile

CI: Fix PYTHONHASHSEED issue

---

ci/docker-compose.yml
docs/source/release.rst
ibis/omniscidb/operations.py
ibis/tests/all/test_generic.py

#2083 fix omnisci image version to pass CI

omnisci image fix

---

ci/docker-compose.yml

CI: Update Clickhouse server image tag to 18.14

---

ci/docker-compose.yml

CI: Update MySQL to 10.4.12, fix #2162

---

ci/azure/linux.yml
docs/web/about/team.md
docs/web/community/coc.md
docs/web/config.yml
docs/web/getting_started.md

Once this is merged, docs.ibis-project.org will point to the website, and the current docs will be in the /docs/ directory.

DOC: Rendering the website, and publishing it with the docs

---

ci/azure/linux.yml

CI: Fixing the path of the git repo when building the web

---

ci/Dockerfile.docs
ci/azure/linux.yml
ci/requirements-docs.yml

The website is still not published. I incorrectly run the generation in the CI host directly, instead of generating it inside the docs docker. This should fix the problem, and the website should be finally published.

DOC: Building website inside docker

---

ibis/tests/all/test_window.py
ibis/tests/backends.py

TST: Fix MySQL window tests selection on CI

---

ci/requirements-dev-3.6-main.yml
ci/requirements-dev-3.7-main.yml
ci/requirements-dev-3.8-main.yml

Pin google-api-core=1.17.0

---

README.md
ci/docker-compose.yml
docs/source/release/index.rst

Use stable version of OmniSciDB on CI

---

ibis/tests/all/test_aggregation.py
ibis/tests/all/test_numeric.py
ibis/tests/all/test_string.py

Resolve #1491
Add tests for:
- radians
- degrees
- covariance
- correlation
- ilike

TST: Add tests for radians, degrees, covariance, correlation and ilike ops

---

docs/source/user_guide/backends/impala.rst
docs/source/user_guide/index.rst

DOC: move impala guide to backends directory

---

ci/azure/linux.yml

Sorry @jreback, another follow up of #2291.

CI: Fixing another typo when pushing the docs (secret token env)

---

ci/datamgr.py
ci/schema/bigquery.sql

TST: add bigquery schema to datamgr

---

docs/web/community/ecosystem.md
docs/web/config.yml

This closes #2236, adding an ecosystem page to the ibis-project website. @datapythonista, @jreback let me know if there's anything else you want included or changed, or any wording you want differently. I took the SQLAlchemy and pandas descriptions straight from their README's

DOC: Add ecosystem page to docs

---

.github/workflows/main.yml
ci/deps/pyspark-min.yml
ci/deps/spark-min.yml
ibis/tests/all/test_temporal.py

CI: Enable UDF tests for PySpark and Spark backends

---

docs/web/contribute.md

Few things have been simplified recently, and the contributing documentation wasn't update. Updating it here.

DOC: Updating and improving the contributing documentation

---

ibis/filesystems.py

Closes #2399
This import was moved by mistake.
xref: https://github.com/ibis-project/ibis/pull/2385#discussion_r491220098

DEPS: Removing requests as a hard dependency

---

docs/web/contribute.md

Close #2415 I have added the ibis-project link to the contribute link. Please consider this pull request.

ISS 2415 Added IBIS project link to the contribute page

---

docs/source/release/index.rst
ibis/backends/postgres/tests/test_client.py
ibis/expr/datatypes.py
ibis/expr/types.py
ibis/sql/alchemy.py
ibis/tests/all/test_nettypes.py

Fixes https://github.com/ibis-project/ibis/issues/2461 and https://github.com/ibis-project/ibis/issues/2462

Support for MACADDR and INET Postgres Types

---

.github/workflows/main.yml
ci/azure/windows.yml
ci/deps/omniscidb.yml
ci/docker-compose.yml
ci/recipe/meta.yaml
docs/source/backends/omnisci.rst
docs/source/release/index.rst
ibis/backends/omniscidb/client.py
setup.py

This PR continues the work started at https://github.com/ibis-project/ibis/pull/2256
This PR adds the changes needed to use OmniSciDB>=5.3
cc @jclay

Omnisci thrift update

---

ibis/backends/base_sql/__init__.py
ibis/impala/compiler.py

Next batch of operation registry moves from impala.

Batch 3 impala operation registry move

---

docs/web/getting_started.md

closes https://github.com/ibis-project/ibis/issues/2504

Swap broken binder link for a link to tutorials in docs

---

ibis/backends/base_sql/ddl.py
ibis/backends/spark/client.py
ibis/backends/spark/ddl.py
ibis/impala/client.py
ibis/impala/ddl.py
ibis/impala/kudu_support.py
ibis/impala/tests/test_ddl_compilation.py
ibis/impala/tests/test_udf.py

@datapythonista i started with what was in the spark ddl file.  still have some work to do checking tests and other backends but this gets the ball rolling.  hopefully CI is ok. will keep you posted.

Move impala ddl to base_sql

---

docs/source/api.rst

Add asof_join to api ref

---

benchmarks/benchmarks.py

closes #2455 
@datapythonista @jreback
Actually it looked like the functions existed but just werent being called with the correct name.  Lmk if you think otherwise.

Fix pandas benchmark test functions

---

.github/workflows/main.yml
ci/datamgr.py
ci/deps/dask.yml
environment.yml
ibis/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/dask/tests/execution/conftest.py
ibis/backends/dask/tests/test_import.py
ibis/tests/backends.py
setup.cfg
setup.py

Part one of four in breaking up https://github.com/ibis-project/ibis/pull/2400 into more manageable pieces. 
Goal in this PR is to create the basic skeleton and get CI running. I've also added conftest pieces that didn't depend on anything else.

Init skeleton for dask backend

---

ibis/backends/pandas/__init__.py
ibis/backends/pandas/core.py

RE:
- https://github.com/ibis-project/ibis/pull/2541#discussion_r529525250
- https://github.com/ibis-project/ibis/pull/2541#discussion_r529528075
- https://github.com/ibis-project/ibis/pull/2541#discussion_r529528250

DOC: Clean up documentation in pandas backend

---

setup.py

Remove setup.py dev dependencies

---

.github/workflows/main.yml
ibis/backends/impala/hdfs.py

Fix hdfs_connect on GHA

---

environment.yml

Fix for #2578 (until Sphinx itself is fixed)

Pin sphinx<=3.3.1

---

docs/source/tutorial/07-Advanced-Topics-ComplexFiltering.ipynb

To allow #2590, but also makes the tutorial much easier to understand I think.

DOC: Using countries data and SQLite in tutorial 7

---

docs/source/tutorial/07-Advanced-Topics-ComplexFiltering.ipynb
docs/source/tutorial/08-More-Analytics-Helpers.ipynb

I also move one of the section in tutorial 8 (analytics) to tutoral 7 (filtering), since it's about filtering

DOC: Use geography database and SQLite in tutorial 8

---

docs/source/user_guide/extending/extending_elementwise_expr.ipynb
docs/source/user_guide/extending/extending_reduce_expr.ipynb

One more towards #2590. I don't think there is much left in the docs that require docker images, just one more small PR and that's it.

DOC: Using SQLite in extending reduce page

---

docs/source/tutorial/data/Create-geography-database.ipynb

I created the database used for the tutorials in PostgreSQL, to test that some functionality works. This code is not being used at the moment, but I think it's worth having it next to the SQLite equivalent, than not committing it and getting it lost.

DOC: Adding code to create tutorials db in PostgreSQL

---

docs/source/release/index.rst
ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/client.py
ibis/backends/bigquery/tests/conftest.py
ibis/backends/bigquery/tests/test_client.py
ibis/backends/bigquery/tests/test_connect.py
ibis/backends/bigquery/tests/test_datatypes.py
ibis/backends/bigquery/tests/udf/test_core.py
ibis/backends/bigquery/tests/udf/test_find.py
ibis/backends/bigquery/tests/udf/test_udf_execute.py

BUG: Fix BigQuery connect bug that ignored project ID parameter

---

ibis/expr/analysis.py
ibis/expr/api.py

Straightforward move of some pretty lengthy mutate logic into a reusable public method.

Refactor logic in mutate API into method

---

.github/workflows/main.yml

CI: Removing Dask builds on Windows, since they seem redundant

---

README.md

Replacing Azure badge by the GitHub actions one in README

---

ibis/backends/tests/base.py
ibis/backends/tests/test_vectorized_udf.py

Update Spark/Pyspark test to use multiple partitions.
Fix broken tests.

TST: Use multiple partitions for spark csv test data

---

ci/deps/clickhouse.yml
ci/deps/postgres-min.yml
docs/source/release/index.rst
ibis/backends/base_sqlalchemy/alchemy.py
ibis/backends/mysql/compiler.py
ibis/backends/postgres/tests/test_functions.py
setup.py

Making Ibis work with SQLAlchemy 1.4

---

ibis/backends/pyspark/tests/test_basic.py

Adding a unit test for the new logic introduced here: https://github.com/ibis-project/ibis/pull/2687

TST: Add unit test for Pyspark selection logic

---

ibis/backends/tests/base.py

CI: Fixing Spark tests by setting the ip address to bind

---

ibis/expr/rules.py
ibis/tests/expr/test_rules.py

Closes https://github.com/ibis-project/ibis/issues/2745

ENH: Add rlz.optional rule

---

docs/web/getting_started.md

DOC: Link to advanced installation broken

---

environment.yml

CI: Pin sphinx below `4.0.0`

---

environment.yml

CI: Pin jinja2 to restore CI

---

docs/source/release/index.rst
ibis/backends/base/sql/alchemy/client.py
ibis/backends/tests/conftest.py
ibis/backends/tests/test_client.py

Closes #2613
The implementation is similar to what is currently implemented for the Impala database. Please have a look and merge it if you think this helps your requirement. I have also added commentary to what will work and what won't in the code so that enhancements can be made to it later on. Thanks.

Implementation for insert method for SQLAlchemy backends

---

ibis/backends/base/sql/compiler/query_builder.py

Simplifying a bit the code of `QueryBuilder` and remove some duplicate code.

CLN: Simplify QueryBuilder code

---

.github/workflows/main.yml
ci/impalamgr.py
dev/merge-pr.py
ibis/_version.py
ibis/backends/dask/tests/execution/conftest.py
ibis/backends/dask/tests/execution/test_join.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/expr/operations.py

CI: Fixing and validaing flake8

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/clickhouse/compiler.py
ibis/backends/impala/compiler.py
ibis/backends/mysql/compiler.py
ibis/backends/postgres/compiler.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/spark/compiler.py
ibis/backends/sqlite/compiler.py
ibis/backends/sqlite/tests/conftest.py

Closes #2824 
xref https://github.com/ibis-project/ibis/pull/2818#discussion_r651651172

CLN: Make compiler attribute names consistent

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/postgres/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/postgres/udf.py
ibis/backends/tests/test_numeric.py

Closes #2840
These imports are causing problems in the CI of `ibis-omniscidb` and to me locally.

CLN: Fix and standardize SQLAlchemy dialect imports

---

ibis/backends/mysql/client.py
ibis/backends/postgres/client.py
ibis/backends/sqlite/client.py

Not sure why those were added, but don't seem very useful.

CLN: Remove client property in Client

---

ibis/backends/base/sql/alchemy/client.py

I don't think it adds much value to have this optimization in the code. `sqlalchemy.inspect(con).info_cache.clear()` is immediate, and we can save the calls to it only for code like `con.list_tables()`, which I don't see any use case for being called more than once (and not in a loop). So, I think this is making the code more complex, for no reason.

CLN: Removing inspector optimization

---

ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/postgres/udf.py
ibis/backends/sqlite/tests/conftest.py
ibis/backends/sqlite/tests/test_functions.py

CI: Fix some mypy issues in backends

---

ibis/backends/base/sql/alchemy/client.py

Small reorganization to make the conversion to geodataframe clearer.

CLN: Small simplification of conversion to geodataframe

---

docs/source/release/index.rst
ibis/backends/base/__init__.py
ibis/backends/clickhouse/tests/test_client.py
ibis/backends/impala/tests/test_client.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/spark/tests/test_api.py
ibis/backends/sqlite/tests/test_client.py
ibis/backends/tests/test_client.py
ibis/expr/types.py

DEPR: Deprecate verify

---

.github/workflows/main.yml
ibis/backends/base/file/__init__.py

BUG: Loading pandas options for file backends

---

ibis/backends/dask/tests/test_client.py
ibis/backends/pandas/execution/maps.py
ibis/backends/pandas/tests/execution/test_maps.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_temporal.py
ibis/tests/sql/test_sqlalchemy.py

Follow up of #2886 
Fixing some more warnings

Fixing more warnings

---

.github/workflows/main.yml
environment.yml
ibis/backends/base/sql/client.py
ibis/common/geospatial.py
ibis/config.py
ibis/tests/expr/test_geospatial.py
ibis/udf/validate.py
ibis/util.py

Fixing some mypy errors, and validate fixed directories

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/mysql/__init__.py
ibis/backends/mysql/client.py
ibis/backends/postgres/__init__.py
ibis/backends/postgres/client.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/client.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/client.py

Remove unused Database and DatabaseTable subclasses

---

ibis/backends/dask/client.py
ibis/backends/dask/execution/selection.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/execution/window.py
ibis/backends/pandas/execution/constants.py
ibis/expr/scope.py

Partially solves issue #2852 
There are some remaining errors, but I think they might need a deeper code refactor.

CI: Fix most mypy errors in the Dask backend

---

ibis/backends/pandas/udf.py

Both branches had exactly the same code.

MAINT: Remove duplicate udf branch in pandas backend

---

docs/source/release/index.rst

DOC: Adding pending release note for Client.version output

---

ibis/expr/analysis.py
ibis/expr/api.py
ibis/expr/datatypes.py
ibis/expr/format.py
ibis/expr/scope.py
ibis/expr/timecontext.py

Fix most mypy errors in ibis/expr

---

ibis/backends/base/__init__.py
ibis/backends/base/client.py
ibis/backends/base/file/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/client.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/csv/__init__.py
ibis/backends/hdf5/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/impala/tests/conftest.py
ibis/backends/pandas/__init__.py
ibis/backends/parquet/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/postgres/client.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/client.py
ibis/backends/tests/test_api.py

CLN: Standardize list_databases and exists_database and move to Backend

---

ibis/backends/base/__init__.py
ibis/backends/base/client.py
ibis/backends/base/file/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/client.py
ibis/backends/base/sql/client.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/pandas/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/client.py
ibis/backends/tests/test_api.py

CLN: Standardize current_database and move to Backend

---

docs/source/api.rst
ibis/backends/base/__init__.py
ibis/backends/base/client.py
ibis/backends/base/file/__init__.py
ibis/backends/base/sql/alchemy/client.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/csv/tests/test_csv.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/pandas/__init__.py
ibis/backends/parquet/tests/test_parquet.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/client.py
ibis/backends/tests/test_api.py

CLN: Standardize set_database and move to Backend

---

docs/web/config.yml

This PR updates some information on the website

chore: update website information

---

ci/pytest_errors.sh

This PR adds a few standard bashisms to increase robustness
and decrease so of the stdout-writing redundancy

ci: clean up pytest_errors.sh script

---

environment.yml

This PR removes some unnecessary dependencies from ibis's environment.yml

chore: remove unneeded deps

---

.github/workflows/main.yml
.gitignore

This PR fixes the pushing part of the doc build

docs: fix doc build

---

.github/workflows/test-report.yml

This PR attempts to fix the test reporter to post comments to the right place.

ci: try using the specific commit for publishing

---

docs/source/release/index.rst
ibis/backends/pandas/__init__.py
ibis/backends/tests/conftest.py
ibis/backends/tests/test_api.py

Raise NotImplementedError when databases are not supported

---

ci/recipe/meta.yaml
docs/source/release/index.rst
environment.yml
ibis/backends/tests/test_client.py
ibis/expr/datatypes.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_rules.py
ibis/tests/expr/test_schema.py
requirements.txt

This PR replaces our current handwritten parser with a parser combinator
produced by the [`parsy`](https://parsy.readthedocs.io/) library.
Closes #2975.
Depends on https://github.com/conda-forge/staged-recipes/pull/16171

refactor: replace handwritten parser with library

---

docs/source/release/index.rst
ibis/backends/clickhouse/tests/test_functions.py

- docs: add missing release notes for #2984 and #2985
- docs: add comment with PR number

docs: add missing release notes

---

ci/datamgr.py
ibis/backends/base/file/__init__.py
ibis/backends/csv/__init__.py
ibis/backends/hdf5/__init__.py
ibis/backends/parquet/__init__.py
ibis/backends/tests/test_api.py
ibis/backends/tests/test_temporal.py
ibis/backends/tests/test_window.py

This PR adds data generation for the hdf5 backend.
Closes #2998

test: ensure that python ci/datamgr.py hdf5 produces data

---

ibis/backends/clickhouse/__init__.py

xref https://github.com/ibis-project/ibis/pull/3018#discussion_r716755123

CLN: Remove redundant bool in clickhouse fully_qualified_name

---

docs/source/release/index.rst

DOC: Adding release note for the backend API changes

---

docs/web/contribute.md

doc(install): fix env setup #3146

---

ibis/tests/expr/test_interactive.py

test: remove invalid xfail, and remove unittest usage from test_interactive.py

---

ibis/backends/pandas/aggcontext.py

refactor: remove dead pandas code for handling windows

---

ibis/expr/api.py
poetry.lock

docs: clean up schema documentation

---

docs/source/release/index.rst

docs: fix release notes

---

.github/workflows/auto-rebase.yml
.github/workflows/conda-lock-dispatch.yml
.github/workflows/conda-lock-pr.yml
.github/workflows/conda-lock.yml
.github/workflows/create-rotate-key-issue.yml
.github/workflows/ibis-main.yml
.github/workflows/update-deps.yml
.github/workflows/update-setup-py.yml

This PR adds:
1. Automatic nightly PRs for upgrading nix dependencies
2. Autorebase for PRs on an opt-in basis. The auto nix update PRs add this label when they are created.

ci: add automatic dependency update PRs

---

ibis/expr/rules.py
ibis/tests/expr/test_rules.py

Closes https://github.com/ibis-project/ibis/issues/3152

feat: allow column_of to take a column expression

---

docs/source/backends/pandas.rst
ibis/backends/pandas/trace.py

Looks like an old code that was not updated in #2440.

docs: fix sample code

---

.github/workflows/check-setup-py.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-main.yml
poetry.lock

This PR uses two github actions to consolidate the ci caching of poetry dependencies as well as allow updates to the cache if anythin chagnes during the run

ci(perf): improve caching in ci

---

.github/workflows/update-deps.yml

This PR fully automates our nix dependency updates.
The action is changed to approve and set the PR to automerge, so
that when the check suite passes, the PR will be merged.

ci: fully automate nix updates

---

docs/source/backends/datafusion.rst
docs/source/backends/index.rst
ibis/backends/datafusion/__init__.py

docs: add basic datafusion client documentation

---

ibis/backends/clickhouse/client.py
ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_operators.py
ibis/backends/clickhouse/tests/test_types.py
ibis/backends/dask/tests/execution/test_arrays.py
ibis/backends/pandas/tests/execution/test_arrays.py
ibis/backends/postgres/registry.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/tests/test_array.py
ibis/expr/api.py

Added support arrays for clickhouse.
Implemented next operations:
* ArrayIndex
* ArrayConcat
* ArrayRepeat
* ArraySlice

feat: support of arrays and tuples for clickhouse

---

ibis/backends/dask/execution/selection.py

This change generates much less intermediate code/operations/concat calls in the simple case where we are doing a simple selection or selection + rename. It still falls back to the projection logic in the case where we need to perform some computation (though lots of this can probably be cleaned up/refactored in the future).
Resolves #2742.

perf: fast path for simple column selection

---

.github/workflows/ibis-backends.yml
ibis/backends/postgres/__init__.py
ibis/backends/postgres/udf.py

bug: fix postgres udfs and reenable ci tests

---

ibis/backends/dask/execution/util.py
ibis/backends/dask/udf.py

Closes https://github.com/ibis-project/ibis/issues/2815. 
Also remove a shim we no longer need.

refactor: remove shim which is no longer needed

---

ibis/backends/sqlite/tests/test_client.py

test: add test for DatabaseTable equality semantics

---

.github/workflows/ibis-backends.yml
ci/datamgr.py
docker-compose.yml
docker/ibis-postgres/Dockerfile
docs/web/contribute/backend_test_suite.md
ibis/backends/postgres/__init__.py
ibis/backends/postgres/tests/test_udf.py
ibis/backends/postgres/udf.py
ibis/backends/tests/test_window.py
shell.nix

- ci: use official postgis image and add plpythonu extension
- chore(dev): bump impala's postgres to 13.3
- chore: remove the need for 5433 since impala only needs to address the postgres container inside the docker network
- chore(dev): run the impala postgres container as the postgres user

ci: tighten up the docker-compose setup

---

ibis/backends/csv/__init__.py
ibis/backends/tests/test_join.py

fix: remove broken csv pre_execute

---

ibis/backends/impala/tests/test_sql.py
ibis/expr/analysis.py
ibis/expr/window.py
ibis/tests/expr/test_window_functions.py

fix: correctly combine windows during windowization

---

ibis/expr/analysis.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_sqlalchemy.py

fix: mutate + filter no longer compiles to unintentionnal cross join

---

ibis/backends/dask/tests/execution/conftest.py
ibis/backends/dask/tests/execution/test_join.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/hdf5/__init__.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/selection.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/pandas/tests/execution/conftest.py
ibis/backends/pandas/tests/execution/test_operations.py
ibis/backends/parquet/__init__.py
ibis/backends/parquet/tests/conftest.py
ibis/backends/tests/test_join.py
shell.nix

test: fix failing pandas, dask, parquet and hdf5 tests

---

docs/web/community/ecosystem.md

docs: add fugue to ecosystems
@cpcloud

docs: add fugue to ecosystems

---

ibis/backends/clickhouse/tests/test_client.py

test: remove unnecessary skip decorator on test_insert

---

docs/source/api.rst
ibis/expr/api.py
ibis/expr/datatypes.py
ibis/expr/types.py
ibis/tests/expr/test_array.py
ibis/tests/expr/test_literal.py

fix(api): add ibis.map and .struct

---

.github/workflows/ibis-main-skip-helper.yml
docs/about/team.md

docs: fix bad link on team page

---

docs/about/team.md
docs/community/coc.md
docs/example.py
docs/example.sql
docs/getting_started.md
docs/index.md
docs/sqlalchemy_example.py
mkdocs.yml
setup.cfg

- docs: add better comparison section
- chore: fix links

docs: add better comparison section and fix broken links

---

setup.py

Looks like this slipped through from #3395

chore: fix setup.py gen

---

docs/contribute/environment.md

docs: fix incorrect -f argument for conda dev environment setup

---

ibis/backends/datafusion/__init__.py
ibis/backends/datafusion/tests/test_client.py

- chore: fix setup.py gen
- test: add failing test
- fix: remove passing schema into register_parquet

fix: remove passing the schema argument to register_parquet

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/tests/test_numeric.py

also add basic test for col.histogram()
closes #622

fix(histogram): cross_join needs onclause=True

---

ci/schema/postgresql.sql
ibis/backends/conftest.py
ibis/backends/dask/tests/execution/conftest.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/pandas/tests/execution/conftest.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/tests/test_numeric.py
ibis/tests/expr/conftest.py
ibis/tests/sql/conftest.py

- chore: remove unused fixture
- ci: add dead fixtures test
- chore(dev-deps): add pytest-deadfixtures
- test: remove dead fixtures

test: remove dead fixtures

---

ibis/backends/dask/execution/selection.py
ibis/backends/dask/execution/util.py

Right now we build up projections by creating pieces and then concating them all together (following the pandas backend). This is a fairly inefficient operation in dask and some local testing shows that dask will struggle to optimize operations between the pieces you're concating (TODO elaborate). 
This change assigns into the existing frame, reducing operations and speeding things up.

perf: use assign instead of concat in projections when possible

---

ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py
ibis/backends/pandas/tests/test_udf.py
ibis/backends/pandas/udf.py

refactor(pandas): remove unused rule_to_python_type

---

docs/example.sql
docs/index.md
docs/stylesheets/extra.css

This PR fixes a couple broken links and cleans up the general area a bit.

docs: fix broken links

---

ibis/backends/sqlite/registry.py
ibis/backends/tests/test_temporal.py

This PR implements `week_of_year` for the SQLite backend.

feat(sqlite): implement ISO week of year

---

ibis/backends/pandas/execution/window.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_window.py

This PR enables the test for percent_rank on grouped bound window functions

test(window-functions): fix percent rank test

---

ibis/expr/types/generic.py
ibis/expr/types/relations.py
mkdocs.yml

- docs: remove warnings during build
- docs: build in strict mode to fail on warnings

docs: fix docs warnings and fail on warnings in ci

---

ibis/tests/benchmarks/test_benchmarks.py

This PR introduces additional benchmarks for the repr. These should go in before #3594 so that we have a bit of a baseline.

test: add repr benchmarks

---

ibis/expr/datatypes/__init__.py
ibis/tests/expr/test_schema.py

- test(bench): add datatype parsing and repr benchmarks
- perf(datatypes): speed up __str__ and __hash__

perf(datatypes): speed up __str__ and __hash__

---

docker-compose.yml
ibis/backends/clickhouse/compiler.py
ibis/backends/clickhouse/registry.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_union.py
shell.nix

This PR implements a few more string operations for clickhouse as well as unions.

feat(clickhouse): implement string ops and union

---

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_temporal.py

fix(duckdb): add casts to literals to fix binding errors

---

ibis/backends/tests/test_aggregation.py
ibis/expr/operations/relations.py

Fix for minor regression introduced in #3619

fix: regression in sort_by with resolved_keys

---

ibis/expr/format.py
ibis/tests/expr/test_format.py

Fixes a minor regression in the new repr

fix(repr): allow ops.TableNode in fmt_value

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/postgres/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_temporal.py
ibis/expr/api.py
ibis/expr/operations/temporal.py
ibis/tests/expr/test_temporal.py

Pw22 date from ymd

---

ibis/backends/tests/test_window.py

This PR speeds up the grouped bounded range window test by about 6x by using a
better algorithm that takes advantage of the sortedness of the window using
`np.searchsorted`.

test: speed up the grouped window test by 6x

---

ibis/backends/base/sql/alchemy/database.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/impala/tests/test_exprs.py
ibis/expr/datatypes/core.py
ibis/expr/operations/core.py
ibis/expr/operations/generic.py
ibis/expr/operations/relations.py
ibis/expr/operations/sortkeys.py
ibis/expr/schema.py
ibis/expr/signature.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/window.py
ibis/tests/expr/test_signature.py
ibis/tests/test_util.py
ibis/util.py

Splitting https://github.com/ibis-project/ibis/pull/3626 into multiple PRs.

refactor(ir): global equality cache

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/tests/test_client.py

This PR reimplements `_get_schema_using_query` for the ClickHouse backend using
[`EXPLAIN`](https://clickhouse.com/docs/en/sql-reference/statements/explain/#explain-plan)
with JSON.
Previously the method was executing the entire query (!) to get the schema.

refactor(clickhouse): implement _get_schema_using_query using explain with json

---

ci/schema/clickhouse.sql
ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/tests/test_join.py
ibis/backends/tests/test_string.py

This PR changes our clickhouse ci schema to use Nullable(T) columns, which exposed a couple of bugs and xpass a few tests, yay!

test: test using nullable clickhouse columns

---

ibis/backends/clickhouse/tests/test_client.py

Should have rebased https://github.com/ibis-project/ibis/commit/c97cbce258d6109d96adab25dce5a6aa59849698 on top of https://github.com/ibis-project/ibis/commit/0d5744643722f1070852c9412d6b8910943ffd78

test(clickhouse): fix field nullability for new test cases

---

ibis/backends/pyspark/tests/conftest.py

Hopefully this fixes the current pyspark test flakiness

test: fix pyspark cleanup

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/postgres/registry.py
poetry.lock
pyproject.toml
setup.py

This PR bumps the sqlalchemy lower bound to 1.4. Without 1.4 we cannot fix the recent cross join issue in #3677 .

chore(deps): increase sqlalchemy lower bound to 1.4

---

.github/workflows/check-setup-py.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-main.yml

This PR adds codecov upload reports for our CI test suite

ci: add codecov upload reports

---

ibis/backends/datafusion/compiler.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/expr/types/relations.py
ibis/util.py
poetry-overrides.nix
poetry.lock
pyproject.toml
setup.py

This PR fixes the rendering of `table.info()` using the lightweight `tabulate` library.

fix(expr): fix formatting of table info using `tabulate`

---

docs/tutorial/04-More-Value-Expressions.ipynb

chore(tutorial): update usage of distinct in tutorial notebooks

---

poetry-overrides.nix

Small cleanup PR to remove poetry overrides that have since been upstream'd

build: remove upstream'd poetry overrides

---

default.nix
shell.nix

This PR moves us to the proper version of gdal in the nix shell.

build: move to proper gdal_2

---

poetry-overrides.nix

Removes more upstreamed poetry overrides.

build(nix): remove more upstream'd poetry overrides

---

.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml
docs/contribute/01_environment.md
patches/datafusion-macos.patch
patches/watchdog-force-kqueue.patch
poetry-overrides.nix

This PR adds back macOS x86 builds to the CI.

ci: run macOS in nix build

---

ibis/backends/base/sql/compiler/translator.py
ibis/backends/dask/execution/strings.py
ibis/backends/duckdb/compiler.py
ibis/backends/duckdb/registry.py
ibis/backends/pandas/execution/strings.py
ibis/backends/pyspark/compiler.py
ibis/expr/operations/strings.py
ibis/expr/types/strings.py
ibis/tests/expr/test_string.py
ibis/tests/sql/test_compiler.py

refactor(ops): add StringContains operation

---

ci/release/prepare.sh

This PR ensures that the built wheel contains the expected version number.

ci: verify version in built wheel during prepare phase

---

.github/renovate.json
.pre-commit-config.yaml

chore: add pre-commit ci config

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml
.github/workflows/ibis-main.yml
.pre-commit-config.yaml
.prettierignore
nix/default.nix
shell.nix

This PR shaves the shell.nix down by about 500MB which should save a bit on cache download times.

chore(deps): shave down shell.nix

---

poetry-overrides.nix

- build: parallelize pandas build
- build: parallelize pydantic build
- build: parallelize pybind11 build

build: parallelize expensive package builds

---

docs/ibis-for-sql-programmers.ipynb
docs/tutorial/01-Introduction-to-Ibis.ipynb
docs/tutorial/02-Aggregates-Joins.ipynb
docs/tutorial/03-Expressions-Lazy-Mode-Logging.ipynb
docs/tutorial/04-More-Value-Expressions.ipynb
docs/tutorial/05-IO-Create-Insert-External-Data.ipynb
docs/tutorial/06-ComplexFiltering.ipynb
docs/tutorial/07-Analytics-Tools.ipynb
docs/tutorial/08-Geospatial-Analysis.ipynb
docs/user_guide/extending/elementwise.ipynb
docs/user_guide/extending/reduction.ipynb
shell.nix

docs(notebooks): fix extending notebooks

---

poetry.lock
pyproject.toml
requirements.txt

This PR allows conda to solve for gdal instead of specifying it explicitly for conda-lock.

chore(deps): let conda solve for gdal

---

docker-compose.yml
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/clickhouse/datatypes.py
ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/clickhouse/tests/test_operators.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/clickhouse/tests/test_types.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/postgres/datatypes.py
ibis/backends/tests/test_array.py
ibis/expr/datatypes/core.py
ibis/tests/benchmarks/test_benchmarks.py
ibis/tests/expr/test_datatypes.py
poetry.lock
pyproject.toml
setup.py

This PR adds type parsing and serialization for ClickHouse, as well as fixes existing issues with nullable clickhouse types.

feat(clickhouse): add proper type serialization

---

ibis/backends/clickhouse/registry.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_array.py
ibis/expr/analysis.py
ibis/expr/operations/arrays.py
ibis/expr/types/arrays.py

This PR adds an unnest API. Closes #1146.

feat(api): unnest

---

docs/stylesheets/extra.css

docs: pin backend header and operation column

---

docs/tutorial/01-Introduction-to-Ibis.ipynb

Fix for the issue #3942.
Fixes #3942.

docs: fix SQLite's broken link on tutorial

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py

- test: add tests for and, or, and xor
- feat(sqlalchemy): add xor translation rule
- feat(pyspark): implement xor

feat: implement Xor where not already implemented and add tests

---

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_aggregation.py

feat(duckdb): implement arbitrary first and last aggregation

---

ibis/backends/base/sql/compiler/extract_subqueries.py
ibis/backends/base/sql/compiler/select_builder.py

This PR removes code found to be dead through coverage and experimentation. ExtractSubqueries is also simplified.

refactor: delete more dead code

---

ibis/backends/base/sql/registry/helpers.py
ibis/tests/sql/test_select_sql.py

fix(compiler): fix bool bool comparisons

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_numeric.py

- feat(clickhouse): implement clip
- style(clickhouse): make array translation rule args consistent
- feat(sqlalchemy): implement clip

feat: implement clip in most remaining backends

---

ibis/backends/duckdb/__init__.py

This PR cleans up some duplicated metadata handling code for DuckDB.

refactor(duckdb): clean up metadata handling

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py

- chore: remove line with no effect
- test(backend): add test for Where operation
- feat(pyspark): implement Where
- feat(sqlalchemy): implement Where

feat: implement ops.Where for remaining backends

---

ci/schema/clickhouse.sql
ci/schema/duckdb.sql
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/clickhouse/registry.py
ibis/backends/conftest.py
ibis/backends/dask/tests/conftest.py
ibis/backends/datafusion/tests/conftest.py
ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/impala/tests/conftest.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/pandas/client.py
ibis/backends/pandas/execution/structs.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/sqlite/tests/conftest.py
ibis/backends/tests/base.py
ibis/backends/tests/test_struct.py
ibis/expr/datatypes/core.py
ibis/expr/schema.py
ibis/tests/expr/test_literal.py

This PR adds the ability to retrieve fields from struct/tuples in the DuckDB and ClickHouse backends.

feat: implement struct field access for backends that support it

---

shell.nix

For those of us who can't remember the assorted incantations.

chore(nix): add shell shortcut to update reqs/lock files/setup.py

---

ibis/backends/clickhouse/tests/conftest.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/impala/tests/conftest.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/sqlite/tests/conftest.py
ibis/backends/tests/base.py

This PR deduplicates some of the database setup parameters in the backend test configuration classes.

refactor(test): deduplicate test configuration parameters

---

.github/workflows/ibis-backends.yml

Now that we have consolidated data loading for tests we can merge all the backend steps into a single job. This PR consolidates all the backend steps into a `test_backends` job.

ci: consolidate backends

---

ibis/backends/impala/tests/test_patched.py

This PR removes use of unittest.mock in favor of pytest-mock.

test(impala): use pytest for mocking impala

---

poetry-overrides.nix

This PR removes more poetry overrides from the corresponding file.

chore(deps): remove more poetry overrides

---

poetry-overrides.nix

This override is no longer necessary.

chore: remove unnecessary poetry override

---

ibis/expr/types/structs.py
ibis/tests/expr/test_struct.py

feat: add `__getattr__` support to `StructValue`

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_aggregation.py

- test(backends): add aggregate-with-predicate backend test
- fix(datafusion): handle predicates in aggregates

fix(datafusion): handle predicates in aggregates

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

- test(duckdb): add `file://` prefix test
- test(duckdb): add gz test
- test(duckdb): test register with name that requires quoting
- fix(duckdb): handle multiple dotted extensions; quote names; consolidate implementations
This PR fixes a couple issues with the current duckdb `register` implementation.
1. `\w+` was used to parse paths, when in actuality paths can be arbitrary bytes.
1. Similarly for extensions, `\w+` prevents `.csv.gz` from being parsed as an extension
1. Table names that require quotes such as `fancy stones` are now quoted
I also did a bit of consolidation of the implementations where it made sense, for example `csv` and `csv.gz`.

fix(duckdb): handle multiple dotted extensions; quote names; consolidate implementations

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/base/sql/registry/window.py
ibis/backends/clickhouse/registry.py
ibis/backends/pandas/execution/window.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_window.py
ibis/expr/operations/analytic.py
ibis/expr/types/generic.py

I didn't get this working with PySpark but it seems like the rest are
doing ok.
Resolves #3590

feat(api): add cume_dist operation

---

.coveragerc
codecov.yml

- Adds `__init__.py` files to those tracked by coverage
- Makes codecov checks more forgiving to slight decreases in coverage
Fixes #4252.

ci: Track `__init__.py` files in coverage

---

ibis/backends/base/__init__.py
ibis/backends/tests/test_api.py

This adds a `.tables` access to the `BaseBackend`. The main motivation here is tab-completion for table access when working with multiple tables in an interactive session. Tab completion works via both attribute and index access:
~Still needs tests/docs, just pushing this up for now to see if people like the idea.~

feat(api): add `.tables` accessor to `BaseBackend`

---

ibis/backends/duckdb/__init__.py

This PR returns the `ir.Table` object from calling `con.register` when using the DuckDB backend.

feat(duckdb): return the `ir.Table` instance from DuckDB's `register` API

---

docs/blog/Ibis-version-3.1.0-release.md
docs/stylesheets/extra.css
justfile

This is a PR to add a release blogpost for Ibis version 3.1.0.

Ibis v3.1.0 Release Blogpost

---

.github/workflows/check-generated-files.yml
ci/release/verify.sh
poetry.lock
requirements.txt
shell.nix

This PR fixes an issue that causes the automated release to fail.

chore: regenerate lockfiles

---

ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/test_aggregation.py

fix(pandas): fix `contains` with a filter inside of `group_concat`

---

ibis/backends/mysql/tests/test_client.py

test(mysql): check that we correctly infer blob types from sqlalchemy

---

ibis/backends/base/sql/registry/main.py
ibis/backends/base/sql/registry/timestamp.py
ibis/backends/pandas/execution/temporal.py
ibis/backends/tests/test_temporal.py

Reopened https://github.com/ibis-project/ibis/pull/4272

fix(pandas): use localized UTC time for now operation

---

docs/how_to/duckdb_register.md

Adding a how-to for using `register` with the duckdb backend
xref #4385

docs: add how-to for ibis+duckdb register

---

ibis/expr/operations/analytic.py
ibis/expr/operations/core.py
ibis/expr/operations/generic.py
ibis/expr/operations/relations.py
ibis/expr/operations/sortkeys.py
ibis/expr/operations/temporal.py
ibis/expr/types/analytic.py
ibis/expr/types/arrays.py
ibis/expr/types/binary.py
ibis/expr/types/generic.py
ibis/expr/types/geospatial.py
ibis/expr/types/logical.py
ibis/expr/types/maps.py
ibis/expr/types/numeric.py
ibis/expr/types/relations.py
ibis/expr/types/sortkeys.py
ibis/expr/types/strings.py
ibis/expr/types/structs.py
ibis/expr/types/temporal.py
ibis/expr/visualize.py
ibis/tests/expr/test_operations.py
ibis/tests/expr/test_udf.py
ibis/tests/expr/test_value_exprs.py
ibis/tests/expr/test_visualize.py

refactor(ir): resolve circular imports so operations can be globally imported for types

---

ibis/expr/analysis.py
ibis/expr/operations/relations.py
ibis/expr/schema.py
ibis/tests/expr/test_format.py

refactor(ir): remove sch.HasSchema and introduce ops.Projection base class for ops.Selection

---

ibis/expr/analysis.py
ibis/expr/operations/analytic.py
ibis/expr/operations/core.py
ibis/expr/operations/relations.py
ibis/expr/types/relations.py

refactor(ir): remove node.blocks() in favor of more explicit type handling

---

docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md

docs: fix markdown

---

.pre-commit-config.yaml
ibis/backends/base/sql/compiler/select_builder.py
ibis/common/grounds.py
ibis/common/tests/conftest.py
ibis/common/tests/test_grounds_py310.py
ibis/expr/operations/core.py
ibis/tests/expr/conftest.py
ibis/tests/expr/test_operations_py310.py

feature(common): support python 3.10 pattern matching on Annotable nodes

---

.gitignore
ibis/backends/impala/__init__.py
ibis/backends/impala/udf.py

fix(impala): add date column dtype to impala to ibis type dict

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/clickhouse/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/sqlite/registry.py
ibis/backends/sqlite/udf.py
ibis/backends/tests/test_generic.py
ibis/expr/operations/numeric.py
ibis/expr/types/numeric.py
ibis/tests/expr/test_value_exprs.py

I wanted to leave this issue for onboarding, but it of course turned out to be quite a slog. Closes #866.

feat: add elementwise bit operations

---

ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/backends/pandas/tests/test_udf.py

perf(pandas): remove reexecution of alias children

---

ibis/backends/pandas/client.py
ibis/backends/pandas/tests/test_datatypes.py

This PR adds support for inferring pandas string dtypes

feat(type-system): infer pandas' string dtype

---

docs/blog/ffill-and-bfill-using-ibis.md
docs/how_to/ffill_bfill_w_window.md
justfile
lychee.toml

- docs: added how to bfill and ffill
- docs: updated how to guide
- docs: blog addition how to trim

docs: how-to bfill and ffill

---

ibis/backends/clickhouse/datatypes.py
ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/dask/execution/maps.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/maps.py
ibis/backends/tests/test_map.py
ibis/expr/operations/maps.py
ibis/expr/types/maps.py
ibis/tests/expr/test_literal.py
ibis/tests/expr/test_value_exprs.py

feat(pandas,dask,clickhouse): revamp Map type support

---

ibis/backends/base/sql/registry/main.py
ibis/backends/dask/execution/strings.py
ibis/backends/pandas/execution/strings.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_string.py

This PR fixes existing or adds missing implementations of the StringReplace operation to various backends.

feat: round out StringReplace implementations

---

docs/CODE_OF_CONDUCT.md

docs: add coc reporting information

---

docs/backends/DuckDB.md

Closes #4503.
Here's what it looks like rendered.

docs(duckdb): add installation note for duckdb >= 0.5.0

---

poetry-overrides.nix

This PR removes some poetry overrides that have since been upstreamed to poetry2nix.

chore: remove unnecessary poetry overrides

---

docs/index.md

The example seemed incorrect to me. I guess this is the correct fix.
Thanks!

chore: fix homepage example code

---

ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/tests/test_types.py

This adds a new `type_map` kwarg to `ibis.sqlite.connect` for overriding type reflection. Since SQLite doesn't have string types, people use all sorts of names for their types, and not all of them are handled properly by ibis/sqlalchemy.
For example, a `STRING` SQLite type will be inferred by sqlalchemy as a `NUMERIC` type (based on the [type affinity rules](https://www.sqlite.org/datatype3.html#type_affinity)) - and `ibis` will then treat this incorrectly as a `Decimal` type.
To work around this, users can pass in a `type_map` option. This takes a mapping between SQLite types (as strings) and the corresponding ibis types they map to.
For example:
```python
con = ibis.sqlite.connect("some.db", type_map={"STRING": "string"})
```
~Builds on #4507~, fixes #4505.

feat(sqlite): add `type_map` arg to override type reflection

---

ibis/expr/types/core.py
ibis/expr/visualize.py

fix(visualize): dedup nodes and edges and add `verbose` argument for debugging

---

ibis/backends/tests/test_client.py

This PR fixes an assumption in ibis.connect tests that there is a file called ibis_testing.ddb laying around. Here, we use pytest to create a per-test temporary test database for both duckdb and sqlite.
An example of this kind of failure this addresses is [here](https://github.com/ibis-project/ibis/actions/runs/3096917348/jobs/5013012333).

fix(test): ensure that file-based url tests don't expect data to exist

---

ibis/backends/tests/test_client.py
ibis/tests/expr/test_value_exprs.py

test: move `test_repr_html` to backend test suite

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This adds support for passing a callable to `Table.relabel`, instead of just a mapping. This is mainly useful for relabeling all columns in a table with some common naming scheme (e.g. adding a prefix/suffix, lowercasing, etc...).
I found myself wanting this mainly when joining multiple tables together that all had conflicting column names - relabeling before the join avoids the need to mess with the `suffixes` kwarg to `join`, and makes it clearer which column belongs to which table.
```python
In [2]: items = ibis.table({"name": "string", "price": "float"}, name="item")
In [3]: items.relabel(lambda n: f"item_{n}")
Out[3]: 
r0 := UnboundTable: item
name  string
price float64
Selection[r0]
selections:
item_name:  r0.name
item_price: r0.price
```

feat: support passing callable to relabel

---

ibis/backends/duckdb/__init__.py

I've tested this locally and it works.  
There are some (hopefully minor) issues.  
> One, DuckDB doesn't use the aws sdk -- so auth (if required) must be set via some SQL commands.  I've added in a very brittle shim here to support the common environment variables, but this won't work for `credentials` files or via roles on an EC2 instance, etc.  Once DuckDB is using the aws sdk to handle auth, that can all be ripped out.
Non-issue using `pyarrow.dataset`
> Two -- not sure how we'd like to test this.  I can go to town with some mocks, but I'm not entirely sure of the utility.  Open to suggestions.
Not going to test it, really, since it's mostly testing string parsing
> Three -- passing in a glob works, because we pass it through to `duckdb`, but we currently can't resolve what the glob …

feat(duckdb): enable registration of parquet files over http or s3

---

nix/default.nix
poetry-overrides.nix

This PR enables s3fs for pyarrow in the nix environment.

chore(deps): add s3fs to pyarrow build

---

ibis/expr/format.py
ibis/tests/expr/test_format.py

fix: fix expression repr for table -> value operations

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

feat: support tab completion for getitem access of table columns

---

nix/sources.json
poetry.lock

Fixing up the broken simulate release job
Fixes #4697

chore(nix): update nixpkgs and poetry.lock

---

nix/default.nix

Fixes the failing docs build on master

ci(docs): fix build

---

ibis/backends/base/__init__.py

docs: improve the docstring of the generic connect method

---

docs/SUMMARY.md
docs/ibis-for-pandas-users.ipynb

I suggested that it might be nice if there was documentation for people coming from pandas in the same way that you have a document for SQL programmers. I started a notebook that outlines most of the issues that I came across when attempting to port projects from pandas to Ibis. This might be a good starting point for that suggested doc.

feat(docs): first draft of Ibis for pandas users

---

ibis/expr/api.py
ibis/tests/expr/test_value_exprs.py

fix(api): support deferred input to `ibis.desc` and `ibis.asc`

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

Fixes #4729
It doesn't seem like a huge performance penalty to re-reflect views on initial creation.

fix(duckdb): rereflect sqla table on re-registration

---

docker/postgres/Dockerfile

Update the postgres docker image to the latest major release of postgres (15).

ci: test against postgres 15

---

ibis/backends/tests/test_window.py

This is a follow up to #4734.
I didn't actually test the thing I meant to test in that PR, added here.

test(backend): actually test a window function inside of coalesce

---

nix/sources.json
poetry-overrides.nix

Removes some unused package overrides in the nix setup

build: remove unused poetry overrides

---

ibis/backends/polars/__init__.py
ibis/backends/polars/tests/conftest.py

``` python
[ins] In [1]: import ibis
[ins] In [2]: import pandas as pd
[ins] In [3]: con = ibis.polars.connect()
[ins] In [4]: df = pd.DataFrame(
...:     {
...:         "value": [1, 2, 3, 4, 5],
...:         "group": ["a", "b", "b", "b", "a"],
...:     }
...: )
[ins] In [5]: ibis.options.interactive = True
[ins] In [6]: con.register(df, table_name="pandas")
Out[6]: 
┏━━━━━━━┳━━━━━━━━┓
┃ value ┃ group  ┃
┡━━━━━━━╇━━━━━━━━┩
│ int64 │ string │
├───────┼────────┤
│     1 │ a      │
│     2 │ b      │
│     3 │ b      │
│     4 │ b      │
│     5 │ a      │
└───────┴────────┘
[ins] In [7]: con.register("/home/gil/data/databog/imdb_ratings.parquet", table_name="ratings")
Out[7]: 
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ tconst    ┃ averageRating ┃ numVotes ┃ …
```

refactor(polars): match duckdb registration api

---

ibis/expr/operations/relations.py
ibis/tests/expr/test_table.py

feat: support deferred predicates in join

---

nix/default.nix
poetry-overrides.nix
shell.nix

This PR cleans up some unnecessary nix code.

refactor: cleanup a few nix things

---

.github/workflows/ci-data.yml
.github/workflows/ibis-backends.yml
.github/workflows/update-deps.yml
.pre-commit-config.yaml
nix/default.nix

This PR adds a GitHub Actions linter [`actionlint`](https://github.com/rhysd/actionlint) to our pre-commit hooks

ci: add `actionlint` github actions linter

---

.github/workflows/ibis-backends.yml

This PR fixes the failing MySQL backend test.

ci: make sure `geospatial` extra is installed with `mysql` backend

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_temporal.py

Hello,
Ibis:
```python
ibis.time(16, 20, 0)
```
Snowflake SQL:
```sql
SELECT time_from_parts(16, 20, 0) AS "TimeFromHMS(16, 20, 0)"
```

feat(snowflake): implement `time` literal

---

docs/how_to/sessionize.md

- docs: added how to sessionzie guide
- docs: updated guide
see #4385

docs(how-to): sessionization

---

docs/how_to/sessionize.md

This PR edits the sessionization how-to to use the parquet data source, fix typos, and leverage deferred for more concision.

docs(how-to): use parquet data source for sessionization, fix typos, more deferred usage

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This PR adds support for out of core execution with in-memory duckdb connections by setting `temp_directory` to a default location.
Many Linuxen now default to `tmpfs` as the filesystem for the directory pointed to by `$TEMPDIR`, and `tmpfs` is effectively ramdisk, so we use `XDG_CACHE_HOME` to have a least a shot at hitting actual disk for spilling.
Resolves #4857.

feat(duckdb): support out of core execution for in-memory connections

---

.github/workflows/ibis-backends.yml
.github/workflows/ibis-main.yml
poetry.lock
pyproject.toml

fix(deps): bound shapely to a version that doesn't segfault

---

ibis/expr/visualize.py

fix(visualize): handle join predicates in visualize

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

fix(duckdb): s3 priority

---

.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-main-skip-helper.yml
.github/workflows/ibis-main.yml
README.md
docs/backends/MSSQL.md
docs/backends/index.md

This PR adds an mssql backend page alongside the rest.

docs: add mssql backend page

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_temporal.py

fix(snowflake): snowflake now likes Tuesdays

---

ibis/backends/tests/test_temporal.py

Enable an XPASS-ing test for day of week column expressions.

feat(snowflake): enable day-of-week column expression

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This adds support for registering external postgres tables with duckdb, using the [postgres_scanner](https://duckdb.org/2022/09/30/postgres-scanner) extension. Example:
```python
con = ibis.connect("duckdb://")
t = con.register("postgres://localhost:5432", "mytable")
```
Filters are pushed down into the backing postgres engine when possible, limiting the amount of data loaded into duckdb to perform queries against the external tables. It's pretty slick that this works at all :).
A few warts:
- The latest release of the `postgres_scanner` extension is buggy. These bugs are fixed on master, but not yet released. I've written the code here to work as if they were released, but to test locally you need to build and load the extension yourself.
- This API works _ok_ with `register`, but …

feat(duckdb): support registering external postgres tables with duckdb

---

ibis/backends/bigquery/udf/__init__.py
ibis/compat.py

This PR removes some dead compatibility code.

refactor: remove dead `compat.py` module

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/duckdb/__init__.py
ibis/expr/types/core.py

we return RecordBatchReader, not an iterable
h/t @wjones127

docs: fix pyarrow batches docstring

---

ibis/backends/tests/test_client.py

Fixes a test that is flaky with the mssql backend.

test(mssql): fix test so that ordering is consistent

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/tests/test_client.py

fix(clickhouse): fix list_tables to use database name

---

ibis/backends/tests/test_aggregation.py
ibis/backends/trino/registry.py

any, all, and friends, plus some correlation and covariance.

feat(trino): add some basic aggregation ops

---

ibis/backends/mysql/registry.py
ibis/backends/pandas/client.py
ibis/backends/tests/test_temporal.py
ibis/backends/trino/registry.py

- test(mysql): add failing milliseconds extraction test
- fix(mysql): handle out of bounds timestamps and fix milliseconds calculation

fix: fix out of bounds timestamp handling and fix milliseconds calculation in the mysql backend

---

ibis/expr/format.py
ibis/tests/expr/test_format.py

Fixes #5007 if there's actually anything to fix.

fix(repr): don't repeat value in repr for literals

---

flake.lock
poetry-overrides.nix

Removes some poetry2nix overrides that have since been upstreamed.

chore(dev-deps): remove upstreamed poetry2nix overrides

---

ibis/backends/postgres/registry.py

Hello,
We have an auxiliary function that will generate the full code of this function, so we can get rid of specialized implementation.
In addition, we gain support for backends that do not support reduction filter syntax.
https://github.com/ibis-project/ibis/blob/40ef35ee974f79d6132cc44c089fc430b17283a5/ibis/backends/base/sql/alchemy/translator.py#L79-L87
Best regards

Simplify ops.ArrayColumn in Postgres backend

---

ibis/backends/mysql/compiler.py
ibis/backends/mysql/registry.py
ibis/backends/snowflake/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_aggregation.py
ibis/backends/trino/registry.py
ibis/expr/operations/logical.py

Hi.
Thanks to this, we have a slightly simpler generated SQL code.
Best regards

Implement ops.Where using IF/IFF/IIF functions

---

ibis/backends/base/sql/alchemy/registry.py

Hi.
I forgot about this backend. 
Similar to: https://github.com/ibis-project/ibis/pull/5026
Best regards,
Kamil

refactor: simplify ops.ArrayColumn in alchemy backend

---

.github/workflows/ibis-backends.yml
flake.nix

This PR bumps our java version in CI and in the nix shell.

chore(deps): bump testing jdk to 17

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

fix(select): raise error on attempt to select no columns in projection

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml
flake.nix
nix/overlay.nix

Fixes the failing docs push job and removes some more unnecessary nix code.

build(docs): fix broken docs builds and remove unnecessary `ibisDocsEnv`

---

docs/ibis-for-pandas-users.ipynb
docs/ibis-for-sql-programmers.ipynb
flake.nix
mkdocs.yml

Fix the tutorial notebook rendering. Closes #5066.

fix(docs): make sure data can be downloaded when building notebooks

---

ibis/backends/base/sql/alchemy/registry.py

Hello,
The current error message contained too little detail, so it adds information about the condition values.
Best regards,
Kamil

feat(sql): improve error message in fixed_arity helper

---

ibis/backends/bigquery/registry.py
ibis/backends/tests/test_aggregation.py

Add support for correlation to the BigQuery backend.

feat(bigquery): add support for correlation

---

ibis/backends/bigquery/registry.py
ibis/backends/tests/test_aggregation.py

Add support for argmin and argmax to the BigQuery backend.

feat(bigquery): implement `argmin` and `argmax`

---

ibis/backends/bigquery/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/postgres/registry.py
ibis/backends/tests/test_array.py
ibis/backends/trino/registry.py

Add support for array repeat to the BigQuery backend.

feat(bigquery): implement array repeat

---

docker-compose.yml
docker/trino/catalog/memory.properties
ibis/backends/tests/test_client.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_sql.py
ibis/backends/tests/test_struct.py
ibis/backends/trino/__init__.py
ibis/backends/trino/compiler.py
ibis/backends/trino/datatypes.py
ibis/backends/trino/registry.py
ibis/backends/trino/tests/conftest.py

This PR adds support for struct field access and constructing structs to the Trino backend.

feat(trino): add struct operations

---

ci/schema/clickhouse.sql
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/tests/test_map.py
ibis/backends/trino/datatypes.py
ibis/backends/trino/registry.py
ibis/backends/trino/tests/conftest.py

This PR adds support for map operations to the Trino backend.

feat(trino): implement map operations

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_string.py
ibis/backends/trino/registry.py

This PR implements `parse_url` for snowflake and trino, and adds support for a few more values of `extract` for the clickhouse backend.

feat: implement `parse_url` for more backends

---

ibis/backends/tests/test_string.py
ibis/backends/trino/registry.py

Add regex operations to the trino backend.

feat(trino): implement regex functions

---

ibis/backends/snowflake/registry.py

Fixes some failing implementations of the new URL extraction APIs.

fix(snowflake): fix failing snowflake url extraction functions

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/pandas/execution/arrays.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/test_struct.py
ibis/tests/expr/test_rules.py
ibis/tests/expr/test_udf.py
pyproject.toml

Cleans up map/comprehension usage and adds the corresponding ruff style checks.

style: clean up `map` and comprehension usage

---

ibis/backends/bigquery/__init__.py

Upstreams changes made in https://github.com/ibis-project/ibis-bigquery/pull/153 to fix some issues encountered with certain combinations of ibis-bigquery and ibis.
Fixes https://github.com/ibis-project/ibis-bigquery/issues/152

fix(bigquery): don't try to parse database when name is already fully qualified

---

docs/tutorial/01-Introduction-to-Ibis.ipynb
docs/tutorial/02-Aggregates-Joins.ipynb
docs/tutorial/03-Expressions-Lazy-Mode-Logging.ipynb
docs/tutorial/04-More-Value-Expressions.ipynb
docs/tutorial/06-ComplexFiltering.ipynb
docs/tutorial/07-Analytics-Tools.ipynb
docs/user_guide/extending/elementwise.ipynb
docs/user_guide/extending/reduction.ipynb
flake.nix
ibis/backends/conftest.py
nix/ibis.nix

Remove some superfluous environment variables and their use.

cleanup envars

---

poetry.lock
pyproject.toml

Add support for support shapely v2.

feat(deps): support shapely 2.0

---

.github/workflows/ibis-backends.yml

Run MSSQL tests in series to see if that reduces the flaky schema-getting test.

test(mssql): run tests serially, refactor GHA conditionals

---

ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/registry.py
ibis/backends/bigquery/tests/conftest.py
ibis/backends/tests/test_json.py

Add JSONGetItem support to BigQuery.

feat(bigquery): implement JSON getitem functionality

---

.github/workflows/ibis-backends.yml

This change is to help us diagnose flaky MSSQL tests.
https://github.com/ibis-project/ibis/actions/runs/3873334785/jobs/6603235557

ci: display docker compose logs on failure

---

docs/SUMMARY.md
docs/blog/ibis-version-4.0.0-release.md

- docs: added 4.0 release blog post
- docs: update
- docs: update

blog v4 release

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_numeric.py

Follow-up: https://github.com/ibis-project/ibis/pull/5182

Fix snowflake tests after deleting unsupported operations

---

ibis/expr/operations/logical.py
ibis/tests/expr/test_value_exprs.py

fixes https://github.com/ibis-project/ibis/issues/5191

fix(ir): ops.Where output shape should consider all arguments

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/compiler/translator.py
ibis/backends/base/sql/registry/main.py
ibis/expr/operations/core.py
ibis/expr/schema.py
ibis/expr/types/core.py
ibis/util.py

Use an empty string to encode unnamed.

refactor(ir): remove UnnamedMarker

---

ci/schema/clickhouse.sql
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/datatypes.py
ibis/backends/clickhouse/tests/conftest.py
ibis/backends/clickhouse/tests/test_operators.py
ibis/backends/datafusion/tests/conftest.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/tests/base.py

This PR add support for native boolean types in the clickhouse backend

feat(clickhouse): properly support native boolean types

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/conftest.py
ibis/backends/clickhouse/__init__.py
ibis/backends/tests/test_export.py
ibis/expr/types/core.py

Implement `to_pyarrow` for the BigQuery backend.

feat(bigquery): add to_pyarrow method

---

docs/backends/support_matrix.md
gen_matrix.py

Hello,
I want to analyze this data on my own, so I'm adding a CSV link with raw data.
Love,

docs: publish raw data for operation matrix

---

ibis/backends/tests/test_client.py
ibis/config.py

- test(backend): add default backend setting and reading test
- fix(backend): read the default backend setting in `_default_backend`

fix(backend): read the default backend setting in `_default_backend`

---

ibis/common/tests/test_validators.py
ibis/common/validators.py

feat(common): support annotations with typing.Literal

---

docs/backend_info_app.py

This PR adds the Python code for the streamlit backend operation matrix app. Once this is merged, I can deploy it and embed the app in our docs.

docs: add streamlit app for showing the backend operation matrix

---

ibis/backends/duckdb/__init__.py

I am not sure if this ever worked, but now it does!

fix(duckdb): make `read_csv` on URLs work

---

docs/backends/app/backend_info_app.py
gen_matrix.py

Hello,
Now this script can be much simpler.

docs: clean up gen_matrix.py after adding streamlit app

---

ibis/backends/snowflake/registry.py

This PR fixes a failing snowflake backend test for the typeof API.

feat(snowflake): implement typeof operation

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/datatypes.py
ibis/backends/sqlite/tests/test_client.py
ibis/backends/tests/test_dot_sql.py

feat(sqlite): implement `_get_schema_using_query` in SQLite backend

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_string.py

This PR adds array aggregation and string splitting to the snowflake backend.

feat(snowflake): more array operations

---

ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_sql.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_struct.py
ibis/backends/tests/test_temporal.py
ibis/backends/tests/test_window.py
ibis/expr/api.py
ibis/expr/operations/temporal.py

This PR adds some more ops and fixes an uncovered bug in the PySpark backend that showed up after a test refactor.

feat(snowflake): more ops

---

justfile

This PR adds a convenience command `just reup [container]` that makes it more concise to restart one or more services.

chore(dev): stop and start containers with a single command

---

ibis/backends/tests/test_temporal.py

This PR fixes a failing test on `master`.

test(snowflake): xfail ns test

---

.gitattributes
docs/backends/app/backend_info_app.py
docs/backends/app/requirements.txt

Hello,
To show how Ibis can be used with Streamlit, I rewrote our application to use Ibis.
Best regards

chore: rewrite streamlit app to use Ibis

---

docs/backends/app/backend_info_app.py

This PR fixes an issue where the duckdb backend tries to install extensions which streamlit cloud does not seem approve of.

docs(backend-info): prevent app from trying install duckdb extensions

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/datatypes.py

This PR removes the need for a complex parser for snowflake types. Based on [the snowflake Python connector documentation](https://docs.snowflake.com/en/user-guide/python-connector-api.html#label-python-connector-type-codes).

refactor(snowflake): remove the need for `parsy`

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This PR adds support for reading sqlite tables using the DuckDB backend.

feat(duckdb): add support for reading sqlite tables

---

README.md

A small PR to adjust a bit of prose in the readme and fix a typo.

docs(README.md): clean up readme, fix typos, alter the example

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/duckdb/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/mysql/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/postgres/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/snowflake/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/sqlite/out.sql
ibis/backends/tests/snapshots/test_sql/test_group_by_has_index/trino/out.sql
ibis/tests/sql/test_sqlalchemy.py

This PR refactors `struct_pack` in the duckdb backend and deduplicates a bit of code in CASE statement translation.

refactor(duckdb): clean up struct packing and case statement translation

---

ibis/backends/snowflake/__init__.py

This PR fixes an issue where we are trying to use snowflake pyarrow integration without pyarrow installed at all.

fix(snowflake): handle the case where pyarrow isn't installed

---

ibis/backends/pandas/client.py

This PR fixes an issue where a dispatch of `dt.dtype` was attempted on the `ArrowDtype` object, which is not available until pandas 1.5.0.

fix(pandas): don't try to dispatch on arrow dtype if not available

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_map.py

This PR uses snowflake javascript UDFs to fill out the remaining map functionality.

feat(snowflake): implement remaining map functions

---

docs/how_to/sessionize.md

docs: remove duplicate "or"

---

docs/backends/app/backend_info_app.py

Quick fix for a URL we missed in the de-versioning.

docs(streamlit): fix url for support matrix

---

ibis/backends/polars/datatypes.py
ibis/backends/polars/tests/test_datatypes.py

This PR fixes inference for polars categorical dtype. Closes #5439.

fix(polars): properly infer polars categorical dtype

---

ibis/expr/types/arrays.py

This PR adds concrete examples to the array expression API.

docs: array expression examples

---

.pre-commit-config.yaml
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/bigquery/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/mssql/registry.py
ibis/backends/mysql/registry.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/test_string.py
ibis/backends/trino/registry.py

This PR fixes an issue where an extra character was sneaking in to some capitalize implementations.

fix(backends): fix capitalize implementations across all backends

---

docs/blog/ibis_substrait_to_duckdb.md

docs(blog): specify parsy 2.0 in substrait blog article

---

ibis/expr/types/generic.py

This PR improves the searchability (by referencing names from other systems) and clarity (by providing executable examples) of the `Column.collect` method.

docs(api): improve `collect` method API documentation

---

ibis/backends/clickhouse/__init__.py

Fixes a bug where memtables were not being registered before calling `to_pyarrow` et al.

fix(clickhouse): register in-memory tables in pyarrow-related calls

---

.github/workflows/ibis-backends-cloud.yml

This PR adds CI for snowflake that hits the pyarrow bits.

ci(snowflake): add pyarrow job

---

.github/workflows/ibis-backends-cloud.yml

This PR sets up caching for virtualenvs for the cloud backend CI.

ci(cloud): cache virtualenvs where possible

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-main-skip-helper.yml
.github/workflows/ibis-main.yml
.github/workflows/ibis-tpch-queries-skip-helper.yml
.github/workflows/ibis-tpch-queries.yml
.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml

Adds the necessary config to make merge queues work.

ci: enable merge groups

---

.github/workflows/ibis-backends.yml
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/tests/test_uuid.py
ibis/backends/trino/datatypes.py
ibis/backends/trino/registry.py

This PR adds support for sqlalchemy 2 to the trino backend.

feat(trino): support sqlalchemy 2

---

ibis/backends/postgres/tests/test_client.py

This test assumed `functional_alltypes` existed before it ran, but that
isn't always the case. Here I make sure that the table exists by
creating a one-off table and verifying metadata laziness with that.

test(postgres): fix flaky test

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/literal.py
ibis/backends/bigquery/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/pandas/client.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/registry.py

Fix backend implementations of NULL literal handling. Closes #5520.

fix(backends): fix null literal handling

---

ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/snowflake/__init__.py

This PR sets ibis-required parameters once per connection instead of once per transaction. This should cut down the number of database calls and simplifies the code a bit.

refactor(sqlalchemy): set session parameters once per connection

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/tests/test_array.py
ibis/backends/trino/registry.py
ibis/expr/operations/arrays.py
ibis/expr/operations/core.py
ibis/expr/types/arrays.py
ibis/tests/expr/test_value_exprs.py

```py
a = ibis.array([1, 2, 3])
r = a.map(lambda x: x * 2.1)
assert r.type() == dt.Array(dt.float64)
```
Just a quick prototype for now, adding more thorough validation, testing and implementation for some backends.
cc @cpcloud @NickCrews

feat(ir): implement `ArrayMap` operation

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/trino/registry.py
ibis/common/annotations.py
ibis/common/tests/test_annotations.py
ibis/common/tests/test_validators.py
ibis/common/validators.py
ibis/expr/operations/arrays.py
ibis/expr/operations/core.py
ibis/expr/rules.py
ibis/tests/expr/test_value_exprs.py

depends on https://github.com/ibis-project/ibis/pull/5515

refactor(ir): update `ArrayMap` to use the new `callable_with` validation rule

---

ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_param.py

I noticed that we don't have any test for this operation.

test(backend): add test for ops.Between

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/tests/test_array.py
ibis/backends/trino/registry.py
ibis/expr/operations/arrays.py
ibis/expr/types/arrays.py

This PR implements an array filtering API. DuckDB, Trino and ClickHouse implementations are provided.

feat: implement array filtering operation

---

ibis/backends/base/sql/compiler/base.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/expr/analysis.py
ibis/tests/sql/snapshots/test_sqlalchemy/test_where_correlated_subquery_with_join/out.sql

refactor(analysis): slightly simplify `find_subqueries()`

---

ibis/backends/impala/tests/snapshots/test_sql/test_limit_cte_extract/out.sql
ibis/expr/analysis.py
ibis/tests/sql/snapshots/test_select_sql/test_bug_project_multiple_times/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_join_with_limited_table/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_limit_cte_extract/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_topk_analysis_bug/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_topk_operation/e1.sql
ibis/tests/sql/snapshots/test_select_sql/test_topk_operation/e2.sql
ibis/tests/sql/snapshots/test_select_sql/test_topk_predicate_pushdown_bug/out.sql

depends on https://github.com/ibis-project/ibis/pull/5575

fix(analysis): extract `Limit` subqueries

---

ibis/interactive.py
pyproject.toml

This PR adds an `ibis.interactive` module that is explicitly designed to be star-imported, including the option-setting side-effect, for maximum interactive use convenience.
It is expressly *not* for any kind of production or pipeline use and named in such a way that hopefully makes that obvious.
```
In [4]: from ibis.interactive import *
In [5]: t = ibis.read_json("/data/test/products.jsonl")
In [6]: t
Out[6]:
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ sku    ┃ desc                                                                            ┃ baseprice ┃ weight_kg ┃ dims_cm              ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━ …
```

feat(ux): easy interactive setup

---

ibis/backends/base/sql/compiler/select_builder.py

Apparently we had the world's most complex `tuple` to `list` converter laying around.

chore: remove dead code

---

ibis/backends/snowflake/__init__.py

Makes the cross schema concurrent test runs more reliable by always setting the initial database/schema if needed.

test(snowflake): reduce flakiness of concurrent cross schema tests

---

ibis/backends/tests/test_set_ops.py

Shoring up flaky snowflake tests yet again.

test: avoid memtable in set ops testing to prevent unreliable snowflake random string generation

---

ibis/backends/base/__init__.py
ibis/common/collections.py
ibis/common/tests/test_collections.py
ibis/expr/datatypes/core.py
ibis/expr/datatypes/tests/test_core.py
ibis/expr/operations/core.py
ibis/expr/operations/relations.py
ibis/expr/operations/window.py
ibis/expr/schema.py
ibis/expr/tests/test_rules.py
ibis/expr/tests/test_schema.py
ibis/tests/expr/test_table.py

TODOs:
Resolves https://github.com/ibis-project/ibis/issues/5546

feat(common): add abstract mapping collection with support for set operations

---

ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_dot_sql.py

add support for alias() in snowflake.

feat(snowflake): add support for alias in snowflake

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml
.github/workflows/nix.yml
.github/workflows/release.yml
.github/workflows/update-deps.yml

Fixed in the latest release of the cachix/install-nix-action

chore(nix): remove cachix install nix workaround

---

docker/druid/environment

This PR increases the RAM constraints for the druid services.

ci: cut down the druid RAM requirements even more

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR adds support for selectors in the `Table.drop` method

feat: accept selectors in `Table.drop`

---

ibis/backends/postgres/tests/conftest.py

Small PR to improve the dev experience for serial postgres test execution.

test(postgres): make serial test execution faster

---

.gitignore
ibis/backends/tests/test_temporal.py

ci(bigquery): fix broken pytest run

---

ibis/tests/expr/test_selectors.py

fix(ci): fix invalid test id

---

ibis/backends/tests/test_generic.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This is a PR to discuss a [`pivot_longer`](https://tidyr.tidyverse.org/reference/pivot_longer.html)-style API for table expressions. Ideally this can go into 5.0, but the main purpose is to generate discussion around working code. Depends on #5662.

feat(table): `pivot_longer` API

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/mssql/registry.py
ibis/backends/tests/test_temporal.py
ibis/backends/trino/registry.py

To detect some hidden issues, I added stricter exceptions validation.

Normalize exceptions in backends

---

ibis/backends/base/sql/compiler/translator.py
ibis/backends/impala/tests/snapshots/test_sql/test_join_key_name/out.sql
ibis/backends/impala/tests/snapshots/test_sql/test_nested_join_multiple_ctes/out.sql
ibis/tests/sql/snapshots/test_compiler/test_table_drop_with_filter/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_complex_union/result.sql
ibis/tests/sql/snapshots/test_select_sql/test_subquery_in_union/out.sql
ibis/tests/sql/snapshots/test_select_sql/test_subquery_used_for_self_join/out.sql
ibis/tests/sql/snapshots/test_sqlalchemy/test_gh_1045/out.sql
ibis/tests/sql/snapshots/test_sqlalchemy/test_lower_projection_sort_key/out.sql
ibis/tests/sql/snapshots/test_sqlalchemy/test_tpc_h11/out.sql
ibis/tests/sql/test_select_sql.py

Fixes an issue where we were generating duplicate aliases.
Fixes #5708.

fix(compiler): be less clever about generating aliases

---

ibis/backends/tests/test_set_ops.py
ibis/expr/types/relations.py

Add support for single argument set operations. Closes #5715.

feat(api): allow single argument set operations

---

ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/tests/test_join.py

This PR fixes the failing cloud backend tests coming from the new join-from-memtable functionality added in #5722.

fix(bigquery): ensure that memtables are translated correctly

---

ibis/expr/types/relations.py

docs: clean up agg argument descriptions and add join examples

---

ibis/backends/bigquery/tests/system/test_client.py
ibis/expr/datatypes/parse.py
ibis/expr/datatypes/tests/test_parse.py

Close: https://github.com/ibis-project/ibis/issues/5765

feat(bigquery): support bignumeric type

---

.pre-commit-config.yaml
flake.nix

Add a deadnix pre-commit check for unused nix code.

build: add deadnix to pre-commit-hooks

---

ibis/backends/duckdb/__init__.py

This PR uses duckdb as the source of truth for loading extensions instead of ibis. This PR is part of an effort to fix backend-construction-time configuration that showed up as part of https://github.com/ibis-project/ibis/issues/5784. Passing `ibis.duckdb.connect(..., s3_endpoint=...)` fails because the configuration option is only available if the `httpfs` extension is loaded. There will be one more PR after this to address that issue.

refactor(duckdb): source loaded and installed extensions from duckdb

---

ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_client.py

This PR adds support for caching to the PySpark backend

feat(pyspark): support basic caching

---

ibis/backends/bigquery/__init__.py

This PR makes use of bigquery APIs to allow proper record batch emission without first materializing into a pyarrow Table.

feat(bigquery): make `to_pyarrow_batches()` smarter

---

docs/SUMMARY.md

We forgot to add the blog to SUMMARY.md

docs(blog): add campaign finance to `SUMMARY.md`

---

ibis/backends/tests/test_client.py
ibis/expr/types/pretty.py

feat: default repr to showing all columns in Jupyter notebooks

---

ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/trino/registry.py

This PR fixes a flaky snowflake test for the new distinct API.

test(snowflake): fix arbitrary comparisons

---

.github/workflows/ibis-backends.yml
poetry.lock
pyproject.toml

This PR removes the unnecessary pyarrow extra

chore(deps): remove unnecessary pyarrow extra

---

docs/getting_started.md

Followup to #5812, addressing some comments from @jcrist

docs: style and review fixes in getting started guide

---

ibis/backends/duckdb/tests/conftest.py
ibis/backends/duckdb/tests/test_register.py

Hopefully this should fix the last of the extension loading issues

test(duckdb): make remaining tests pass through extension load on init

---

ibis/backends/duckdb/tests/test_register.py

These tests are still failing, I think this should fix the issue.

test(duckdb): run register tests with a load group

---

docs/getting_started.md
ibis/examples/CITATIONS.md

Added to examples citations and also to getting started page.

docs(penguins): add citation for palmer penguins data

---

docs/getting_started.md

A trivial (but hopefully fun) change to these great intro docs. No offence taken if this isn't merged.

docs(penguins): change to flipper

---

ibis/backends/base/__init__.py
ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/duckdb/tests/test_register.py
ibis/backends/polars/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_register.py
ibis/expr/api.py
ibis/util.py

If this does not address the issue then I will skip these tests on windows.

ci: give each duckdb process outside of the backend suite its own extensions directory

---

ibis/expr/types/groupby.py
ibis/expr/types/relations.py

docs: add warning about comparisons to `None`

---

ibis/backends/snowflake/__init__.py

This PR brings back the higher performance memtable support.

fix(snowflake): make sure pyarrow is used when possible

---

.github/workflows/ibis-backends.yml

Otherwise we can end up with solve that incorrectly passes tests

ci(pyspark): be more specific with tested versions

---

docker-compose.yml

Small PR to add health checks for the last two services that did not have them.

chore(docker): add health checks for kudu

---

docs/community/contribute/01_environment.md
docs/stylesheets/extra.css
mkdocs.yml

Refresh the environment setup pages to reflect the current state of ibis.

docs: refresh environment setup pages

---

ci/schema/duckdb.sql
ibis/backends/duckdb/compiler.py
ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/registry.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/pandas/client.py
ibis/backends/tests/test_json.py
ibis/backends/tests/test_map.py
ibis/backends/tests/test_param.py

feat(duckdb): map operations

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py

Follow up fixes to the new array APIs.

fix(snowflake): fix new array operations; remove `ArrayRemove` operation

---

ibis/expr/types/logical.py

Examples for `notany` and `notall` are incomplete because of this: https://github.com/ibis-project/ibis/issues/5988

docs: improve docstrings for BooleanValue and BooleanColumn

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

Resolves #5981 
I opted for the `attach_sqlite` method because I imagine someone will request an equivalent `attach_postgres` at some point.

feat(duckdb): add attach_sqlite method

---

ibis/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/impala/tests/test_client.py

fix(impala): expose `hdfs_connect` function as `ibis.impala.hdfs_connect`

---

ibis/backends/snowflake/__init__.py
ibis/expr/types/maps.py

Small PR to indicate that our custom JavaScript functions are pure and that they return NULL on NULL input.

refactor(snowflake): add flags to supplemental JavaScript UDFs

---

ibis/backends/sqlite/registry.py
ibis/backends/tests/test_aggregation.py

Since version [3.7.11]( http://www.sqlite.org/releaselog/3_7_11.html), SQLite supports queries of the form:
```sqlite
SELECT max(x), y FROM table
```
that:
> returns the value of y on the same row that contains the maximum x value.
The same applies to the min aggregate function. 
This solution combines the max (min) aggregate function with the JSON functions: [json_array](https://www.sqlite.org/json1.html#jarray) and [json_extract](https://www.sqlite.org/json1.html#jex) to first build an array: `[y, max(x)]` from the aggregate and then extract `y`.

feat(sqlite): add argmin and argmax functions

---

ibis/backends/bigquery/tests/conftest.py

This PR skips bigquery tests that require auth when auth fails with a 403

ci: skip bigquery tests when auth fails

---

ibis/backends/bigquery/client.py
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/bigquery/tests/unit/test_datatypes.py

This change can fix #6043.
Fixes #6043.

fix(bigquery): add srid=4326 to the geography dtype mapping

---

ibis/expr/types/generic.py

Filling in a few more examples in docstrings.

docs(generic): add docstring examples in types/generic

---

ibis/expr/types/arrays.py
ibis/expr/types/core.py
ibis/expr/types/logical.py
ibis/expr/types/relations.py
ibis/expr/types/structs.py

This PR cleans up a few docstrings.

docs: fill out more docstrings

---

ibis/backends/bigquery/tests/system/conftest.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/bigquery/tests/system/udf/test_udf_execute.py

Fixes the failing tests upstream

test(bigquery): rename client fixture to con

---

ibis/backends/tests/test_window.py

Fixes the xpassing test upstream

test(bigquery): enable xpassing test

---

ibis/expr/api.py

docs: add allowed input for memtable constructor

---

ibis/expr/types/relations.py

docs: change plural variable name cols to col

---

ibis/backends/pandas/execution/generic.py
ibis/backends/tests/test_aggregation.py

fix(pandas): grouped aggregation using a case statement

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/mysql/datatypes.py
ibis/backends/mysql/tests/test_client.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/snapshots/test_string/test_rlike/sqlite/out.sql

fix(mysql): handle zero timestamps

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/duckdb/registry.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_aggregation.py
ibis/expr/operations/reductions.py
ibis/expr/types/numeric.py

This PR adds a `median` API to numeric columns

feat(api): exact median

---

ibis/common/patterns.py
ibis/common/tests/test_patterns.py

These matchers enable matching node hierarchies in either top-down or bottom-up fashion, e.g.:
```py
Topmost(InstanceOf(ops.Reduction)) # to locate the reduction node if any
Innermost(InstanceOf(ops.TableNode))  # to locate the root table
```

feat(common): add `Topmost` and `Innermost` pattern matchers

---

ibis/backends/duckdb/__init__.py
ibis/backends/snowflake/__init__.py

This PR fixes an issue where a RecordBatchReader produced by DuckDB
via ibis can outlive the ibis backend, and therefore its connection, causing a variety of fun problems.
I saw all of these errors while debugging this:
- double free
- corrupt doubly linked list
- sigsegv
- sigill (illegal instruction)
- sigabrt
Ultimately it was looking at a core dump from GDB showing the failing call was
a decref on an apparently already-freed DataFrame (from a `PandasScan` node)
that convinced me there was still a lifetime issue.
The approach I took, which I believe should be sufficient to guarantee that the
connection lives at least as long as the RecordBatchReader, is to use a
generator inside of a context manager created by `sa.Engine.begin()`. That way,
the generator's termination is commensurate …

fix(duckdb): ensure connection lifetime is greater than or equal to record batch reader lifetime

---

ci/schema/druid.sql
ci/schema/postgresql.sql
docker-compose.yml
ibis/backends/clickhouse/tests/conftest.py
ibis/backends/druid/tests/conftest.py
ibis/backends/mssql/tests/conftest.py
ibis/backends/postgres/tests/conftest.py

This PR cleans up a bit of testing code and unnecessary volume mounts in the docker-compose setup.

test: clean up data loading; remove service spec where possible

---

justfile

Small fix for just download-data

chore: use upstream testing data

---

ibis/backends/base/sql/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py
ibis/backends/snowflake/__init__.py
ibis/expr/analysis.py

feat(duckdb): warn when querying an already consumed RecordBatchReader

---

ibis/expr/api.py
ibis/tests/expr/test_temporal.py

Also does some general UX cleanups and test coverage for this utility.
Fixes #5983.

feat(api): allow passing multiple keyword arguments to `ibis.interval`

---

ibis/backends/impala/client.py

Fixes #6141
Currently, ibis conceals the impala error message by replacing it with the message "Operation is in ERROR_STATE". This can be avoided by relying on the impyla cursor to handle waiting synchronously for results, using nearly identical existing functionality that does not conceal the error.
Impyla's `HiveServer2Cursor._wait_to_finish` method [here](https://github.com/cloudera/impyla/blob/db67498e0a4e833b64e5e070272be2fcbd36f443/impala/hiveserver2.py#L411) handles waiting for results, even using the same sleep intervals [here](https://github.com/cloudera/impyla/blob/db67498e0a4e833b64e5e070272be2fcbd36f443/impala/hiveserver2.py#L464). We can simply wrap this in our `KeyboardInterrupt` handling and we get the wait functionality for free, and we no longer lose the text of the error …

refactor(impala): rely on impyla cursor for _wait_synchronous

---

ibis/expr/types/numeric.py

not done, but I didn't want to lose track of this branch

doc(numeric): add examples to numeric methods

---

docs/backends/app/backend_info_app.py

Add oracle to the backend matrix.

docs(oracle): add oracle to matrix

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

fix(duckdb): fix problem with kwargs

---

docs/SUMMARY.md
docs/backends/support_matrix.md
docs/example_streamlit_app/example_streamlit_app.py
docs/example_streamlit_app/requirements.txt
docs/how_to/streamlit.md
docs/stylesheets/extra.css
ibis/streamlit/__init__.py

This PR adds a tiny implementation of the new experimental streamlit connection API, supporting streamlit apps that use this interface.

feat(streamlit): add support for streamlit connection interface

---

ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/window.py
ibis/backends/pandas/tests/execution/test_window.py

fix(pandas): fix first and last over windows

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/snapshots/test_string/test_rlike/bigquery/out.sql

Fixes the failing cloud backend `master` builds.

fix: fix failing upstream bigquery and snowflake ci

---

ibis/backends/mysql/registry.py
ibis/backends/mysql/tests/test_client.py

fix(mysql): ensure that enum operations return the correct type
