.coveragerc
.gitignore
scripts/run_jenkins.sh

Coverage data gets reported to codecov.io/github/cloudera/ibis
Fixes #598.

TST: Added coverage computation on jenkins runs

---

docs/source/api.rst
ibis/client.py
ibis/expr/tests/mocks.py
ibis/expr/tests/test_interactive.py
ibis/expr/types.py
ibis/impala/tests/test_client.py
ibis/sql/sqlite/tests/test_client.py

Enhances usability and gives a way to compile or validate expressions without executing them

ENH: add compile and verify methods to Expr. Close #608

---

ibis/impala/client.py

https://github.com/cloudera/ibis/pull/875 Introduced a problem where the cursor connections in the connection pool were no longer being released on the impala connection close. This adds back that functionality.

Fixed an issue where connections weren't being closed

---

ibis/impala/client.py

If I understand what is supposed to happen here, it looks like the message has been updated.
```
Traceback (most recent call last):
File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/impala/client.py", line 206, in _close_cursor
self._cursor.close()
File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/impala/hiveserver2.py", line 197, in close
self.close_operation()
File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/impala/hiveserver2.py", line 212, in close_operation
self._reset_state()
File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/impala/hiveserver2.py", line 221, in _reset_state
self._last_operation.close()
File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/impala/hiveserver2.py", …
```

There is a new exception for already closed

---

requirements.txt

https://github.com/pytest-dev/pytest/issues/1889
pytest >= 3.0 introduced a bug where conftest is being loaded multiple times. This is causing the tests to fail to run.

Pin to <= 2.9.2

---

ibis/expr/api.py
ibis/expr/operations.py
ibis/pandas/execution.py
ibis/pandas/tests/test_client.py
ibis/pandas/tests/test_core.py
ibis/pandas/tests/test_operations.py
ibis/sql/postgres/compiler.py

ENH: Implement array ops for pandas

---

ibis/bigquery/compiler.py
ibis/clickhouse/operations.py
ibis/expr/api.py
ibis/expr/operations.py
ibis/mapd/operations.py
ibis/mapd/tests/conftest.py
ibis/mapd/tests/test_operations.py
ibis/pandas/execution/generic.py

This fixes #1680 by adding support for the `arbitrary` aggregate in MapD by mapping it to the `SAMPLE` function.

[OmniSci/MapD] Add support for arbitrary aggregate

---

README.md

Update MapD references to OmniSci

Update README reference to MapD to say OmniSci

---

azure-pipelines.yml
ibis/bigquery/tests/test_compiler.py
ibis/expr/tests/test_value_exprs.py
ibis/expr/window.py
ibis/impala/compiler.py

Before this PR, calls like
```python
ibis.window(preceding=(None, 1))  # ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
ibis.window(following=(1, None))  # ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING
```
would fail because of incorrect usage of comparison operators, comparing
``None`` to another value that is not ``None`` raising a ``TypeError``.
This PR addresses the problem.

BUG: Fix preceding and following with None

---

docs/source/developer.rst

Fixes error in documentation, issue #1774
The following command in `developer.rst` no longer works for two reasons. One, the YAML file no longer exists. Two, creating a conda environment from YAML needs to be done with `conda env create` instead of `conda create`.
Failing instruction:
`conda create -n ibis36 -c conda-forge --file=ci/requirements-dev.yml python=3.6`
Should now be:
`conda env create -n ibis36 -f ci/requirements-3.6-dev.yml`

Fixes DOC: conda create command listed no longer works

---

ibis/clickhouse/tests/test_functions.py
ibis/impala/tests/test_partition.py
ibis/pandas/execution/temporal.py
ibis/tests/all/conftest.py
ibis/tests/all/test_aggregation.py
ibis/tests/all/test_generic.py
ibis/tests/all/test_temporal.py
ibis/tests/all/test_window.py
setup.cfg

This PR makes all `XPASS`ing tests pass in the typical way, by customizing the
behavior of two fixtures `xfail_backends` (all listed backends are permitted to
fail) and `xpass_backends` (all backends *not* listed are permitted to fail)
I've also added `xfail_strict = true` to `setup.cfg` to make sure that we don't introduce any `XPASS`ing tests in the future. Of course, that's always up for debate in the future but I think there's probably a way to customize `xfail`s similar to what I've done here such that we don't need to have any future `XPASS`es.

Clean up most xpassing tests

---

Makefile
ibis/bigquery/compiler.py
ibis/bigquery/udf/tests/test_udf_execute.py
ibis/expr/analysis.py
ibis/file/client.py
ibis/file/tests/test_csv.py
ibis/file/tests/test_hdf5.py
ibis/file/tests/test_parquet.py
ibis/pandas/aggcontext.py
ibis/pandas/client.py
ibis/pandas/core.py
ibis/pandas/dispatch.py
ibis/pandas/execution/generic.py
ibis/pandas/execution/selection.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/execution/window.py
ibis/pandas/tests/test_udf.py
ibis/sql/compiler.py
ibis/sql/postgres/compiler.py
ibis/tests/all/test_window.py

ENH: Rewrite pandas execution to use topological sort instead of recursion

---

ci/Dockerfile.dev
ci/Dockerfile.docs
ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
setup.py

@ian-r-rose Can you take a look at this and make sure that it matches our discussion re OmniSci on #1796?

BUG/CI/BLD: Fix Python 3.5 dependency versions

---

ibis/mapd/api.py
ibis/mapd/client.py
ibis/mapd/tests/conftest.py
ibis/mapd/tests/test_client.py

`pymapd` recently gained the ability to connect via a pre-authenticated session ID. It would be nice if the Ibis mapd connector could do that as well. cc @xmnlab

Mapd session

---

Makefile
ibis/expr/analysis.py
ibis/expr/api.py
ibis/expr/tests/test_analysis.py
ibis/expr/tests/test_table.py
ibis/expr/types.py
ibis/tests/backends.py

Closes #1799
This was kind of a nasty one. The query flattening optimization was far too
aggressive.
@toryhaavik Do you feel comfortable reviewing this?
One downside to this fix is that simple, single expression columns are not flattened into their subquery anymore. This will be addressed in the future after the compiler is refactored.

BUG: Chained mutate operations give wrong results

---

ibis/expr/tests/test_window_functions.py
ibis/expr/window.py

This constitutes one step of several required to extend Ibis trailing window functionality, where trailing_window will become more extensible to support various types of 'preceding' parameters. In this first step, trailing_window is able to handle not only integers but ibis intervals as well, using the type of the 'preceding' parameter to determine the 'how' of the window.

consolidate trailing window functions

---

azure-pipelines.yml
ci/requirements-3.5-dev.yml
conftest.py
ibis/bigquery/tests/test_datatypes.py
ibis/bigquery/udf/tests/test_core.py
ibis/bigquery/udf/tests/test_find.py
ibis/clickhouse/tests/test_select.py
ibis/impala/tests/test_metadata.py
ibis/sql/postgres/compiler.py
ibis/sql/postgres/tests/test_functions.py
ibis/sql/sqlite/tests/conftest.py
ibis/sql/sqlite/tests/test_functions.py
ibis/tests/all/test_temporal.py
setup.cfg

Also address the warnings about unknown marks coming from newer versions of
pytest
Closes #1699
Closes #1808

BUG: Fix failing strftime tests on Python 3.7

---

ci/feedstock.py

This enables easier testing of feedstock fixes.

SUPP: Allow passing a branch to ci/feedstock.py

---

ibis/expr/api.py
ibis/expr/tests/test_window_functions.py
ibis/expr/window.py
ibis/impala/tests/test_window.py
ibis/pandas/execution/tests/test_window.py

Support row-based trailing windows bound by a maximum look-back period

Accept rows-with-max-lookback as preceding parameter

---

ibis/expr/tests/test_window_functions.py
ibis/expr/window.py

See issue: https://github.com/ibis-project/ibis/issues/1832

allow pandas timedelta in rows_with_max_lookback

---

ibis/expr/tests/test_window_functions.py
ibis/expr/window.py

BUG: Add max_lookback to window replace and combine functions

---

.isort.cfg
ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
dev/genrelease.py
setup.py

Example run:
```
$ dev/genrelease.py 1.2.0
* :release:`1.2.0 2019-06-19`
* :bug:`1842 major` Add max_lookback to window replace and combine functions
* :bug:`1837 major` Partially revert #1758
* :support:`1839` Tighter version spec for pytest
* :support:`1838` allow pandas timedelta in rows_with_max_lookback
* :support:`1825` Accept rows-with-max-lookback as preceding parameter
* :support:`1786` PostGIS support
* :support:`1826` Allow passing a branch to ci/feedstock.py
```

SUPP: Generate release notes from commits

---

ibis/expr/operations.py
ibis/expr/tests/test_window_functions.py
ibis/impala/tests/test_window.py
ibis/pandas/execution/tests/test_window.py
ibis/sql/postgres/tests/test_functions.py

SUPP: Validate order_by when using rows_with_max_lookback window

---

ibis/expr/datatypes.py
ibis/expr/format.py
ibis/expr/operations.py
ibis/expr/tests/test_value_exprs.py

BUG: Fix nested array literal repr

---

ibis/expr/api.py
ibis/expr/datatypes.py
ibis/expr/operations.py
ibis/expr/tests/test_geospatial.py
ibis/mapd/operations.py
ibis/tests/all/test_geospatial.py
ibis/tests/backends.py

Add 2 new geo spatial functions to OmniSciDB backend:
- set_srid
- transform
Add a cast to geographic type

FEAT: Add new geospatial functions to OmniSciDB backend

---

ibis/expr/window.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/execution/window.py

Without this exception external clients will be able to use rows_with_max_lookback with pandas

Remove pandas exception for rows_with_max_lookback

---

ibis/expr/tests/test_window_functions.py
ibis/expr/window.py
ibis/pandas/aggcontext.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/execution/window.py

The offset interval specified in RowsWithMaxLookback should be used in the determination of each row's window, not just the first n rows. For the pandas backend, rolling apply can be used to implement this functionality.

FEAT: Use pandas rolling apply to implement rows_with_max_lookback

---

ci/azure/windows.yml

This is a workaround for the somewhat mysterious `flake8` failures on Windows
so that we can get green builds.

CI: Removing linting from windows

---

.pre-commit-config.yaml
Makefile
ci/azure/linux.yml
ci/azure/windows.yml
ci/datamgr.py
ci/docker-compose.yml
ci/load-data.sh
ibis/sql/postgres/__init__.py
ibis/sql/postgres/client.py
ibis/sql/postgres/compiler.py
ibis/sql/postgres/tests/conftest.py
ibis/sql/postgres/tests/test_postgis.py
ibis/sql/postgres/tests/test_udf.py
ibis/sql/postgres/udf/__init__.py
ibis/sql/postgres/udf/api.py
setup.cfg

The following functionality is included: 
* ability to use user-defined functions (UDFs) 
* ability to use UDFs that are already defined in the database (I just want to refer to them and use them)
* ability to wrap a python function, automatically define it as a PL/Python function in the database, and be able to use it with ibis objects
* changed Docker image to support testing of Postgres PL/Python UDF functionality in the ibis test suite
* Tests for UDF functionality
The current API looks like this. Comments and feedback are welcome. 
```
import ibis.expr.datatypes as dt
from ibis.sql.postgres.udf.api import existing_udf, func_to_udf
my_udf = existing_udf(
'my_udf',
input_types=[dt.String()],
output_type=dt.Integer(),
schema='my_schema'
)
expr = …
```

FEAT: Add support for Postgres UDFs

---

.isort.cfg
ibis/common/geospatial.py
ibis/expr/datatypes.py
ibis/mapd/operations.py
ibis/spark/tests/test_udf.py
ibis/spark/udf.py
ibis/sql/alchemy.py
ibis/sql/postgres/compiler.py
ibis/tests/all/test_geospatial.py

In this PR:
- Add shapely geometries as input for literals
- add tests for shapely geometries as input for literals

FEAT: Add shapely geometries as input for literals

---

ibis/mapd/api.py
ibis/mapd/client.py
ibis/mapd/tests/test_client.py
ibis/tests/all/test_client.py

Currently, SQL expressions which contain a LIMIT statement trigger an exception from the Omnisci Validator, as 'LIMIT 1' is used in the get_schema_using_query routine.  
`Exception: Sort node not supported as input to another sort`
This PR introduced a BUGFIX which utilizes the built in mapd sql_validate routine, and associated thrift type mappings to build the schema via direct reference, without the one line query.
UPDATE:
- added regex to remove `;`
- added tests using raw sql queries
-  set option 'default_limit' to `None` to avoid default `LIMIT 10000`

BUG: `sql` method doesn't work when the query uses LIMIT clause

---

ibis/omniscidb/client.py
ibis/omniscidb/tests/test_client.py

In this PR:
- Fixes explain operation
Resolves #1921 
Depends on #1928

BUG: Fixes explain operation

---

ibis/pyspark/compiler.py
ibis/tests/all/test_string.py

This PR implements column operations and string operations for the PySpark backend to pass all/test_column.py and all/test_string.py tests.
String operations not implemented and skipped:
- find_in_set - no equivalent behavior in Pyspark

ENH: PySpark backend string and column ops

---

ibis/expr/schema.py

SUPP: More informative IntegrityError on duplicate columns

---

ibis/pandas/execution/generic.py

SUPP: Remove pandas deprecation warnings

---

ibis/pyspark/compiler.py
ibis/pyspark/tests/test_basic.py
ibis/tests/all/test_window.py

Implemented window operations for PySpark backend to pass all tests in `ibis/tests/all/test_window.py`:
- `WindowOp`
- `Lag`
- `Lead`
- `MinRank`
- `DenseRank`
- `NTile`
- `FirstValue`
- `LastValue`
- `RowNumber`
- `CumulativeSum`
- `CumulativeMean`
- `CumulativeMin`
- `CumulativeMax`
Also enhanced select aggregation operations (e.g. `Any`, `NotAny`, `All`, `NotAll`, `Count`, `Max`, `Min`, `Mean`, `Sum`) to be interoperable with windows.

ENH: window operations for pyspark backend

---

ibis/pyspark/compiler.py
ibis/pyspark/tests/test_basic.py

Introduces predicate handling in `ops.Selection` for `filter()` functionality.
Also implemented a few missing comparison operations:
- `And`
- `Or`
- `NotEquals`
- `Less`
- `LessEquals`

ENH: filter for PySpark backend

---

docs/source/contributing.rst

DOC: Developer doc enhancements

---

ibis/file/csv.py
ibis/pyspark/compiler.py
ibis/pyspark/tests/test_basic.py
ibis/tests/all/test_join.py
ibis/tests/backends.py

Implement join functionality for PySpark backend. This PR only enables tests/all/test_join.py

ENH: Implement join for PySpark backend

---

ibis/tests/all/test_join.py

Strangely, `pytest.mark.only_on_backends` doesn't skip BigQuery, so I added an explicit skip as a workaround.

SUPP: Disable BigQuery explicitly in all/test_join.py

---

ibis/pyspark/api.py
ibis/pyspark/client.py
ibis/pyspark/compiler.py
ibis/tests/all/test_client.py

Pass ibis/all/test_client.py and ibis/all/test_params.py
test_params.py is partially supported

ENH: Add support for params, query_schema, and sql in PySpark backend

---

ibis/pyspark/compiler.py
ibis/pyspark/tests/test_basic.py
ibis/tests/all/test_param.py
ibis/tests/all/test_temporal.py
ibis/tests/backends.py

Implemented date/time operations for PySpark backend to pass all supported tests in `ibis/tests/all/test_temporal.py`.
Features that are supported:
- `Date`
- `Timestamp`
- Date and time extraction
- Date and timestamp truncation
- Timestamp now
- String to timestamp
- Timestamp to formatted string - `strftime`
- Day of week index
- Day of week name
- Date add, subtract
- Timestamp add, subtract
- Interval add, subtract
Additional operations implemented to pass `test_temporal.py`:
- `cast`
- `limit`
- `array` index
Features that are not supported:
- `ms`, `us`, `ns` time units - unsupported in native PySpark sql functions
- non-literal `interval` (e.g. casting an integer column to an interval column) - this is because there is no timedelta type in PySpark
- Date and timestamp diff - …

ENH: Add support for date/time operations in PySpark backend

---

ibis/pyspark/compiler.py
ibis/tests/all/test_generic.py

Passes all/test_generic.py and also fixes #1957

ENH: Implement sort, if_null, null_if and notin for PySpark backend

---

ci/azure/linux.yml
ci/check-services.sh
ibis/expr/datatypes.py
ibis/sql/alchemy.py
ibis/sql/postgres/tests/test_client.py
ibis/sql/tests/test_sqlalchemy.py

Fixes #1944. This does *not* add support for JSON, JSONB, and UUID PostgreSQL types. Instead, it marks them as having `dt.Any` type, allowing the tables to be loaded, and those columns mostly ignored.
There is also some black formatting on some lines I didn't touch...

Json UUID any

---

Makefile
ci/azure/linux.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
ibis/pyspark/compiler.py
ibis/pyspark/tests/conftest.py
ibis/pyspark/tests/test_array.py
ibis/pyspark/tests/test_basic.py
ibis/tests/all/test_temporal.py

SUPP: Add black step to CI

---

ibis/sql/alchemy.py
ibis/sql/postgres/tests/test_client.py

Possible fix for #1273 
Adds default precision and scale to decimal types for PostgreSQL and MySQL. Numeric data types without defined precision and scale are allowed in these dialects (even if it is recommended that you specify them), and these tables exist in the wild.
I'm not sure if this is the best fix, but I was hoping to get a conversation started.

ENH: SQLAlchemy Default precision and scale to decimal types for PostgreSQL and MySQL

---

ibis/pyspark/compiler.py

Removing `compile_with_scope()` in favor of caching all operations in `scope` during `translate()`. Caching only select operations with `compile_with_scope()` is error prone. This change ensures we don't compile the same operation more than once.

PySpark backend: cache all ops in translate()

---

ibis/pyspark/compiler.py
ibis/tests/all/test_window.py

Implemented `preceding` and `following` window boundaries for PySpark backend.
Also, added tests in `ibis/tests/all/test_window.py` that tests bounded windows. (note: filed issue #2000 for incorrect behavior in Pandas, Csv, and Parquet backends)

ENH: Pyspark backend bounded windows

---

ci/azure/linux.yml
ci/requirements-3.5-dev.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
conftest.py
ibis/__init__.py
ibis/_version.py
ibis/client.py
ibis/common/exceptions.py
ibis/compat.py
ibis/config.py
ibis/config_init.py
ibis/filesystems.py
ibis/omniscidb/__init__.py
ibis/omniscidb/api.py
ibis/omniscidb/client.py
ibis/omniscidb/compiler.py
ibis/omniscidb/ddl.py
ibis/omniscidb/identifiers.py
ibis/omniscidb/operations.py
ibis/omniscidb/tests/__init__.py
ibis/omniscidb/tests/conftest.py
ibis/tests/all/test_geospatial.py
ibis/util.py
setup.py
versioneer.py

In this PR:
- Fixed omniscidb docstrings
- Fixed some docstrings
- Added pydocstyle check for ./ibis/.py and ./ibis/omniscidb/*.py
Current issues with pydocstyle:
- https://github.com/PyCQA/pydocstyle/issues/111
- https://github.com/PyCQA/pydocstyle/issues/363

FEAT: Add docstring check to CI for an initial subset files

---

ibis/sql/postgres/tests/test_udf.py
ibis/sql/postgres/udf/api.py

Other scalar types can be represented either by the class or an instance, but Array types work differently. Array types must be an instance, because the Array class must be instantiated specifying the datatype of the elements of the array. This was causing an error in the translation.
```
ibis/sql/postgres/tests/test_udf.py:176 (test_array_type)
con_for_udf = <ibis.sql.postgres.client.PostgreSQLClient object at 0x11eb3ada0>
test_schema = 'udf_test_18'
table = PostgreSQLTable[table]
name: udf_test_users
schema:
user_id : int32
user_name : string
name_length : int32
def test_array_type(con_for_udf, test_schema, table):
"""Test that usage of Array types work
Other scalar types can be represented either by the class or an instance,
but Array types work differently. Array types must be an …
```

BUG: Fix handling of Array types in Postgres UDF

---

ibis/pyspark/compiler.py

There are some code duplication in the current pyspark compiler. I cleaned up a bit.

ENH: Clean up window translation logic in pyspark backend

---

docs/source/release.rst
ibis/expr/window.py
ibis/pandas/aggcontext.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/tests/test_udf.py
ibis/spark/tests/test_udf.py
ibis/tests/all/test_window.py

Fix for issue #2000.
The `preceding` argument to `ibis.window()` and `ibis.trailing_window()` is an inclusive preceding bound. The `window` argument to `pandas.DataFrame.rolling()` is a window size.
Currently, pandas backends pass the preceding bound directly as the window size and do not adjust for the inclusive window bounds in ibis.
This PR implements the correct expected behavior and updates the pandas backend tests accordingly.

BUG: Fix pandas backends to have inclusive preceding window bound

---

ci/docker-compose.yml
docs/source/release.rst

This PR update omniscidb image tag from v4.7.0 to v.5.0.0 on docker-compose recipe.

Update omniscidb image version

---

docs/source/release.rst
ibis/omniscidb/client.py

[pymapd.connect](https://github.com/omnisci/pymapd/blob/0dceb144cca4e76ac06b795b2fe7a8040f91178b/pymapd/connection.py#L40) function doesn't have session_id argument so session_id was
replaced with sessionid

BUG: Fix argument in pymapd.connect calling

---

Makefile
benchmarks/benchmarks.py
docs/source/release.rst
ibis/pandas/aggcontext.py
ibis/pandas/execution/tests/test_arrays.py
ibis/pandas/tests/test_udf.py
ibis/pandas/udf.py

This PR addresses issue https://github.com/ibis-project/ibis/issues/1998
Currently, when using UDAF with rolling window, pandas backend will throw an exception:
```
import ibis
import pandas as pd
import numpy as np
from ibis.pandas.udf import udf
import ibis.expr.datatypes as dt
client = ibis.pandas.connect({'table': pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'key': ['a', 'a', 'a']})})
t = client.table('table')
w = ibis.trailing_window(preceding=1, order_by='key', group_by='key')
#w = ibis.window(group_by='key')
@udf.reduction(input_type=[dt.double, dt.double], output_type=dt.double)
def my_average(v, w):
return np.average(v, weights=w)
t = t.mutate(new_col=my_average(t.a, t.b).over(w))
t.execute()
```
With this PR, it will support this use case.
The main idea of this PR is that …

ENH: Support multi args window UDF for pandas backend

---

docs/source/api.rst
docs/source/backends.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/release.rst
ibis/pyspark/api.py
ibis/spark/api.py

In this PR:
- Added initial documentation for OmniSciDB, MySQL, PySpark and SparkSQL backends
- Added initial documentation for Geo Spatial methods 
- Added link to Ibis wiki page 
- Fixed PySpark and Spark connect docstring: `**kwargs` needed to be escaped.
xref  partially #2025

DOC: Add new backends and Geospatial methods to documentation

---

docs/source/release.rst
ibis/expr/operations.py
ibis/pandas/execution/tests/test_functions.py
ibis/pandas/udf.py
ibis/pyspark/compiler.py
ibis/tests/all/test_vectorized_udf.py
ibis/udf.py
ibis/udf/vectorized.py

One of Ibis' design goal is to have one common expression language that works for multiple backend execution engines. However, the current UDF api contradicts this design goal because the UDF is defined under per backend namespace (e.g., `ibis.pandas.udf`) and therefore, ibis program that contains UDF cannot move to another backend.
I propose to introduce a top level ibis UDF api, `ibis.udf.vectorized` to address this issue. Vectorized UDFs take vectorized data structure as input, this currently means `numpy.ndarray` `pd.Series` and `pd.DataFrame` and return Python scalar or vectorized data structure as output.
This is proposed as a very experimental API.
In this PR, I have made the following changes in particular:
- Introduced `ibis.udf.vectorized` namespace 
- Implemented elementwise …

FEAT: Introduce vectorized UDF api

---

docs/source/release.rst
ibis/omniscidb/client.py

BUG: Fix cudf import on OmniSciDB backend

---

docs/source/release.rst
ibis/omniscidb/operations.py
ibis/tests/all/test_window.py

In this PR, added the follow window operations:
- DenseRank
- PercentRank (that is translated to cume_dist)
- RowNumber
- MinRank
- Count

FEAT: Adding more window operations to OmniSciDB

---

docs/source/getting-started.rst
docs/source/release.rst
ibis/expr/tests/test_datatypes.py
ibis/pandas/aggcontext.py
ibis/pandas/tests/test_udf.py

This PR fixes a couple of issues with the documentation CI build that I noticed over in #2060 which are related to the recent Pandas 1.0 release (see https://dev.azure.com/ibis-project/ibis/_build/results?buildId=1791&view=logs&j=8f09edc2-e3b7-52de-126a-0225c4f3efa1&t=78a72aec-b398-558e-7c0d-2d33604b9e53&l=129)

CI: Fix CI builds related to new pandas 1.0 compatibility

---

ci/datamgr.py
docs/source/release.rst

BUG: fix datamgr.py fail if IBIS_TEST_OMNISCIDB_DATABASE=omnisci

---

ibis/pandas/tests/test_udf.py

This PR linked the current xfail tests in pandas/test/test_udf.py to the potential issues in pandas 1.0.0

TST: Link pandas issues with xfail tests in pandas/tests/test_udf.py

---

Makefile
ci/azure/linux.yml
ci/backends-to-start.sh
ci/datamgr.py
ci/load-data.sh
docs/source/release.rst

Main problem inside the string: `$(DOCKER_RUN) -e LOGLEVEL=$(LOGLEVEL) ibis ./ci/load-data.sh $(BACKENDS)`.  `BACKENDS` var  contains all the backends, but `./ci/load-data.sh` can load for specific backend. There was no error checking in this script and it was not noticeable.
<details><summary>
LinuxTest py36:Load test datasets before fix
</summary>
```
2020-02-02T19:27:46.1265072Z ##[section]Starting: Load test datasets
2020-02-02T19:27:46.1268292Z ==============================================================================
2020-02-02T19:27:46.1268531Z Task         : Bash
2020-02-02T19:27:46.1268634Z Description  : Run a Bash script on macOS, Linux, or Windows
2020-02-02T19:27:46.1268791Z Version      : 3.163.1
2020-02-02T19:27:46.1268894Z Author       : Microsoft Corporation …
```

BUG: Fix load data stage for Linux CI

---

docs/source/release.rst
ibis/pandas/core.py
ibis/pandas/execution/tests/test_functions.py
ibis/pandas/tests/test_udf.py
ibis/pandas/udf.py

Problem
--------
The existing pandas udf implementation suffers from huge performance problem when the udf takes many arguments. 
The problem is that, the existing implementation tries to register execution rules for every possible combination of argument types, resulting in an exponential growth execution rules (exponential to the number of udf arguments)
For an example, if a udf takes n arguments, it will ended register O(4^n) rules because each argument can take >4 different types, e.g., for floating numbers, (float, np.floating, pd.Series, pd.SeriesGroupBy) and the existing implementation tries to register the Cartesian product of those.
Proposed Solution
------------------
In this PR, the number of rules registered for a given number of arguments is reduced to 3. I.e., for a 10 …

FEAT: Improve pandas udf performance for many arguments

---

ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml

This is introduced in #2043 to get around the bug in rtree 0.9. Now I think this is no longer needed.

Unpin rtree version

---

ci/datamgr.py
ci/schema/omniscidb.sql
ibis/sql/postgres/tests/test_postgis.py
ibis/tests/all/test_geospatial.py

Different SRIDs aren't supported in Omnisci backend since [commit](https://github.com/omnisci/omniscidb/commit/ff6e70db3f01483700c04561b7c5e4ab44fcfcab) . [Exception](https://github.com/omnisci/omniscidb/blob/29e35f4d5804d193f225ff0b622b73c5b8cbd4ea/QueryEngine/RelAlgTranslatorGeo.cpp#L825) is occurred. Can't use transform func separately to change SRID in the database table so create new objects with the same default SRID.

[Omnisci] The same SRIDs for test_geo_spatial_binops

---

ibis/tests/backends.py

Make the user the possibility to define the connection port to the database, so check IBIS_TEST_OMNISCIDB_PORT env variable.

TST: Use user-defined port variables for Omnisci and PostgreSQL tests

---

.isort.cfg
.pre-commit-config.yaml
Makefile
ci/azure/linux.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
setup.cfg

isort 4.3.21 formatting conflicts in some cases with black. I am moving back isort to the previous pinning. 
also isort from master has a lot of formatting conflicts with black

SUPP: Pin back version of isort

---

ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
docs/source/getting-started.rst
docs/source/release.rst
setup.py

BUG: change clickhouse-driver version to >=0.1.3

---

ci/azure/linux.yml
ci/azure/windows.yml
ci/requirements-3.8-dev.yml
docs/source/release.rst
ibis/__init__.py
ibis/bigquery/udf/api.py
ibis/bigquery/udf/tests/test_core.py
ibis/bigquery/udf/tests/test_find.py
ibis/bigquery/udf/tests/test_udf_execute.py
ibis/compat.py
ibis/expr/datatypes.py
ibis/filesystems.py
ibis/impala/ddl.py
ibis/impala/kudu_support.py
ibis/pandas/aggcontext.py
ibis/spark/client.py
pyproject.toml

Resolves #2036 
this PR: 
- adds support to Python 3.8 without pyspark and pymapd*
- adds a udf pytest mark for bigquery.udf tests
- improves ci/azure/linux variables
- skip a doctest check on ibis.bigquery.udf for Python 3.8
`* package conflicts:`
- it needs pyspark v3 https://github.com/apache/spark/pull/26194#issuecomment-566592265
- it needs omniscidb/pymapd with pyarrow=0.15 support

SUPP: Add support to Python 3.8

---

ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
docs/source/release.rst
ibis/client.py
ibis/omniscidb/api.py
ibis/omniscidb/client.py
ibis/omniscidb/tests/test_client.py
setup.cfg

In this PR:
- Removed `execution_type` parameter and add `gpu_device: int` and `ipc: bool` for OmniSciDB backend (Resolves #1919)
- Fixed categorical data type issue when using `cudf.DataFrame` output (Resolves #1920 )
- add mock test for execution_type using pytest-mock

FEAT: Remove execution_type param and add gpu_device and ipc to execute method for OmniSciDB backend

---

ci/feedstock.py

Currently CI is failing for CondaBuild (see #2094). 
In this PR:
- Removed `pytest` from ci/feedstock

CI: Fix LinuxCondaBuild

---

docs/source/getting-started.rst

In the release notes I see that Python 3.5 support has been dropped, so I guess 3.6 is the minimum required...

Update minimum Python version in getting started page

---

docs/source/api.rst
docs/source/release.rst
ibis/expr/api.py
ibis/expr/operations.py
ibis/expr/random.py
ibis/sql/mysql/compiler.py
ibis/sql/postgres/compiler.py
ibis/tests/all/test_numeric.py

This PR adds an `ibis.random` function which returns a random number between 0 (inclusive) and 1 (exclusive). I've started with initial support for the postgresql and mysql backends
Closes #1450

Add initial support for ibis.random function

---

ibis/omniscidb/client.py

BUG: remove drop method

---

docs/source/release.rst
ibis/file/parquet.py
ibis/omniscidb/compiler.py
ibis/tests/all/test_aggregation.py

Resolve #1918 . Additionally fix #2129

BUG: [OmniSciDB] Fix TopK when used as filter

---

docs/source/release.rst
ibis/omniscidb/client.py
ibis/omniscidb/ddl.py
ibis/omniscidb/tests/test_client.py

continuation of #1977
The advantage of this approach is the avoidance of additional memory costs.
Problem:
- for test purpose I should have dataset inside omniscidb container. What the best way for this?

FEAT: Implement read_csv for omniscidb backend

---

docs/source/release.rst
ibis/expr/datatypes.py
ibis/expr/tests/test_schema.py

FEAT: Add non-nullable info to schema output

---

README.md
ci/docker-compose.yml
docs/source/getting-started.rst
ibis/tests/all/test_aggregation.py
ibis/tests/all/test_generic.py
ibis/tests/all/test_numeric.py
ibis/tests/all/test_temporal.py

Enable tests that use queries without table and another tests that are already working on OmniSciDB
* it depends on OmniSciDB v5.2

TST: OmniSciDB - Enable logical value tests

---

docs/source/release.rst
ibis/pyspark/compiler.py
ibis/pyspark/tests/test_basic.py

This PR fixes the bug where PySpark backend is enable to handle this express correctly:
```
table = ...
table = table[[col]]
table = table.mutate(col2=table[col])
```

BUG: Fix PySpark error when doing alias after selection

---

ibis/omniscidb/tests/test_client.py

'test_read_csv' added at #2062 uses `/omnisci` directory to store test files, however that dir may not exists at some other environments, which causes errors while testing.
Since test files used as temporary, it's rational to store them at `/tmp` dir, which is always exists in Linux environment, unlike `/omnisci`

fix path to temporary test files at 'test_read_csv'

---

docs/source/release.rst
ibis/omniscidb/operations.py
ibis/pandas/execution/temporal.py
ibis/sql/mysql/compiler.py
ibis/sql/postgres/compiler.py
ibis/tests/all/test_temporal.py

Fix #2167 
Fix #2166 
Fix #2168
Fix #2169

BUG: Fix millisecond issue for omniscidb, mysql, postgresql and pandas

---

ci/azure/linux.yml
ci/requirements-3.6-dev.yml
ci/requirements-3.7-dev.yml
ci/requirements-docs.yml
docs/source/getting-started.rst

Testing if splitting tests in this naive way solves the disk space problem. I guess docker images for the unused backends should not be download and storage consumption should be much less.

CI: Split tests in two groups by backend

---

ci/azure/linux.yml
ci/feedstock.py

Currently condabuild ci job is failing because:
- the current conda recipe doesn't work for python 3.8, because pymapd depends on pyarrow <= 0.13 and it has dependency conflict with another packages. also the current pyspark will not work well for python 3.8 (waiting pyspark v3) 
- as conda recipe uses noarch:python, and currently the conda build uses the python 3.8 to build, the build will have a very complex dependency tree to resolve
in this PR:
- I changed the repo and the branch used to get the conda recipe to check if the new recipe will work
- I added the `python` flag to `feedstock.py test` to specify the python version to conda-build 
notes:
- as can be observed, it worked. the time spent is not the desired yet (43m) but as the time limit is 1h, probably it is enough for now.
- …

Fix CondaBuild CI job

---

ibis/impala/tests/test_udf.py

No clue why flake8 started to fail the CI now (see #2206), but this fixes the problem.
CC: @jreback

CI: Fix flake8 errors

---

ci/azure/linux.yml

In #2206, the website is being built, with the docs in the `/docs/` directory, but I'm pushing the `/docs/` directory to GitHub pages, instead of the whole website.
This should fix it, and push both the website and the docs to docs.ibis-project.org

CI: Publish website instead of docs

---

ibis/filesystems.py
ibis/impala/client.py
ibis/impala/pandas_interop.py
ibis/impala/tests/test_ddl.py
ibis/impala/tests/test_parquet_ddl.py
ibis/impala/tests/test_partition.py
ibis/impala/tests/test_udf.py
ibis/spark/tests/test_ddl.py
ibis/tests/test_filesystems.py

I assume because a new version of isort, the CI is failing for wrong order of imports. I run the latest conda version of isort, and it made these changes.

CI: Running isort with the latest version to fix CI

---

docs/source/release/index.rst
ibis/impala/client.py
ibis/omniscidb/client.py
ibis/sql/alchemy.py
ibis/sql/postgres/tests/conftest.py
ibis/sql/postgres/tests/test_client.py
ibis/sql/sqlite/client.py
ibis/tests/all/test_client.py

In this PR:
- Added load_data 
- Allow database parameter for load/create/drop when database parameter is the same than the current database (fixes #1979)
- Added `has_attachment` to `AlchemyClient`, useful for some operations that need to use `schema` when database attachment is used, for example `to_sql`.

FEAT: Added load_data to sqlalchemy's backend

---

ibis/expr/operations.py
ibis/pandas/tests/test_udf.py
ibis/pandas/udf.py
ibis/pyspark/compiler.py
ibis/spark/udf.py
ibis/tests/all/test_vectorized_udf.py
ibis/udf/vectorized.py

This PR refactor `ibis.pandas.udf.reduction` and `ibis.pandas.udf.analytics` into `ibis.udf.vectorized`.
This is similar to the first vectorized UDF PR:
https://github.com/ibis-project/ibis/pull/2047

FEAT: Move ibis.pandas.udf.reduction and ibis.pandas.udf.analytics to ibis.udf.vectorized namespace

---

ibis/expr/operations.py
ibis/pandas/udf.py
ibis/udf/vectorized.py

This is a minor change about renaming. This was an over sight in https://github.com/ibis-project/ibis/pull/2210 that accidentally name 'analytic' to `analytics`. This PR fixes that.

BUG: Rename AnalyticsVectorizedUDF to AnalyticVectorizedUDF

---

docs/source/release/index.rst
ibis/omniscidb/operations.py

OmniSciDB - Add support to week extraction
ref: #1499

FEAT: OmniSciDB - Add support to week extraction

---

docs/source/release/index.rst
ibis/pyspark/compiler.py
ibis/spark/datatypes.py

The PySpark compiler will raise a
```
TypeError: 'NoneType' object is not callable
```
when trying to compile a `ElementWiseVectorizedUDF` node whose `output_type` argument is not in [this list](https://github.com/timothydijamco/ibis/blob/f92adea724da4c6a1af3887a8e3e0ff407e497a7/ibis/spark/datatypes.py#L10) (e.g. `Decimal` and `TimestampType` is not in the list)
This PR:
- Have the PySpark compiler use a more general conversion function (`spark_dtype` instead of `ibis_dtype_to_spark_dtype`)
- Allow `spark_dtype` to convert an Ibis `TimestampType` to an Spark `TimestampType` (add another dispatch function to `spark_dtype`)

BUG: PySpark compiler cannot compile elementwise UDF for some output types

---

docs/source/release/index.rst
ibis/bigquery/udf/api.py
ibis/impala/udf.py
ibis/spark/udf.py
ibis/sql/postgres/udf/api.py
ibis/tests/all/test_vectorized_udf.py
ibis/udf/validate.py
ibis/udf/vectorized.py

The normal syntax for defining an elementwise UDF is passing a single value to `output_type`:
```
@elementwise(input_type=[dt.float64, dt.float64], output_type=dt.float64)
def sum_udf(a, b):
return a + b
```
If the output type is placed into a list (similar to `input_type`) (see below), then executing an expression with the UDF succeeds on Pandas but fails on Spark with `TypeError: 'NoneType' object is not callable`
```
@elementwise(input_type=[dt.float64, dt.float64], output_type=[dt.float64])
def sum_udf(a, b):
return a + b
```
Currently, `output_type=[dt.float64]` is interpreted as the output type being `array<float64>`
This PR unpacks the single value in `output_type` if it's a list and uses that as the output type so that e.g. `output_type=[dt.float64]` is treated as just a `float64` …

FEAT: Validate that the output type of a UDF is a single element

---

Makefile
docs/web/contribute.md

The Makefile target `testspark` broke after #2216. `testspark` tries to use the main requirements file (which no longer has PySpark/Spark dependencies) for building the `ibis` docker image.
**This PR changes `testspark` to use the requirements file for PySpark/Spark.** To keep the Makefile consistent, I also refactored other `test...` targets further.
The diff is confusing, so here's a list of changes:
1. Add `testnoinit` and `testparallelnoinit`. These are the same as `test` and `testparallel`, except that they do not run `init` before running the tests.
2. Change `testmost`, `testfast`, `testpandas`, `testspark` to simply run `make testparallelnoinit` (passing in which requirements file should be used and which pytest markers should be tested) Example:
```
testspark:
$(MAKE) …
```

BUG: Fix Makefile targets for running tests

---

ci/azure/windows.yml
docs/source/release/index.rst
ibis/pandas/api.py
ibis/pandas/dispatch.py
ibis/pandas/dispatcher.py
ibis/pandas/tests/test_core.py
ibis/pandas/tests/test_dispatcher.py
ibis/pandas/trace.py

What is the change
==============
This PR implements a `TwoLevelDispatcher` and replace the `multipledispatch.Dispatcher` with `TwoLevelDispatcher` to define `ibis.pandas.execute_node`
The original dispatcher is found to be slow when
(1) dispatch the first execute_node
(2) dispatch after new signature for execute_node is registered (this happens when user uses UDF)
In this alternative dispatcher, neither of these two issue appears. For details, see docstring of `TwoLevelDispatcher`
How is the change tested
===================
* `ibis/pandas/tests/test_dispatcher.py` is added
* Also replies on existing pandas backend tests.
* Manually tested tracing and verified tracing still works.
Benchmark
========
A benchmark is performed by running all the pandas backend tests and record "time to …

FEAT: Implement two level dispatcher for execute_node

---

docs/source/release/index.rst
ibis/pandas/aggcontext.py
ibis/pandas/execution/tests/test_window.py

What change is proposed?
===================
This PR fixes a bug where `group_by` and `order_by` column cannot be used as window operation input columns. It used to throw an exception.
```
w = ibis.trailing_window(
order_by="time",
group_by="tid",
preceding = 1000,
)
table['time'].count().over(w).execute()
```
Exception:
```
../generic.py:460: in execute_reduction_series_groupby
return aggcontext.agg(data, type(op).__name__.lower())
../../aggcontext.py:489: in agg
indexed_by_ordering = frame[columns].set_index(order_by)
/Users/icexelloss/miniconda3/envs/ibis-dev/lib/python3.7/site-packages/pandas/core/frame.py:4351: in set_index
index = ensure_index_from_sequences(arrays, names)
/Users/icexelloss/miniconda3/envs/ibis-dev/lib/python3.7/site-packages/pandas/core/indexes/base.py:5288: in …
```

BUG: Allow group_by and order_by column as window input in pandas backend

---

docs/source/release/index.rst
ibis/sql/sqlite/compiler.py
ibis/tests/all/test_window.py
ibis/tests/backends.py

This PR adds window operations support to SQLite
Resolve #2231

FEAT: Add window ops support to SQLite

---

ibis/pandas/aggcontext.py
ibis/pandas/tests/test_aggcontext.py

This PR refactors window_agg_udf inside aggcontext.py to take window upper and lower indices instead of window sizes. This allows more flexible way of specifying window indices.
This is tested with existing window tests. Also added a new test file `test_aggcontext.py`

FEAT: Refactor window_agg_udf to take window indices instead of window sizes

---

ibis/omniscidb/tests/conftest.py
ibis/omniscidb/tests/test_client.py

The test_add_columns test currently doesn't work when tests are running in parallel (xdist)

TST: [OmniSciDB] Fix test_add_columns

---

docs/source/release/index.rst
ibis/expr/window.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/execution/window.py

This PR refactors the existing pandas window execution to allow implementing custom window with pandas backend.
The change is tested with a new test `test_custom_window_udf` which implements a dummy custom window and test it with pandas backend.

FEAT: Support custom window in pandas backend

---

docs/web/config.yml
docs/web/contribute.md
docs/web/getting_started.md
docs/web/static/css/codehilite.css
docs/web/static/css/ibis.css

Closes #2219.
Code blocks in the home, getting started, and contributing page, now use syntax highlighting.

DOC: Adding syntax hihlighting to the code in the website

---

ci/requirements-dev-3.6-main.yml
ci/requirements-dev-3.7-main.yml

Closes #2271 
This should speed up conda, from taking more than one hour, to taking 30 minutes. It's still a lot, without pymapd it takes less than 5 minutes. But if this leaves the CI green, probably worth merging while we find a better solution.

CI: Pinning pymapd to 0.23 to speed up conda solver

---

ci/requirements-dev-3.6-main.yml
ci/requirements-dev-3.6-pyspark-spark.yml
ci/requirements-dev-3.7-main.yml
ci/requirements-dev-3.7-pyspark-spark.yml
ci/requirements-dev-3.8-main.yml

This PR is an immediate (and maybe temporary) fix for the failing CI (#2275)
I'll soon add a commit to pin `pytest` to be <=5.4.3, but I'm starting with an empty commit just to confirm that the CI fails in the current state

CI: Pin pytest version to be below 6.0.0rc1 to fix failing CI

---

docs/source/release/index.rst
ibis/pandas/execution/tests/test_operations.py
ibis/pyspark/compiler.py
ibis/pyspark/tests/test_basic.py
ibis/sql/postgres/tests/test_functions.py
ibis/tests/all/test_union.py

Add a compilation function for the `Union` node in the PySpark backend (roughly mirroring [the execution function for `Union` in the Pandas backend](https://github.com/ibis-project/ibis/blob/master/ibis/pandas/execution/generic.py#L762)).
Added a new test in `pyspark/tests/test_basic.py` to test the compilation function (exposed by [`union`](https://github.com/ibis-project/ibis/blob/master/ibis/expr/api.py#L4290) in the table API)

FEAT: Add support for Union in PySpark backend

---

ci/datamgr.py
docs/source/user_guide/extending.rst
ibis/bigquery/tests/test_compiler.py

This allows developers without access to the `ibis-gbq` project to run
the tests if they first set the `GOOGLE_BIGQUERY_PROJECT_ID` environment
variable.
Note: I notice a few errors in local tests: `TypeError: from_arrays() takes at least 2 positional arguments`. I believe this is due to BigQuery requiring a newer version of pyarrow than I currently have installed (0.13.0) in the `pandas-dev` conda environment.

TST: parametrize BigQuery compiler tests by project ID

---

docs/source/release/index.rst
ibis/expr/datatypes.py
ibis/pandas/execution/constants.py
ibis/pandas/execution/tests/test_cast.py

Noticed that you couldn't use cast with the dtype category

ENH: Add category integration for cast to pandas backend

---

ibis/pandas/tests/test_udf.py
ibis/tests/all/test_vectorized_udf.py
ibis/udf/validate.py
ibis/udf/vectorized.py

This PR makes it legal to define a vectorized UDF to take `*args` (previously, a `TypeError` is raised):
```
@elementwise(input_type=[dt.double, dt.double], output_type=dt.double)
def add_cols(*args):
return args[0] + args[1]
```
Before this PR, users _must_ define an explicit positional argument per input defined in `input_type`, like this:
```
@elementwise(input_type=[dt.double, dt.double], output_type=dt.double)
def add_cols(col1, col2):
return col1 + col2
```
Having to explicitly define the positional arguments is a little restrictive. By allowing `*args`, we'll allow users to dynamically generate UDFs even when the number of columns the UDF should accept is not known beforehand.
I'm making it illegal to mix `*args` with explicit positional arguments since the function signatures …

Allow vectorized UDFs to accept *args

---

docs/source/release/index.rst
ibis/bigquery/compiler.py

These two test were failing on master.
https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2744&view=logs&j=1cbd69f0-78ce-5895-4e19-fcb1e813c2be&t=a8633626-0096-538a-5a80-67d017a633d1&l=1248
https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2744&view=logs&j=1cbd69f0-78ce-5895-4e19-fcb1e813c2be&t=a8633626-0096-538a-5a80-67d017a633d1&l=1360
These ops were inherited from Impala but it doesn't look like they are supported by BigQuery

CI: Add some unsupported BigQuery ops inherited from Impala

---

Makefile
ci/Dockerfile.docs
ci/azure/linux.yml

https://ibis-project.org is currently broken. The problem comes from the domain change from docs.ibis-project.org to ibis-project.org. We updated the domain in the github setting of the project, but the setting is overwritten by the `CNAME` file in the repo. This file is coming from the fork https://github.com/cpcloud/docs.ibis-project.org, which is used as a base to build the website/docs. I opened https://github.com/cpcloud/docs.ibis-project.org/pull/1 for an immediate fix, but doesn't look like the fork is being maintained. And I think it's a bad practice and unnecessary to use that fork as a base.
So, in this PR I create the repo that will be pushed to GitHub pages from scratch, instead of cloning the fork. I fix the `CNAME` content, which now is in the Azure setting, and not in the …

DOC: Fix website CNAME and stop using a fork as a base

---

ci/azure/linux.yml

Follow up of #2291. I forgot to update this, from when we were reusing a repo, to now that we create a new one.
Probably not worth waiting for the CI, since this step is not running in the CI of PRs.
CC: @jreback

CI: Fixing typo when pushing the docs

---

docs/source/backends/bigquery.rst
docs/source/backends/clickhouse.rst
docs/source/backends/impala.rst
docs/source/backends/mysql.rst
docs/source/backends/omnisci.rst
docs/source/backends/pandas.rst
docs/source/backends/postgres.rst
docs/source/backends/spark.rst
docs/source/backends/sqlite.rst

The pages of the backends were moved from different places, and now the titles are a mix of things like:
- Using Ibis with BigQuery
- Clickhouse Quickstart
See https://ibis-project.org/docs/backends/index.html. Which doesn't make sense. Leaving just the name of the backend.

DOC: Updating titles of backend pages

---

docs/web/getting_started.md

Got the name of the conda-forge package wrong when I wrote the new installation instructions. Just realized now, fixing it here.

DOC: Fix wrong conda-forge package in setup instructions

---

ibis/expr/tests/test_datatypes.py

We've got a typo in the tests that it's now captured by pandas 1.1, and raising an exception.

TST/CI: Fix test failing in pandas 1.1

---

ci/run_tests.sh

I assume these were created as placeholders for backends that were expected to be added, but they just add confusion to the code base and make it more difficult to find things.

CLN: Remove empty backends

---

ci/deps/bigquery.yml
docs/source/release/index.rst
setup.py

This is needed in order to set the application name in the user agent
header. This feature to be added in:
https://github.com/ibis-project/ibis/pull/2303
Also, removes pin on google-api-core, now that
https://github.com/googleapis/python-api-core/issues/47 is closed.

SUPP: update min google-cloud-bigquery version

---

docs/source/release/index.rst
ibis/bigquery/api.py
ibis/bigquery/client.py
ibis/bigquery/tests/conftest.py
ibis/bigquery/tests/test_client.py

This allows Google API requests by Ibis or tools using Ibis to be
attributed to the project.

ENH: add application name option to BigQuery connect

---

.github/workflows/bigquery.yml

The Bigquery job is still failing. The credentials need to be available before setting up the environment, so the data can be loaded.

CI: Make bigquery credentials available for the loading of the data

---

.github/workflows/bigquery.yml

Closes #2325
Based on [this comment](https://github.com/ibis-project/ibis/issues/2325#issuecomment-674083674) the bigquery key doesn't need to be saved as base64 anymore. So, making things simpler, and saving/loading it directly as json.

CI: Using bigquery key as json, not base64

---

ibis/pandas/aggcontext.py
ibis/pandas/execution/tests/test_window.py
ibis/pandas/tests/test_aggcontext.py

What change is proposed
==================
Currently, `window_agg_udf` assumes that the data series has the same frequency of the window series, i.e., there is one window per data point. However, this function can extended to support the case where there are less windows than data points, e.g., there is 10 data points, and 2 windows, the first window covers data[0: 7] and the second window covers data[5: 10]. 
This PR proposes supporting this use case.
There are no user facing changes, only changes to developer API that makes it easier to extend window operations.
How is this tested
=============
Added test in`test_aggcontext` to cover this case.

FEAT: Allow window_agg_udf to handle the case where window and data has different frequency

---

ibis/pandas/execution/generic.py
ibis/tests/all/test_aggregation.py

This is a really simple change, but a detailed explanation is unfortunately pretty long because of some nuances.
**TL;DR:** The Pandas backend sometimes does an unnecessary `reset_index` when executing the `Aggregation` node. This PR makes it only do `reset_index` when it actually should. This is simply an internal-logic correction that doesn't change any user-facing behavior.
The Pandas backend's execution method for the `Aggregation` node is called `execute_aggregation_dataframe`.
`execute_aggregation_dataframe` does this:
1. [Executes the aggregation metrics requested by the user](https://github.com/ibis-project/ibis/blob/13387c5a0969c99be403af5b3e8aa70bdb671623/ibis/pandas/execution/generic.py#L426)
2. [Concats the metric results (`pd.Series`) into one …

FIX: Avoid creating unnecessary `index` column when executing Aggregation node on Pandas backend

---

docs/source/api.rst
docs/source/release/index.rst
ibis/expr/api.py
ibis/expr/operations.py
ibis/omniscidb/operations.py
ibis/pandas/execution/generic.py
ibis/sql/sqlite/compiler.py
ibis/tests/all/test_column.py

Closes #1462
Supersedes #2251
Implementing `rowid` for backends that support it. Based on the implementation in #2251, but I think this implementation is simpler, and also tried to make the docs more useful for users.

ENH: Implementing rowid

---

docs/source/release/index.rst
ibis/expr/api.py
ibis/expr/operations.py
ibis/expr/tests/test_table.py
ibis/pandas/execution/generic.py
ibis/pandas/execution/tests/test_operations.py
ibis/sql/compiler.py
ibis/sql/tests/test_compiler.py

This pull request adds the SQL 'EXCEPT' functionality, which is the set difference. I followed the same format as intersect so it should be fairly straightforward

Add table except

---

.github/workflows/bigquery.yml

The hdfs tests are currently running in the bigquery build, but failing, see: https://github.com/ibis-project/ibis/runs/1063452941?check_suite_focus=true#step:5:28743
hdfs tests should only run when the impala container is loaded (xref #2341)

CI: Skip hdfs tests for bigquery build

---

ibis/bigquery/tests/test_client.py
ibis/tests/all/test_temporal.py

These failures appear to be less substantial than the others in #2353.
Cleaning those easy ones up first before digging in to the true
failures.

TST: fix failing BigQuery backend tests

---

docs/source/backends/index.rst
docs/source/backends/mysql.rst
docs/source/backends/pandas.rst
docs/source/backends/postgres.rst
docs/source/backends/spark.rst
docs/source/backends/sqlite.rst

Looks like we've got some title sections mixed, and currently the left bar of the navigation in the docs shows the backends mixed with other sections (e.g. `API`): https://ibis-project.org/docs/backends/
This leaves the navigation bar with just the backend names under the `Backend` section.

DOC: Fixing the backends toc tree

---

docs/source/release/index.rst
ibis/pyspark/compiler.py
ibis/tests/all/test_aggregation.py
ibis/tests/all/test_vectorized_udf.py
ibis/tests/all/test_window.py

This is a re-make of #2348.
Add a compilation function for `ReductionVectorizedUDF` for the PySpark backend
- `test_vectorized_udf.py`: New basic test for reduction UDF
- `test_aggregation.py`: New test parameter (that uses reduction UDFs) for `test_aggregate` and `test_aggregate_grouped`
- `test_window.py`: New test for unbounded window, including a test parameter that uses reduction UDFs

 FEAT: Add PySpark support for ReductionVectorizedUDF

---

docs/source/release/index.rst
ibis/bigquery/compiler.py
ibis/bigquery/tests/test_compiler.py

Arguments weren't being translated.
Towards #2353
Closes #2367

BUG: fix the covariance operator in the BigQuery backend.

---

docs/source/release/index.rst
ibis/pandas/execution/window.py
ibis/tests/all/test_vectorized_udf.py
ibis/tests/all/test_window.py

Using analytic ops (like `lead`, `lag`, `first`, `last`, or analytic UDFs) over a window where no `group_by` and no `order_by` are defined produces an incorrect result.
Analytic op `lag` over an ungrouped+unordered window
```
import pandas as pd
import ibis
client = ibis.pandas.connect({'df': pd.DataFrame({'id': [1, 2, 3], 'value_col': [16, 92, 51]})})
table = client.table('df')
window = ibis.window()
expr = table.value_col.lag().over(window)  # lag operation over window
df = expr.execute()
df.to_markdown()
```
The result of the analytic op is a `Series`. That `Series` result is strangely copied `n` times, where `n` is the number of rows of the original column.
|    | 0                               |
|---:|:--------------------------------|
|  0 | 0     NaN                       |
|    | …

BUG: Fix analytic ops over ungrouped and unordered windows on Pandas backend

---

.github/workflows/assign.yml

Now that hacktoberfest is approaching, and I'm also thinking on organizing a sprint to take care of many "good first issue", I think it may be useful to let people assign issues to themselves via a comment. Adding it here.
Will add docs in a follow up, the contributing page needs several updates, and I'll add about assigning issues there.

CI: Adding workflow to self-assign issues

---

.github/workflows/bigquery.yml

Looks like the bigquery build was copied from the pandas one, but the name wasn't changed.

CI: Fix typo in bigquery build name

---

docs/web/contribute.md

Looks like I was a bit sleepy when I changed the contributing guide yesterday, and I forgot to remove the first section (cloning the repo), which was integrated in "setting up a development environment" in #2391.
Fixing it here, and also standardizing the title formatting.

DOC: Remove unused part of the contributing guide

---

docs/source/release/index.rst
ibis/expr/operations.py
ibis/tests/expr/test_literal.py

The Problem
=========
Currently the equality method for Literal is ill defined, e.g.:
```
>>> a = Literal(1, datatypes.int16)
>>> b = Literal(1, datatypes.int32)
>>> a != b
False
>>> a == b
True
>>> hash(a)
1536673607048974696
>>> hash(b)
-4587729510117789678
```
This IMO is bad behavior because it breaks the contract of equal and hashcode (if a == b, then hash(a) must == hash(b)).
What's even worse:
```
>>> a = ibis.interval(hours=1).op()
>>> b = ibis.interval(seconds=1).op()
>>> a == b
True
```
Here a and b are totally different objects.
The Fix
=====
The PR proposes a fix where we also checks the dtype equality in literal equality check.
This fix deals with the two problems above. However, it does change some existing behavior:
Before the PR:
```
a = Literal(1, datatypes.int16) …
```

BUG: Fix equality behavior for Literal ops

---

ibis/__init__.py
ibis/filesystems.py

Moving the function `hdfs_connect` out of `__init__.py, which seems a more natural place.

Moving hdfs_connect to hdfs module

---

docs/source/release/index.rst
ibis/expr/scope.py
ibis/pandas/tests/test_core.py

Overview
------
This PR aims to fix a bug in looking up an `op` in `scope`.  The current implementation is using a list lookup to look up items in `iter(_items)`. This is slower than a hashmap lookup, also it may cause bugs for objects if their equality is ill-defined.
Example
-------
```
a = ibis.interval(days=1).op()
b = ibis.interval(hours=1).op()
>>> a
Literal(1, Interval*value_type=int8, unit='D', nullable=True)
>>> a == b
True
```
In this case, `Literal` is ill-defined for equality. And if we have only `a` in scope`. `b in iter(scope._items)` will be `True` while `b in scope._items` return false. 
Tests
-------
This is tested in `ibis/pandas/tests/tes_core.py` with a new test case `test_scope_look_up`.

BUG: Fix scope get to use hashmap lookup instead of list lookup

---

docs/source/release/index.rst
ibis/pandas/aggcontext.py
ibis/pandas/tests/execution/test_window.py

The Problem
=========
Currently, user defined function doesn't support non numeric inputs for rolling window:
```
win = ibis.trailing_window(preceding=1, group_by=...,order_by=...)
my_udf(t['non_numeric_column']).over(w)
```
will raise exception because we try to compute window bounds by calling `grouped_series.rolling(1).apply(len, raw=True)`, which doesn't work on non numeric columns.
The Fix
=====
I changed the logic to compute window bounds to no longer rely on the input series to the UDF, instead, I created an placeholder column used just for the window bounds computation. The placeholder column is an int column and doesn't have NaNs.
Test
===
Added a new test `test_rolling_window_udf_nan_and_non_numeric` to cover this case as well as the case where input columns contains NaN values.

FEAT: Support rolling window UDF with non numeric inputs

---

README.md
docs/source/backends/omnisci.rst
setup.py

cc @datapythonista in reference to https://github.com/ibis-project/ibis-dask/pull/2#discussion_r493405457. 
There are two references in the `omnisci.rst` docs to http://docs.ibis-project.org/design.html that I couldn't find a replacement for (the existing links currently 404). Please let me know if there's a good replacement or I should leave them as is.

DOC: Update the url to ibis project

---

docs/source/release/index.rst
ibis/pyspark/compiler.py
ibis/pyspark/tests/test_timecontext.py
ibis/pyspark/tests/test_window.py

Overview
=======
Currently, window size defined by `ibis.interval` is broken for pyspark backend.  This PR aims to fix this issue. 
The Problem
=======
In pyspark backend, for a `table` generated by the following df:
```
df_time_indexed = client._session.createDataFrame(
[
[datetime(2017, 1, 2, 5, tzinfo=timezone.utc), 1, 1.0],
[datetime(2017, 1, 2, 6, tzinfo=timezone.utc), 1, 3.0],
],
['time', 'key', 'value'],
)
```
And calculate mean with a `trailing_window`, ordered by time column on this table:
```
window = ibis.trailing_window(
preceding=ibis.interval(hours=2), order_by='time', group_by='key'
)
result = table.mutate(
mean_2h=table['value'].mean().over(window)
).compile()
```
will result in error:
```
-> pyspark_window = pyspark_window.rowsBetween(start, end)  (compile_window_op …
```

FEAT: Support Ibis interval for window in pyspark backend

---

docs/source/release/index.rst
ibis/pyspark/compiler.py
ibis/pyspark/tests/test_window.py

Overview
===============
This PR fixes #2412 where the same window op with different window size on tables will lead to incorrect results for pyspark backend.
A refactor of param `window` in pyspark translation is proposed.
Example
===============
Let's say we create two windows with different sizes to calculate `Mean()` on the same column of a table
```
def test_multiple_windows(client):
table = client.table('time_indexed_table')
window1 = ibis.trailing_window(
preceding=ibis.interval(hours=1), order_by='time', group_by='key'
)
window2 = ibis.trailing_window(
preceding=ibis.interval(hours=2), order_by='time', group_by='key'
)
result = table.mutate(
mean_1h=table['value'].mean().over(window1),
mean_2h=table['value'].mean().over(window2),
).compile()
result_pd = result.toPandas()
df = …
```

BUG: Fix same window op with different window size on table lead to incorrect results for pyspark backend

---

ci/deps/bigquery.yml
setup.py

There are breaking changes in `google-cloud-bigquery` 2.0 that aren't
handled yet. Also, 2.0 seems to require a newer version of the protobuf
library than is available in CI.
Closes #2413

BUG: add upper-bound to BigQuery dependency

---

ibis/tests/all/conftest.py
ibis/tests/backends.py

During https://github.com/ibis-project/ibis/pull/2431#issuecomment-702334682 we found that PySpark CI doesn't fail properly. I think this will fix it.

CI: Remove import skip in tests/all

---

.github/workflows/main.yml
ci/recipe/meta.yaml

Avoid having to update the feedstock repo to get the packaging build passing. It'll be updated on releases only after this change, with the recipe moved here.
See https://github.com/conda-forge/ibis-framework-feedstock/pull/50#issuecomment-702994281

CI: Copying the recipe to this repo, and using it for the packaging build

---

ibis/tests/backends.py

Those imports are giving problems when moving in the backends. Not sure why in master they don't cause them, but I think it's a good thing to not import the backends from the core tests.
Eventually I'd like to move these `Backend` testing classes to the backends, and import them lazily for the backends being tested.

TST: Not importing backends globally in the tests

---

docs/source/release/index.rst
ibis/pandas/aggcontext.py
ibis/pandas/tests/test_aggcontext.py

This PR is to fix a bug with the `Summarize` aggregation context class in the Pandas backend.
Currently, `Summarize.agg` makes pretty straightforward use of `pandas.Series.agg` to produce its result.
However, `pandas.Series.agg` seems to have a quirk where if a single function is passed to `pandas.Series.agg`, it will behave exactly like `pandas.Series.apply` (in fact, it will call `pandas.Series.apply`) and produce a `Series` result, unless an exception is caught while doing this, in which case it will treat the function as an aggregation function (and produce a scalar result).
Because of this quirk, `Summarize.agg` will have unexpected results (i.e., will sometimes produce a `Series` rather than a scalar value) simply depending on whether the function passed to `Summarize.agg` happens …

BUG: Fix Summarize not always producing a scalar value (Pandas backend)

---

.github/workflows/main.yml
ci/datamgr.py
ibis/backends/omniscidb/__init__.py
ibis/backends/omniscidb/client.py
ibis/backends/omniscidb/ddl.py
ibis/backends/omniscidb/operations.py
ibis/compat.py
ibis/config.py
ibis/expr/operations.py
ibis/expr/rules.py
ibis/file/tests/conftest.py
ibis/filesystems.py
ibis/impala/client.py
ibis/impala/tests/test_ddl.py
ibis/impala/tests/test_exprs.py
ibis/impala/tests/test_parquet_ddl.py
ibis/impala/tests/test_partition.py
ibis/impala/tests/test_udf.py
ibis/pyspark/tests/conftest.py
ibis/spark/tests/test_ddl.py
ibis/sql/mysql/client.py
ibis/sql/postgres/client.py
ibis/tests/all/test_column.py
ibis/tests/expr/test_visualize.py
ibis/tests/sql/test_compiler.py
ibis/tests/test_filesystems.py

We're supposed to be using isort, but it wasn't validated in the CI. Several PRs lately had some unrelated imports resorted, if the contributor run isort manually in some files that don't pass isort.
Running isort in all files, and enabling it in the CI, so we stop having those unrelated changes in PRs.

CI: Enable isort in the CI and fix pending imports

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/clickhouse/operations.py

We merge #2450 and #2437 together, and we've got the isort validation, but some incorrectly sorted imports in clickhouse (CI is red). Fixing it here.
Sorry for the mess with the isort PR, really bad timing for it.

CI: Fix isort after clickhouse refactoring

---

ibis/expr/types.py

- [`ibis.expr.types`](https://github.com/ibis-project/ibis/blob/master/ibis/expr/types.py#L12) imports `ibis.expr.format`, then
- [`ibis.expr.format`](https://github.com/ibis-project/ibis/blob/master/ibis/expr/format.py#L4) imports `ibis.expr.types` and `ibis.expr.operations` (this forms two circular imports, see diagram below)
In the context of Ibis these circular imports are not a problem (works fine and causes no issues/bugs/errors). I'll explain more below.
```
+--------------------+
+---->----------->|ibis.expr.operations|
|                 +---------+----------+
|                           |
|                           |
/|\                         \|/
|                 +--------------------+
|                 |ibis.expr.datatypes |
|                 +---------+----------+
| …
```

ENH: Avoid top-level circular imports in ibis/expr/types.py

---

docs/source/backends/clickhouse.rst

As discussed with @datapythonista in https://github.com/ibis-project/ibis/pull/2437#issuecomment-702856451, I am adding in the docs the autosummary for the ClickHouse API that was missing.
I have tried to keep it consistent with the rest of the backends, and I have added for now only the client methods with docstrings. Should I add others?
Unfortunately I was not able to generate the docs locally to check if it looks ok visually, which command should I use to build the documentation?
Please let me know if there is anything else I should improve, thank you very much!

DOC: Added autosummary of ClickHouse API

---

ibis/compat.py
ibis/expr/api.py
ibis/pandas/client.py
ibis/pandas/execution/generic.py
ibis/pandas/tests/test_datatypes.py

closes #2454
I have removed the pandas imports from `compat.py` and made explicit imports from pandas in the scripts that were using compat.
The only variable that remains in compat is `PY38`, probably it should be moved somewhere else. What do you think?
Please let me know if I can improve this.
Thanks

DEPS: Remove old pandas compatibility functionality

---

.pre-commit-config.yaml

As stated in https://github.com/asottile-archive/seed-isort-config
```
DEPRECATED
this is no longer needed as of isort>=5
```
Therefore, removing this and upgrade to isort >= 5

Remove seed-isort-config and upgrade isort

---

ci/run_tests.sh

We do not have backends in `ibis/sql` anymore, so looking for tests there is not needed.

CLN: Removing unused test directory in call

---

ci/deps/omniscidb.yml
docs/source/release/index.rst
ibis/backends/omniscidb/client.py
ibis/backends/omniscidb/tests/test_client.py
setup.py

FEAT: [OmniSciDB] Add method parameter to load_data

---

ibis/backends/pandas/aggcontext.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/selection.py
ibis/backends/pandas/execution/util.py
ibis/backends/pandas/execution/window.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/backends/pandas/udf.py
ibis/backends/pyspark/compiler.py
ibis/expr/api.py
ibis/expr/operations.py
ibis/expr/types.py
ibis/tests/all/test_vectorized_udf.py
ibis/tests/backends.py
ibis/udf/vectorized.py
ibis/util.py

What is this change
===============
This PR is a follow up of #2473. In this PR, I added the support for `destructure` for analytics and reduction UDFs:
- Support for groupby aggregation UDF
- Support for window analytic UDF (unbounded window)
- Support for window aggregation UDF (moving window)
Example:
- groupby aggregation UDF
```
Define and use an UDF with multiple return columns:                                                                                                                                                     
>>> @reduction(                                                                                                                                                                                         
...     input_type=[dt.double], …
```

FEAT: Add destructure support for analtyic and reduction UDF

---

ci/azure/linux.yml
environment.yml

The static site generator we use for the website seems stable enough, so I released it to pypi. Using that version instead the github path.

CI: Installing web generator pysuerga from pipy and not github

---

.github/workflows/main.yml
ci/setup_env.sh

closes #2389
I have changed `setup_env.sh` to set the CONDA_PATH based on which OS is running the script.
At the moment, I am passing the OS name using the value in `runner.os` as an argument as seen [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#runner-context), but as suggested by @datapythonista I will try something else like `uname`.
I am still working on it , but please let me know if you have any suggestions.

CI: Make GitHub Actions builds compatible with Windows

---

ibis/backends/base_sql/__init__.py
ibis/backends/base_sql/compiler.py
ibis/backends/bigquery/compiler.py
ibis/backends/spark/compiler.py
ibis/impala/compiler.py
ibis/impala/tests/mocks.py
ibis/impala/tests/test_sql.py
ibis/tests/expr/mocks.py
ibis/tests/sql/test_compiler.py

Closes #2501
@datapythonista from starting on this it looks like even `base_sql` relies on the `base_sqlalchemy` compiler - so that definitely emphasizes your point on eventually having just one base sql backend.  i def still have ways to go but my approach was as follows:
1. Move impala compiler classes and functions to new `base_sql.compiler.py` file (and update names from `Impala` to `Base`
2. Update `impala.compiler.py` to subclass from these new `base_sql` classes
3. Update other backends that use impalas compiler to use the new `base_sql` one instead
By doing this i thought i would be able to leave the rest of the impala code untouched and have it still pull from impala compiler while the impala compiler is based on base_sql.
I def still have ways to go but can you let me know if …

Move impala compiler to base_sql

---

docs/source/release/index.rst
ibis/backends/pandas/execution/util.py
ibis/backends/pandas/tests/test_udf.py
ibis/tests/all/test_aggregation.py
ibis/tests/all/test_vectorized_udf.py
ibis/util.py

What is the change
==============
Follow up of #2487 
Added support for aggregation without groupby with destruct.
This change itself is straight forward. The main change is in `coerce_to_output` where I added support for coercing a tuple of scalar, e.g., (1.0, 2.0) to a single row DataFrame, which is what we used for other destruct columns.
How is this tested
=============
Added `test_reduction_udf_no_groupby`

FEAT: Add support for destruct for aggregation with no groupby

---

docs/source/release/index.rst
ibis/expr/datatypes.py
ibis/tests/expr/test_datatypes.py

This should be self explanatory.

FEAT: Add Struct.from_dict

---

docs/web/contribute.md
environment.yml

Close #2524 
Moving the instructions in the [wiki](https://github.com/ibis-project/ibis/wiki/Releasing-Ibis) to the `Contribute` page in the docs. And updating the outdated things. I will delete the wiki page and disable the GitHub wiki once this is merged (we don't have anything else in the wiki).

Moving release instructions to the contributing guide

---

docs/web/contribute.md
docs/web/static/css/ibis.css

Headers of level 4 (i.e. markdown `#### Header`) don't look so much as headers. Making them more visible.
Also fixing a typo in the markdown here.

DOC: Fixing style of level 4 headers

---

ci/run_tests.sh
ibis/backends/omniscidb/tests/test_client.py
ibis/backends/omniscidb/tests/test_operations.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/postgres/tests/test_udf.py
ibis/backends/pyspark/tests/test_timecontext.py
ibis/backends/spark/tests/test_ddl_compilation.py
ibis/backends/sqlite/tests/conftest.py

`run_tests.sh` was still expecting the old directory structure and thus not running tests specific to each backend. 
For example compare test dirs/number of tests in https://github.com/ibis-project/ibis/pull/2536/checks?check_run_id=1433682341#step:4:6 vs https://github.com/ibis-project/ibis/runs/1433974150?check_suite_focus=true#step:4:10
This PR also fixes various other test failures uncovered now that backend tests are running again.

TST/BUG: Fix run_tests.sh for new backend directory structure

---

ibis/tests/test_version.py

Closes #2520
After moving tests to actions, the time test that was was supposed to be skipped in the CI started running again, and failing quite often. Skipping it here.

CI: Skipping time test in CI

---

ci/impalamgr.py
docs/source/release/index.rst
ibis/__init__.py

Closes #2505 
Removing `ibis.hdfs_connect`... previously deprecated in favor of `ibis.impala.hdfs_connect`...

Remove previously deprecated hdfs function from top level module

---

docs/source/backends/impala.rst
docs/source/tutorial/04-More-Value-Expressions.ipynb
docs/source/tutorial/05-IO-Create-Insert-External-Data.ipynb
docs/source/tutorial/06-Advanced-Topics-TopK-SelfJoins.ipynb
docs/source/tutorial/07-Advanced-Topics-ComplexFiltering.ipynb
docs/source/tutorial/08-More-Analytics-Helpers.ipynb
docs/source/user_guide/configuration.rst
ibis/backends/impala/__init__.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_hdfs.py
ibis/tests/backends.py

Closes #2555 
Not sure why the CI didn't fail for #2545, but looks like there were some missing calls to `ibis.hdfs_connect` that weren't updated to be `ibis.impala..hdfs_connected` and this is making the docs build fail.

DOC: Update hdfs_connect calls in docs

---

ci/Dockerfile.dev

Docs are built on azure via `BuildDocs` in ci/azure/linux.yml. 
This then builds `ibis-docs` (via make) in using `ci/docker-compose.yml`. 
This builds `Docker.docs` which depends on `Docker.dev`, which conda installs files from `ci/deps/. 
cc @jreback

BLD: Speed up azure builds 

---

ibis/tests/test_version.py

In #2548 we skipped the time test in GitHub Actions, but removing the skip in Azure, which was a mistake. Skipping it in both here.

CI: Skipping time test in Azure

---

ci/setup_env.sh
environment.yml
ibis/__init__.py

In #2582, these tests are failing:
```
FAILED ibis/tests/expr/test_interactive.py::TestInteractiveUse::test_repr_png_is_not_none_in_not_interactive
FAILED ibis/tests/expr/test_visualize.py::test_optional_graphviz_repr - Asser...
FAILED ibis/tests/expr/test_visualize.py::test_html_escape - assert None is n...
= 3 failed, 4357 passed, 452 skipped, 229 xfailed, 1 xpassed, 116 warnings in 252.71s (0:04:12)
```
in these CI jobs:
* Tests pandas / files (windows-latest, 3.7)
* Tests pandas / files (windows-latest, 3.8)
* Tests dask (windows-latest, 3.7)
* Tests dask (windows-latest, 3.8)
In this PR, starting off with no changes to confirm that the tests still fail on a clean slate

CI: Fix failing tests related to graphviz

---

ibis/expr/rules.py

There is a small typo in ibis/expr/rules.py.
Should read `validators` rather than `valudators`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

DOC: fix simple typo, valudators -> validators

---

environment.yml

Closes #2580 
[Sphinx 3.4.1 was released](https://github.com/sphinx-doc/sphinx/milestone/95?closed=1), which includes the fix to the issue that the Ibis docs CI was having

CI: Unpin sphinx version

---

ibis/backends/base/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/csv/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/hdf5/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/parquet/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/spark/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_api.py

At the moment, the API between Ibis and a backend is defined by whatever it's defined in `ibis/backends/<backend>/__init__.py`. Here, I start to change that to use a subclass of a base backend class. The main advantages are:
- The API now it's not explicit, since the abstract base class forces which methods must be implemented (for example, currently some backends have a `verify` method, and some others don't, and there is no consistency, and it's not clear what's the expected API and what's not)
- A lot of repetitive code among backends can be moved to the base class
A first draft of how things can look like has been built in #2550. That PR looks a great potential for simplifying things, besides the standardization, it deletes 500 lines of repetitive code, and the PR is not yet finished. …

Adding skeleton for new backends API (Backend class)

---

ibis/backends/dask/execution/arrays.py
ibis/backends/dask/execution/generic.py
ibis/backends/dask/execution/numeric.py
ibis/backends/dask/execution/reductions.py
ibis/backends/dask/execution/strings.py
ibis/backends/dask/execution/structs.py
ibis/backends/dask/execution/temporal.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/dask/tests/execution/test_strings.py
ibis/backends/dask/tests/execution/test_structs.py
ibis/backends/tests/test_temporal.py

This PR adds more complicated grouping operations to the dask backend. Previously simple operations worked, but more complicated operations failed. See changes in `test_operations` for examples. 
I'm a bit concerned about potential performance issues in `_make_selection_obj` but I figure those can be fixed separately from the base functionality working. 
Aggregation/aggcontext is fairly intertwined with grouping. I _think_ it makes sense to do that as a separate PR, but I'm going to tackle that next anyway, so happy to do it as part of this one. 
TODOs

ENH: Grouping operations in the dask backend

---

docs/source/release/index.rst
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/tests/test_compiler.py

Fixes #2354
Added a unit test for verifying that the expected generated SQL string is generated.

Adds proper binary column translation for BigQuery compiler

---

docs/source/backends/impala.rst

In order to not require an Impala instance to build the docs, and move the build to GitHub actions (see #2590), I'm making the Impala examples in the backend doc not run with the ipython Sphinx directory, but be regular code blocks instead.

DOC: Making Impala doc not require an Impala server

---

ibis/backends/dask/core.py
ibis/backends/dask/execution/aggregations.py
ibis/backends/dask/execution/generic.py
ibis/backends/dask/execution/numeric.py
ibis/backends/dask/execution/reductions.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/tests/conftest.py
ibis/backends/dask/tests/execution/conftest.py
ibis/backends/dask/tests/execution/test_join.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/dask/tests/execution/test_structs.py
ibis/backends/dask/tests/test_client.py
ibis/backends/dask/tests/test_schema.py
ibis/backends/tests/conftest.py
ibis/backends/tests/test_aggregation.py

This PR does a few things:
1. Enables aggregations in the backend and adds missing test coverage for grouped/masked reductions
2. Changes dask `conftest.py`  objects to return `DataFrame` objects with `npartitions=2` to make sure we are exercising multi partition behavior. 
3. Fixes bugs uncovered by the change in `(2)`. 
4. Refactors backend testing fixtures so we don't need `if backend.name() == "dask"` calls in `ibis/backends/tests/test_aggregation.py`.

[ENH] Dask backend aggregations

---

ibis/backends/tests/conftest.py

We have a custom pytest marker `skip_missing_feature`, for example used like this:
https://github.com/ibis-project/ibis/blob/019ccd5122befd3b843b32abf8b59991244596c9/ibis/backends/tests/test_array.py#L20-L26
However it is not skipping tests. This PR fixes this by changing the implementation of `skip_missing_feature` to call `pytest.skip` instead of `pytest.mark.skip` (similar to the implementation of [`skip_backends`](https://github.com/timothydijamco/ibis/blob/019ccd5122befd3b843b32abf8b59991244596c9/ibis/backends/tests/conftest.py#L85))

TST: Fix custom pytest marker skip_missing_feature

---

docs/source/release/index.rst
ibis/backends/mysql/tests/conftest.py
ibis/backends/postgres/compiler.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_array.py

This PR allows `np.array` literals in the PySpark backend. This was already supported on the Pandas backend.
```
import numpy as np
from ibis import backends
from ibis.expr.types import literal
spark = ...
ibis_pyspark = backends.pyspark.connect(spark)
ibis_pyspark.execute(literal(np.array([1, 2])))
```
Before:
```
AttributeError: 'numpy.int64' object has no attribute '_get_object_id'
```
After:
```
array([1, 2], dtype=int32)
```

ENH: Add support for np.array literals

---

ibis/backends/dask/core.py
ibis/backends/dask/dispatch.py
ibis/backends/dask/execution/aggregations.py
ibis/backends/dask/execution/arrays.py
ibis/backends/dask/execution/decimal.py
ibis/backends/dask/execution/generic.py
ibis/backends/dask/execution/indexing.py
ibis/backends/dask/execution/join.py
ibis/backends/dask/execution/maps.py
ibis/backends/dask/execution/numeric.py
ibis/backends/dask/execution/reductions.py
ibis/backends/dask/execution/selection.py
ibis/backends/dask/execution/strings.py
ibis/backends/dask/execution/structs.py
ibis/backends/dask/execution/temporal.py
ibis/backends/dask/tests/test_core.py

Closes #2601
Here, we create new dispatchers specifically for the dask backend (instead of just adding onto the ones in the pandas backend). We copy over the existing python functions and then switch other files to use the dask specific dispatchers.

ENH: Adding separate dispatchers for dask backend

---

docs/source/backends/impala.rst
docs/source/tutorial/05-IO-Create-Insert-External-Data.ipynb

Moving the Impala specific examples to the Impala backend doc, and using the standard examples for the rest of the tutorial 5.

DOC: Make tutorial 5 not require Impala

---

docs/source/release/index.rst
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py

FEAT: Implement Not operation in PySpark backend

---

docs/source/release/index.rst
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_string.py

What's the change
==============
* Added support for case/when clause in PySpark backend
* Fixed a NPE issue with substr in PySpark backend
* Switch the implementation of substr in PySpark backend from UDF to built-in function and raise errors for unsupported case (when start and length is not static) 
How is this tested
=============
Add test under test_string.py for `substr`
Add test under test_generic.py for `case/when`

FEAT: Add support for case/when in PySpark backend

---

ibis/backends/tests/test_generic.py

Looks like it was accidentally dropped in https://github.com/ibis-project/ibis/pull/2610/

TST: Add back assert in test_filter

---

docs/source/release/index.rst
ibis/backends/dask/execution/arrays.py
ibis/backends/pandas/execution/arrays.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_array.py
ibis/expr/api.py
ibis/expr/operations.py
ibis/expr/types.py
ibis/tests/test_api.py

This PR adds a new operation called `ArrayColumn`.
**Input:** list of _n_ `ColumnExprs` (of the same datatype)
**Output:** single `ArrayColumn`, where each element is an array of length _n_. Each array is populated from the values in the input columns for that row.
(See *New API* section below for an example)
This operation is similar to PySpark's `array(*cols)` ([link](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.functions.array)) and Postgres's `array[...]` ([link](https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS)).
I have implemented the operation on the following backends so far:
* PySpark
* Pandas
* Dask
The operation is exposed through a new top-level function: `ibis.array_column(*cols)` (other examples of a …

FEAT: API for creating array column from other columns

---

ibis/backends/dask/execution/selection.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/tests/conftest.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/backends/tests/test_union.py

This PR adds limited sorting support for the dask backend. These limitations stem form `dask` having no existing way to do sorting, see discussion below. 
Limitations:
- Sorts must be on a single column (or expression resulting in a single column)
- Only ascending sort is supported. 
To accomplish sorting in the dask backend, we cheat a bit and `assign` a temporary column, `set_index` it, then `reset_index(drop=True)`. 
Having dug around a bit, I think it is definitely possible to use the machinery of `set_index` to create a more general sorting method here, though arguably that should live in upstream dask, not an ibis util function. I'm not yet sure how we would support multi column sorts without making that too complicated (should be doable if we can partition the frame correctly and …

ENH: Partial sorting support in dask backend

---

ibis/backends/dask/execution/util.py

Maybe these should be `_` prefixed as they're really not meant to be user facing, but right now this follows the pandas backend naming.

DOC: Update docstring for compute_sort_key in dask backend

---

ibis/backends/dask/client.py
ibis/backends/dask/core.py
ibis/backends/dask/tests/conftest.py
ibis/backends/dask/tests/execution/test_arrays.py
ibis/backends/dask/tests/execution/test_cast.py
ibis/backends/dask/tests/execution/test_functions.py
ibis/backends/dask/tests/execution/test_join.py
ibis/backends/dask/tests/execution/test_maps.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/dask/tests/execution/test_strings.py
ibis/backends/dask/tests/execution/test_structs.py
ibis/backends/dask/tests/execution/test_temporal.py
ibis/backends/dask/tests/execution/test_timecontext.py
ibis/backends/dask/tests/test_client.py
ibis/backends/dask/tests/test_core.py
ibis/backends/pandas/tests/execution/test_functions.py
ibis/backends/tests/conftest.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_temporal.py

Closes https://github.com/ibis-project/ibis/issues/2604. 
Changes:
- `.compile()` now returns an object that you can run `.compute()` on 
- `.execute()` calls `.compute()` on the object returned by `.compile()`
Most of the diff is updating all the tests in the dask backend for this new behavior and removing some shims we had in the generic ibis backend tests. Also un-xfails some `TODO - pandas` tests that now no longer fail. 
<hr />

ENH: Change dask backend to return computed objects  with .execute()

---

environment.yml

Closes #2629
New version of Graphviz was released 3 hours ago, so I guess it's the problem. Pinning for now.

CI: Pinning graphviz

---

docs/source/user_guide/extending/extending_elementwise_expr.ipynb

Towards #2590. Using SQLite in one more page, so no backend docker images are required to build the docs.

DOC: Use SQLite instead of PostgreSQL in elementwise extending

---

docs/source/release/index.rst
ibis/backends/tests/test_generic.py
ibis/expr/analysis.py
ibis/tests/expr/test_analysis.py

What change is proposed
===================
Example code
```
t = ibis.table(ibis.schema([('col', 'float32')]), 't')
t = t[['col']]
t = t[~t['col'].isnan()]
t = t.mutate(col=t['col'].cast('int32'))
```
Before:
```
ref_0
UnboundTable[table]
name: t
schema:
col : float32
Selection[table]
table:
Table: ref_0
selections:
col = Cast[int32*]
col = Column[float32*] 'col' from table
ref_0
to:
int32
predicates:
Not[boolean*]
IsNan[boolean*]
col = Column[float32*] 'col' from table
ref_0
```
After:
```
ref_0
UnboundTable[table]
name: t
schema:
col : float32
ref_1
Selection[table]
table:
Table: ref_0
selections:
col = Column[float32*] 'col' from table
ref_0
predicates:
Not[boolean*]
IsNan[boolean*]
col = Column[float32*] 'col' from table
ref_0
Selection[table]
table:
Table: ref_1
selections:
col = …
```

BUG: Fix fusion optimization bug that incorrectly changes operation order

---

.github/workflows/main.yml

Follow up of #2590. Pushes the docs to github pages, as it was done before from azure.
**Note** it requires #2637 for this to work.

Pushing the docs to GitHub pages from the CI

---

.github/workflows/main.yml

Pushing of the docs to GitHub pages in #2638 worked well (investigating a problem with the static files, but they are pushed).
I forgot the custom domain configuration is not kept if we don't create the `CNAME` file manually. Adding it here.

DOC: Set up custom domain when pushing the docs

---

.github/workflows/main.yml

Fixes the pushing of the docs (I didn't realize the old repo was docs.ibis-project.org and not the current domain ibis-project.org).
Merging before the CI finishes, so we restore the website asap (the changes here don't execute for PRs anyway).

DOC: Fixing website repo url

---

.github/workflows/main.yml

This was missing for static files to be served by the GitHub pages server. Not sure how it was added before, I haven't seen this code in azure.

DOC: Adding nojekyll file so static files are served by GitHub pages

---

docs/source/release/index.rst
ibis/backends/tests/test_vectorized_udf.py
ibis/expr/api.py

Currently ibis does some checking inside the mutate API method to determine whether any assigned columns are overwriting an existing column in the table. It then uses this logic to correctly select the column expr from the assignment expr that does the overwriting. This also ensures that there are no duplicate columns detected in schema computation.
However, this logic does not properly account for an overwrite that may occur within a DestructColumn, which are used to specify output of multi-column UDFs. Since DestructColumns by design cannot be named (since they can represent many columns internally), the current logic does not detect if a column inside a DestructColumn is overwriting an existing column. The result is an error at expression creation time as duplicate columns are detected …

BUG: Fix overwrite logic to account for DestructColumn inside mutate API

---

docs/source/api.rst
docs/source/release/index.rst
ibis/backends/bigquery/compiler.py
ibis/backends/bigquery/tests/test_compiler.py
ibis/backends/mysql/compiler.py
ibis/expr/api.py
ibis/expr/operations.py

FEAT: add `bit_xor` aggregate to BigQuery and MySQL backends

---

ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/parquet/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/spark/__init__.py
ibis/backends/sqlite/__init__.py

Specifying the builder and the dialect of each backend. This is still unused, but will be used soon when we move from using the `compile` function in each backend module, to using the generic one in the base backend class.

Adding builder and dialect to Backend classes

---

conftest.py

Not failing silently if test data directory is not found. We may end up not running the tests without realizing (hopefully it's not the case already).

TST: Not skipping tests if data directory not found

---

setup.cfg

I don't think the current list of ignored files is useful, removing everything that doesn't contain Python files or that is passing.

Remove uneeded excluded files from linting

---

docs/source/release/index.rst
ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/test_connect.py

Towards #2179 
In order to verify the application, I need to submit a video demonstrating the need for the requested scopes. I realized that we don't make it easy to query data in Google Drive, so this PR remedies that.

FEAT: Add auth_local_webserver, auth_external_data, and auth_cache to BigQuery connect

---

ibis/backends/tests/test_join.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_temporal.py
ibis/backends/tests/test_union.py

After merging https://github.com/ibis-project/ibis/pull/2623 it seems I didn't unskip/unxfail certain dask tests. 
I've gone through and either removed the dask restriction or reclassified it (in the code and on the tracker https://github.com/ibis-project/ibis/issues/2553).

TST: unskip or recategorize dask pandas skipped tests

---

ci/deps/clickhouse.yml
ci/deps/dask-min.yml
ci/deps/dask.yml
ci/deps/hdf5.yml
ci/deps/impala.yml
ci/deps/mysql.yml
ci/deps/parquet.yml
ci/deps/postgres.yml
ci/deps/pyspark.yml
ci/deps/spark.yml
ci/setup_env.sh
environment.yml
ibis/backends/base_file/tests/test_schema.py

Closes #2670
Trying to speed up CI builds by speeding up conda solver.
Unpining most dependencies in the base file, and moving few dependencies from the base file to the backend dependencies.
The base file resolves in a bit more than a minute locally.

CI: Simplifying dependencies to speed up conda resolve

---

docs/source/release/index.rst
ibis/__init__.py
ibis/backends/pandas/aggcontext.py
ibis/backends/pandas/execution/window.py
ibis/backends/pandas/tests/execution/test_timecontext.py
ibis/backends/pandas/tests/execution/test_window.py
ibis/backends/pandas/tests/test_udf.py
ibis/backends/tests/test_timecontext.py
ibis/expr/timecontext.py

Overview
=======
As a follow-up of #2646, add namespace `timecontext` for the ibis config `time_col`.
Also, fix a type check in `trim_with_time_context` for pandas window execution. The type check to check a DataFrame has a `time_col` column and its type is a Datetime type, will not hit by any user level APIs, removing it.
For the result series of a Groupby Transform. The result series is still using the name of the input series. We should unset it to avoid confusion. e.g. If the input series is 'time' and the result series is float but still named 'time' Then in trimming with context the series will be identified as a time column and result in an error.
Tests
=======
Still using the tests implemented in `ibis/backends/tests/test_timecontext.py`, and …

ENH: Namespace time_col config, fix type check for trim_with_timecontext for pandas window execution.

---

.github/workflows/main.yml

Looks like in #2590 I forgot to build the website, and we are only publishing the docs in https://ibis-project.org/. Just realized now. Fixing it here.

DOC: Restoring website

---

.github/workflows/main.yml

Follow up of #2685, the temporary path is different in the website and the docs, and the website is not being uploaded. Fixing here.

DOC: Fixing docs path, so website and docs are uploaded together

---

environment.yml

Closes #2631 
Looks like the latest graphviz doesn't cause problems anymore. Checked the test logs, and `test_interactive.py` is not being skipped, so the broken test in #2629 works with the latest version.

CI: Making Ibis compatible with latest graphviz

---

docs/source/release/index.rst
ibis/backends/pyspark/client.py
ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/pyspark/timecontext.py
ibis/backends/tests/test_timecontext.py
ibis/expr/timecontext.py

Mixture of a few minor issues with context adjustment for pyspark:
Main change:
- Fix Selection node that is filter only so that we pass the original timecontext correctly.
Minor changes:
- Localize tz-naive time context with spark.sql.session.localTimezone. This is consistent with how does Spark treats timestamps in the DataFrame.
- Only trim if the context and adjusted_context are different
- (Minor) Clean up test_timecontext.py
- (Minor) Fix error in backends/pyspark/testconf.py (verified manually)
Tests
====
Add new test in test_timecontext.py

BUG: Fix issues with context adjustment for filter with PySpark backend

---

docs/source/release/index.rst
ibis/backends/pandas/execution/util.py
ibis/backends/tests/test_aggregation.py

On the Pandas backend, when `.aggregate()` is passed an aggregation/reduction that results in a list/ndarray, `aggregate` will automatically explode that list/ndarray into **many rows** (one row per element in the array). This is not the desired behavior. A list/ndarray coming from a Reduction op should actually be treated as a scalar (i.e., **should result in a single row, not many rows**).
```
df = pd.DataFrame({
'key': pd.Series([1, 1, 2]),
'foo': pd.Series([100, 200, 300]),
})
ibis_pandas = ibis.pandas.connect({'test': df})
t = ibis_pandas.table('test')
@udf.reduction(input_type=[dt.int32], output_type=dt.Array(dt.int32))
def to_list_udf(v):
return list(v)
@udf.reduction(input_type=[dt.int32], output_type=dt.Array(dt.int32))
def to_np_array_udf(v):
return np.array(v) …
```

BUG: Fix `aggregate` exploding the output of Reduction ops that return a list/ndarray

---

ibis/backends/dask/tests/execution/test_timecontext.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/selection.py
ibis/backends/pandas/execution/window.py
ibis/backends/pandas/tests/execution/test_timecontext.py
ibis/backends/tests/test_timecontext.py
ibis/expr/timecontext.py

Overview
=======
When time context is adjusted, the result of 'window after filer' is wrong for pandas backend. This PR fixes the bug.
Example:
```
window = ibis.trailing_window(ibis.interval(days=3), order_by='time')
expr = exp[expr['bool_col']]
expr = expr.mutate(v1=expr['value'].count().over(window))
result = expr.execute(timecontext=context)
```
The result looks like:
```
index  Unnamed: 0    id bool_col  tinyint_col  smallint_col  ...  date_string_col  string_col           timestamp_col    year month    v1
0   3938.0      3938.0  40.0     True          0.0           0.0  ...         01/05/09           0 2009-01-05 00:40:01.800  2009.0   1.0  11.0
1      NaN         NaN   NaN      NaN          NaN           NaN  ...              NaN         NaN                     NaT     NaN   NaN …
```

BUG: Fix wrong row indexing in the result for 'window after filter' for timecontext adjustment

---

docs/source/release/index.rst
ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/tests/test_basic.py
ibis/backends/tests/test_generic.py

Currently, if you write an expression that does a filter on a window operation and execute this in the pyspark backend, we get a failure from upstream Spark. For example:
`table.filter(lambda t: t['id'].mean().over(window) > 3)`
would raise `pyspark.sql.utils.AnalysisException: It is not allowed to use window functions inside WHERE clause;`. There is an upstream Spark issue about this: https://issues.apache.org/jira/browse/SPARK-33057.
A simple workaround can be implemented to avoid passing a window operation directly to filter in the pyspark backend. We can achieve the same filter by first assigning the filter predicate to a temporary, internal column, performing the filter using that column, and then dropping the column.
Added a test in test_basic.py that does a window operation in a …

FEAT: Support Spark filter with window operation

---

ibis/backends/dask/__init__.py
ibis/backends/dask/execution/aggregations.py
ibis/backends/dask/execution/selection.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/tests/execution/test_arrays.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/dask/tests/execution/test_util.py
ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py
ibis/backends/pandas/execution/util.py
ibis/backends/tests/test_vectorized_udf.py
ibis/util.py

This PR adds support for udf operations to the dask backend. It unskips all non-window tests in
- `ibis/backends/tests/test_vectorized_udf.py`
- `ibis/backends/dask/tests/test_udf.py` (which were ported from the pandas backend. I've purposely left in xfail window tests so I can add to the tracker. )
In addition, I've built out the dask backend clones of `coerce_to_output` and `coerce_to_dataframe` which get used in udf/section operations. 
Post Merge:

ENH: UDF operations for dask backend

---

ibis/backends/bigquery/compiler.py

This PR fixes #2717 
The code change is just reversing the diff in the lines that are selected here: [Diff of ibis/backends/bigquery/compiler.py from #2661](https://github.com/ibis-project/ibis/pull/2661/files#diff-d7c2d45959c2baa00df6631a8818c081adecd87626c52ab82b7560933609e91cL79-L81)
I was able to confirm locally that `.compile()` using the BigQuery backend works with this PR. In the BigQuery CI, this should make `test_large_compile` in `ibis/backends/bigquery/tests/test_compiler.py` start succeeding again (note: BigQuery CI runs after PRs are merged).

Restore build_ast in BigQuery backend

---

ibis/backends/sqlite/tests/conftest.py

Removing some dangerous skips that will make tests fail silently if there is a problem in SQLite test db.

CI: Do not skip sqlite tests if database is not found

---

ci/deps/impala-min.yml
ci/deps/impala.yml

CI is broken, seems like the latest `bitarray` version is not installed in the Python 3.7 build.
Apparently bitarray is in its 2.0, but released a security version of 1.9, which is the one installed in Python 3.7, and it is failing our CI (`impyla` uses a private attribute, so it's not exactly a breaking change). So far testing if we can fix the CI by pinning versions, not sure what would be the best approach here.

CI: Testing with older impyla and bitarray versions

---

ibis/backends/clickhouse/compiler.py

xref #2715
All other backends have their classes inheriting from `Base*` but Clickhouse. I don't think there is a reason for this, replacing to see if this fails.
If this works, we should be able to easily merge the two sets of base classes for the backends (e.g. `SelectBuilder` / `BaseSelectBuilder`...)

Make Clickhouse compiler inherit from the right classes

---

ibis/backends/dask/execution/selection.py

This silences the warnings in the dask backend from standard selection. Maybe revert once we have a fast path for the standard: https://github.com/ibis-project/ibis/issues/2742. This is deep in the implementation so shouldn't be user facing.

ENH: Silence warnings from selection in dask backend

---

ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py

If we don't pass a `multiindex` here correctly, the `reset_index`  call in the `op.by` operation (https://github.com/ibis-project/ibis/blob/master/ibis/backends/dask/execution/aggregations.py#L90) will cause a bad value for `result.columns` at https://github.com/ibis-project/ibis/blob/master/ibis/backends/dask/execution/aggregations.py#L92, which will break computation downstream.

BUG: Fix dask udaf_node_groupby for multiple key grouping

---

ibis/backends/base/sql/ddl.py
ibis/backends/impala/client.py
ibis/backends/impala/ddl.py
ibis/backends/impala/kudu_support.py
ibis/backends/impala/tests/test_ddl_compilation.py
ibis/backends/spark/client.py
ibis/backends/spark/ddl.py
ibis/backends/spark/tests/test_ddl_compilation.py

Just moving the `ddl.py` from `base_sqlalchemy` (which is removed) to `base/sql`.
Also making private few functions, and adding an `__all__`.

Move ddl to base/sql and define its API

---

ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/translator.py
ibis/backends/base_sql/compiler.py

Removing some of the functionality of `base_sql` in favor of the base compiler.
Going step by step with this, since the whole refactoring has been breaking mysteriously.

Remove functionality from base_sql

---

ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py

Currently you can't pass in a `pd.DatetimeTZDtype`  to meta. I have a PR up for this in https://github.com/dask/dask/pull/7627, but we can patch this here until that goes through and we update min dependencies for the dask backend. 
This is the only place we're using the output meta in this way to create a scalar (it works fine in other contexts).

BUG: Patch meta for DatetimeTZDtype

---

ibis/backends/base/sql/compiler/query_builder.py

After adressing #2761 the base compiler can now import the base registry without loops.

Restore import from registry after fixing circular problem

---

docs/source/release/index.rst
ibis/backends/dask/tests/test_udf.py
ibis/backends/pandas/aggcontext.py
ibis/backends/pandas/tests/test_udf.py

BUG: Reduction UDF returning `np.array` hits error when used in grouped aggregation

---

ci/deps/impala.yml

Issue to investigate failures: https://github.com/ibis-project/ibis/issues/2780
Noticed a maybe related PR here: https://github.com/ibis-project/ibis/pull/2737

Pin bitarray version to 2.0.1 to fix CI

---

ibis/backends/dask/execution/util.py
ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py

This fixes a few more UDFs areas affected by https://github.com/dask/dask/pull/7627. I created a `safe_scalar_type` util function to handle this conversion and expanded the udf test coverage to test in all these cases.

BUG: Fix a few more places dask could recieve tz meta

---

ibis/backends/dask/execution/selection.py

Instead of constructing a `pd.Series` in memory and forcing computation to get the length of the dask index, we assign the scalar into the dataframe directly and pull out just the series. This also ensures that the `dd.Series` we get back from `compute_projection_scalar_expr` will match the rest of the selections in `compute_projections` (in terms of `n_partitions`, `known_divisions`, etc

ENH: Let dask handle scalar projection

---

docs/source/release/index.rst
ibis/backends/dask/tests/execution/test_functions.py
ibis/backends/pandas/tests/execution/test_functions.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_numeric.py

Implement support to be able to execute `clip` in the Pyspark backend. For example:
```
t.col.clip(lower=0, upper=10).execute()
```
Moved existing pandas and dask clip tests into test_numeric.py to call on pyspark as well.

Implement Clip in the Pyspark backend

---

docs/source/release/index.rst
ibis/backends/dask/tests/test_udf.py
ibis/backends/pandas/execution/util.py
ibis/backends/pandas/udf.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_timecontext.py
ibis/backends/tests/test_vectorized_udf.py
ibis/expr/schema.py
ibis/udf/vectorized.py
ibis/util.py

This PR adds support for more flexible return types of single- and multi-column UDFs.
Before this PR:
Supported return types for single column UDF: pd.Series
Supported return types for multi column UDF: Tuple[pd.Series]
Supported return types for multi column aggregation UDF: tuple of scalar
After this PR:
Supported return types for single column UDF: pd.Series, list, np.ndarray
Supported return types for multi column UDF: Tuple[pd.Series], List[pd.Series], Tuple[np.ndarray], List[np.ndarray]
Supported return types for multi column aggregation UDF: tuple of scalar, list of scalar, np.ndarray of scalar
The proposed return types make the UDF API a bit more flexible for the user, and are also non-ambiguous when the return type of the UDF is not an Array type.
Added tests in …

ENH: Allow more flexible return type for UDFs

---

ibis/expr/schema.py

This logic was mistakenly not removed after a refactor in a commit in this PR: https://github.com/ibis-project/ibis/pull/2776/

Remove unneeded check about arrays in coerce_to_dataframe

---

docs/source/release/index.rst
ibis/backends/dask/udf.py
ibis/backends/tests/test_vectorized_udf.py

This was temporarily removed in https://github.com/ibis-project/ibis/pull/2776 and tracked in https://github.com/ibis-project/ibis/issues/2553#issuecomment-843528132. 
This adds back support.

ENH: Add dt.Struct support back to elementwise udfs

---

ci/deps/dask-min.yml
ci/deps/dask.yml
setup.py

xref https://github.com/ibis-project/ibis/issues/2800. 
Looks like `2021.5.1` had some issue with meta:
- https://github.com/dask/dask/issues/7731
- https://github.com/dask/dask/pull/7503
For now, let's set a cap on the max dask version and wait for a fix in dask to happen.

ENH: More tightly bound dask versions

---

docs/source/release/index.rst
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/base/sql/registry/string.py
ibis/backends/pandas/execution/strings.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_string.py
ibis/expr/api.py
ibis/expr/operations.py
ibis/expr/schema.py
ibis/tests/expr/test_operations.py
ibis/tests/expr/test_string.py
ibis/tests/sql/test_compiler.py

Closes #2790 .
Adds `StartsWith` and `EndsWith` operations and adds compilers to base SQL and SQLAlchemy.
I haven't written any tests yet. 
I assume I should add the operations to `test_ops_smoke` in *expr/test_operations.py* and test them in _sql/test_compiler.py_ and _sql/test_sqlalchemy.py_ ?
Anything else I am missing?

FEAT: Add startswith and endswith

---

docs/source/release/index.rst
ibis/backends/pandas/client.py
ibis/backends/pandas/tests/test_datatypes.py

#2753 made some changes to type inference in the Pandas backend (i.e. the way that we infer column types in input data that is in the form of Pandas DataFrames). These changes made use of `dt.binary` as a general fallback type.
Specifically, the final type inference approach that we attempt is to call `pd.api.types.infer_dtype` on the Series, then match the result of that function to some Ibis dtype ([ibis/backends/pandas/client.py#L159](https://github.com/ibis-project/ibis/blob/fd62fe52f9f59a4c5964b30b2f061c354b736249/ibis/backends/pandas/client.py#L159)). For non-obvious mappings, we use `dt.binary`  ([ibis/backends/pandas/client.py#L82-L103](https://github.com/ibis-project/ibis/blob/fd62fe52f9f59a4c5964b30b2f061c354b736249/ibis/backends/pandas/client.py#L82-L103)).
This PR changes some …

ENH: Use more useful fallback types for 'categorical' and 'decimal' Series'

---

docs/source/release/index.rst
ibis/backends/base/sql/alchemy/client.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/client.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/impala/tests/test_patched.py
ibis/backends/pyspark/__init__.py
ibis/backends/spark/__init__.py
ibis/backends/spark/client.py
ibis/backends/spark/tests/test_ddl.py
ibis/backends/tests/test_client.py
ibis/client.py
ibis/tests/expr/mocks.py

The `Query` class and subclasses have a tricky implementation, and are causing problems in #2777.
The class `SQLClient` instantiates the `Query` class, passing itself as a parameter, and then calls it's `execute` method, which will call the client `_execute` method. This seems nonsense, and just implementing the functionality of `Query` (which is quite simple) in `SQLClient` seems to be much more reasonable.

CLN: Removing Query class

---

ci/setup_env.sh
environment.yml

Closes #2801
In theory we are already using conda-forge, since it's the only channel in `environment.yml`, but that doesn't seem to be enough in practice.

CI: Force mamba to use conda-forge

---

docs/source/release/index.rst
ibis/backends/dask/execution/generic.py
ibis/backends/pandas/execution/generic.py
ibis/backends/tests/test_temporal.py

This PR adds support to execute the following types of expressions that compare a ColumnExpr to a timestamp literal, which was previously missing functionality in the Pandas and Dask backends:
```
expr.filter(expr['timestamp_col'] > pd.Timestamp('20100301'))
```
Added tests for all comparison operations in test_temporal.py.

Support comparison of ColumnExpr to timestamp literal

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/base_sql/compiler.py
ibis/backends/clickhouse/compiler.py
ibis/backends/impala/compiler.py
ibis/backends/spark/compiler.py

Another step on cleaning the compiler code. Main work here:
- `SelectBuilder` moved to it's own file (it's huge)
- `SelectBuilder` received the `Select` class it needs as a parameter, instead of having to subclass in every backend
- `QueryBuilder` does not need to be instantiated, and `get_result()` renamed to `to_ast`. So instead of `QueryBuilder(expr, context).get_result()` we use `QueryBuilder.to_ast(expr, context)`.
- The previous point has the advantage that `build_ast` are just aliases of the new `to_ast` (I'll delete the aliases later anyway)
- Added `to_sql` method to `QueryBuilder`, and started using in few places where the same code was being repeated

CLN: Improve QueryBuilder and SelectBuilder API

---

docs/source/release/index.rst
ibis/backends/dask/execution/util.py
ibis/backends/tests/test_aggregation.py

Using `.aggregate()` with a reduction that outputs an array + a reduction that outputs a scalar fails on the Dask backend.
```
@udf.reduction(
input_type=[dt.int64],
output_type=dt.int64,
)
def sum_udf(v):
return np.sum(v)
@udf.reduction(
input_type=[dt.int64],
output_type=dt.Array(dt.int64),
)
def collect_udf(v):
return np.array(v)
t = t.aggregate(
sum_col=sum_udf(t['int_col']),
arr_col=collect_udf(t['int_col'])
)
t.execute()
```
```
~/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/dask/dataframe/multi.py in concat(dfs, axis, join, interleave_partitions, ignore_unknown_divisions, **kwargs)
1138             return concat_unindexed_dataframes(dfs, **kwargs)
1139         else:
-> 1140             raise ValueError(
1141                 "Unable to concatenate DataFrame with unknown " …
```

BUG: Aggregation with mixed reduction datatypes (array, scalar, etc) fails on Dask backend

---

docs/source/release/index.rst
ibis/backends/dask/tests/execution/test_arrays.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/execution/test_cast.py

In the Pandas backend, when casting a column to an array type, a `list` is created as the output instead of a `np.array` (which is the new standard in the Pandas backend).
```
>>> series = t['arr_col'].execute()
>>> type(series[0])
numpy.ndarray
>>> series = t['arr_col'].cast('array<float64>').execute()
>>> type(series[0])
list
```
Change the Pandas backend implementation of the cast operation to produce a `np.array`.

BUG: `.cast()` to array outputs list instead of np.array in Pandas backend

---

docs/source/release/index.rst
ibis/expr/operations.py

Currently, on instantiation of the ``Aggregation`` node, ibis calls into [this expr optimization logic](https://github.com/ibis-project/ibis/blob/master/ibis/expr/analysis.py#L266), where this line will attempt to simplify a projection by lifting the root. This optimization method is O(n) as it iterates over all the root.selections ([here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/analysis.py#L353) and [here](https://github.com/ibis-project/ibis/blob/master/ibis/expr/analysis.py#L367)), and in practice when called inside the ``Aggregation`` constructor, the outcome is O(n^2) as this logic runs for each table column - the result can be very slow expression creation on wide tables when there is a Selection followed by an aggregation.
```
N = 3000
df = pd.DataFrame({'a': [1, …
```

Disable aggregation expr optimization due to N squared performance

---

ci/deps/dask.yml
setup.py

Status: Breaking because of https://github.com/ibis-project/ibis/issues/2815, specifically here https://github.com/ibis-project/ibis/blob/master/ibis/backends/dask/udf.py#L133. We shouldn't have been doing this anyway, will fix this code.

DEP: Uncap dask dependency

---

environment.yml
ibis/backends/tests/conftest.py
requirements.txt

The backend tests currently run for all backends in `ibis/backends/`. With this PR it will run with backends defined as entrypoints. So, besides the core backends i nthat directory, tests can be run from third-party backends.

TST: Run tests for backends defined as entrypoints

---

ibis/backends/tests/conftest.py
ibis/tests/test_api.py

Follow up of #2836
I didn't realise that the `TestConf` class was being loaded from the path in the Ibis repo. So that part had to be changed to load relative to the module in #2836. Changing it here, so Ibis backend tests can run in third-party backends.

Loading TestConf correctly for third-party backends

---

ci/deps/pyspark-min.yml
ci/deps/spark-min.yml

Last successful CI run: https://github.com/ibis-project/ibis/runs/2967145346?check_suite_focus=true
First Broken CI run: https://github.com/ibis-project/ibis/runs/2975032046?check_suite_focus=true
Errors look like:
```
==================================== ERRORS ====================================
____________ ERROR collecting ibis/backends/spark/tests/test_udf.py ____________
ibis/backends/spark/tests/test_udf.py:98: in <module>
@udf.elementwise.pandas([dt.double], dt.double)
ibis/backends/spark/udf.py:93: in __call__
udf_func = self.pyspark_udf(func)
ibis/backends/spark/udf.py:125: in pyspark_udf
return f.pandas_udf(func, self.spark_output_type, self.pandas_udf_type)
/usr/share/miniconda/lib/python3.7/site-packages/pyspark/sql/functions.py:2922: in pandas_udf
return _create_udf(f=f, …
```

CI: Pin pyspark pandas dep for pyarrow issues

---

setup.cfg

xref #2823
We currently ignore mypy errors in the CI, since lots of things are broken. In preparation to fix the actual errors, this PR fixes the main issues, so the CI (or running mypy locally) reports the actual errors.
I'm thinking on organizing a sprint to get help fixing all errors. I will be creating subissues of #2823 with fixes to specific modules, so problems in an issue can be addressed by a single contributor in a reasonable time.

CI: Fixing most obvious mypy errors, and adding mypy settings

---

ibis/backends/dask/__init__.py
ibis/backends/dask/execution/__init__.py
ibis/backends/dask/execution/generic.py
ibis/backends/dask/execution/selection.py
ibis/backends/dask/execution/util.py
ibis/backends/dask/execution/window.py
ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py
ibis/backends/tests/test_vectorized_udf.py

Previously (in https://github.com/ibis-project/ibis/pull/2786) I tried to handle windowing + grouping/ordering in the same PR  and it got very messy. This is a simpler PR that "unwraps" a windowing operation and executes the logic inside. Only supports "no-op" windows (those with no lead/lag/group by/order by parameters).  But this can occur in situations like `test_analytic_udf_mutate`. The `add_partitioned_sorted_column` will be used in follow up PRs to support grouping and ordering windows (and I can probably get rid of all usages of `utils.safe_concat` now).
This code also fixes https://github.com/ibis-project/ibis/issues/2711 by using `da.select`. This was only introduced in dask 2021.6.1, so I've ported the code into a shim. https://github.com/ibis-project/ibis/issues/2847 is a …

ENH: Support no-op windows in the dask backend

---

ibis/backends/tests/base.py

`TestConf.api` is assuming all backends can be accessed via `ibis.backends.<backend-name>.Backend()`, which is not true for third-party backends.

Make TestConf.api work for third-party backends

---

docs/source/release/index.rst
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_temporal.py

This PR adds support in the Pyspark backend for doing binary operations (e.g. add/subtract) on timestamp columns using Pandas Timedeltas, for example:
```
dt['timestamp_col'] + pd.Timedelta(days=5)
```

Support binary operation with Timedelta in Pyspark backend

---

environment.yml

Closes #2783
I didn't really make any changes.
The latest version of Sphinx running correctly.

CI/DOC: Make docs work with the latest Sphinx

---

ibis/backends/clickhouse/tests/test_aggregations.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_string.py

The warnings list if quite long, and makes it quite time consuming to find test failures (and the github CI log is quite slow to load). Besides many of them are future warnings that will eventually make Ibis or the tests fail. Fixing several here.

Fixing several warnings

---

ibis/backends/pandas/execution/temporal.py
ibis/backends/tests/test_temporal.py

pandas deprecated `Series.dt.weekyear`. Updating to the new syntax, to avoid warnings for users, in the tests, and to not have this breaking in future pandas updates.

Updating pandas Series.dt.weekofyear to avoid warnings

---

ibis/backends/dask/execution/window.py
ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py
ibis/backends/tests/test_vectorized_udf.py

Part two of windows in the dask backend, built on top op noop windows in https://github.com/ibis-project/ibis/pull/2843. 
- `execute_grouped_window_op` directly follows the pandas logic in https://github.com/ibis-project/ibis/blob/master/ibis/backends/pandas/execution/window.py#L239. It felt better to section off all the grouping specific logic while windows are only partially supported by the dask backend, though we can refactor this later. 
- I've split up the handlers for grouped analytic and grouped reduction function application, the logic was getting a bit messy to put into one function like pandas does. 
- Using the udf directly, as in https://github.com/ibis-project/ibis/blob/master/ibis/backends/dask/tests/test_udf.py#L253 meant I needed to handle some of the "cleanup" actions …

ENH: Grouped unbounded windows in the dask backend 

---

.github/workflows/main.yml
ci/pytest_errors.sh
ci/run_tests.sh
ibis/tests/test_api.py

It takes a lot of scrolling to find the traceback of tests errors. This adds a new step in GitHub actions with only the useful information, so it's immediate to find.

Add GitHub Actions step with only pytest errors

---

docs/source/release/index.rst
ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_functions.py

Added `group_concat` operation to Clickhouse.

clickhouse: support `group_concat` operation

---

ibis/backends/base/__init__.py
ibis/backends/base/client.py
ibis/backends/base/sql/alchemy/client.py
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/client.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/translator.py
ibis/backends/base/sql/registry/window.py

Fix mypy errors in backends/base

---

ci/deps/clickhouse.yml
ci/recipe/meta.yaml
environment.yml

We're getting this error in the CI:
```
pkg_resources.ContextualVersionConflict: (tzlocal 3.0 (/usr/share/miniconda/lib/python3.8/site-packages), Requirement.parse('tzlocal<3.0'), {'clickhouse-driver'})
```
Not sure what's the problem, but looks like tzlocal has just been released, so I guess it's a compatibility problem with the new version. Pinning for now.
I see that there is a tzlocal 4.0 alpha after the yesterday's 3.0, so I guess it may be a known problem about to be fixed.

CI: Pin tzlocal version

---

docs/source/release/index.rst
ibis/backends/pandas/aggcontext.py
ibis/backends/tests/test_vectorized_udf.py
ibis/expr/schema.py

Handle empty input data in summarization.
Currently, when a summarization gets passed empty data in the Pandas backend, we error out with a confusing 
```
UnboundLocalError: local variable 'grouped_col_name' referenced before assignment
```
This PR adds checks in a couple of places for empty data, such that we gracefully return an empty DataFrame instead.
Added a new test for this in test_vectorized_udf.py.

Support summarization of empty data in Pandas backend

---

ibis/expr/operations.py

`resolve_name` is a method defined on Ops, and is used to get the name of a given Expr (e.g. `get_name` on an Expr calls into its Op's `resolve_name` method). Currently, the `resolve_name` implementation of `ValueOp` raises an error that calls `repr(self)` to print out the entire expression tree. This O(N) error message is problematic especially for large trees, resulting in very slow performance just to raise an error message.
This change will print `type(self)` instead.

Do not print full tree repr in resolve_name error message

---

docs/source/release/index.rst
ibis/backends/clickhouse/compiler.py
ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_select.py

It seems that for some historical reasons ClickHouse backend banned joining on different columns, and that has been supported by ClickHouse now. So i removed the vailidation and added some codes for that (refer to ibis SQL backend).

FEAT: ClickHouse: support joining on different columns.

---

ibis/backends/tests/test_client.py

These changes fix a race condition when running tests in parallel. Without this
multiple clients try to remove `temp_to_table`/`temp_from_table` independently
and collide with each other.

BUG: Fix race condition in temporary table deletion

---

ibis/backends/tests/conftest.py

Prior to this patch the backends all show up as `TestConf1`, `TestConf2`, etc.

TST: show the name of the backend when running tests

---

ibis/backends/pyspark/tests/conftest.py

Tests were being run without data for the backend, causing them to fail

BUG: Fix pyspark client that was being used to test without data

---

ibis/backends/tests/conftest.py

This PR adds a `backend` marker for backend tests which makes it easier to run non-backend and backend tests in the same pytest session.

TST: Add backend marker

---

ibis/tests/test_version.py

This test has low utility, as it cannot be validated in CI.

TST: Remove low-utility test

---

.github/workflows/main.yml
ci/run_tests.sh
environment.yml
ibis/backends/dask/trace.py
ibis/backends/pandas/tests/test_client.py
ibis/backends/pandas/trace.py

Fix bug in pandas and dask backends, where options can not be initialized, if tests are run in an arbitrary order.
- ci: run tests across multiple processes
- fix: ensure that the pandas test client registers options
- fix: ensure that dask trace option is initialized
- fix: ensure that pandas trace option is initialized

fix: fix a few broken assumptions in the dask and pandas backends

---

pyproject.toml
setup.cfg

This PR moves some of the existing configuration in `setup.cfg` (`isort`,
`pydocstyle`, and `pytest`) to `pyproject.toml`. `mypy` just released a version
with `pyproject.toml` support so it's a bit early to move IMO.

refactor: move some config to pyproject.toml

---

pyproject.toml

This PR removes omniscidb from the pydocstyle configuration

style: remove omniscidb from pydocstyle config

---

ibis/backends/tests/conftest.py

This PR slighty changes the meaning of PYTEST_BACKENDS.
It's a really terrible developer experience to suddenly be
testing all backends because of an **undefined** environment variable.
The new behavior is:
- If the variable is undefined or empty, return an empty list, so no backends are tested
- If the variable is defined, existing behavior is retained

fix: allow an undefined PYTEST_BACKENDS variable to indicate no backends should be tested

---

setup.py

This fixes a bug that isn't caught in the current CI where the spark entrypoint
points to a non-existent `spark` attribute.

fix: forward the spark entry point to pyspark

---

docs/source/release/index.rst
ibis/backends/clickhouse/client.py
ibis/backends/impala/client.py
ibis/backends/impala/hdfs.py
ibis/backends/pyspark/client.py

Some backends implement `Client.log`, which doesn't seem useful at all. I guess the original reason was to be able to overwrite the method, so the logging could be replaced. I don't think `Client` is subclassed for any of the backends that provide the `log` method. And also, the provided implementation of the logging uses `options.verbose_log`, which can be set to change the logging in an easier way than overwritting the method.
Removing those `log` methods here, which are inconsistent among backends, don't provided any feature, and polute the public `Client` API.

CLN: Remove overcomplicatted logging

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/expr/analysis.py
ibis/expr/operations.py
ibis/expr/types.py
ibis/tests/expr/test_table.py

Root tables are operation specific, so call it explicitly rather than hiding it behind a proxy method.

ENH: Remove Expr._root_tables()

---

docs/source/release/index.rst
ibis/expr/operations.py
ibis/tests/expr/test_case.py
ibis/tests/expr/test_literal.py
ibis/tests/expr/test_struct.py
ibis/tests/expr/test_table.py
ibis/tests/util.py

From icexelloss:
We are trying to build "consistent hash" for ibis Expression (hash that doesn't change cross Python interpreter restart for ibis Expression) and the current implementation depends on first pickling the ibis Expression then use something like hashlib.sha256() to compute the hash from the pickled bytes.
During this, we found that because ibis Node class that "_cached_expr" and "_hash" attributes, the pickled bytes can be different for the same table depending on whether those two fields are created, which is not a very desirable behavior. This PR aims to fix the serialization/deserialization method so that they produce consistent results for the equivalent Node object.

ENH: Add __getstate__ and __setstate__ for Nodes

---

.github/workflows/main.yml

This PR is a follow up to #2957 to handle the test output from every job in the build matrix

ci: handle matrix for test output

---

docs/source/api.rst
docs/source/backends/clickhouse.rst
docs/source/release/index.rst
ibis/backends/base/__init__.py
ibis/backends/base/client.py
ibis/backends/base/sql/alchemy/client.py
ibis/backends/impala/__init__.py
ibis/backends/impala/client.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/client.py
ibis/backends/tests/test_api.py

Closes #2913
Only Impala and pyspark support `set_database`. It doesn't add much value, since a new client can be created for the different database. But it adds extra complexity, having to handle the not implement errors, and managing a state for the two backends implemented. Also, it creates wrong expectations in the users, since it's in the documentation, but almost no backend supports it.
CC: @cpcloud @jreback

DEPR: Deprecate set_database

---

.github/workflows/main.yml
.github/workflows/test-report.yml
ibis/tests/test_api.py

The current CI test reporter doesn't allow publishing test failures on runs from forks.
This PR attempts to address that.

ci: make the test reporter fork friendly

---

.github/workflows/test-report.yml

This PR ensures the test report is only produced when a workflow suceeded or failed, and not for example in the case where the workflow was cancelled.

ci: only produce a test report if the workflow succeeded or failed

---

.github/workflows/main.yml

Dask tests seem unable to be run in parallel.
This disables parallel in the simpler backend testing until it can be reproduced and fixed.
I do think it's a bug that we can't execute tests in parallel without failure
but I don't think this should hold up the release.

chore: disable dask parallel testing

---

.github/workflows/main.yml
ci/run_tests.sh

This PR ensures that the tests in `ibis/tests` aren't run in every single job.

ci: only run ibis/tests in one job

---

.github/workflows/main.yml
.github/workflows/test-report.yml

This is a small PR to rename the main CI workflow to `CI` instead of the much longer `Continuous Integration`
that tends to push useful information about various checks in PRs to the right and obscure it.

ci: rename workflow

---

.github/workflows/main.yml
environment.yml
ibis/backends/dask/tests/test_dispatcher.py
ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_client.py
ibis/backends/impala/tests/test_udf.py
ibis/backends/pandas/tests/test_dispatcher.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/sqlite/tests/conftest.py

This should help us be robust to any test-run ordering dependencies

test: run tests in a random order

---

ci/deps/impala.yml
ci/merge_and_update_env.sh
ibis/backends/impala/tests/test_client.py

This PR adds `pure-sasl` to the impala backend dependencies due to `impyla`
not declaring a hard dependency on `pure-sasl` (https://github.com/cloudera/impyla/issues/471).

ci: temporarily add pure-sasl to impala conda dependencies

---

ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/clickhouse/tests/test_select.py

Split from https://github.com/ibis-project/ibis/pull/2983
---
When literal `None` to some Nullable column's type will raise error.
``` python
expr = table.mutate(ibis.literal(None, table['nullable_string_column'].type()).name('new_column'))
expr.compile()
```

fix: fix literal of Nullable in Clickhouse

---

ci/run_tests.sh

Now that we are using `pytest-randomly`, we should remove use of the `-q` option
so that if we need to reproduce a particular test run ordering we can see the
`--randomly-seed` value shown on test startup.

test: don't suppress test start info

---

ibis/backends/clickhouse/compiler.py
ibis/backends/clickhouse/tests/test_select.py

Split from https://github.com/ibis-project/ibis/pull/2983
---
The order of limit and offset in compiled SQL is reversed 🤣.
https://clickhouse.tech/docs/en/sql-reference/statements/select/limit/#limit-clause

fix: fix order of limit and offset param in Clickhouse.

---

ibis/backends/impala/tests/test_connection_pool.py

This PRs fixes an incorrect assumption in a test, that the cursor in the impala
client connection pool is never GCd, seen failing [here](https://github.com/ibis-project/ibis/runs/3652404022).
Under certain test run orderings, the cursor *is* GCd, and therefore never gets put into the connection pool.

test: fix incorrect connection pool test

---

docs/source/release/index.rst
ibis/backends/impala/client.py

This PR fixes some possible race conditions in cursor management in the Impala backend

fix: fix cursor accounting races

---

ibis/backends/impala/tests/test_client.py

This PR fixes another test that was assuming `__del__` was invoked at a
particular time.

test: fix incorrect assumption about GC in impala test

---

ibis/backends/pandas/aggcontext.py
ibis/backends/pandas/udf.py

In the Pandas backend Summarize agg function, since we are already looping through the grouped data, we can simply get the aggregation results by calling the function directly rather than calling Pandas `agg`, which should save us some overhead.
This is an internal refactor, all existing tests should pass.

Call aggregation function directly for pandas Summarize

---

ci/deps/impala.yml

This removes the `pure-sasl` dependency now that the upstream PR has landed.

ci: remove pure-sasl dependency

---

ibis/backends/impala/client.py
ibis/backends/impala/tests/test_parquet_ddl.py

This PR removes `ImpalaTemporaryTable` in favor of a weakref
finalizer that has stronger guarantees on when it will be called.

refactor: remove ImpalaTemporaryTable

---

ibis/backends/impala/client.py
ibis/backends/impala/kudu_support.py
ibis/backends/impala/pandas_interop.py
ibis/backends/impala/tests/test_pandas_interop.py

This PR removes the `__del__` method from `DataFrameWriter` in favor of a context manager.

refactor: remove __del__ from pandas_interop

---

ibis/expr/api.py
ibis/expr/types.py

Looks like a more suitable place.
Probably we can move other factory functions too: `ibis.null|literal|sequence|array()`,

refactor(ir): Move ibis.param() to api.py

---

ibis/expr/api.py

At least I think it serves no purpose, I think it's a debugging leftover.

fix(ir): remove accidental print statement

---

ibis/expr/operations.py

Changing the rule validators for `left` and `right` from `rlz.noop` to the more precise `ir.TableExpr` in `Join` node.

Use TableExpr validator in Join node

---

ibis/backends/tests/test_geospatial.py

Looks like in #2902 I made some PostGIS specific tests run in all backends, see [here](https://github.com/ibis-project/ibis/pull/2902/files#diff-3aa1fee3c73ec6755835d6873ca3727c0dda2a72ff779a55b7f38be5320e557bL17)
This is breaking the CI in the Ibis-OmniSci repo
@jreback we should merge this before the release

Avoid running PostGIS specific backends in all backends

---

ibis/backends/dask/core.py
ibis/backends/pandas/core.py
ibis/backends/pandas/execution/timecontext.py
ibis/backends/pandas/tests/execution/test_timecontext.py
ibis/expr/timecontext.py

This PR passes `scope` to the functions that compute context adjustment: `compute_context_adjustment` and `adjust_context`.
The existing `compute_context_adjustment` and `adjust_context` functions don't make any use of `scope`. This change is useful for making context adjustment more extensible downstream of Ibis.
The `scope` variable is mainly used to cache ops that have already been calculated, but since it can store anything, it's also useful for storing general information that is accessible/updatable during the execution process. Before this PR, `adjust_context` has a limited view—the only information it has access to is the op-in-question and the current timecontext. Giving context adjustment functions access to `scope` makes them more extensible/flexible (e.g. to implement …

ENH: Pass scope to context-adjustment functions

---

.github/workflows/main.yml

This fixes pushing docs to `ibis-project/ibis-project.org`, and prevents
future breakage by tracking a released version instead of `main` of the action.

ci: fix docs push

---

.github/workflows/main.yml

Minor PR to squash a warning when pushing docs.

ci: remove unused field when pushing docs

---

ibis/backends/dask/core.py
ibis/backends/dask/tests/execution/test_timecontext.py
ibis/backends/pandas/core.py
ibis/backends/pandas/tests/execution/test_timecontext.py

Before this PR, any `adjust_context` function (i.e., a function that defines logic for adjusting the timecontext for a particular Node) that results in **an adjusted context is not a superset of the original context** would cause an error in the Pandas and Dask backends.
--
Example:
- Begin adjusted from `2020-02-01` to `2020-01-29`
- End adjusted from `2020-02-07` to `2020-02-03`
The adjusted context is _not_ a superset of the original context.
--
This is not causing any user-facing issues currently, because all of our existing `adjust_context` functions produce an adjusted timecontext that is a superset of the original timecontext, which doesn't trigger this error. However, this bug is not ideal because context adjustment functions should not be restricted to only being able to _expand_ …

FIX: Pandas and Dask backends fail when adjusted context is not a superset of original context

---

docs/source/release/index.rst
ibis/backends/dask/execution/generic.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/expr/api.py
ibis/expr/operations/relations.py
ibis/util.py

```
TableExpr.dropna(subset=None, how='any')
"""Drop  rows with null values from the table"""
subset: Optional list of column names to consider
how: {'any', 'all'} - whether to drop rows if any or all values are null
TableExpr.fillna(replacements)
"""Fill null values in the table"""
replacements: scalar value (to fill all columns) or mapping of column names to replacement value
```
This PR adds support for the Pandas, Dask, and Pyspark backends only.
There is a follow-up issue to add support for SQL backends: #3110.
Added new tests for both methods in test_generic.py

Support fillna and dropna on TableExpr

---

ibis/backends/dask/tests/test_udf.py
ibis/backends/dask/udf.py
ibis/backends/pandas/tests/execution/test_functions.py
ibis/backends/pandas/tests/test_udf.py
ibis/backends/pyspark/compiler.py
ibis/expr/operations/core.py
ibis/expr/operations/vectorized.py
ibis/expr/signature.py
ibis/tests/expr/test_signature.py
ibis/tests/expr/test_udf.py
ibis/udf/vectorized.py

While adding UDF support for datafusion backend I recognized some issues with the UDF operations.

refactor(ir): Don't bypass argument coercion and validation for user defined functions

---

ibis/backends/dask/execution/selection.py

Calling `len` here forces dask to materialize all the predicates, just to check the assertion. This was transplanted from the pandas code.

PREF: Do not materialize predicates on selection

---

ibis/expr/datatypes.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_value_exprs.py

fix(datatypes): infer bytes literal as binary #2915

---

ibis/expr/operations/generic.py
ibis/tests/expr/test_value_exprs.py

```
import ibis
import uuid
value = uuid.uuid4()
x = ibis.literal(value, type="uuid")
```
This was raising 
```
IbisTypeError: argument passes none of the following rules: instance_of((<class 'shapely.geometry.base.BaseGeometry'>, <class 'bytes'>, <class 'datetime.date'>, <class 'datetime.datetime'>, <class 'datetime.time'>, <class 'datetime.timedelta'>, <class 'dict'>, <enum 'Enum'>, <class 'float'>, <class 'frozenset'>, <class 'int'>, <class 'list'>, <class 'numpy.generic'>, <class 'numpy.ndarray'>, <class 'pandas._libs.tslibs.timedeltas.Timedelta'>, <class 'pandas._libs.tslibs.timestamps.Timestamp'>, <class 'set'>, <class 'str'>, <class 'tuple'>, <class 'NoneType'>),), is_computable_input()
```
but `ibis.literal(str(value), type="uuid")` wasn't.  Adding in `uuid.UUID` as a valid …

fix(literal): allow creating ibis literal with uuid

---

.github/workflows/check-setup-py.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-main.yml
.github/workflows/update-setup-py.yml

This PR uses the installed python version for cache hits to avoid breakage
when setup-python starts installing a new patch release of Python.
This failure can be seen here: https://github.com/ibis-project/ibis/runs/4355031281?check_suite_focus=true
cc @gforsyth

ci: use the precise python version installed for cache lookups

---

ibis/expr/analysis.py

The source of my confusion was that the final line of the repr(Expr) for sort_by is the "reverse" boolean, so the final line of the error output was:
```
False does not fully originate from dependencies of the table expression.
```
This adds quotes around the Expr for this error message, which would have provided a clue that the `False` is part of a larger multi-line expression.  Alternatively/additionally the Expr repr could have some some outer brackets or braces to indicate the bounds of the Expr.

chore(expr): add quotes around expr in validator error

---

ibis/config.py
ibis/tests/test_api.py

Closes https://github.com/ibis-project/ibis/issues/3145
Adds a basic test of reading/writing options.

fix: restore the ability to have more than two option levels

---

ibis/backends/base/__init__.py
ibis/backends/base/file/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/database.py
ibis/backends/clickhouse/__init__.py
ibis/backends/dask/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/tests/test_client.py
ibis/expr/types.py
ibis/tests/expr/mocks.py
ibis/tests/expr/test_table.py

- to .execute() the same table (or a copy) from multiple threads
Closes #64
Closes #1768

fix(sqlite): defer db connection until needed

---

.github/workflows/assign.yml

This PR removes `assign.yml` which currently doesn't seem to serve a purpose
other than to eat up CI time.

ci: clean up issue assignment job

---

.github/workflows/update-deps.yml
default.nix
nix/default.nix
nix/sources.json
poetry-overrides.nix
shell.nix

We run the backends tests elsewher in CI, so we do not need to run them in the nix setup. Non backend tests are still run as a sanity check for the environment.

ci: stop running backend tests in default.nix

---

.github/workflows/ibis-backends.yml
.github/workflows/ibis-main.yml

This PR sets up `simulate_release` (for non-backend CI) and a new `backends` job (for backend CI)
to have dependencies so that we can gate merging on these two jobs.

ci: set up checks with dependencies

---

.github/workflows/ci-data.yml

This PR adds a workflow to upload the previous day's workflow 
run information to a GCS bucket

ci: upload workflow run data to GCS daily

---

ibis/__init__.py
ibis/backends/base/__init__.py
ibis/tests/test_api.py

This PR removes the abstractmethod decorator from do_connect so that existing backends such as ibis-bigquery can continue to function with ibis 2.x

fix: address ibis-bigquery incompatibilities

---

.github/workflows/ibis-main.yml

This PR removes the conda recipe build, which is perenially outdated and a maintenance burden

ci: remove stale conda recipe build

---

.github/workflows/ibis-main.yml
.github/workflows/release.yml
.releaserc.json
ci/release/dry_run.sh
ci/release/prepare.sh
ci/release/publish.sh
ci/release/run.sh
ci/release/verify.sh
docs/web/release_notes.md
pre-commit.nix
pyproject.toml

This PR adds automatic releases using `workflow_dispatch` (click-to-run).
The steps that happen (though not necessarily in this specific order) are:
1. Update the version number in `pyproject.toml`
1. Generate release notes (in `docs/web/release_notes.md`)
1. Commit all changes
1. Tag the commit
1. Push the commit and tag
1. Build a wheel
1. Publish wheel and sdist to PyPI
1. Publish a new release to github (wheel and source) using the generated release notes
Here's an example of what a release looks like:
https://github.com/cpcloud/protoletariat/releases/tag/v0.5.5
Our releases will of course have many more bullet points.

ci: setup automatic releases

---

docs/Makefile

In further evidence that computers were a mistake, because `nix` sets
`SOURCE_DATE_EPOCH=1` when it builds things and because Sphinx has a
workaround for bugs in _different_ packages that might be doing
something silly with dates, we need to explicitly set
`SOURCE_DATE_EPOCH` so we don't end up 40+ years in the past.
https://github.com/sphinx-doc/sphinx/issues/3451

docs: fix copyright years for Sphinx pages

---

ibis/backends/base/sql/alchemy/registry.py
ibis/tests/sql/test_sqlalchemy.py

This PR addresses #3163.
It turns out that we weren't examining parent contexts when looking up tables
in the SQLAlchemy backend. Without this, a table subexpression would get
recompiled instead of looked up. We have to look into the outer scope since the
referenced expression may not be available in the current context, in this case
precisely because of the correlated subquery.
Closes #3163.

fix: correlated subquery with join generates incorrect SQL

---

docs/source/backends/clickhouse.rst
docs/source/backends/datafusion.rst
docs/source/backends/impala.rst
docs/source/backends/mysql.rst
docs/source/backends/postgres.rst
docs/source/backends/pyspark.rst
docs/source/backends/sqlite.rst
docs/source/tutorial/01-Introduction-to-Ibis.ipynb

Add in links to conda-forge backend-specific packages.
Also standardized heading precedence for the RST stuff that's still
here.
Finally, fixed a broken link in the tutorial intro notebook and fixed up
a rotten link to a pyspark + pyarrow explainer.
Finishing up #2448

docs(install): update backend specific install options

---

.github/workflows/ibis-main.yml

Versions will be managed in separate directories, not by tags so this code is unnecessary

ci: remove git tagging from docs build

---

.github/workflows/ibis-backends.yml
.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-main.yml

This moves all of the docs + linting checks to a separate GHA yml file
that is always executed for pushes to or PRs against `master`.
Other tests are in `ibis-backends.yml` and `ibis-main.yml` and these are
also run for pushes and PRs except if the only files touched are within
the `docs/` subfolder.
Going to run this first without any docs-changes to confirm all checks still run, then will push a docs change to confirm the lighter touch.

ci(docs): skip backend tests if _only_ docs have been touched

---

.github/workflows/test-report.yml

This PR fixes an issue with test reports overwriting each other in the case where a lot of builds are queued, by running against PRs instead of the latest completed workflow

ci: fix racy workflow run test reports

---

.github/workflows/ibis-backends.yml

This PR brings back an additional job which is running the postgres backend tests with 3.7 agains the latest set of dependencies for that backend

ci: test latest postgres backend deps with python 3.7

---

ibis/expr/datatypes.py
ibis/tests/expr/test_datatypes.py

Fixes #3136 
You can still cast from UUID to String, but UUID no longer inherits from string (this also removes the need for an extra dispatch rule in the `_normalize` function)

refactor: dt.UUID inherits from DataType, not String

---

.github/workflows/test-report.yml

Use the workflow_run head instead of the non-existent PR number

ci: fix the test report yet again

---

ibis/backends/dask/execution/generic.py
ibis/backends/dask/execution/util.py

Min is now 2021.10 (via https://github.com/ibis-project/ibis/commit/e6b5c095e562a0f1f1386efe578ca4562062154a),

refactor: remove da.select shim after dask min version is 2021.6.1

---

ibis/expr/format.py
ibis/tests/expr/test_format.py
ibis/tests/expr/test_temporal.py
ibis/tests/expr/test_value_exprs.py

This tightens up the format string returned by `repr(expr)`.  Some tests had to be adjusted as they depended on the literal output.

fix(format): remove some newlines from formatted expr repr

---

.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-main-skip-helper.yml

These intentionally collide with the jobs in `ibis-main.yml` and
`ibis-backends.yml` and run on the inverse of the path skipping logic
present in those two files.
This should allow CI to finish and all jobs to return, even if they're
skipped.
This is an ugly hack, but is the supported one for now:
https://github.com/github/docs/commit/4364076e0fb56c2579ae90cd048939eaa2c18954#diff-3052509b0e9a9ca90d0b911cc12c333506e652dbac7c7d5bd41d462be5c07dfdR48
Rendered docs for skipping procedure: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks

ci(docs): add dummy jobs that return in place of skipped required jobs

---

ibis/expr/rules.py

Avoid calling into the TableExpr's repr within these rule validator error messages, and instead use `type(table)`. Using the O(N) repr causes performance issues when called in a tight loop.
See this issue for a follow-up idea: https://github.com/ibis-project/ibis/issues/3334

Remove full tree repr from rule validator error message

---

ibis/expr/datatypes.py
ibis/expr/operations/generic.py
ibis/tests/expr/test_value_exprs.py

This PR allows the construction of decimal literals from strings, integers and decimal.Decimal objects. It will correctly adjust scale of the input depending the passed datatype

feat: allow construction of decimal literals

---

.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-main-skip-helper.yml
.github/workflows/ibis-main.yml
.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml
default.nix
poetry.lock
pyproject.toml

This PR changes our nix builds to only when relevant files such as any nix files as well as dependency related files have changed.

ci: run nix builds only when relevant files have changed

---

ibis/expr/analysis.py
ibis/tests/expr/test_table.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_sqlalchemy.py

This PR addresses an annoying bug where filtering an aggregate column
after aggregation would get merged into its child. This optimization
is only valid for non-aggregate columns.
The solution here is to force incoming predicates to derive from the
aggregate table instead of trying to push them into the aggregate.
This allows projection fusion to continue to work, while fixing
#2907.
Here are the other approaches I tried before arriving at this solution:
1. Removal of the predicate pushdown code
This isn't viable because it breaks a number of APIs around projection and predicate creation
2. Adjusting the `blocks()` method to return `True` when an incoming column name overlaps with an
aggregate column during substitution
This might be viable, but it was more code to change
Closes #2907

fix: correct results when a group_by is followed by a filter

---

ibis/expr/signature.py
ibis/tests/expr/test_signature.py
ibis/tests/util.py

Fixes https://github.com/ibis-project/ibis/issues/3358.

fix: ibis.expr.signature.Parameter is not pickleable

---

.rgignore
ibis/backends/dask/__init__.py
ibis/backends/dask/tests/test_client.py
ibis/backends/pandas/__init__.py
ibis/backends/tests/test_client.py
ibis/common/exceptions.py

This PR addresses incorrect implementations of create_table in the pandas and dask backends.
The backends now store an additional dictionary mapping inferred or user-specified (when `create_table` is called)
ibis Schema objects, and uses those to construct `TableExpr`s from `client.table`.
Closes #3020.

fix: implement create_table correctly for pandas and dask backends

---

ibis/expr/api.py
ibis/expr/schema.py

fixes #3040
I had to create an alias for the `schema` function since the `table` function has a `schema` argument, please let me know if there is a cleaner approach or if I missed something.
Thank you very much!

refactor: using ibis.expr.api.schema inside ibis.expr.api.table

---

ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/pyspark/tests/test_ddl.py

Closes #2879. We really need to avoid xfailing without understanding the reason for the failure.

fix: implement count on tables for pyspark

---

ibis/backends/mysql/registry.py
ibis/backends/tests/test_generic.py

Quick fix to add `ops.IfNull` to the `mysql` backend and remove a now-unnecessary test decorator.

fix: expose ops.IfNull for mysql backend

---

ibis/expr/types/core.py
ibis/tests/expr/test_pipe.py

`__call__` is gone and it isn't coming back.
Resolves #2258
BREAKING CHANGE: `Expr() -> Expr.pipe()`

refactor: remove blanket __call__ for Expr

---

conda-lock/linux-64-3.7.lock
conda-lock/linux-64-3.8.lock
conda-lock/linux-64-3.9.lock
conda-lock/osx-64-3.7.lock
conda-lock/osx-64-3.8.lock
conda-lock/osx-64-3.9.lock
conda-lock/win-64-3.7.lock
conda-lock/win-64-3.8.lock
conda-lock/win-64-3.9.lock
ibis/backends/clickhouse/__init__.py
poetry.lock

Tests starting failing for `clickhouse_driver==0.2.3` (showing up after running `poetry update`). This PR fixes the underlying cause.

fix: disconnect from clickhouse when computing version

---

ibis/backends/dask/tests/execution/test_arrays.py
ibis/backends/dask/tests/test_datatypes.py
ibis/backends/pandas/tests/execution/test_arrays.py

Small fixes to some of the dask tests to remove tests that aren't checking anything of value and editing `test_series_to_ibis_literal` to make use of `ibis.array` and check execution.

chore: fix dask array literal test

---

ibis/backends/postgres/tests/test_client.py

This PR removes a test that is flaky when parallelized. Since the database API is deprecated, there is no reason to leave this around

test: remove flaky test

---

.github/workflows/ibis-backends.yml

This PR changes the datafusion ci to run against a released version, as upstream does not have a rapid pace of development at the moment there is no real need to spend the time testing against master.

ci: test datafusion backend as a simple backend

---

ibis/backends/datafusion/datatypes.py

In datafusion backend. 
I believe this is the correct type as I can't find `TimestampType` in `ibis.expr.datatypes`.

fix: change TimestampType to Timestamp

---

ibis/backends/pandas/execution/util.py
ibis/udf/vectorized.py

As mentioned by @cpcloud in https://github.com/ibis-project/ibis/pull/3387#issuecomment-1031342083, I made the `coerce_` functions private.
I am a bit unsure about the `_coerce_to_dataframe`, does it need to be private even if it is imported in another module?
Please let me know if I should change some other things. Thanks :)

refactor: make coerce functions in ibis.udf.vectorized private

---

ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/tests/expr/test_value_exprs.py

This PR implements `_repr_html_` for interactive mode (currently delegating to
pandas implementation) to enable pretty printing tables in the notebook.

feat: add repr html for pretty notebook tables

---

ibis/backends/postgres/tests/test_functions.py
ibis/expr/operations/generic.py
ibis/tests/expr/test_value_exprs.py

This PR addresses a bug where a `null`-typed expression occuring first in a `CoalesceLike`
operation results in an expression `output_type` of `null`.
The algorithm used here is to remove all `null` typed expressions and then pass the
resulting list to `ibis.expr.datatypes.highest_precedence_dtype`.

fix: fix coalesce-like type inference

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/tests/test_client.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/sqlite/udf.py
ibis/backends/tests/test_client.py

This PR deletes a good chunk of code from some of the sqlalchemy-based backends,
allowing them to use the base class code where possible.
Notable changes:
- Remove of the `has_attachment` hack in favor of a private `_current_schema` property, specific to a backend.
- Removal of the `create` parameter to the sqlite backend. There is no substitute here, this is a breaking change.
- Allowance of the string `":memory:"` for the `path` argument to the sqlite connection API.
- Implementation of the `force` argument to `create_table` on the base sqlalchemy backend class.

refactor: reuse more sqlalchemy base class code

---

.github/workflows/ci-data.yml

This PR changes our GitHub Actions ci data to be inserted directly into BigQuery as opposed to reading from JSON. Queries on the data are much faster and can be integrated with Google's BI suite much better.

ci: insert directly into bigquery

---

ci/datamgr.py
ibis/backends/clickhouse/compiler.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/impala/__init__.py
ibis/backends/impala/tests/conftest.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/execution/join.py
ibis/backends/pandas/tests/execution/test_join.py
ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/base.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_temporal.py
ibis/expr/schema.py
ibis/tests/expr/test_schema.py
nix/default.nix

This PR implements most remaining joins, to allow nearly all of them to
successfully pass the join backend test. The test itself has also been
simplified.
Things done:
- clickhouse joins
- pyspark coalesce
- semi/anti join for pyspark
- semi/anti join for pandas
- enforcing column names, not just types, in `Schema.apply_to`; this is the handle the
impala case where column names' case may not match the actual schema's
columns' case.
Things still not working:
- clickhouse right/outer joins; the results don't seem to match up to any other
backend because values selected from the right table on right join are zero
or null when there's no match, similar behavior occurs with outer joins
Things not yet implemented in ibis:
- datafusion; joins aren't implemented
- dask; semi/anti joins aren't …

feat: implement most remaining joins

---

docs/overrides/main.html

This adds analytics for ibis-project.org using [goatcounter](https://www.goatcounter.com/).
goatcounter is privacy preserving, and strives to be GDPR compliant.

docs: add goatcounter analytics

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/string.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_string.py
ibis/expr/api.py
ibis/tests/expr/test_value_exprs.py

This PR fixes the broken __mul__/__rmul__ implementation to use ops.Repeat instead of ops.Multiply which is only defined for NumericValue.

fix(api): map string multiplication with integers to repeat method

---

ibis/config.py
ibis/tests/expr/test_visualize.py

Turn off graphviz repr by default in Jupyter notebooks.
This is causing some annoying things in our docs that I haven't been able
to reproduce anywhere:
It should be opt-in anyway. This PR implements the necessary changes.

refactor(config): disable graphviz-repr-in-notebook by default

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/mysql/registry.py
ibis/backends/postgres/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_temporal.py

This PR implements truncate for date types in the SQLite backend, and generalizes the implementation of date for the SQLAlchemy based backends.

feat(sqlite): implement date_truncate

---

ibis/backends/tests/test_join.py
ibis/expr/analysis.py
ibis/tests/expr/test_analysis.py
poetry.lock
pyproject.toml

Fixes #3529 
Fixes #3515 
I traced the failure mode in #3529 to `ibis.expr.analysis._lift_TableColumn` -- there wasn't a readily apparent way to fix the failure there (or even how to special case it), but removing the entire code path definitely fixes things.  That's not always the best way to fix things, but I think a lot of the expr rewriting stuff is probably causing a lot of issues on the edges.
In any case, I tried a bit to quantify what, if any, time savings are offered by having the `_lift_TableColumn` path available and the results are below.  Usual caveat around how all benchmarks are terrible.
TLDR: For the runs below, removing the expr rewrite has no performance impacts and allows joining on mutated columns, but there may be cases not covered here that would suffer.
**All times …

fix(mutate): do not lift table column that results from mutate

---

.github/workflows/conda-lock.yml

This also pins to conda-lock pre 1.0 to debug why the extras weren't working correctly

ci: add kind explicit to conda-lock invocation

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/mysql/compiler.py
ibis/backends/postgres/compiler.py
shell.nix

This PR removes the spurious support for geospatial operations in duckdb

refactor: remove geospatial from unsupported backends

---

ibis/backends/dask/tests/execution/test_cast.py
ibis/backends/pandas/tests/execution/test_cast.py

This PR fixes tests that are sensitive to timezone changes.

test: don't use now in pandas and dask cast tests

---

ibis/tests/benchmarks/test_benchmarks.py
pyproject.toml

This PR adds attribute access benchmarks so that we have a baseline

test(bench): add attribute access benchmarks

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/duckdb/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_string.py

This PR fills out a number of features in a few backends:
1. `StringSQLILike` equivalent to SQL's `ILIKE` operator, for all sqlalchemy backends
2. log base `b` for all backends except clickhouse and datafusion
3. `RegexExtract` for duckdb
4. `ArrayIndex` for duckdb
5. `RegexReplace` for duckdb
I also removed failing string tests that were pyspark specific since pyspark now passes on vanilla Perl regexen tests.

feat(duckdb): fill out regexp_replace and array indexing APIs

---

ibis/backends/tests/test_aggregation.py
pyproject.toml

This PR removes the use of markers that no longer exist.

chore: remove dead backend markers

---

ibis/backends/tests/test_generic.py
ibis/expr/signature.py

This PR speeds up attributes access.
Local benchmarking shows about a **6x** speed up when accessing attributes.
An individual access isn't that expensive, but in a tight loop, the overhead of `@property` plus tuple construction adds up to quite a lot.
This PR is a prerequisite for #3594. We should be able to get a sub-millisecond TPC-H query 2 repr in #3594 after this PR.

perf(expr/operations): speed up args and argnames attribute access

---

docs/backends/SQLite.md
ibis/backends/base/sql/__init__.py

Also adds a `NotImplementedError` to the base class for child classes
that don't implement `_get_schema_using_query`.
This isn't the solution that I wanted for the docs, but it works.
There are options to `filter` out `members` in `mkdocstrings` but the
`filter` option is currently incompatible with `inherited_members`.
ref: #3610

doc(sqlite): remove unavailable sql method from sqlite docs

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/clickhouse/registry.py
ibis/backends/postgres/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_temporal.py

This PR adds StringJoin and StringConcat rules for the SQLite backend. Unit tests are also included. Closes #3611.

feat(sqlite): implement string join and concat

---

ibis/backends/base/sql/compiler/query_builder.py
ibis/expr/datatypes/__init__.py
ibis/expr/operations/core.py
ibis/expr/operations/generic.py
ibis/expr/operations/relations.py
ibis/expr/schema.py
ibis/expr/signature.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/window.py
ibis/tests/expr/test_datatypes.py
ibis/tests/expr/test_value_exprs.py
ibis/util.py
pyproject.toml

This PR refactors the caching mechanism for expr and op equality comparison. Previously we were caching in a very ad hoc manner. After this PR, subclasses of util.CachedEq need only implement the `_raw_equals` interface to gain the benefits of caching. Additionally, some comparisons have been specifically implemented to hit the short circuit path as soon as possible.

perf(ir): speed up expr and op equality comparisons by caching

---

ibis/expr/datatypes/__init__.py
ibis/expr/operations/temporal.py
ibis/expr/types/temporal.py

This PR moves `DataType` and its subclasses away from `__slots__` and replaces the current
property caching with `cached_property`s.

refactor(datatypes): make DataType and friends immutable and remove __slots__usage

---

ibis/expr/operations/core.py

This PR removes the private `_expr_cached` field, as it does not appear to have any noticeable effect.

refactor(ir): remove _expr_cached Node property

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/pyspark/__init__.py
ibis/expr/signature.py
ibis/expr/types/core.py
ibis/expr/types/relations.py
ibis/tests/expr/test_signature.py
ibis/tests/expr/test_table.py
ibis/util.py

This PR adds a no-op materialize along with a deprecation warning.
This will help us break less code out in the wild, since in many cases
materialize was a pass through.

refactor(api): add no-op materialize

---

ibis/expr/types/groupby.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py
ibis/tests/expr/test_window_functions.py

BREAKING CHANGE: Columns that were added or used in an aggregation would
be alphabetically sorted in compiled SQL outputs.  This was a vestige
from when Python dicts didn't preserve insertion order.  Now columns
will appear in the order in which they were passed to `aggregate`

refactor(expr): preserve column ordering in aggregations

---

ibis/expr/analysis.py
ibis/expr/datatypes/core.py
ibis/expr/format.py
ibis/expr/timecontext.py
ibis/expr/types/arrays.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/types/groupby.py
ibis/expr/types/logical.py
ibis/expr/types/maps.py
ibis/expr/types/relations.py
ibis/expr/types/strings.py
ibis/expr/types/structs.py
pyproject.toml

I haven't gone through everything, but the largest chunk of repr docstrings are in `ibis/expr/` and I've updated all of those to reflect the new expr repr.  I also ran across a repr that needed `ops.TimeAdd` so I've added that to the mapping of binop formatting options

update docstrings to match new expr repr

---

ibis/common/grounds.py

`flat_args()` should be and already is defined on `Node`

refactor(common): remove Annotable.flat_args

---

docker-compose.yml
ibis/backends/mysql/__init__.py
ibis/backends/mysql/datatypes.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/mysql/tests/test_client.py

This PR implements `_get_schema_using_query` for the MySQL backend.
I originally was going to add this in #3642, but it became significantly complex
that I broke it out into a separate PR.
Closes #2002.

feat(mysql): implement _get_schema_using_query

---

ibis/common/grounds.py
ibis/common/tests/test_grounds.py
ibis/common/validators.py
ibis/expr/operations/core.py
ibis/expr/operations/relations.py
ibis/expr/schema.py

Should be useful for scenarios like `output_dtype`, `output_shape` and `output_type` defined in https://github.com/ibis-project/ibis/pull/3276
The following class calculates and stores `double_a`'s output value in a slot like it were a cached property.
```py
class ValueOp(Annotable):
a = IsInt
@promoter
def double_a(self):
return 2 * self.a
```
TODO: I'd like to mimic the use case of `output_dtype` in additional unit tests, meanwhile preliminary reviews are welcome.

refactor(common): more convenient way to define cached properties for Annotable subclasses

---

ibis/backends/clickhouse/__init__.py
pyproject.toml

Previously we ignored "ignored exception" warnings when running `pytest`.
It turns out that these were coming from ibis's slight misuse of the clickhouse-driver
Client, where we weren't closing the connection when an error occurred during execution of
an `xfail` test.
Using the `Client` instance as a context manager handles this for us, and the test is that
no new failures occur from removing the warning ignorance.

fix(clickhouse): use a context manager for execution

---

ibis/backends/dask/execution/join.py
poetry.lock

This PR works around a bug introduced in merge_asof in https://github.com/dask/dask/pull/8857, where when the `on` argument is falsey the `right_on` columns are duplicated in the right dataframe. The subsequent call to `reset_index` in the `merge_asof` implementation fails.

fix(dask): workaround dask/dask#8857

---

.github/workflows/ibis-main-skip-helper.yml
docs/backends/template.md
docs/index.md
docs/user_guide/udfs.md

This PR converts absolute links to relative links, which is necessary after changing our
docs to support multiple versions. We don't want to link to the site root, but rather the link
should be relative.

docs: convert absolute links to relative links

---

shell.nix

This PR reduces the size of the nix shell JDK by using the headless version.
Here's a comparison of their sizes:
```
❯ nix path-info -ShsL 'nixpkgs#openjdk11_headless' 'nixpkgs#openjdk11' | sort -h -k2
/nix/store/6x9vk1cm44d9hlv2cvv4jzn2qqlxgasm-openjdk-headless-11.0.12+7   523.5M  563.1M
/nix/store/2k27v0z85z9das0c70qs2vqpgxiky6kh-openjdk-11.0.12+7            681.7M    1.4G
```

chore(dev-deps): use a headless jdk in nix shell

---

ibis/expr/format.py

trying this out.  there are a lot of ways to make this more complicated
and some of them might be worth it, but this seems to provide a little
more information with a tiny footprint.
closes #3668
in re: other options:
If we don't want to special-case the Interval repr, we could redefine Interval as a subclass of Literal so we can catch it explicitly in the single dispatch.
Other possible changes / improvements:
More verbose unit descriptions (`seconds` instead of `s`)

feat(repr): add interval info to interval repr

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/conftest.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/base.py
ibis/backends/tests/test_dot_sql.py

Hopefully this is the last of the flakiness fixes for the pyspark test suite.

test: localize table creation instead of altering existing batting table

---

ibis/backends/pandas/execution/window.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_window.py
ibis/expr/types/sortkeys.py

This PR address issues with range windows in the pandas and pyspark backends.
1. PySpark does allow a wider range (forgive the pun!) of `RANGE` windows, so
that was simply altering the code path and allowing the test through.
1. We don't yet implement arbitrary `RANGE` windows with the pandas backend
because there's so obvious way to do this with pandas itself, so only
temporal range windows are allowed (which have been implemented for a while).
Closes #2709.

fix(pyspark/pandas): fix range window bugs, disable arbitrary pandas range windows

---

.releaserc.json

This PR disables PR commenting by the semrel bot, because it's just too slow when there are a large number of PRs in between two releases.

chore: disable semrel PR/issue commenting

---

ibis/backends/base/sql/alchemy/registry.py

This PR replaces corresponding_column with a simpler but equal-for-our-purposes API exported_columns

refactor(sqlalchemy): use exported_columns instead of corresponding_column

---

.github/renovate.json

This PR enables renovate on our docker-compose setup.

ci: run renovate over docker-compose setup

---

justfile

This PR makes it much easier to run benchmarks locally

chore(dev): make it easier to run benchmarks

---

ibis/backends/pandas/execution/selection.py
pyproject.toml

The warning is valid in many contexts, but it's spurious here and it's
quite loud.
Despite my memory of `warnings.filterwarnings` serving as a contextmanager, it
doesn't appear to do so, so I've created a simple one that silences the pandas
warning in question, then restores it on exit.
Fixes #3702

fix: filter SettingWithCopyWarning to silence user-facing warning

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/tests/test_aggregation.py
ibis/util.py
pyproject.toml

This PR addresses an annoying bug where we were inadvertently generating an
implicit cross join for left semi/anti-join queries for the SQLAlchemy
backends.
The fix is to always select from the compiled `table_set` by replacing the
single `FROM` in the `result` selections with `table_set`.
Closes #2131.
Closes #2132.
Closes #2612.
Closes #3526.

fix(sqlalchemy): don't generate cartesian product for semi/anti-join in topk

---

.gitignore
.releaserc.json
ci/release/dry_run.sh
ci/release/run.sh
ibis/__init__.py
poetry-overrides.nix
poetry.lock
pyproject.toml
setup.py

This adds a dynamic version identifier to Ibis installs -- this should
have no discernable impact on users installing from `conda` or
`pypi` (or from released versions generally).
For users who install from source, it generates a version of the form:
```
<most_recent_release>-post.<numcommits_since_release>+<short_sha_of_HEAD>(.dirty)?
```
The `dirty` suffix is added if there are unstaged changes when the
install is performed.
This will help us help users and other devs track which exact version is
installed when troubleshooting / comparing performance.
The `version` identifier in `pyproject.toml` is not affected by this
process and should display the last released version (currently 2.1.1).
The `__version__` string in `ibis/__init__.py` is now also hard-coded to `"2.1.1"`
During a …

feat(ver): dynamic version identifiers

---

ibis/common/grounds.py
ibis/common/tests/test_grounds.py

fix(annotable): allow optional arguments at any position

---

.releaserc.json
ci/release/dry_run.sh
ci/release/run.sh

This PR changes our release notes style to conventionalcommits. Among other small cosmetic changes, this puts breaking changes at the top of the release notes for maximum visibility.
Here's an example of what that looks like:

style(release): use conventional-commits style

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/dask/execution/generic.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/execution/test_operations.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/compiler.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_column.py
ibis/expr/operations/generic.py
ibis/expr/types/generic.py
ibis/tests/expr/test_value_exprs.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_sqlalchemy.py

Remove `ColumnExpr.distinct()` because it's a confusing API.
This is a breaking change.
Here are a few examples of why this method is easily misused, confusing and error prone:
```
>>> import ibis
>>> t = ibis.table(schema=[("a", "int64"), ("b", "string"), ("c", "string")], name="t")
>>> t.a.distinct().log().distinct()  # what does this even compile to?
>>> t.b.length().distinct() + t.c.distinct().length()  # again, this is very ambiguous if defined at all
```
The `TableExpr.distinct()` method still exists, so it's still possible to
compute distict rows, but it can no longer be done with `t.foo.distinct()`.
Note that this doesn't prevent the following operation from being constructed, but
it will fail to compile due to the expression having multiple leaf tables outside of
a join or …

refactor(api): remove distinct ColumnExpr API

---

.github/workflows/ibis-docs-lint.yml
ibis/tests/benchmarks/test_benchmarks.py
poetry.lock
pyproject.toml

This PR improves benchmarks in a few ways:
1. Bump the alert threshold to 3x to avoid more spurious alerts
1. Use module scoped pytest fixtures to avoid recreating the same thing multiple times
1. Run the compilation benchmark across all possible backends (dask,
datafusion, and pyspark are `xfail`ed because they don't support compiling
`UnboundTable`s)
1. Give every benchmark a benchmark group

refactor(benchmarks): add compile benchmarks for backends where possible; add benchmark groups

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-main.yml

This PR runs the visualization tests in the main workflow, instead of only in the setuptools check.

ci: run visualization tests in the main workflow

---

shell.nix

This PR adds two tools for looking at a generated changelog that more closely matches the final output as opposed to looking at the output of ci/release/dry_run.sh which uses a fake repo.

chore(dev): make it easier to render the changelog

---

ibis/backends/base/sql/alchemy/registry.py
ibis/tests/sql/test_sqlalchemy.py

This PR fixes an issue where the `FROM` clause in correlated subqueries with `JOIN`s in the `FROM` clause
were not rendered.
The problem was that before SQLAlchemy 1.4 the behavior of automatically rendering a `FROM` clause
was implicit, while in 1.4 it's not. The solution was to make it explicit.

fix(sqlalchemy): correctly render from clauses in correlated subqueries

---

.github/workflows/ibis-docs-lint.yml

This PR changes the documentation alias "latest" to point to the next release. We should merge this right before we cut a release.

chore(release): move latest alias to release

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/clickhouse/tests/test_select.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_temporal.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_non_tabular_results.py

If the ColumnExpr is named, keep that name in the SQL query (and eventually in the resulting pandas series) rather than unconditionally using the name `tmp`
fixes #3754

fix(sql): retain column names for named ColumnExprs

---

ci/schema/clickhouse.sql
ci/schema/duckdb.sql
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/duckdb/__init__.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/test_array.py

This PR fixes array column type discovery on leaf tables inside of a database.

fix(duckdb): fix array column type discovery on leaf tables and add tests

---

.git-blame-ignore-revs
.gitconfig

This PR uses the ignore-revs feature of git blame to ignore the recent mass reformatting commits when blaming.

chore(dev): ignore mass import refactor in git-blame

---

docs/backends/index.md

OmniSci is being rebranded to HeavyAI. This updates the documentation link to the new `ibis-heavyai` backend.
The current link is already resolving to this new URL since the repo got renamed. There is a PR in progress that does the internal rebranding.

docs: rebrand OmniSciDB to HeavyAI

---

.github/workflows/ibis-tpch-queries.yml

Resolves #3782 
This currently relies on ibis-project/tpc-queries#4 in order to run against Ibis master.  So it's currently pointed at my fork in order to run.  I'm leaving this as a draft for now -- once we cut a new release and merge the corresponding tpc-queries PR, I can update this to start the TPC-runs

test: run tpc-queries on CI

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-docs-release.yml

This PR splits the release docs build into a separate workflow. For 3.0.0 I had to manually push the docs because the tag was not available when the push job ran. This PR should address that.

ci: split release docs build into separate workflow

---

docs/blog/Ibis-version-3.0.0-release.md

Changing the breaking changes section to 'Other Changes' and clarifying depreciation of materialize instead of removal of it.

docs: Adding updates to breaking changes section and materialize() 

---

.releaserc.json

This PR moves the version replacement step to execute before exec plugin so that wheels are published with an updated `__init__.py`.

fix(build): replace version before exec plugin runs

---

shell.nix

This PR fixes the possible TEMPDIR mismatch when building docs.

fix(docs): fix tempdir location for docs build

---

poetry-overrides.nix
poetry.lock
pyproject.toml

This PR unconstrains jinja2 and markupsafe by patching in the mkdocstrings upstream fix in `poetry-overrides.nix`.

chore(deps): unconstrain jinja2 and markupsafe

---

ibis/expr/datatypes/core.py
ibis/tests/expr/test_decimal.py

This tweaks the new behavior around decimal precision and scale.  If a
decimal has unbounded precision/scale, specified as `(None, None)`, then
the precision/scale of an aggregation of that column will also have
unbounded precision.
For a decimal with some bounded precision/scale, e.g. `(18, 2)`, the
precision/scale of an aggregation of that column will have a precision
of `(38, 2)` which is the previous default maximum for bounded precision
and matches up with _most_ backends.
Fixes #3833

fix: use bounded precision for decimal aggregations

---

ibis/expr/datatypes/core.py
ibis/tests/expr/test_decimal.py

The previous fix for decimals imposes an effective limit on decimal
precision -- it can either be 38 or unbounded.  In the case that the
user does want to specify a bounded precision/scale that are larger than
our defaults, they can now do that.

refactor(decimal): allow user to specify precision > 38

---

.github/workflows/ibis-docs-lint.yml
shell.nix

This PR addresses some usability concerns with the shell.nix setup: 1) cachix is unnecessary 2) shell.nix is not currently populating the cachix cache. Both concerns are addressed in this PR.

build(nix): improve usability of the nix shell

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/tests/test_aggregation.py
ibis/expr/analysis.py
ibis/expr/format.py
ibis/expr/operations/generic.py
ibis/expr/types/analytic.py
ibis/expr/types/relations.py
ibis/tests/expr/test_analysis.py
ibis/tests/expr/test_analytics.py
ibis/tests/sql/test_select_sql.py

This PR deprecates SummaryFilter and the currently-public TopK.to_filter method in favor of eagerly generating the semi-join. As a bonus, topk is now supported in the pyspark backend. Closes #2130 for real.

refactor: deprecate SummaryFilter in favor of inlining the semi-join

---

ibis/expr/api.py
ibis/expr/deferred.py
ibis/expr/rules.py
ibis/expr/types/groupby.py
ibis/expr/types/relations.py
ibis/tests/expr/test_value_exprs.py

This PR is an experiment to play with a way of avoiding `lambda`s using `_`.
Here's an example:
```python
t = ibis.table(dict(a="int64"), name="t")
expr = (
t.mutate(b=_.a - 2)
.select([(_.a.sum() + _.b.count()).name("b")])
.group_by(key=_.b.cast("string"))
.aggregate(total=_.b.mean())
)
```
The way this works is that a `Deferred` object graph is built, and resolved
element by element as needed, for example, in a projection or aggregation.
Every `Deferred` instance has a `resolve` attribute that accepts an ibis
expression and returns another ibis expression effectively replaying the graph.
The `_` object's `resolve` attribute is the identity function, which resolves to the
table expression from which the rest of the graph is evaluated over.

feat(api): underscore convenience api

---

ibis/backends/postgres/__init__.py

This is only an issue with the `postgres` backend -- there's a
_function_ called `udf` inside of the `postgres.udf` _module_ and we
import that function into the `ibis.backends.postgres` namespace, which
then prevents direct access to the module itself, e.g.
you can
```python
from ibis.backends.postgres.udf import existing_udf
existing_udf(...)
```
but can't
```python
ibis.backends.postgres.udf.existing_udf(...)
```
I aliases the import to avoid the collision.

fix: don't mask udf module in __init__.py

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/clickhouse/registry.py
ibis/backends/dask/execution/numeric.py
ibis/backends/datafusion/compiler.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_numeric.py
ibis/expr/analysis.py
ibis/expr/operations/analytic.py
ibis/expr/operations/logical.py
ibis/expr/operations/relations.py
ibis/expr/types/analytic.py
ibis/expr/types/logical.py
ibis/expr/types/numeric.py
ibis/expr/types/relations.py
ibis/expr/types/temporal.py
ibis/tests/expr/test_value_exprs.py

This PR moves the transformation of `.any()`/`.notany()` filters with outer
table references to happen at expression construction time, rather than the
current phase which is inside the compiler.
The changes are motivated by the following requirements:
1. Allow representation of `EXISTS` queries using Substrait
2. Simplify the codebase by moving towards removing rewrites during
compilation.
This PR fixes the modeling of `EXISTS` which is currently incorrectly modeled
as an analytic expression.
`EXISTS` expressions are nothing more than fancy predicates so they are modeled
as `BooleanColumn`s here.

refactor: move AnyToExistsTransform to expression construction time

---

ibis/expr/analysis.py

Since the `Alias` refactor the condition `expr.op().name != expr.get_name()` cannot be true anymore.

refactor(ir): remove analysis _is_aliased() function

---

ibis/backends/pyspark/__init__.py

This PR overrides the `BaseSQLBackend.has_operation` implementation for PySpark to correct its accuracy.

fix(pyspark): specialize implementation of `has_operation`

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/base/sql/registry/binary_infix.py
ibis/backends/pandas/execution/generic.py
ibis/backends/tests/test_generic.py
ibis/expr/analysis.py
ibis/expr/types/relations.py
ibis/tests/sql/test_select_sql.py

- refactor: rewrite filters at expression construction time
- chore(pandas/dask): implement TableArrayView
- chore: don't rewrite filters with Window operations

refactor: move filter rewriting to expression construction

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/expr/analysis.py

@cpcloud the new `_rewrite_filter` essentially does the same as `reduction_to_aggregation` which dispatches the logic to the `ScalarAggregate` class doing an almost identical `traverse and reconstruct expression` replacement as `_rewrite_filter`.
Could we generalize (even before using matchpy) this substitution logic to shortly represent the following?
```py
is_scalar_reduction =>
has_multiple_bases => 
cross_join_tables().aggregate()
else => 
table.aggregate()
```
Actually there is the substitutor class already, could we use that here?

refactor(ir): slightly simplify ScalarAggregate's implementation

---

ibis/expr/types/relations.py

Doesn't seem to be used anywhere else than in an ibis-bigquery test case: https://github.com/ibis-project/ibis-bigquery/blob/9dc580800d607b809433bb2a3f2da2ba43b2f679/tests/system/test_client.py#L643
cc @tswast

refactor(ir): deprecate ibis.prevent_rewrite

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/dask/execution/generic.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py

- test(generic): add zeroifnull tests
- feat(sqlalchemy): implement zeroifnull
- feat(pyspark): implement zeroifnull
- test(pandas): enable zeroifnull test
- feat(pandas): implement zeroifnull
- test(dask): enable zeroifnull tests
- feat(dask): implement zeroifnull

feat: implement zeroifnull for most remaining backends

---

ibis/backends/base/sql/compiler/select_builder.py

- refactor: tighten up `is_subquery` check
- refactor: reduce the amount of branching in `is_root`
- chore: remove unused `op_memo` field
- style: check for truthiness not length
- chore: add `deprecated` to `_collect_MaterializedJoin` and prevent coverage

refactor: increase coverage of `select_builder.py`

---

.github/workflows/conda-lock.yml

This PR turns off `continue-on-error: true` for `conda-lock` file generation because 3.10 works now and should fail if it stops working.

ci: remove `continue-on-error` for `conda-lock` job

---

.github/workflows/ibis-tpch-queries.yml
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/impala/udf.py
ibis/common/tests/test_grounds.py
ibis/expr/analysis.py
ibis/expr/operations/generic.py
ibis/expr/operations/logical.py
ibis/expr/operations/reductions.py
ibis/expr/operations/relations.py
ibis/expr/types/logical.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR splits `Any` and `NotAny` into their reduction versions with the same names,
and the previously-mashed-together `ExistSubquery` while preserving the `.any()` API and semantics.
This is a backwards compatible expression API change, but the value of `.op()`
is different.
It's slightly more optimistic than that though, because we're only moving the
time at which `ExistSubquery` is constructed to earlier in the expression
construction pipeline. Previously it was happening right after a user called
`.compile()` whereas now the transformation happens any time a user calls `.any()`.
Closes #3925.

refactor(ir): split `Any`/`NotAny` to reduction and `Exists`/`NotExists` subquery operators

---

ibis/expr/analysis.py
ibis/expr/lineage.py
justfile

- perf(lineage): ensure that expressions are not traversed multiple times in most cases
- build: more reasonable default parameters for `just bench`

perf(lineage): fix large construction perf regression

---

gen_matrix.py
ibis/backends/base/sql/__init__.py
ibis/backends/datafusion/__init__.py
ibis/backends/pandas/__init__.py

This PR does two things:
1. Makes the operation support matrix more accurate by rolling in the
pandas/dask UDFs as well as operations like Quantile that are not leaf
classes but are nevertheless constructed directly in our APIs.
1. Speeds up `hash_operation` by storing the supported operation set in an
`lru_cache`. This helps shave time on the backends that use single or
multiple dispatch and require calling `isinstance`/`issubclass`.

docs: make the operation support matrix more accurate

---

ibis/backends/impala/tests/test_sql.py
ibis/backends/pyspark/tests/test_window_context_adjustment.py
ibis/expr/analysis.py
ibis/tests/expr/test_analysis.py
ibis/tests/sql/test_select_sql.py

This PR fixes an issue where mutations with overlapping names
are erased during projection fusion.
Name overlap is only a symptom though and not the underlycausing
cause of the problem.
The real distinction that needs to be made is between projection columns that
are not equivalent expressions.
Here, the approach I took to prevent fusion in those cases was exactly that.
It's more conservative than it could be (for example, equivalence can be
considerd across a Selection with an empty `selections` list, for example), but
this code is already a pile of spaghetti and I didn't want to add to it.
Fixes #4003.
Fixes #2453.

fix(ir): make projection fusion more conservative to prevent mutation erasure

---

ibis/expr/analytics.py
ibis/tests/expr/test_analytics.py
poetry.lock
pyproject.toml
requirements.txt

Should've been done for 3.0, better late than never.

chore: remove `ibis.expr.analytics` module

---

ibis/expr/analysis.py
ibis/expr/lineage.py
ibis/expr/operations/relations.py
ibis/tests/benchmarks/test_benchmarks.py
ibis/tests/expr/test_analysis.py

This PR addresses a performance regression when constructing chains of joins.
The proximate issue was the reconstruction of equivalent projections of
a traversed `Selection` using `op.__class__(op.table, op.selections)`.
I've addressed this by adding a cached private `_projection` property that is
tied to unique instances of `Selection`.
There's some more investigation of the repeated computation to be done, but that
will be done in a follow-up.
Fixes #4036.

perf: make multiple joins fast again

---

ibis/backends/base/sql/registry/literal.py
ibis/backends/impala/tests/test_value_exprs.py
ibis/backends/postgres/registry.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_temporal.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_select_sql.py
shell.nix

Also fixes extraction for SQLite timestamp literals.
Closes #4054.

fix: fix millisecond extraction for postgres and duckdb

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/mysql/compiler.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/tests/test_temporal.py

fix(duckdb): remove timezone invocation from int-to-timestamp cast

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/registry/main.py
ibis/backends/base/sql/registry/window.py
ibis/backends/clickhouse/registry.py
ibis/backends/dask/execution/reductions.py
ibis/backends/duckdb/registry.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/expr/operations/reductions.py
ibis/expr/types/generic.py

Deprecated, with a plan to be fully removed in 4.0.0.
Closes #3961

refactor: rename CMSMedian to ApproxMedian, and HLLCardinality to ApproxCountDistinct

---

ci/datamgr.py
docs/contribute/04_backend_tests.md
ibis/backends/clickhouse/tests/conftest.py
ibis/backends/conftest.py
ibis/backends/dask/tests/conftest.py
ibis/backends/datafusion/tests/conftest.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/impala/tests/conftest.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/sqlite/tests/conftest.py
ibis/backends/tests/base.py
poetry.lock
pyproject.toml
requirements.txt

This PR adds a `load_data` to the `TestConf` for all of the current backends in `ibis/backends/{backend}/tests/conftest.py`. PR also removes references to `ci/datamgr.py load` from the `docs/contribute/05_backend_tests.md`.
If the database already exists, the database will be dropped, and recreated.
Expected that every backend in the future will have a `load_data` function in its `TestConf`.
This PR uses [filelock](https://py-filelock.readthedocs.io/en/latest/) to ensure that the databases are only instantiated once per test run. It handles the case for if `pytest-xdist` is used to create multiple `pytest` threads. With `pytest-xdist` session fixtures are invoked once per thread.
I attempted to follow the instructions [here](https://github.com/ibis-project/ibis/blob/master/docs/contribute/ …

test: use pytest fixtures to initialize and populate the backends once per run

---

ibis/backends/clickhouse/registry.py
ibis/backends/dask/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_aggregation.py

This PR implements covariance and correlation for the backends that support it.
Correlation in particular is odd in that there don't seem to be any backend
that we support that implement both population and sample correlation, despite
many of them implementing population and sample variance, standard deviation,
and covariance.
Here's the support matrix for correlation among the backends:
| Backend    | Population | Sample |
|------------|------------|--------|
| ClickHouse | ❌         | ✅     |
| Dask       | ❌         | ✅     |
| DuckDB     | ✅         | ❌     |
| Impala     | ❌         | ❌     |
| MySQL      | ❌         | ❌     |
| Pandas     | ❌         | ✅     |
| PostgreSQL | ✅         | ❌     |
| PySpark    | ❌         | ✅     |
| SQLite     | ❌         | ❌     |
To make this more …

feat: implement covariance and correlation where possible

---

ibis/backends/clickhouse/registry.py
ibis/backends/clickhouse/tests/test_functions.py
ibis/backends/clickhouse/tests/test_literals.py
ibis/backends/postgres/tests/test_functions.py
ibis/backends/pyspark/compiler.py
ibis/backends/sqlite/tests/test_functions.py
ibis/backends/tests/test_temporal.py
ibis/expr/api.py

This PR removes duplicate timestamp literal tests from individual backends and integrates the test
into a single backend-suite test.
cc @anjakefala

refactor: remove duplicate timestamp literal tests

---

ibis/backends/conftest.py
ibis/backends/impala/tests/conftest.py
justfile
pyproject.toml

This hook isn't necessary because a new temporary directory is created for each pytest invocation.

test: remove pytest_sessionfinish hook

---

ibis/backends/conftest.py
ibis/backends/tests/test_client.py

The recent test flakiness for duckdb appears to be related to the fact that the ddl_backend and alchemy_backend fixtures are not currently loading their data. This PR fixes that.

test: ensure that ddl and alchemy backends load data

---

poetry.lock
pyproject.toml
requirements.txt

This PR locks duckdb-engine to 0.1.9 so we can test against it in CI

build: lock duckdb-engine to latest version

---

ibis/backends/clickhouse/tests/conftest.py
ibis/backends/conftest.py
ibis/backends/impala/tests/conftest.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/sqlite/tests/conftest.py
ibis/backends/tests/base.py

This PR ensures that we do not share the data loading lockfile across all invocations of pytest.

test: only grab the parent directory when loading data if running in parallel

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/update-deps.yml
nix/sources.nix
shell.nix

This PR replaces use of cp with rsync in the nix shell shellHook which will avoid a copy when data already exists in ci/ibis-testing-data and thus speedup any direnv command that reloads the shell.

chore(dev-shell): speed up direnv by avoiding data copy on every reload

---

docs/tutorial/02-Aggregates-Joins.ipynb

Referenced:https://en.wikipedia.org/wiki/Antarctica

docs(tutorial): correct spelling of Antarctica

---

docs/about/team.md

Page with current url: https://ibis-project.org/docs/3.0.2/about/team/
"ibis is developed and maintained by a [community of volunteer contributors](https://github.com/ibis-project/ibisgraphs/contributors)."
Expected url: https://github.com/ibis-project/ibis/graphs/contributors

docs: fix broken url

---

.github/workflows/ibis-backends.yml

This PR addresses the failing backend CI by ensuring that other dependencies are not updated when testing lower bounds.

ci: ensure that only the lower bound dependencies are updated

---

.github/workflows/conda-lock.yml
.github/workflows/update-deps.yml

This PR reduces the dependency update cycle to once a week for conda lock and every 3 days for nix updates. The goal here is to reduce the number of commits from bots while still staying up to date. The nix updates could be less often, but I wanted to avoid dealing with having to split huge commit lists in the update action for now.

ci: update dependencies less often

---

ibis/expr/api.py
ibis/tests/expr/test_schema.py

This PR refactors `ibis.schema` to use `ibis.expr.schema.schema`, which allows `ibis.schema` to accept `Schema` objects as input. Closes #4159.

feat(api): accept `Schema` objects in public `ibis.schema` function

---

codecov.yml

This PR changes our codecov configuration to only run coverage against PRs.

ci: only run coverage on pull requests

---

ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_ddl.py
shell.nix

This PR should quell the remaining impala flakiness. We restrict the scope of connection fixtures to `"module"` as well as close them on teardown, which should prevent exhausting the connection pool until we can land the fixes to impala connection pooling from 4.x.x.

test(impala): restrict scope of connection fixtures and close connections on teardown

---

.github/workflows/conda-lock.yml

I am clearly bad at cron and should always verify with https://crontab.guru before committing anything.

ci: run condalock less frequently

---

ibis/expr/types/structs.py
ibis/tests/expr/test_value_exprs.py

Accessing the metadata of a struct field is cumbersome right now. This PR address that by `names`/`types`/`fields` properties to `StructValue` expressions to make this information easier to access.

feat(api): make struct metadata more convenient to access

---

.github/workflows/ibis-tpch-queries.yml

Since these tests are installed from a separate repo, we'll want to install the requirements from that repo to ensure the tests still run properly. Currently things are broken since `ibis-substrait` is missing.

ci: ensure tpc-h test deps installed

---

ibis/backends/base/__init__.py
ibis/expr/api.py

Add a toplevel API that can take either a URL or a path string, and connect to it, without having to specify the backend explicitly.  Auto-detect based on URL scheme or path extension.

feat(api): add toplevel ibis.connect()

---

ibis/backends/dask/trace.py
ibis/backends/pandas/trace.py

Closes https://github.com/ibis-project/ibis/issues/3171. 
We already had similarish logic in the `trace` functions themselves.

fix(pandas): force backend options registration on trace.enable() calls

---

ibis/backends/pandas/execution/selection.py
ibis/backends/pandas/tests/execution/test_join.py
ibis/expr/operations/relations.py

This PR fixes a bug when selecting from a join inside of another join using the pandas backend. Closes #4163.

fix(pandas): can't join a join-derived table expression to another table expression

---

ibis/backends/mysql/registry.py
ibis/backends/pyspark/tests/test_basic.py
ibis/backends/tests/test_temporal.py

* Added test_string_to_timestamp
* Proposed removal of "duplicate" test_string_to_timestamp in the pyspark-specific tests.
Timezones are currently not taken into account. Additionally, we might be able to factor this out so it can be used with other `sqlalchemy` backends. 
There was an existing `test_to_timestamp`, but it turned out to be specifically written for "integer to timestamp".
Potentially out of scope:

feat(mysql): implement StringToTimestamp

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/postgres/tests/test_postgis.py
poetry.lock
requirements.txt

This PR fixes an issue with numpy>=1.23 where the array interface now surfaces errors instead of silently ignoring them.

fix(geospatial): ensure that later versions of numpy are compatible with geospatial code

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This PR fixes an issue where the non-specific `file://`-or-no-prefix dispatcher rule split on the first `os.extsep` which meant
that paths like `/tmp/python3.10` would return an extension of `10`. Here we change it to use `Path.suffixes` instead.

fix(duckdb): ensure that paths with non-extension `.` chars are parsed correctly

---

ibis/expr/analysis.py

This PR removes the `"tmp"` name that is assigned to subquery filters.
This alias is never necessary since the filter is always part of a `WHERE`
clause and never enters into a projection column list directly.
This isn't a problem for ibis, but in `ibis_substrait` it makes comparing
expressions decompiled from substrait fail because of the
inserted-and-pointless alias.

refactor(analysis): remove `"tmp"` name from subquery filter rewriting

---

codecov.yml

Tries to delay codecov reporting until most CI runs have finished,
should cut down on PR noise.

ci: delay codecov reporting

---

ibis/backends/base/__init__.py
ibis/expr/operations/relations.py
ibis/expr/types/core.py
ibis/expr/types/relations.py
ibis/expr/types/structs.py
ibis/expr/window.py
poetry.lock
pyproject.toml
requirements.txt
setup.py

This is now available as `functools.cached_property` in Python 3.8+. An
external dependency should be unnecessary afaict.

chore(deps): drop `cached-property` dependency

---

.pre-commit-config.yaml
default.nix
nix/default.nix
poetry-overrides.nix
shell.nix

This PR cleans up some dead code in poetry-overrides.nix, from recent updates to nixpkgs and poetry2nix.

refactor: remove dead poetry-overrides

---

ci/schema/clickhouse.sql
ci/schema/duckdb.sql
ci/schema/postgresql.sql
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/duckdb/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/test_array.py

This PR adds the ability to parse the metadata from duckdb for multidimensional arrays as well as fixes a bug in type inference of such arrays. Closes #4236.

fix(sqlalchemy): fix parsing and construction of nested array types

---

shell.nix

This PR brings back using `builtins.toPath` in `shell.nix` so that `PYTHONPATH` tracks the local repo outside the nix store.

chore(dev): bring back `builtins.toPath` for `shell.nix` convenience

---

ibis/backends/tests/test_aggregation.py
ibis/expr/types/groupby.py
ibis/expr/types/relations.py

This PR fixes an issue where aggregation `by`, `metrics`, and `having` lists
containing `Deferred` objects (the thing that backs the `_` API) are not
resolved to expressions.

fix(api): ensure that `Deferred` objects work in aggregations

---

ibis/__init__.py
ibis/backends/conftest.py
ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/tests/test_api.py
poetry.lock
pyproject.toml
requirements.txt
setup.py

- Adds tab completion for backends, so e.g. `ibis.sq<tab>` will autocomplete to `ibis.sqlite`.
- Removes need for `importlib_metadata` backport dependency

feat(api): Backend tab completion

---

ibis/backends/clickhouse/__init__.py

From my experience using [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver), the user needs a decent bit of flexibility when configuring the client. For example, this is a common Client constructor used for our Clickhouse deployment:
```python
import os
from clickhouse_driver import Client
client = Client(
host=os.getenv("CH_HOST"),
user=os.getenv("CH_USER"),
password=os.getenv("CH_PASSWORD"),
port=9440,
secure=True,
verify=False,
database="default",
compression=True,
settings={"use_numpy": True},
)
```
Currently, I cannot get the Ibis Clickhouse connection to work because I can't pass in these kwargs.
I would like the ability to do:
```python
import os
import ibis
connection = ibis.clickhouse.connect(
host=os.getenv("CH_HOST"),
user=os.getenv("CH_USER"), …
```

feat(clickhouse): add ability to pass arbitrary kwargs to Clickhouse driver settings

---

ibis/backends/clickhouse/tests/test_operators.py
ibis/backends/postgres/tests/test_functions.py

https://github.com/ibis-project/ibis/blob/8c026390abe7a22742c538d6011a1db8bc2d62c9/ibis/backends/tests/test_numeric.py#L409
https://github.com/ibis-project/ibis/blob/d6f95d79256eb97427f043c02cc960d8749339d0/ibis/backends/tests/test_temporal.py#L768
Part of work for https://github.com/ibis-project/ibis/issues/3994

refactor: remove backend specific test_binary_arithmetic which are already in larger suite

---

ibis/backends/base/sql/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/impala/tests/test_client.py
ibis/backends/impala/tests/test_patched.py

This is _technically_ a breaking change but I am not marking it as
breaking because I don't imagine anyone is actually using the `results`
kwarg, and because it does nothing.

refactor(raw_sql): Remove unused `results` kwarg

---

ibis/backends/base/sql/registry/main.py
ibis/backends/dask/execution/generic.py
ibis/backends/pandas/execution/generic.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_temporal.py

This PR fixes issues with comparing timestamps and dates in the pandas and dask
backends as well as a bug in the impala translation rule for `StringConcat`
along the way.
Closes #4291.

fix: fix timestamp-date comparisons

---

docs/tutorial/01-Introduction-to-Ibis.ipynb
docs/tutorial/04-More-Value-Expressions.ipynb

mkdocs-jupyter cannot find relative links in upper directories with the
standard markdown syntax
(https://github.com/danielfrg/mkdocs-jupyter/issues/27). Switching to using relative hyperlinking with `<a>`.
Closes #4064, closes #4201
I tried to test using `mike` versioning in my local build, but had a hard time figuring out how to add my `docs-relative` branch to it. I tested with the basic `mkdocs serve` to make sure it was at least functional there. 
`mike` advice is welcome. Otherwise this has a decent chance of succeeding, and I feel worth trying out with the `dev` docs.

docs: fix relative links in tutorial

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR adds, with full backwards compatibility, a shorter and more convenient notation for projections:
1. Existing code still works.
You can still write things like
```python
t.select([(t.a + 1).name("b")])
```
2. You can leave the `list`s at home:
```python
t.select((t.a + 1).name("b"), t.x.length().name("c"))
```
3. You can use keyword arguments instead of calling `.name(...)`:
```python
t.select(b=t.a + 1, c=t.x.length())
```
4. You can combine any of these as long as it's valid Python syntax:
```python
t.select(t.x.length().name("c"), [t.y.split(",").name("z")], b=t.a + 1)
```

feat(api): allow transmute-style select method

---

ibis/backends/pandas/execution/generic.py
ibis/backends/tests/test_aggregation.py

This PR is a follow up to #4304 to add the same support for `NotContains` as we have for `Contains`.

fix(pandas): implement `NotContains` on grouped data

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_client.py

Backwards compatible fix for #4282.
This is fixed upstream in https://github.com/Mause/duckdb_engine/issues/338,
but we can address it in ibis without requiring users to upgrade `duckdb_engine`.
This PR implements the same fix in ibis.
Fixes #4282.

fix(duckdb): ensure that in-memory connections remain in their creating thread

---

docker-compose.yml

When trying to run `docker-compose up` the `mysql` container would never come up. The logs mentioned "Can't initialize timers" and the first result that came up was https://github.com/MariaDB/mariadb-docker/issues/434 which has this comment https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1135889824 which mentions pinning to `10.8.2`. After pinning to that version everything seemed to work fine.

Pin Mariadb to 10.8.2

---

ibis/backends/pandas/execution/join.py
ibis/backends/tests/test_join.py

This PR fixes support for anti-joins in pandas. Currently a pandas anti-join will filter out a row if any of the columns match versus all of the columns matching. This changes the behavior to only remove rows where all columns match. This matches the behavior of the duckdb backend.
Potentially fixes: https://github.com/ibis-project/ibis/issues/4268

fix(pandas): Fix anti-joins

---

ibis/backends/tests/test_generic.py
ibis/common/grounds.py
ibis/expr/types/relations.py
poetry.lock
pyproject.toml
requirements.txt
setup.py

**Please read the entire description before reviewing**.
This PR introduces `rich` for outputting the content of `Table.info()`.
Ultimately I want to use `rich` to format the `Node` tree including datatypes
and schemas, so that deeply nested objects are approachable.
This PR is just a taste of using it in a non-invasive place.
**Note: this DOES NOT change the `Expr` repr**.
The `Expr` repr will continue to be the same: optimized for speed and concision.
Here's a screenshot of what it looks like after this PR:

feat(ux): use `rich` to format `Table.info()` output

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/duckdb/compiler.py
ibis/backends/tests/test_client.py
ibis/expr/datatypes/core.py
ibis/expr/operations/temporal.py
ibis/expr/rules.py

- Adds unsigned integer support for the sqlalchemy backends, only implemented for duckdb so far. Things work, but I'm 100% sure there's a better way.
- Modifies the integer numeric promotion rules so that (some) unsigned integer arithmetic works
At this point for duckdb, you can:
- create tables with unsigned integers in the schema
- load tables with unsigned integer columns
- compute reductions on unsigned integer columns
- do (some) arithmetic between unsigned integer columns
Still needs more work and tests.
Fixes #4224.

feat(duckdb): unsigned integer support

---

ibis/expr/types/relations.py
ibis/expr/types/structs.py
ibis/tests/expr/test_struct.py

This PR adds a `Table.unpack()` API to support projecting struct fields into
their child tables as well as a `StructValue.lift` method that lifts struct fields into a table.
Tests and docstrings are included and showcase examples.

feat(api): add `StructValue.lift()` and `Table.unpack(*args)` API for projecting struct fields

---

ibis/__init__.py
ibis/tests/test_api.py

- list for KNOWN_BACKENDS was compiled by referencing the backends in
here that were not already part of ibis-framework:
https://ibis-project.org/docs/3.1.0/backends/

fix(backends): only recommend installing ibis-foo when foo is a known backend

---

ibis/expr/operations/__init__.py
ibis/expr/operations/generic.py
ibis/expr/operations/structs.py

This PR moves operations on structs into their own module under
`ibis/expr/operations` to be consistent with the rest of the
per-type-operations structure that we have.

refactor(internals): move struct operations to their own module

---

ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/pyspark/tests/test_aggregation.py
ibis/backends/pyspark/tests/test_null.py
ibis/config.py

Backends like the Pandas backend treat `np.nan`s as nulls when computing aggregations. The PySpark backend was not treating `np.nan`s as nulls, leading to results for aggregations that are inconsistent with other backends (e.g. I would expect `count` to ignore `np.nan`s).
This change filters out `np.nan`s in float columns when computing built-in aggregations on the PySpark backend.
I wasn't sure how to classify this change, but I marked it as a breaking change since it changes the behavior of existing Reduction operations. Let me know if I should change that.

feat(pyspark): add option to allow treating nans as nulls in the pyspark backend

---

ibis/expr/rules.py
ibis/tests/expr/test_decimal.py

closes #4319 
This PR addresses the type evolution for decimal types as specified [here](https://www.ibm.com/docs/en/i/7.1?topic=operators-decimal-arithmetic-in-sql). As I am relatively new to the ibis development environment, I was not sure where/how to add a testcase for this, so I just used the following code:
```python
import ibis
table = ibis.table(
schema=[("a", "decimal(4, 2)"), ("b", "decimal(5, 3)")], name="t"
)
res = table.projection((table.a + table.b).name('c'))
print(res.c.type())
res = table.projection((table.a * table.b).name('c'))
print(res.c.type())
```
Currently there are two main shortcomings of this PR that I see, both are hard for me to fix as I do not know ibis in-depth.
1. It only handles cases where there are two args given. I cannot see a case where this is not a …

fix(decimal): add decimal type inference

---

ibis/backends/clickhouse/datatypes.py
ibis/backends/clickhouse/tests/test_types.py

Using vdsql to connect to Clickhouse's own [playground](https://clickhouse.com/docs/en/getting-started/playground/) (`vdsql clickhouse://explorer@play.clickhouse.com:9440/\?secure=1`) exposed several types that weren't being handled by the Clickhouse backend type parser.  This PR adds them.

feat(clickhouse): add enum, ipaddr, json, lowcardinality to type parser

---

.github/workflows/ibis-backends.yml
.pre-commit-config.yaml
ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/conftest.py
ibis/backends/duckdb/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_client.py
ibis/common/dispatch.py
mkdocs.yml
poetry.lock
requirements.txt

This PR rounds out support for `ibis.connect` in the remaining backends.
Working with @saulpw we tried to use ibis+clickhouse through visidata and discovered
that that didn't work.
This PR should fix that issue. See notes below for more information.
* Query parameters are supported. They are passed in as keyword
arguments to the backend's `do_connect` method. A new `_convert_kwargs`
method on the base backend now exists to override any of the query parameter
values after parsing but before they are passed to the underlying backend
API.
* A backend test for exercising the different ways to use `ibis.connect` are included.
* This PR introduces `sqlalchemy` as a hard dependency for its handling of URL parsing.
* I deprecated `path` as a keyword argument to the sqlite and duckdb backend
and …

feat(api): enable `ibis.connect` for backends where it makes sense

---

ci/release/verify.sh
dev/lockfile_diff.sh
dev/poetry2setup
dev/update-lock-files.sh
docs/contribute/05_maintainers_guide.md
poetry.lock
setup.py

Turns out that we cannot workaround the hash seed stuff by ignoring ordering. Occasionally a poetry solve will result in different dask markers for the dataframe extra, depending on the ordering of extras it seems. This PR is to get other PRs to stop failing the dry run release step so often. I will follow up on the poetry issue tracker as soon as I have simple reproducer.

chore: revert `PYTHONHASHSEED` removal

---

ibis/backends/base/sql/alchemy/datatypes.py

Missing BLOB types found while accessing `mysql://rfamro@mysql-rfam-public.ebi.ac.uk:4497/Rfam`.

feat(mysql): register BLOB types

---

ibis/backends/base/sql/alchemy/translator.py
ibis/backends/clickhouse/registry.py
ibis/backends/dask/execution/reductions.py
ibis/backends/duckdb/registry.py
ibis/backends/pandas/execution/generic.py
ibis/backends/tests/test_aggregation.py
ibis/expr/operations/reductions.py
ibis/expr/types/generic.py

This PR adds support for `argmin` and `argmax` methods on column expressions. This was motivated by trying to reproduce [Scrooge McDuck](https://pdet-blog.github.io/2022/08/16/scrooge.html)

feat(api): add `argmin` and `argmax` APIs

---

ibis/backends/pandas/execution/temporal.py
ibis/backends/tests/test_temporal.py

This PR unifies the result value of `now` between pandas and dask and the SQL backends to be a localized UTC value

fix(pandas): use localized UTC time for `now` operation

---

ibis/common/grounds.py
ibis/common/tests/test_validators.py
ibis/common/validators.py

also make the Signature object validatable
BREAKING CHANGE: use ibis.common.validators.{Patameter, Signature} instead

refactor(common): move `Parameter` and `Signature` to validators.py

---

.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-main.yml
ibis/backends/conftest.py
ibis/tests/benchmarks/test_benchmarks.py
pyproject.toml

This PR should reduce the amount of time to merge a PR by reducing the duration
of CI runs, specifically benchmarks.
I've moved the full benchmark suite to run only after a push to master, while
still running a single iteration of each benchmark to make sure they aren't
broken. I also reduced the join size in the multiple joins benchmark because a
single iteration of it takes about 60 seconds.

ci: only run benchmarks against push to `master` branch

---

ibis/backends/base/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_client.py

Fixes a bug so that ibis.connect can be used with pyspark.

fix(pyspark): make sure `ibis.connect` works with pyspark

---

ibis/backends/clickhouse/tests/test_select.py
ibis/backends/impala/tests/test_case_exprs.py
ibis/backends/impala/tests/test_exprs.py
ibis/backends/impala/tests/test_unary_builtins.py
ibis/expr/api.py
ibis/expr/types/logical.py
ibis/tests/expr/test_value_exprs.py
ibis/tests/sql/test_non_tabular_results.py

Enable calling API functions with `_` (`ibis.expr.deferred.Deferred` instances).
Fixes #4365.

fix(api): enable calling API functions with deferred objects

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/clickhouse/compiler.py
ibis/backends/dask/execution/generic.py
ibis/backends/tests/test_api.py
ibis/tests/sql/test_select_sql.py

Our current behavior with chained limits is questionable. IMO it qualifies as a
bug even though it appears to have been intentional (see the deleted
comment):
```python
t.limit(5).limit(10)
```
is currently equivalent to
```python
t.limit(10)
```
and
```python
t.limit(10).limit(5)
```
is currently equivalent to
```python
t.limit(5)
```
Both of these behaviors are inconsistent with every other relational operation
we implement in that these chains-of-limits are sensitive to the fact that
there's a specific relational operation underneath. Instead, limits should be
"dumb" and just do whatever the user asks for.
Yes, it may be ultimately pointless to chain a limit in some cases, but we
should strive hard to not second guess the user.
This PR removes the special casing of chained limits.

fix(backend): ensure that limit chains respect inner limits

---

.pep8speaks.yml

`pep8speaks` doesn't understand some modern python constructs like `:=`, causing it to unnecessarily flag some PRs. Since we don't let it actually fail PRs or fix issues, it's just a noisy bot. Lets remove it and rely on the precommit linters instead.

ci: remove pep8speaks

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/expr/operations/relations.py
ibis/expr/operations/sortkeys.py
ibis/tests/sql/test_sqlalchemy.py

This:
- Fixes several bugs in `sort_by` mostly around handling of different ways of representing ascending/descending sort orders
- Expands the test suite to better test `sort_by`
- Loosens the restrictions on sort keys to support `sort_by(random())` for (inefficiently) selecting out a random element from a table.

feat: support `sort_by(random())`

---

ibis/backends/tests/test_numeric.py

Follow up to #4394 where I forgot to enable the other random test for pyspark
after implement support for it in the PR.

test(pyspark): enable `random` test

---

docs/api/expressions/top_level.md
ibis/backends/tests/test_set_ops.py
ibis/expr/api.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

Also makes the corresponding methods variadic.
This makes using `union` to concatenate multiple tables much more ergonomic, since you don't have to manually chain calls to `union` for every pair. For example:
```python
tables = [some_subquery(table, arg) for arg in args]
combined = ibis.union(*tables)
```
I also see value in the top level `intersect` for similar reasons, but it seems less important to me. I only included `difference` for completeness. Unlike `union` and `intersect`, `difference` operations aren't commutative - the first table has different meaning than all subsequent tables. I could see an argument against making `difference` variadic or a top-level function, no strong thoughts here.

feat: variadic union, intersect, & difference functions

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/duckdb/compiler.py
ibis/backends/pandas/client.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_client.py
ibis/common/grounds.py
ibis/expr/api.py
ibis/expr/format.py
ibis/expr/operations/relations.py
ibis/expr/rules.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR adds support for an API to work with in-memory tables: `ibis.memtable`.
`ibis.memtable` returns a `Table` expression.
The motivation is to allow use of simple in memory datasets in expressions.
`ibis.memtable` defers to pandas to for type inference which makes it suitable
for handling the case of inserting into/creating tables from various kinds of
Python objects.
1. Whatever the `pd.DataFrame` constructor supports can be passed to `memtable`.
1. `ibis.memtable` has both a `columns` argument and a `schema` argument. If
`schema` is `None`, the function performs type inference on the entire table.
1. I'm not entirely sure where the row count performance falls over.
1. When both `columns` and `schema` are `None` and the row type is not a
mapping the default naming scheme is `col{i}` …

feat(api): add `ibis.memtable` API to support in-memory table expressions

---

ibis/backends/tests/test_client.py
ibis/expr/api.py
ibis/expr/format.py

This PR fixes passing in a list of dicts to `ibis.memtable`
Previously we assumed that if `columns` was `None` that meant that the columns
couldn't have been inferred, but the DataFrame constructor handles this for us.
After this change we only generated column names if the inferred column index
type isn't `string`.
Additionally some code to format joins using their mathematical symbols snuck
in, so I removed that here. Thanks for finding this @jcrist!

fix(api): make sure column names that are already inferred are not overwritten

---

ibis/backends/dask/execution/indexing.py
ibis/backends/dask/tests/execution/test_operations.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pandas/tests/execution/test_operations.py
ibis/backends/tests/test_generic.py

This fixes a few issues with the pandas and dask `where` implementations:
- Neither implementation supported scalars for the `true` case, only the `false` case. This was most likely an oversight made difficult to see due to multiple functions being used to handle each case. We now use a single function for all cases, making the logic easier to understand.
- Neither implementation supported `None` or `str` values for `true` or `false`
- The dask implementation was _highly_ inefficient, resulting in unnecessary computation. This is now handled through dask-native mechanisms, resulting in major speedups.

fix: fix pandas & dask where implementations

---

docker-compose.yml
ibis/backends/clickhouse/registry.py
ibis/backends/tests/test_window.py

This PR enables support for window functions that behave
out of the box like the rest of the SQL world does.
Issues:
1. A few window functions appear broken entirely when an `ORDER BY` statement
is added. 
1. ~Some "working" functions cause the resulting query to return zero rows when the window function expression
is part of another expression, e.g., `rank() over () - 1`.~ Fixed upstream already, waiting on release.
1. Some window functions just don't exist upstream, `percent_rank` and `cume_dist`
Otherwise, the basic aggregates work as expected.

feat(clickhouse): enable support for working window functions

---

ibis/backends/dask/execution/selection.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/expr/analysis.py
ibis/tests/expr/test_analysis.py
ibis/tests/sql/test_compiler.py
ibis/tests/sql/test_select_sql.py

This PR addresses an issue where filtering after a projection
is incorrectly fused.
Long term, we probably don't want to keep this behavior around, and instead
limit the API to allow only lambdas, strings and deferred instances to be
passed to `select` and `filter`.
However, this behavior is defined in the current version of ibis and therefore
should be considered a bug.
The fix it to try to eagerly simplify predicates by replacing their child table
with the `Selection`'s child, and bail out if anything goes wrong during the
substitution.
If the substitution succeeds the following criteria must be true for fusion to work:
1. The simplified predicates must all derive from the incoming `Selection`'s child table.
1. None of the selection columns can be an `Unnest`. This is because `Unnest` …

fix(backends): ensure select after filter works

---

ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/dask/execution/generic.py
ibis/backends/pandas/execution/generic.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_generic.py
ibis/expr/operations/relations.py
ibis/expr/types/relations.py

Also fixes a bug where `table.dropna(subset=())` would be treated the same as `table.dropna(subset=None)` for some backends.
Fixes #3110.

feat: implement dropna for SQL backends

---

.github/workflows/ibis-tpch-queries.yml

Hopefully this fixes the failing master branch until we can figure out what is happening.

ci: constrain duckdb in tpc-queries for now

---

ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/tests/test_client.py

This PR makes SQLQueryResult aka con.sql work for SQLAlchemy backends

fix(sqlalchemy): implement `SQLQueryResult` translation

---

justfile

Adds a command to the justfile to view the changelog for the upcoming release. Helpful when trying to remember what the highlights are for an upcoming release.
```
just view-changelog
just view-changelog --pretty
```

chore: add `just view-changelog` command

---

.github/workflows/ci-data.yml

This PR uploads our CI data into a bigquery native table instead of relying on the external JSON (which will still be available). This should make querying the data faster.

ci: load data into bigquery native tables

---

ibis/backends/base/sql/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/base/sql/compiler/query_builder.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/compiler.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/compiler.py
ibis/backends/pandas/client.py
ibis/backends/pyspark/__init__.py
ibis/backends/pyspark/compiler.py
ibis/backends/tests/test_client.py
ibis/expr/api.py
ibis/expr/operations/relations.py
ibis/util.py

This PR registers in-memory tables directly to a backend where native support for it
exists in the backend.
* DuckDB, new in this PR
* PySpark, already worked
* ClickHouse, works but could be more efficient if we set `use_numpy=True` in the driver settings.

perf(sqlalchemy): register DataFrames cheaply where possible

---

.prettierignore
docs/api/expressions/top_level.md
ibis/expr/api.py
ibis/tests/expr/test_value_exprs.py

This adds some helper methods for composing multiple predicates together using boolean logic. I think these methods are useful when programmatically combining expressions, but I'm not sold on the names/variadic nature.
- Should these be called `and_`/`or_` or `all`/`any`?
- Should these be variadic or take an iterable?
I went with `and_`/`or_` and variadic for now, but happy to change if others feel strongly.
I do think it's important that these helpers work with 0 or more elements to make it easier to programmatically combine predicates - this lets the caller not worry about the 0 or 1 element case. For no predicates I went with the behavior of python's `all`/`any` methods:
- `and_()` returns `literal(True)`
- `or_()` returns `literal(False)`

feat(api): add `and_` and `or_` helpers

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

This lets you create a table automatically by passing an in-memory pandas or pyarrow table/dataset to `con.register`.
```python
In [2]: con = ibis.duckdb.connect()
In [3]: import pyarrow as pa
In [4]: table = pa.Table.from_pydict({"x": [1, 2, 3], "y": ["a", "b", "c"]})
In [5]: t = con.register(table)  # register with duckdb
In [6]: t.x.sum().execute()
Out[6]: 6
```
Fixes part of #4481.

feat(duckdb): register tables from pandas/pyarrow objects

---

docs/SUMMARY.md
docs/blog/Ibis-version-3.0.0-release.md
docs/blog/Ibis-version-3.1.0-release.md
docs/blog/ffill-and-bfill-using-ibis.md

This PR moves the blog up to the top level sidebar, underneath `Home`.

docs: move blog to sidebar; style attribution the same for all blog posts.

---

docs/api/expressions/top_level.md
ibis/common/pretty.py
ibis/expr/api.py

This PR adds a top-level `.sql` API for getting the formatted SQL string from an ibis expression.

feat(api): add `ibis.to_sql` to easily get a formatted SQL string

---

ibis/backends/dask/core.py
ibis/backends/pandas/core.py
ibis/backends/tests/test_client.py
ibis/config.py
ibis/expr/types/core.py
ibis/tests/expr/test_table.py

This PR adds DuckDB as the default backend to use for things that don't have a backend.
Right now, those things are:
1. `ops.Literal`s
2. `ops.InMemoryTable`s
This is useful for doing analysis on in-memory things without having to think too hard about
how to do it. The workflow is one call to `ibis.memtable` on the object and you're off to
the races.

feat(ux): add duckdb as the default backend

---

ci/schema/clickhouse.sql
ci/schema/duckdb.sql
ibis/backends/clickhouse/tests/conftest.py

This PR is a small test DDL cleanup to use `CREATE OR REPLACE` instead of `DROP -> CREATE` where it is supported.

test: use `CREATE OR REPLACE` where possible

---

ibis/backends/sqlite/__init__.py
ibis/backends/sqlite/tests/test_types.py

This lets ibis load `TIMESTAMP` columns containing a wider range of the string formats accepted by SQLite. This changes nothing at the SQL execution level, just when pulling results back into the Python process.
Formats 1-7 in https://sqlite.org/lang_datefunc.html#time_values are accepted, with optional timezone suffixes.
Fixes the timestamp handling part of #4505.

feat(sqlite): support wider range of datetime formats

---

docs/tutorial/02-Aggregates-Joins.ipynb

In the joining data section, the prose claims that the GDP country code corresponds to iso_alpha2, when it actually corresponds to iso_alpha3, which is reflected in the code. This PR fixes that.

docs: Correct small typo in aggregates-joins

---

ibis/expr/operations/temporal.py
ibis/expr/types/temporal.py

Previously `table.col.day_of_week` was an `Expr`. This didn't really make sense: it couldn't ever be directly computed, and only served as a namespace to store more specific methods (e.g. `col.day_of_week.full_name()`. However, having it as an expression made it easy to accidentally pass on to other expressions, leading to cryptic errors later.
This makes it not an `Expr`, removing those issues. This shouldn't be a breaking change, since any treatment of this node as an expression would have errored (just more cryptically) before.

fix: make `col.day_of_week` not an expr

---

ibis/backends/dask/tests/test_client.py
ibis/backends/pandas/tests/test_client.py
ibis/backends/tests/test_join.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py
ibis/tests/sql/test_compiler.py

This was a minor rough edge found while using `ibis`. I kept calling `drop` incorrectly since I expected it to be variadic like `select` (viewing it as the inverse of select for column subsetting).
This PR isn't a breaking change, the old calling style is deprecated in favor of a variadic call.
```python
In [2]: t = ibis.table(dict.fromkeys("abcd", "int"))
In [3]: t.select("a", "b").columns
Out[3]: ['a', 'b']
In [4]: t.drop("c", "d").columns
Out[4]: ['a', 'b']
```

feat(api): make `Table.drop` variadic

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_generic.py
ibis/common/grounds.py
ibis/common/pretty.py
ibis/config.py
ibis/expr/datatypes/core.py
ibis/expr/format.py
ibis/expr/types/analytic.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/tests/expr/mocks.py
ibis/tests/expr/test_decimal.py
ibis/tests/expr/test_interactive.py

This PR adds a new interactive repr for Table expressions using rich.

feat(ux): `rich` interactive table

---

ci/schema/duckdb.sql
ci/schema/mysql.sql
ci/schema/postgresql.sql
ci/schema/sqlite.sql
ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/alchemy/translator.py
ibis/backends/clickhouse/tests/conftest.py
ibis/backends/conftest.py
ibis/backends/dask/execution/strings.py
ibis/backends/dask/tests/conftest.py
ibis/backends/datafusion/tests/conftest.py
ibis/backends/impala/tests/conftest.py
ibis/backends/mysql/compiler.py
ibis/backends/mysql/registry.py
ibis/backends/mysql/tests/conftest.py
ibis/backends/pandas/client.py
ibis/backends/pandas/execution/constants.py
ibis/backends/pandas/execution/strings.py
ibis/backends/pandas/tests/conftest.py
ibis/backends/postgres/tests/test_json.py
ibis/backends/pyspark/compiler.py
ibis/backends/pyspark/datatypes.py
ibis/backends/pyspark/tests/conftest.py
ibis/backends/tests/base.py
ibis/backends/tests/test_json.py
ibis/expr/operations/__init__.py
ibis/expr/operations/json.py
ibis/expr/rules.py
ibis/expr/types/json.py

This PR adds the ability to extract object values or array elements of a JSON-typed column.
Notable things:
- ClickHouse support for this is experimental, and doesn't seem to work in ClickHouse itself and is also broken/unsupported in `clickhouse_driver`.
- PySpark works, but since we're not handling result conversion at all really the test fails.
- The SQLAlchemy backends basically all "just work", the main differences being how the `JSON` type is return in Python. We handle this here by trying to parse the JSON and if that fails assuming the value is already deserialized.

feat(api): add JSON getitem support

---

ibis/expr/rules.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

This PR allows arbitrary expression in sort keys. One use case is working around snowflakes requirement that a window with a frame specification has an order by key even if it is not strictly necessary. These cases will come up in the future and we should just allow any expression instead of arbitrarily restricting things.

fix(api): allow arbitrary sort keys

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_api.py
ibis/backends/tests/test_client.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py

This PR adds an implementation of `__array__` for `Column` and `Table` expressions.
There's hardly any code here, but this gives the ability to plot ibis expressions **out of the box**.
Here's an example:
which yields this plot:

feat(api): implement `__array__`

---

ibis/backends/base/__init__.py
ibis/backends/tests/test_client.py

Need to add some tests and this is less elegant, but works.
Fix #4548

fix: auto-register csv and parquet with duckdb using `ibis.connect`

---

.github/workflows/ci-data.yml

The GCS Insert workflow is currently failing due to a bigquery schema mismatch. The way the shell script is written does not allow the data to be inserted into gcs regardless of whether it can be successfully inserted into BigQuery. This PR allows for that.

ci: allow `bq load` to fail

---

ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/tests/expr/test_table.py
ibis/tests/expr/test_value_exprs.py

This fixes a small bug introduced in #4547. That PR added an `__array__` method, which lets users pass ibis columns and tables to functions expecting array-like objects, and have those implicitly work.
However, defining only `__array__` means that `numpy` will happily convert ibis types to numpy types when used in larger arithmetic expressions. We _could_ make this work by properly defining `__array_ufunc__`, but that's a bit tricky. Instead we define:
- `__array_priority__` to something higher than numpy (0) & dask priorities (11)
- `__array_ufunc__ = None` to disable the array-ufunc protocol.
Doing this means that:
- numpy scalar + ibis type works as before, no accidental computation
- numpy array + ibis type errors with a `TypeError`, rather than implicitly computing

fix: ensure numpy ops dont accidentally cast ibis types

---

ibis/backends/base/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_client.py

- feat(duckdb): overwrite views when calling `register`
- chore: return `options.default_backend` from `_default_backend`
- feat(api): return the table from `ibis.connect('foo.csv')`

feat(duckdb): make it more convenient to access files

---

ibis/expr/analysis.py
ibis/tests/expr/test_table.py

Fixes a bug where substitution occurs and triggers a correct TypeError but the TypeError is not specific enough.

fix: fix comparisons for nested types

---

ibis/expr/types/relations.py
ibis/tests/expr/test_interactive.py

By default `rich` will decrease the size of columns until they're unreadable to make all columns fit in repr. This PR attempts to fix that by adding a trailing `...` column to indicate there are more columns to the right, and truncating the number of columns displayed to only those whose column names can be completely rendered (we set `min_width=len(column_name)` for every column).
This also switches to using horizontal ellipsis (`…`) everywhere instead of vertical ellipsis. Vertical ellipsis mess with the alignment in non-terminal rendering (e.g. copy-paste the output into a code block comment in github), while horizontal ellipsis don't have this problem.
Example:
```python
In [2]: con = ibis.duckdb.connect()
In [3]: ibis.options.interactive = True
In [4]: import …
```

fix: truncate columns in repr for wide tables

---

ibis/backends/clickhouse/registry.py
ibis/backends/tests/test_generic.py

This PR fixes a bug in the clickhouse compiler leftover from The Great Refactor.

fix(clickhouse): ensure that correlated subqueries' columns can be referenced

---

.releaserc.js

This PR adds a `# Refactors` section to the release notes, at least for 4.0.0, since there are a number of important changes there that should be categorized and shown publicly for maximum visibility

chore: include refactoring in release notes

---

.envrc
.github/workflows/ibis-snowflake.yml
poetry.lock
requirements.txt

Follow up to #4568 to allow `snowsql` in `shell.nix`.

chore: allow unfree packages in nix-shell

---

.github/workflows/ibis-backends.yml

Impyla now supports python 3.10, so we can remove the special case in CI and run the impala tests with python 3.10 same as the other backends.

ci(impala): remove special casing of python version in CI

---

.github/workflows/ibis-snowflake.yml
shell.nix

This PR removes snowsql from shell.nix. There is no point in dealing with the unfree nature of it in CI since it is meant only for debugging convenience. The clickhouse cli is also removed, because it is huge and never used in CI. To use either or both you can always run `nix-shell -p snowsql -p clickhouse`, even if you are already in a nix-shell. Finally, the virtualenv caching is removed from the snowflake unit tests: since the poetry lockfile must be modified (by installing an older version of pyarrow), there is no point in caching.

ci: remove snowsql, clickhouse from shell.nix; remove venv caching in snowflake CI

---

ci/release/dry_run.sh
ci/release/prepare.sh
ci/release/publish.sh
ci/release/run.sh
ci/release/verify.sh
default.nix
dev/lockfile_diff.sh
dev/update-lock-files.sh
nix/default.nix
shell.nix

This PR should fix the failing `simulate_release` GHA job.

build: use `./nix` as the source of nixpkgs instead of `nixos-unstable`

---

ibis/backends/base/__init__.py
ibis/backends/base/sql/__init__.py
ibis/backends/datafusion/__init__.py
ibis/backends/datafusion/tests/test_udf.py
ibis/backends/duckdb/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/pyarrow/datatypes.py
ibis/backends/tests/test_export.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/util.py

Adds `to_pyarrow` and `to_pyarrow_batches` to the alchemy backends, datafusion, and pandas.  More to come.
Some open questions / issues:
Where should the schema inference stuff live?  The type mapping is already defined in the `pyarrow` backend but it feels weird to import that backend into other backends.
`chunk_size`?  `chunksize`?  `batch_size`?
In this context, are chunks / batches properly defined in terms of rows or is that a conflation?
Datafusion has some slightly wonky behavior when it comes to a consistent schema across recordbatches
DuckDB does not seem to respect their own `chunksize` argument.
xref #4443

feat: add to_pyarrow and to_pyarrow_batches

---

ibis/backends/snowflake/tests/conftest.py
ibis/backends/tests/test_export.py

Fixes failing snowflake tests.

test(snowflake): fix `test_export` and skip tests if envar isn't defined
