ibis-project/ibis

ibis/backends/duckdb/registry.py
ibis/backends/tests/test_array.py
ibis/expr/types/arrays.py

Implements array zipping for the duckdb backend.

feat(duckdb): support array zip operation

---

ibis/expr/datatypes/core.py
ibis/expr/datatypes/tests/test_core.py
ibis/expr/datatypes/tests/test_value.py
ibis/expr/operations/generic.py

Also slightly improve the test coverage for scalar value normalization.

feat(datatypes): support creating Timestamp from units

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py

Implements the new zip method for the snowflake backend.

feat(snowflake): implement array zip

---

ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/clickhouse/tests/snapshots/test_functions/test_column_regexp_extract/out.sql
ibis/backends/duckdb/registry.py
ibis/backends/pandas/execution/strings.py
ibis/backends/tests/test_string.py
ibis/expr/types/strings.py

fix(common): fix bug in `re_extract`

---

ibis/backends/datafusion/__init__.py
ibis/backends/datafusion/tests/test_register.py
ibis/backends/tests/test_export.py

feat(datafusion): register tables and datasets in datafusion

---

ibis/backends/dask/tests/execution/test_window.py

Fixes a failing dask window test cc @jreback @patcao.

test(dask): fix flaky window test

---

ibis/expr/types/groupby.py
ibis/tests/expr/test_table.py

fix(ir): raise Exception for group by with no keys

---

ibis/backends/dask/tests/execution/test_join.py

Fixes some flaky dask tests seen here: https://github.com/ibis-project/ibis/actions/runs/5082574851/jobs/9132484378?pr=6304

test(dask): fix flaky tests

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/duckdb/tests/test_datatypes.py

fix(sqlalchemy): quote struct field names

---

ibis/backends/tests/snapshots/test_string/test_rlike/bigquery/out.sql

Fixes the single failing test from BigQuery.

test(bigquery): update generated code from sqlglot update

---

ibis/backends/snowflake/tests/conftest.py

Fixes Snowflake CI hiccups due to username changes from SSO setup

ci(snowflake): fix testconf to not assume that the username equals the schema name

---

.github/renovate.json
poetry.lock
pyproject.toml

- ci(deps): auto label various dependency updates
- ci(deps): pin ruff version to avoid lumping lint updates into lock file update PRs

ci: auto label dependencies updates

---

ibis/expr/types/groupby.py

I just wrote this in the GitHub web UI so no idea if this will pass mypy

feat: add easy type hints to GroupBy

---

ibis/selectors.py

I noticed that across wasn't documented. I made an attempt at adding it. Please suggest improvements!

fix(docs): add documentation for across

---

ibis/backends/pyspark/__init__.py

Removes an unused variable in the pyspark backend.

chore(pyspark): remove unused variable

---

.github/workflows/ibis-backends-cloud.yml
ibis/backends/snowflake/tests/conftest.py
ibis/backends/snowflake/tests/test_client.py

ci: fix flaky snowflake ci jobs

---

ibis/backends/conftest.py

A typo in one of our custom marks would just lead to a test failure (usually) because a test that we expected to xfail wasn't xfailed.
This is annoying because a) it's surprising and b) you have to run possibly the whole test suite to hit it (and then you have to figure out why).
I added a collection hook to flag any typos in the arguments to our custom marks, and it spits them all out, along with path and test name, then aborts the test run altogether.
resolves #6355 
Sample output:
```
INTERNALERROR>     raise pytest.PytestCollectionWarning("\n" + "\n".join(unrecognized_backends))
INTERNALERROR> pytest.PytestCollectionWarning: 
INTERNALERROR> Unrecognize backend(s) [{'quackdb'}] passed to notimpl marker in
INTERNALERROR> /home/gil/github.com/ibis-project/ibis/ibis/backends/tests/test_tim …
```

chore(pytest): fail fast on typos in notimpl, notyet, and never marks

---

ibis/backends/base/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/tests/test_dot_sql.py

Add support for SQL dialect translation and fix upstream test failures.

feat(polars): support SQL dialect translation

---

ibis/backends/base/__init__.py

Follow up to #6006 to fix an attribute resolution order issue with the snowflake backend.

fix(snowflake): ensure that `_pandas_converter` attribute is resolved correctly

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/clickhouse/tests/snapshots/test_select/test_array_join_in_subquery/out.sql
ibis/backends/clickhouse/tests/test_select.py

fix(clickhouse): generate correct arrayJoin syntax in Contains subquery

---

ibis/expr/visualize.py

The expression rendering is broken (as shown in the picture below):
This PR fixes the expression rendering:

fix(expr): fix graphviz rendering

---

.gitignore
ibis/backends/base/sql/alchemy/registry.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/mssql/registry.py
ibis/backends/tests/test_string.py

In response to https://github.com/ibis-project/ibis/pull/5462#issuecomment-1420704815

fix(backends): fix capitalize to lowercase subsequent characters

---

ibis/backends/duckdb/registry.py

Previously these were naive timestamps in the backend (timestamp, not timestamp with timezone), and the timezone was being applied in `.execute()` as part of the expected schema being enforced. This would cause issues if chaining operations (since the type in the backend was different) or if returning through `to_pyarrow` since the result wouldn't have a timezone attached.
I'm not sure of a good way to test this with our current test setup. A test using `to_pyarrow` would show the issue, but not all backends support `to_pyarrow` yet, kinda complicating the testing path. Either way, I can confirm this patch fixes the issue.

fix(duckdb): ensure `to_timestamp` returns a UTC timestamp

---

ibis/backends/polars/__init__.py

The `_add_table` method in the polars Backend was already typed such that it appeared to be expecting to handle both types of frame, but didn't ensure eager → lazy registration - now it does ;)

feat(polars): allow seamless connection for `DataFrame` as well as `LazyFrame`

---

ibis/__init__.py
ibis/backends/base/__init__.py
ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/polars/__init__.py

Noticed one of these and did a quick search to see if we were missing any others.

docs(install): add quotes to all bracketed installs for shell compatibility

---

ibis/backends/snowflake/tests/test_udf.py

Fixes the failing upstream snowflake tests.

test(snowflake): xfail annotated map UDFs on snowflake

---

docs/api/expressions/timestamps.md
ibis/backends/base/sql/registry/main.py
ibis/backends/bigquery/registry.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/dask/execution/temporal.py
ibis/backends/impala/tests/snapshots/test_value_exprs/test_timestamp_extract_field/microsecond/out.sql
ibis/backends/impala/tests/test_value_exprs.py
ibis/backends/mssql/registry.py
ibis/backends/mysql/registry.py
ibis/backends/pandas/execution/temporal.py
ibis/backends/pandas/tests/execution/test_temporal.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/sqlite/registry.py
ibis/backends/tests/test_temporal.py
ibis/backends/trino/registry.py
ibis/expr/decompile.py
ibis/expr/operations/temporal.py
ibis/expr/types/temporal.py
ibis/tests/expr/test_timestamp.py

feat: add microsecond method to TimestampValue and TimeValue

---

ibis/backends/mssql/__init__.py

Continuing in the efforts against this heisenbug.
Previous fix didn't do the trick.  xref #6503 #6509
We noticed two failure modes:
1. the LHS is wrong (expr.execute())
2. the RHS is wrong (wrote the wrong number of rows to a file)
both of these point, at their core, to some issue with the cursor, since the mssql backend relies on a SQLAlchemy cursor for feeding both `execute` and `to_pyarrow_batches` (which itself feeds `to_parquet` and `to_csv`).
We found this:
http://www.pymssql.org/en/stable/pymssql_examples.html#important-note-about-cursors
which lets us know that we _cannot_ have multiple cursors on the same connection.
Attempting to close the cursor after the `yield` loop doesn't work.
So instead, for now, this terrible workaround.
We fetch the entire contents, then re-batch it …

fix(mssql): dont yield from inside a cursor

---

docs/SUMMARY.md
docs/blog/rendered/ibis-version-6.0.0-release.ipynb

Add a v6.0.0 release blog overviewing major breaking changes, backend improvements, and new features.

docs(blog): v6.0.0 release blog

---

docs/release_notes.md

Fixes a typo in the release notes

docs(release-notes): fix typo

---

ibis/backends/base/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/snowflake/__init__.py

Small PR to clean up some handling of pyarrow columns and empty tables.

refactor(pyarrow): clean up column and empty table handling

---

ibis/backends/druid/__init__.py
ibis/backends/druid/compiler.py
ibis/backends/druid/datatypes.py
ibis/backends/tests/test_binary.py
ibis/backends/tests/test_export.py
ibis/backends/tests/test_temporal.py

This PR fixes some conversion issues in the druid backend.

fix(druid): handle conversion issues from string, binary, and timestamp

---

ibis/backends/pyspark/__init__.py
ibis/backends/tests/test_export.py

closes #6383 
implements `read_delta` and `to_delta` for the pyspark backend
example: https://gist.github.com/lostmygithubaccount/2d2ab5f70e8afda643c600e98c3989a8

feat(pyspark): read_delta and to_delta

---

ibis/backends/base/sql/alchemy/__init__.py

Solves https://github.com/trinodb/trino-python-client/issues/385

Filter index warning in Trino dialect

---

docs/backends/oracle.md

docs(oracle): add note about old password checks in oracle

---

ibis/backends/trino/datatypes.py
ibis/backends/trino/tests/test_datatypes.py
ibis/common/parsing.py

This PR fixes data type parsing issues coming from the trino backend, seen in https://github.com/ibis-project/ibis/discussions/6542.

fix(trino): handle all remaining common datatype parsing

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/base/sql/compiler/select_builder.py
ibis/backends/polars/__init__.py
ibis/backends/polars/compiler.py
ibis/expr/analysis.py
ibis/expr/decompile.py
ibis/expr/types/generic.py
ibis/tests/expr/test_analysis.py

Most of the test suites do work, haven't checked impala yet. 
Apparently we no longer need the cross join, possibly due to recent changes.

refactor(analysis): remove `ScalarAggregate`, `reduction_to_aggregation` and `has_multiple_bases`

---

.git-blame-ignore-revs

Update commit for git ignore revs

chore: update `black` style update commit in git ignore revs

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_string.py

This PR adds the following functions to the DataFusion backend 😄 :
- fragment
- protocol
- authority
- host
- userinfo
- query

feat(datafusion): add extract url fields functions

---

ibis/expr/types/relations.py

Adds an example of mixing SQL strings with ibis expressions to the `.sql` method docstring

docs(dot-sql): add examples of mixing ibis expressions and SQL strings

---

ibis/backends/postgres/tests/test_client.py

test(postgres): add test demonstrating postgres CTEs with INSERT

---

ibis/expr/types/arrays.py
ibis/expr/types/generic.py
ibis/expr/types/json.py
ibis/expr/types/maps.py
ibis/expr/types/strings.py
ibis/expr/types/structs.py
ibis/tests/expr/test_operations.py

chore(error-reporting): add more thorough information about slicing a non-sliceable column

---

docs/backends/bigquery.md
docs/backends/clickhouse.md
docs/backends/dask.md
docs/backends/datafusion.md
docs/backends/druid.md
docs/backends/duckdb.md
docs/backends/impala.md
docs/backends/memtable-template.md
docs/backends/mssql.md
docs/backends/mysql.md
docs/backends/oracle.md
docs/backends/pandas.md
docs/backends/polars.md
docs/backends/postgresql.md
docs/backends/pyspark.md
docs/backends/snowflake.md
docs/backends/sqlite.md
docs/backends/template.md
docs/backends/trino.md
mkdocs.yml

docs(backends): document memtable support and performance for each backend

---

docker-compose.yml
docker/mysql/startup.sql
ibis/backends/base/__init__.py
ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/conftest.py
ibis/backends/datafusion/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/pandas/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/tests/test_api.py
ibis/backends/tests/test_client.py
ibis/backends/trino/__init__.py

Adds support for databases and schema creation and listing.
Closes #6331.

feat(ddl): support `create_schema` and implement `create_database` as an abstract base class

---

ibis/backends/duckdb/__init__.py
ibis/backends/tests/test_client.py

fix(duckdb): deduplicate the output of `list_schemas()`

---

ibis/common/patterns.py
ibis/common/tests/test_patterns.py

refactor(common): ibis.common.patterns.match() should return with the matched value rather than the context

---

ibis/backends/snowflake/__init__.py

Fixes the failing tests on `master`.

test(snowflake): specify the current database and schema when creating a temp stage in snowflake

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/test_client.py

Fixes an issue where creating a schema or database automatically activates them, causing test failures that depended on the order in which `test_create_schema` ran relative to other tests.

fix(snowflake): reset the schema and database to the original schema after creating them

---

ibis/backends/snowflake/__init__.py

We need to also reset to the original schema, not just the database

fix(snowflake): reset to original schema when resetting the database

---

docs/blog/rendered/ibis-version-6.1.0-release.ipynb

docs: minor blog fixes/prose update

---

docs/blog/rendered/ibis-version-6.1.0-release.ipynb

per https://twitter.com/jonmmease/status/1687474948342718464?s=20 and quick internal discussion, slightly reword the visualization computation pushdown statement

docs: minor blog update

---

ibis/backends/postgres/registry.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py

Implement array sort for postgres and snowflake.

feat(postgres, snowflake): implement `ArrayValue.sort`

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py

Enable `ArrayValue.remove` which is now implemented upstream.

feat(snowflake): add `ArrayRemove` implementation

---

ibis/backends/snowflake/__init__.py

This PR removes unnecessary schema setting code in the snowflake backend. Originally this code was used ensure that table metadata was pulled from the schema specified, but now it appears this code is no longer necessary.

refactor(snowflake): remove unnecessary schema setting

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_array.py

Add support for array repeat API.

feat(snowflake): implement `ops.ArrayRepeat`

---

ibis/backends/postgres/registry.py
ibis/backends/tests/test_array.py

Implement array remove, unique, position, map and filter for postgres.

feat(postgres): implement remaining array functions

---

ibis/backends/bigquery/compiler.py
ibis/backends/bigquery/registry.py
ibis/backends/tests/test_array.py

Add array function support to BigQuery.

feat(bigquery): implement array functions

---

ibis/backends/tests/test_array.py

Fixes array unique tests to accommodate clickhouse and bigquery null handling

test(bigquery): fix array unique test to accommodate bigquery null handling

---

ibis/backends/tests/snapshots/test_sql/test_isin_bug/bigquery/out.sql
ibis/backends/tests/snapshots/test_sql/test_isin_bug/snowflake/out.sql
ibis/backends/tests/test_map.py

This PR fixes a couple small failing tests for BigQuery and Snowflake.

test(cloud-backends): fix failing tests

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_generic.py
ibis/expr/types/generic.py

This PR adds to DataFusion the following functions:
- coalesce
- nullif
- ifnull
- zeroifnull

Add coalesce, nullif, ifnull, zeroifnull

---

docker/trino/catalog/hive.properties
ibis/backends/trino/tests/test_client.py

This PR adds a test for overwriting hive tables in trino.

test(trino): test hive table overwrite

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_join.py

This PR adds join support to the DataFusion Backend.

feat(datafusion): add join support

---

ibis/expr/tests/test_visualize.py
ibis/tests/expr/conftest.py
ibis/tests/expr/test_interactive.py

refactor(tests): move `test_visualize.py` to `ibis/expr/tests`

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/tests/snapshots/test_select/test_complex_array_expr_projection/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_isin_notin_in_select/out1.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_isin_notin_in_select/out2.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_isnull_case_expr_rewrite_failure/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_join_self_reference/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_physical_table_reference_translate/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_self_reference_simple/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-any_inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-any_left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-awardID-left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-any_inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-any_left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-inner_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_joins/playerID-playerID-left_join/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_simple_scalar_aggregates/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_table_column_unbox/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_timestamp_extract_field/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_where_simple_comparisons/out.sql
ibis/backends/clickhouse/tests/snapshots/test_select/test_where_with_between/out.sql
ibis/backends/clickhouse/tests/test_client.py
ibis/backends/tests/test_client.py

Add support for temp tables and `cache` for clickhouse

feat(clickhouse): support temporary tables and caching

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/test_client.py

Add `read_json` support to the snowflake backend. Closes #6849.

feat(snowflake): implement `read_json`

---

ibis/backends/snowflake/__init__.py

Executes one less query when reading in a CSV file to snowflake.

chore(snowflake): skip extra ddl step in snowflake read csv

---

ibis/tests/benchmarks/test_benchmarks.py

Adds a benchmark using the code from #6874.

test(benchmarks): add `to_pyarrow` benchmark for duckdb

---

ibis/backends/snowflake/__init__.py

Delete a bunch of code for uploading memtables to snowflake that is redundant with `read_parquet`, depends on #6858.

refactor(snowflake): replace custom temp table ddl for memtables with `read_parquet`

---

ibis/backends/snowflake/__init__.py

Allow disabling object UDFs when connecting to the snowflake backend. Closes #6654.

feat(snowflake): allow disabling creation of object UDFs

---

ibis/common/annotations.py
ibis/common/bases.py
ibis/common/grounds.py
ibis/common/patterns.py
ibis/common/tests/test_annotations.py
ibis/common/tests/test_grounds.py
ibis/common/tests/test_grounds_benchmarks.py
ibis/expr/datatypes/core.py
ibis/expr/operations/analytic.py
ibis/expr/operations/arrays.py
ibis/expr/operations/generic.py
ibis/expr/operations/histograms.py
ibis/expr/operations/logical.py
ibis/expr/operations/maps.py
ibis/expr/operations/numeric.py
ibis/expr/operations/reductions.py
ibis/expr/operations/relations.py
ibis/expr/operations/strings.py
ibis/expr/operations/structs.py
ibis/expr/operations/temporal.py
ibis/expr/operations/udf.py
ibis/expr/rules.py
ibis/expr/schema.py
ibis/selectors.py

depends on https://github.com/ibis-project/ibis/pull/6900
Preparing for a follow-up to provide more error context for the validation errors.

refactor(common): turn annotations into slotted classes

---

ibis/expr/types/relations.py
ibis/tests/expr/test_table.py

fix(drop): support deferred objects in calls to drop

---

ibis/backends/datafusion/compiler.py
ibis/backends/tests/test_temporal.py

This PR adds the following functions:
- ExtractWeekOfYear
- ExtractMicrosecond
- ExtractEpochSeconds
- ~~Strftime~~
It also fixes a minor typo.

feat(datafusion): add temporal functions

---

ibis/backends/tests/test_aggregation.py

Enable xpassing quantile tests for the clickhouse backend

test(clickhouse): enable xpassing quantile tests

---

ibis/backends/base/sql/alchemy/registry.py
ibis/backends/pyspark/compiler.py
ibis/common/numeric.py
ibis/common/tests/test_numeric.py
ibis/expr/datatypes/tests/test_value.py
ibis/expr/datatypes/value.py
ibis/tests/expr/test_literal.py
ibis/tests/expr/test_value_exprs.py

Should resolve https://github.com/ibis-project/ibis/issues/6899

fix(datatypes): decimal normalization failed for integers

---

ibis/backends/tests/test_numeric.py

Fixes two failing decimal-related tests for the Snowflake backend.

test(snowflake): fix decimal comparison tests

---

.github/workflows/ibis-docs-lint.yml

This PR adds netlify deploy previews to our CI, for pull requests only

ci(docs): netlify deploy previews

---

docs/_code/input_output_penguins.qmd
docs/_quarto.yml
docs/backends/bigquery.qmd
docs/backends/sqlite.qmd
docs/concepts/internals.qmd
docs/index.qmd
docs/posts/v6.1.0-release/index.qmd
docs/support_matrix.qmd

A bunch of small docs fixes noticed during our daily triage meeting

docs: a bunch of small fixes

---

docs/backends/bigquery.qmd
docs/backends/clickhouse.qmd
docs/backends/dask.qmd
docs/backends/datafusion.qmd
docs/backends/druid.qmd
docs/backends/duckdb.qmd
docs/backends/mssql.qmd
docs/backends/mysql.qmd
docs/backends/oracle.qmd
docs/backends/pandas.qmd
docs/backends/polars.qmd
docs/backends/postgresql.qmd
docs/backends/pyspark.qmd
docs/backends/snowflake.qmd
docs/backends/sqlite.qmd
docs/backends/trino.qmd

This PR adds links to all the products or projects that underlie each backend.

chore: add product links to the various backends

---

docs/backends/bigquery.qmd
docs/backends/clickhouse.qmd
docs/backends/dask.qmd
docs/backends/datafusion.qmd
docs/backends/druid.qmd
docs/backends/duckdb.qmd
docs/backends/impala.qmd
docs/backends/mssql.qmd
docs/backends/mysql.qmd
docs/backends/oracle.qmd
docs/backends/pandas.qmd
docs/backends/polars.qmd
docs/backends/postgresql.qmd
docs/backends/pyspark.qmd
docs/backends/snowflake.qmd
docs/backends/sqlite.qmd
docs/backends/trino.qmd

This PR fixes product links. Links in the title render drop down links as the title link and not the page link.

chore: fix product links

---

.github/ISSUE_TEMPLATE/docs-issue.yml

This PR adds an issue template for documentation-related issues.

chore: add documentation issue template

---

docs/_quarto.yml

Makes the API docs pages title case match other pages

chore: make case consistent

---

docs/_quarto.yml
docs/tutorials/ibis-for-sql-users.qmd

This PR reformats and cleans up a few small bits of the ibis-for-sql-users tutorial.

chore: clean up ibis-for-sql-users

---

docs/_quarto.yml

put the ones w/ arrow things next to each other, and contribute next to the GH options that are also generally contributing
also pad my GH stats

docs: swap release notes and contribute in navbar

---

docs/_quarto.yml

add docs issue to GH navbar
pad my GH stats

docs: add docs issue to navbar

---

ibis/backends/duckdb/__init__.py
ibis/backends/impala/client.py
ibis/expr/api.py
ibis/expr/operations/logical.py
ibis/expr/types/core.py
ibis/selectors.py

This PR cleans up and starts running more examples as doctests.

docs: clean up and run more examples

---

docs/_quarto.yml
docs/styles.css

Love the smell of fresh CSS in the afternoon.

chore: add custom css for scrolling connection parameters when type names are long

---

ibis/backends/flink/__init__.py
ibis/backends/flink/ddl.py
ibis/backends/flink/tests/conftest.py
ibis/backends/flink/tests/test_ddl.py
ibis/backends/pyspark/__init__.py

Implements table-related ddl in Flink backend to support streaming connectors.

feat(flink): implement table-related ddl in Flink backend to support streaming connectors

---

docs/_quarto.yml

Fixes rendering of API docs for @lostmygithubaccount.

chore: ensure the full module path

---

docs/404.qmd

docs: add 404 page

---

docs/_quarto.yml
docs/how-to/extending/elementwise.qmd
docs/how-to/extending/reduction.qmd

these look fine to me, just missed in the `_quarto.yml`
closes #7074

docs: add exending how-to guides

---

ibis/backends/pyspark/datatypes.py

Finish fixing #7060 
I missed the additional usage of `DayTimeIntervalType` in the `pyspark.datatypes` module but that's also gated now
```python
[ins] In [1]: import pyspark
[ins] In [2]: pyspark.__version__
Out[2]: '3.2.0'
[ins] In [3]: from ibis.backends.pyspark.datatypes import type_to_sql_string
[ins] In [4]: 
```
We should probably be testing on PySpark 3.2 if we want to maintain it as a supported version.

fix(pyspark): gate other usage of DayTimeIntervalType for PySpark 3.2

---

docs/backends/impala.qmd

docs: remove old S3 comment in impala docs

---

docs/release_notes.md

docs: add 6.2.0 release notes

---

ibis/backends/duckdb/tests/test_client.py

This fixes issues with the new duckdb extension loading tests running in parallel (see https://github.com/ibis-project/ibis/actions/runs/6123415956/job/16621516374?pr=7099#step:18:93 for an example).

test(duckdb): fix extension loading tests to support parallel execution

---

ibis/expr/format.py
ibis/expr/tests/snapshots/test_format/test_format_table_with_empty_schema/repr.txt
ibis/expr/tests/test_format.py

fix(format): support rendering empty schemas

---

docs/backends/bigquery.qmd
docs/backends/clickhouse.qmd
docs/backends/dask.qmd
docs/backends/datafusion.qmd
docs/backends/druid.qmd
docs/backends/duckdb.qmd
docs/backends/impala.qmd
docs/backends/mssql.qmd
docs/backends/mysql.qmd
docs/backends/oracle.qmd
docs/backends/pandas.qmd
docs/backends/polars.qmd
docs/backends/postgresql.qmd
docs/backends/pyspark.qmd
docs/backends/snowflake.qmd
docs/backends/sqlite.qmd
docs/backends/trino.qmd

Fixes the style for installing setuptools extras for each backend.

docs: fix setuptools extra install style

---

docs/_quarto.yml
ibis/backends/base/__init__.py

Add top-level `ibis.connect` to API docs

docs: add `ibis.connect` to `top_level` API docs

---

ibis/common/patterns.py
ibis/common/tests/test_patterns.py

Small improvement to support optional keyword arguments with a default value: need to distinguish between optional and required positional/positional_or_keyword arguments to support optional positional or keyword arguments.

fix(patterns): support optional keyword arguments in CallableWith

---

docs/index.qmd

Add back the goatcounter script to the website

docs: add back goatcounter to website

---

ibis/expr/types/arrays.py

Adds an example of `functools.partial` and a lambda with a closure to each of `ArrayValue.map` and `ArrayValue.filter`

docs: add `functools.partial` and lambda closures to `ArrayValue.map` and `ArrayValue.filter`

---

docs/_quarto.yml
docs/_renderer.py
ibis/expr/operations/udf.py

Adds API documentation for existing scalar UDF APIs.

docs: add UDF API documentation

---

ibis/backends/flink/__init__.py
ibis/backends/flink/ddl.py
ibis/backends/flink/tests/test_ddl.py
ibis/backends/flink/tests/test_literals.py
ibis/backends/flink/utils.py
ibis/expr/api.py
ibis/expr/streaming.py

Introduce watermarks in Ibis API and implements `CREATE TABLE` DDL with optional watermark strategy definition in Flink backend.

feat: introduce watermarks in ibis api

---

docs/how-to/visualization/altair.qmd
docs/index.qmd

We weren't showing off all the features of altair and giving it justice.

docs: add interactivity to altair example

---

gen_redirects.py

docs: more redirects and add ibis 3.0.2

---

ibis/backends/polars/compiler.py
ibis/backends/polars/tests/test_udf.py
ibis/backends/tests/test_udf.py

Adds support for the new scalar UDF API to the polars backend.

feat(polars): implement new UDF API

---

docs/contribute/01_environment.qmd

Update the poetry version in env setup instructions.

docs: update `poetry` version

---

docs/how-to.qmd
docs/how-to/extending/sql.qmd

Add how-to for working with raw SQL.
Closes #7145.

docs: add how-to for working with raw sql strings

---

docs/_quarto.yml
docs/index.qmd

update links in docs from gitter to zulip

docs: gitter -> zulip

---

.github/workflows/ibis-backends-cloud.yml

Add a cloud backend job to test nanoarrow with snowflake

ci(snowflake): run nanoarrow ci job

---

README.md

Add a badge that links to our zulip chat to the README

docs: link to zulip in `README.md`

---

docs/contribute/01_environment.qmd

Benefits of a new laptop, running through setup instructions and finding the missing bits.

docs(nix): add configuration notes to nix environment setup

---

ibis/backends/flink/compiler/core.py

This enables `ibis/backends/tests/test_generic.py::test_memtable_bool_column` and `ibis/backends/tests/test_generic.py::test_memtable_construct` to pass. It's loosely based on something implemented on a private work previously.

fix(flink): implement an in-memory table formatter

---

ibis/backends/flink/tests/conftest.py

* Changes the `TestConf` to batch mode by default, to be used by the common backend tests. 
* Adds `TestConfForStreamingMode`.

feat(flink): add batch and streaming mode test fixtures for Flink backend

---

ibis/common/patterns.py
ibis/common/tests/test_patterns.py

Reverts ibis-project/ibis#7218.
This seems to break some pattern usage in #7209 around empty tuples.

revert: feat(patterns): support building sequences in replacement patterns

---

ibis/backends/bigquery/compiler.py
ibis/backends/bigquery/datatypes.py
ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_compile_in_memory_table/out.sql
ibis/backends/bigquery/tests/unit/test_compiler.py

fix(bigquery): escape memtable field names

---

ibis/backends/base/sqlglot/__init__.py
ibis/backends/clickhouse/compiler/core.py
ibis/backends/clickhouse/compiler/relations.py
ibis/backends/clickhouse/compiler/values.py
ibis/backends/clickhouse/tests/snapshots/test_functions/test_string_column_like/out2.sql

This PR contains a few follow-ups from the recent clickhouse compiler refactor.

refactor(clickhouse): compiler cleanups

---

ibis/backends/flink/__init__.py
ibis/backends/flink/ddl.py
ibis/backends/flink/tests/test_ddl.py
ibis/backends/tests/base.py

Implement INSERT DML in Flink backend.

feat(flink): implement insert dml

---

docs/backends/impala.qmd

Document the status of the impala backend

docs: set expectations for the impala backend

---

ibis/backends/bigquery/client.py
ibis/backends/duckdb/__init__.py
ibis/expr/api.py
ibis/expr/types/relations.py
ibis/expr/types/temporal.py

Remove usage of underscore in docstrings and doctests

docs: remove underscores that are not deferreds in doctest

---

ibis/backends/base/sqlglot/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/compiler/values.py

Add a few more sqlglot conveniences for codegen and default to the MergeTree engine for file reading.

refactor(clickhouse): use more sqlglot constructs

---

ibis/backends/duckdb/__init__.py

The sqlalchemy queries sent to duckdb for metadata seem to avoid taking into
account the current database and schema when using MotherDuck. This PR
addresses that by implementing our own metadata query for listing tables, based
on `information_schema.tables`.
Fixes #7290.

fix(duckdb): query table list directly instead of relying on sqlalchemy

---

ibis/expr/types/generic.py
ibis/expr/types/relations.py

The crusade continues!
I appreciate your help reviewing these. The docs are really starting to look quite awesome and useful and I am PSYCHED about that.

docs: misc improvements

---

ibis/common/bases.py
ibis/common/tests/test_bases.py

It also add unit tests for those two base classes.

feat(common): make `Slotted` and `FrozenSlotted` pickleable

---

ibis/backends/clickhouse/__init__.py
ibis/backends/clickhouse/tests/test_client.py

Move string munging in clickhouse create_table to sqlglot expressions.

refactor(clickhouse): use sqlglot for `create_table` implementation

---

ibis/backends/dask/tests/execution/test_window.py
ibis/common/graph.py
ibis/common/tests/test_graph_benchmarks.py
ibis/expr/analysis.py
ibis/expr/types/groupby.py
ibis/tests/sql/test_select_sql.py

I have hacked a stop condition to the graph abstraction which I need to clean up first.
I also need to figure out both a proper API and implementation for controlling the traversals (currently `stop` limits the traversal and builds up a subgraph). 
depends on #7330

refactor(analysis): vastly simplify windowize_function

---

ibis/backends/base/sql/registry/window.py
ibis/backends/flink/registry.py
ibis/backends/impala/tests/snapshots/test_analytic_functions/test_analytic_exprs/ntile/out.sql
ibis/backends/mysql/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_window.py
ibis/backends/trino/registry.py

Add support for `ntile` across most of our SQL backends

feat(backends): add `ntile` support

---

ibis/expr/datatypes/core.py
ibis/expr/datatypes/tests/test_cast.py
ibis/expr/datatypes/tests/test_core.py

followup to #7332. A bug was sneaking through before :)

fix: uint upper bounds

---

ibis/backends/oracle/__init__.py

fix(oracle): disable if_exists for Oracle drop view command

---

ibis/backends/clickhouse/compiler/core.py
ibis/backends/clickhouse/compiler/values.py

Use a pattern for repetitive transformations like nullifying strings and subtracting one from more one-based indexed operations

refactor(clickhouse): apply repetitive transformations as pattern replacements

---

ibis/backends/flink/registry.py

Part of the effort to make the common unit tests work for `flink` backend.
This PR adds new operators in `ibis/backends/flink/registry.py` to make the tests in `ibis/ibis/backends/tests/test_temporal.py` work with `pytest -m flink ...`.

feat(flink): add temporal operators

---

docs/backends/trino.qmd

docs(trino): add note about SSO configuration

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_client.py

This PR fixes cross-database/schema access for DuckDB.

fix(duckdb): ensure proper quoting when compiling cross database/schema tables

---

ibis/backends/flink/registry.py

* This is a follow-up to this [previously merged PR](https://github.com/ibis-project/ibis/pull/7265).
* Contains the remaining changes in `ibis/ibis/backends/flink/registry.py` to pass/skip the common tests for Flink backend.
* Next step is the [PR](https://github.com/ibis-project/ibis/pull/7366) that contains changes in the common tests to make them pass/skip for Flink backend.

feat(flink): add remaining operators for Flink to pass/skip the common tests

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py

Just to get `master` back to green.

fix(snowflake/bigquery): small adjustments fix listing tables

---

ibis/backends/snowflake/registry.py
ibis/backends/tests/test_temporal.py

This was failing on `master` so I decided to implement it.

feat(snowflake): support timestamp bucketing

---

ibis/backends/tests/tpch/conftest.py
ibis/backends/trino/tests/conftest.py

test(trino): use `tpch.tiny` for faster testing of tpch queries

---

.github/workflows/ibis-backends.yml
ibis/backends/conftest.py
poetry.lock
pyproject.toml

Pin PySpark to a known working upper bound

fix(deps): pin pyspark to a working version

---

ibis/backends/sqlite/registry.py
ibis/backends/tests/test_temporal.py

fix(sqlite): truncate week to previous week not following

---

ibis/backends/duckdb/__init__.py

This is apparently needed for (at least) Motherduck upgrades.

feat(duckdb): expose option to force reinstall extension

---

ibis/expr/types/relations.py

docs: improve join() docstring

---

ibis/backends/oracle/__init__.py

fix(oracle): change filter inside select into case when

---

ibis/backends/oracle/__init__.py

feat(oracle): change parsing of Oracle NUMBER data type

---

docs/contribute/01_environment.qmd

docs(contribute): fix path to conda-lock files for contributors

---

ibis/backends/base/sql/alchemy/datatypes.py
ibis/backends/sqlite/tests/test_types.py

Fixes #7496
Thanks @oneextrafact for reporting this. 
cc: @gforsyth (thanks for the help)

fix(sqlite): handle BLOB datatype

---

ibis/backends/datafusion/compiler/values.py
ibis/backends/datafusion/tests/test_string.py
ibis/backends/tests/test_string.py

This PR also fixes negative indices for `substr`

feat(datafusion): add StringLength, FindInSet, ArrayStringJoin

---

.github/workflows/ibis-backends.yml
.github/workflows/ibis-docs-lint.yml
.github/workflows/ibis-main.yml

Trying this out to see if it fixes the failure popping up on the mssql builds

ci(mssql/apt): update before trying to install from apt

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_client.py

Adds a dict-like passthrough object for setting options in the DuckDB backend.
The repr will show all values as stringified, but this is also how they'll be passed in.
This avoids users having to pass in options via calls to `raw_sql` or similar.
```python
[ins] In [1]: import ibis
[ins] In [2]: penguins = ibis.examples.penguins.fetch()
[ins] In [3]: con = ibis.get_backend(penguins)
[ins] In [4]: con.settings["null_order"] = "nulls_first"
[ins] In [5]: ibis.options.interactive = True
[ins] In [6]: penguins
Out[6]: 
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━┓
┃ species ┃ island    ┃ bill_length_mm ┃ bill_depth_mm ┃ flipper_length_mm ┃ body_mass_g ┃ … ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━ …
```

feat(duckdb): add dict-like for DuckDB settings

---

pyproject.toml

Offhand saw a few [PyPI classifiers](https://pypi.org/classifiers/) that look relevant to ibis, so I added them.

chore(build): add more project classifiers

---

ibis/backends/pandas/__init__.py

There's a pandas drop-in replacement from the Rapids team: https://rapids.ai/cudf-pandas/
This mostly works with Ibis, but our recent change to rendering the repr with `pyarrow` is failing because something in the cudf version adds an additional `index` column.
We don't know to expect this column, and asking `convert_table` to apply a schema with 5 columns to a table with 6 columns causes problems.
This is a hack, but maybe that's enough for now.

fix(pandas): drop `__index_level_N__` cols before applying schema

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/system/test_client.py

Fixes a few failing tests in the BigQuery backend for the 8.x.x branch.

test(bigquery): fix failing non-warning tests

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/converter.py
ibis/backends/snowflake/tests/test_client.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/formats/pyarrow.py

Redux of #7562 due to my accidental force push.

fix(snowflake): fix array printing by using a pyarrow extension type

---

docs/contribute/01_environment.qmd
docs/contribute/03_style.qmd

Update based on this zulip discussion: https://ibis-project.zulipchat.com/#narrow/stream/405274-environment-setup/topic/pre-commit.20hooks/near/399308596

Chore: Update docs contributing guidelines 

---

ibis/backends/tests/test_generic.py
ibis/backends/tests/test_string.py
ibis/expr/types/generic.py
ibis/tests/expr/test_value_exprs.py

feat(substitute): allow `None` keys in input mapping

---

ibis/backends/duckdb/tests/test_register.py
ibis/expr/types/pretty.py
ibis/formats/pyarrow.py

Pretty print geospatial columns

fix(geospatial): pretty print data in interactive mode

---

.github/workflows/docs-preview-dispatch.yml
.github/workflows/preview-command.yml

This PR adds support for documentation previews by writing `/preview` as a PR comment.

ci: documentation previews

---

.github/workflows/docs-preview-dispatch.yml
.github/workflows/preview-command.yml

Try out some fixes for docs previews.

ci: docs preview fixes

---

ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_unnest/out_one_unnest.sql
ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_unnest/out_two_unnests.sql
ibis/backends/tests/snapshots/test_sql/test_union_aliasing/bigquery/out.sql

Fixes some newly quoted things from the sqlglot upgrade

ci(bigquery): fix quoting

---

ibis/backends/duckdb/tests/test_register.py

Fixes the spatial extension installation setup during testing; windows does not support downloading extensions in parallel to the same location

test(duckdb): fix flaky extension installation test for windows

---

ibis/backends/tests/test_generic.py
ibis/expr/api.py

Previously, the `pandas` memtable constructor was performing two tasks
inconsistently, one was to subselect columns out of the provided
dataframe, the other was to rename those columns.
This led to some weird behavior where a mismatch in provided names could
lead to a dataframe consisting of NaNs.
Now, `columns` can only be provided to rename existing columns and there
is no subselection behavior.  If the length of the `columns` iterable
does not match the number of columns in the provided data, we error.

fix(memtable): ensure column names match provided data

---

ibis/backends/base/sql/alchemy/__init__.py
ibis/backends/base/sql/alchemy/query_builder.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/test_client.py

fix db\schema quoting issue in snowflake in accordance to this comment
https://github.com/ibis-project/ibis/pull/7652#discussion_r1413864963

fix(snowflake): database identifier quoting

---

flake.lock

Brings in the fix from https://github.com/nix-community/poetry2nix/pull/1462.

chore(deps): bump poetry2nix

---

ibis/backends/datafusion/compiler/relations.py
ibis/backends/tests/test_aggregation.py

This PR works around an issue in DataFusion where computed grouping keys in a `GROUP BY` with at least one `COUNT(DISTINCT ...)` aggregation are not executable due to what appears to be a bug in DataFusion.
The workaround is to replace the computed grouping keys with a projection of the computed keys and the usual subsequent group by.

fix(datafusion): support computed group by when the aggregation is count distinct

---

ibis/backends/flink/ddl.py
ibis/backends/flink/registry.py
ibis/backends/flink/tests/conftest.py
ibis/backends/tests/test_struct.py
ibis/backends/tests/test_timecontext.py

Implement support for nested schema (`ROW`).

feat(flink): implement nested schema support

---

.github/workflows/docs-preview.yml

Restrict who can run docs previews by using labels.

ci: use labels to restrict who can run docs-previews

---

docs/backends/_templates/api.qmd

docs(backends): include docs for inherited members

---

ibis/backends/duckdb/registry.py

Remove translation rules that are no longer used after we bumped the lower bound of duckdb to a version that natively supports all these operations.

chore: remove unused translation rules in duckdb

---

ibis/common/graph.py
ibis/common/tests/test_graph.py

Also clean up the docstrings and reuse typehints.
depends on #7759

refactor(common): consolidate the finder and replacer inputs for the various graph methods

---

ibis/backends/tests/test_array.py

Add a test for #7679, which was addressed by #7741.
Closes #7679.

test(array): add test for #7679

---

ibis/backends/duckdb/registry.py
ibis/backends/duckdb/tests/conftest.py
ibis/backends/duckdb/tests/test_geospatial.py
ibis/expr/operations/geospatial.py
ibis/expr/types/geospatial.py

- Closes #7716
@gforsyth ~~I have this so far, it's definitely broken. Trying to figure out how to make it work, I think this is a problem with the types but not super clear, any pointers would be helpful.~~
~~I added a test to make it easier to try things.~~

feat(geospatial): add support for GeoTransform on duckdb

---

ibis/backends/clickhouse/compiler/values.py
ibis/backends/datafusion/compiler/values.py
ibis/backends/datafusion/udfs.py
ibis/backends/duckdb/registry.py
ibis/backends/polars/compiler.py
ibis/backends/postgres/registry.py
ibis/backends/pyspark/compiler.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/registry.py
ibis/backends/tests/test_string.py
ibis/backends/trino/registry.py
ibis/expr/operations/strings.py
ibis/expr/types/strings.py

feat: add support for splitting a string using a regular expression

---

ibis/backends/base/sql/registry/helpers.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_temporal.py

Add rudimentary date support to Impala. Closes #7827.

feat(impala): rudimentary date support

---

.github/PULL_REQUEST_TEMPLATE.md

Add a PR template for contributors

docs(contrib): add pull request template

---

SECURITY.md

docs(security): add a security policy

---

ibis/backends/flink/tests/test_ddl.py
ibis/backends/tests/errors.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_array.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_dot_sql.py
ibis/backends/tests/test_export.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_join.py
ibis/backends/tests/test_network.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_set_ops.py
ibis/backends/tests/test_string.py
ibis/backends/tests/test_temporal.py
ibis/backends/tests/test_timecontext.py
ibis/backends/tests/test_window.py

Consolidate all the backend errors under a single file.

test: consolidate backend errors in a single file

---

docs/posts/zulip/index.qmd

add a simple post on the move to Zulip chat
closes #7888

docs: add post about move to Zulip chat

---

docs/concepts/who.qmd

reading the doc back, making some very minor edits
n/a

docs: minor edit to the who supports ibis doc

---

ibis/backends/flink/__init__.py
ibis/backends/flink/ddl.py
ibis/backends/flink/tests/test_ddl.py

Reviving https://github.com/ibis-project/ibis/pull/7800 which got closed after switching to `main`.

feat(flink): add primary key support

---

docs/_quarto.yml

docs: add ibis.join() to docs

---

docs/concepts/user-testimonials.qmd

add a user testimonials page. three recent examples, we can add more
closes #7341

docs: add user testimonials page

---

docs/concepts/composable-ecosystem.qmd

low-level protocol -> API per https://github.com/ibis-project/ibis/pull/7898#discussion_r1445111841
n/a

docs: minor update to composable data ecosystem concept

---

ibis/backends/duckdb/registry.py
ibis/backends/duckdb/tests/test_geospatial.py
ibis/expr/operations/geospatial.py
ibis/expr/types/geospatial.py

- Extend api to support ST_FlipCoordinates
- Clarify convert (equivalent of st_transform) docs to mention it that coordinates are expected as XY (longitude/latitude)
Closes #7835

feat(duckdb-geospatial): add support for flipping coordinates

---

docs/_tabsets/install.qmd

Added exasol backend to list of supported backends in install "tabset".

docs: add exasol to list of supported backends

---

ibis/expr/datatypes/tests/test_parse.py

Minor issue I found while looking at examples of string specification for datatypes.

test(datatypes): update test to test double quotes

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/test_client.py

Implements the `insert` method for snowflake. Closes #7955.

feat(snowflake): implement insert method

---

ibis/backends/snowflake/__init__.py

fix(snowflake): insert into the correct object

---

ibis/backends/tests/test_generic.py

Cleans up the try_cast tests that return null

test(backends): make null results try_cast test agnostic to nan vs None

---

.github/workflows/ibis-backends.yml
ibis/backends/conftest.py
ibis/backends/pyspark/converter.py
ibis/backends/pyspark/datatypes.py
ibis/backends/pyspark/tests/test_basic.py
ibis/backends/tests/errors.py
ibis/backends/tests/test_export.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_numeric.py
ibis/backends/tests/test_register.py
poetry.lock
pyproject.toml

feat(pyspark): add support for PySpark 3.5

---

docs/posts/ibis-duckdb-geospatial-dev-guru/index.qmd

Replicate Spatial Dev Guru's blog using Ibis
Closes https://github.com/ibis-project/ibis/issues/7717

docs(blog-post): replicate spatial dev guru blog

---

docs/posts/ibis-duckdb-geospatial-dev-guru/index.qmd

docs: update release date on Ibis geospatial dev guru post

---

ibis/backends/duckdb/registry.py
ibis/backends/duckdb/tests/test_geospatial.py

This PR adds support for geospatial literals for duckdb
Closes: #7662

feat(duckdb-geospatial): support for literals

---

ibis/backends/pandas/executor.py
ibis/backends/pandas/helpers.py
ibis/backends/tests/test_window.py

Also fix a bug caused by a wrongly placed reset index.

refactor(pandas): simplify pandas helpers

---

ibis/common/deferred.py
ibis/common/tests/test_deferred.py

fix(api): deferred values are not truthy

---

docs/_quarto.yml

docs(meta): add goatcounter to header of all quarto pages

---

ibis/backends/duckdb/tests/test_client.py

test(duckdb): test that column name case is preserved when inserting

---

docs/backends/pandas.qmd

docs(pandas): fix format for kwarg warning callout

---

ibis/formats/pandas.py
ibis/formats/tests/test_pandas.py

fix(pandas): support non-string categorical columns

---

ibis/backends/oracle/compiler.py

Simplify the overrides used to make sure Oracle timestamp types are generated with the correct syntax.
This has been fixed upstream but is not yet released.  I've added a note about when it can be ripped out.
Unrelated but small change, the stddev pop and samp remappings are unnecessary.

refactor(oracle): simplify oracle timestamp overrides

---

ibis/examples/__init__.py

fix(examples): use anonymous access when reading example data from GCS

---

ibis/backends/polars/__init__.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_dot_sql.py

fix(polars): avoid using unnecessary subquery for schema inference

---

ci/schema/trino.sql
compose.yaml
docker/minio/config.json
ibis/backends/trino/tests/conftest.py

Cleans up the minio container setup in preparation for the risingwave backend.

build(docker): clean up minio setup

---

ibis/conftest.py
ibis/expr/api.py

-------
Add more detail to docstring of `ibis.random()` about the behavior of repeated use of a single `ibis.random` instance.
Bonus: I didn't use the word "singleton", not even once.
Resolves #8055

docs(random): document behavior of repeated use of ibis.random() instance

---

.github/renovate.json

chore: disable renovate dependency dashboard

---

ibis/backends/tests/test_generic.py

test(risingwave): add notimpl markers for new hexdigest tests

---

docs/posts/kedro-ibis/index.qmd

add a quick Kedro blog post, linking out to the main article

docs: kedro blog post link

---

ibis/backends/tests/test_array.py

I think this should fix this CI failure https://github.com/ibis-project/ibis/actions/runs/7730026284/job/21074510642

test: fix flink ci failure

---

docs/contribute/03_style.qmd

docs: include American spelling usage in style guide

---

ibis/expr/types/geospatial.py

See this for context https://github.com/ibis-project/ibis/issues/8143

docs(geospatial): fix flaky ci geo-literals doctests

---

ibis/backends/flink/tests/test_join.py
ibis/backends/tests/test_array.py

test(arrays): ensure that array test assertions are not sensitive to row order

---

docs/index.qmd

relable -> rename
also formats the cell resulting in a minor change

docs: update quickstart to use rename

---

ibis/backends/tests/test_dot_sql.py

test(snowflake): enable xpassing test

---

ibis/backends/snowflake/tests/test_client.py

Adds a test to the snowflake backend ensuring that the `compile` method does not make requests to the database

test(snowflake): ensure that compilation does not make requests

---

docs/_tabsets/install.qmd

Resolves #8228, pending https://github.com/conda-forge/ibis-framework-feedstock/pull/90

docs(flink): update conda-based installation guide

---

.github/workflows/ibis-backends-cloud.yml

docs only change to test ci labels

ci(cloud-run): add label checkout and remove label after used

---

ibis/backends/trino/compiler.py

This was implemented natively on `main`, but got lost in the refactor.

fix(trino): re-enable native TABLESAMPLE support

---

docs/posts/why-voda-supports-ibis/index.qmd

Dane pointed out this typo :) thanks!

docs: typo fix to why voda blog

---

ibis/expr/operations/relations.py

Tiny little improvement. I was running into this, and this would have made it easier to debug.

feat(api): include bad type in NotImplementedError

---

README.md

docs: update number of backends in readme

---

docs/theme-dark.scss
docs/theme-light.scss
nix/quarto/default.nix

Bumps to a pre-release quarto to pick up some nice QoL changes for theming as well as itables CSS fixes.

chore(deps): bump quarto to pick up css table fixes

---

docs/posts/roadmap-2024-H1/index.qmd

de-drafts the roadmap blog and makes some edits
extra closes #7939

docs: roadmap 2024 H1 blog

---

flake.lock

Bump nixpkgs to the latest version

chore(deps): bump nixpkgs

---

poetry.lock
pyproject.toml

Was running into `AttributeError: module 'sqlglot.expressions' has no attribute 'IsInf'`

chore(deps): bump SQLGlot bound to include `IsInf`

---

conda/environment-arm64.yml
conda/environment.yml

Remove some unused dependencies in our conda env files.

chore(dev-tools): remove unused dependencies in conda environment files

---

ibis/expr/tests/test_newrels.py

Before `the-epic-split` refactor the left and right sides of join predicates were incorrectly generated for joins where the sides had the same base table. This has been fixed during the refactor, this PR only add the reproducer from the bug report.
Closes https://github.com/ibis-project/ibis/issues/8292

test(ir): cover join predicate dereferencing using tuple syntax

---

ibis/backends/datafusion/__init__.py

ensures that datafusion's `to_pyarrow_batches` does not do compute
Resolves #8468

fix: datafusion: ensure that to_pyarrow_batches does **NOT** do compute

---

docs/contribute/01_environment.qmd

Update environment setup instructions for `conda`.

docs: update environment setup instructions

---

docs/contribute/01_environment.qmd

Fixes a styling issue with the current pip callout box.

docs(dev): give the callout box a title

---

docs/how-to/visualization/graphs.qmd

docs(how-to): add graphviz section

---

ibis/backends/sqlite/udf.py
ibis/backends/tests/test_uuid.py

fix(sqlite): ensure `ibis.uuid()` generates a unique uuid per row

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-benchmarks.yml
.github/workflows/ibis-main.yml
.github/workflows/pre-release.yml
docs/contribute/01_environment.qmd
flake.lock
justfile

Bump nix flakes and poetry version requirement.

chore(deps): bump nix flakes and poetry version

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_temporal.py

Add implementation for TimestampNow to Exasol backend

feat(exasol): add support for TimestampNow

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_temporal.py

Add implementation for DateDelta to Exasol backend

feat(exasol): add support for DateDelta

---

docs/concepts/datatypes_datashapes.qmd

inspired by https://github.com/ibis-project/ibis/pull/8358

docs: add concepts guide on Datatypes and Datashapes

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_temporal.py

Add implementation for ExtractDayOfYear to Exasol backend

feat(exasol): add support for ExtractDayOfYear

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_temporal.py

Add implementation for ExtractQuarter to Exasol backend

feat(exasol): add support for ExtractQuarter

---

poetry.lock
pyproject.toml

fix(dask): pin dask version to avoid automatically picking up dask-expr

---

docs/index.qmd

Fixes https://github.com/ibis-project/ibis/issues/8639

docs: add constants to width and height

---

.github/workflows/create-rotate-key-issue.yml
.github/workflows/docs-preview.yml
.github/workflows/ibis-backends-cloud.yml
.github/workflows/release.yml

ci: use more robust app installation token generating action

---

docker/trino/catalog/hive.properties

Fixes failing trino CI and local testing.

test(trino): remove invalid properties from trino hive connector setup

---

ibis/backends/duckdb/compiler.py
ibis/backends/tests/test_array.py
ibis/expr/types/arrays.py

fixes https://github.com/ibis-project/ibis/issues/8650

fix(api): return NULL when NULL is passed to `Array.zip`

---

compose.yaml

Bump the clickhouse server version

ci(clickhouse): bump docker image to latest version

---

ibis/backends/duckdb/tests/test_geospatial.py

Work around flaky windows extension downloading in parallel test runs in CI (observed in the wild [here](https://github.com/ibis-project/ibis/actions/runs/8357537262/job/22876913288#step:14:109)).

ci(duckdb): work around flaky windows extension downloading

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_register.py

- Closes https://github.com/ibis-project/ibis/issues/8109

feat(duckdb): add support for read_mysql

---

ibis/backends/tests/test_dot_sql.py

Fixes a failing test due to the polars-dot-sql PR.

test(bigquery): fix quoting issues in new dot sql test

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_temporal.py

Add support for extract epoch seconds to exasol backend.

feat(exasol): add support for extract epoch seconds

---

ibis/backends/flink/tests/conftest.py

Aims to unblock people who cannot run the tests with Flink backend on the dockerized env as documented in https://github.com/ibis-project/ibis/issues/8507.
Allows running the tests with local env when env variable `IBIS_FLINK_LOCAL_ENV` is set to `true` or `1`.
E.g.
```
$ IBIS_FLINK_LOCAL_ENV=1 pytest -m flink ...
$ IBIS_FLINK_LOCAL_ENV="True" pytest -m flink ...
$ IBIS_FLINK_LOCAL_ENV=true pytest -m flink ...
```

test(flink): enable turning on local test env

---

ibis/backends/duckdb/__init__.py
ibis/expr/api.py

docs: update links to duckdb csv parameters

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_generic.py

Add support for `hexdigest` to exasol backend.

feat(exasol): add support for hexdigest

---

ibis/backends/exasol/compiler.py
ibis/backends/tests/test_numeric.py

Add support for bit operations to exasol backend.

feat(exasol): add support for bit operations

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-main.yml

Apparently we have not been uploading coverage for a bit :) This PR fixes that.

ci(coverage): actually upload coverage

---

docs/backends/duckdb.qmd

Per user request in https://ibis-project.zulipchat.com/#narrow/stream/415909-documentation/topic/geospatial.20dependency.20install

docs(duckdb): add short section on enabling duckdb geospatial

---

docs/contribute/02_workflow.qmd

Porting @gforsyth's comment [here](https://github.com/ibis-project/ibis/pull/8751#discussion_r1539914566) into dev docs.

docs(contribute): add a section to explain the different pytest markers

---

docs/tutorials/ibis-for-sql-users.qmd

Add a couple of examples showcasing how to do complex topk.
#8830

docs(tutorial): add examples for complex topk

---

conda/environment-arm64-flink.yml
conda/environment-arm64.yml
conda/environment.yml
poetry.lock
pyproject.toml

Bump polars lower bound due to its breaking changes.

fix(deps): bump polars lower bound

---

ibis/backends/__init__.py
ibis/backends/tests/test_client.py

support empty URL for local backends in ibis.connect()
* Resolves #8450

feat(pandas, polars, dask, datafusion): enable create local backends with empty url

---

.github/workflows/check-generated-files.yml
.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml
.github/workflows/ibis-benchmarks.yml
.github/workflows/ibis-main.yml
.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml
.github/workflows/pre-release.yml
docs/contribute/01_environment.qmd
flake.lock
flake.nix
justfile
nix/overlay.nix

Bump nix flakes back to the latest version, which now contains the xz downgrade.

chore(deps): bump nixpkgs back to the latest version

---

docs/concepts/user-testimonials.qmd

Feel free to expand the quote, if it makes sense; wanted to avoid more Kedro-specific concepts (like datasets).

docs: add testimonial on combining Ibis with Kedro

---

.github/ISSUE_TEMPLATE/feature-request.yml

We talked about having a motivation section in the feature request issue template, to encourage people to explain why they "need" what they are requesting beyond a personal specific use case. 
This PR adds such section.

chore: add motivation section to feat req template

---

docs/why.qmd

thanks to #8860, can simplify the connections to URIs in the "Why Ibis" article. this makes the tabsets slightly cleaner

docs: uniform connect via url across backends in why ibis

---

docs/contribute/01_environment.qmd

- Closes: https://github.com/ibis-project/ibis/issues/8653

docs: add link to style and formatting in env setup section

---

conda/environment-arm64.yml
conda/environment.yml

- Closes  #8654
In  #8654 there was the discussion about making an easier env for docs, I went backwards in my opinion about this given that it'll be another env to maintain and test locally. I think one big env for dev purposes is fine.

chore: add java deps to conda envs

---

ibis/backends/tests/test_json.py
ibis/backends/trino/compiler.py

Implement existing JSON functionality for the Trino backend.

feat(trino): implement existing json functionality

---

.github/workflows/ibis-backends-cloud.yml
ibis/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/conftest.py

Add a `from_snowpark` method to Snowflake backend. cc @IndexSeek.

feat(snowflake): create an ibis backend from a snowpark session

---

.github/workflows/ibis-backends-cloud.yml

Fixes the snowpark install in CI.

ci(snowflake): install python with specific version constraint marker

---

ibis/backends/snowflake/__init__.py

Forgot to include this change in the previous related PR. That will show me to not run the cloud tests in CI.

fix(snowflake): initialize the parent class on construction

---

ibis/backends/tests/test_generic.py

xref #8739
quick fix for bigquery failing on main

chore(bigquery): add notimpl marker to table_info test

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/tests/system/test_client.py

fix(bigquery): ensure session creation before creating temp tables

---

ibis/backends/snowflake/__init__.py

Fixes the failing Snowflake tests in CI.

fix(snowflake): set con outside of `_setup_session` call

---

ibis/backends/clickhouse/tests/test_client.py

Adds a test for #8924. Closes #8924.

test(clickhouse): verify create table from #8924 works

---

ibis/backends/clickhouse/tests/test_client.py

Fixes a flaky clickhouse test by using a distinct connection for listing tables in an empty database.

test(clickhouse): isolate empty table listing from existing connection

---

ibis/backends/pyspark/compiler.py
ibis/backends/sql/compiler.py
ibis/backends/tests/errors.py
ibis/backends/tests/test_struct.py
ibis/backends/trino/compiler.py

fix(structs): ensure that isin works with struct membership

---

.devcontainer/Dockerfile
.devcontainer/updateContent.sh

Resolves #9011 
take 2
also TIL you can't reopen a closed PR after force-pushing to the branch

chore(container): add gdal to codespace, disable dynamic versioning

---

ibis/expr/types/relations.py

This has been importing from the wrong place for a while,
causing an error in pylance

chore(dev-tools): fix import location in type import

---

ibis/backends/exasol/__init__.py

chore(exasol): correct typo in create_table docstring

---

.devcontainer/devcontainer.json
.devcontainer/postCreate.sh

Fixes the use of an LLM-hallucinated environment variable.

chore(dev-tools): fix poetry-dynamic-versioning usage in devcontainer

---

ibis/backends/tests/tpch/snapshots/test_h07/test_tpc_h07/snowflake/h07.sql
ibis/backends/tests/tpch/snapshots/test_h08/test_tpc_h08/snowflake/h08.sql
ibis/tests/benchmarks/test_benchmarks.py

Forgot to update them in https://github.com/ibis-project/ibis/pull/8992

chore(snowlake): update sql snapshots

---

ibis/expr/operations/udf.py

UDF arguments need to be Ibis expressions.  In the existing docstring examples
for the UDF decorators, it can be unclear that the integers being passed to
`add_one` are implicitly converted to Ibis literals.
To make it clearer, I've added memtables to all the examples, and used pandas-
and pyarrow-specific functions to the examples.

docs(udfs): improve udf docstring examples

---

ibis/backends/duckdb/__init__.py
ibis/backends/duckdb/tests/test_geospatial.py

- Closes https://github.com/ibis-project/ibis/issues/9076

fix(duckdb): load extension when executing geospatial expressions

---

docs/release_notes_generated.qmd

Bit of light editing to remove some stray commit messages from breaking changes section.

chore: remove some extra release notes information

---

ibis/backends/tests/test_generic.py

Fixes the currently failing test on `main`

test(snowflake): fix failing snowflake null boolean literal test

---

docs/presentations/overview.qmd

fix a typo; some other minor edits

docs(presentation): minor updates to overview presentation

---

ibis/backends/bigquery/__init__.py
ibis/backends/bigquery/client.py
ibis/backends/bigquery/tests/system/test_client.py
ibis/backends/pyspark/__init__.py

Remove custom implementation of cursor classes.

refactor(pyspark): remove custom implementation of cursors

---

docs/presentations/pycon2024/maintainers.qmd

Switch to the default theme for pycon2024 slides

chore: default theme

---

.github/workflows/ibis-backends-cloud.yml

Ensure that snowpark tests and non-snowpark tests run in different schemas.

ci(snowflake): ensure that snowpark tests run in their own schema

---

ibis/backends/impala/tests/conftest.py
ibis/backends/impala/tests/test_ddl.py
ibis/backends/impala/tests/test_parquet_ddl.py
nix/overlay.nix

Bump hash and adjust data paths in backend conftest for new directory data path.

test(data): adjust data directory for impala and bump nix hash

---

ibis/backends/dask/executor.py
ibis/backends/pandas/executor.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_struct.py

Pulled out part of https://github.com/ibis-project/ibis/pull/8666 to implement it separately

feat(pandas,dask): implement ops.StructColumn

---

ibis/backends/bigquery/compiler.py
ibis/backends/tests/test_string.py

feat(bigquery): implement a few URL ops

---

docs/CONTRIBUTING.md
gen_redirects.py

Updating maintainers guide URL from rename in https://github.com/ibis-project/ibis/pull/7633.

docs(dev): update maintainers guide link

---

ibis/tests/expr/test_literal.py

Preparing for https://github.com/ibis-project/ibis/pull/8666

test(refactor): simplify expr/test_literal.py

---

ibis/backends/tests/test_sql.py

This still isn't much meat in this test, but it is a little more substantial now.
Working towards https://github.com/ibis-project/ibis/pull/8666

test(sql): do more than a smoketest in test_literal()

---

.github/workflows/nix.yml
nix/quarto/default.nix

Fix the failing nix build on `main`.

chore(dev-deps): enable aarch64-linux dev envs

---

README.md

Commit 24b795a8963f119b69348641e6bbd250c2e41ae2 moved the location of the code of conduct. This PR adjusts sources to changes.

docs: update the code of conduct link

---

.github/workflows/ibis-main.yml

Re-enable doctests in main CI.

ci: reenable doctest builds

---

ibis/backends/snowflake/tests/test_udf.py

Be a bit less cheeky in the xfail marker.

test(snowflake): give a slightly better explanation for test failure

---

.github/workflows/upload-algolia-api.py

Don't worry, I'm a professional.

chore(docs): actually run the algolia index augmenter

---

ibis/backends/snowflake/tests/test_client.py

test(snowflake): add case to insert test

---

ibis/backends/snowflake/tests/test_udf.py

Apparently this is working again.

test(snowflake): enable xgboost model test again

---

ibis/backends/tests/test_window.py

Unxfail a passing window function test.

test(snowflake): unxfail passing test

---

flake.lock

chore(build): fix pyogrio build for macos arm

---

flake.lock

chore(deps): bump nix flakes

---

ibis/backends/tests/test_generic.py

Reverts ibis-project/ibis#9461

revert: test: add some basic cast tests

---

justfile

Add a command that I tend to use a lot, in case others want to use it.

chore(dev-tools): add `justfile` command to clean up containers

---

docs/why.qmd

Ibis works great within Shiny for Python as well, not just Quarto. Add link to Shiny to the docs.

docs: add Shiny (for Python) to "works well with" section

---

docs/concepts/who.qmd
docs/how-to/extending/builtin.qmd

Hello
I found some minor spelling issues in your docs.
Tried my best, hope it helps.

docs: fix spelling issues

---

ibis/backends/tests/test_generic.py

test(redo): add some basic cast tests

---

ibis/backends/tests/test_generic.py

Fix upstream failing bigquery and snowflake cast tests.

ci(snowflake,bigquery): fix failing tests

---

.github/workflows/docs-preview.yml

chore: test links

---

.github/workflows/docs-preview.yml

chore: fix quotes in links

---

flake.lock

chore(deps): bump nixpkgs and poetry2nix

---

ibis/expr/types/generic.py

Add an example to the `arbitrary` method docstring.

docs(arbitrary): add example for `arbitrary` method docstring

---

ci/schema/bigquery.sql
ci/schema/duckdb.sql
ci/schema/mysql.sql
ci/schema/postgres.sql
ci/schema/risingwave.sql
ci/schema/snowflake.sql
ci/schema/sqlite.sql
ci/schema/trino.sql
ibis/backends/tests/test_json.py

Fixes upstream failing tests for snowflake, and ensures that we do not hit the issue in the future.

test(sql): fix json array/map ordering in test to be deterministic

---

docs/how-to/extending/streaming.qmd

Add a guide on streaming operations
#9007

docs(how-to): add a guide on streaming operations

---

ibis/backends/polars/compiler.py

refactor(polars): delete some dead versioning code

---

ci/schema/druid.sql
ibis/backends/druid/tests/conftest.py
ibis/backends/sql/compilers/druid.py
ibis/backends/tests/test_aggregation.py
ibis/backends/tests/test_export.py
ibis/backends/tests/test_generic.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_temporal.py

WIP
Many of the temporal tests are failing because of this maybe simple reason.

fix(druid): get basic timestamp functionality working

---

ibis/backends/sql/compilers/bigquery.py
ibis/backends/tests/test_temporal.py

Add support for timestamp bucketing to BigQuery.

feat(bigquery): support timestamp bucket

---

compose.yaml
ibis/backends/sql/compilers/clickhouse.py
ibis/backends/tests/snapshots/test_sql/test_union_aliasing/clickhouse/out.sql

Managed to get backwards compatible code working with the latest clickhouse-server version bump

chore(deps): bump clickhouse-server version

---

ibis/backends/sql/compilers/snowflake.py
ibis/backends/tests/test_temporal.py

feat(snowflake): implement interval arithmetic

---

ibis/expr/types/core.py

This is the first step of some larger refactoring of the repr'ing code that I want to do, to hide a bunch more implementation details into pretty.py so that there is a better defined, smaller API.
I want to clean some things up first though.
We can pin down more precisely where the TranslationError happens: when we call
` to_rich(self, console_width=console_width)` and actually
try to execute the expression.
So let's consolidate the two try-catches down to just one, now there is less to think about. Now, `self._interactive_repr()` is really just `_capture_rich_renderable()`,
and so move this out into a pure function
where it is more obvious what it's responsibility is.

chore: consolidate error handling in __rich_console__

---

ibis/backends/clickhouse/tests/test_client.py

I can't reproduce the original error, so I'm adding a regression test to ensure we catch it in the future if it ever regresses.
Closes #9152.

test(clickhouse): add test for aliasing

---

docs/presentations/positconf2024/talk.qmd
docs/presentations/pycon2024/maintainers.qmd

- **docs(presentations): positconf2024 talk**
- **chore: add different title and author**

chore: fix titles in positconf pres

---

docs/presentations/linkedin-meetup-2024-04-24.qmd
docs/presentations/overview/index.qmd
docs/presentations/positconf2024/talk.qmd
docs/presentations/pycon2024/maintainers.qmd

Add some dates for better sorting

chore: give dates to presentations for better sorting

---

ibis/expr/rewrites.py
ibis/expr/tests/test_newrels.py

fix(ir): convert analytic functions to window functions in filters

---

docs/presentations/positconf2024/talk.qmd
docs/presentations/pycon2024/maintainers.qmd

Give some fancy animations to the plots at the end.

chore(positconf2024): fancy animations

---

docs/presentations/positconf2024/talk.qmd

chore: count dbs correctly

---

docs/presentations/positconf2024/talk.qmd

Fix the date, unfortunately I cannot time travel.

chore: fix date

---

ibis/backends/oracle/tests/test_client.py

test(oracle): fix flaky test that assumes tables exist

---

docs/posts/farewell-pandas/index.qmd

Mention dask in the deprecation post.

docs(blog): mention dask in the pandeprecation post

---

ibis/backends/tests/tpc/ds/test_queries.py

test(tpcds): add tpcds query 84

---

ibis/backends/tests/tpc/ds/test_queries.py

test(tpcds): add test for tpc ds query 99

---

ibis/backends/tests/tpc/ds/test_queries.py

test: add tests for tpc-ds query 98

---

ibis/backends/tests/tpc/ds/test_queries.py

code looks ok, did not understand why failed tolerance, not sure if we should change the tolerance for individual test .

test(tpcds): add test for tpcds query 97

---

ibis/backends/tests/tpc/ds/test_queries.py

test: add test for query 93

---

ibis/backends/tests/tpc/ds/test_queries.py

test(tpcds): add queries 68-71

---

ibis/backends/tests/tpc/ds/test_queries.py
ibis/backends/tests/tpc/queries/duckdb/ds/75.sql

This is wrong on a small handful of rows and I can't spot the mistake,
but pushing it up before I forget about it.

test(tpcds): add query 75

---

ibis/backends/tests/tpc/ds/test_queries.py

test: add tpcds 89

---

ibis/backends/tests/tpc/ds/test_queries.py
ibis/backends/tests/tpc/queries/duckdb/ds/92.sql
ibis/backends/tests/tpc/queries/duckdb/ds/94.sql

test(tpcds): add queries 92 and 94

---

ibis/backends/tests/tpc/ds/test_queries.py
ibis/backends/tests/tpc/queries/duckdb/ds/95.sql

TPC-DS queries 65, 86, 90, 91, and 95.

test(tpcds): queries 65, 86, 90, 91, and 95

---

ibis/backends/tests/tpc/ds/test_queries.py
ibis/backends/tests/tpc/queries/duckdb/ds/83.sql

test(tpcds): query 83

---

ibis/backends/tests/tpc/ds/test_queries.py

TPC-DS query 81, and xfail 67 until rollup is implemented.

test(tpcds): query 81

---

ibis/backends/tests/tpc/ds/test_queries.py

test(tpcds): query 88

---

ibis/expr/types/strings.py

fix(strings): correct a typo in `startswith` docstring

---

ibis/backends/tests/test_dot_sql.py

Fixes the failing snowflake test I introduced.

test(snowflake): deal with all the shouting

---

docs/_quarto.yml
docs/reference/cursed_knowledge.qmd

We have a lot of catching up to do, but we can at least note down these
horrors as we reencounter them.

docs(accursed): add cursed knowledge page

---

ibis/backends/datafusion/__init__.py
ibis/backends/datafusion/tests/test_register.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_string.py

Closes: https://github.com/ibis-project/ibis/issues/10069

fix(datafusion): raise when attempting to create temp table

---

flake.lock

chore(deps): bump poetry2nix and nixpkgs

---

docs/backends/bigquery.qmd

A hard won command line flag, this.

docs(bigquery): add update-adc flag to gcloud auth login

---

docs/reference/cursed_knowledge.qmd

Random number generation is cursed in ClickHouse.

docs(clickhouse): entry into the accursed

---

.github/labeler.yml
.github/workflows/labeler.yml

Adds some automatic labeling to incoming PRs based on files changed in the PR.

ci: add automatic pull request labels

---

ibis/backends/tests/test_array.py

Fix failing test on BigQuery CI.

test(bigquery): xfail nested flatten test

---

flake.lock

Bump nixpkgs and other nix flake dependencies.

chore(deps): bump nix flake dependencies

---

.github/workflows/algolia/configure-algolia-api.py
.github/workflows/algolia/upload-algolia-api.py

Noticed someone searched for `strptime` and got no results (there is no `strptime` method).  Seemed like a good candidate for a synonym.
I also noticed some methods missing from the index and added those in.

docs(algolia): feed the index a little snack

---

docs/contribute/02_workflow.qmd
docs/contribute/04_maintainers_guide.qmd

Alongside cursed knowledge comes blessed knowledge

docs(dev): add some hard-won pytest tips and tricks

---

.github/renovate.json
.github/workflows/update-nix-flakes.yml

Adds a weekly job to update nix flakes

ci(nix): add auto flake update [skip ci]

---

.github/workflows/update-nix-flakes.yml

Adds a conformant commit message for flake.lock updates

ci(nix): set nix flake update message [skip ci]

---

ibis/backends/snowflake/tests/test_udf.py

test(snowflake): fix snowflake test

---

ibis/backends/polars/compiler.py
ibis/backends/tests/test_array.py

Implements ArrayIntersect with [pl.Series.list.set_intersection](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.list.set_intersection.html#).

feat(polars): add ArrayIntersect operation

---

ibis/expr/types/relations.py

This now matches Column.value_counts()
The doctest can act as a test I figure.

feat(api): add `name` kwarg to `Table.value_counts()`

---

docs/backends/support/matrix.qmd
ibis/backends/sql/compilers/flink.py
ibis/expr/operations/analytic.py
ibis/expr/operations/arrays.py
ibis/expr/operations/relations.py
ibis/expr/operations/strings.py

docs(support-matrix): hide internal operations from the support matrix

---

ibis/expr/types/temporal.py

Adds doc examples for `day_of_week.index()` and `day_of_week.full_name()` for the `DayOfWeek` namespace.

docs(examples): add DayOfWeek method examples

---

docs/how-to/visualization/marimo.qmd
docs/presentations/overview/index.qmd

Many of our users @ marimo use Ibis and have strong integration with Ibis tables. We would love to be a part of your ecosystem page getting people set up to use Ibis in marimo

docs(how-to): marimo integration

---

flake.lock
nix/quarto/default.nix

- **chore(deps): bump poetry2nix**
- **chore(deps): bump nixpkgs**
- **chore(quarto): use deno instead of deno_1**
- **chore(deps): bump quarto to 1.6.32**

chore(deps): bump nix flakes and quarto version

---

ibis/backends/sql/compilers/base.py
ibis/backends/sql/compilers/druid.py
ibis/backends/sql/compilers/exasol.py
ibis/backends/sql/compilers/flink.py
ibis/backends/sql/compilers/impala.py
ibis/backends/sql/compilers/mssql.py
ibis/backends/sql/compilers/mysql.py
ibis/backends/sql/compilers/oracle.py
ibis/backends/sql/compilers/snowflake.py

The as_ family of snowflake functions already behaves as we previously wrote it, so there is no need to check first.

refactor(snowflake): remove some unnecessary checking of input in the snowflake compiler

---

ibis/expr/types/generic.py

Adds examples for [`cummin`](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Column.cummin), [`cummax`](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Column.cummax), [`lead`](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Column.lead), [`lag`](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Column.lag), and [`nth`](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Column.nth) to complete examples for the remaining [Generic expressions](https://ibis-project.org/reference/expression-generic) methods.
The table for `cummin` and `cummax` is a little wide. I used the `id` column to force ordering because without it the doctest would occasionally …

docs(examples): `cummin`, `cummax`, `lead`, `lag`, `nth` example usage

---

ibis/expr/api.py
ibis/expr/types/generic.py

Sets up examples, parameter, return information, and links to respective top level equivalent functions for [Value.asc](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Value.asc) and [Value.desc](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Value.desc). 
Fixes small typo with weather -> whether.

docs(examples): add `Value.asc` and `Value.desc` examples

---

ibis/backends/tests/test_array.py

Fixes the upstream failing test cases for bigquery.

test(bigquery): fix array concat test

---

pyproject.toml
uv.lock

similar to #10503
closes #10492 even more
I've kept the upper bound on sqlglot, but i'd appreciate it if the other pins could be relaxed please

chore: relax upper bounds on required dependencies (except sqlglot)

---

.env
flake.nix
ibis/backends/athena/tests/conftest.py

chore: avoid setting environment variables except for local cases

---

.env
.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml
flake.nix

chore: athena ci

---

.github/workflows/ibis-backends-cloud.yml

Attempt to fix athena CI again.

chore: fail fast on clouds

---

.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml

Got things working. This PR reverts debugging changes.
Example run with a single test file that hits credentials and runs a decent set of smoke tests: https://github.com/ibis-project/ibis/actions/runs/12563092302/job/35024742288

ci: revert athena debugging changes

---

ibis/backends/athena/tests/conftest.py
ibis/backends/tests/test_generic.py

Fixes an order dependent backend test.

test(athena): ensure that results are ordered

---

ibis/backends/athena/tests/conftest.py
pyproject.toml
requirements-dev.txt
uv.lock

Ensure that tables in Athena are only created if they do not exist.

chore(athena): reuse existing connection when setting up data fixtures

---

flake.lock
nix/pyproject-overrides.nix

chore(deps): bump nix flakes and add missing `editables` dependency for `hatchling`

---

docs/tutorials/browser/repl.qmd
flake.lock
requirements-dev.txt
uv.lock

Bump nix flakes and also try removing the pyarrow wheel hack

chore(deps): bump nix flakes and remove pyodide wheel loading hack

---

docs/tutorials/browser/repl.qmd
justfile

Finally remove all jupyterlite hacks for the ibis jupyterlite console.

chore(docs): remove remaining jupyterlite setup hacks

---

flake.lock
ibis/backends/tests/test_set_ops.py
requirements-dev.txt
uv.lock

Bump nix flakes and relock lockfiles.

chore(deps): bump flakes and do lockfile maintenance

---

flake.lock
requirements-dev.txt
uv.lock

Bump nix flakes and relock lockfiles.

chore(deps): bump flakes and bump lockfile versions

---

ibis/backends/tests/test_export.py

Fix failing cloud backend tests to account for all-nulls test cases.

test(cloud-backends): fix all-null tests for the clouds

---

flake.lock
requirements-dev.txt
uv.lock

Bump nix flakes and relock lockfiles.

chore(deps): bump flakes and bump locked versions

---

ibis/common/tests/test_patterns.py

chore: remove redundant word

---

ibis/expr/api.py
ibis/expr/types/relations.py

I recently had to use this, and the semantics were not clear to me.
I had to do this experimentation myself, so I thought I would write them down.

docs: clarify `distinct` in difference(), add examples

---

ibis/backends/tests/test_impure.py

Fixes failing cloud tests related to `test_impure.py`

test: fix cloud purity tests

---

flake.lock
ibis/backends/mssql/__init__.py
requirements-dev.txt
uv.lock

Bump nix flakes and regenerate lockfiles

chore(deps): bump deps

---

flake.lock
ibis/backends/tests/test_set_ops.py
requirements-dev.txt
uv.lock

Bump nix flakes and regenerate lockfiles

chore(deps): bump pyproject-nix, uv2nix, nixpkgs and relock

---

docs/_quarto.yml

Add JSON expression API docs page. Closes #10721.

docs: add JSON API docs

---

.github/actionlint.yaml
.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml

Beef up runners to see if memory is causing the transient failures.

ci(runners): beef up arm64 nix runners a bit

---

flake.lock
requirements-dev.txt
uv.lock

chore(deps): bump

---

ibis/backends/tests/snapshots/test_sql/test_union_aliasing/athena/out.sql

Fix failing athena test on `main`.

test(athena): regen snapshots for first/last value

---

ibis/backends/sql/compilers/duckdb.py
ibis/backends/sql/compilers/postgres.py
ibis/backends/tests/test_array.py
ibis/expr/operations/arrays.py
ibis/expr/types/arrays.py

feat(arrays): add `modes` array aggregation

---

ibis/backends/athena/__init__.py
ibis/backends/athena/tests/conftest.py
ibis/backends/athena/tests/test_client.py

fix(athena): use `exists` instead of `replace` for `schema`

---

.github/workflows/ibis-backends-cloud.yml
ibis/backends/snowflake/__init__.py

fix(snowflake): ensure that paths are URIs on all platforms

---

nix/pyproject-overrides.nix

fix(dev-env): fix aarch64 nix builds

---

ibis/backends/snowflake/__init__.py
ibis/backends/snowflake/tests/conftest.py

Fixes failing Snowflake CI, again :)

ci(snowflake): ensure that paths are posix during `PUT` in `conftest.py`

---

ibis/backends/sql/dialects.py

fix(sqlglot): ensure that `sge.Median` is only accessed when it exists

---

docs/posts/udf-rewriting/index.qmd

- remove an inadvertent close bracket 
- update date

docs: update post date

---

flake.lock
requirements-dev.txt
uv.lock

chore(deps): bump nix flakes and regen lockfiles

---

.github/workflows/ibis-backends-cloud.yml
.github/workflows/ibis-backends.yml

This PR adds a timeout to steps that occasionally timeout

ci(backends): set a lower timeout for steps

---

ibis/backends/postgres/tests/test_client.py

test(postgres): add test for inserting into and creating a table with overwrite

---

ci/schema/mssql.sql
compose.yaml
ibis/backends/mssql/__init__.py
ibis/backends/mssql/tests/conftest.py
ibis/backends/mssql/tests/test_client.py
ibis/backends/oracle/__init__.py
ibis/backends/sql/__init__.py
ibis/backends/tests/test_client.py
justfile

fix(mssql): ensure that dots in `database` parameter to `list_tables` are used as path delineators

---

ibis/backends/sqlite/__init__.py

fix(sqlite): avoid generating double-quoted string literals

---

ibis/backends/duckdb/__init__.py

Refactors extension loading in duckdb to avoid clobbering installation and loading of extensions.

refactor(duckdb): simplify loading and installation of extensions

---

ibis/tests/expr/test_selectors.py

chore(selectors): remove deprecated tests

---

ibis/backends/__init__.py
ibis/backends/athena/__init__.py
ibis/backends/bigquery/__init__.py
ibis/backends/clickhouse/__init__.py
ibis/backends/databricks/__init__.py
ibis/backends/datafusion/__init__.py
ibis/backends/druid/__init__.py
ibis/backends/duckdb/__init__.py
ibis/backends/exasol/__init__.py
ibis/backends/flink/__init__.py
ibis/backends/impala/__init__.py
ibis/backends/mssql/__init__.py
ibis/backends/mysql/__init__.py
ibis/backends/oracle/__init__.py
ibis/backends/polars/__init__.py
ibis/backends/postgres/__init__.py
ibis/backends/pyspark/__init__.py
ibis/backends/risingwave/__init__.py
ibis/backends/snowflake/__init__.py
ibis/backends/sqlite/__init__.py
ibis/backends/tests/test_examples.py
ibis/backends/tests/test_numeric.py
ibis/backends/trino/__init__.py
ibis/examples/__init__.py
pyproject.toml
requirements-dev.txt
uv.lock

Make example loading overloadble by the backend. This allows more backends to support example loading.

feat(examples): expand examples functionality to more backends

---

ibis/backends/athena/tests/conftest.py

Ensure that Athena tests are not running against empty data, by dropping tables before loading them

test(athena): ensure that tables are dropped before loading

---

flake.lock
requirements-dev.txt
uv.lock

chore(deps): bump and relock

---

ibis/backends/athena/tests/conftest.py

Clean up the test data loading in the athena conftest.py module

ci(athena): use internal ibis APIs for creating testing data

---

ibis/backends/oracle/__init__.py

Small refactor to remove unused query output from oracle `list_tables` metadata queries

refactor(oracle): remove unused `owner` column from `select` metadata query

---

ibis/backends/mysql/datatypes.py
ibis/backends/mysql/tests/test_client.py
ibis/backends/sql/datatypes.py

fix(mysql): ensure that unsigned integers are mapped to the ibis type system

---

ibis/backends/postgres/__init__.py

Fixes a cursor lifetime issue showing up in CI where the server-side cursor in Postgres to_pyarrow_batches is cleaned up before the RecordBatchReader is ever consumed.

refactor(postgres): split out `hstore` extension registration into separate method

---

docker/postgres/debug.sql
ibis/backends/postgres/__init__.py
ibis/backends/postgres/tests/test_client.py
ibis/backends/tests/test_client.py

This PR cleans up a leaky cursor coming from a `raw_sql` call that never closed
the cursor it returns.
I've also added some SQL that should make it easier to debug the problem of
idle transactions in the future.

fix(postgres): clean up leaky cursor coming from `raw_sql`

---

ibis/expr/types/core.py

docs: fix to_* methods docstrings typos

---

ibis/backends/postgres/__init__.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/postgres/tests/test_client.py

PR to clean up a few bits in the postgres backend to help isolate idle transactions

fix(postgres): clean up possible transaction hangs

---

ibis/backends/sql/compilers/databricks.py
ibis/backends/sql/datatypes.py
ibis/backends/tests/test_json.py

feat(databricks): add support for json via variant

---

.github/workflows/docs-preview.yml

Debugging for changed file detection

ci: changed file debug

---

.github/workflows/create-rotate-key-issue.yml
.github/workflows/docs-preview.yml
.github/workflows/ibis-backends-skip-helper.yml
.github/workflows/ibis-main-skip-helper.yml
.github/workflows/nix-skip-helper.yml
.github/workflows/nix.yml
.github/workflows/pr-title.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/update-nix-flakes.yml

Address token permission issues.

ci: assign token permissions to each gha workflow

---

.github/workflows/pr-title.yml

ci(pr-title): fix commitlint call

---

ibis/backends/sql/dialects.py
ibis/backends/tests/test_binary.py

feat(pyflink): fix type mapping from BINARY to VARBINARY

---

ibis/backends/postgres/__init__.py

feat(postgres): allow disablement of hstore extension loading

---

ci/schema/postgres.sql
ibis/backends/postgres/__init__.py
ibis/backends/postgres/converter.py
ibis/backends/postgres/tests/conftest.py
ibis/backends/sql/compilers/datafusion.py
ibis/backends/sql/compilers/postgres.py
ibis/backends/sql/compilers/risingwave.py
ibis/backends/sql/datatypes.py
ibis/backends/sql/dialects.py
ibis/backends/tests/test_client.py
ibis/backends/tests/test_map.py
ibis/backends/tests/test_param.py
ibis/backends/tests/test_udf.py

Reimplement maps for postgres using JSONB instead of HSTORE.
Fixes #11107.

feat(postgres): implement maps in terms of JSONB instead of HSTORE

---

ibis/backends/polars/compiler.py
ibis/backends/sql/compilers/bigquery/__init__.py
ibis/backends/sql/compilers/clickhouse.py
ibis/backends/sql/compilers/datafusion.py
ibis/backends/sql/compilers/druid.py
ibis/backends/sql/compilers/duckdb.py
ibis/backends/sql/compilers/flink.py
ibis/backends/sql/compilers/mysql.py
ibis/backends/sql/compilers/postgres.py
ibis/backends/sql/compilers/sqlite.py
ibis/backends/sql/compilers/trino.py
ibis/backends/tests/test_temporal.py
ibis/common/temporal.py
ibis/expr/datatypes/core.py

Resolves https://ibis-project.zulipchat.com/#narrow/channel/405263-general/topic/milliseconds.20from.20Unix.20epoch.20with.20sqlite/with/510962087

feat(temporal): implement casting floating values to timestamps

---

ibis/backends/databricks/tests/conftest.py
ibis/backends/databricks/tests/test_json.py

Adds a test for the original issue reported in #11025.

test(databricks): add test for creating a table using json

---

ibis/backends/sql/compilers/athena.py
ibis/backends/sql/compilers/bigquery/__init__.py
ibis/backends/sql/compilers/snowflake.py
ibis/backends/sql/compilers/trino.py

Fix timestamp casting for cloud backends.

fix(snowflake/bigquery/athena): ensure that timestamp casting works

---

ibis/backends/sql/compilers/datafusion.py
ibis/backends/tests/test_array.py

Add ArrayAny and ArrayAll to datafusion backend

feat(datafusion): add support for anys and alls

---

docs/concepts/casting.qmd

I realized we hadn't written down anywhere how we defined our behavior on many of these ambiguous topics. This doc isn't nearly complete, but it is somewhere to start, and we can use it as a north star as we implement stuff.

docs: add concepts doc on casting

---

ibis/backends/sql/compilers/datafusion.py
ibis/backends/tests/test_numeric.py

Add Greatest and Least to DataFusion Backend

feat(datafusion): add Greatest and Least

---

ibis/backends/sql/compilers/snowflake.py

Fixes currently failing Snowflake tests

fix(snowflake): use newer sqlglot syntax for unnest

---

nix/pyproject-overrides.nix

Fixes nix builds on python 3.13

fix(builds): ensure that python 3.13 builds on nix

---

ibis/backends/duckdb/tests/conftest.py
ibis/backends/tests/test_impure.py

snowflake udf no underscore

---

ibis/backends/tests/test_client.py
ibis/expr/types/_rich.py
ibis/expr/types/core.py
ibis/expr/types/generic.py
ibis/expr/types/relations.py
ibis/expr/types/rich.py

revert: feat(ux): improve rich rendering (#11326)

---

docs/contribute/01_environment.qmd

Hi! I found broken link in docs and replaced their.

chore: fixed broken link

---

ibis/expr/types/generic.py

Try building docs with expected failure

chore(generic): expected failure for cast docs

---

flake.nix
justfile

Upgrade compose build to buildx bake.

chore(dev-deps): replace `compose build` with recommended `buildx bake`

---

flake.lock
flake.nix
nix/overlay.nix
nix/quarto/default.nix
requirements-dev.txt
uv.lock

Bump and relock deps and also bump quarto

chore(deps): bump and relock and bump quarto to latest pre-release

---

ibis/backends/snowflake/tests/conftest.py

test(snowflake): fix unpacking test

---

ibis/expr/types/temporal.py

just a few little improvements.

docs: improve docstrings for temporal Values

---

.releaserc.js
CITATION.cff

Add `CITATION.cff`. Closes #11513.

chore: add `CITATION.cff`

---

ibis/backends/athena/__init__.py

Follow up to #11573 that should also improve performance in the very common case of accessing in-database table metadata.

perf(athena): use `get_table_metadata` in `get_schema`

---

ibis/expr/types/generic.py

A followup to this would be to somehow make this more discoverable. Perhaps add in docstrings for `__eq__` and friends, and then link to this from there.

docs: improve Value.identical_to() docstring and example
