- ibis/backends/clickhouse/compiler/values.py
Only generate a `tuple` prefix if there's a single element.
> test(clickhouse): fix code to avoid snapshot regeneration

- ibis/backends/base/__init__.py
- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/tests/test_api.py
- ibis/backends/tests/test_client.py
This PR adds a `database` argument to  `list_schemas` for listing schemas in databases other than the currently active one.
> feat(sql): add `database` argument to `list_schemas`

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/datatypes.py
- ibis/backends/snowflake/tests/test_datatypes.py
- ibis/backends/tests/test_client.py
This PR fixes an issue with some logic that was incorrectly assuming that if a precision and scale were
specified in a [`ResultMetadata`](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api#label-python-connector-resultmetadata-object) object, then the type was unambiguously a numeric type because that's what
the documentation says.
The documentation seems to be wrong in practice, because timestamp metadata comes along with a `precision`
equal to 0 and a non-zero `scale`.
Unfortunately, this information is completely missing from timestamp type modeling in `snowflake-sqlalchemy`.
This means that type reflection from sqlalchemy for timestamps doesn't match that of what's reported by
Snowflake itself, so until we move away from `snowflake-sqlalchemy` there'll …
> fix(snowflake): fix timestamp scale inference

- ibis/expr/deferred.py
- ibis/expr/tests/test_deferred.py
- ibis/expr/types/core.py
- ibis/util.py
This PR fixes an issue where non-ibis APIs that depend on implicit
implementations of `__iter__` that use `__getitem__` would never terminate due
to `Deferred` instances implementing an always-succeeding version of
`__getitem__`.
The main downside is that because `Deferred` now implements `__iter__` it
appears to be iterable, so we have to exclude it from `is_iterable` instances
checks explicitly.
> fix(api): fail on trying to construct an iterable of a deferred object

- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/datatypes.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/snowflake/tests/test_datatypes.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_examples.py
- ibis/tests/benchmarks/test_benchmarks.py
~Depends on #6792.~
This is another set of workarounds to support consistent quoting behavior
in the presence of tables from different schemas and/or databases.
As part of this PR I moved away from using SQLAlchemy autoloading (in favor of
`Backend._metadata`).
Anecdotally, this appears to be a bit snappier than what we're currently doing.
> fix(snowflake): handle databases and schemas when quoting tables

- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/test_client.py
This PR fixes the trino implementations of `list_databases` (only lists the current catalog instead of all available catalogs), and `list_schemas` (incorrect quoting of the schema in the base sqlalchemy implementation).
> fix(trino): fix `list_databases` to show all catalogs and `list_schemas` to allow the `database` argument

- justfile
Require a benchmark run number when running `just benchcmp` to avoid spurious comparisons to benchmark runs on the same commit.
> chore(benchmarks): require a benchmark run number when invoking `just benchcmp`

- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/test_client.py
- feat(trino): add source application to trino backend
- docs(trino): add connection docstring
> feat(trino): add application source to the trino client by default

- docker-compose.yml
- docker/trino/Dockerfile
- docker/trino/entrypoint.sh
This PR moves our `hive-metastore` docker image to use a supported JDK, as well as bumps its version.
> chore(dev-deps): bump JDK and move to supported JDK docker image

- ibis/backends/dask/execution/generic.py
- ibis/backends/tests/test_numeric.py
- ibis/expr/types/numeric.py
.histogram has a serious bug, where the bin width is calculated wrong. If you do the same calculation with np.histogram(), you get very different results. I added a fix for this.
But this still doesn't solve another bug:
`ibis.examples.penguins.fetch().bill_depth_mm.histogram(5).name("hist").value_counts().order_by("hist")`
gives 
```
┏━━━━━━━┳━━━━━━━━━━━━┓
┃ hist  ┃ hist_count ┃
┡━━━━━━━╇━━━━━━━━━━━━┩
│ int64 │ int64      │
├───────┼────────────┤
│     0 │         56 │
│     1 │         66 │
│     2 │         99 │
│     3 │         95 │
│     4 │         25 │
│     5 │          1 │
│  NULL │          2 │
└───────┴────────────┘
```
Note how the max value is assigned the bin `5`. That isn't right, the bins should only be labeled 0 to 4.
Seeing as how no one is noticing that this is broken, …
> fix(histogram): ensure that the bin width calculation matches numpy

- ibis/backends/base/sql/__init__.py
- ibis/backends/base/sql/alchemy/__init__.py
> docs(backends): explain how to release a cursor and suggest using `.sql` instead

- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_map.py
Fixes a bug in snowflake lateral join rewriting where we were not accounting for newlines. Discovered fiddling around with #6851.
> fix(snowflake): ensure that laterals joins with newlines are also rewritten

- ibis/expr/types/core.py
- ibis/expr/types/numeric.py
- ibis/expr/types/strings.py
- ibis/expr/types/temporal.py
`NotImplemented` is an instance and the actual type is `NotImplementedType`. The mypy errors which this fixes look like this:
```bash
...
ibis/expr/types/numeric.py:711: error: Variable "builtins.NotImplemented" is not valid as a type  [valid-type]
ibis/expr/types/numeric.py:711: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
...
```
As mentioned in #6844, I can create a few more of these smaller PRs or I can bundle more changes into a single PR. Whatever works best for you.
Edit: NotImplementedType was introduced in Python 3.10 so tests fail for 3.9. I'll look into it.
> fix(type hints): remove notimplemented as type hints as not valid

- ibis/backends/datafusion/compiler.py
- ibis/backends/tests/test_temporal.py
This PR adds to the DataFusion backend the following operations:
- ExtractYear
- ExtractMonth
- ExtractDay
- ExtractQuarter
- ExtractMinute
- ExtractHour
- ExtractMillisecond
- ExtractSecond
- ExtractDayOfYear
- DayOfWeekIndex
- DayOfWeekName
- Date
The cast function is broken due to an upstream bug in Arrow (or PyArrow), hence I marked it as broken in the tests
> feat(datafusion): add temporal functions

- ibis/expr/operations/tests/test_core.py
With an error in the pandas backend this test case was failing.
> test(ir): test_custom_table_expr should not depend on the pandas backend

- ibis/backends/clickhouse/__init__.py
- ibis/backends/tests/test_register.py
Add support for reading parquet and csv files from local disk.
Depends on #6860.
> feat(clickhouse): support `read_csv` and `read_parquet`

- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_datatypes.py
- ibis/tests/benchmarks/test_benchmarks.py
This PR implements some performance improvements to the duckdb backend in support
of making one of the more difficult-to-make-usable use cases workable.
That use case is CSV files with lots of columns.
The primary part of the duckdb backend that's faster here is table metadata handling.
This is made up of a few components, and process is roughly:
1. Run a `DESCRIBE SELECT * FROM table` query to get the names and types from duckdb
1. Parse the type strings into ibis types
1. Construct a `sqlalchemy.Table` object from the resulting list of column
names and types
It turns out that **all three** of these steps were very slow in "lots of columns" case.
`DESCRIBE SELECT * FROM table` seems to be **slower** than `DESCRIBE table` if
`table` is a view of CSV file. I'm not sure why, but this PR …
> perf(duckdb): speed up performance with wide tables

- ibis/formats/tests/test_numpy.py
- ibis/tests/strategies.py
- ibis/tests/test_strategies.py
I wanted to limit the hypothesis generated datatypes to be nullable, but the previously defined strategies were not allowing that.
> feat(tests): support defining datatype nullability for hypothesis strategies

- ibis/common/annotations.py
- ibis/common/bases.py
- ibis/common/caching.py
- ibis/common/collections.py
- ibis/common/egraph.py
- ibis/common/graph.py
- ibis/common/patterns.py
- ibis/common/tests/conftest.py
- ibis/common/typing.py
As suggested by @kszucs in https://github.com/ibis-project/ibis/pull/6862#issuecomment-1676799118, I copied all type hint changes from #6852 into this PR. I also fixed a few more mypy errors but this PR does not yet fix all in `ibis.common`. I think I'm not familiar enough with Ibis to suggest changes for the remaining ones but happy to brainstorm and review!
Some but not all outstanding points:
> fix(type hints): improve type hints in ibis.common

- ibis/expr/types/relations.py
- ibis/selectors.py
- ibis/tests/expr/test_selectors.py
- ibis/tests/expr/test_table.py
This PR adds promotion of lists of column names to `s.any_of(s.c(col0), s.c(col1), ...)` selectors, which allows specifying them wherever you can specifyc `s.c(...)`.
> feat(ux): promote lists of strings to `any_of` selectors

- ibis/backends/base/__init__.py
- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/trino/__init__.py
This PR adds support for cross-schema and cross-catalog table operations to the trino backend. I pulled out the logic to access metadata into a specialized SQLAlchemy backend that is shared with the Snowflake backend due to their near-identical logic for achieving the same result.
> feat(trino): add support for cross-schema and cross-catalog table operations

- ibis/backends/bigquery/tests/conftest.py
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_union/False/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_union/True/out.sql
- ibis/backends/bigquery/tests/unit/test_compiler.py
Fixes failing bigquery tests that were unnecessarily using a negated `s.c` selector to select columns that do not exist.
> test(bigquery): remove unnecessary use of `s.c` selector in tests

- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/test_client.py
Fixes an issue where the full identifier for snowflake tables was not compiled for `sa.Table` objects.
> fix(snowflake): ensure that the fully qualified name is compiled into `sa.Table`s

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
Given the feedback [here](https://github.com/duckdb/duckdb/discussions/8582#discussioncomment-6737173) this switches `to_pyarrow` to use `.sql(...).to_arrow_table()` instead of `.execute(...)`. This has a measurable impact on performance on some queries (up to 4x faster on my machine) as it allows duckdb to include the result conversion to pyarrow in the physical plan.
With this fix ibis & duckdb vs duckdb alone perform ~the same on the workload described in #6874.
Fixes #6874.
> perf(duckdb): improve `to_pyarrow` performance

- ibis/selectors.py
- ibis/tests/expr/test_selectors.py
Resolves #6872
There are other ways to accomplish supporting column references in `drop`, but I think it makes sense to also support column references in the named column selector.
> feat(selectors): support column references in column selector

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
> chore(duckdb): remove use of cursor in `to_pyarrow` and remove duplicate test marker

- ibis/expr/analysis.py
- ibis/expr/deferred.py
- ibis/expr/operations/relations.py
- ibis/expr/operations/tests/conftest.py
- ibis/expr/types/core.py
- ibis/expr/types/generic.py
- ibis/expr/types/structs.py
These are the changes proposed in #6862 for `ibis.expr`. There are many more errors in `ibis/expr`. As mentioned in https://github.com/ibis-project/ibis/pull/6867#issuecomment-1682735449 I'm currently getting a few hundred errors, depending on which part of ibis I check. For `ibis.expr` it's 1157 errors.
> fix(type hints): improvements to type hints in ibis.expr

- ibis/common/annotations.py
- ibis/common/grounds.py
- ibis/common/patterns.py
- ibis/common/tests/test_grounds.py
- ibis/common/tests/test_grounds_benchmarks.py
- ibis/common/tests/test_patterns.py
- added a benchmark for constructing `Concrete` objects
- entirely separated the two kinds of `Annotation`s, `Arguments` are now only available from `cls.__signature__.parameters` and `Attributes` are stored in `cls.__attributes__`
- inline the construction of `__args__` and `__precomputed_hash__` instead of slower default attribute initialization
- added a specialized `SequenceOf` pattern matcher which contains less checks and can be used in most of the cases, renamed the previous one as `GenericSequenceOf`
- construct `.__args__` and set the arg values using a single pass instead of the previous two iterations
These resulted in a rough 12% improvement in the particular benchmark. Since we heavily depend on this codepath this could even have a higher impact over the full test suite.
``` …
```
> perf(common): improve `Concrete` construction performance

- ibis/expr/datatypes/tests/test_value.py
- ibis/expr/datatypes/value.py
Fixes an issue where error messages normalizing certains kinds of literals was not readable due to missing to f-string sigil.
> fix(api): ensure that normalization of boolean, ints and floats fail with readable error message

- docs/backends/clickhouse.md
- docs/backends/polars.md
- docs/backends/pyspark.md
- docs/backends/snowflake.md
- ibis/backends/base/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_register.py
This PR adds support for reading globs to existing file-supporting backends with a few exceptions. The clickhouse backend does not support reading JSON (no way to infer the schema), and I simply did not implement datafusion json reading.
> feat(backends): support globbing in existing file-reading backends

- .github/workflows/ibis-backends.yml
- gen_matrix.py
- ibis/backends/flink/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/tests/test_dot_sql.py
- justfile
- mkdocs.yml
- pyproject.toml
_NB: This requires `pip install apache-flink` on top of the Ibis requirements, which will overwrite some dependency versions._
As a quick update, as of https://github.com/ibis-project/ibis/pull/6835/commits/7685791c877557349072e17c28dc2e58a2649612, the backend "works" (with many caveats). For example:
```python
from pyflink.table import EnvironmentSettings, TableEnvironment
env_settings = EnvironmentSettings.in_batch_mode()
table_env = TableEnvironment.create(env_settings)
import ibis
backend = ibis.flink.connect(table_env)
table_env.execute_sql(
"""
CREATE TABLE awards_players (
playerID STRING,
awardID STRING,
yearID BIGINT,
lgID STRING,
tie STRING,
notes STRING
) WITH (
'connector' = 'filesystem',
'path' = '/workspaces/ibis/ci/ibis-testing-data/csv/awards_players.csv',  # replace with …
```
> feat(flink): implement a minimal PyFlink `Backend`

- ci/schema/snowflake.sql
- ibis/backends/snowflake/tests/conftest.py
This PR refactors Snowflake test data loading to use Parquet files instead of CSV, which should save slightly on storage and bandwidth usage as well as be robust to any particular schema inference and/or parser changes on the server side.
> test(snowflake): use parquet for data loading in the test suite

- ibis/expr/types/relations.py
- ibis/selectors.py
- ibis/tests/expr/test_relocate.py
This PR adds a new `relocate` method on `Table` expressions.
The implementation is a near exact clone of the [`dplyr` implementation](https://dplyr.tidyverse.org/reference/relocate.html).
The tests are also based on the [`dplyr` test suite](https://github.com/tidyverse/dplyr/blob/c963d4db08ab4b4e7f75e3b99b04ef5f6e903a25/tests/testthat/test-relocate.R) for this feature.
Closes #6803.
> feat(api): add `relocate` table expression API for moving columns around based on selectors

- ibis/backends/clickhouse/datatypes.py
- ibis/formats/parser.py
Adds backcompat imports for some recently renamed objects in sqlglot 17.15.0. The TPC-H job exposed this failure because it has no dependency pins for better or worse.
> fix(sqlglot): ensure back compat for `DataTypeParam` import

- justfile
> chore(dev-deps): check poetry version when invoking `just lock`

- poetry-overrides.nix
This PR adds two tiny, related patches to `oscrypto` in the nix environment.
I discovered this problem by trying to run snowflake tests after a recent
nixpkgs update (ca2b0238b).
This update broke snowflake tests in the nix environment, due to a switch to
openssl 3 in that update.
Searching around the internets I found
https://github.com/dbt-labs/dbt-core/issues/3366, which led me to
https://github.com/wbond/oscrypto/issues/78 which is fixed upstream in
`oscrypto`.
Nix has a solid patching mechanism for doing post-install surgery on packages,
which I use here to apply two patches that address the regex-version-searching
bug (the root cause of the original failure).
We can remove these when the next version of `oscrypto` is released to PyPI.
> chore(snowflake): patch `oscrypto` in the nix environment

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
Remove the unnecessary `ClickhouseTable` class in favor of using the backend `insert` method.
> refactor(clickhouse): move `ClickhouseTable.insert` method to clickhouse backend and remove `ClickhouseTable` class

- ibis/backends/bigquery/registry.py
As of the most recent fix for string literals, we were double-escaping some characters in the BigQuery regex pattern arguments.
Closes #6961
> fix(bigquery): correctly escape ASCII escape sequences in regex patterns

- ibis/backends/base/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/impala/client.py
- ibis/backends/impala/tests/test_ddl.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/client.py
- ibis/backends/tests/test_client.py
- Adds a new `Backend.rename_table` method for renaming an existing table
- Implements this method for `impala` and `pyspark` alone
- Removes the existing `ImpalaTable.rename` method in favor of `Backend.rename_table`
- Removes the existing `PySparkTable.rename` method in favor of `Backend.rename_table`
Needed for #6959.
> feat(api): add `Backend.rename_table` method

- ibis/backends/oracle/__init__.py
- ibis/backends/oracle/tests/conftest.py
Maybe resolves #6913 
just so I don't forget this _again_:
A `sid` is a unique name of an INSTANCE running an oracle process (a single, identifiable machine).
A `service name` is an ALIAS to one (or many) individual instances that can be hotswapped without the client knowing / caring -- so a `service_name` might map to one or more `sid`s but this would be opaque to the user.
A `dsn` is a 'data source name' and is a very lispy connection definition that the oracle python clients can parse for things like `sid`, `service_name`, `host`, `port`, etc.
In order to allow for maximal connection flexibility, this PR lets users pass in a DSN directly, which will override every other keyword argument.  If they don't pass in a DSN, we construct one from the provided keyword arguments (like `host`, …
> fix(oracle): clarify sid vs service_name handling and allow dsn

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
- ibis/backends/clickhouse/tests/test_select.py
- ibis/backends/clickhouse/tests/test_types.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/impala/tests/test_pandas_interop.py
- ibis/backends/pandas/execution/generic.py
- ibis/backends/pandas/tests/execution/test_operations.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_json.py
- ibis/backends/tests/test_string.py
- ibis/formats/pandas.py
- ibis/tests/strategies.py
This PR makes ibis compatible with pandas 2.1.0.
Unfortunately at least one hack was required due to duckdb's aggressive imports
when using bind parameters with arrow output reported in https://github.com/duckdb/duckdb/issues/8735.
`clickhouse_connect` is using a removed API as well. The workaround there was
easy: use `insert_arrow` instead of `insert_df`. Filed an issue there too: https://github.com/ClickHouse/clickhouse-connect/issues/234
`hypothesis` is another one that is using a removed API (`is_categorical_dtype`).
> fix(pandas): make ibis compatible with pandas 2.1.0

- ibis/backends/bigquery/client.py
- ibis/backends/dask/tests/execution/test_join.py
- ibis/backends/impala/tests/conftest.py
- ibis/backends/impala/tests/test_sql.py
- ibis/backends/pandas/tests/execution/test_join.py
- ibis/backends/pyspark/tests/test_basic.py
- ibis/backends/trino/tests/conftest.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
- ibis/tests/sql/test_compiler.py
As suggested in #6801, this:
- Adds a new `Table.rename` method that accepts column names as `new_name="old_name"` kwargs. This new method also swaps the order of key-value pairs when passing a mapping as an argument to `{"new_name": "old_name"}` for consistency.
- Deprecates `Tabel.relabel` in favor of `Table.rename`.
Fixes #6801.
> feat(api): `add Table.rename`, deprecate `Table.relabel`

- docs/.gitignore
- docs/_quarto.yml
- docs/styles.css
- docs/theme-light.scss
> docs(quarto): make sure blog post titles are readable in light mode

- pyproject.toml
This PR changes pre-release versions to always start with the next major version, so that any releases in between major releases such as backports (#6980) will not be sorted _after_ a pre-release.
The change is visible by running `poetry build` from this PR's commit:
```
❯ poetry build
Building ibis-framework (7.0.0.dev217)
- Building sdist
- Built ibis_framework-7.0.0.dev217.tar.gz
- Building wheel
- Built ibis_framework-7.0.0.dev217-py3-none-any.whl
```
Note the 7.0.0 prefix.
> build: bump the major version to ensure that prereleases are always sorted after existing versions

- nix/quarto/default.nix
This PR bumps to the most recent quarto pre-release version and removes the nix use of pandoc in favor of the binary that quarto ships directly. This cuts down quite a lot of the size of the dependency closure.
> ci: build with vendored version of pandoc and bump quarto version

- docs/tutorials/getting_started.qmd
minor annoyance, but you're already in a tutorial
> docs: update link to 'example repository' instead of 'tutorial'

- docs/index.qmd
adds a break after the 3d scatter plot before the button
> docs: fix whitespace issue on homepage

- ibis/backends/snowflake/__init__.py
This PR refactors a bit of IO code in snowflake to sort column names inside the warehouse instead of on the client.
> refactor(snowflake): sort column names in the database instead of on the client

- docs/backends/impala.qmd
- ibis/backends/base/sql/__init__.py
This PR brings the impala backend back into the fold of backend docs and provides an example of how to handle rendering API docs directly with quartodoc APIs.
> chore: bring impala back into the backend fold

- docs/_quarto.yml
- docs/backends/impala.qmd
- docs/concepts/internals.qmd
- docs/posts/_metadata.yml
- ibis/backends/base/sql/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/pyspark/client.py
- ibis/config.py
- ibis/expr/api.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/parse.py
- ibis/expr/datatypes/value.py
- ibis/expr/schema.py
- ibis/expr/types/arrays.py
- ibis/expr/types/core.py
- ibis/expr/types/generic.py
- ibis/expr/types/groupby.py
- ibis/expr/types/numeric.py
- ibis/expr/types/relations.py
- ibis/expr/types/strings.py
- ibis/expr/types/structs.py
- ibis/expr/types/temporal.py
- ibis/legacy/udf/vectorized.py
- ibis/selectors.py
- ibis/util.py
- justfile
- lychee.toml
This PR fixes the remaining interlinks between ibis documentation and itself and links to inventories like the core Python docs.
> docs: fix self and external links

- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_parse.py
Hypothesis has discoreved this bug in another PR: https://github.com/ibis-project/ibis/actions/runs/6059728425/job/16443137662?pr=6876#step:11:121
Parsing expects a different parameter order as the formatting produces.
> fix(dtypes): switch scale and timestamp parameter order when formatting a timestamp datatype

- ibis/expr/types/generic.py
- ibis/expr/types/groupby.py
- ibis/expr/types/maps.py
- ibis/expr/types/structs.py
- ibis/selectors.py
Fixes some missing imports and improves the group_by.mutate example. Extracted from #7027.
> docs: fix more internal API docs links and improve `group_by` mutate example

- docs/_tabsets/install.qmd
this should fix to links to the connection docs (removing the `.qmd`)
> docs: fix links from install to connect

- docs/tutorials/ibis-for-sql-users.qmd
Moves the SQL users tutoral to use `ibis.to_sql` which will render the SQl strings with syntax highlighting.
> chore: render sql using the notebook instead of only printing to stdout

- docs/backends/duckdb.qmd
This PR replaces the code annotations in the DuckDB backend docs with their standard prose equivalents.
> chore(docs): remove code annotations from duckdb backend docs

- ibis/tests/benchmarks/test_benchmarks.py
Fixes a failing benchmark test.
> test(benchmark): adjust duckdb parsing benchmark to account for removed top-level parse function

- docs/_renderer.py
- ibis/backends/base/df/timecontext.py
- ibis/backends/dask/execution/util.py
- ibis/backends/impala/__init__.py
- ibis/backends/pandas/aggcontext.py
- ibis/backends/pandas/execution/util.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/client.py
- ibis/expr/api.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
- ibis/legacy/udf/vectorized.py
This PR fills out our docstring examples renderer to actually leverage quarto to run the examples and make the output look super nice. I had to cook up some custom docstring example comment markers because quartodoc (maybe griffe?) erases `doctest: ` indicators before passing the code to the renderer. Eventually we may want to upstream this renderer to quartodoc if the idea make sense and is not burdensome to maintain.
> docs: add fancy renderer for docstring examples

- ibis/expr/operations/generic.py
- ibis/tests/test_strategies.py
Fail to spuriously convert deferred objects to literal values.
Closes #7051.
> fix(api): ensure that deferred objects cannot be converted into literals

- .gitattributes
- docs/_extensions/machow/interlinks/interlinks.lua
Addresses https://github.com/machow/quartodoc/pull/268 until that is in a release.
Since we're likely going to encounter extension issues in the future I've turned off considering extension code generated.
> chore(quarto-preview): avoid trying to process `nil` value when API docs do not exist

- docs/_quarto.yml
we should consider switching to `main` as the default branch; the `repo-subdir` will be needed either way
docs: https://quarto.org/docs/websites/website-navigation.html#github-links
> docs: fix edit this page button

- docs/how-to/analytics/basics.qmd
this was the change I wanted to edit through the browser! removes a single stray bracket in a how-to guide
> docs: remove stray bracket

- docs/_tabsets/install.qmd
A small change in the installation tabset.
The `ibis.{backend_name}.connect` anchor has the sample connection strings and is located directly above the `do_connect` anchor we're currently linking to.
> docs(install): point to `connect` anchor instead of `do_connect`

- ibis/backends/pyspark/compiler.py
- ibis/backends/tests/test_temporal.py
This _might_ fix #7060 -- it gates the usage of the `DayTimeIntervalType` based on the pyspark version.
I can't even get pyspark 3.2 to start a session on my laptop, so this is untested locally.
> fix(pyspark): gate datediff op to restore pyspark 3.2 support

- docs/concepts/internals.qmd
The previous link goes to a page that says the resource has moved, so I updated the link to that resource.
> docs: update link to sqlalchemy tutorial

- docs/concepts/versioning.qmd
Brings back the versioning policy under `concepts/`
> docs: bring back versioning policy doc

- docs/_quarto.yml
This PR hides some datatypes in the relevant API docs
> docs: hand roll `datatypes.core` APIs to avoid documenting private types

- docs/_quarto.yml
This PR moves column selector API docs closer to where they are more likely to come up.
> docs: move column selectors closer to relevant expression page

- .github/workflows/ibis-backends.yml
If you do, you can get things like:
```
Run poetry run pip install "apache-flink grpcio-status"
ERROR: Invalid requirement: 'apache-flink grpcio-status'
```
> ci: do not quote joined arguments to `pip install`

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
- Adds an `extensions` option to `ibis.duckdb.connect` for automatically installing/loading extensions by name on connect
- Adds a `con.load_extension` method for installing/loading an extension on an existing connection
~Still needs tests, will finish up tomorrow.~
Fixes #7063.
> feat(duckdb): expose loading extensions

- docs/index.qmd
meant to do this pre-merge -- Streamlit doesn't really fit into the category of visualization of the rest; we have a how-to elsewhere; this app is sluggish and from my personal accounts (and goes down frequently) so we shouldn't have it on the front page
edit: oh and the post it links to is hidden and needs a full rewrite
> docs: remove streamlit app on front page

- docs/concepts/internals.qmd
- docs/concepts/versioning.qmd
I'll open a separate issue for a style guide; this updats two places on capitalization to match the rest of the website
> docs: minor consistency on capitalization of concept docs

- ibis/backends/flink/registry.py
The SQLAlchemy backend's `ops.Radians` implementation works on Flink, but the `ops.Degrees` translation doesn't. For whatever reason, `SELECT 180 * CAST(5.556 AS DOUBLE) / pi()` causes casting errors, but `SELECT power(pi(), -1) * 180 * CAST(5.556 AS DOUBLE)` doesn't. However, rather than rewrite the arithmetic, we can just use the built-in method, and do the same for `ops.Radians` for consistency.
> refactor(flink): use built-in `DEGREES`, `RADIANS`

- .envrc
- ci/schema/clickhouse.sql
- ci/schema/druid.sql
- ci/schema/mssql.sql
- ci/schema/mysql.sql
- ci/schema/oracle.sql
- ci/schema/oracle/astronauts.ctl
- ci/schema/oracle/awards_players.ctl
- ci/schema/oracle/batting.ctl
- ci/schema/oracle/diamonds.ctl
- ci/schema/oracle/functional_alltypes.ctl
- ci/schema/postgres.sql
- ci/schema/snowflake.sql
- ci/schema/sqlite.sql
- ibis/backends/base/sql/alchemy/query_builder.py
- ibis/backends/conftest.py
- ibis/backends/flink/tests/test_ddl.py
- ibis/backends/sqlite/tests/conftest.py
- ibis/backends/tests/base.py
- ibis/backends/tests/test_dot_sql.py
- nix/overlay.nix
This PR address the removal of `ORDER BY` clauses that is happening due to an unnecessary extra projection on sqlalchemy relations. The fix is to return early when no `select_set` is collected. Closes #7050.
> fix(sql): avoid reselecting relations to prevent dropping order by clauses

- docs/backends/_templates/api.qmd
- docs/backends/_utils.py
- docs/backends/bigquery.qmd
- docs/backends/clickhouse.qmd
- docs/backends/dask.qmd
- docs/backends/datafusion.qmd
- docs/backends/druid.qmd
- docs/backends/duckdb.qmd
- docs/backends/mssql.qmd
- docs/backends/mysql.qmd
- docs/backends/oracle.qmd
- docs/backends/pandas.qmd
- docs/backends/polars.qmd
- docs/backends/postgresql.qmd
- docs/backends/pyspark.qmd
- docs/backends/snowflake.qmd
- docs/backends/sqlite.qmd
- docs/backends/trino.qmd
- docs/styles.css
This PR brings back generated backend API documentation that was lost in the quarto-ization.
Closes #6999.
Closes #7076.
> docs: bring back backend API documentation

- ibis/backends/tests/test_array.py
- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
- ibis/expr/operations/arrays.py
- ibis/expr/types/arrays.py
- ibis/tests/expr/test_value_exprs.py
> fix(api): support passing `functools.partial` to array `.map`/`.filter` methods

- ibis/backends/flink/registry.py
Necessary to fix `ibis/backends/tests/test_numeric.py::test_trig_functions_columns`.
> feat(flink): implement translation of `NULLIFZERO`

- ibis/backends/base/sql/registry/literal.py
- ibis/backends/clickhouse/compiler/values.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/value.py
- ibis/expr/types/inet.py
- ibis/expr/types/uuid.py
- ibis/formats/numpy.py
Removes String* as a parent class of other types. This is technically a breaking change, ~though we do not have any coverage of these that I could see.~ We have some coverage of the data type changes by way of literal normalization.
> refactor(api): remove string as a parent type from expression API

- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Previously passing a too-nested-list with a valid column name to `Table.select` would result in ibis trying (and failing) to "windowize" the expression. We now handle `.select` argument coercion more uniformly, and error appropriately if any of the arguments fail to coerce to an `Expr`.
Fixes #7039.
> fix(api): improve error message for bad arguments to `Table.select`

- docs/styles.css
Ensure that all parameters tables overflow with a horizontal scrollbar if necessary.
> docs: ensure that all parameters elements overflow with a scrollbar

- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends-skip-helper.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-docs-lint.yml
- .github/workflows/ibis-main-skip-helper.yml
- .github/workflows/ibis-main.yml
- .github/workflows/ibis-tpch-queries-skip-helper.yml
- .github/workflows/ibis-tpch-queries.yml
- .github/workflows/nix-skip-helper.yml
- .github/workflows/nix.yml
A bit of github actions cleanup after the great quarto-ization.
> ci: remove unused branches and ignore envrc file

- docs/backends/duckdb.qmd
Removes a bogus duckdb code annotation
> docs: remove duckdb code annotations

- docs/backends/impala.qmd
- ibis/backends/impala/__init__.py
Hello,
At the moment it is not possible to pass arbitrary keyword arguments to Impala backend, which makes it impossible to connect if, for example, Impala is configured to use HTTP transport. It should be possible to supply any arguments required by Impyla. I tested this on Impala (with S3) and both querying and table creation worked fine.
I also added one more example of how a connection can be created, which I think is more realistic to what users encounter in practice, especially with CDP. As hdfs_client is optional and not relevant to S3 setups I purposely leave it out from this example.
p.s. I closed [!7116](https://github.com/ibis-project/ibis/pull/7116) because I was having trouble rebasing my commits, hopefully commitlint will not complain anymore.
> fix(impala): allow arbitrary connection params

- ibis/backends/tests/test_generic.py
- ibis/common/annotations.py
- ibis/common/grounds.py
- ibis/common/patterns.py
- ibis/common/tests/snapshots/test_annotations/test_annotated_function_without_decoration/error.txt
- ibis/common/tests/snapshots/test_annotations/test_signature_from_callable_with_keyword_only_arguments/missing_a_required_argument.txt
- ibis/common/tests/snapshots/test_annotations/test_signature_from_callable_with_keyword_only_arguments/too_many_positional_arguments.txt
- ibis/common/tests/snapshots/test_annotations/test_signature_from_callable_with_positional_only_arguments/parameter_is_positional_only.txt
- ibis/common/tests/snapshots/test_grounds/test_error_message/error_message.txt
- ibis/common/tests/snapshots/test_grounds/test_error_message/error_message_py311.txt
- ibis/common/tests/test_annotations.py
- ibis/common/tests/test_grounds.py
- ibis/common/tests/test_patterns.py
- ibis/common/typing.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_core.py
- ibis/expr/operations/core.py
- ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call0-missing_a_required_argument/missing_a_required_argument.txt
- ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call1-too_many_positional_arguments/too_many_positional_arguments.txt
- ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call2-got_an_unexpected_keyword/got_an_unexpected_keyword.txt
- ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call3-multiple_values_for_argument/multiple_values_for_argument.txt
- ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call4-invalid_dtype/invalid_dtype.txt
- ibis/expr/operations/tests/snapshots/test_generic/test_error_message_when_constructing_literal/call5-unable_to_normalize/unable_to_normalize.txt
- ibis/expr/operations/tests/test_core.py
- ibis/expr/operations/tests/test_generic.py
- ibis/tests/expr/test_table.py
- ibis/tests/expr/test_window_frames.py
Currently we have really cryptic, hard to interpret error messages:
```py
class Example(Annotable):
a: int
b: int = 0
c: str = "foo"
d: Optional[float] = None
e: tuple[int, ...] = (1, 2, 3)
f: As[int] = 1
Example("1", "2", "3", "4", "5", [])
```
Previously we raised
```
'1' doesn't match InstanceOf(type=<class 'int'>)
```
After this change we have the additional information to construct the error message: 
- pattern used for validation
- mismatched value
- argument/field the validation failed on
- annotable class failed to construct
Currently this PR produces the following error message:
```py
Example('1', '2', '3', '4', '5', []) has failed due to the following errors:
`a`: '1' is not an int
`b`: '2' is not an int
`d`: '4' is not either None or a float
`e`: '5' is not a tuple of ints
`f`: …
```
> refactor(common): improve error messages raised during validation

- .github/workflows/ibis-docs-lint.yml
This PR moves our benchmark data processing away from gh-pages and dumps to a GCS bucket on every push to `master`. After this I would like to scrub the `gh-pages` branch of benchmark data to reduce the size of the ibis repo and thus the time it takes to clone the repo.
> ci: dump benchmark data to gcs bucket

- docs/backends/impala.qmd
- ibis/backends/pandas/aggcontext.py
This PR cleans up some old-style `ibis.schema` API calls.
> docs: remove old-style schema construction from examples and docstrings

- ibis/backends/druid/__init__.py
- ibis/backends/druid/datatypes.py
- ibis/backends/duckdb/registry.py
- ibis/backends/tests/test_string.py
- poetry.lock
- pyproject.toml
Address doubly escaped percent signs in the duckdb backend, by bumping the lower bound of duckdb. Fixes #7103.
Apparently druid was broken here too, fixed that as well.
> fix(duckdb): remove hack to workaround bug that was fixed upstream

- ibis/backends/flink/registry.py
Nit: Is there a reason why the default translation of `ops.RandomScalar` for SQL backends is `rand(utc_to_unix_micros(utc_timestamp()))` (originally from https://github.com/ibis-project/ibis/pull/5558/files), instead of that being a specific implementation for Impala? The way I understand it, Impala has the unique behavior of always returning the same values for `rand()`, so you need to essentially randomize the seed, but this shouldn't be necessary for most backends?
> fix(flink): translate `ops.RandomScalar` to `rand`

- docs/_quarto.yml
Just some nits:
- Only have expressions in the Expressions section
- Only 3 main sections: Expressions, Other, and Configuration
- Sort expressions by usefulness/prevalence: table, generic, numeric/string
- Sort the "Other API" section by my opinion of usefulness/prevalence, but not as sure here.
- Rename Complex to Collections
- Improve descriptions for some pages
> docs: re-organize reference sections

- ibis/examples/__init__.py
- ibis/examples/tests/test_examples.py
For illustrative purposes, especially when using `.sql` methods, having
examples tables named the same as the example reduces setup code.
> feat(examples): name examples tables according to example name

- ibis/backends/pyspark/compiler.py
- ibis/backends/tests/test_udf.py
- ibis/backends/tests/test_vectorized_udf.py
Enable the new scalar UDF API for the PySpark backend. Closes #6322.
> feat(pyspark): enable the new scalar UDF API

- ibis/backends/flink/registry.py
- ibis/backends/flink/translator.py
For whatever reason, tests with both `upper` and `lower` fail with the base SQL translation:
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
Using --randomly-seed=236677405
rootdir: /workspaces/ibis
configfile: pyproject.toml
plugins: repeat-0.9.1, xdist-3.3.1, hypothesis-6.80.0, cov-4.1.0, httpserver-1.0.6, randomly-3.12.0, snapshot-0.0.0, benchmark-4.0.0, mock-3.11.1, clarity-1.0.1
collected 2538 items / 2532 deselected / 6 selected
ibis/backends/tests/test_numeric.py ...FFF                               [100%] …
```
> fix(flink): rewrite `ops.Clip` using if statements

- ibis/backends/flink/registry.py
`UNIX_SECONDS` doesn't exist in Flink AFAIK, and I don't see this code being used anywhere. Looks like it may have been accidentally copied from the BigQuery backend or something.
> fix(flink): remove broken, untested `epochseconds`

- ibis/backends/bigquery/registry.py
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_hash/binary/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_hashbytes/md5-test-binary/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_hashbytes/sha1-test-binary/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_hashbytes/sha256-test-binary/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_hashbytes/sha512-test-binary/out.sql
Clean up the bigquery backend literal translation. For some reason we had
a branch that checked whether the op was a literal, which is unnecessary since
by definition that is true.
> refactor(bigquery): clean up literal handling

- ibis/common/grounds.py
- ibis/expr/operations/relations.py
- ibis/tests/benchmarks/test_benchmarks.py
This PR is ~a draft of~ a fix for #7124.
There are at least four issues, two of which are addressed in this PR.
1. For giant set operations, like a nested union of 400 tables with another
giant union, the schema was computed dynamically, resulting in a traversal
of that entire 400 deep set on every access. I've replaced all the schema `@property`
with `@attribute` where possible (e.g., not joins because `__init__`
can affect the result and `@attribute` is computed on construction).
This effectively removes the traversal at the cost of some additional memory
used to store the `Schema` object on each relation.
2. The second problem is the recursion in `__cached_equals__` and is somewhat
related to the first.
Here, the stack builds rapidly due to `__eq__` being called for hash
collision …
> perf(ops): allow larger table sets in expressions

- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_sql.py
- ibis/backends/trino/compiler.py
- ibis/backends/trino/registry.py
Fixes a bug in the Trino backend when accessing fields on an `array<struct<...>>`.
> fix(trino): differentiate between a single column struct and a column when chaining unnest expressions with field accesses

- .gitignore
- justfile
opening for discussion -- I think just chat would be a very convenient command when working in the repo to instantly open Zulip chat in the terminal
should probably adjust the justfile to pass through args (note some of the themes don't seem to work out of the box on Mac) and add to dev-requirements or something (note 3.11 is not supported on released versions, I'm installing from git+https://)
> feat: just chat to open Zulip in terminal

- README.md
- docs/posts/ibis-version-4.0.0-release/index.qmd
I should have checked before the last PR. feel free to reword, I took the liberty of removing the link to Twitter/X and StackOverflow from the README.md. if there's no objection, I'd like to keep GitHub + Zulip as the primary two channels of information and recommendations for community stuff
> docs: remove final instances of gitter

- .github/workflows/ibis-backends.yml
Should have been dropped in #6877
> ci(flink): don't generate now-unused 3.10 lockfile

- README.md
- docs/_quarto.yml
- docs/index.qmd
- docs/posts/ibis-version-4.0.0-release/index.qmd
updates to use a join-as-member link that never expires, my bad on missing this earlier
> docs: fix zulip link for new members

- .github/workflows/ibis-backends-cloud.yml
Avoid cancelling jobs in the same concurrency group
> ci(cloud): avoid cancelling jobs

- docs/_quarto.yml
- docs/index.qmd
I had added these, now invitation requirement is removed, removing these
> docs: remove extra bits in zulip links

- .github/workflows/ibis-backends-cloud.yml
We create a schema for snowflake tests per python version, so allowing e.g., 3.9 and 3.11 to run concurrently is okay.
> ci(snowflake): allow concurrent python version tests to run

- docker-compose.yml
Oracle 23.3 seems to have [some issues](https://github.com/ibis-project/ibis/actions/runs/6296921012/job/17092938287) with dropping existing tables related to timezone information. This PR pins our version to 23.2 to avoid flaky ci until we understand the issue.
> ci(oracle): pin database version until flakiness can be fixed

- ibis/backends/base/sql/compiler/translator.py
- ibis/backends/clickhouse/compiler/values.py
- ibis/backends/flink/registry.py
- ibis/backends/polars/compiler.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/tests/test_numeric.py
- ibis/expr/types/numeric.py
Ensure that NULLs are propagated through `clip`
Fixes #7168.
> fix(clip): preserve nulls when clipping

- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
Support sequences in the right hand side of replacements:
```py
from ibis.common.patterns import Replace, Variable
a = Variable("a")
r = Replace(searcher, (1, 2, a))
```
Added a new decorator based syntax for defining replacement rules:
```py
from ibis.common.patterns import replace
@replace(searcher)
def substitute(value, context):
```
Miscellaneous changes:
- renamed `Builder.make()` method to `Builder.build()`
- use `Base.__create__()` instead of `__new__()`
> feat(patterns): support building sequences in replacement patterns

- ibis/backends/oracle/__init__.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_dot_sql.py
> fix(oracle): ensure that metadata queries use SQL and not sqlplus-specific syntax

- ibis/backends/base/sql/compiler/base.py
- ibis/common/bases.py
- ibis/common/caching.py
- ibis/common/collections.py
- ibis/common/graph.py
- ibis/common/grounds.py
- ibis/common/patterns.py
- ibis/common/temporal.py
- ibis/common/tests/test_bases.py
- ibis/common/tests/test_collections.py
- ibis/common/tests/test_graph.py
- ibis/common/tests/test_grounds.py
- ibis/common/tests/test_grounds_benchmarks.py
- ibis/common/tests/test_patterns.py
- ibis/expr/operations/core.py
- ibis/expr/operations/generic.py
Almost all of the ibis objects have been extending `ABC` which hooks into the instance and subclass checks making the very common `isinstance()` calls more expensive. It had a significant impact based on occasional code profilings. 
I was thinking on how could we avoid the performance impact on instance checks while keep supporting the handy abstract methods and properties. Turns out that we can easily mitigate `ABC`'s overhead by setting the `__abstractmethods__` attribute for the created types and the python internals automatically raises the "Can't instantiate abstract class Foo with abstract methods bar, foo" error. This way we provide our own, less flexible abstract base classes using the python builtin isinstance checks.
On direct isinstance checks against base classes the …
> perf: introduce quicker abstract base classes

- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
Reopened version of #7218 with a fix for infinite recursion in case of string inputs.
Support sequences in the right hand side of replacements:
```py
from ibis.common.patterns import Replace, Variable
a = Variable("a")
r = Replace(searcher, (1, 2, a))
```
Added a new decorator based syntax for defining replacement rules:
```py
from ibis.common.patterns import replace
@replace(searcher)
def substitute(value, context):
```
Miscellaneous changes:
- renamed `Builder.make()` method to `Builder.build()`
- use `Base.__create__()` instead of `__new__()`
> feat(patterns): support building sequences in replacement patterns       

- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
Currently both patterns and builders must be hashable, so the mapping passed must be a FrozenDict. 
We can possibly lift the hashable requirement in the future.
> fix(patterns): support passing mappings to Getitem builder

- ibis/expr/api.py
- ibis/expr/deferred.py
- ibis/expr/tests/test_deferred.py
- ibis/tests/expr/test_temporal.py
- ibis/tests/expr/test_timestamp.py
- ibis/tests/expr/test_value_exprs.py
This PR does a few things:
- Adds full support for deferred expressions passed to `ibis.date`/`ibis.time`/`ibis.timestamp`
- Adds a new `deferrable` decorator (non-public) for wrapping top-level expr functions and making them work with deferred arguments.
- Improves the docstrings of `ibis.date`/`ibis.time`/`ibis.timestamp`
- Improves the type-signatures of `ibis.date`/`ibis.time`/`ibis.timestamp`. In particular, now mypy/pyright will complain if you don't pass in all components required or the components are the incorrect type. It also fixes the return type to indicate it's not always a scalar.
Fixes #4534.
> feat(api): support deferred expressions in `ibis.date`/`ibis.time`/`ibis.timestamp`

- ibis/expr/types/relations.py
- ibis/tests/expr/test_relocate.py
Fixes #7225.
```
In [10]: from ibis.interactive import *
In [11]: t = ibis.examples.penguins.fetch()
In [12]: t.relocate("year", s.numeric()).columns
Out[12]:
['year',
'bill_length_mm',
'bill_depth_mm',
'flipper_length_mm',
'body_mass_g',
'species',
'island',
'sex']
In [13]: t.relocate(s.numeric(), "year").columns
Out[13]:
['bill_length_mm',
'bill_depth_mm',
'flipper_length_mm',
'body_mass_g',
'year',
'species',
'island',
'sex']
```
> fix(api): ensure the order of duplicate non-renamed columns in `relocate` is preserved

- ibis/expr/deferred.py
- ibis/expr/tests/test_deferred.py
This makes `Column`/`Scalar` values found in a deferred expression repr as `<column[type]>`/`<scalar[type]>`. Previously they'd repr using their standard repr, which would lead to weird displays (especially in interactive mode).
Example:
```python
In [2]: from ibis import _
In [3]: t = ibis.table({"x": "int"})
In [4]: ibis.date(_.h, _.m, t.x.sum())
Out[4]: date(_.h, _.m, <scalar[int64]>)
```
> feat(api): improve repr for deferred expressions containing Column/Scalar values

- ibis/expr/operations/udf.py
- ibis/tests/expr/test_udf.py
```python
In [2]: from ibis import _
In [3]: @ibis.udf.scalar.builtin
...: def myfunc(x: int) -> int:
...:     pass
...: 
In [4]: myfunc(_.x)
Out[4]: myfunc(_.x)
```
> feat(api): support deferred arguments to udfs

- docs/_quarto.yml
- ibis/backends/base/__init__.py
- ibis/expr/api.py
- ibis/expr/types/relations.py
This is a followup per #7141
- Move every datatype-specific API out of the top-level section. eg ibis.array() got moved to collections section
- Now only backend-specific stuff got left in the top-level section. Therefore, I renamed it to "Connections API".
In addition to these high-level changes, also a few tweaks:
- soft deprecate ibis.where
- fix ibis.ifelse docstring (plenty other functions like this are still missing docstrings, but at least the existing ones should be correct)
- import ibis in a doctest to prevent a rendering failure. This was little weird. This wasn't failing before only due to the ordering of this function in the larger API tab. All of the members in a a quartodoc section get squashed into a single .qmd file. Then quarto goes through and evaluates all the …
> Docs: Reorganize reference v2

- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
Fixes a missing `f` for an f-string.
> fix(patterns): fix pattern mismatch error for default `Pattern`

- ibis/expr/api.py
This method wasn't exposed in the `ibis` namespace (nor documented), so there's no need to deprecate it IMO.
> refactor: delete unexposed `ibis.api.category_label` function

- ibis/backends/flink/__init__.py
- ibis/backends/flink/compiler/core.py
- ibis/backends/flink/ddl.py
- ibis/backends/flink/registry.py
- ibis/tests/benchmarks/test_benchmarks.py
Allows use of `pytest -m "not pyflink"` to avoid collection failures.
> test(dev-tools): allow skipping flink with pytest markers

- ibis/backends/base/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_export.py
- ibis/expr/types/core.py
Adds a `to_pandas_batches` for returning an iterator of pandas DataFrames from expression execution. Closes #6805.
> feat(api): add `to_pandas_batches`

- ibis/expr/api.py
- ibis/expr/builders.py
- ibis/tests/expr/test_case.py
- Adds support for case expressions in `ibis.case()` statements. Support is _not_ added for `Column.case()` statements, since it's not clear what the `_` would refer to there or when it would resolve.
- Improves docstrings and type annotations for case builders. In particular these APIs now pass `mypy`.
- Refactors the `CaseBuilder` implementations. The code shared between implementations was small, and since `SimpleCaseBuilder` doesn't support deferreds while `SearchedCaseBuilder` does it felt cleaner to me to fully split the implementations.
> feat(api): support deferred arguments in `ibis.case()`

- ibis/backends/dask/execution/numeric.py
- ibis/backends/dask/tests/execution/test_functions.py
- ibis/backends/dask/tests/execution/test_operations.py
- ibis/backends/pandas/execution/generic.py
- ibis/backends/pandas/tests/execution/test_functions.py
- ibis/backends/pandas/tests/execution/test_operations.py
- ibis/backends/postgres/registry.py
- ibis/expr/operations/reductions.py
- ibis/expr/types/numeric.py
BREAKING CHANGE: the `interpolation` argument was only supported in the dask and pandas backends; for interpolated quantiles use dask or pandas directly
> refactor(api): remove interpolation argument

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/compiler/relations.py
- ibis/backends/tests/test_dot_sql.py
Add `.sql` support for ClickHouse. Closes #6698.
> feat(clickhouse): add support for `.sql` methods

- docs/_quarto.yml
- docs/support_matrix.qmd
closes #7257
adds some prose explaining the page and why backends aren't all at 100%
> docs: add some prose and move operation support matrix

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_datatypes.py
- poetry.lock
- pyproject.toml
Removes unnecessary version checking from the duckdb backend due to increasing the lower bound to 0.8.1 in previous PR.
> chore(deps): remove `packaging` requirement for the duckdb backend

- ibis/expr/builders.py
- ibis/expr/deferred.py
- ibis/expr/operations/generic.py
- ibis/expr/tests/test_deferred.py
- ibis/expr/types/arrays.py
- ibis/expr/types/generic.py
- ibis/expr/types/maps.py
- ibis/expr/types/structs.py
- ibis/tests/expr/test_case.py
- ibis/tests/expr/test_value_exprs.py
- Adds support for passing deferred arguments to `ibis.array`/`ibis.map`/`ibis.struct`
- Adds support for traversing builtin collections (`list`, `tuple`, `dict`, `set`) when detecting `Deferrred` arguments to `deferrable` functions
- Refactors the deferred case implementation to use `deferrable` instead of a custom `Deferred` subclass
> feat: support deferred arguments in `ibis.array`/`ibis.map`/`ibis.struct`

- docs/_quarto.yml
Followup to https://github.com/ibis-project/ibis/pull/7159
Make the signatures appear show the full path,
eg `random()` is now `ibis.random()`.
Also fix some of the paths where possible,
eg now it is `ibis.connect()` instead of `backends.base.connect()`
@machow, note how quartodoc was silently ignoring the previously-incorrectly-configured `signature_name` option. It would have been nice if the build had failed here, instead of us thinking that we
had configured something.
See the difference in `ibis.connect()`:
and note how in the sidebar you just see "random", not "ibis.random"
> docs(reference): improve signatures

- codecov.yml
I _think_ this will stop flagging "code not covered" annotations on all
bigquery and snowflake diffs -- those warnings just take up space
because the test suite isn't running those tests on PRs.
> chore(codecov): skip processing bigquery and snowflake codecov

- ibis/expr/api.py
- ibis/expr/schema.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
Just some small things that have been missing from the docs that have been bothering me for a while.
> Improve reference docs

- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/test_connect.py
when `config` is an instance of `SessionContext`, it shouldn't subsequently be used as a config
> fix: datafusion: do_connect: properly handle config-is-actually-context

- ibis/backends/tests/tpch/conftest.py
Decrease TPC-H test duration by avoiding parallelism. This prevents loading data multiple times in the case of duckdb (which seems to be the proximate cause of a large slowdown for these tests), and also prevents high memory usage for Trino.
> test(perf): run all tpch queries in a single process to avoid high memory usage and multiple data loads

- ibis/expr/types/relations.py
- ibis/tests/expr/test_selectors.py
This PR implements selector support in the `.order_by` method
> feat(api): allow selectors in `order_by`

- ibis/expr/types/pretty.py
- ibis/tests/expr/test_pretty_repr.py
Render strings that have at least a scheme and netloc as clickable links in the terminal. This PR does not avoid rendering strings as links if they are truncated. Closes #7292.
> feat(ux): render url strings as links in rich table output

- docs/backends/mysql.qmd
Hi :)
In looking through documentation I found a small typo where connection params under the mysql backend page were showing the mssql params instead.
Hope this PR fixes that
> docs(mysql): render_do_connect mssql to mysql

- ibis/expr/types/pretty.py
- ibis/tests/expr/test_pretty_repr.py
Followup to https://github.com/ibis-project/ibis/pull/7304
Before, long links would take you to the truncated version, eg https://www.super.long.url.that.is.trucated.com
would both display and link to
https://www.super.long.url.tha...
Now it just renders as that, but links to the full url.
This also makes links render in vscode notebook environment. Before, links were rendering correctly in ipython console. But, they weren't
showing up as links in vscode notebook environment either. This commit adds vscode functionality.
> feat(ux): fix long links, add repr links in vscode

- ibis/expr/types/numeric.py
Although users got a deprecationWarning
whenever they used these in code,
in the docs there is no
indication they are deprecated.
Not sure, possibly we could do some hack where we add this
function to the class after the class block, and then
it wouldn't even show up in the documentation?
but probably if a user sees the deprecation warning, they might
want to look up that method on the docs for more info,
so it might be nice if there were something there...
> docs: add deprecation to .nullifzero docstring

- ibis/backends/flink/registry.py
- ibis/backends/flink/tests/snapshots/test_translator/test_translate_complex_filtered_agg/out.sql
- ibis/backends/flink/tests/snapshots/test_translator/test_translate_complex_groupby_aggregation/out.sql
- ibis/backends/flink/tests/snapshots/test_translator/test_translate_count_star/out.sql
- ibis/backends/flink/tests/snapshots/test_translator/test_translate_having/out.sql
- ibis/backends/flink/tests/snapshots/test_translator/test_translate_value_counts/out.sql
This will fix something like `ibis/backends/tests/test_aggregation.py::test_reduction_ops[flink-is_in-count_star]`.
Nit: I also took the liberty of changing `count` to `COUNT`, so that the translated SQL wouldn't be a mix of lowercased keywords and capitalized keywords. I don't know if there's ever been thought around standardizing this; maybe it only bothers me. :)
~This may not be the right long-term solution (`FILTER` syntax has some advantages), but at least this works.~ Update: I went ahead and just used `FILTER` syntax instead, I thought it would be a bigger deal.
> fix(flink): correct the filtered count translation

- ibis/common/bases.py
- ibis/common/grounds.py
- ibis/common/tests/test_bases.py
- ibis/common/tests/test_grounds.py
Separating the two is not worth it since `Base` is used in conjunction with `Abstract` in the rest of the codebase, e.g. `Annotable`. After this PR all of the base classes support abstract methods out of the box.
Performance-wise it only affects the class construction so it should have no "runtime" overhead. Just in case I ran the benchmark for constructing `Concrete` instances:
```
------------------------------------------------------------------------------- benchmark 'test_concrete_construction': 2 tests -------------------------------------------------------------------------------
Name (time in us)                                Min                Max              Mean            StdDev            Median               IQR            Outliers  OPS (Kops/s)            Rounds …
```
> refactor(common): remove `ibis.common.bases.Base` in favor of `Abstract`

- ibis/common/grounds.py
- ibis/common/patterns.py
- ibis/common/tests/test_graph_benchmarks.py
- ibis/common/tests/test_grounds.py
- ibis/common/tests/test_typing.py
- ibis/common/typing.py
`Annotable` haven't been supporting `Self` annotations so far, mostly because is that the type being constructed is not available inside `AnnotableMeta.__new__()` yet. This can be overcome by deferring the type loading using a `LazyInstanceOf` pattern with a `ForwardRef`.
Possible improvement: `LazyInstanceOf` should have an alternative implementation for single type use, currently it is using `lazy_dispatched` which is tailer for a slightly different use case.
> feat(common): support `Self` annotations for `Annotable`

- ibis/backends/flink/__init__.py
- ibis/backends/flink/ddl.py
- ibis/expr/api.py
- ibis/expr/streaming.py
We shouldn't introduce a new module for a single object just yet. If there will be more streaming related construct we can factor them out to a separate module.
> refactor(ir): remove `ibis.expr.streaming`

- ibis/backends/datafusion/compiler.py
- ibis/backends/datafusion/registry.py
This PR is based on this discussion: https://github.com/ibis-project/ibis/discussions/6967
The keys in the `udfs` dictionary are strings because we need to differentiate between signatures (i.e. input types) for the same function. The udf registry of datafusion is only based on the name of the functions.
> refactor(datafusion): create registry of time udfs to create them only once

- ibis/backends/duckdb/registry.py
- ibis/backends/snowflake/converter.py
- ibis/backends/tests/test_json.py
- ibis/backends/tests/test_param.py
- ibis/formats/pandas.py
This PR implements recursive element conversion for arrays, structs, maps and json datatypes, for the pandas execution path. `ToJSONArray` and `ToJSONMap` are also implemented here for DuckDB.
> feat(ux/duckdb): implement recursive collection type conversion for `.execute()`

- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_cast.py
- ibis/expr/datatypes/tests/test_core.py
they were off by an order of magnitude.
added a silly test but it should catch any regressions that arise in future refactors.
> fix(datatypes): correct unsigned integer bounds

- ibis/backends/clickhouse/compiler/core.py
- ibis/backends/clickhouse/compiler/values.py
Use a pattern to convert output of ranked window functions from one-based indexing to zero-based indexing
> refactor(clickhouse): use a pattern for one-to-zero index conversion of ranking window functions

- ibis/backends/base/sql/alchemy/query_builder.py
- ibis/backends/base/sql/compiler/query_builder.py
- ibis/backends/tests/test_client.py
- ibis/backends/trino/compiler.py
I found this bug while refactoring a bit of this code to support `TABLESAMPLE` clauses. In short - the use of `ref_op` and `op` made it confusing which op to use, resulting in broken code for handling self joins on memtables. I renamed the variables to make it clear which `op` was the original operation and which was the `op` being compiled.
> fix: support self joins on memtables

- ibis/backends/postgres/__init__.py
- ibis/expr/operations/udf.py
- Removes unused `*args` argument to udf decorators
- Makes `ibis.udf.scalar.builtin`, `ibis.udf.scalar.python` and `ibis.udf.agg.builtin` compatible with mypy
- Makes `ibis.udf.scalar.pandas` and `ibis.udf.scalar.pyarrow` mypy compatible at _call_ time (so `myudf(1, 2)` will be valid). This does not resolve mypy compatibility of the UDF function definitions themselves. Supporting this will require an addition to the decorators. I'll address this in a follow-up PR.
Partially addresses #7201.
> feat: improve udf mypy compatibiity

- ibis/backends/base/__init__.py
- ibis/tests/test_api.py
- justfile
With `pytest -s` this test case opens a python terminal for me. Apparently the original test case was wrong too since it wasn't running the given `script`
```
❯ pytest -s ibis/tests/test_api.py::test_no_import_pandas
================================================================================================================= test session starts ==================================================================================================================
platform darwin -- Python 3.11.4, pytest-7.4.0, pluggy-1.3.0
Using --randomly-seed=1649009272
rootdir: /Users/kszucs/Workspace/ibis
configfile: …
```
> test: fix pandas import test case

- ibis/backends/impala/tests/snapshots/test_sql/test_join_key_name/out.sql
- ibis/expr/analysis.py
- ibis/expr/operations/logical.py
- ibis/expr/types/relations.py
- ibis/tests/sql/snapshots/test_compiler/test_agg_filter/out.sql
- ibis/tests/sql/snapshots/test_compiler/test_agg_filter_with_alias/out.sql
- ibis/tests/sql/snapshots/test_compiler/test_subquery_where_location/decompiled.py
`_rewrite_filter()` was mostly about the traversal itself, now it can be expressed with a simple pattern:
```py
node.replace(
p.Reduction >> (lambda _: ops.TableArrayView(_.to_expr().as_table()), 
filter=p.Value & ~p.WindowFunction & ~p.TableArrayView & ~p.ExistsSubquery
)
```
> refactor(analysis): remove `_rewrite_filter()` in favor of using replacement patterns

- ibis/backends/duckdb/tests/conftest.py
Currently we download extensions anew for every instantiation of a duckdb client for testing. This makes any extension-using tests very slow due to network latency. While this approach is safe, it makes testing unnecessarily slow. This PR tries to remove this isolation to see if it is still an issue.
> test(duckdb): speed up duckdb parallel tests by avoiding repeated extension downloads

- docker-compose.yml
A few `docker-compose.yml` cleanups
> refactor(docker-compose): clean up unused exposed ports and make envar spec uniform

- ibis/backends/base/sql/compiler/select_builder.py
- ibis/expr/analysis.py
- ibis/tests/expr/test_analysis.py
Apparently we don't require it anymore, I'd guess that the functionality of this function is superseded by sub_immediate_parents().
> refactor(analysis): remove `substitute_parents()`

- ibis/backends/base/sql/compiler/query_builder.py
- ibis/backends/base/sql/compiler/select_builder.py
- ibis/backends/clickhouse/compiler/core.py
- ibis/backends/clickhouse/compiler/relations.py
- ibis/backends/tests/test_generic.py
- ibis/expr/datatypes/value.py
- ibis/expr/rewrites.py
Previously these were hacked in in a few different locations. Now all SQL backends share the same rewrite-rule based implementations, currently stored in a common location in `ibis.expr.rewrites`.
As a side effect, this also adds support for `Table.fillna` to the clickhouse backend.
> refactor(sql): implement `Table.fillna`/`Table.dropna` using rewrite rules

- ibis/backends/duckdb/tests/conftest.py
Should fix the occasionally-failing windows duckdb tests
> ci(duckdb): bring back a faster version of isolated extension downloads

- ibis/backends/bigquery/udf/__init__.py
- ibis/backends/tests/test_export.py
This PR moves the current SQL code setting hack in the BigQuery backend to be a proper argument, so that when nodes are rewritten (and thus reconstructed) the sql string makes it through the process. This is a workaround to get BigQuery UDFs working again. Longer term we should try to roll BigQuery UDFs into the new UDF setup.
> fix(bigquery): move sql code to proper argument

- ibis/backends/oracle/__init__.py
- ibis/backends/oracle/datatypes.py
- ibis/backends/oracle/tests/test_datatypes.py
Need to add a test for the `RAW` and `BLOB` loading and I don't like the fix for the column inference fallback
> feat(oracle): add support for loading Oracle RAW and BLOB types

- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_export.py
- ibis/backends/tests/tpch/snapshots/test_h01/test_tpc_h01/trino/h01.sql
- ibis/backends/tests/tpch/snapshots/test_h02/test_tpc_h02/trino/h02.sql
- ibis/backends/tests/tpch/snapshots/test_h03/test_tpc_h03/trino/h03.sql
- ibis/backends/tests/tpch/snapshots/test_h04/test_tpc_h04/trino/h04.sql
- ibis/backends/tests/tpch/snapshots/test_h05/test_tpc_h05/trino/h05.sql
- ibis/backends/tests/tpch/snapshots/test_h06/test_tpc_h06/trino/h06.sql
- ibis/backends/tests/tpch/snapshots/test_h07/test_tpc_h07/trino/h07.sql
- ibis/backends/tests/tpch/snapshots/test_h08/test_tpc_h08/trino/h08.sql
- ibis/backends/tests/tpch/snapshots/test_h09/test_tpc_h09/trino/h09.sql
- ibis/backends/tests/tpch/snapshots/test_h10/test_tpc_h10/trino/h10.sql
- ibis/backends/tests/tpch/snapshots/test_h11/test_tpc_h11/trino/h11.sql
- ibis/backends/tests/tpch/snapshots/test_h12/test_tpc_h12/trino/h12.sql
- ibis/backends/tests/tpch/snapshots/test_h13/test_tpc_h13/trino/h13.sql
- ibis/backends/tests/tpch/snapshots/test_h14/test_tpc_h14/trino/h14.sql
- ibis/backends/tests/tpch/snapshots/test_h15/test_tpc_h15/trino/h15.sql
- ibis/backends/tests/tpch/snapshots/test_h16/test_tpc_h16/trino/h16.sql
- ibis/backends/tests/tpch/snapshots/test_h17/test_tpc_h17/trino/h17.sql
- ibis/backends/tests/tpch/snapshots/test_h18/test_tpc_h18/trino/h18.sql
- ibis/backends/tests/tpch/snapshots/test_h19/test_tpc_h19/trino/h19.sql
- ibis/backends/tests/tpch/snapshots/test_h20/test_tpc_h20/trino/h20.sql
- ibis/backends/tests/tpch/snapshots/test_h21/test_tpc_h21/trino/h21.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/trino/h22.sql
- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/test_client.py
This PR fixes [an issue](https://github.com/ibis-project/ibis/issues/7354#issuecomment-1761439271) with Trino with the following undesirable behavior
```python
con = ibis.trino.connect() # default parameters
t = con.table("table_properties", schema="system.metadata") # fails
t = con.table("table_properties", schema="system.metadata") # succeeds
```
The first assignment to `t` fails because the `finally` handler in `_use_stmt` was
trying to roll back to the current schema and database, but `connect` has
no default database or schema (which is a valid operating mode for Trino clients).
However, it's not valid to roll back to an empty database or schema.
The second assignment to `t` **succeeds** because during the first assignment
we `USE system.metadata` so the finally handler has something …
> fix(trino): remove stateful `USE` pattern for cross-schema table compilation

- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_compile_toplevel/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_set_operation/difference/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_set_operation/intersect/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_set_operation/union_all/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_set_operation/union_distinct/out.sql
Regenerate some failing bigquery test snapshots. I think this is due to [these lines](https://github.com/ibis-project/ibis/pull/7377/files#diff-ff7982dc41d280b20e266548b77f73ce378fc7d859b88192e8e3f07e63af75aaR131-R132) from #7377. Previously we unconditionally produced an alias in the string compiler, in that PR we only produce one if the the retrieved reference does not match the alias
> chore(bigquery): regenerate sql

- ibis/backends/duckdb/tests/conftest.py
A race condition in downloading extensions [still seems to be an issue on Windows](https://github.com/ibis-project/ibis/actions/runs/6551379268/job/17792455543). Bringing back preloading (one of the things we did before) should avoid downloading extensions in tests that aren't explicitly testing installing/downloading extensions.
> test(duckdb): preload extensions to avoid race condition

- ibis/expr/types/relations.py
This PR fixes a test whose success seems to depend on the direction the wind is blowing. Sorting by the `wool` column should address this.
> test(doctest): sort `pivot_wider` case that occasionally fails in CI

- ibis/backends/bigquery/client.py
Remove an unused object from the BigQuery backend.
> refactor(bigquery): remove unused `BigQueryTable` object

- docker-compose.yml
- justfile
Make the healthcheck policy easier to understand by removing timeouts and only using retry count plus healthcheck retry intervals. Also fixes an incorrectly specified dependency betweeen kudu and kudu-tserver: `kudu-tserver` should depend on `kudu`, not the other way around.
> ci(docker): allow containers to start up a bit faster if possible

- ibis/backends/base/__init__.py
- ibis/backends/base/sql/__init__.py
- ibis/backends/base/sql/alchemy/__init__.py
- ibis/backends/base/sql/alchemy/query_builder.py
- ibis/backends/base/sql/compiler/query_builder.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/compiler/relations.py
- ibis/backends/druid/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/impala/client.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/client.py
- ibis/backends/trino/tests/test_client.py
- ibis/expr/operations/relations.py
- ibis/tests/expr/mocks.py
Add a `Namespace` object for dealing with database hierarchies in the cross-schema backends. Fixes #7398.
> fix(trino): enable passing the `database` argument when accessing tables

- ibis/backends/datafusion/compiler.py
- ibis/backends/datafusion/registry.py
- ibis/backends/datafusion/tests/test_temporal.py
- ibis/backends/tests/test_temporal.py
This PR adds:
- TimestampTruncate for the defined precisions in DataFusion
- The missing missing tests suggested in [here](https://github.com/ibis-project/ibis/pull/7320#discussion_r1354650753), and also the corresponding bug fixes.
> feat(datafusion): add TimestampTruncate / fix broken extract time part functions

- ibis/backends/bigquery/__init__.py
- ibis/backends/tests/test_array.py
After moving the pretty table printing to use `to_pyarrow` this slipped through the cracks. Added a simple test in `test_unnest_complex` that execution works.
> fix(bigquery): apply unnest transformation in other methods that execute SQL

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
Add `attach` and `detach` methods mirroring the [DuckDB syntax](https://duckdb.org/docs/sql/statements/attach.html).
> feat(duckdb): add `attach` and `detach` methods for adding and removing databases to the current duckdb session

- ibis/expr/sql.py
Adds syntax-highlighted output in the IPython console.
> feat(ux): show syntax-highlighted SQL if pygments is installed

- .devcontainer/devcontainer.json
- .devcontainer/updateContent.sh
Add a codespace devcontainer setup for the ibis `getting_started.qmd` tutorial.
I've enabled codespace prebuilds for the ibis repo, so once this is merged to `master` the images will be built and ready for use.
Going forward I would like to keep this codespace configuration extremely minimal: it should contain enough setup to be able to run the `getting_started.qmd` with the VSCode Jupyter extension, nothing more, nothing less.
Things like developer tooling, vim extensions and other customizations should IMO remain out-of-scope. This codespace is focused solely on giving people an environment they can use to try ibis out.
For posterity:
- https://containers.dev/features is where I found the feature for automatically installing the quarto CLI
- I was able to use one of the alpine base …
> docs: setup codespace configuration for `getting_started.qmd` tutorial

- ibis/backends/bigquery/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/conftest.py
Ok, need to add tests for this, but the changes are a bit scattershot and I thought we can use this as a sounding-board for whether we want to go down this path.
The general idea here is:
1. Backends that only have a concept of `database` remain unchanged (`clickhouse`, `druid`, `impala`, `mysql`, `pyspark`, `sqlite`)
2. Backends that allow you to _interact_ with tables in other database -> schema hierarchies now have a `schema` kwarg in `list_tables` to allow fine-grained specification (formalized in `bigquery`, added for `trino`, `mssql`, and `snowflake`, and already present in `duckdb`)
3. Backends that have this hierarchy but don't allow for cross-database operations have a kwarg change from `database` to `schema` -- this unifies the arguments of `list_tables` and `table` for these …
> Update `list_tables` to account for database->schema hierarchy where applicable

- ibis/backends/snowflake/registry.py
- chore(snowflake): remove now-implemented `TimestampBucket` operation
> chore(snowflake): remove now-implemented `TimestampBucket` operation

- ibis/backends/base/sql/alchemy/query_builder.py
- ibis/backends/tests/test_dot_sql.py
Turns out that sqlalchemy does not allow most tabular operations on textual selects without a prior `.select()` call.
Fixes #7415.
> fix(sqlalchemy): ensure that limit on `.sql` calls works

- ibis/backends/base/sqlglot/datatypes.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/duckdb/tests/test_datatypes.py
Add support for seconds, milliseconds, microseconds (the default) and nanoseconds scales in timestamp types.
Closes #7412.
> feat(duckdb): add support for specific timestamp scales

- ibis/expr/operations/udf.py
- ibis/tests/expr/test_udf.py
This adds support for a new `sig` parameter to all udf definition functions. If present, this will be used for determining the UDF signature instead of the function annotations. This can be useful for:
- Users who don't want to make use of annotations
- Programmatic usage, where generating a function with a signature may be tricky
- Pandas or pyarrow udfs where you want the decorated function to be annotated with pandas/pyarrow types, and need another way of expressing the types ibis should use
- Expressing more complicated input/output types than can easily be expressed via python annotations. `sig` accepts anything coercible to an ibis dtype, so struct/map/array types are more easily expressible
Fixes #7201.
> feat(api): support specifying `sig` in udf definitions

- ibis/expr/format.py
- ibis/tests/expr/test_geospatial.py
The `GeoUnaryOp`s are already handled by the rules for the parent
classes, but the `GeoSpatialBinOps` break because they often have an
additional keyword (`distance`) passed in that doesn't get handled by
the existing rule for binary operations.
xref #7427
> fix(repr): add dispatch for repr of GeoSpatialBinOps

- ibis/expr/datatypes/core.py
- ibis/expr/operations/core.py
- ibis/expr/operations/numeric.py
- ibis/expr/operations/reductions.py
- ibis/expr/operations/tests/test_generic.py
Add special coercion paths for non-concrete datatypes like `dt.Floating` and `dt.Integer`.
Resolves https://github.com/ibis-project/ibis/issues/7427
> fix(ir): coerce integers passed to `Value[dt.Floating]` annotated values as `dt.float64`

- ibis/tests/benchmarks/test_benchmarks.py
[Benchmarks for compiling unbound tables](https://github.com/ibis-project/ibis/actions/runs/6652773664/job/18077408762) are now failing (with `XPASS`, yay!) after moving DataFusion to sqlglot. This PR fixes that.
> test(datafusion): enable compile benchmarks for datafusion after move to sqlglot

- ibis/backends/dask/__init__.py
I was looking at the docs and noticed a small typo with the return type specification for Dask Scalar objects. 
I'm not sure if [codespell](https://github.com/codespell-project/codespell) would have caught this one. ✍️
> docs: fix dask compile docstring typo

- ibis/backends/datafusion/compiler/values.py
- ibis/backends/tests/test_aggregation.py
**Note:**
The `how` parameter seems to be ignored in the tests. Moreover, several backends do not define the parameter either. In particular, none of these backends implements it:
- [DuckDB](https://duckdb.org/docs/sql/aggregates.html#statistical-aggregates)
- [Postgres](https://www.postgresql.org/docs/9.4/functions-aggregate.html)
- [Polars](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.corr.html) (mentions degrees of freedom but no `sample` or `population`) 
- [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html)
Does it make sense to have the `how` argument for `corr`?
> feat(datafusion): add corr and covar

- docs/backends/_utils.py
- ibis/backends/dask/__init__.py
- ibis/backends/pandas/__init__.py
- ibis/backends/tests/test_register.py
This adds `read_csv` and `read_parquet` methods to the Pandas and Dask backends.
> feat(pandas, dask): add read_csv and read_parquet

- docs/contribute/03_style.qmd
Must have missed it when I grepped for references to Black.
> docs(style): replace Black with Ruff in guidelines

- pyproject.toml
Gets rid of the warning produced when running `ruff format .`
> chore(style): clean up ruff format warning

- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/compiler/values.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_numeric.py
This PR also fixes the offset, which is available but is broken for `count(*)` with parquet files.
> feat(datafusion): add isnull/isnan operations

- ibis/backends/flink/registry.py
- ibis/backends/tests/test_aggregation.py
Note that this won't work in streaming mode: `APPROX_COUNT_DISTINCT aggregate function does not support yet for streaming.`
However, it works in batch mode, which is also how the test suite is run. (There are also other things that don't work in streaming mode, such as unbounded ordering, that are already implemented in the backend/passing batch tests, so this isn't any different.)
> fix(flink): re-implement `ops.ApproxCountDistinct`

- ibis/backends/clickhouse/compiler/core.py
- ibis/common/deferred.py
- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
- improve the implementation of `PatternSequence` and related supplemental patterns
- `TupleOf` pattern now aligns with `*Of` naming to match sequence of a single pattern rather than a tuple of patterns
- remove reduntand object creation logic for alternative but more performant implementations of certain patterns
- support the unpacking syntax to turn patterns into a `SomeOf` pattern
- short circuit `SequenceOf(Any())` to not traverse over the input sequence
- remove unused `PatternMapping` pattern
> refactor(patterns): support more flexible sequence matching

- ibis/backends/tests/test_aggregation.py
* `test_aggregation.py`
* **notimpl** Backend doesn't support UDFs yet
* **notyet** Backend doesn't support mode aggregation (maybe never?)
* **notyet** Flink doesn't support `ORDER BY` clauses in `JSONARRAY_AGG`
* I tried implementing `ops.ArgMin`/`ops.ArgMax` (modeled on BigQuery and other backends):
```diff
diff --git a/ibis/backends/flink/registry.py b/ibis/backends/flink/registry.py
index 19bd95b61..06a02ad5f 100644
--- a/ibis/backends/flink/registry.py
+++ b/ibis/backends/flink/registry.py
@@ -1,6 +1,6 @@
from __future__ import annotations
-from typing import TYPE_CHECKING
+from typing import TYPE_CHECKING, Literal
import ibis.common.exceptions as com
import ibis.expr.operations as ops
@@ -17,6 +17,21 @@ if TYPE_CHECKING:
operation_registry = base_operation_registry.copy()
+def …
```
> test(flink): revise WIP marks in aggregation tests

- LICENSE.txt
noticed this in the ibis-birdbrain repo, feel free to change directly or suggest other words
> docs: add copyright holders to license

- docs/contribute/01_environment.qmd
The standalone `nix-shell` command doesn't work with the newer `flake` setup.
> docs(contribute): fix instructions for nix environment setup

- ibis/backends/datafusion/compiler/values.py
- ibis/backends/tests/test_temporal.py
Also removes redundant function for StringLength added in a previous [PR](https://github.com/ibis-project/ibis/pull/7500) and improves the arguments of some functions.
> feat(datafusion): add TimestampNow, TimestampFromUNIX, subtract/add operations

- ibis/backends/polars/compiler.py
- ibis/backends/polars/datatypes.py
- ibis/backends/tests/test_string.py
A few improvements:
* Replace `map_elements` lambdas for Capitalize and Repeat with native expressions.
* Gracefully handles various upcoming deprecations (eg: `clip_min/max` → `clip`).
* Fixes start-only slice ("substr-start-only" test now passes).
* Streamlines usage of literal values (`_assert_literal` → `_literal_value`)
* Use explicit "scale" & "precision" param names with `pl.Decimal`, as we may make a breaking change to switch the order in the near-ish future (apparently we are the odd ones out at the moment ;)
> feat(polars): various Polars compiler enhancements

- ibis/backends/base/sql/compiler/translator.py
- ibis/backends/base/sql/registry/aggregate.py
- ibis/backends/base/sql/registry/main.py
- ibis/backends/flink/registry.py
- ibis/backends/flink/translator.py
- ibis/backends/tests/test_aggregation.py
* There were arbitrary (at least, to my untrained eye) discrepancies in how the `WHERE` clause was getting applied to the reduction arguments. In the base SQL implementation, it was only applied to the first argument, whereas it was applied to all arguments in the Alchemy implementation.
* I've adapted some of the logic from the Alchemy implementation, such as enabling casting values to `Int32` before certain aggregations (e.g. `SUM`). I've been very conservative, and only actually turned it on for the Flink backend.
* In general, I've tried to do some refactoring, but keep things as similar to the original code as possible. I'm open to a different approach, if it makes sense, but wanted to be conservative before aligning.
> refactor(sql): align logic for filtered reductions

- ibis/backends/bigquery/registry.py
Fixes a bug that came through in #7482.
> fix(bigquery): avoid trying to filter separator argument to `GroupConcat` operation

- ibis/expr/types/temporal.py
While tesing https://github.com/ibis-project/ibis/issues/7502 I saw that we don't have possible units listed for temporal delta operations. This PR fixes that.
> docs(temporal): add `Literal` annotation to display possible units for `delta` method

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
- ibis/util.py
DuckDB's python client introduced an integration with `fsspec` where you can use
`fsspec` to handle downloads from any supported `fsspec.AbstractFileSystem` and
feed that into various `DuckDB` `read_*` functions.
Upstream docs are here: https://duckdb.org/docs/guides/python/filesystems
The test is pulling from GCS, but it's also a 59 byte file -- if it ends up
being flaky we can always drop it.
Note for future self and other maintainers:
When we normalize filenames before passing them to DuckDB, we compare against a
known "allowlist" of various cloud blob prefixes (like `az`, `gcs`, `s3`, etc.)
If we _don't_ have the appropriate prefix in there, we mangle the URL quite badly.
For now, we can keep that list up-to-date, but we may want to revisit how we're handling that.
> feat(duckdb): allow users to register fsspec filesystem with DuckDB

- .github/workflows/ibis-docs-lint.yml
Converts JSON benchmark data to parquet before uploading to GCS.
> ci: write benchmark data to parquet

- ibis/expr/sql.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_aggregation_with_multiple_joins/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_basic_aggregation/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_basic_aggregation_with_join/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_basic_join/inner/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_basic_join/left/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_basic_join/right/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_basic_projection/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_join_with_filter/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_multiple_joins/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_scalar_subquery/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_simple_reduction/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_simple_select_count/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_table_alias/decompiled.py
- ibis/expr/tests/test_sql.py
- pyproject.toml
Resolves https://github.com/ibis-project/ibis/issues/7516
SQLGlot has a `"condition"` field in the `Join` expression object which hasn't been mapped to an ibis expression previously. It also provides a `projections` field which is omitted for now, we may need to consider another level of projection for that too.
> fix(ir): `ibis.parse_sql()` removes where clause

- .github/workflows/ibis-docs-lint.yml
Fix failing benchmark data upload
> ci(benchmarks): set GH_TOKEN to allow `gh` CLI usage

- ibis/expr/types/temporal.py
This PR removes `Temporal*` classes, which only existed to avoid repeating the definition of `strftime`. With this PR, I repeat the definition and we get accurate docstrings for `strftime` for every type and some needless hierarchy is removed. Since this operatrion has not changed for quite a while, I think the repetition is worth the cost.
Closes #7504.
> refactor(temporal): remove unnecesary `Temporal*` classes

- ibis/backends/base/sql/compiler/query_builder.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/compiler.py
- ibis/backends/bigquery/datatypes.py
- ibis/backends/bigquery/tests/conftest.py
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_compile_in_memory_table/out.sql
- ibis/backends/bigquery/tests/unit/test_compiler.py
- ibis/backends/tests/test_array.py
This PR moves the BigQuery memtable implementation to be much more efficient than the current one by using temporary tables along with the `bq.Client.load_table_from_dataframe` method.
Depends on #7527.
> perf(bigquery): use more efficient representation for memtables

- ibis/backends/bigquery/__init__.py
- ibis/backends/tests/test_register.py
This PR adds support for reading Parquet, JSON and CSV files directly into BigQuery. Local paths, local globs, GCS paths, and GCS globs are all supported. Depends on #7545.
Loading local globs with and without `concurrent.futures`:
```
cloud in 🌐 falcon in ~ via 🐍
❯ ls ~/data/trip-data
Permissions Size User  Date Modified Name
.rw-r--r--  151M cloud 26 Jun 11:34  yellow_tripdata_2016-01.parquet
.rw-r--r--  158M cloud 26 Jun 11:34  yellow_tripdata_2016-02.parquet
```
```
In [1]: from ibis.interactive import *
In [2]: con = ibis.bigquery.connect()
In [3]: ibis.set_backend(con)
In [4]: %time t = ibis.read_parquet("/home/cloud/data/trip-data/*.parquet")
CPU times: user 254 ms, sys: 191 ms, total: 445 ms
Wall time: 51 s
```
```
In [1]: from ibis.interactive import *
In [2]: con = …
```
> feat(bigquery): support reading parquet, json and csv files

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/converter.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
- ibis/formats/pyarrow.py
This is a possible solution to #7561.
While it works, it does feel like a lot of code to solve the problem of array column printing.
That said, I'm not sure if there's a better way to do it, and we have similar code for pandas conversion (in fact, probably a lot more, and more complex too).
The reason I took the extension array approach was to avoid having to adjust any of the pretty printing code to be backend-specific.
With extension array approach I am attempting to limit the blast radius of Snowflake-specific behavior while allowing Snowflake to continue to be extremely relaxed about the underlying storage of the data.
I followed the examples here: https://arrow.apache.org/docs/python/extending_types.html#custom-extension-array-class
Fixes #7561.
> fix(snowflake): fix array printing by using a pyarrow extension type

- .github/workflows/ibis-backends-flink.yml
- ibis/backends/tests/test_temporal.py
- pyproject.toml
* `grpcio-status` isn't a dependency for the Flink backend; one of the underlying libraries just raises a warning, requesting to install it, if it isn't already
* No need to manually upgrade (or cap) pandas anymore. As a side effect, one of the pandas 2.x-only tests now works as expected.
* Using pandas 2.x will result in deprecation warnings, because (Py)Flink is stuck on an older Beam, which in turn pins an older PyArrow. So we ignore those for now.
I opened this while leaving #7444 still open, because we can't add the Flink dependencies officially to the backend (see [discussion](https://claypotai.slack.com/archives/C047W8D9674/p1698775815390869?thread_ts=1698338539.212219&cid=C047W8D9674)).
> build(flink): use PyFlink 1.18 and drop workaround

- ibis/backends/base/sql/__init__.py
- ibis/backends/base/sql/alchemy/__init__.py
Based on https://github.com/ibis-project/ibis/discussions/7578, add some related documentation.
> docs(sql): emphasize the need to close a `raw_sql` cursor only when using `SELECT` statements

- .github/workflows/ci-data.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/conda-lock.yml
- .github/workflows/create-rotate-key-issue.yml
- .github/workflows/pre-release.yml
- .github/workflows/update-deps.yml
These CI workflows don't make sense to run on forks. As a fork owner,
I get emails every time these flows fail.
Let's save some junk emails and some
wasted electricity.
Double check me that I picked out the right workflows to skip, and that I didn't miss other ones.
fixes https://github.com/ibis-project/ibis/issues/7568
> chore(ci): skip bad CI runs on forks

- poetry.lock
- pyproject.toml
Turns out it is enough to set the upper bound of docs dependencies python to 3.13
> chore(deps): remove need for explicit scipy dependency

- docs/_quarto.yml
- docs/how-to/timeseries/sessionize.qmd
- docs/index.qmd
- ibis/backends/base/__init__.py
- ibis/backends/clickhouse/tests/test_select.py
- ibis/backends/tests/test_sql.py
- ibis/expr/api.py
- ibis/expr/sql.py
Now that we syntax highlight the result of `to_sql` in IPython and Jupyter, we can decrease API surface a bit by removing `show_sql` in favor of `print(to_sql(...))` for folks that are not using IPython or Jupyter.
> refactor: remove `show_sql` in favor of `print(to_sql)`

- ibis/backends/base/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
- ibis/expr/types/relations.py
Small tweak to allow passing of writer specific args/kwargs. Also fixes a typo
> feat(exporting): allow passing writer_opts to PyArrow ParquetWriter and CSVWriter

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/registry.py
Use the now-GA `array_sort` function from upstream snowflake.
> feat(snowflake): use upstream `array_sort`

- ibis/backends/clickhouse/compiler/values.py
- ibis/backends/duckdb/registry.py
- ibis/backends/pandas/execution/arrays.py
- ibis/backends/polars/compiler.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/snowflake/registry.py
- ibis/backends/tests/test_array.py
- ibis/backends/trino/registry.py
- ibis/expr/operations/arrays.py
- ibis/expr/types/arrays.py
This PR implements `ArrayFlatten` which can be used to remove a single level of
nesting from a nested array value.
Closes #7575.
> feat: add `ArrayValue.flatten` method that removes one level of nesting from array values

- ibis/backends/bigquery/registry.py
- ibis/backends/clickhouse/compiler/values.py
- ibis/backends/duckdb/registry.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/registry.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/snowflake/registry.py
- ibis/backends/tests/test_array.py
- ibis/backends/trino/registry.py
- ibis/expr/api.py
- ibis/expr/operations/arrays.py
- ibis/expr/operations/relations.py
- ibis/expr/types/generic.py
Adds an `ibis.range` API for generating sequences. This cannot yet be used with `ibis.read_parquet` et al. That will be done in a follow-up.
Closes #7169.
Backend support:
Follow-ups:
- date range
- timestamp range
- decimal range
- floating range
> feat(api): add `ibis.range` function for generating sequences

- ibis/backends/base/sqlglot/datatypes.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/client.py
- ibis/backends/bigquery/datatypes.py
- ibis/backends/bigquery/registry.py
- ibis/backends/bigquery/tests/unit/test_datatypes.py
- ibis/backends/bigquery/udf/__init__.py
This PR moves the BigQuery type mapper to use sqlglot instead of the string munging we are currently using. Closes #7531.
> refactor(bigquery): move `BigQueryType` to use sqlglot for type parsing and generation

- ibis/backends/base/sql/alchemy/registry.py
- ibis/backends/tests/test_window.py
This PR adds support for passing expressions to RANGE and ROWS window bounds to SQLAlchemy-based backends.
This PR is a hack, because SQLAlchemy itself doesn't support expression-based window bounds.
See https://github.com/ibis-project/ibis/issues/7598#issuecomment-1819578202 for details.
Closes #7598.
> feat(sqlalchemy): support expressions in window bounds

- .github/workflows/ibis-backends.yml
This PR fixes the flaky flink tests, by separating general backend tests and flink backend tests, inspired by previous [investigation](https://github.com/ibis-project/ibis/blob/903cf5b9112e30c5d85628849a079aa17b1cd18a/.github/workflows/ibis-backends-flink.yml#L130C7-L133C73).
> test(flink): fix flaky flink tests

- ibis/backends/flink/tests/conftest.py
The previous attempts to address this did not work. I believe we need to use `UnorderedComparator` for testing the Flink backend.
> test(flink): use unordered comparisons for series and dataframe assertions

- ibis/expr/sql.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_in_clause/decompiled.py
- ibis/expr/tests/test_sql.py
With #7610 merged, now this fix for IN clauses in `parse_sql` should work.
> fix(parse_sql): parse IN clauses

- .github/workflows/ibis-backends.yml
Increasing compressed class space size is only necessary if running the test suite using mini-cluster, but the CI here is using a remote, Dockerized cluster.
> ci(flink): don't raise compressed class space size

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
Fixes #7621 
Potential performance impact for large dataframes getting converted to `pyarrow` before getting piped into PyArrow, but also... do we care?
> refactor(duckdb): use pyarrow for all memtable registration

- ibis/backends/pandas/execution/arrays.py
- ibis/backends/snowflake/registry.py
- ibis/backends/tests/test_array.py
- ibis/expr/types/arrays.py
Fixes pandas and snowflake to drop empty array rows when unnesting.
> fix(pandas/snowflake): make unnest of empty array rows consistent with other backends

- ibis/backends/tests/test_sql.py
Two options:
1. [Expect `to_sql` to fail, because we don't have a SQLGlot dialect for Flink, and don't feel like anything is "close enough."](https://github.com/ibis-project/ibis/pull/7639/commits/aef728321981585e79d38fbb15155a920b652b28)
2. [Use Hive (or some other?) dialect as a close-enough stand-in, in order to enable SQL rendering.](https://github.com/ibis-project/ibis/pull/7639/commits/4492ae5d0b6dcb0a5f45906e071ba2ecd386f4bb)
---
Double-checked--`to_sql` doesn't work without a SQLGlot dialect. ~I don't believe we've identified one that's "close enough".~
Wonder if https://github.com/apache/flink/blob/76f754833298beb3e7589d521e75325adf283bf3/flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/delegation/PlannerContext.java#L270 might indicate that can start …
> chore(flink): use `pytestmark` over repeated marks

- ibis/backends/tests/test_map.py
In short, this test needs PyArrow 13 to work, where [the `maps_as_pydicts` option for `pa.Table.to_pandas()` was introduced](https://github.com/apache/arrow/commit/1a697abd08d6db6ac1496e548dcdb86a9a82c152).
However, only PyFlink only supports up to PyArrow 11 (due to the Apache Beam dependency).
Once (if?) the Apache Beam dependency is relaxed, it would at least be possible to patch the PyFlink `Table.to_pandas()` call to call `pa.Table.to_pandas()` with `maps_as_pydicts="lossy"`, with the possibility of proposing the change in PyFlink `Table.to_pandas()` upstream.
> test(flink): revise mark for map dict construction

- docs/contribute/04_maintainers_guide.qmd
- ibis/backends/clickhouse/tests/test_functions.py
- ibis/backends/dask/aggcontext.py
- ibis/backends/dask/tests/test_client.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/pandas/aggcontext.py
- ibis/expr/operations/tests/test_core.py
- ibis/expr/tests/conftest.py
- ibis/tests/expr/test_interactive.py
Found via `typos --hidden --format brief`
> docs: fix typos

- ibis/common/deferred.py
This is a weird one, BUT:
There is (at least) one case where, when trying to resolve a deferred value, we end up at the `CoercionError` exception with a non-deferred expression.
When `ibis.options.interactive = True`, we then attempt to render that expression using `rich` because that's what f-strings do.
Even though in the calling code, which here is in `CoercedTo.match`, we catch the `CoercionError`, the `CoercionError` never gets thrown because we've instead errored out trying to render an f-string that will never be seen.
If, instead of rendering the expression, we instead mention the expression type, that prevents the short-circuit.
Fixes #7627 
Alternatively, we would have a context manager that disables interactive mode, so we don't end up inadvertently executing expressions.
> fix(deferred): don't pass expression in fstringified error message

- ibis/backends/datafusion/compiler/values.py
- ibis/backends/tests/test_string.py
Fixes an issue where we assume that non matching patterns return an empty array, when in fact they return null
> fix(datafusion): ensure that non-matching re_search calls return bool values when patterns do not match

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_aggregation.py
Works around a bug in the polars where column names from computed grouping kyes are not propagated through to drop_nulls.
> fix(polars): project first when creating computed grouping keys

- docker-compose.yml
- ibis/backends/clickhouse/__init__.py
Allow metadata queries to work with older versions of clickhouse.
Closes #7604.
> fix(clickhouse): allow schema metadata to be retrieved from older versions of clickhouse

- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_export.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_json.py
- ibis/backends/tests/test_map.py
- ibis/backends/tests/test_param.py
- ibis/backends/tests/test_struct.py
- ibis/backends/tests/test_temporal.py
- ibis/backends/tests/test_timecontext.py
- ibis/backends/tests/test_udf.py
- ibis/backends/tests/test_window.py
- ibis/backends/tests/tpch/conftest.py
Fixes flakiness associated with backends whose results are arbitrarily ordered (e.g., https://github.com/ibis-project/ibis/actions/runs/7092619807/job/19304311500)
> test: use backend assertions in backend test suite

- compose.yaml
- docs/contribute/02_workflow.qmd
- ibis/backends/oracle/tests/conftest.py
- ibis/backends/tests/base.py
Reading https://docs.docker.com/compose/compose-file/03-compose-file/, apparently `compose.yaml` is preferred over `compose.yml` and `docker-compose.yml`. 
Also, `docker-compose` is only maintained as an alias of `docker compose` for compatibility in Docker Compose V2, and the `version` key in the Compose file is only maintained for backwards compatibility.
> build: move `docker-compose.yml` to `compose.yaml`

- .github/workflows/update-deps.yml
Fixes the currently-failing `update-deps.yml` workflow.
> ci(deps): use non-deprecated method of updating nix flakes

- docs/contribute/05_reference.qmd
Before this change the API docs needed to be generated to render any single page. This skips including API docs if requested files do not exist.
> docs(build): allow building individual docs without rendering api docs first

- ibis/backends/mssql/registry.py
- ibis/backends/mssql/tests/test_client.py
Fix string length computation in the MS SQL backend with a glorious hack. Thanks to @arkanovicz for the suggestion.
> fix(mssql): compute the length of strings correctly

- ibis/backends/oracle/__init__.py
> fix(oracle): ensure that `.sql` metadata results are in column-definition order

- poetry.lock
- pyproject.toml
Both `pyspark` and `polars` backends rely on `packaging` in non-test
code but we aren't installing it as an extra for those backends.
> fix(pyspark,polars): add packaging extra

- ibis/backends/base/__init__.py
It just wraps `execute` but I thought we should have it for consistency,
since it is present on expressions.
> feat(base): add `to_pandas` method to BaseBackend

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/registry.py
Remove a custom UDF in favor of equivalent upstream functionality
> refactor(snowflake): use upstream map-from-arrays function instead of a custom UDF

- ibis/backends/bigquery/registry.py
- ibis/backends/clickhouse/compiler/values.py
- ibis/backends/duckdb/registry.py
- ibis/backends/postgres/registry.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/tests/test_array.py
- ibis/backends/trino/registry.py
- ibis/expr/operations/core.py
- ibis/expr/types/arrays.py
Fixes #7676.
I created https://github.com/duckdb/duckdb/issues/9981 because I think this is a bug in DuckDB.
For now this is a workaround to address the issue.
> fix(duckdb): ensure that parameter names are unlikely to overlap with column names

- ibis/common/grounds.py
- ibis/common/tests/test_grounds.py
Previously we silently allowed unkown arguments.
> fix(ir): raise if `Concrete.copy()` receives unexpected arguments

- ibis/common/graph.py
- ibis/expr/analysis.py
The point of the `traverse()` function to allow the traverser function to alter the entire visiting strategy. The filter argument on the other hand is used for the higher level methods, like `node.find()`.
> refactor(common): remove `traverse()` function's `filter` argument since it can be expressed using the visitor

- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
Currently only exact matches are supported, we can extend this to allow
more advanced dictionary patterns in the future.
> feat(common): allow matching on dictionaries in possibly nested patterns

- ibis/common/graph.py
- ibis/common/tests/test_graph.py
- ibis/expr/analysis.py
> refactor(common): unify the `node.find()` and `node.match()` methods to transparently support types and patterns

- ibis/common/graph.py
- ibis/common/tests/test_graph.py
> feat(common): expose `node.__children__` property to access the flattened list of children of a node

- ibis/common/graph.py
- ibis/common/tests/test_graph_benchmarks.py
depends on https://github.com/ibis-project/ibis/pull/7760
In the #7580 branch I measured 17% percent improvement, it it is roughly `12%` - `14%`. 
The reason of the performance gain is that `Concrete` implements `__recreate__(kwargs)` where we validate the argument but without going through the `Signature`'s binding process.
Using `recreated = node.__class__(**kwargs)` VS `recreated = node.__recreate__(kwargs)` (now):
```
------------------------------------------------------------------------------ benchmark 'test_replace': 2 tests ------------------------------------------------------------------------------
Name (time in ms)                   Min                Max               Mean            StdDev             Median               IQR            Outliers      OPS            Rounds …
```
> perf(common): improve the performance of replacing nodes by using a specialized `node.__recreate__()` method

- ci/schema/trino.sql
- compose.yaml
- ibis/backends/tests/base.py
- ibis/backends/trino/tests/conftest.py
Simplify the minio setup by using bitnami, which allows use of a non-root container and allows us to avoid hacking the entrypoint and command.
> ci(dev): simplify minio container setup

- ibis/expr/api.py
- ibis/expr/operations/relations.py
- ibis/formats/__init__.py
- ibis/formats/pandas.py
- ibis/formats/pyarrow.py
- ibis/util.py
The `TableProxy` classes were misplaced under `ibis.expr.operations.relations`, probably because the `formats` arrived later. This change moves the types to the respective `ibis.formats.pandas` and `ibis.formats.pyarrow` modules as well as use `ibis.util.PseudoHashable` to make them well, "pseudo" hashable.
> refactor(formats): move the `TableProxy` object to formats from the operations

- ibis/backends/flink/__init__.py
- ibis/backends/flink/ddl.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/flink/tests/test_ddl.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_examples.py
- ibis/backends/tests/test_map.py
[Previously](https://github.com/ibis-project/ibis/pull/6920), we made a pass over the tests under `ibis/ibis/backends/tests/` and marked them if they fail for the Flink backend. We are now making the second pass over these tests, and looking deeper into those marked previously. This PR contains the changes for the deep dive on `test_client.py`.
**Edit**: The scope of this PR got extended during the review process and after the merging with https://github.com/ibis-project/ibis/pull/7650. Now contains the following major changes:
- Adds support for creating `temporary view` for in-memory `obj` in `create_table()` and `create_view()`.
- Raises error when the user-set `temp` argument does not match the supported behavior.
- Adds `rename_table()` for Flink backend.
- Adds unit tests that were …
> test(flink): deep dive on the tests marked for Flink in test_client.py

- docs/_tabsets/install.qmd
Closes #7738 
`pip`:
`conda`/`mamba`/`pixi`:
> docs(flink): override default install instructions

- ibis/backends/base/sql/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/unit/udf/snapshots/test_builtin/test_bqutil_fn_from_hex/out.sql
- ibis/backends/bigquery/tests/unit/udf/snapshots/test_builtin/test_farm_fingerprint/out.sql
- ibis/backends/bigquery/tests/unit/udf/test_builtin.py
Discovered in draft PR https://github.com/googleapis/python-bigquery-dataframes/pull/277/files
Often BigQuery Project IDs contain `-` which need to be enclosed in backticks to ensure it is interpreted as one identifier.
> fix(bigquery): escape the schema (project ID) for BQ builtin UDFs

- ibis/expr/operations/core.py
- ibis/expr/operations/generic.py
- ibis/expr/operations/tests/test_generic.py
- ibis/expr/tests/test_api.py
- ibis/expr/types/generic.py
Resolves https://github.com/ibis-project/ibis/issues/7775
> fix(ir): implicitly convert `None` literals with `dt.Null` type to the requested type during value coercion

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_udf.py
This PR fixes an issue in the duckdb backend where UDFs were using their input
*values* instead of their input types (from the UDF signature) to define a UDF with DuckDB's `create_function`.
> fix(duckdb): allow None inputs to UDFs

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
Currently using the Snowflake backend with Ibis, you'll get an error if you specify a URL as a file path for read_csv. This works with other engines where the behavior is natively supported, but Snowflake requires those additional preprocessing steps. 
I added a portion to use a TempFile and load the content to the temporary stage. Complex file formats might cause issues with this, but I'll try to do some additional testing. 
We could likely add this to the other `read_...` methods, but I wanted to start with this for now. 
It's possible to make this work with S3, Azure Blob, GCS, etc., but that could get complex determining whether or not to use client storage options or integrations available natively in Snowflake. 
Here's some code you can use to test the new feature:
```python
from …
```
> Snowflake: Add Support for "read_csv" with https

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
In the upcoming update of the spatial extension, to be able to read form a url, the `httpfs` extension is needed. This PR adds this support.
Closes #7719
> feat(geospatial): update read_geo to support url reading 

- ibis/backends/snowflake/__init__.py
We have tests that hit this code path, but I forgot to run the whole test suite before merging.
> fix(snowflake): convert path to `str` when checking for a prefix

- compose.yaml
- docker/flink/Dockerfile
We should be able to use a simpler image specification to make it easier to Mend Renovate to perform automatic upgrades to the image. We can also isolate the flink job manager a bit more by running the flink base image.
> ci(flink): clean up docker image specifications

- .github/workflows/ibis-docs-lint.yml
- .github/workflows/pr-title.yml
Adapt the https://github.com/substrait-io/substrait-python/blob/main/.github/workflows/pr_title.yml workflow for our needs, so that we can allow squash merges.
Closes #6549.
> ci(dev-tools): add PR title and body linter to verify conventional commits and allow squash merges

- .github/workflows/pr-title.yml
Otherwise, we're stuck telling people to always start PR descriptions with a blank line which seems silly (and annoying).
> ci(dev-tools): stop warning on leading blank line in body

- .github/workflows/conda-lock.yml
- .github/workflows/ibis-backends.yml
Avoid annoying spurious failures in CI due to a broken v4 of the upload and download artifact actions.
> ci: move back to download artifact v4 until actions/download-artifact#249 is fixed

- ibis/backends/duckdb/registry.py
- ibis/backends/oracle/registry.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/registry.py
- ibis/backends/tests/test_aggregation.py
- ibis/expr/operations/reductions.py
- ibis/expr/types/generic.py
- ibis/expr/types/numeric.py
Adds support for calling `median` and `quantile` on more types than numeric.
Tests are included for computing the median of dates + strings.
Closes #7250.
> feat(api): support median and quantile on more types

- ibis/formats/pyarrow.py
- ibis/formats/tests/test_pyarrow.py
Does what it says on the tin. We will want to specialize this more once we have
proper support for `geoarrow` and friends, but for now, we should assume all
geospatial types should be rendered as binary.
> fix(repr): default to pa.binary for all geospatial dtypes

- ibis/backends/base/sqlglot/datatypes.py
- ibis/backends/duckdb/tests/test_geospatial.py
I thought, initially, that `WKB_BLOB` should be mapped on to something
like `dt.GeoSpatial`, but that leads to a situation where we try to call
`AsWKB` on an existing WKB column, and DuckDB does not like that.
Mapping it as `binary` works and the created columns are still correctly
detected as `geometry:geospatial`.
> fix(duckdb): allow table creation from expr with geospatial datatypes

- ibis/backends/impala/compiler.py
- ibis/backends/tests/test_generic.py
Work around [a bug in sqlglot](https://github.com/tobymao/sqlglot/issues/2717) where it cannot parse Impala `VALUES` syntax. Discovered by @chris-park in https://github.com/ibis-project/ibis/issues/7827#issuecomment-1867499217.
> fix(impala): generate memtables using `UNION ALL` to work around sqlglot bug

- ibis/expr/decompile.py
- ibis/expr/format.py
- ibis/expr/operations/relations.py
- ibis/expr/tests/snapshots/test_format/test_asof_join/repr.txt
- ibis/expr/tests/snapshots/test_format/test_format_multiple_join_with_projection/repr.txt
- ibis/expr/tests/snapshots/test_format/test_memoize_filtered_tables_in_join/repr.txt
- ibis/expr/tests/snapshots/test_format/test_table_count_expr/join_repr.txt
- ibis/expr/tests/snapshots/test_format/test_two_inner_joins/repr.txt
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/joins.py
- ibis/expr/types/relations.py
- ibis/tests/expr/snapshots/test_format_sql_operations/test_memoize_database_table/repr.txt
- ibis/tests/expr/test_analysis.py
- ibis/tests/expr/test_struct.py
- ibis/tests/expr/test_table.py
This enables us to maintain join expression equality: `a.join(b).equals(a.join(b))`
So far we have been using `SelfReference` to make join tables unique, but it was globally unique which broke the equality check above. Therefore we need to restrict the uniqueness to the scope of the join chain. The simplest solution for that is to simply enumerate the join tables in the join chain, hence now all join participants must be `ops.JoinTable(rel, index)` instances. 
`ops.SelfReference` is still required to distinguish between two identical tables at the API level, but it is now decoupled from the join internal representation.
> refactor(ir): introduce `JoinTable` operation unique to a `JoinChain` instead of using the globally unique `SelfReference`

- ibis/backends/tests/sql/test_compiler.py
- ibis/backends/tests/sql/test_select_sql.py
- ibis/backends/tests/sql/test_sql.py
- ibis/expr/decompile.py
- ibis/expr/tests/test_decompile.py
- ibis/tests/util.py
Fixes decompilation of `SelfReference` and adds the ability to customize decompilation comparison.
> fix(decompile): ensure that `SelfReference` is decompiled with a call to `.view()`

- ibis/expr/rewrites.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/joins.py
@cpcloud this is going to fix several integrity errors in the duckdb refactor while producing a simpler join chain. 
A solution would have been to just remove the support of "continue the left chain"  in rather than just "nest the chains", but I managed to resolve the dereferencing issue by "peeling" all `JoinChain` fields in the input values. 
I still need to finish the PR.
> refactor(ir): support join of joins without nesting the left side

- ibis/backends/base/sqlglot/rewrites.py
- ibis/backends/base/sqlglot/tests/test_rewrites.py
It makes the compiler implementation more straightforward as well as helps to produce cleaner SQL.
Pulled out from https://github.com/ibis-project/ibis/pull/7796
> feat(sql): lower expressions to SQL-like relational operations

- poetry.lock
- pyproject.toml
`filelock` is only used in testing, so move that dependency to the `test` dependency group
> fix(deps): remove `filelock` from required dependencies

- ibis/backends/base/sqlglot/datatypes.py
- ibis/backends/base/sqlglot/tests/test_datatypes.py
- ibis/tests/strategies.py
Fix support for decimal types and add support for basic geograph and geometry types to the sqlglot type mapper.
> feat(datatypes): fix decimal support and add geospatial types to the sqlglot type mapper

- ibis/backends/base/sqlglot/datatypes.py
- ibis/backends/base/sqlglot/tests/test_datatypes.py
Roundtrip interval types through the sqlglot type mapper
> feat(datatypes): make intervals round trip through sqlglot type mapper

- ibis/common/dispatch.py
- ibis/common/tests/test_dispatch.py
Example use:
```py
class Visitor(Dispatched):
def visit(self, x: int):
assert isinstance(x, int)
def visit(self, x: str):
assert isinstance(x, str)
class ChildVisitor(Visitor):
def visit(self, x):
return super().visit(x)
def visit(self, x: float):
assert isinstance(x, float)
```
instead of 
```py
class Visitor(Dispatched):
@functools.singledispatchmethod
def visit(self, x):
...
@visit.register(str)
def visit_str(self, x):
...
class ChildVisitor(Visitor):
@functools.singledispatchmethod
def visit(self, x):
return super().visit(x)
@visit.register(float)
def visit_float(self, x):
...
```
Used in practice to implement the new pandas executor in https://github.com/ibis-project/ibis/pull/7797
> feat(common): add `Dispatched` base class for convenient visitor pattern implementation

- ibis/backends/duckdb/__init__.py
Remove an unused method in the new duckdb sqlglot backend.
> refactor(duckdb): remove the need for a specialized `_to_geodataframe` method

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_client.py
Ensure that create_schema and create_database tests actually assert something meaningful. Before this PR there was no validation in the test suite that calling create_schema/create_database had any stateful effect.
> fix(duckdb): ensure that create_schema and create_database are actually tested

- ibis/expr/operations/relations.py
- ibis/expr/rewrites.py
- ibis/expr/tests/test_newrels.py
Previously the integrity check allowed arbitrary value expressions originating from a reduction. This change enforces that the value wrapped in a `ScalarSubquery` must be a reduction instance.
> refactor(ir): stricter scalar subquery integrity checks

- ibis/common/graph.py
- ibis/common/tests/test_graph.py
Alternative implementation of `map` to reduce memory usage. While `map` keeps all the results in memory until the end of the traversal, the new `map_clear()` method removes intermediate results as soon as they are not needed anymore.
Planned to be used in the pandas refactor #7797
> feat(common): add a memory efficient `Node.map()` implementation

- ibis/backends/clickhouse/tests/test_select.py
- ibis/expr/operations/relations.py
- ibis/expr/tests/snapshots/test_format/test_asof_join/repr.txt
- ibis/expr/tests/test_format.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/joins.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Previously the `ASOF` join API was imprecise. 
The backends supporting `asof` joins require exactly one nearest match (inequality) predicate along with arbitrary number of ordinary join predicates, see [ClickHouse ASOF](https://clickhouse.com/docs/en/sql-reference/statements/select/join#asof-join-usage), [DuckDB ASOF](https://duckdb.org/docs/guides/sql_features/asof_join.html#asof-joins-with-the-using-keyword) and [Pandas ASOF](https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html). 
This change alters the API to `table.asof_join(left, right, on, predicates, ...)` where `on` is the nearest match predicate defaulting to `left[on] <= right[on]` if not an expression is given. I kept the `by` argument for compatibility reasons, but we should phase that out in favor of …
> refactor(api): revamp `asof` join predicates

- .github/workflows/ibis-backends.yml
Installation of postgres extras are no longer necessary for Trino, so no reason to waste time installing them.
> ci(trino): remove postgres extras

- .devcontainer/updateContent.sh
- .github/workflows/ibis-backends.yml
- docs/_tabsets/install_default.qmd
- docs/index.qmd
- ibis/backends/duckdb/tests/test_register.py
- ibis/backends/tests/test_examples.py
- poetry.lock
- pyproject.toml
> refactor(deps): make `pins` an optional dependency through an `examples` extra

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/tests/test_asof_join.py
- ibis/backends/tests/test_join.py
- ibis/expr/tests/snapshots/test_format/test_asof_join/repr.txt
- ibis/expr/tests/test_dereference.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/joins.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
To correctly mimic pandas' tolerance argument we need to do the following steps:
1. Do the ASOF join with `on` and `by` parameters
2. Filter the joined result using the predicate creates be the tolerance: `left[on] <= right[on] + tolerance AND left[on] >= right[on] - toletance`
3. Join the filtered table to the `left` table again using a LEFT JOIN
This PR also adds support for ASOF joins in duckdb: fixes https://github.com/ibis-project/ibis/issues/6487
> fix(ir): `asof` join `tolerance` parameter handling generated incorrect expression

- .github/workflows/ibis-backends.yml
Fixes installation of the `decompiler` extra.
> ci: install decompiler as extra not as its own dependency

- ibis/backends/tests/test_numeric.py
- ibis/common/numeric.py
- ibis/formats/pandas.py
Use `normalize_decimal` for output conversion from backend decimal values into pandas objects.
> fix(conversion): convert decimals to the exact precision and scale requested by the input type

- .github/workflows/ibis-backends.yml
- ibis/backends/pandas/rewrites.py
- ibis/backends/polars/__init__.py
- ibis/backends/polars/compiler.py
- ibis/backends/polars/tests/test_join.py
- ibis/backends/tests/test_interactive.py
- ibis/backends/tests/test_join.py
Bare minimum changes required for the polars backend to work with the new relational operations. Since polars' join API follows the same semantics as pandas, I'm using the pandas specific rewrites here.
In the future we may want to rewrite the compiler similarly to the pandas one: using `node.map()` and `Dispatched`.
> refactor(polars): update the polars backend to use the new relational abstractions

- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_core.py
Fix bad reference to `NumpyFormat`; use `NumpyType` as in the other `to_*` methods.
Calling `.to_numpy()` on a `DataType` object resulted in:
```python
*** ImportError: cannot import name 'NumpyFormat' from 'ibis.formats.numpy' (/opt/miniconda3/envs/pandera-dev/lib/python3.11/site-packages/ibis/formats/numpy.py)
```
> fix(datatypes): fix bad references in `to_numpy()`

- ibis/backends/duckdb/tests/test_register.py
- ibis/backends/tests/test_client.py
Fixes a rare test case failure observed when tests execute in a particular order that implicitly sets the default backend (ex: https://github.com/ibis-project/ibis/actions/runs/7412054856/job/20167990310?pr=7877).
> test(duckdb): ensure that no test causes the default backend to be set

- docs/release_notes.md
I was looking for information about the `get_name()` method, and I ran across a badly-formatted line:
> docs: fix formatting for note on `_name`, `_dtype`

- ibis/backends/mysql/__init__.py
When trying to connect to a mySQL backend, the following error can appear:
```
OperationalError: (pymysql.err.OperationalError) (1298, "Unknown or incorrect time zone: 'UTC'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
This is due to an exception generated by PyMySQL.
The exception, formerly generated by SQLAlchemy was already caught by Ibis since #6010, this PR adds a catching of the PyMySQL exception.
Resolves #7918
> fix(mysql): catch PyMySQL OperationalError exception

- ibis/backends/tests/test_window.py
- ibis/expr/analysis.py
- ibis/expr/types/generic.py
This PR fixes an issue where duplicate window expressions were given the position of the new (duplicated value)
of the expression, rather than preserving the original order.
This was because we were iterating over the new keys first and putting those expressions into a `dict`.
BY iterating over the old keys first, we preserve the original order.
Closes #7940.
> fix(backends): preserve `order_by` position in window function when subsequent expressions are duplicated

- ibis/backends/postgres/registry.py
- ibis/backends/postgres/tests/snapshots/test_client/test_timezone_from_column/out.sql
- ibis/backends/postgres/tests/test_client.py
This PR addresses an issue where we are unintentionally converting values from
their time zone to UTC by using the `AT TIME ZONE 'timezone'` syntax.
`AT TIME ZONE` is used to convert a `timestamp with time zone` to a `timestamp
without time zone` after adjusting for the timezone offset. This is not the
desired behavior.
The values we get back from the database are always in UTC, regardless of the
system timezone so this PR leaves them as is.
Resolves #7872.
> fix(postgres): ensure that no timezone conversion takes place on timestamptz columns when selecting them out

- ibis/backends/clickhouse/compiler/core.py
- ibis/common/deferred.py
- ibis/common/patterns.py
- ibis/common/tests/test_deferred.py
- ibis/tests/expr/test_value_exprs.py
> fix(common): do not convert callables to resolveable objects

- ibis/backends/base/sql/alchemy/query_builder.py
- ibis/backends/base/sql/compiler/translator.py
This (potentially) fixes the bug found in #7952. With this fix the query at least runs successfully and I _think_ the fix makes sense. Pushing this up to see if it passes full CI for now. I haven't attempted to write a proper test for this yet.
> fix(sqlalchemy): properly handle aliases of extracted subqueries

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/trino/compiler.py
Clean up the use of anonymous functions and remove `array_func` hack in favor of `f.array`
> refactor(sqlglot): make anonymous functions easier to use and remove `array_func` hack

- ci/schema/postgres.sql
- docker/postgres/Dockerfile
Fixes currently-failing CI due to an expired `pgxn` SSL certificate. I removed the usage of pgxn entirely so we hopefully never have to deal with that issue again.
> ci(postgres): avoid pgxn due to expired certificate

- ibis/backends/base/sqlglot/compiler.py
This PR changes non-finite value definitions in the base sqlglot compiler to be more dialect-agnostic.
> refactor(sqlglot): use a more backend-agnostic expression for non-finite constants

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/snowflake/compiler.py
Cleans up some redundant use of `sge.Explode`
> refactor(sqlglot): clean up `explode` usage

- ibis/expr/types/generic.py
moves towards https://github.com/ibis-project/ibis/issues/7295.
This just removes the methods from the docs
(by removing the docstring)
and informs current users of the API as to the upgrade path
(using the `@deprecated` decorator)
> depr: deprecate Value.least() and Value.greatest()

- .git-blame-ignore-revs
Apparently the commit hash was wrong. Discovered this while blaming `ibis/formats/tests/test_dask.py`: https://github.com/ibis-project/ibis/blame/main/ibis/formats/tests/test_dask.py
> chore: fix commit hash for git-blame-ignore-rev

- ibis/backends/flink/registry.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/flink/tests/snapshots/test_compiler/test_timestamp_from_unix/timestamp_ms/out.sql
- ibis/backends/flink/tests/snapshots/test_compiler/test_timestamp_from_unix/timestamp_s/out.sql
- ibis/backends/tests/test_temporal.py
Adds several new temporal operators for Flink backend. The goal with this is to clear as many of the tests in `ibis/ibis/backends/tests/test_temporal.py` as possible for the Flink backend.
> feat(flink): add new temporal operators

- ibis/backends/flink/registry.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/tests/test_window.py
This PR is a part of the deep-dive investigation to increase the test coverage for Flink backend. Contains the changes made to clear as many of the tests in `test_window.py` and `time_timecontext.py` as possible at this time for the Flink backend.
> feat(flink): implement struct field, clean up literal, and adjust timecontext test markers

- ibis/backends/impala/tests/test_bucket_histogram.py
- ibis/backends/impala/tests/test_case_exprs.py
- ibis/backends/impala/tests/test_sql.py
- ibis/backends/impala/tests/test_window.py
Found these while working on the exasol port. We cannot enable linting yet, but we should be able to do so once we port the backends.
> chore(impala): remove unused imports

- .github/workflows/check-generated-files.yml
- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-docs-lint.yml
- .github/workflows/ibis-main.yml
- ibis/backends/base/sql/alchemy/geospatial.py
- ibis/backends/duckdb/tests/conftest.py
- ibis/backends/duckdb/tests/test_geospatial.py
- ibis/backends/duckdb/tests/test_register.py
- justfile
Apparently these actions are archived and functionality is rolled into setup-python. This PR attempts to validate that.
> ci: migrate to setup-python dependency caching

- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_generic.py
- ibis/expr/types/relations.py
- ibis/util.py
We were not handling unsplatted dicts in mutate/select, this PR fixes that. Fixes #8013.
> fix(mutate/select): ensure that unsplatted dictionaries work in `mutate`and`select` APIs

- .github/workflows/ibis-backends-cloud.yml
- ibis/backends/bigquery/datatypes.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/bigquery/tests/unit/test_datatypes.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_temporal.py
This PR fixes some failing tests that slipped through the BigQuery sqlglot port:
- The type of errors raised from `BigQueryType` is now `UnsupportedBackendType` instead of the generic `TypeError`.
- Handling of UDF redefinitions wasn't implemented in the Snowflake backend.
- CI wasn't installing the geospatial dependencies for the BigQuery backend.
> fix(clouds): account for new error types in bigquery and udf renaming in snowflake

- .gitignore
- docs/_renderer.py
- ibis/expr/api.py
- ibis/selectors.py
Fixes #8001. For each example were disabling interactive mode before rendering, which caused subsequent examples in the same docstring to use non-interactive rendering. The fix is to surround each code block with turning interactive mode on just before the block and off right after.
> fix(docs): surround executable code blocks with interactive mode on/off

- ibis/backends/flink/__init__.py
- ibis/backends/flink/tests/test_ddl.py
- ibis/backends/tests/test_param.py
- ibis/backends/tests/test_register.py
Reviving https://github.com/ibis-project/ibis/pull/7777 which got closed after switching to `main`.
> test(flink): deep dive on the tests marked for Flink in test_json.py

- ibis/backends/base/sql/alchemy/datatypes.py
- ibis/backends/duckdb/tests/snapshots/test_datatypes/test_cast_to_floating_point_type/float32/out.sql
- ibis/backends/duckdb/tests/snapshots/test_datatypes/test_cast_to_floating_point_type/float64/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_geospatial_dwithin/out.sql
- ibis/backends/duckdb/tests/test_datatypes.py
- ibis/backends/tests/tpch/snapshots/test_h06/test_tpc_h06/duckdb/h06.sql
- ibis/backends/tests/tpch/snapshots/test_h11/test_tpc_h11/duckdb/h11.sql
- ibis/backends/tests/tpch/snapshots/test_h17/test_tpc_h17/duckdb/h17.sql
- ibis/backends/tests/tpch/snapshots/test_h20/test_tpc_h20/duckdb/h20.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/duckdb/h22.sql
Fixes a bug when compiling expressions to DuckDB sql. Discussed [in Zulip](https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/Issue.20with.20casting.20and.20sql.20genertion.20in.20duckdb).
> fix(duckdb): ensure that casting to floating point values produces valid types in generated sql

- ibis/backends/exasol/__init__.py
- ibis/backends/tests/test_window.py
- chore(exasol): avoid complex websocket callback for inserting memtables
- test(exasol): account for unordered results in window function tests
> fix(exasol): use slower but more reliable ddl and allow non-strict xfail on window function test

- ibis/backends/bigquery/registry.py
- ibis/backends/clickhouse/compiler/values.py
- ibis/backends/dask/execution/arrays.py
- ibis/backends/datafusion/compiler/values.py
- ibis/backends/duckdb/registry.py
- ibis/backends/pandas/execution/arrays.py
- ibis/backends/pandas/execution/generic.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/registry.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/snowflake/registry.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_map.py
- ibis/backends/tests/test_param.py
- ibis/backends/tests/test_sql.py
- ibis/backends/trino/registry.py
- ibis/expr/operations/arrays.py
- ibis/expr/tests/test_format.py
- ibis/expr/types/arrays.py
We were previously returning `ArrayColumn` from `ibis.array` when any inputs were expressions regardless of their shape. This PR renames `ArrayColumn` -> `Array` and uses the input arguments shapes to determine the output array shape.
Fixes #8022.
> fix(datatypes): ensure that array construction supports literals and infers their shape from its inputs

- docs/posts/ibis-duckdb-geospatial-dev-guru/index.qmd
- docs/posts/ibis-duckdb-geospatial/index.qmd
Adds instructions on installing duckdb with geospatial dependencies in the relevant blogs.
Request from [Zulip topic](https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/.E2.9C.94.20Error.20on.20referencing.20a.20DuckDB.20table.20with.20geospatial.20column/near/417345894).
> docs(blog): show how to install geospatial dependencies

- ibis/backends/conftest.py
- ibis/backends/tests/test_markers.py
I had a thought about a potential edge case with `None` being the only
listed "Exception" in a `raises` argument.  This fixes the edge case and
also adds some simple tests to make sure our custom markers correctly
handle when an imported backend exception is set to `None` due to a
missing import.
> test(markers): test the test markers

- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/tests/test_client.py
This started out as a "simple" effort to allow passing both `temp` and `overwrite` to `create_table` in DuckDB.  That works, and so I added a test.  And there my journey begins...
* Handle intersection of `temp=True` and `overwrite=True` in DuckDB and Oracle
* Fix drop table on oracle to handle dropping temp tables (this was missed in the port to sqlglot)
* Ensure that memtables on Oracle are both a) temporary and b) cleaned up on exit (another miss in the port)
* Add a missing `temp` kwarg to Exasol for API consistency
* Relax a check against the `temp` kwarg in Polars that was a bit too strict (`False` should be allowed)
I never got around to opening the issue, but this should resolve the problems @ncclementi was seeing trying to create a temp table in DuckDB with `overwrite=True`.
> fix(many): try to allow passing both overwrite and temp to create_table

- docs/posts/ibis-duckdb-geospatial/index.qmd
At the moment of writing this blog, there was a need to use[to_array()](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.to_array) to generate a scalar subquery from a table with a single column (whose shape is scalar). Otherwise it wouldn't work. For example: 
```python
sts_near_broad = streets.filter(_.geom.d_within(broad_station.select(_.geom).to_array(), 10))
```
However, a user posted on Zulip, that this wasn't needed. See [Zulip: Geospatial-not clear why `.to_array()` is required](https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/Geospatial.20-.20not.20clear.20why.20.2Eto_array.28.29.20is.20required/near/417987170)
After checking, the user is right, there is no need now for this. 
This PR, updates the queries accordingly
> docs(blog): update geospatial - no need to_array()

- compose.yaml
The `minio` container was failing to start in my local setup since `yes` was being parsed as `True` due to yaml's ~features~ weirdness. I'm assuming since this wasn't already failing in CI that some other version of docker-compose has patched around this yaml issue, but it's easy enough to fix it for everyone here.
> ci(docker): yes -> "yes" to avoid yaml parsing weirdness

- ibis/expr/operations/relations.py
- ibis/tests/expr/test_table.py
> fix(api): forbid using `asc`/`desc` in selections

- ibis/expr/types/relations.py
Most backends that do support a `seed` for table sampling don't document the range of possible values. Marking this as "backend specific", with a note that experimentally most support at least `[0, 2**32 - 1]`.
Fixes #8053.
> docs: document possible range of seed values to `Table.sample`

- ibis/backends/flink/__init__.py
After looking into the `raw_sql` implementation on some backends, I couldn't see any reason not to just rename `_exec_sql` (instead of wrapping it).
https://github.com/ibis-project/ibis/pull/7912#discussion_r1464204408
> refactor(flink): expose `raw_sql` over `_exec_sql`

- docs/contribute/03_style.qmd
Adding a first version of our unwritten style guide for prose and documentation.
Resolves #7094
> docs(style): add style guide to contributing

- ibis/expr/types/strings.py
This was giving me a `SyntaxError: invalid escape sequence '\.'`
> chore: escape "\." in re_split() docstring

- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
> fix(api): support passing literal booleans to `filter`

- compose.yaml
Turns out we do not need a separate volume for each druid service, including for test data. This PR unifies them all under a single `druid` volume.
> build(docker): remove extraneous druid docker volumes

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_sql.py
Adds a test for #7350.
Closes #7350.
> test(api): add test for alias generation

- ibis/backends/flink/__init__.py
- ibis/backends/flink/datatypes.py
- ibis/backends/flink/tests/test_ddl.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_export.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_join.py
The goal of this change is to support `to_csv()` and `to_parquet()` for the Flink backend. Adds `to_pyarrow()` and `to_pyarrow_batches()` in `Backend` class for Flink.
`Note to reviewers`: Please pay special attention on `get_field_data_types()` which I added to work around the "precision issue" in PyFlink.
> feat(flink): export result to pyarrow

- compose.yaml
- docker/risingwave/risingwave.toml
- ibis/backends/tests/test_json.py
Remove risingwave-specific minio service in favor of existing minio service.
> build(docker): simplify risingwave docker setup

- ibis/backends/duckdb/tests/snapshots/test_client/test_default_backend/out.sql
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/sqlite/tests/test_client.py
- ibis/backends/tests/test_client.py
- ibis/conftest.py
Moves some backend-specific tests in `ibis/backends/tests/test_client.py` to their respective backend test suite locations. The sqlite tests are moved, but not running (yet).
> test(duckdb): move tests to specific backend test suites

- ibis/backends/clickhouse/compiler/values.py
- ibis/backends/duckdb/registry.py
- ibis/backends/mssql/registry.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/tests/test_generic.py
- ibis/expr/operations/generic.py
- ibis/expr/types/strings.py
This adds support for `ops.HashBytes` to `mssql` and also adds a test for that functionality so it's easier to port when we merge in the epic split branch.
I've also added a new op, `HashHexDigest` which returns the hexdigest of various cryptographic hashing functions since I imagine this is what many users are _probably_ after.  This newer op (and corresponding `hexdigest` method) can also support many more backends, as most of them default to returning the string hex digest and not the raw binary output.
I tried to be very accurate in the `notimpl` and `notyet` portions of both tests and I think I've done that.
For now, only exposing DuckDB, Pyspark, and MSSQL so we don't add a huge extra burden for the epic split but also address the user request in #8082 
And I guess now we can …
> feat(mssql): add hashbytes and test for binary output hash fns

- ibis/backends/base/sqlglot/__init__.py
Fix for upstream removal in https://github.com/tobymao/sqlglot/pull/2884
Should we set a stricter upper bound on sqlglot before releasing 8.x?
> fix(sqlglot): stop using removed singletons for true, false, null

- compose.yaml
Revert 87525f5817 due to https://github.com/ClickHouse/ClickHouse/issues/59414.
> revert: chore(deps): update clickhouse/clickhouse-server docker tag to v24

- ibis/expr/types/relations.py
In IPython exceptions inside of _repr_mimebundle_ are swallowed to
allow calling several display functions and choosing to display
the "best" result based on some priority.
This behavior, though, means that exceptions that bubble up inside of the interactive repr
are silently caught.
We can't stop the exception from being swallowed, but we can force
the display of that exception as we do here.
A _very_ annoying caveat is that this exception is _not_ being
` raise`d, it is only being printed to the console.  This means
that you cannot "catch" it.
This restriction is only present in IPython, not in other REPLs.
I'm still trying to figure out the best way to test this.
Resolves #8137
> fix(repr): force exception message in IPython in interactive mode

- docs/_quarto.yml
- ibis/expr/types/geospatial.py
- ibis/expr/types/numeric.py
- Add docstring examples for duckdb geospatial functions
Closes #7959
TODO/Problems/need help
> docs(geospatial): add examples for duckdb supported  methods

- ibis/backends/flink/registry.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_map.py
Adds several new array operators for Flink backend. The goal with this is to clear as many of the tests in `ibis/ibis/backends/tests/test_array.py` as possible for the Flink backend.
> feat(flink): implement array operators

- ibis/common/tests/test_temporal.py
Replaces a flaky test with a reliable mock.
> test: replace flaky `today()` test with mock

- ibis/backends/base/sqlglot/tests/test_compiler.py
- ibis/common/patterns.py
- ibis/common/tests/test_patterns.py
Turns out one of the patterns were referencing non-existing fields and the `Object` pattern was still matching on it.
Fixes https://github.com/ibis-project/ibis/issues/8058.
> fix(common): don't match an `Object` pattern with more positional arguments defined than `__match_args__` has

- ibis/backends/conftest.py
- ibis/backends/flink/datatypes.py
- ibis/backends/flink/ddl.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/flink/tests/test_ddl.py
- ibis/backends/flink/tests/test_join.py
1. Added unit test for window join
2. Cleaned up some existing test files
3. Fixed a couple of bugs
A couple of notes:
1. The generated SQL is not an exact match to the example Flink has in their documentation. The one Ibis generates is a little more complicated, because it automatically turns them into subqueries and it's also not able to fuse the select statements automatically.
2. Right now only full outer join works. Other types of join have a different syntax in Flink, e.g. semi join looks like
```sql
SELECT *
FROM (
SELECT * FROM TABLE(TUMBLE(TABLE LeftTable, DESCRIPTOR(row_time), INTERVAL '5' MINUTES))
) L WHERE L.num IN (
SELECT num FROM (   
SELECT * FROM TABLE(TUMBLE(TABLE RightTable, DESCRIPTOR(row_time), INTERVAL '5' MINUTES))
) R WHERE L.window_start = R.window_start AND …
```
> test(flink): add unit test for window join

- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_join.py
It has been already fixed by [the rewrite converting the join chain to pairwise join operations](https://github.com/ibis-project/ibis/issues/7345
), so this only adds a test case.
Fixes https://github.com/ibis-project/ibis/issues/7345
Depends on https://github.com/ibis-project/ibis/pull/8127
> fix(polars): columns are picked from the correct side in case of conflicting names

- poetry.lock
- pyproject.toml
SQLGlot has a non-standard view of semver, documented here:
https://github.com/tobymao/sqlglot#versioning
TLDR: it's BIG_BREAKING.BREAKING.NONBREAKING
so we should hard pin major.minor.
Worth noting that this may not be strict enough.  It's unclear to me
whether the contents of `sqlglot.expressions` are considered public.  I
will ask.
-------
> chore(poetry): add strict upper bound to sqlglot

- ibis/expr/api.py
documenting `row_number`'s behavior
Resolves #8208
> docs: row_number always starts at 0

- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Discovered and fixed by @cpcloud: https://github.com/ibis-project/ibis/pull/8161#discussion_r1477098975
This PR covers it with a test case.
> fix(api): selection using a selector yielding multiple columns

- ibis/expr/types/arrays.py
- ibis/expr/types/core.py
- ibis/expr/types/dataframe_interchange.py
- ibis/expr/types/generic.py
- ibis/expr/types/geospatial.py
- ibis/expr/types/groupby.py
- ibis/expr/types/maps.py
- ibis/expr/types/numeric.py
- ibis/expr/types/pretty.py
- ibis/expr/types/relations.py
- ibis/expr/types/ruff.toml
- ibis/expr/types/strings.py
- ibis/expr/types/structs.py
- ibis/expr/types/temporal.py
- ibis/expr/types/typing.py
- pyproject.toml
The `ruff.toml` file in `ibis/expr/types` was causing the module to be ignored by `ruff`. This PR removes that file since it is no longer necessary, and fixes the resulting lint and format issues. I also added a new ignore rule to prevent an additional newline from being added to the end docstrings (`D413`).
> chore: remove ruff.toml causing types directory to be ignore and fix subsequent lint errors

- ibis/backends/tests/test_array.py
Fixes a flaky risingwave test noticed in #8161.
> test(risingwave): make unnest test not flaky

- ibis/backends/tests/test_array.py
Cleans up more array tests to disregard row output order using set comparison.
> test(arrays): disregard row output order when testing array APIs

- docs/index.qmd
add a button on the home page that goes to the blog
> docs: add blog link on the homepage

- .codespellrc
- .github/workflows/ibis-backends-skip-helper.yml
- .github/workflows/ibis-backends.yml
- pyproject.toml
I really like `pyproject.toml` and having one place to look.  But
running the full backend test suite because we need to add a word to an
"ignore-list" for codespell is silly.
So, breaking it out into a `.codespellrc` file so that it can be updated
without triggering a full CI run.
I have some other ideas for reducing build times for unrelated changes but I'll open an issue to document and track those.
> ci(codespell): separate codespell config into standalone file

- .github/workflows/check-generated-files.yml
- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-main.yml
Currently our CI fails when codecov fails to upload, which has been happening more frequently after
the upgrade to `codecov-action@v4`.
This PR allows the codecov step to fail to upload, since:
1. It's not a useful enough indicator of a failed build.
2. It's likely to pass on the next run, as it's often a transient issue.
> ci: allow codecov uploads to fail

- ibis/expr/rules.py
- ibis/tests/expr/test_decimal.py
This change is removing the decimal precision promotion logic from the unbounded ibis expr. The logic was introduced by #4330 so the decimal precision can matches the [DB2](https://www.ibm.com/docs/en/i/7.1?topic=operators-decimal-arithmetic-in-sql). However, this rule is not generic for all. For example, BQ only support `precision=38`. 
* Resolves #8189
> refactor(ir): remove the decimal precision promotion logic

- .github/workflows/docs-preview.yml
Right now our docs previews always run to completion, even if a new commit is pushed to the same PR. This PR will cancel in progress jobs if a new commit is pushed to a PR.
> ci: eagerly cancel docs previews

- environment.yml
current issues:
- lonboard pins pyarrow >14 so not installing it
- quarto on conda-forge is on 1.3 for the moment, so dashboards don't
work (this should be temporary)
> chore(dev-deps): add environment.yml file for ibis development

- .pre-commit-config.yaml
I was getting "warning: The `--show-source` argument is deprecated. Use `--output-format=full` instead." in
https://github.com/ibis-project/ibis/actions/runs/7805418174/job/21289589595?pr=7915
This is the new API in [ruff 0.2.0](https://github.com/astral-sh/ruff/releases/tag/v0.2.0), and we now have that version
of ruff pinned.
> chore: update flags for ruff 0.2.0

- ibis/tests/expr/test_table.py
> test(api): add test for `Table.select` on literals

- ibis/formats/pyarrow.py
- ibis/formats/tests/test_pyarrow.py
> fix(datatypes): convert UUIDs to strings

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/tests/sql/snapshots/test_select_sql/test_exists_subquery/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_filter_inside_exists/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_exists/e1.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_exists/e2.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_not_exists/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_self_reference_in_not_exists/anti.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_self_reference_in_not_exists/semi.sql
- ibis/backends/tests/tpch/snapshots/test_h04/test_tpc_h04/duckdb/h04.sql
- ibis/backends/tests/tpch/snapshots/test_h04/test_tpc_h04/trino/h04.sql
- ibis/backends/tests/tpch/snapshots/test_h21/test_tpc_h21/duckdb/h21.sql
- ibis/backends/tests/tpch/snapshots/test_h21/test_tpc_h21/trino/h21.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/duckdb/h22.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/trino/h22.sql
- ibis/expr/operations/__init__.py
- ibis/expr/operations/relations.py
- ibis/expr/operations/subqueries.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/logical.py
- ibis/tests/expr/test_table.py
Also move the subquery operations to a separate file.
> refactor(ir): accept any relation in `ops.ExistsSubquery`

- ibis/backends/base/sqlglot/__init__.py
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/bigquery/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/clickhouse/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/datafusion/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/duckdb/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/exasol/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/impala/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/mssql/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/mysql/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/oracle/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/postgres/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/pyspark/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/risingwave/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/snowflake/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/sqlite/out.sql
- ibis/backends/tests/snapshots/test_dot_sql/test_cte/trino/out.sql
- ibis/backends/tests/test_dot_sql.py
Addresses flaky testing observed in https://github.com/ibis-project/ibis/actions/runs/7811784691/job/21307516496, ultimately coming from two concurrent runs of the BigQuery backend test suite trying to create the same table. Here I changed the test to compare against an equivalent sqlglot expression instead of using a snapshot test.
> test(dot-sql): replace snapshot test with sqlglot compilation test to avoid clashing table names

- ibis/backends/base/sqlglot/compiler.py
`ops.Project` cannot reach the SQL compiler because the rewrites rule are replacing it with a SQL specific `Select` node.
> chore(sql): remove unused `ops.Project` compile method

- docs/_quarto.yml
- justfile
Explicitly listing out the members of `_DateComponentMixin` and
`_TimeComponentMixin` where relevant.
A bit verbose, but I also don't imagine these changing all that often.
Or maybe we can add support to `quartodoc` at some point to exclude
inheriting from certain parents?  dunno.
Fixes #8179
> docs(api): expose relevant mixin members in temporal docs

- ibis/backends/tests/test_array.py
- ibis/expr/types/arrays.py
fixes https://github.com/ibis-project/ibis/issues/8180
> feat(api): support Deferreds in Array.map and .filter

- .devcontainer/updateContent.sh
- docs/how-to/analytics/imdb.qmd
- docs/how-to/input-output/duckdb-parquet.qmd
- docs/tutorials/data-platforms/clickhouse.qmd
Moves content except for `Substrait.ipynb` to a new `Examples` tab in our documentation. `Substrait.ipynb` has multiple issues which need to be addressed if we want to include it. I opted for not including it at the moment.
> docs: populate docs with `ibis-examples` repo content

- .github/workflows/ibis-backends-cloud.yml
I had this thought the other day -- instead of relying on someone with cloud credentials, sometimes we might want to trigger the cloud runs on a PR manually.  So this does that following the same pattern as our docs preview.  Need to add the label `ci-run-cloud` and it should kick off bigquery and snowflake.
If we're game to try this, we can also make it more specific, and have labels for only running bigquery or snowflake, but before I start writing a GHA matrix generator I thought I'd see how folks feel about this.
> ci(clouds): allow running cloud backends with github label

- docs/backends/risingwave.qmd
-------
Adds a backend docs page for the RisingWave backend.
> docs(risingwave): add backend docs page for RisingWave

- docs/posts/why-voda-supports-ibis/index.qmd
- genuinely no idea why I thought today was the 10th, I updated that this morning
- remove some links that are relics from this being a combined roadmap blog (could re-link once published)
> docs: change date and remove links from why voda blog

- ibis/backends/base/sql/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/tests/test_dot_sql.py
- ibis/backends/trino/__init__.py
`.sql` tests can now run in separate processes because the implementation is no longer stateful
> test(sql): remove xdist_group marker for `.sql` tests

- ibis/backends/duckdb/tests/test_udf.py
- ibis/expr/operations/udf.py
- ibis/tests/expr/test_udf.py
This PR fixes the error thrown when trying to create a `udf.scalar.builtin` for an function that takes no arguments, for example
```python
@ibis.udf.scalar.builtin
def version() -> str: ...
version()
```
Thank you @gforsyth for the help troubleshooting this, as it wasn't that straightforward to figure out the core issue.
For a bit more context, the error was happening because when we had a udf that takes no arguments, then the shape check happening here: 
```python
@public
class ScalarUDF(ops.Value):
shape = rlz.shape_like("args")
```
was failing, because there are no arguments to grab the shape of.
This fix, now takes cares of that by  defaulting to a scalar shape when this happens. 
Closes https://github.com/ibis-project/ibis/issues/8256
> fix(duckdb): udfs builtins taking zero args

- .devcontainer/devcontainer.json
Allows use of the duckdb cli in our dev container
> build(dev-tools): enable duckdb cli in the github dev container

- ibis/backends/datafusion/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/exasol/compiler.py
- ibis/backends/mssql/compiler.py
- ibis/backends/oracle/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/tests/sql/snapshots/test_sql/test_no_cart_join/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_order_by_expr/out.sql
- ibis/backends/tests/test_string.py
- ibis/expr/types/strings.py
> fix(backends): make string concat-with-null behavior consistent across backends

- docs/posts/ibis-version-8.0.0-release/index.qmd
Fixes a broken link in the 8.0 release notes.
> docs(links): fix release notes link in 8.0 release

- ibis/tests/benchmarks/test_benchmarks.py
This PR removes pandas execution benchmarks, whose performance has gotten much
worse after `the-epic-split` merge.
IMO, there are good reasons to avoid benchmarking backend execution in Ibis,
the main one being that execution is not a part of Ibis that we can control.
That isn't true of the Pandas backend, but since the DuckDB backend can now do
everything the pandas backend could do after merging `the-epic-split`
--including `asof_join`--we are not going to spend any time improving the
performance of the pandas backend,
I would actually vote to remove all execution tests here, and keep only the
ones that benchmark expression compilation and construction.
> refactor(benchmarks): remove pandas benchmarking and replace with more-representative duckdb version

- ibis/tests/benchmarks/test_benchmarks.py
xref: https://github.com/tobymao/sqlglot/issues/2961. This lowers the number of tables in the test to avoid hitting issues with sqlglot.
> chore: lower the test set size of big unions

- docs/posts/ibis-duckdb-geospatial/index.qmd
I thought that I fixed it a while ago, but the errors are not surfacing from the ipython cells, so we need to check the rendered output.
> docs: update the geospatial blogpost to use explicit scalar subqueries

- .github/workflows/ibis-docs-main.yml
Now that the geospatial blog rendering has been fixed, we can re-enable docs publishing
> ci: enable docs publishing again

- ibis/formats/pyarrow.py
- ibis/formats/tests/test_pyarrow.py
Previously we were mapping our `Date` type to `pa.date64`. Here I propose we map to `pa.date32` instead. This is what `pa.Table.from_pandas` does for date columns. Also support for `date32` seems to be more common across backends with native arrow support.
> fix(pyarrow): map date type to arrow date32 not date64

- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
Pass through additional kwargs that are parsed out of a connection string and send them on to the `psycopg2.connect` call.
Resolves #8168
xref #8190
> fix(postgres): pass through additional kwargs in pguri

- .github/workflows/docs-preview.yml
- .github/workflows/ibis-backends-cloud.yml
This PR attempts to address an issue when running cloud CI along with our docs preview.
The issue is that when you run one, it clobbers the other.
This is because for a given workflow, the other is skipped, which will clobber
an existing run **from the other workflow**.
Let's walk through a scenario:
1. Label a PR with `docs-preview`
1. This creates a concurrency group with the name `ibis-project-$SHA-Docs Preview` and kicks off a job.
1. While that job is running, you add the `ci-run-cloud` label.
1. Both the `docs-preview` and `ci-run-cloud` workflows are invoked, because they are run on `pull_request_target` events with `labeled` type.
1. The `docs-preview` **workflow** runs, **under the same concurrency group** and is thus cancelled, because `cancel-in-progress` is set to `true`.
1. …
> ci: prevent labelled workflows from clobbering each other

- ibis/backends/base/__init__.py
- ibis/backends/base/sqlglot/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/dask/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/pandas/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/tests/test_client.py
- ibis/tests/expr/mocks.py
This adds a `disconnect` method to all backends.  Previously we didn't do
this since the actual connection was often wrapped in SQLAlchemy and our
ability to terminate the connection was unclear.
The DB-API spec states that there should be a `close` method, and that
any subsequent operations on a given `Connection` should raise an error
after `close` is called.
This _mostly_ works.
Trino, Clickhouse, Impala, and BigQuery do not conform to the DB-API in
this way.  They have the `close` method but don't raise when you make a
subsequent call.
Spark is not a DB-API, but the `spark.sql.session.stop` method does the right thing.
For the in-process backends I've chosen to raise, since I don't think
there's a clear meaning on what closing that connection would mean, but
happy to take any …
> feat(api): add disconnect method

- ibis/common/temporal.py
- ibis/expr/datatypes/cast.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_cast.py
- ibis/expr/datatypes/value.py
- ibis/expr/rules.py
- ibis/tests/expr/test_timestamp.py
This makes it easier to understand the implicit casting rules.
> refactor(dtype): move all the castable logic to a single function

- ibis/expr/tests/test_newrels.py
- ibis/expr/types/core.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
Since there is no safe way to determine whether a table or a column contains a single cell we need to provide a way for the users to inform ibis that it should treat an expression as a scalar subquery. Previously it was the `.to_array()` method, but it only worked for table expressions. 
Note that when a scalar reduction is passed to certain API methods ibis is able to infer that the value should be turned into a scalar subquery and it implicitly does it. Using this method can be omitted in those cases.
> feat(api): add `.as_scalar()` method for turning expressions into scalar subqueries

- ibis/backends/tests/test_join.py
Skips test cases that can cause a timeout.
> test(risingwave): skip semi join test that times out

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/datafusion/compiler.py
- ibis/backends/druid/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/exasol/compiler.py
- ibis/backends/flink/compiler.py
- ibis/backends/impala/compiler.py
- ibis/backends/mssql/compiler.py
- ibis/backends/mysql/compiler.py
- ibis/backends/oracle/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/risingwave/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/sqlite/compiler.py
- ibis/backends/trino/compiler.py
Follow up to #8338 to clean up the SIMPLE_OPS boilerplate.
> refactor(sql): automatically add simple ops implementations

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/base/sqlglot/rewrites.py
- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/dask/tests/test_strings.py
- ibis/backends/druid/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/impala/tests/snapshots/test_string_builtins/test_string_builtins/capitalize/out.sql
- ibis/backends/impala/tests/test_exprs.py
- ibis/backends/mssql/compiler.py
- ibis/backends/mysql/compiler.py
- ibis/backends/pandas/tests/test_strings.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/tests/test_functions.py
- ibis/backends/risingwave/tests/test_functions.py
- ibis/backends/sqlite/udf.py
- ibis/backends/tests/test_string.py
- ibis/expr/types/strings.py
Fixes #8271.
BREAKING CHANGE: Backends that previouslly used `initcap` (analogous to `str.title`) to implement `StringValue.capitalize()` will produce different results when the input string contains multiple words (a word's definition being backend-specific).
> fix(strings): make `StringValue.capitalize()` consistent across backends

- ibis/expr/operations/subqueries.py
- ibis/tests/expr/test_value_exprs.py
> fix(ir): compute `InSubquery.shape` property from `needle` input

- ibis/backends/base/sqlglot/compiler.py
- ibis/backends/impala/tests/snapshots/test_sql/test_is_parens/isnull/out.sql
- ibis/backends/tests/test_generic.py
We wrap arguments to a `sge.Equals` in parens if the inputs are
themselves binary operations.  There are other operations we will have
to wrap -- for now I'm just adding `isNull` to the list, but I imagine
this will grow, possibly on a backend-by-backend basis.
I'm going to investigate the mssql and oracle failures but they are
unrelated to this PR (they fail the added test with or without the parentheses)
* Resolves #8346
> fix(comparison): wrap isnull equality check in parens

- ibis/backends/duckdb/compiler.py
- ibis/backends/tests/test_struct.py
Fixes #8360 by overriding duckdb's visit_StructColumn and corresponding literal branch translation.
> fix(duckdb): ensure that structs can be used with sqlglot 20.1.0

- ibis/backends/base/__init__.py
Our `_from_url` was a little aggressive in calling `Path().absolute()`
on targets. Since we already handle that in `duckdb.do_connect` we can
use `urlparse` to rip out the appropriate bits and forward them.
Fixes #8355
> fix(duckdb): allow connection to motherduck via ibis.connect

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_datatypes.py
Turns out we are artificially restricting the input of all-null columns in memtables. This works out of the box by simply deleting the check that raises an exception.
> feat(duckdb): allow all-null columns in memtables

- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/snowflake/__init__.py
Fixes an issue where we try to pluck package metadata for a non-existent package (`snowflake-connector-python`) when transpiling from one dialect to another; in this case duckdb sql to snowflake sql.
> fix(duckdb-sql): ignore importlib package errors when importing ibis.snowflake for transpilation

- pyproject.toml
Removes dead conda-lock configuration in `pyproject.toml`.
> chore: remove conda-lock from pyproject.toml

- docs/posts/why-duckdb/index.qmd
> docs(blog): blog on why DuckDB is the default backend

- .github/workflows/ibis-backends.yml
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/tests/test_register.py
Fixes an issue where we were not testing `to_delta` for pyspark in CI and breakage to its `to_delta` method after the-epic-split crept in due to the return type of `compile()` being a `str` now instead of pyspark DataFrame.
> fix(pyspark): ensure to_delta works and is tested in ci

- ibis/backends/base/sqlglot/datatypes.py
- ibis/backends/mssql/tests/test_client.py
See https://learn.microsoft.com/en-us/sql/relational-databases/hierarchical-data-sql-server?view=sql-server-ver16
for reference.
We represent this as a string column internally in Ibis (this seems to
be the recommended thing to do by MSSQL itself).
Resolves #8381
> feat(mssql): add datatype mapping for `hierarchyid`

- ibis/backends/base/sqlglot/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sqlite/__init__.py
Removes dupcliated udf registration and default failure mode logic for sql backends.
> refactor(udfs): consolidate builtin udf compilation and failure modes for unimplemented udfs

- ibis/backends/mssql/compiler.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_window.py
I took a look through what sqlalchemy was generating for these failing
test cases and then reimplemented it using sqlglot.
Any and All:
* Instead of `logical or` we do a `Max(IIF(condition, 1, 0))`
* Instead of `logical and` we do a `Min(IIF(condition, 1, 0))`
Cumulative versions:
The cumulative versions work, but required an additional check in the
`visit_Not` node. MSSQL doesn't support doing `IFF(MAX(IFF(...` -- the
argument to IFF has to be a boolean and the Window function isn't
considered a boolean for some reason, so the outer conditional needs to
be a case statement.- fix(mssql): restore any, all and cumulative versions
- fix(mssql): support aggregations with any/all
* Resolves #8073
> fix(mssql): restore any, all and cumulative versions

- ibis/backends/mssql/compiler.py
- ibis/backends/tests/test_numeric.py
- ibis/backends/tests/test_window.py
MSSQL requires an order-by clause in unbounded windows.  This is clearly
documented in
https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors-10000-to-10999
(just kidding, it's a huge list of error codes you have to scroll through.  You
want Error 10756)
The behavior of the mssql sqlalchemy connector is to order by the field used in
the window function.  This seems silly, and potentially slightly
computationally wasteful, but not incorrect.
So, I've added a rewrite rule to the MSSQL compiler that copies this behavior
for all reduction functions that aren't UDFs, since those aren't supported
anyway (and would require a different rewrite rule, in any case).
* Resolves #8072
> fix(mssql): restore unbounded window functions

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
Snowflake supports connecting with no arguments using [`connections.toml`](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-connect#connecting-using-the-connections-toml-file), but snowflake-connector-python does not work when passing sessions parameters and no connection arguments. The workaround is to set session parameters after connecting.
> feat(snowflake): support connecting with no arguments

- ibis/common/typing.py
> chore: resurrect `SupportsSchema` type; clean up unused ignored imports

- ibis/backends/sql/__init__.py
- ibis/common/typing.py
- ibis/expr/api.py
- ibis/expr/schema.py
- ibis/expr/types/relations.py
This is a follow-up to #8421.
- The use of a `TypeVar` here was incorrect - what you want is a `TypeAlias` instead. The previous version would cause type checkers to error.
- I moved the type definition to be adjacent to `Schema`. This makes the import paths cleaner since you don't need as many `if TYPE_CHECKING` blocks. Logically it also makes sense to me to put the union of schema-like things next to the `Schema` code.
- I renamed the type alias to `SchemaLike` which reads better IMO.
> refactor: rename SupportSchema -> SchemaLike, fix type definition

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
Follow-up to #8422 to support that behavior in `ibis.connect()`.
> feat(snowflake): allow empty url when using ibis.connect

- docs/how-to/extending/sql.qmd
- ibis/config.py
> docs: clean up cursor closing and link to `Table.sql` API docs

- ibis/backends/tests/test_window.py
Fixes the failing upstream snowflake test caused by snowflake not supporting window frames sizes larger than 1000.
> test(snowflake): xfail on test with window larger than 1000

- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/impala/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/risingwave/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/sqlite/compiler.py
- ibis/backends/sqlite/udf.py
- ibis/backends/tests/test_uuid.py
- ibis/backends/trino/compiler.py
- ibis/expr/api.py
- ibis/expr/operations/generic.py
- ibis/tests/expr/test_uuid.py
Fixes #8257.
We implemented a bunch of these in a pairing session - there are still a few lingering backends that we should be able to support (but weren't added in this PR):
- `mssql`, `flink`, `pyspark`, `datafusion`, and `oracle` (through existing SQL functions)
- `pandas`, `dask`, maybe `polars` (through shelling out to a python udf)
> feat(api): add a `uuid` function for returning a new uuid

- ibis/backends/flink/compiler.py
- ibis/backends/flink/datatypes.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/sql/datatypes.py
- ibis/backends/tests/test_map.py
- ibis/backends/tests/test_udf.py
Adds `MAP` support for Flink backend. Addresses item 9 in https://github.com/ibis-project/ibis/issues/8250.
> feat(flink): add map support

- flake.nix
- nix/overlay.nix
Tiny PR to switch the default version of Python in the nix setup to be 3.11. Previously we avoided this because we did not support a version of PySpark that supported Python 3.11, but now we do (PySpark 3.5).
> chore(deps): default to python 3.11 with nix

- ibis/expr/operations/core.py
- ibis/expr/tests/test_api.py
Fixes #8432. In short, the pattern we are using here for accessing `name` results in exponential growth of attribute accesses.
> perf(ir): avoid exponential growth on `name` attribute access

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/docs-issue.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/new-backend.yml
now that I've seen it, annoys me a lot -- the one we can't customize (?) has a period at the end, none of the others do:
> chore: add period to end of issue templates for consistency

- ibis/expr/rewrites.py
-------
I don't know if just aren't using these rewrites or aren't testing them. 
Anyway, quick PR to remove the now renamed `ops.TableColumn` -- if it makes more sense to rip out the rewrites, I can do that instead.
> fix(rewrites): change `TableColumn` -> `Field` in rewrites

- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/snowflake/converter.py
- ibis/backends/snowflake/tests/conftest.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/tests/test_client.py
- ibis/formats/pyarrow.py
Localize custom pyarrow json serialization to snowflake. This custom type doesn't compose well (e.g., inside structs, which aren't directly supported in snowflake anyway) and was causing problems for other backends when trying to convert rows into a struct of the table schema and then into a proper table.
Fixes #8318.
> fix(postgres): fix json type conversion in `to_pyarrow` output

- ibis/expr/analysis.py
- ibis/expr/types/core.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
- ibis/expr/types/structs.py
- ibis/selectors.py
There were just a couple of places left where `find_first_base_table()` was still in use. Since the epic split refactor the preferred way to retrieve parent relation(s) is the `value.relations` property.
> refactor(ir): remove `find_first_base_table()` analysis function

- ibis/expr/operations/analytic.py
- ibis/expr/operations/reductions.py
Since `the-epic-split` refactor these properties are not used anymore.
> refactor(ir): remove now obsolete `__window_op__` property

- ibis/backends/impala/tests/test_window.py
- ibis/backends/pandas/tests/test_window.py
- ibis/backends/postgres/tests/test_functions.py
- ibis/backends/risingwave/tests/test_functions.py
- ibis/backends/sql/rewrites.py
- ibis/expr/api.py
- ibis/expr/builders.py
- ibis/expr/operations/window.py
- ibis/tests/expr/test_window_frames.py
This feature was only supported by the pandas backend, but wasn\'t tested
properly and the support for it was entirely removed in the-epic-split refactor.
BREAKING CHANGE: `ibis.rows_with_max_lookback()` function and `ibis.window(max_lookback)` argument are removed
> refactor(api): remove now unsupported `max_lookback` window attribute

- ibis/expr/tests/test_newrels.py
- ibis/expr/types/relations.py
For consistency with `.select()` and `.filter()`.
Fixes https://github.com/ibis-project/ibis/issues/8461
> feat(api): support `Table.order_by(*keys)`

- ibis/backends/sql/rewrites.py
- ibis/backends/tests/test_generic.py
- ibis/expr/tests/test_newrels.py
After `the-epic-split` refactor we concatenated successive ordering keys (due to squashing selections) which can result in multiple order statements referring the same value expression. As turned out this can lead ambiguous behaviour based on the backend, so now we overwrite repeated order keys. 
For expression
```py
t.order_by(ibis.desc("a")).order_by("a")
```
Previously we compiled to:
```sql
SELECT t.a FROM t ORDER BY t.a DESC, t.a ASC
```
Now we compile to:
```sql
SELECT t.a FROM t ORDER BY t.a ASC
```
Fixes https://github.com/ibis-project/ibis/issues/8442
> fix(sql): overwrite the original sort key on successive order_by calls using the same key

- ibis/backends/sql/dialects.py
The previous workaround for temp tables in Oracle was quite brittle and broke
when I tried to bump our upper pin on `sqlglot`. I've refactored it to be
(hopefully) less brittle ~and also bumped the `sqlglot` pin up a few versions.~
Dropping the version bump from this PR, there are some breaking changes for postgres, risingwave, and trino, looks like.
> refactor(oracle): remove dependency on private function for temp tables

- ibis/backends/duckdb/compiler.py
- ibis/backends/tests/test_struct.py
> fix(duckdb): parenthesize argument to StructField operation to support field access on CASE statements

- ibis/backends/impala/__init__.py
- ibis/backends/impala/tests/conftest.py
Remove the creation of temporary resources in the Impala backend, which are no longer used after the HDFS removal (these temp resources were used as scratch space for things like dataframe csvs). Fixes #8466.
> fix(impala): remove no-longer-used temporary database and paths that may prevent connection success

- docs/contribute/05_reference.qmd
per style guidelines, edit the capitalization
also changes the title style, inline w/ the local docs but out of line w/ the rest of the docs
> chore(docs): remove title case capitalization from test class reference

- ibis/backends/clickhouse/tests/test_datatypes.py
- ibis/backends/sql/datatypes.py
- ibis/backends/tests/test_array.py
This PR makes ClickHouse arrays non nullable. I ran into the issue when trying to convert text to an array of float values as part of a RAG pipeline and run into this error:
```text
File ~/Library/Caches/pypoetry/virtualenvs/ibis-clickhouse-ZMCVYiHj-py3.11/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py:361, in HttpClient._error_handler(self, response, retried)
359     err_msg = common.format_error(err_content.decode(errors='backslashreplace'))
360     err_str = f':{err_str}\n {err_msg}'
--> 361 raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
DatabaseError: :HTTPDriver for http://localhost:8123 returned response code 500)
Code: 43. DB::Exception: Nested type Array(Nullable(Float64)) cannot be inside Nullable type. …
```
> fix(clickhouse): make arrays non nullable

- conda/environment-arm64-flink.yml
- conda/environment-arm64.yml
- conda/environment.yml
Looks like pandas 2.2 breaks many things, so setting the dependency for <2.2 for now.
> chore: pin pandas <2.2 on conda envs

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_basic.py
> feat(pyspark): support `ibis.pyspark.connect()`

- conda/environment-arm64-flink.yml
- conda/environment-arm64.yml
- conda/environment.yml
- docs/contribute/01_environment.qmd
- docs/contribute/02_workflow.qmd
This PR includes
- Update to the arm64 enviornments to include quarto via conda-forge since now it's available.
- Update to docs to contributing guidelines and testing, including a doc on how to setup colima.
Closes: #8372
> docs: update contributing docs and env for m1/m2 devs

- ibis/expr/types/relations.py
Adds `-> Table` to the signature of `pivot_wider` to ensure consistency with the other `Table` methods.
Each `Table` method with an indicated `Table` return in their docstring also has a corresponding `-> Table` in their signature, except `pivot_wider`, where no return typehint was present.
> chore: add return `Table` typehint to `pivot_wider`

- ibis/expr/operations/analytic.py
The existing example was not self-contained. Upon execution, it raised an error as `dt.int64` could not be resolved.
```python
>>> import ibis
>>> t = ibis.table([("values", dt.int64)])  # NameError: name 'dt' is not defined
>>> w = ibis.window(order_by=t.values)
>>> row_num = ibis.row_number().over(w)
>>> result = t[t.values, row_num.name("row_num")]
```
This PR adds the missing `import ibis.expr.datatypes as dt` statement.
> docs: add missing import to `RowNumber` example

- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Fixes https://github.com/ibis-project/ibis/issues/8504
> feat(api): support variadic arguments on `Table.group_by()`

- justfile
Noticed in https://github.com/ibis-project/ibis/pull/8541 after changing the flink dockerfile that the image hasn't been rebuilt.
> chore(docker): ensure that `just up <backend>` builds the image if necessary

- docs/contribute/01_environment.qmd
Instead of defaulting to `pip` for environment setup, list in order
conda -> nix -> pip since we don't recommend using `pip` for this anyway.
> docs(development): move pip to end of env creation tabset

- docs/concepts/composable-ecosystem.qmd
- docs/concepts/internals.qmd
- gen_redirects.py
> docs(concepts): remove outdated refs to SQLAlchemy

- ibis/backends/bigquery/compiler.py
- ibis/backends/flink/compiler.py
- ibis/backends/impala/compiler.py
- ibis/backends/impala/tests/snapshots/test_window/test_add_default_order_by/out.sql
- ibis/backends/mssql/compiler.py
- ibis/backends/mysql/compiler.py
- ibis/backends/oracle/compiler.py
- ibis/backends/pandas/executor.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/sql/compiler.py
- ibis/backends/sql/rewrites.py
- ibis/backends/sqlite/compiler.py
- ibis/backends/tests/snapshots/test_sql/test_union_aliasing/clickhouse/out.sql
- ibis/backends/tests/snapshots/test_sql/test_union_aliasing/duckdb/out.sql
- ibis/backends/tests/snapshots/test_sql/test_union_aliasing/postgres/out.sql
- ibis/backends/tests/test_window.py
- ibis/backends/trino/compiler.py
- ibis/expr/operations/analytic.py
During recent refactors the `FirstValue`/`LastValue` have been pretty much removed from the codebase - at this point they only exist since some backends require spelling `first`/`last` as `first_value`/`last_value` when used in a window function context (other backends alias `first`/`last` to these for nicer SQL UX).
This PR:
- Moves `FirstValue`/`LastValue` to `ibis/backends/sql/rewrites.py` to treat them as SQL-specific IR.
- Refactors the `First -> FirstValue`/`Last -> LastValue` window function rewrites to always apply for all SQL backends, making our compilation more uniform here.
> refactor(sql): simplify `FirstValue`/`LastValue` usage

- docs/how-to/extending/unbound_expression.qmd
Add a tutorial for executing unbound expressions on backends
Resolves #8297
> docs(how-to): add a how-to guide for executing unbound expressions on backends

- ibis/backends/tests/test_numeric.py
This fixes a test that was failing for bigquery (due to a divide-by-0 error). By adjusting the input data to not trigger this issue (what `cot(0)` does varies by backend) we can also remove all the other failure markers from the test.
> ci: failing cotangent test

- docs/why.qmd
adds a "Python + SQL: better together" section to the "Why Ibis?" conceptual documentation inline with #8524
adding Polars for consistency w/ the above example blocked on #8525
might need more prose
> docs: add Python + SQL section to why ibis

- ibis/tests/benchmarks/test_benchmarks.py
This PR gets benchmarks passing again. Nesting levels were increased by https://github.com/ibis-project/ibis/pull/8414.
Unfortunately, SQLGlot's SQL generation algorithm (but not its parsing algorithm) is recursive.
This means that it cannot handle large nesting levels of select statements.
Pre-SQLGlot, Ibis used to handle much larger nesting levels. This functionality was lost in the sqlglot refactor.
Ultimately, someone needs to address this upstream in sqlglot by converting the generation algorithm to an iterative
one.
I believe we should gain a little bit back after #8572 is merged, since fewer select statements will be generated.
> test(bench): reduce big union join threshold

- ibis/backends/exasol/compiler.py
- ibis/backends/tests/test_temporal.py
Add custom TimestampTruncate for exasol in order to support `week` based truncation.
> refactor(exasol): add custom TimestampTruncate

- ibis/backends/sql/rewrites.py
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/bigquery/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/clickhouse/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/datafusion/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/druid/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/duckdb/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/exasol/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/flink/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/impala/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/mssql/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/mysql/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/oracle/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/postgres/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/pyspark/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/risingwave/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/sqlite/out.sql
- ibis/backends/tests/snapshots/test_generic/test_many_subqueries/trino/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_subquery_in_union/out.sql
While the CTE extraction worked properly, the CTEs haven't been replaced in the already extracted CTEs meaning that we didn't recursively replace.
> fix(sql): replace CTEs within CTEs

- .github/workflows/check-generated-files.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-benchmarks.yml
- .github/workflows/ibis-main.yml
- .github/workflows/nix-skip-helper.yml
- .github/workflows/nix.yml
- flake.nix
- ibis/backends/tests/test_temporal.py
- ibis/common/temporal.py
- ibis/common/tests/snapshots/test_annotations/test_signature_from_callable_with_keyword_only_arguments/missing_a_required_argument.txt
- ibis/common/tests/test_annotations.py
- ibis/common/tests/test_temporal.py
- ibis/expr/datatypes/tests/test_value.py
- ibis/expr/types/strings.py
- ibis/formats/pandas.py
- ibis/tests/expr/test_literal.py
- nix/overlay.nix
- poetry-overrides.nix
- pyproject.toml
Add 3.12 job and support in our nix builds and environment; fixes warnings about utcfromtimestamp from ibis code and ignores them in testing due to their use at the top level of dateutil.
> fix(deps): support python 3.12

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_geospatial.py
This PR add support for duckdb geospatial operations directly on geospatial literals. 
I gave this a try, I'm not sure this is the best way to go, but happy to iterate over it if there is a better way around. 
Closes: https://github.com/ibis-project/ibis/issues/8143
cc: @gforsyth (thanks for the pointer to `_run_pre_execute_hooks`)
> feat(geospatial): add support for duckdb operations on literals

- ibis/expr/types/arrays.py
- ibis/tests/expr/test_value_exprs.py
Fixes #8553, supersedes #8552.
We can't realistically catch the invalid use of deferred sin the original issue, but we can ensure that in the case the deferred resolves to something valid we raise a nice error message rather than whatever `inspect.signature` happens to raise.
> fix(api): improve error message raised on improper calls to array `map` or `filter`

- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_window.py
> fix(snowflake): bring back default nth behavior from before the-epic-split

- ibis/expr/types/core.py
The docstring for to_delta in core.py seems copied from to_csv, I updated it to match the docstring here: https://github.com/ibis-project/ibis/blob/e94366700ae460052f675188674e24002b755ec5/ibis/backends/__init__.py#L536
> docs: update to_delta kwargs docs

- ibis/backends/dask/tests/test_udf.py
- ibis/backends/dask/tests/test_window.py
- ibis/backends/datafusion/tests/test_udf.py
- ibis/backends/pandas/tests/test_functions.py
- ibis/backends/pandas/tests/test_udf.py
- ibis/backends/pandas/tests/test_window.py
- ibis/backends/polars/tests/test_udf.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_vectorized_udf.py
- ibis/backends/tests/test_window.py
- ibis/expr/tests/test_format.py
- ibis/legacy/udf/vectorized.py
This PR adds warnings for deprecation of `ibis.legacy.udf` for `v9.0`. I'm not super sure about the `instead` message for `elementwise`, suggestions are welcomed. 
According to the issue, seems like we are not going to support `analytic` and `reduction` on the new system, hence the empty comment on `instead`
- Closes https://github.com/ibis-project/ibis/issues/8567
> depr: deprecate and warn on `legacy` udf usage

- ibis/expr/types/arrays.py
- ibis/expr/types/maps.py
- ibis/expr/types/structs.py
The existing descriptions for these types at https://ibis-project.org/reference/expression-collections are pretty bad.
- Improve toplevel docstring for types so you can get a sense for what they type even is.
- ~~Add "corresponds to" list so people
can link this concept to concepts they are familiar to.~~
- fix explanations of how the datashape is determined in .map(), .array(), and .struct().
- some examples weren't really needed
- used "column" not "array" when describing datashape, since "array" has another meaning in ibis
> docs: improve nested type docstrings

- ibis/backends/oracle/__init__.py
- ibis/backends/tests/test_dot_sql.py
Fixes a bug discovered during polars dot sql implementation where we were mapping empty precision and scale decimal types, but the oracle docs say that empty precision and scale together are mapped to number(38, 0).
The discovery during polars dot sql implementation is incidental, due to the test I changed, which is included here.
> fix(oracle): map bare `NUMBER` to `int64` and consolidate data type mapping code for shared inference

- ibis/backends/bigquery/tests/conftest.py
- ibis/backends/bigquery/tests/system/conftest.py
- ibis/backends/bigquery/tests/system/udf/test_udf_execute.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/tests/test_client.py
Workaround for https://github.com/googleapis/python-bigquery/issues/1845.
> fix(bigquery): get literals working again

- docs/_quarto.yml
- ibis/expr/types/temporal.py
Fixes https://github.com/ibis-project/ibis/issues/8165
> docs: include return type in Interval component properties

- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/druid/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/trino/__init__.py
Remove the unnecessary `_metadata` method in favor of `_get_schema_using_query`
> refactor(backends): remove `_metadata` method in favor of `_get_schema_using_query`

- ibis/common/graph.py
- ibis/common/tests/test_graph_benchmarks.py
Mitigate the performance overhead of signature binding during node reconstruction. 
Benchmark showing ~20% improvement:
```
------------------------------------------------------------------------------ benchmark 'test_replace_mapping': 2 tests ------------------------------------------------------------------------------
Name (time in ms)                           Min                Max               Mean            StdDev             Median               IQR            Outliers      OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_replace_mapping (0412_b5f9bbe)     10.6952 (1.17)     31.7057 (1.04) …
```
> perf(common): improve the performance of replacing nodes using mappings

- ibis/tests/benchmarks/test_benchmarks.py
- **ci: ensure that benchmarks do not reference data that subject to disappear**
- **ci: actually fix benchmarking**
> ci: actually fix benchmarking

- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/datafusion/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/flink/compiler.py
- ibis/backends/mssql/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/sql/__init__.py
- ibis/backends/sql/compiler.py
- ibis/backends/trino/compiler.py
Still profiling and adding more `copy=False` options, apparently it greatly improves the performance.
According to profiling the recursive generation of sqlglot is still a bottleneck for big queries which cannot be fixed on the ibis side. There could be one option though to compile the fragments in a greedy fashion which are going to be cached by `Node.map()` and inject those as arbitrary strings to other sqlglot expressions.
The benchmark shows a pretty solid improvement:
```
------------------------------------------------------------------------------ benchmark 'test_compile[large-duckdb]': 2 tests -------------------------------------------------------------------------------
Name (time in ms)                                 Min                Max               Mean            StdDev …
```
> perf(sql): prevent sqlglot from extensive deepcopying every time we create a sqlglot object

- ibis/backends/tests/test_interactive.py
- ibis/config.py
- ibis/expr/format.py
- ibis/expr/tests/snapshots/test_format/test_format_show_variables/repr.txt
- ibis/expr/tests/test_format.py
- ibis/expr/types/core.py
For the following code:
```py
import ibis
alltypes = ibis.table(...)
filtered = alltypes[alltypes.f > 0]
ordered = filtered.order_by("f")
projected = ordered[["a", "b", "f"]]
expr = projected.a + projected.b
ibis.options.repr.show_variables = True
repr(expr)
```
instead of showing 
```
r0 := UnboundTable: alltypes
a int8
b int16
c int32
d int64
e float32
f float64
g string
h boolean
i timestamp
j date
k time
r1 := Filter[r0]
r0.f > 0
r2 := Sort[r1]
asc r1.f
r3 := Project[r2]
a: r2.a
b: r2.b
f: r2.f
Add(a, b): r3.a + r3.b
```
now we can render the expression representation as 
```
alltypes := UnboundTable: alltypes
a int8
b int16
c int32
d int64
e float32
f float64
g string
h boolean
i timestamp
j date
k time
filtered := Filter[alltypes]
alltypes.f > 0
ordered := Sort[filtered]
asc …
```
> feat(ir): support showing variable names used to create an expression in `repr()`

- ibis/backends/sql/rewrites.py
- ibis/backends/tests/sql/snapshots/test_select_sql/test_subquery_factor_correlated_subquery/out.sql
- ibis/backends/tests/tpch/snapshots/test_h02/test_tpc_h02/snowflake/h02.sql
- ibis/backends/tests/tpch/snapshots/test_h02/test_tpc_h02/trino/h02.sql
- ibis/backends/tests/tpch/snapshots/test_h11/test_tpc_h11/duckdb/h11.sql
- ibis/backends/tests/tpch/snapshots/test_h11/test_tpc_h11/snowflake/h11.sql
- ibis/backends/tests/tpch/snapshots/test_h11/test_tpc_h11/trino/h11.sql
- ibis/backends/tests/tpch/snapshots/test_h15/test_tpc_h15/duckdb/h15.sql
- ibis/backends/tests/tpch/snapshots/test_h15/test_tpc_h15/snowflake/h15.sql
- ibis/backends/tests/tpch/snapshots/test_h15/test_tpc_h15/trino/h15.sql
Common table expressions haven't been extracted for subqueries because we stopped traversing once reaching any value expression.
> fix(sql): look for CTEs under value expressions as well

- ci/schema/clickhouse.sql
- ci/schema/duckdb.sql
- ci/schema/exasol.sql
- ci/schema/mssql.sql
- ci/schema/mysql.sql
- ci/schema/oracle.sql
- ci/schema/postgres.sql
- ci/schema/risingwave.sql
- ci/schema/snowflake.sql
- ci/schema/sqlite.sql
- ci/schema/trino.sql
- ibis/backends/bigquery/tests/conftest.py
- ibis/backends/dask/tests/conftest.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/impala/tests/conftest.py
- ibis/backends/pandas/tests/conftest.py
- ibis/backends/polars/tests/conftest.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/tests/data.py
- ibis/backends/tests/sql/snapshots/test_select_sql/test_chain_limit_doesnt_collapse/result.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_topk_operation/e2.sql
- ibis/backends/tests/test_generic.py
- ibis/expr/types/generic.py
Default to count star instead of count(expr) in topk API. Closes #8518.
BREAKING CHANGE: `expr.topk(...)` now includes null counts. The row count of the `topk` call will not differ, but the number of nulls counted will no longer be zero. To drop the `null` row use the `dropna` method.
> feat(api): count nulls with topk

- ibis/backends/pandas/executor.py
- ibis/backends/polars/compiler.py
- ibis/backends/sql/rewrites.py
- ibis/backends/tests/sql/snapshots/test_sql/test_double_order_by/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_double_order_by_deferred/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_double_order_by_different_expression/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_double_order_by_not_fused/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_double_order_by_same_column/out.sql
- ibis/backends/tests/sql/test_sql.py
- ibis/backends/tests/test_generic.py
- ibis/expr/sql.py
Now we turn 
```
r0 := DatabaseTable: functional_alltypes
id              int64
bool_col        boolean
tinyint_col     int8
smallint_col    int16
int_col         int32
bigint_col      int64
float_col       float32
double_col      float64
date_string_col string
string_col      string
timestamp_col   timestamp(6)
year            int64
month           int64
r1 := Sort[r0]
asc r0.tinyint_col
asc r0.bool_col
Sort[r1]
asc r1.bool_col
desc r1.tinyint_col + 1
```
into 
```
r0 := DatabaseTable: functional_alltypes
id              int64
bool_col        boolean
tinyint_col     int8
smallint_col    int16
int_col         int32
bigint_col      int64
float_col       float32
double_col      float64
date_string_col string
string_col      string
timestamp_col   timestamp(6)
year            int64
month …
```
> fix(sql): outer order by should take precedence over inner order by

- ibis/backends/impala/tests/conftest.py
Ensure that the topk table gets created anew every time the test suite is run for Impala.
> test(impala): ensure that topk table does not already exist

- ci/schema/bigquery.sql
- ibis/backends/bigquery/tests/conftest.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/bigquery/tests/system/test_connect.py
- ibis/backends/tests/test_json.py
This PR moves bigquery test data loading to SQL DDL in an effort to reduce the complexity of the setup code and make it less stateful.
> test(bigquery): clean up test data loading

- ibis/formats/pandas.py
- ibis/formats/tests/test_pandas.py
Previously ibis's `date` type was mapped to `datetime64[D]`. This type isn't supported by pandas (the max is `datetime64[s]`), but the errors were hidden due to a `try/except` block causing things to fallback to `dtype('O')`. Pandas 2.2 changed the error raised here resulting in test failures.
> fix(pandas): map `date` type to `datetime64[s]`

- docs/_quarto.yml
- ibis/backends/druid/compiler.py
- ibis/backends/flink/compiler.py
- ibis/backends/oracle/compiler.py
- ibis/backends/pandas/kernels.py
- ibis/backends/polars/compiler.py
- ibis/backends/risingwave/compiler.py
- ibis/backends/sql/compiler.py
- ibis/backends/sql/dialects.py
- ibis/backends/tests/test_temporal.py
- ibis/expr/api.py
- ibis/expr/operations/generic.py
- ibis/tests/expr/test_temporal.py
Responding to this user request: https://github.com/ibis-project/ibis/discussions/8213#discussioncomment-8798497
Also adds support for `ibis.now()` for `oracle` and `druid`. I assume these were marked as unsupported due to prior upstream issues in sqlglot? The compilation seems to work fine now.
> feat(api): add `ibis.today()` for retrieving the current date

- ibis/backends/duckdb/__init__.py
In #6875 we switched to using `con.sql(sql)` instead of `con.execute(sql)` when retrieving an arrow table of results. The former is more efficient than the latter since the `.sql` api lets the query planner take advantage of the known output type, possibly resulting in a more efficient execution.
In the `the-epic-split` refactor this optimization was dropped (note - it seems less necessary since duckdb 0.9.0, although they say [a performance difference is still expected](https://github.com/duckdb/duckdb/discussions/8582#discussioncomment-8806576)). We add the optimization back here, and apply it to all locations where we return in-memory data.
We choose _not_ to use `duckdb_con.sql` instead of `duckdb_con.execute` in the public-facing `raw_sql` api, since:
- The returned object isn't …
> refactor(duckdb): use `.sql` instead of `.execute` in performance-senitive locations

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_temporal.py
Previously broadcasting a scalar as a column and then selecting only that column would result in only one row (rather than `len(t)` rows). This fixes that bug and adds a test.
Based on #8664, since this fixes a test in that PR too.
> fix(polars): ensure `t.select(col=scalar)` results in `len(t)` rows

- docs/backends/mssql.qmd
- ibis/backends/mssql/__init__.py
The method for enabling Integrated Authentication with ODBC is to not
provide a `user` or `password`, and to set `Trusted_Connection =
'true'`.
If `Trusted_Connection` is already set in `kwargs`, do nothing, because
either the user set it to 'true' and it will work untouched, or they're
specifying 'false' for a reason and we should leave it alone.- feat(mssql): use integrated auth when no user or password supplied
- docs(mssql): add odbc tabset and integrated authentication section
Resolves #8657
> feat(mssql): use integrated auth when no user or password supplied

- docs/_callouts/experimental_backend.qmd
- docs/backends/datafusion.qmd
- docs/backends/druid.qmd
- docs/backends/oracle.qmd
- docs/backends/polars.qmd
- docs/backends/trino.qmd
These backends have all been around for a while, no need to keep marking them as experimental.
> docs: remove experimental indicator from all backends

- ibis/expr/types/core.py
Previously this gave wrong advice to set the default backend.
Fixes #8677.
> fix: update error message when executing against unbound tables

- ibis/common/egraph.py
There was a duplicated frozen slotted implementation under `ibis.common.egraphs` which is now replaced by `ibis.common.bases.FrozenSlotted`.
> refactor(common): consolidate egraph implementation by using `FrozenSlotted`

- ibis/expr/operations/core.py
`op` as a method on another operation was deprecated in 4.0.
`output_dtype` and `output_shape` were deprecated in 7.0.
I think 2 major versions is a reasonable deprecation cycle.
BREAKING CHANGE: Deprecated methods and properties `op`, `output_dtype`, and `output_shape` are removed. `op` is no longer needed, and use `.dtype` and `.shape` respectively for the other two.
> refactor(cleanup): remove deprecated methods and properties

- ibis/backends/dask/tests/test_join.py
- ibis/backends/pandas/tests/test_join.py
- ibis/backends/tests/test_asof_join.py
- ibis/expr/types/joins.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Closes #7869.
BREAKING CHANGE: The `by` argument from `asof_join` is removed. Calls to `asof_join` that previously used `by` should pass those arguments to `predicates` instead.
> refactor(api): remove `by` of asof_join() in favor of `predicates`

- ci/schema/exasol.sql
- ibis/backends/polars/__init__.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/__init__.py
- ibis/backends/tests/test_dot_sql.py
- ibis/backends/tests/test_export.py
Adds limited support for `.sql` to the Polars backend. Closes #8525.
> feat(polars): add limited support for table dot sql

- docs/backends/exasol.qmd
Remove outdated or deprecated parameters from the Exasol backend example.
> docs(exasol): remove deprecated parameters from example

- ibis/common/bases.py
- ibis/common/caching.py
- ibis/common/grounds.py
- ibis/common/tests/test_bases.py
- ibis/common/tests/test_graph_benchmarks.py
- ibis/common/tests/test_grounds.py
- ibis/expr/datatypes/core.py
- ibis/expr/operations/core.py
- ibis/expr/schema.py
Previously we used a rather complicated mechanism to implement global equality cache for operation nodes involving tricky weak reference tracking registering callbacks to invalidate cache entries. 
While this has greatly improved the overall performance of ibis internals we can have a simpler and more lightweight implementation by storing the equality comparison results in a `dict[dict[object_id, bool]]` data structure which allows us quick lookups and quick deletions. The caching is also specialized to a pair of objects in contrary to the previous `WeakCache` implementation which supported arbitrary number of key elements requiring multiple iterations over the key tuple.
```
---------------------------------------------------------------------------- benchmark 'test_bfs': 2 tests …
```
> perf(common): improve equality caching by explicitly invalidating the entry on `__del__`

- ibis/backends/flink/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_map.py
- ibis/expr/operations/maps.py
Fixes https://github.com/ibis-project/ibis/issues/8605
I bet a lot of these tests will fail in CI. IDK, a lot of these tests feel like overkill. Could just ensure that the Expr can get created, but skip actually executing them on the backend. That requires a lot more boilerplate. But, it is sort of nice to actually have an up-to-date status on what types each backend supports in maps.
> feat(api): support all dtypes in MapGet and MapContains

- ibis/backends/flink/compiler.py
Fixes failing upstream flink tests due to flink's need for exact type matching on map lookups.
> fix(flink): cast map key lookups because flink requires exact type matches

- ibis/backends/pandas/tests/test_structs.py
- ibis/backends/tests/test_param.py
- ibis/common/collections.py
- ibis/common/tests/test_collections.py
This was motivated to work around pandas not repr'ing `frozendict` elements properly (seen in #8687), but while poking at that I found:
- The existing code was unnecessarily nested (the actual dict was boxed in a `MappingProxyType` which was boxed in a `FrozenDict` - we can do better by just using storing the data in the `FrozenDict` itself).
- There was a bug in the hash implementation where the order mattered, meaning that `hash(frozendict(a=1, b=2)) != hash(frozendict(b=2, a=1))`. This has since been fixed.
Fixes #8687.
> refactor(common): make `FrozenDict` a subclass of `dict`

- ibis/backends/sql/__init__.py
- ibis/backends/sql/compiler.py
- ibis/backends/sqlite/tests/test_client.py
Previously `has_operation` for the SQL backends was ignoring operations supported through rewrite rules, leading to some gaps in the support matrix. Related to question in #8715. The pandas/dask backends still aren't correct - I started down fixing these up, but got bogged down in the magic of the `Dispatched` class and decided to punt for now.
Also deletes some dead code in the base sql backend.
> fix: fix some missing operations in the support matrix

- docs/how-to/visualization/graphs.qmd
- ibis/expr/tests/test_visualize.py
- ibis/expr/visualize.py
This PR properly displays relation field names when accessed and avoids displaying references as `.None` when coming from a JoinLink object.
> fix(graphviz): show proper field attributes of accessed relations and do not display join link property accesses

- .gitignore
- ibis/examples/README.md
- ibis/examples/gen_registry.py
- ibis/examples/metadata.json
- ibis/examples/pixi.lock
- ibis/examples/pixi.toml
Resolves #8718
As an example:
``` python
[ins] In [1]: from ibis.interactive import *
[ins] In [2]: ibis.examples.nycflights13_airports.fetch()
Out[2]: 
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━┓
┃ faa    ┃ name                       ┃ lat       ┃ lon         ┃ alt   ┃ tz    ┃ … ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━┩
│ string │ string                     │ float64   │ float64     │ int64 │ int64 │ … │
├────────┼────────────────────────────┼───────────┼─────────────┼───────┼───────┼───┤
│ 04G    │ Lansdowne Airport          │ 41.130472 │  -80.619583 │  1044 │    -5 │ … │
│ 06A    │ Moton Field Municipal Air… │ 32.460572 │  -85.680028 │   264 │    -6 │ … │
│ 06C    │ Schaumburg Regional        │ …
```
> chore(examples): add nycflights13 dataset to examples

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
Bigquery, unlike other bcakends, had existing support for specifying table
hierarchy in the table name, e.g. con.table("dataset.table_name") so we
have an extra layer of disambiguation to handle.
> fix(bigquery): restore option to specify table path in table name

- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/tests/benchmarks/test_benchmarks.py
Quick followup to #8655
I'm sure this won't be the last of these, but hopefully it's _close_ to the last.
> chore(descheming): remove remaining internal usage of deprecated schema

- ibis/backends/dask/executor.py
Aims to close https://github.com/ibis-project/ibis/issues/8186.
> perf(dask): avoid triggering compute for dynamic limit/offset

- ibis/backends/druid/__init__.py
I tried connecting to the druid container and got an
`AttributeError: module 'pydruid' has no attribute 'db'`
> fix(druid): import pydruid.db module explicitly

- ibis/expr/schema.py
- ibis/expr/tests/test_schema.py
This logic has been moved to the `ibis.formats.pandas` module.
BREAKING CHANGE: `Schema.apply_to()` is removed, use `ibis.formats.pandas.PandasConverter.convert_frame()` instead
> refactor(ir): remove deprecated `Schema.apply_to()` method

- ibis/expr/api.py
- ibis/expr/format.py
- ibis/expr/operations/relations.py
- ibis/expr/tests/snapshots/test_format/test_format_unbound_table_namespace/repr.txt
- ibis/expr/tests/snapshots/test_format/test_format_unbound_table_namespace/reprcatdb.txt
- ibis/expr/tests/snapshots/test_format/test_format_unbound_table_namespace/reprdb.txt
- ibis/expr/tests/test_api.py
- ibis/expr/tests/test_format.py
This allows specifying 1 or 2 levels of table positional hierarchy in a
call to `ibis.table`. I've updated the reprs for `UnboundTable` and
`DatabaseTable` to show that hierarchy when it is specified.
I've also swapped the attribute order for `ops.Namespace` as a
convenience to allow unpacking the argnames in the correct hierarchical
order.
Resolves #8253
> feat(api): add `catalog` and `database` kwargs to `ibis.table`

- ibis/backends/dask/__init__.py
- ibis/backends/pandas/__init__.py
- ibis/expr/datatypes/core.py
- ibis/expr/schema.py
- ibis/expr/tests/test_schema.py
- ibis/formats/__init__.py
- ibis/formats/pandas.py
`sch.infer()` and `DataMapper.infer_table()` implementations had an unnecessary schema argument which wan't actually used.
> refactor(formats): remove unnecessary schema argument from schema inference

- ibis/expr/datatypes/core.py
- ibis/expr/schema.py
- ibis/expr/tests/test_schema.py
Dask is not an explicitly supported format and these methods were just aliases for `.to_pandas()` and `.from_pandas()`.
BREAKING CHANGE: Schema.to_dask(), Schema.from_dask(), DataType.from_dask(), DataType.to_dask() methods are removed, use `.to_pandas()` and `.from_pandas()` methods instead
> refactor(api): remove `Schema.from/to_dask()` and `DataType.from/to_dask()`

- ibis/formats/__init__.py
This argument is used by several formatting classes and the function has
limited meaning without it.
xref #8814
> chore(formats): restore schema arg to convert_table

- ibis/backends/clickhouse/compiler.py
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_string_column_find/out1.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_string_column_find/out2.sql
Makes our implementation of string find and substring operations backwards compatible with clickhouse 23.
> fix(clickhouse): use backwards compatible string search function

- ibis/backends/bigquery/tests/unit/test_datatypes.py
Fixes the two failing tests due to now quoting all struct field names.
> test(bigquery): fix struct field quoting in type translation tests

- .github/workflows/nix-skip-helper.yml
- .github/workflows/nix.yml
- flake.lock
- flake.nix
- nix/overlay.nix
Downgrade nixpkgs to avoid picking up newer versions of xz. This is a developer-tools-only issue. We can revisit the 312 support in the nix job once nixos-unstable-small finishes building (it has the xz revert patch applied).
> chore(deps): downgrade nixpkgs

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
In https://github.com/ibis-project/ibis/pull/8656 we made the args for `read_mysql`  required-keyword. 
This PR, makes the args for `read_postgres` and `read_sqlite` to be  required-keyword to be consistent. 
It also fixes a broken test that runs only locally, `test_read_postgres` (thanks @gforsyth for the patch suggestion). 
- Closes https://github.com/ibis-project/ibis/issues/8712
> chore: make arguments required-keyword for read_postgres and read_sqlite

- ibis/common/graph.py
- ibis/common/tests/test_graph.py
Currently we are unable to locate certain values under a relation while applying a value filter because the root node gets filtered out, like:
```py
relation.find(pattern, filter=ops.Value)
```
Used in practice at https://github.com/ibis-project/ibis/pull/8825
```py
for child in _.__children__ + _.parent.__children__:
if child.find((Window, ops.ExistsSubquery, ops.InSubquery, ops.Unnest), filter=ops.Value):
...
```
Which can be simplified to `_.find_below() or _.parent.find_below()` after this feature.
I am not that satisfied with the name, but marked as experimental so we can change it anytime. 
This feature will also help with pretty printing the dereference mapping without traversing the dictionary keys in `_flatten_collections()`.
> feat(common): add `Node.find_below()` methods to exclude the root node from filtering

- ibis/expr/tests/test_newrels.py
- ibis/expr/types/relations.py
Slightly smarter dereferencing to also dereference literal expressions without any relations attached. 
The following expression 
```py
one = ibis.literal(1)
two = ibis.literal(2)
four = (one + one) * two
t1 = t.mutate(four=four)
t2 = t1.select(four)
```
Before
```
r0 := UnboundTable: t
bool_col   boolean
int_col    int64
float_col  float64
string_col string
r1 := Project[r0]
bool_col:   r0.bool_col
int_col:    r0.int_col
float_col:  r0.float_col
string_col: r0.string_col
four:       1 + 1 * 2
Project[r1]
Multiply(Add(1, 1), 2): 1 + 1 * 2
```
After
```
r0 := UnboundTable: t
bool_col   boolean
int_col    int64
float_col  float64
string_col string
r1 := Project[r0]
bool_col:   r0.bool_col
int_col:    r0.int_col
float_col:  r0.float_col
string_col: r0.string_col
four:       1 + 1 * 2 …
```
> refactor(ir): dereference literal expressions

- ibis/expr/operations/relations.py
- ibis/expr/tests/test_newrels.py
Enables us easier join chain rewrites since we don't need to maintain a monotonically increasing index for the join tables.
Resolves https://github.com/ibis-project/ibis/issues/8773
> refactor(ir): loosen the join integrity checks

- ibis/expr/format.py
- ibis/expr/tests/snapshots/test_format/test_default_format_implementation/repr.txt
- ibis/expr/tests/test_format.py
We have custom nodes for example to lower expressions to certain backends. Pretty printing these are especially useful but currently we raise for unknown node types.
> feat(ir): add default implementation of pretty formatting nodes

- ibis/tests/benchmarks/test_benchmarks.py
Fixing build error: https://github.com/ibis-project/ibis/actions/runs/8541350879/job/23400454706
> test(benchmarks): fix constructing large benchmark expression

- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
Before this was just ignored, so if you tryied to connect to
anything besides port 5432, it would
just use the default of 5432
> feat(postgres): use port in connection string

- ibis/backends/sql/rewrites.py
- ibis/backends/tests/snapshots/test_sql/test_isin_bug/mssql/out.sql
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/tpch/snapshots/test_h20/test_tpc_h20/duckdb/h20.sql
- ibis/backends/tests/tpch/snapshots/test_h20/test_tpc_h20/trino/h20.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/duckdb/h22.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/trino/h22.sql
- ibis/common/graph.py
Another take on https://github.com/ibis-project/ibis/pull/8820 by introducing a complexity metric and only merge `Select` nodes if the outcome is less complex.
> fix(sql): avoid excessive inlining during `Select` merge

- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-main.yml
- ibis/backends/tests/tpch/snapshots/test_h20/test_tpc_h20/snowflake/h20.sql
- ibis/backends/tests/tpch/snapshots/test_h22/test_tpc_h22/snowflake/h22.sql
Fixes snapshots.
I also disabled dependency caching except in cases where we're installing all extras: benchmarking and doctests. It doesn't seem like we're getting much from it in other cases except [bizarre failures](https://github.com/ibis-project/ibis/actions/runs/8632266124/job/23662562629?pr=8758).
> test(snowflake): fix snapshots

- docs/contribute/05_reference.qmd
- ibis/backends/bigquery/tests/conftest.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/exasol/tests/conftest.py
- ibis/backends/impala/tests/conftest.py
- ibis/backends/pandas/tests/conftest.py
- ibis/backends/tests/base.py
Test case configuration now happens through pytest markers.
depends on #8935
> test(backends): remove now unused `supports_divide_by_zero` backend flag

- ibis/expr/types/groupby.py
this brings it in line with the normal Table methods
> feat(api): allow *arg syntax with GroupedTable methods

- ibis/expr/format.py
- ibis/expr/types/core.py
- ibis/expr/types/generic.py
- ibis/expr/types/pretty.py
- ibis/expr/types/relations.py
redo of #7408 targeting main instead of master
fixes #7172 
I wasn't sure how testing this should work so I didn't add any tests. I would really appreciate it if someone more familiar could pick this up and finish it off, I think I've gotten a lot of it out of the way.
Hopefully I've implemented this is such a way that it is testable.
Things I'm not sure about:
1. EDIT: I think this is fine to just keep them opaque as fmt_kwargs. adding **fmt_kwargs all over pretty.py. I didn't really want all the boilerplate that would be required if I was explicit with each kwarg. Possibly could pass around a container object such as options.Repr instead.
2. I encapsulated some logic into pretty.pretty_repr() because I thought that was going to be necessary for the functional change. It ended up not …
> feat(ux): add Table and Column.preview()

- ibis/backends/risingwave/__init__.py
Resolves #8780
If we set this option then the table expression doesn't render until the transaction is complete.
I _think_ this is a reasonable thing to do by default, but there may be
streaming-related side-effects that I'm not considering.  
@KeXiangWang -- does this seem ok to you?
> fix(risingwave): set implicit flush to true

- ibis/backends/tests/test_generic.py
- ibis/expr/types/generic.py
> test(api): verify that null isin behavior is consistent across backends

- docs/how-to/visualization/altair.qmd
Noticed in @koaning's livestream that we never updated the Altair example to remove the call to `to_pandas`
Here's the local render:
> docs(altair): remove to_pandas from altair example

- ibis/backends/tests/test_array.py
Quick fix for an XPASS-ing clickhouse test.
> test(clickhouse): bring back xpassing array unnest of structs test

- .github/workflows/check-generated-files.yml
- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-benchmarks.yml
- .github/workflows/ibis-main.yml
Remove dependency caching and pipx usage to avoid CI hiccups from mismatching pipx python versions and target test python versions.
> ci(deps): remove dep caching and pipx usage in favor of plain pip

- ibis/expr/types/relations.py
- ibis/tests/expr/test_selectors.py
- ibis/tests/expr/test_table.py
- ibis/tests/expr/test_value_exprs.py
Removing the int-as-column references in mutate and select. Further discussed in #8878.
BREAKING CHANGE: Integer inputs to `select` and `mutate` are now always interpreted as literals. Columns can still be accessed by their integer index using square-bracket syntax.
> refactor(api): treat integer inputs as literals instead of column references

- .github/workflows/ibis-backends-cloud.yml
Fixes the snowpark install in CI (again). The issue is that passing the optional flag causes the library to not be installed.
> ci(snowflake-snowpark): make install required

- .github/workflows/ibis-backends-cloud.yml
Sets the python version of the snowpark test job to be 3.10 to avoid clobbering the data in the 3.9 and 3.11 jobs.
> ci(snowflake-snowpark): test against python 3.10 to avoid clobbering other runs test data

- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_client.py
It's not yet feasible to call `reconnect` with an Ibis Snowflake backend initialized from a Snowpark connection, so this PR disables that code path.
> fix(snowflake-snowpark): disable the `reconnect` method

- ci/schema/bigquery.sql
- ci/schema/duckdb.sql
- ci/schema/mysql.sql
- ci/schema/postgres.sql
- ci/schema/risingwave.sql
- ci/schema/snowflake.sql
- ci/schema/sqlite.sql
- ci/schema/trino.sql
- ibis/backends/bigquery/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/mysql/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/sqlite/compiler.py
- ibis/backends/tests/data.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_json.py
- ibis/backends/trino/compiler.py
- ibis/expr/operations/json.py
- ibis/expr/types/json.py
Adds `str`, `int`, `float`, and `bool` properties to `JSONValue` as well as an `unwrap_as` method for easier programmatic usage and more fine-grained casting.
Unless someone really hates the static property names, I'd prefer to keep them as they are. Open to alternative names for `unwrap_as` though.
In theory this can all be done with casting, but if you look at what's being done in the various backends it's typically a lot more involved than that. Trino in particular requires queries over JSON to be `VARCHAR` inputs, when then have to be cast **back** to its `JSON` type to be able to cast _that_ to the desired output type.
Complicating the cast branching _just_ for the `JSON -> not JSON` case seemed like the wrong tradeoff.
I went with these names to match the `map` and `array` APIs, and …
> feat(api): add API for unwrapping JSON values into backend-native values

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_udf.py
Add a test demonstrating running Ibis inside of a Snowpark stored procedure.
Closes #5877.
> test(snowflake-snowpark): testing running ibis code in a snowpark stored procedure

- ibis/backends/duckdb/compiler.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/postgres/compiler.py
- ibis/backends/tests/test_map.py
partially addresses https://github.com/ibis-project/ibis/issues/8632
> fix(duckdb): workaround for duckdb Map NULL bugs

- ibis/backends/duckdb/compiler.py
- ibis/backends/tests/test_map.py
- ibis/expr/types/maps.py
Closes #8632.
Note that of the backends that support nullable maps, DuckDB is the only one whose `NULL` handling semantics differ.
Other backends that support nullable maps and are implemented in Ibis and tested in CI:
- Postgres (only maps of string -> string via the postgres `hstore` extension)
- PySpark
- Snowflake
- Trino
BREAKING CHANGE: Calling the `get` or `contains` method on `NULL` map values now returns `NULL`. Use `coalesce(map.get(...), default)` or `coalesce(map.contains(), False)` to get the previous behavior.
> fix(duckdb): workaround remaining null map issues

- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Accidentally introduced in #8884
> fix(ir): accidentally remapping fields during bind()

- ibis/expr/types/strings.py
- ibis/tests/expr/test_value_exprs.py
Before, ibis.literal(1) or any ibis expression was a valid step in slices, but it shouldn't have been, since this argument
is ignored.
> test: add test for non-1 step in String slicing

- ibis/backends/tests/test_struct.py
Follow-up to xfail the flink test for `IN STRUCT` queries
> test(flink): xfail in-struct test

- ibis/backends/duckdb/tests/test_client.py
The test removed here is [flaky](https://github.com/ibis-project/ibis/actions/runs/8737544784/job/23974768058) and does not really add much value.
> test(duckdb): remove flaky test

- ibis/backends/dask/executor.py
- ibis/backends/tests/test_aggregation.py
Avoids calling `compute` when executing `cov`/`corr`/`argmin`/`argmax`.
This necessarily drops support for `cov`/`corr` with `how="pop"`, since dask doesn't include native support (yet).
Fixes #8187.
> perf(dask): avoid unnecessary calls to `compute` for `cov`/`corr`/`argmin`/`argmax`

- conda/environment-arm64-flink.yml
- conda/environment-arm64.yml
- conda/environment.yml
- docs/contribute/01_environment.qmd
We removed the `all` extra in a previous PR and it is no longer necessary.
Fixes #9002
> docs: remove `all` extra installation from contributing docs

- ibis/backends/dask/executor.py
Fixes a bug introduced in #9015 that was masked by pandas magically doing the right thing in newer pandas versions.
> fix(dask): fix argmin/argmax implementation for dask

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/postCreate.sh
These change are what was required for me to get the devcontainer to run on my machine. Before these changes, the devcontainer image wasn't building correctly because it was missing gdal. The root cause of that was that the devcontainer.json wasn't using the Dockerfile.
- The previous devcontainer.json wasn't actually using the Dockerfile, now it does
- In devcontainer.json, I switched updateContent command for postCreateCommand as that looks more appropriate based on the docs
- A couple of minor tidying changes
Resolves #9011
> fix: make devcontainer work correctly

- .github/workflows/ibis-backends-skip-helper.yml
I _think_ this should prevent weird merge-even-though-the-things-failed problems observed in https://github.com/ibis-project/ibis/pull/9015.
> ci: make skip helper jobs match non-skip-helper workflows

- ibis/backends/pandas/executor.py
- ibis/expr/operations/generic.py
- ibis/expr/operations/tests/test_generic.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/relations.py
All impure values passed to the API methods are treated as separate impure invocations:
```py
impure = ibis.random()
t1 = t.mutate(y=impure)
t2 = t1.mutate(z=impure.cast("string"))
```
now produce
```
r0 := UnboundTable: unbound_table_0
a int64
b string
r1 := Project[r0]
a: r0.a
b: r0.b
y: RandomScalar()
Project[r1]
a: r1.a
b: r1.b
y: r1.y
z: Cast(RandomScalar(), to=string)
```
> refactor(ir): impure values are never dereferencible

- ibis/backends/snowflake/tests/test_udf.py
This showed up in #9030 and I wasn't sure if it was flaky, but it looks like Snowpark can now run Ibis as `caller`, too!
> chore(snowflake): remove XPASSing xfail on udf test

- ibis/common/typing.py
- ibis/expr/format.py
- ibis/expr/tests/snapshots/test_format/test_arbitrary_traversables_are_supported/repr.txt
- ibis/expr/tests/test_format.py
- ibis/expr/types/core.py
This enables pretty formatting the dereference mappings and also the replacements mappings we use in rewrites for better inspection. Also moved the irrelevant logic out from `format.py`.
> feat(ir): support pretty printing arbitrary traversable objects

- ibis/common/graph.py
- ibis/common/tests/test_graph.py
This change allows repr-ing node mappings, like the dereference mappings for easier inspection.
Inevitably this is slowing down the traversals, but changing the instance checks to use a plain dict instead of `(dict, frozendict)` maintains the previous traversal speed:
```
---------------------------------------------------------------------------- benchmark 'test_bfs': 2 tests -----------------------------------------------------------------------------
Name (time in ms)              Min               Max              Mean            StdDev            Median               IQR            Outliers       OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> feat(common): also traverse nodes used as dictionary keys

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_client.py
- ibis/backends/tests/test_api.py
- ibis/backends/tests/test_client.py
Resolves #9038 
Adds support for specifying the `catalog` in various `pyspark` calls.  
BREAKING CHANGE: Arguments to `create_database`, `drop_database`, and
`get_schema` are now keyword-only except for the `name` args.  Calls to
these functions that have relied on positional argument ordering need to
be updated.
> feat(pyspark): add catalog support to pyspark

- ci/schema/postgres.sql
- docker/postgres/Dockerfile
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/sql/datatypes.py
Resolves #9025
We have had support for a bare `vector` type for a while, but `pgvector` defines
their vector type with precision, like `vector(3)` which was breaking our dtype
parsing.
I've opted to check here if the type starts with `vector` and treat all of those as `dt.unknown`.
For testing this, I've added `pgvector` to the postgres dockerfile -- if that's
too heavy, we can maybe mock up something in the `postgres.sql` file?  But it
does compile reasonably quickly on my machine (~4 seconds).
> feat(postgres): support loading tables with `pgvector` column types

- docs/presentations/linkedin-meetup-2024-04-24.qmd
Fixes incorrect markup in a slide from the talk last night.
> docs(presentations): fix quarto markup for Ibis origins slide in linkedin-meetup presentation

- ibis/backends/pyspark/compiler.py
- ibis/backends/tests/test_array.py
Fix PySpark zip implementation to ensure that its output matches the schema expected by Ibis. Fixes #9049.
> fix(pyspark): ensure that the output of zip matches the expected ibis schema

- ibis/backends/postgres/tests/test_client.py
- ibis/backends/sql/datatypes.py
Resolves #8845
Postgres' `information_schema` has a few custom dtypes that are only used there. Most of them just map to stringlike things, but users should be able to load these tables without issue.
I also added a mapping for the `name` type, which shows up in some of the default tables in `postgis`.
> feat(postgres): add mappings for more esoteric dtypes

- ibis/backends/flink/tests/test_memtable.py
Fix flaky flink test output order.
> test(flink): fix flakiness in test results output order

- ibis/backends/pyspark/__init__.py
Remove unused of `sparkContext` attribute, use of which prevents using spark connect.
Closes #9060.
> fix(pyspark): remove use of attribute that prevents using spark connect

- docs/backends/datafusion.qmd
With DataFusion [now being a top-level project](https://github.com/apache/datafusion/issues/9691#issuecomment-2063690461), this URL now redirects, and I have updated it to point to the new site.
https://arrow.apache.org/datafusion
https://datafusion.apache.org/
> docs(datafusion): update website link

- ibis/backends/duckdb/compiler.py
- ibis/backends/duckdb/tests/conftest.py
- ibis/backends/duckdb/tests/test_geospatial.py
- ibis/expr/types/generic.py
Add support to cast wkb to geometry type in duckdb backend
Closes https://github.com/ibis-project/ibis/issues/8805
This PR: needs a data file, CI will fail until https://github.com/ibis-project/testing-data/pull/8 gets merged
> feat(geo-duckdb): support casting binary to geometry

- nix/overlay.nix
Update nix hash to pick up new geo parquet dataset.
> chore(testing-data): update nix hash and rev

- ibis/backends/bigquery/tests/unit/udf/test_builtin.py
- ibis/backends/impala/udf.py
- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_udf.py
- ibis/backends/sql/__init__.py
- ibis/expr/operations/udf.py
I did not deprecate `schema` as we have elsewhere, because I don't think we can
determine the quoting behavior of the backend at UDF definition time, which
makes accepting dotted string paths harder. 
BREAKING CHANGE: The `schema` parameter for UDF definition has been removed. A new `catalog` parameter has been added. Ibis uses the word database to refer to a collection of tables, and the word catalog to refer to a collection of databases. You can use a combination of `catalog` and `database` to specify a hierarchical location for the UDF.
> refactor(udf): remove hierarchical usage of schema

- ibis/backends/tests/test_client.py
- ibis/common/collections.py
- ibis/common/tests/test_collections.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_core.py
- ibis/expr/operations/relations.py
- ibis/expr/schema.py
- ibis/expr/tests/test_dereference.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/tests/test_schema.py
- nix/overlay.nix
Continuation of https://github.com/ibis-project/ibis/pull/9068 by adding `FrozenOrderedDict` which calculates its hash from `tuple(self.items()` rather than `frozenset(self.items())` and also checks for item order during equality checks. 
Closes #9063.
> feat(common): introduce `FrozenOrderedDict`

- ibis/backends/pandas/executor.py
- ibis/backends/pandas/tests/test_operations.py
This PR makes `PandasExecutor` create the `Series` with an index that matches the incoming data. Currently, when the incoming data does not use a `RangeIndex`, the output index is a union of a `RangeIndex` and the incoming data index.
> fix(pandas): make case work for non-RangeIndex dataframes

- ibis/backends/tests/test_vectorized_udf.py
- ibis/expr/builders.py
- ibis/expr/rewrites.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/types/groupby.py
- ibis/expr/types/joins.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Previously we allowed arbitrary nesting of input expressions for various
API methods like `table.join`, `table.group_by`, etc. While this was
backward compatible with `8.0.0` it also exposes additional ambiguity
which can be confusing for users and difficult to reason about.
This change restricts the nesting of input expressions to a
"single level" of nesting with the exception of the first positional
argument which can be a list of expressions, but only if there are no
more positional arguments. Examples:
```python
t.select([t.foo, t.bar])  # OK
t.select(t.foo, t.bar)    # OK
t.select([t.foo], t.bar)  # Error
t.select(t.foo, name=t.bar)  # OK
t.select([t.foo], name=t.bar)  # OK
```
Aims to resolve https://github.com/ibis-project/ibis/issues/7819 and …
> refactor(api): restrict arbitrary input nesting

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_client.py
We set the catalog using a context manager, and we set the database also
using a context manager. There is a weird edge case:
set catalog to comms_media_dev (succeeds)
set database to dart_extensions within comms_media_dev (succeeds)
then we write the table, great! Now we try to change catalog and database back in reverse order and...
set database to default (the previous value that we saved) within comms_media_dev (fails, you do not have permission to access that)
set catalog back to spark_catalog (or previous value, but we never get here because of the previous error.
So what we need to do is instead:
set catalog
set database
write table
set catalog back
set database back
It would be really great if spark would allow for setting both of these values at the same time, but that is …
> fix(pyspark): unwind catalog/database settings in same order they were set

- .gitignore
- docs/jupyter_lite_config.json
- justfile
Fix the docs build that is failing due to a hardcoded wheel name
> docs: fix jupyterlite build

- docs/styles.css
> docs(website): make icon grayscale for consistency

- pyproject.toml
* We don't support Python 3.8 anymore
* We don't use pydantic, FastAPI, etc.
* All of the changes this would have guarded against were made in 25946f9865 anyway
> build(ruff): don't use keep-runtime-typing anymore
