ibis-project/ibis

- ibis/expr/types/core.py
- ibis/expr/types/generic.py
- ibis/tests/expr/test_value_exprs.py
Previously we coerced `co == None` to `IdenticalTo(col, None)`, but wouldn't do so for `ibis.NA` (resulting in that compiling as `Equals(col, None)` (which would result in incorrect SQL). This PR fixes this eager branch to handle any null literal, and compiles it the same as `isnull`/`notnull` (usually `col IS NULL`) rather than the more verbose `col IS NOT DISTINCT FROM NULL` that using `IdenticalTo` would result in.
Other options for this fix would be to:
- Always return `Equals` and use a rewrite rule to rewrite these cases. I opted against this since we'd have to have the same detection logic later, and this rewrite rule would be applied for every backend. Honestly having `Equals.__new__`/`NotEquals.__new__` optionally return `IsNull`/`NotNull` would be cleaner IMO, but that's harder …
> fix(api): treat `col == None` or `col == ibis.NA` as `col.isnull()`

- ibis/backends/pandas/kernels.py
- ibis/backends/tests/test_generic.py
- ibis/expr/api.py
- ibis/expr/types/generic.py
This is mostly a UX nicety. Instead of needing to do `ibis.null().cast(int)`, you can do it as `ibis.null(int)`.
pandas tests were breaking due to not being resilient to None scalars. So I fixed a bunch of affected Ops, not just the ones that I needed to change.
> feat(api): support `type` arg to ibis.null()

- ibis/backends/mysql/__init__.py
- ibis/backends/postgres/__init__.py
Examples were broken on MySQL backend and PySpark backend when there are null values in a numeric column. 
Druid, PySpark, RW don't support examples.
- Exasol - did not test
- Flink - broken
- Impala - did not test
- MSSQL - broken #9095 
- MySQL - fixed
- Oracle - did not test
- PostgreSQL - fixed
- Snowflake - did not test
#8792
> fix: replace NaNs with None in some backends when loading from pandas dataframe

- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_generic.py
This PR aims to add support for SAMPLE/TABLESAMPLE for Snowflake to build on the work done in #7377. 
As the SAMPLE/TABLESAMPLE clause seems to be written the same way between Snowflake and DuckDB in SQL, I was able reuse code from: https://github.com/ibis-project/ibis/blob/b48f451de77bd9af832cea10d7ddf8c44097c45a/ibis/backends/duckdb/compiler.py#L118-L128
Snowflake Docs: [SAMPLE/TABLESAMPLE](https://docs.snowflake.com/en/sql-reference/constructs/sample)
Code Snippet I used to validate it was working:
```
import ibis
con = ibis.snowflake.connect(create_object_udfs=False)
t = con.table("WOWAH_DATA_RAW", database=("WOWAH", "PUBLIC"))
print(t.count().execute())
for expression in (
t.sample(fraction=0.01),
t.sample(fraction=0.01, seed=42),
t.sample(fraction=0.01, method="block", seed=42),
): …
```
> feat(snowflake): implement Table.sample

- ibis/expr/api.py
- ibis/expr/types/generic.py
Use `ibis.options.interactive = True` in typed-null docstrings instead of calling `.execute()`.
> docs: use interactive mode instead of execute for typed null docstrings

- ibis/backends/tests/test_examples.py
The palmer penguins data has null valued integers, which when used to
create a `memtable`, leads to pandas casting a column to `float` because
it reads in the nulls as NaN.
We added a fix for this for some backends in #9094.
> test(examples): add penguins example test

- docs/how-to/extending/builtin.qmd
I updated the path of these in our google cloud bucket to reflect the
date of the pypi-data release (for tutorial purposes).  Inadvertantly
broke this usage here.
> docs(builtin): update url for packages.parquet file

- ibis/backends/snowflake/tests/conftest.py
Add a statement in the Snowflake test configuration to create the **ibis_testing** stage if it does not already exist. This is used in the `copy_into` function. 
https://github.com/ibis-project/ibis/blob/4f93a917a00173c03968b79e1210ab53de8d85ce/ibis/backends/snowflake/tests/conftest.py#L71-L72
When configuring these tests to run locally, I noticed yesterday that the models stage was being created automatically for the joblib file, but not this one. When the `PUT ibis/ci/ibis-testing-data/parquet/*.parquet` queries run, this results in query failures.
I hope this will help ease the onboarding for anyone wanting to test the Snowflake backend.
> test(snowflake): create stage for copy into

- ibis/backends/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sql/__init__.py
Callouts inside of a parameter description aren't being rendered in the
docs, so I've moved this callout into the main body of the docstring so
it renders correctly.
I've also added the same callout to the `read_postgres` method on the
DuckDB backend, as postgres users may try to use `schema` in the
hierarchical sense.
xref #8712
> docs(descheming): move callout note outside of parameter description

- ibis/backends/tests/test_generic.py
Follow-up to #9134. In https://github.com/ibis-project/ibis/pull/9134#discussion_r1592696374 I said we might want to move these to be handled within the expr methods to return as a no-op, but in practice I think handling as part of the rewrite rule is cleaner. Here we just add a few test cases to improve coverage.
> test: add test cases for no-op fillna expressions

- ibis/backends/tests/test_export.py
- ibis/expr/types/relations.py
> feat(pyarrow): support Arrow PyCapsule interface on `ibis.Table` objects

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_connect.py
- ibis/backends/bigquery/tests/unit/test_client.py
The BigQuery identifier quoting semantics are bonkers
https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#identifiers
my-table is OK, but not mydataset.my-table
mytable-287 is OK, but not mytable-287a
Just quote everything.
xref #8679
> fix(bigquery): quote all parts of table names

- ibis/backends/tests/test_export.py
> test: fixup arrow c stream test to be robust to nondeterministic execution

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
xref #8679
This should hopefully fix the last failure mode noted by @kajen3 -- we weren't quoting the fully qualified path to memtables when we create them.
> fix(bigquery): quote qualified memtable names

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_catalog.py
feat(duckdb): add catalog support to DuckDB create_table
This adds support for creating tables in external catalogs using DuckDB.
External catalogs cover attached SQLite, Postgres, and MySQL databases,
as well as attached DuckDB files.
Resolves #9146
> feat(duckdb): add catalog support to create_table

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
Fixes the repr of the duckdb backend settings property to be the table containing all settings
> fix(duckdb): use existing table repr for settings view

- ibis/expr/types/relations.py
- ibis/tests/benchmarks/test_benchmarks.py
Avoid the full dereference computation in the simple field access case, e.g., `t["a"]` or `t[0]`.
> perf(api): speed up simple column accesses by avoiding dereferencing

- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/exasol/compiler.py
- ibis/backends/oracle/compiler.py
- ibis/backends/pandas/kernels.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_temporal.py
- ibis/backends/trino/compiler.py
- ibis/expr/operations/temporal.py
- ibis/expr/types/temporal.py
- **first steps for implementing iso_year method**
- **added isoyear method for duckdb**
Added a new isoyear method for timestamps.
Resolved #8989
> feat(api): isoyear method

- ibis/common/collections.py
- ibis/common/exceptions.py
- ibis/expr/operations/relations.py
- ibis/expr/schema.py
- ibis/tests/expr/test_set_operations.py
I got tired of `ibis.union()` failing but only saying "the schemas are different"
The relevant tests are in ibis/tests/expr/test_set_operations.py, looks like the bases are already covered pretty well, don't think I need to add any more
> feat(ux): improve error message on unequal schemas during set ops

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/compiler.py
Turns out we can do this without a UDF. Thanks to @krzysztof-kwitt for the idea!
> refactor(snowflake): replace array repeat udf with builtin transform function

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
Fixes a bug where the scale was incorrectly left up to Snowflake, which can produce incorrectly scaled values if a timestamp is read in as a variant integer and then cast to string.
> fix(snowflake): ensure that timestamp conversion from parquet files is correct

- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_array.py
Adds array map and filter implementations to the Snowflake backend. Thanks again @krzysztof-kwitt for the idea!
The main limitation for the Snowflake versions of these APIs is that your lambda cannot reference any columns outside the scope of the lambda, which means the scope is limited to the lambda parameter and constants.
> feat(snowflake): implement array map and array filter

- ibis/backends/snowflake/tests/test_client.py
Fixes a testing usage of `ibis.snowflake.connect()`
> test(snowflake): use standard fixture instead of assuming `SNOWFLAKE_HOME` is set

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_array.py
Follow up to #9177 that adds a test for repeating a column array.
> test(arrays): add array repeat test on column expression

- ibis/backends/snowflake/compiler.py
- ibis/backends/tests/test_asof_join.py
Adds support for `asof_join` to the Snowflake backend.
Depends on #9181.
> feat(snowflake): implement support for `asof_join` API

- ibis/backends/clickhouse/compiler.py
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_hash/out.sql
- ibis/backends/duckdb/compiler.py
- ibis/backends/polars/compiler.py
- ibis/backends/sql/datatypes.py
- ibis/backends/tests/test_generic.py
fixes https://github.com/ibis-project/ibis/issues/9135
I don't love the logic that does the conversion. It seems more complicated than it needs to be, and I don't like how I had to implement it once for each backend, but maybe there is no universal way to do this. If you can think of a cleaner way to do this or sidestep the need entirely that would be awesome
> fix: convert the uint64's from some backends' hash() to the desired int64

- ibis/backends/snowflake/__init__.py
- split database and schema to pass to sqlglot for proper full name qualification
- conditionally include `use_stmt` to prevent invalid `USE SCHEMA` statement when 
currently `use_stmt` is generated like `'USE SCHEMA "DATABASE/SCHEMA"'`, it should be `'USE SCHEMA "DATABASE"."SCHEMA"'`
> fix(snowflake): properly pass schema and database for sqlglot generation

- ibis/backends/snowflake/tests/test_client.py
xref #9221
We weren't handling passing in `catalog/database` as the `database`
kwarg, despite our documentation telling users to do that.
This was fixed in the above PR -- here I'm adding a test to
ensure that both connection methods work.
> test(snowflake): add test for ibis.snowflake.connect

- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/test_client.py
Fixes #9192 -- I imagine some part of this was previously being handled by sqlalchemy, or we just missed something when porting over to sqlglot.
> fix(trino): parse URL passed to ibis.connect

- ibis/backends/tests/test_generic.py
- ibis/expr/types/relations.py
Adds a `value_counts` method to tables for convenience.
> feat(api): add `Table.value_counts` for easy group by count on multiple fields

- ibis/backends/snowflake/tests/test_client.py
The previous version of this test isn't passing on CI for reasons I can't quite understand, so I'm trying this instead.  We'll see?
> test(snowflake): use env-vars only for ibis.snowflake.connect test

- ibis/backends/duckdb/tests/test_client.py
Also test that named DB catalogs aren't bleeding over into unnamed memory dbs
This is a test to ensure we don't accidentally remove the functionality added in
#9241 for connecting to named in-memory databases in DuckDB.
> test(duckdb): test multiple connections to named in-memory db

- ibis/backends/trino/tests/test_client.py
`test_connect_uri` relies on the backend having been initialized with tables, which breaks when the test is run before that happens in another test. This PR fixes that by running a simple SQL query instead.
> test(trino): make sure uri connect test does not rely on backend data

- ibis/backends/bigquery/__init__.py
Followup to #9251 fixing up bigquery failures
> fix(bigquery): only register memtable if obj is not None

- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/datafusion/tests/test_connect.py
- ibis/backends/datafusion/tests/test_register.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/duckdb/tests/test_register.py
- ibis/backends/polars/__init__.py
- ibis/backends/polars/tests/conftest.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/tests/test_register.py
Looks like I messed something up in the rebase, I'll fix it soon. 
- Closes https://github.com/ibis-project/ibis/issues/8735
> refactor: deprecate register api

- ibis/backends/tests/test_generic.py
- ibis/expr/types/relations.py
- ibis/tests/benchmarks/test_benchmarks.py
When I am working on the https://github.com/ibis-project/ibis/pull/9139#issuecomment-2101711159, I had a `RecursionError: maximum recursion depth exceeded while calling a Python object` when union large number of tables, I found we had this similar issues before, https://github.com/ibis-project/ibis/issues/7124 and https://github.com/tobymao/sqlglot/issues/2961.
I am trying to rewrite the `union` in our codebase, It recursively union the tables using a queue, the number of unions is still similar to the original implementation, but it allow us to union more tables than before (It could unblock #9139 and added a test for larger number of tables where the original implementation will fail). Not sure if there is other side effect or not.  If it is not a good solution, I could close this PR. …
> perf(api): rewrite union and intersection construction to support more operands

- ibis/expr/api.py
- ibis/expr/operations/udf.py
- ibis/expr/types/arrays.py
- ibis/expr/types/generic.py
- ibis/expr/types/geospatial.py
- ibis/expr/types/logical.py
- ibis/expr/types/maps.py
- ibis/expr/types/pretty.py
- ibis/expr/types/relations.py
- ibis/expr/types/strings.py
- ibis/expr/types/structs.py
- ibis/expr/types/temporal.py
This is an attempt to close https://github.com/ibis-project/ibis/issues/9247 and possible the discussion around https://github.com/ibis-project/ibis/issues/8833
I'm using rich Panel and the `box.SQUARE` style to wrap scalar values into a box. There are multiple styles (see https://rich.readthedocs.io/en/stable/appendix/box.html), I chose the one that looks the most similar to what we have now. 
TODO:
- Do we need a tests for this? I wasn't quite sure how to add a test for it. 
- Modify doctests accordingly if we like this change
Closes https://github.com/ibis-project/ibis/issues/9247
Here is how it renders in ipython. 
```python
In [2]: ibis.options.interactive = True
In [3]: ibis.literal(1).nullif(1)
Out[3]: 
┌──────┐
│ None │
└──────┘
In [4]: …
```
> chore: add box to scalar expr in interactive mode

- ibis/expr/types/maps.py
part of https://github.com/ibis-project/ibis/pull/8666
> fix(typing): map() can take ArrayValues not just ArrayColumns

- flake.lock
- nix/ibis.nix
- nix/quarto/default.nix
Get nix setup working on macOS. Most of the work needed was in poetry2nix, the main exception being updating the quarto package definition.
> chore(dev-tools): get nix setup working on macOS

- ibis/backends/mysql/tests/test_client.py
- ibis/backends/sql/datatypes.py
> fix(mysql): support parametrized datetime types

- ibis/backends/mysql/__init__.py
- ibis/backends/polars/__init__.py
> fix(polars,mysql): avoid execution of query in `_get_schema_using_query`

- ibis/backends/tests/test_sql.py
No functional change here, just a refactor. Assigning to variables just made things more obscure.
Part of/prepping for https://github.com/ibis-project/ibis/pull/8666
> chore(test): remove indirection in test_sql.py

- ibis/backends/sql/datatypes.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_struct.py
I remove the docstring because it is obvious from the type signature,
and the docstring was wrong. The superclass has the correct docstring though,
just inherit that.
Part of https://github.com/ibis-project/ibis/pull/8666
> fix(clickhouse): more explicitly disallow null structs

- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/tests/base.py
- ibis/backends/tests/tpch/conftest.py
- ibis/backends/tests/tpch/snapshots/test_h01/test_tpc_h01/datafusion/h01.sql
- ibis/backends/tests/tpch/snapshots/test_h02/test_tpc_h02/datafusion/h02.sql
- ibis/backends/tests/tpch/snapshots/test_h03/test_tpc_h03/datafusion/h03.sql
- ibis/backends/tests/tpch/snapshots/test_h04/test_tpc_h04/datafusion/h04.sql
- ibis/backends/tests/tpch/snapshots/test_h05/test_tpc_h05/datafusion/h05.sql
- ibis/backends/tests/tpch/snapshots/test_h06/test_tpc_h06/datafusion/h06.sql
- ibis/backends/tests/tpch/snapshots/test_h07/test_tpc_h07/datafusion/h07.sql
- ibis/backends/tests/tpch/snapshots/test_h08/test_tpc_h08/datafusion/h08.sql
- ibis/backends/tests/tpch/snapshots/test_h09/test_tpc_h09/datafusion/h09.sql
- ibis/backends/tests/tpch/snapshots/test_h10/test_tpc_h10/datafusion/h10.sql
- ibis/backends/tests/tpch/snapshots/test_h11/test_tpc_h11/datafusion/h11.sql
- ibis/backends/tests/tpch/snapshots/test_h12/test_tpc_h12/datafusion/h12.sql
- ibis/backends/tests/tpch/snapshots/test_h13/test_tpc_h13/datafusion/h13.sql
- ibis/backends/tests/tpch/snapshots/test_h14/test_tpc_h14/datafusion/h14.sql
- ibis/backends/tests/tpch/snapshots/test_h15/test_tpc_h15/datafusion/h15.sql
- ibis/backends/tests/tpch/snapshots/test_h17/test_tpc_h17/datafusion/h17.sql
- ibis/backends/tests/tpch/snapshots/test_h18/test_tpc_h18/datafusion/h18.sql
- ibis/backends/tests/tpch/snapshots/test_h19/test_tpc_h19/datafusion/h19.sql
- ibis/backends/tests/tpch/snapshots/test_h20/test_tpc_h20/datafusion/h20.sql
- ibis/backends/tests/tpch/test_h16.py
- ibis/backends/tests/tpch/test_h21.py
- ibis/backends/tests/tpch/test_h22.py
This PR adds DataFusion to the TPC-H correctness test suite.
Depends on #9299.
> test(datafusion): run tpch correctness tests

- ibis/backends/tests/test_generic.py
- ibis/expr/types/relations.py
the same problem as in PR #9139,
Want to use `describe()` function on a large table from a Kaggle competition, which will serve as an example for IbisML.
None
> fix(datatypes): manually cast the type of pos to int16 for `table.describe()`

- docs/backends/pyspark.qmd
As of Ibis 9.0.0, passing a `SparkSession` to `ibis.pyspark.connect()` is no longer required; see https://github.com/ibis-project/ibis/commit/0f663e68dd30d3dc27ec83f787f438f96c71f6cc.
> docs(pyspark): remove outdated `connect()` callout

- ibis/backends/datafusion/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/pandas/kernels.py
- ibis/backends/polars/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/sql/rewrites.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_array.py
- ibis/backends/trino/compiler.py
Fixes #9313, see that issue for the original context.
This PR standardizes the `null` handling behavior of our `.collect()` method to always exclude `NULL` values from the aggregated array. Previously the behavior was backend dependent.
This is _technically_ a breaking change for some backends. I currently haven't flagged it in the commit, but if we deem it worth flagging we probably also want to hold off merging if we plan on doing a 9.1 release (since a breaking change would need to go in 10.0). I'm inclined to treat this more as a behavioral bug, which is why I didn't mark it as breaking here.
I also haven't tested this on the cloud backends, :crossed_fingers: that it passes in CI.
> fix: drop nulls in `.collect()` aggregation

- .github/actionlint.yaml
- .github/workflows/nix-skip-helper.yml
- .github/workflows/nix.yml
Testing out the new GitHub-hosted arm64 runners with a single nix job.
> ci: run one nix job on arm64 runner

- flake.lock
Among other things, this picks up the duckdb cli 1.0.0 bump.
> chore(dev-deps): bump nix flakes

- docs/presentations/overview.qmd
minor edits to history:
- note years of S/R dataframes
- "dataframe history" -> "Python dataframe history"
- remove dplyr
- add Vaex
- minor edits
- add Snowpark pandas API
closes #9336
> docs(presentations): minor updates to history in overview presentation

- ibis/__init__.py
- ibis/backends/__init__.py
- ibis/tests/test_api.py
This functionality was never ported to work with the new compiler
infrastructure in 9.0.
Not marking as a breaking change because the breakage is already done.
Resolves #9158
> chore(api): remove defunct add_operation from backends

- ibis/selectors.py
- ibis/tests/expr/test_selectors.py
Make the is-class check more specific, ensuring the class is an Ibis data type, to avoid catching other inputs (like Python types).
Resolves #9355
> feat(selectors): parse Python types in `s.of_type`

- ibis/backends/dask/kernels.py
- ibis/backends/datafusion/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/exasol/compiler.py
- ibis/backends/pandas/kernels.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_generic.py
- ibis/backends/trino/compiler.py
Similar to #9318. The handling of `NULL` values in `first`/`last` previously was backend specific. We now standardize all backends to exclude `NULL` values from these aggregations.
> fix: exclude null values from `first` and `last` aggregations

- ibis/backends/postgres/compiler.py
- ibis/backends/tests/test_generic.py
Postgres supports hashing on a per-type basis, with "extended" versions providing 64-bit integer output. To list these, run `\df hash*extended`:
Schema   |           Name           | Result data type |   Argument data types    | Type 
----------- | ------------------------ | ---------------- | ------------------------ | -----
pg_catalog | hash_aclitem_extended    | bigint           | aclitem, bigint          | func
pg_catalog | hash_array_extended      | bigint           | anyarray, bigint         | func
pg_catalog | hash_multirange_extended | bigint           | anymultirange, bigint    | func
pg_catalog | hash_numeric_extended    | bigint           | numeric, bigint          | func
pg_catalog | hash_range_extended      | bigint           | anyrange, bigint         | func
pg_catalog | …
> feat(postgres): provide translation for `hash` ops

- docs/contribute/index.md
While it's not easy to navigate to, the index for https://ibis-project.org/contribute/ currently links to a [non-existent CONTRIBUTING.md](https://ibis-project.org/CONTRIBUTING.md). This swaps the entire index page for the content that currently lives in docs/CONTRIBUTING.md.
I didn't test these changes locally because my environment for docs isn't set up (which I'm also working on fixing) so a review of how I did the links would be good.
> docs: update contribute index page content

- .github/workflows/ibis-backends.yml
- compose.yaml
For some reason the existing clickhouse health check is not working on GHA, despite it working locally for me. Using the specific ipv4 address works in both case. Probably some DNS or other networking detail has changed and is leaking through from the host configuration into the container.
> ci(clickhouse): use a different health check

- ibis/backends/mysql/__init__.py
- ibis/backends/mysql/datatypes.py
- ibis/backends/mysql/tests/test_client.py
This PR fixes an issue with using `.sql()` with MySQL in environments where the
user doesn't have permission to create tables.
Previously we created a temporary table with zero rows and then used that to
discover types of a query.
In this PR, I use the given zero-row `SELECT` query to get the types of the columns
using `cursor.description` along with some low level details of the MySQL protocol.
Inferring types this way doesn't allow getting type information from ad-hoc
types that use plugins, like uuid or inet, so their physical type is used
(string in both those cases).
This seems like an acceptable tradeoff given that without this change `.sql()`
cannot be used in a whole class of deployments/environments.
Closes #9354.
> fix(mysql): avoid creating any tables when using `.sql()`

- .github/workflows/nix-skip-helper.yml
- .github/workflows/nix.yml
- flake.lock
- ibis/backends/duckdb/tests/test_register.py
- ibis/backends/tests/test_export.py
- ibis/conftest.py
Apparently github has m1 hosted runners now
> ci: add m1 runners to nix builds and fast ci suites and bump nixpkgs dependency

- ibis/backends/pyspark/__init__.py
We already covered `pyarrow` in the-epic-split, but added these to
`to_delta` and `to_kafka`
* Resolves #8898
> fix(pyspark): plumb through `limit` and `params` in export functions

- .github/workflows/ibis-docs-main.yml
- .github/workflows/upload-algolia-api.py
There's a larger issue here, which is that the quarto `search.json`
doesn't seem to include a bunch of items which we generate using
`quartodoc`, which makes the docs very unhelpful for someone trying to
search (especially) method names.
This is definitely a hack, but I've tried uploading these records
manually and it does make a noticeable improvement.
And yes, I am scraping through QMD files to grab the anchors, and
descriptions, and method names, and yes that's gross, but computers are gross.
I'm planning to spend a bit more time to try to better understand how we
can better augment the algolia index so our search is more useful, but
this is both a start, and a proof-of-concept that we can append to our
existing index.
> docs(search): append scraped API records to algolia index in CI

- ibis/backends/snowflake/tests/test_udf.py
- ibis/backends/tests/test_generic.py
Ideally we can reenable these in the future in the Snowflake case, but it looks like `FARM_FINGERPRINT` no longer accepts anything except strings and bytes, so we might be out of luck there.
> test(clouds): disable flaky tests

- .github/workflows/nix.yml
Apparently empty arrays do not expand in the way I expected.
> ci: make sure args is never empty

- README.md
Removes Markdown syntax that doesn't render correctly on PyPI.
> docs: remove GitHub-specific Markdown in README.md

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/client.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
Add support for BigQuery sharded tables and use of `_TABLE_SUFFIX` pseudo-column for filtering shards. Closes #9371.
> feat(bigquery): support filtering by `_TABLE_SUFFIX` when using a wildcard table name

- ibis/backends/polars/compiler.py
This was never called, and its presence led to bugs when trying to add new code that works with `SortKey` instances (mistakenly assuming that this was doing the correct thing). Better to just raise a translation error when translating `SortKey` instances.
> refactor(polars): delete some dead code in the polars backend

- ibis/backends/tests/test_array.py
Apparently this got re-enabled upstream and our tests are now passing.
> test(snowflake): reenable array map and filter tests

- .github/workflows/upload-algolia-api.py
Would be good to have some output in the workflow runs to see if/how
records are going missing.  Might have to add a separate API gen call to
this workflow section to make sure the QMD files are present.
> chore(algolia): add print outputs to algolia index augmentation

- ibis/common/tests/snapshots/test_annotations/test_signature_from_callable_with_positional_only_arguments/parameter_is_positional_only.txt
- ibis/common/tests/test_annotations.py
Fixes an issue with one of our tests that assumes a specific error message structure. This structure changed in Python 3.12.4, causing the changed test to fail on `main`.
> test(common): replace error message snapshot with match

- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/conftest.py
- ibis/backends/trino/tests/test_client.py
In Ibis 10, I will change the connect API here to just forward kwargs, but for now this change is backward compatible and can be shipped in a non-major release.
Closes #9409.
> fix(trino): allow passing the `auth` keyword

- docs/posts/run-on-snowflake/index.qmd
This PR aims to create a post to tell the story about how we were able to get Ibis running inside Snowflake, fulfilling the reference in  https://github.com/ibis-project/ibis/blob/bdc1b3fbb8d44f9246c957b58372d3df84247468/docs/posts/ibis-version-9.0.0-release/index.qmd#L135-L136
This all ties back to #5877, with the resolution made possible thanks to the effort from converting to SQLGlot from SQLAlchemy.
> docs(blog): run Ibis on Snowflake

- ibis/backends/mysql/__init__.py
- ibis/backends/mysql/tests/test_client.py
> fix(mysql): ensure that `port` is captured in MySQL `_from_url` implementation

- ibis/backends/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/druid/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/sql/__init__.py
Removes redundant implementations of `_register_in_memory_tables`
> refactor(backends): remove redundant implementations of `_register_in_memory_tables`

- ibis/backends/duckdb/__init__.py
- ibis/tests/benchmarks/test_benchmarks.py
Speeds up memtable registration by a factor of some of multiple of N, where N is the number of tables in the database. In other words, the time to register a memtable is no longer dependent on the number of tables in the database.
> perf(duckdb): speed up memtable registration

- ibis/expr/operations/sortkeys.py
Removes a code path to handle tuples in `ops.SortKey`. This code path is apparently never hit (thanks to @ncclement for noticing this) and so has not worked for a while. Therefore, I decided to not mark this as a breaking change.
Closes #9413.
> refactor(api): remove `tuple` support in `SortKey`

- ibis/backends/bigquery/__init__.py
> perf(bigquery): avoid running `list_tables` when registering memtables

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
Moves BigQuery over to use `query_and_wait` to see if that reduces overhead.
Closes #8987.
Depends on #9425.
> perf(bigquery): use `query_and_wait` for better performance on queries of small data with smaller result sets

- ci/check_disallowed_imports.py
- ci/make_geography_db.py
- docs/how-to/visualization/example_streamlit_app/example_streamlit_app.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/unit/udf/test_core.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/duckdb/tests/test_register.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/pyspark/tests/test_ddl.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/sql/dialects.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/trino/__init__.py
- ibis/common/typing.py
- ibis/examples/gen_registry.py
- ibis/expr/tests/test_decompile.py
- ibis/tests/util.py
- ibis/util.py
- pyproject.toml
This PR adds ruff's `flake8-bandit` checks and fixes the lints or explicitly
ignores them (where it's low risk or unavoidable).
Most of the work here was in building SQL using sqlglot instead of constructing
queries using format strings.
That's not 100% foolproof for cases like `.sql()` methods, but we're at least
covering the bases in cases where we have more control over input.
> fix(sec): remove most instances of possible sql injection

- ibis/tests/benchmarks/test_benchmarks.py
> test(benchmarks): ensure that the benchmark has a bit more breathing room (again)

- ibis/backends/oracle/__init__.py
- ibis/backends/oracle/tests/test_client.py
We were missing the parsing part of parsing the connection string.
I also added an oracle-specific test to make sure this gets hit.
Resolves #9428
> fix(oracle): support connection using oracle connection string

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
- ibis/backends/tests/test_client.py
MSSQL has two kinds of temporary tables.
1. Local temporary tables, created in `tempdb.dbo`, prefixed with a
single `#` and suffixed with ~~112 underscores and a number.
2. Global temporary tables, created in `tempdb.dbo`, and prefixed with a
double `#`.
The suffixing on local temporary tables is to avoid name collisions
between separate user sessions trying to create the same temporary table
name.
Otherwise, the two types of temporary tables are functionally
equivalent. Users need specific access to look at temporary tables that
they didn't create, and all temp tables are cleaned up after the session
closes and all stored procedures referencing those tables have run.
Because of the slightly wacky semantics of local temporary tables, this
PR makes all temp tables created by the MSSQL …
> fix(mssql): fix temporary table creation and implement `cache`

- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/pandas/executor.py
- ibis/backends/polars/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/sql/compiler.py
- ibis/backends/sql/rewrites.py
- ibis/backends/tests/sql/snapshots/test_compiler/test_table_drop_with_filter/decompiled.py
- ibis/backends/tests/sql/snapshots/test_sql/test_no_cartesian_join/out.sql
- ibis/expr/decompile.py
- ibis/expr/operations/relations.py
- ibis/expr/types/relations.py
- ibis/tests/benchmarks/test_benchmarks.py
- ibis/tests/expr/test_table.py
This PR speeds up drop construction and compilation in cases where the number
of dropped columns is small relative to the total number of parent-table
columns.
There are two ways this is done:
- `drop` construction is sped up by reducing the number of iterations
over the full set of columns when constructing an output schema.
This is where the bulk of the improvement is.
- Compilation of the `drop` operation is also a bit faster for smaller sets of
dropped columns on some backends due to use of `* EXCLUDE` syntax.
Since the optimization is done in the `schema` property, adding a new
`DropColumns` relation IR seemed like the lightest weight approach given
that that also enables compilers to use `EXCLUDE` syntax, which will produce a
far smaller query than using …
> perf(drop): speed up performance of drop

- ibis/backends/tests/test_aggregation.py
- ibis/expr/operations/relations.py
- ibis/expr/types/groupby.py
- ibis/tests/expr/test_table.py
Allow grouping by scalar values. Needed for TPC-DS. In particular, query 27 uses this functionality.
Also a somewhat common pattern for building unions of aggregations from disparate tables.
> feat(api): allow grouping by scalar values

- ibis/backends/druid/compiler.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_string.py
Fixes a bug where we were not casting nulls to a specific type where we should.
Discovered during #9451.
> fix(druid): handle typed nulls where possible

- ibis/backends/tests/test_generic.py
discovered that casting arrays didn't work in druid when implementing https://github.com/ibis-project/ibis/pull/9458.
So I thought I was write down what I found.
> test: add some basic cast tests

- ibis/expr/tests/test_newrels.py
- ibis/expr/types/relations.py
This PR fixes an issue where we were using `unwrap_aliases` to deduplicate and
enforce expressions by their name in `filter`s.
That approach makes sense in the context of projections, but the name of
predicate expressions in a `filter` is irrelevant.
The solution was to continue to unwrap aliases but avoid deduplicating
expressions based on their name, and do it solely on the hash value of
expressions.
Closes #9474.
> fix(ir): avoid deduplicating filters based solely on their name

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
- ibis/backends/druid/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/trino/__init__.py
If the password is with a bracket in the connection url, `urllib.parse.urlparse(url)` will raise the error `ValueError: Invalid IPv6 URL` in `backends.connect()`. But if the caller quotes the password to avoid parsing failing, ibis does not unquote back the password.
```python
import ibis
import pytest
invalid_password = "invalid_password["
with pytest.raises(ValueError) as e:
ibis.connect(f"postgres://username:{invalid_password}@localhost:5432/dbname")
assert str(e.value) == "Invalid IPv6 URL"
```
> fix(uri-parsing): handle password with bracket in connection url

- ibis/backends/bigquery/compiler.py
- ibis/backends/clickhouse/compiler.py
- ibis/backends/duckdb/compiler.py
- ibis/backends/postgres/compiler.py
- ibis/backends/pyspark/compiler.py
- ibis/backends/snowflake/compiler.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/tests/test_array.py
- ibis/backends/trino/compiler.py
- ibis/expr/operations/relations.py
- ibis/expr/types/arrays.py
- ibis/expr/types/relations.py
Would love to get feedback from folks on the API especially @tswast. The new test is likely to fail on many backends. Looking for a bit of feedback before beefing up the test suite.
Closes #7781.
> feat(api): add `TableUnnest` operation to support cross-join unnest semantics as well as `offset`

- ibis/backends/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
- ibis/backends/druid/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/trino/__init__.py
This PR cleans up our URL handling a bit.
1. We were doing a bunch of unnecessary url parse -> url unparse, only to
immediately again parse the URL as the first call in every `_from_url`
implementation.
1. Each backend was separately handling converting query parameters to single
scalars where possible, due to the unparsing
1. Query parameters were sometimes passed into `kwargs` and sometimes parsed
again to then be used as kwargs later
So, I did the following:
1. Pass the `ParseResult` into the `_from_url` implementation.
1. Convert query parameters into single values where possible _before_ calling `backend._from_url`
1. Pass all query parameters as `**kwargs` into the `_from_url` call.
Fixes #9456.
> fix(urls): standardize pass-through of parsed query parameters

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_array.py
Workaround for https://github.com/pola-rs/polars/issues/17294
pl.concat_list(Iterable[T]) results in pl.List[T], EXCEPT when T is a
pl.List, in which case pl.concat_list(Iterable[pl.List[T]]) results in pl.List[T].
If polars ever supports a more consistent array constructor,
we should switch to that.
Found this when working on https://github.com/ibis-project/ibis/pull/9473
> fix(polars): add workaround to compile Array<Array> correctly

- flake.lock
Bump poetry2nix to pick up scipy 1.14 patch.
> chore(deps): fix macos build with scipy>=1.14 by bumping poetry2nix

- ibis/backends/bigquery/compiler.py
- ibis/backends/tests/test_aggregation.py
Implements countdistinctstar for bigquery
Bigquery does not support count(distinct a,b,c) or count(distinct (a, b, c)) (e.g. using a tuple, as is done with DuckDB) as expressions must be [groupable](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#group_by_grouping_item)
Instead, convert the entire expression to a string  `SELECT COUNT(DISTINCT ARRAY_TO_STRING([TO_JSON_STRING(a), TO_JSON_STRING(b)], ''))`
This works with all the bigquery datatypes ([source](https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions#other_conv_functions)). Using an array generates a unique, deterministic string for each combination of rows deterministically (see [json encoding](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json …
> feat(bigquery): implement CountDistinctStar

- ibis/backends/clickhouse/tests/test_datatypes.py
- ibis/backends/sql/datatypes.py
Add missing support for ClickHouse Date32 type.
> fix(clickhouse): support `Date32` database type

- justfile
Bump our duckdb python wasm build to 1.0.0.
> chore(deps): bump duckdb wasm to 1.0.0 in website jupyterlite build

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
- ibis/backends/oracle/__init__.py
- ibis/backends/oracle/tests/test_client.py
Fix oracle and clickhouse missing `port` in `_from_url`.
> fix(oracle, clickhouse): ensure `port` is captured in `_from_url` implementation

- ibis/backends/__init__.py
- ibis/common/caching.py
Remove some unnecessary parameters from `RefCountedCache`
> refactor(caching): remove parameters that are always the same

- ibis/backends/sql/datatypes.py
`citext` is a case-insensitive text field.
https://www.postgresql.org/docs/current/citext.html
Seems reasonable to map this to a `dt.string`
Resolves #9545
> fix(postgres): add dtype mapping for `citext`

- docs/how-to/visualization/example_streamlit_app/example_streamlit_app.py
- docs/how-to/visualization/streamlit.qmd
- ibis/streamlit/__init__.py
The Streamlit `connection` interface is no longer experimental as of https://github.com/streamlit/streamlit/pull/7536. 
`st.experimental_connection` was deprecated in Streamlit version 1.28.0 and replaced with [st.connection](https://docs.streamlit.io/develop/api-reference/connections/st.connection). 
Adjustments:
- `IbisConnection` class definition uses BaseConnection instead of ExperimentalBaseConnection.
- References of `st.experimental_connection` to use `st.connection`
- Usage of `relabel` to `rename` in the example application.
- "How To Streamlit + Ibis" post to reference `connection` usage with Streamlit developer documentation.
> refactor(streamlit): update to use BaseConnection interface

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_asof_join.py
- ibis/formats/pandas.py
- ibis/tests/benchmarks/test_benchmarks.py
Redo of #9554. The slow bit here was object conversion of timestamps, which seemed to only be hit by this one test.
> perf(duckdb): speedup timestamp conversion by avoiding conversion to object

- ibis/backends/sql/datatypes.py
We've had a number of issues where we haven't exposed a mapping to a
particular (usually Postgres) dtype.
We'll still have requests to provide useful mappings, depending on the
upstream dtype, but this should prevent users being unable to even open
a table because there's an unknown / user-defined dtype present in the
table.
To test, I've removed the special handling for the `vector` and
`ts.vector` types that we were explicitly mapping to `dt.unknown`.
xref #9511 -- we probably still want to pick a _specific_ dtype to map the BIT type to so that the data are REPRd, but this will prevent load failures (there and elsewhere).
> feat(dtypes): fall back to `dt.unknown` for unknown types

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
Redo of #9361.
Closes https://github.com/ibis-project/ibis/issues/9547.
> feat(duckdb): use `delta_scan` instead of reading pyarrow datasets

- ibis/backends/sql/datatypes.py
Reverts ibis-project/ibis#9567
Automerge did the wrong thing and merged this with 6 failing jobs
> revert: feat(dtypes): fall back to `dt.unknown` for unknown types

- .github/workflows/ibis-backends-skip-helper.yml
- .github/workflows/ibis-backends.yml
Adds a missing job to the `backend` ci job that gates passing CI.
> ci(bigquery): gate failure on bigquery lite jobs

- compose.yaml
Pin trino for now until the truncate table statement for in-memory connector can be fixed. See https://github.com/trinodb/trino/pull/22337#issuecomment-2227135370 for a reproducer.
> ci(trino): pin to 449 to avoid truncate table memory bug

- .github/workflows/ibis-main.yml
- ibis/backends/tests/data.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_dataframe_interchange.py
- ibis/backends/tests/test_export.py
- ibis/backends/tests/test_map.py
- ibis/common/tests/test_dispatch.py
- ibis/expr/datatypes/tests/test_value.py
- ibis/expr/tests/test_newrels.py
- ibis/expr/tests/test_schema.py
- ibis/expr/types/joins.py
- ibis/formats/pandas.py
- ibis/formats/pyarrow.py
- ibis/formats/tests/test_pandas.py
- ibis/formats/tests/test_pyarrow.py
- ibis/tests/expr/test_table.py
- ibis/tests/expr/test_value_exprs.py
- ibis/tests/test_api.py
- poetry.lock
- pyproject.toml
Make pyarrow an optional dependency for installs that do not require a backend.
> refactor(deps): make pyarrow optional for non-backend installs

- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/test_register.py
- change collect to execute_stream, `collect` pulls all the data in memory, `execute_stream` only pulls partial data (reducing memory consumed)
- fix creation of table with uppercase name and object (`pa.Table`, `pd.DataFrame`, etc)
- remove the use of strings literal for dialect
> feat(datafusion): datafusion enhancements

- ibis/backends/clickhouse/tests/conftest.py
- ibis/backends/tests/tpc/conftest.py
- ibis/backends/tests/tpc/ds/test_queries.py
- ibis/backends/tests/tpc/h/test_queries.py
- ibis/backends/tests/tpc/queries/clickhouse/ds/13.sql
- ibis/backends/tests/tpc/queries/clickhouse/h/19.sql
Adds TPC-H and TPC-DS testing to clickhouse.
Depends on #9525.
> test(clickhouse): add TPC-H and TPC-DS queries

- justfile
the `quartodoc` output lives in `docs/reference`, so if that folder
doesn't exist, or if it is empty, we can run the `docs-apigen` justfile
target to make sure the build succeeds.
There will definitely still be failure modes in here, but this should
cover the most common ones.
xref #9555
> chore(justfile): add check to justfile docs preview commands

- ibis/backends/dask/tests/test_operations.py
- ibis/backends/pandas/tests/test_operations.py
- ibis/backends/tests/test_conditionals.py
- ibis/backends/tests/test_generic.py
Prepping for https://github.com/ibis-project/ibis/pull/9096
- moves several .ifelse() and .substitute() tests from ibis/backens/test/test_generic.py into a new test_conditionals.py
- moves some .case() tests from the pandas and dask backends into there, so the other backends are now tested as well, and removed duplication.
- adds a test case that `ibis.literal(5).nullif(5).case().when(None, "oops").else_("expected")` results in "expected". Not saying this is actually the best behavior,
but it is currently what we claim to be expected. Perhaps we want to revisit.
> chore(test): consolidate ifelse() and case() tests

- ibis/expr/types/generic.py
Naturally, I was defeated by `arbitrary` and a lack of `order_by`.
> chore(docs): fix arbitrary docstring

- ibis/expr/tests/test_newrels.py
- ibis/expr/types/joins.py
As alternative to #9594, we here avoid the same signature error raised in #9561, when a `Literal` or more general `Value` in a `JoinChain` fails to be included in a `DerefMap`.
A statement like
`t3 = t1.inner_join(t2, "i").select("i", lit=1, val=2 * t1.x)` creates a `JoinChain` looking like
```
JoinChain[r0]
JoinLink[inner, r1]
r0.i == r1.i
values:
i:     r0.i
lit:   1
val:   2 * r0.x
```
with one of the reference "fields" in `values` actually pointing to a `Literal` and another one to a more general `Value`.
Adding a subsequent `JoinLink` to this `JoinChain` like by
`t5 = t3.inner_join(t4, "i")` fails in `prepare_predicates`, since the `DerefMap.from_targets(..., extra=reverse)` call tries to add a substitute from the new `lit`-field to the `Literal(1)` object and from `val` to the …
> fix(join): skip substitution of non-field references in join chains

- docs/_quarto.yml
- docs/presentations-listing.json
- ibis/expr/api.py
- ibis/expr/operations/udf.py
Some top-level APIs were missing from the API reference. This adds them.
> docs: add `deferred`, `range`, `e`, and `pi` to API reference

- ibis/backends/pandas/executor.py
- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/tests/test_join.py
- ibis/expr/operations/relations.py
- ibis/expr/types/joins.py
closes https://github.com/ibis-project/ibis/issues/9486. 
Add positional join to duckdb, pandas, and dask backends.
Amazingly simple to implement, a big cheers to the previous developers that made this code so clean and easy to edit!
By luck or magic, the pandas and dask backends seem to just work with no modification!
Should this be documented somewhere? I hesitate to clutter up the examples with this simple example. Really, I think the better thing that ibis really needs is a how-to guide on joining, where someone *actually* goes deep into the weeds and explains how things work.
> feat(api): add positional joins

- .github/workflows/ibis-backends.yml
- ibis/backends/conftest.py
- poetry.lock
- pyproject.toml
Increase the lower bound of pyspark to avoid a big hack in test collection. Also reduces hacking around numpy imports when making those optional in #9564.
> fix(pyspark): set lower bound of pyspark to 3.3.3 to avoid maintenance burden of pytest collection hook

- ibis/backends/flink/tests/test_memtable.py
This test is flaky, but not sure why, so I add an easier-to-read assertion here so we can see exactly what fails next time around.
Example flakiness: https://github.com/ibis-project/ibis/actions/runs/9949229765/job/27485143009?pr=9601
> test(flink): show more readable assertion error for flaky test

- ibis/backends/polars/compiler.py
Remove numpy usage from the polars backend entirely, it is no longer needed to work around missing functionality.
> refactor(polars): remove numpy usage entirely

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
[bigquery docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical) "[Identifiers] Must be enclosed by backtick (`) characters."
- enclose table names with backticks to avoid failures when spaces are included 
- remove L.586 as it appears to be redundant (see L.551)
- fix typo
* Resolves #9588
> fix(bigquery): escape table names with spaces for bigquery backend

- ibis/expr/datatypes/core.py
- ibis/formats/polars.py
- ibis/formats/tests/test_polars.py
- Closes https://github.com/ibis-project/ibis/issues/8479
polars datetime types have a fixed time unit (us, ns, or ms). Ibis timestamp types do too (but we also have seocnds as an option). In the case of polars we're currently mapping all timestamps to `ns`, this PR makes things a bit more specific and uses proper units. 
I'm still not sure how to handle the case `Ibis seconds` to maybe `ms in polars` ? Need a bit help on how the conversion of units happens, more specifically where is the value part handled? we would need to do `ibis_seconds*1000` = `polars_ms` at the moment I'm raising, similarly to what we do in durations, but I need to tackle this differently, see all the current failures in CI.
> feat(polars): add more accurate type mapping for timestamps

- ibis/backends/flink/tests/test_memtable.py
See https://github.com/ibis-project/ibis/actions/runs/9960229065/job/27519021003?pr=9608 for an example failure.
> test(flink): materialize results to avoid consuming an iterator to check for element membership

- ibis/expr/operations/arrays.py
- ibis/expr/operations/generic.py
- ibis/expr/operations/strings.py
- ibis/expr/operations/temporal.py
- ibis/expr/rules.py
Found this when looking into https://github.com/ibis-project/ibis/pull/9333
Usually when using eg duckdb's REGEXP_REPLACE() function, the pattern and replacement are always scalar constants. But actually it can accept columnar for all three of it's arguments.
These sort of assumptions appeared to be all over the place in the code base. I found these fixs by grepping for "shape_like" and manually looking at all the instances.
I didn't add any test cases, that felt like a monumental thing to do I wasn't willing to put the time in for. But IDK, I'm not sure I would even want to put in all the tests, it would be SO much boilerplate.
To deal with Nodes sometimes having optional args, I modified shape_like() to be more flexible.
IDK, that was sort of a lazy approach, we could be much more …
> fix(datatypes): infer the correct shape for many existing ops

- .github/workflows/upload-algolia-api.py
- docs/.gitignore
- docs/backends/_templates/api.qmd
- docs/backends/_utils.py
The backend-specific methods are added to the backend pages
programmatically using `quarto`.  That seems to lead to them not showing
up in our Algolia search, because they aren't being scraped.
It's a little gross, but I've added in a section to our api docs
rendering scripts to also dump the corresponding records for each method
into a backend-specific json file during `quarto` rendering.
Then those backend-specific records files are loaded and added to the
Algolia index in `upload-algolia-api.py`
Resolves #9600
> docs(algolia): add methods from backend pages to algolia index

- ibis/formats/pyarrow.py
Remove a dead code path that checks for pyarrow tables column equivalence.
> refactor(pyarrow): remove comparison of column names for renaming

- ibis/backends/flink/__init__.py
- ibis/backends/flink/tests/test_ddl.py
- ibis/backends/tests/test_client.py
Related to #9617, this marks a few tests in `ibis/backends/tests/test_client.py` as `notimpl`, because they would mean updating a view (think that's generally not reasonable?).
At the same time, there's no reason we shouldn't support at least constructing the memtable from a broader set of types. This goes through the `ibis.memtable` route, since it already supports a variety of types.
> feat(flink): create views from more mem data types

- ibis/backends/pyspark/__init__.py
@mark-druffel needs Spark-native export functionality. We had put off implementing the fast path because we were trying to figure out if we could unify output options, but we should probably add the fast path until we figure out a better alternative.
> fix(pyspark): run pre-execute hooks for `to_delta`

- ibis/backends/snowflake/tests/test_client.py
Adds a test for inserting from lists of dicts based on a [Zulip conversation](https://ibis-project.zulipchat.com/#narrow/stream/405263-general/topic/ibis-snowflake.208.2E0.2E0.20insert.20failures).
> test(snowflake): add tests for inserting from a list of dictionaries

- ci/schema/postgres.sql
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/postgres/tests/test_json.py
- ibis/backends/risingwave/tests/test_client.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/datatypes.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/parse.py
- ibis/expr/operations/json.py
- ibis/tests/strategies.py
Adds support for JSONB functionality in postgres. Closes #9626.
> feat(postgres): support basic jsonb type and existing operations

- ci/schema/exasol.sql
- ibis/backends/tests/test_dot_sql.py
> ci(exasol): add the astronauts dataset for testing

- .github/workflows/ibis-backends.yml
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/pyspark/tests/test_client.py
- poetry-overrides.nix
As reported in #9604, there is apparently a mismatch in permissioning structure
on Databricks, so that you can set a catalog and database (schema, ugh) with sql
by running `USE CATALOG`, but not via the pyspark api calls that (ostensibly) do
the same thing.
This, however, is not part of standard Spark SQL and is special
Databricks Spark SQL.
SO, we try the special databricks SQL, if that throws a parser error, we
fall back to using the pyspark API methods.
Resolves #9604
> fix(pyspark): set catalog and database with `USE` instead of pyspark api

- conda/environment-arm64-flink.yml
Release python pinning to 3.10 in the flink yaml file.
> chore(conda): relax python pinned version in the flink yaml file

- ibis/expr/types/relations.py
Adds `_fast_bind` from #9641, and uses it for the `drop` method, to gain a bit more performance.
Benchmarks show about 2-3x in all cases except when there are a relatively small number of columns **AND** only one column is dropped. If there are a large number of columns **OR** a large proportion of the columns are dropped then there's a notable improvement.
```
----------------------------------------------------------------------------------- benchmark 'test_wide_drop_construct[10-1]': 2 tests -----------------------------------------------------------------------------------
Name (time in ns)                                      Min                 Max                Mean            StdDev              Median               IQR             Outliers  OPS (Mops/s)            Rounds …
```
> perf(drop): use `_fast_bind` to speed up `drop` even more

- ibis/expr/tests/test_reductions.py
- ibis/expr/types/generic.py
Adds support for using deferreds in the `argmin` and `argmax` `key` argument.
> fix(api): add support for using deferreds in the `argmin`/`argmax` `key` argument

- ibis/expr/types/relations.py
- ibis/tests/benchmarks/test_benchmarks.py
Addresses `rename` performance from #9111 with wide tables by removing some unnecessary rewriting and dereferencing. Neither of these are necessary, because we already have all columns fully bound, we are simply giving them new names.
> perf(rename): avoid unnecessary rewrites and dereferencing in `rename`

- docs/how-to/analytics/basics.qmd
- ibis/expr/types/relations.py
- ibis/selectors.py
- ibis/tests/benchmarks/test_benchmarks.py
- ibis/tests/expr/test_relocate.py
This PR cleans up selector position computation in `relocate`, which was computing selector positions sometimes more than once as well as looping through **all** parent table columns more than once. For relocate, in general we should be bound in the worst case by the number of columns returned by selector, not by the number of columns in the table. Previously we did this with the `positions` method (deleted in this PR), which would, for every selector used in relocate look at every column. Now, the positions are computed from the inverted `_name_locs` dict that lives on Schema objects.
Depends on #9641.
Closes #9111.
> perf(relocate): avoid redundant selector position computation

- ibis/backends/mssql/__init__.py
Passing a port as a separate keyword argument is broken on `pyodbc` for
at least `ODBC Driver 18 for SQL Server`.
Passing the port in the hostname, however, works for both `FreeTDS` and
ODBC Driver 18, so we're just going to do that for now.
* Resolves #9619
> fix(mssql): always pass port to `pyodbc` in host string

- ibis/common/selectors.py
- ibis/expr/builders.py
- ibis/expr/types/relations.py
- ibis/selectors.py
- ibis/tests/expr/test_selectors.py
Support selectors in window function `group_by` and `order_by` arguments. Closes #9637.
> feat(api): support selectors in window function `order_by` and `group_by`

- ibis/backends/mssql/__init__.py
This PR attempts to address flaky behavior of MS SQL observed in CI.
It seems like calling `commit()`/`rollback()` with a `SELECT` statement, AKA autocommit behavior
can cause this issue.
The origin is not 100% clear to me, but there are a number of places where the
same problem (function sequence error) with the same solution show up
(disabling autocommit or not calling commit with a `SELECT` statement):
- https://stackoverflow.com/questions/25769043/function-sequence-error-in-pyodbc
- https://github.com/ansible-collections/community.general/issues/1137
- https://www.reddit.com/r/learnpython/comments/x8568m/function_sequence_error_in_sqlalchemy/
- https://github.com/explorerhq/django-sql-explorer/issues/423
Here I avoid calling `cur.commit()` unless a DDL statement is being executed.
The …
> fix(mssql): avoid calling `.commit()` unless a DDL operation is being performed

- ibis/expr/api.py
- ibis/tests/expr/test_timestamp.py
> feat(api): accept more input types in `ibis.range`

- ibis/expr/schema.py
- ibis/expr/tests/test_schema.py
> feat(pyarrow): support `__arrow_c_schema__` on `ibis.Schema` objects

- .github/workflows/ibis-backends.yml
- gen_redirects.py
- ibis/backends/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/druid/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/tests/test_client.py
- ibis/backends/trino/__init__.py
Enable backend creation from an existing DB-API connection
Resolves #8877
> feat(backends): support creation from a DB-API con

- ibis/expr/tests/test_schema.py
Previously we did not test roundtripping Ibis schemas to PyArrow schemas. This adds an xfailing test that will start to pass once the upstream arrow issue is addressed.
> test(schema): ensure that we attempt to call `__arrow_c_schema__`

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_temporal.py
Apparently we had a slew of tests for this that were simply failing. Spelunking a bit I found https://github.com/ibis-project/ibis/commit/8b711e9896d7a9fed501b05e4e6a332a876ffb19#diff-a87d0374de79428031576dd258bfeb6c63b3bb03dfa533ad1259e34e08575b3cR647, which is definitely something I introduced, but I cannot find anywhere that I documented why I added that.
Closes #9618.
> fix(polars): remove bogus minus-one-week truncation

- ibis/backends/polars/__init__.py
- ibis/backends/polars/compiler.py
- ibis/backends/polars/tests/test_udf.py
Remove casts from the Polars backend; consolidate output types using the usual `PandasData.convert_column`.
> refactor(polars): remove casting where possible; handle conversion on output

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_aggregation.py
Previously the `how` argument in `std`/`var` wasn't being handled. This wasn't caught, since for our testing dataset the results were close enough together that `assert_allclose` wouldn't notice. To fix this we subset the input data size to something small enough that the difference here is significant.
We also refactor the general reduction handling in the polars backend to simplify some of the code and remove some unnecessary filtering to improve performance.
> fix(polars): fix polars `std`/`var` to properly handle `sample`/`population`

- ibis/expr/operations/relations.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Since the ordering doesn't matter for `DropColumns`, a `VarTuple[str]` is probably the wrong data structure for the `columns_to_drop` attribute. This is a bug in the implementation of `DropColumns`—we should either change the type (a `frozenset[str]` would make more sense), or override the comparison so that `.equals` treats those as equal.
> fix(drop): ignore order for `DropColumns` equality

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/client.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/sqlite/udf.py
- ibis/backends/tests/test_window.py
- ibis/common/typing.py
- ibis/expr/types/core.py
- ibis/expr/types/relations.py
- ibis/expr/types/structs.py
- ibis/util.py
Resolves https://github.com/ibis-project/ibis/pull/9603#discussion_r1687104492 (done globally instead of just for BigQuery, for greater consistency)
> docs: replace all double graves with single graves

- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_bucket/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_assign_labels/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/close_extreme_false/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/close_extreme_false_closed_right/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/close_extreme_false_include_under_include_over/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/closed_right/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/closed_right_close_extreme_false_include_under/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/closed_right_include_over_include_under/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/default/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_over_include_under0/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_over_include_under1/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_over_include_under2/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_under/out.sql
- ibis/backends/impala/tests/snapshots/test_bucket_histogram/test_bucket_to_case/include_under_include_over/out.sql
- ibis/backends/impala/tests/snapshots/test_case_exprs/test_search_case/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_case_in_projection/decompiled.py
- ibis/backends/tests/sql/snapshots/test_select_sql/test_case_in_projection/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_searched_case/out.sql
- ibis/expr/builders.py
- ibis/expr/operations/generic.py
- ibis/expr/operations/logical.py
- ibis/expr/rules.py
- ibis/tests/expr/test_case.py
This is pinning down the expected behavior for cases before tackling the case() to cases() switch in https://github.com/ibis-project/ibis/pull/9096 so that PR can be simpler
> fix(case): fix dshape, error on noncomparable and empty cases

- ibis/expr/types/relations.py
Removes unnecessary use of `methodcaller` at a call site known to be costly in some cases.
There's no noticeable performance gain (or loss) here, this is mostly about removing unnecessary dynamism.
> refactor(internals): remove unnecessary dynamism in `drop` method

- docs/posts/run-on-snowflake/index.qmd
- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/conftest.py
- ibis/backends/snowflake/tests/test_udf.py
- ibis/backends/tests/test_client.py
Since Ibis 9.2, it should be possible to use `from_connection` (introduced in #9603) as a more standardized alternative to `from_snowpark`. `from_connection` also supports a `SnowflakeConnection` instance.
> depr(snowflake): deprecate `from_snowpark` method

- .github/workflows/ibis-main.yml
- ibis/tests/benchmarks/test_benchmarks.py
Fixes the upstream fail with druid compilation.
> test(benchmark): remove unnecessary `date` call in benchmark

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_explicit/expr0/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_explicit/expr1/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp0-0_0/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp1-1_1/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp2-2_2/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp3-0_0_1_1_2_2/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp4-2_2_1_1_0_0/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp5-0_0_1_1_2_2_0_0/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp6-0_0_1_1_2_2_0_0/out.sql
- ibis/backends/duckdb/tests/snapshots/test_geospatial/test_literal_geospatial_inferred/shp7-0_0_1_1_2_2_2_2_1_1_0_0/out.sql
Refactors the duckdb output to geospatial to use `* REPLACE` syntax to generate less code when replacing a small number of geospatial columns (usually one) among an otherwise large set of columns. Additionally, we now only need to loop over expression columns once.
> refactor(duckdb): use replace to generate less sql

- ibis/backends/dask/executor.py
- ibis/backends/pandas/executor.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/mysql.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/sqlite.py
- ibis/backends/tests/test_temporal.py
Adds support for quarterly date and timestamp truncate. Closes #9714.
> feat(api): support quarterly truncation

- ci/schema/mssql.sql
- compose.yaml
- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/conftest.py
- ibis/backends/mssql/tests/test_client.py
- ibis/backends/tests/test_generic.py
This should enable support for users working with Microsoft Fabric Warehouse
This updates a few internal table and view calls to use the
case-sensitive names which will allows us to (hopefully) support both
case-sensitive and case-insensitive collations.
The correct casing for the tables and views we use often (and the
corresponding columns):
Info schema tables:
- INFORMATION_SCHEMA.COLUMNS
- INFORMATION_SCHEMA.SCHEMATA
- INFORMATION_SCHEMA.TABLES
Temp table location: tempdb.dbo
Catalogs: sys.databases
Databases: sys.schemas
I also had to swap out a stored procedure that _really_ didn't like
being used with the case-sensitive collation, but I think the
replacement is nicer anyway (we can push down some column selection to
the engine).
* Resolves #9494
> feat(mssql): support case-sensitive collations

- ibis/expr/schema.py
- ibis/tests/benchmarks/test_benchmarks.py
Adds a modest 2x performance improvement when trying to construct schemas with duplicate keys.
> perf(schema): speed up failure case of duplicate keys when constructing schemas

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/converter.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_binary/difference/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_binary/intersection/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_binary/union/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_point/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_simplify/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/buffer/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/centroid/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/end_point/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/point_n/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/start_point/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary_union/out.sql
Fixes a bug in the BigQuery backend when looking at geospatial types in interactive mode.
> fix(bigquery): repr geospatial values in interactive mode

- ibis/expr/types/relations.py
Fixes a typo in the `drop` method failure mode example.
> docs: fix typo in `drop` method docstring

- ibis/backends/sql/rewrites.py
- ibis/backends/tests/sql/test_sql.py
- ibis/common/graph.py
This PR fixes an issue reported at least twice on Zulip:
[Here](https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/CTEs.20generated.20out.20of.20order)
most recently, and
[here](https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/.E2.9C.94.20CTEs.20are.20appearing.20out.20of.20order.20in.20large.20queries)
a while back.
The issue was that we weren't emitting CTEs (common table expressions) in topological order,
because our `find` API on `Node`s didn't order its output topologically.
This meant that sometimes nodes *would* be in topological order because that's
the way the query was constructed but in the case of queries with a graph
structure (more than one shared dependent) child nodes would be emitted before parents.
I added a flag, …
> fix(internals): ensure that CTEs are emitted in topological order

- ibis/backends/tests/test_sql.py
Apparently risingwave has implement support for `UNNEST`.
> test(risingwave): mark `test_union_aliasing` as notimpl because arbitrary aggregate function is not supported

- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/tests/snapshots/test_sql/test_union_aliasing/datafusion/out.sql
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_sql.py
- ibis/backends/tests/test_struct.py
Adds support for unnest, struct literals and fix struct field access, all enabling `pivot_longer` to work as well.
> feat(datafusion): `unnest`, struct literals, and `pivot_longer`

- ibis/backends/sql/compilers/oracle.py
- ibis/backends/tests/test_aggregation.py
Implements `group_concat` for Oracle, but correctly, compared to what we're currently doing in `main`, which is to compile it as `GROUP_CONCAT` instead of `LISTAGG`.
> feat(oracle): support `group_concat` operator

- ibis/backends/pandas/kernels.py
- ibis/backends/sql/compilers/bigquery.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/tests/test_array.py
Still a WIP, figuring out what should be desired.
`ibis.array([1, None, 2]).remove(2)` currently results in `[1]` on many backends. I would expect the NULLs to remain, eg `[1, None]`
> fix(arrays): array.remove() erroneously removes NULLs

- docs/backends/_utils.py
Follow-up to #9730.
I fixed adding the parent docstrings in the rendered docs, but those
weren't showing up in the search summary on Algolia.  They do now.
> fix(algolia): add parent class docstring to algolia index

- .codespellrc
- ibis/backends/tests/tpc/README.md
- ibis/backends/tests/tpc/conftest.py
- ibis/backends/tests/tpc/ds/test_queries.py
- ibis/backends/tests/tpc/queries/clickhouse/ds/48.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/32.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/35.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/38.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/42.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/45.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/48.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/49.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/58.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/61.sql
- ibis/backends/tests/tpc/queries/duckdb/ds/63.sql
Adds TPC-DS queries 28-63. The commits adding the Ibis expressions are in batches of 10. It seemed no less annoying to do it that way than to create a separate PR for each batch of 10.
> test(tpcds): add queries 28-63

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
- ibis/backends/tests/test_register.py
This functionality is available via `create_table` (and also available
across all backends instead of just DuckDB).
> depr(duckdb): deprecate `read_in_memory`

- ibis/backends/bigquery/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/trino/__init__.py
The previous `return None` short-circuit led to a bunch of `is None`
checks across the codebase.  If we always have a `sg.exp.Table`, even if
the fields are set to `None`, we can simplify those checks.
This is a small part of #9742
> refactor(table_loc): return consistent object from catalog.db parsing

- flake.nix
- nix/ibis.nix
Add `PYSPARK_PYTHON` to the nix environment, which allows developers using nix to test pyspark more easily. Thanks to @jstammers for finding this!
> chore(dev-deps): support pyspark in nix

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_udf.py
- ibis/backends/tests/test_udf.py
This PR modifies the pyspark Backend so that it can support UDFs implemented in pure python or pyarrow by making use of the `pyspark.sql.udf` wrapper.
To successfully run the unit tests for a pyarrow UDF, I needed to ensure that the spark worker executed the correct python interpreter by setting
```bash
export PYSPARK_PYTHON=$(which python)
```
within my nix shell. This might require some further configuration of the nix environment in order to pass during the CI tests.
* Resolves #9074
> feat(pyspark): add support for pyarrow and python UDFs

- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/risingwave.py
This avoids the case of a base class `SIMPLE_OPS` dict overriding the `UNSUPPORTED_OPS` list.
> fix(compiler-internals): define unsupported operations after simple operations

- flake.nix
Slight improvement on the previous shellHook approach, which isn't necessary because we know the interpreter path at build time.
> chore(dev-tools): define `PYSPARK_PYTHON` outside of shellHook since it is already known at build time

- ibis/backends/clickhouse/tests/snapshots/test_functions/test_group_concat/comma_none/out.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_group_concat/comma_zero/out.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_group_concat/minus_none/out.sql
- ibis/backends/impala/tests/snapshots/test_analytic_functions/test_analytic_exprs/first/out.sql
- ibis/backends/impala/tests/snapshots/test_analytic_functions/test_analytic_exprs/last/out.sql
- ibis/backends/pandas/executor.py
- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/bigquery.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/druid.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/exasol.py
- ibis/backends/sql/compilers/flink.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/mysql.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/risingwave.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/sqlite.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/sql/dialects.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_generic.py
- ibis/expr/operations/reductions.py
- ibis/expr/tests/test_reductions.py
- ibis/expr/types/generic.py
This adds a new `order_by` keyword argument to order-sensitive aggregates (`collect`/`group_concat`/`first`/`last`) to specify the ordering the aggregation should use. By default no ordering is specified, and the result is backend dependent (following the current behavior).
```python
In [2]: t = ibis.memtable({"x": [1, 3, 2, 4], "y": [10, 9, 8, 7]}, name="test")
In [3]: t.x.collect().execute()  # no ordering specified, backend-dependent result
Out[3]: [1, 3, 2, 4]
In [4]: t.x.collect(order_by="y").execute()  # use the specified ordering, or error if unsupported
Out[4]: [4, 2, 3, 1]
In [5]: ibis.to_sql(t.x.collect(order_by="y"))
Out[5]: 
SELECT
ARRAY_AGG("t0"."x" ORDER BY "t0"."y" ASC) FILTER(WHERE
"t0"."x" IS NOT NULL) AS "ArrayCollect(x, (y,))"
FROM "test" AS "t0"
``` …
> feat(api): support `order_by` in order-sensitive aggregates (`collect`/`group_concat`/`first`/`last`)

- ibis/backends/sql/compilers/snowflake.py
Fixes two bugs introduced in #9729.
- `where` handling was accidentally removed. This PR brings it back.
- `array_agg` must be ordered using `WITHIN GROUP`, it doesn't accept a trailing `ORDER BY` in the call.
> fix(snowflake): bring back `where` filter support in `group_concat`; fix `array_agg` ordering

- ibis/backends/tests/test_array.py
followup to https://github.com/ibis-project/ibis/pull/9089, I think this is a bit more intuitive
> test(arrays): remove unnecessary series construction in `test_array_remove`

- ibis/backends/postgres/tests/test_client.py
- ibis/backends/sql/datatypes.py
Handle postgres enum types as unknown. Closes #9295.
> fix(postgres): handle enums by delegating to the parent class

- .github/workflows/set-milestone-on-issue.yml
- ci/linked-issues.gql
- ci/set-milestone-on-issue.sh
Add an action to automatically set the milestone on linked issues after they are resolved by a PR.
> ci: add job to set the milestone of linked issues to match the milestone of the PR [skip ci]

- docker/mysql/startup.sql
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/exasol/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_client.py
- ibis/backends/trino/__init__.py
This started as a fix of #9686 but it turned up a few issues in other backends.
The short version is: when we call `get_schema` without specifying a
`catalog.database` prefix, we get tables that exist in many (sometimes all) the
databases on a given backend (that match the name passed to `get_schema`).
Postgres has things like `search_path` to help with this, but the tables on `search_path` are slightly different than what's returned by `\dt` (just to make this extra fun).
What's implemented here (and what I'm proposing as a general standard) is:
When you ask for a table named `foo`, we will look through the
`current_database` and wherever temp tables are stored for a match and return
the schema of that table.
My idea here is that anything that shows up in the output of `list_tables` (or …
> fix(sql): only return tables in `current_database`

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
Revert the use of DuckDB delta extension, since it cannot read delta files with more than 100 writes. Closes #9767.
> fix(duckdb): revert back to pyarrow dataset implementation when reading deltalake tables

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
Add support for the `types` argument to `read_csv` in the DuckDB backend.
> feat(duckdb): add support for passing a subset of column types to `read_csv`

- ibis/expr/types/relations.py
Fixing typo in `pivot_longer` explanation. 
I have also submitted an upstream PR to catch this in the future, although it's unlikely we'll re-encounter it. 
https://github.com/codespell-project/codespell/pull/3507
> docs: fix spelling in pivot_longer explanation

- .github/workflows/ibis-backends.yml
Follow-up to #9774, from an overly aggressive GitHub Actions check
> ci(flink): ensure that `pip`-installed dependencies are correctly specified

- ibis/backends/pandas/__init__.py
Remove unreachable code in the pandas' Backend that could be confusing
> refactor(pandas): remove unreachable code in pandas backend

- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/tests/test_string.py
Add `userinfo` URL parsing to Snowflake. Thanks to @krzysztof-kwitt for the suggestion!
> feat(snowflake): add `userinfo` URL parsing

- docs/_quarto.yml
This page existed but wasn't indexed.
> docs: add aggregate-udfs api page to index

- ibis/backends/tests/test_client.py
> test: avoid use of `TablesAccessor` in stateful `reconnect` test

- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/mysql.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_param.py
- ibis/backends/tests/test_temporal.py
Based on #9794, I decided to investigate whether we can do a bit better on date/timestamp +/- interval-style operations.
Many backends support adding and subtracting intervals from dates and timestamps, but do **not** support intervals as a first-class type, and we can allow that functionality to work.
This PR adds support for those operations to mssql and oracle and consolidates some existing implementation details around the `IntervalFromInteger` operation.
> feat(timestamps): add support for timestamp/date +/- intervals for additional backends

- ibis/common/annotations.py
- ibis/common/tests/test_annotations.py
- ibis/common/tests/test_grounds.py
- poetry.lock
- pyproject.toml
The pickles expect a specific constructor for `Parameter`, so remove our custom constructor and provide a `classmethod` with the previous behavior for convenience. Closes #9793.
> fix(pickle): make `Parameter` instances pickleable

- poetry.lock
- pyproject.toml
Unpinning cloudpickle because the specific version does not matter for the test case we are using it in.
> ci(snowflake): acquiesce to the dependency gods and unpin cloudpickle

- ibis/backends/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/tests/test_export.py
- ibis/expr/types/core.py
Initial implementation to add support to write parquet files to a directory as a single file or writing each batch to a different file. 
Partially resolves https://github.com/ibis-project/ibis/issues/8584#issue-2174862538 (it doesn't cover writing csv to dirs)
TODOs:
> feat(output-formats): add support for to_parquet_dir

- .github/workflows/ibis-backends.yml
- ibis/backends/conftest.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/impala.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/mysql.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/risingwave.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/sqlite.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/tests/test_temporal.py
- ibis/backends/tests/test_window.py
Follow-up to #9799 to consolidate some repetitive interval-handling code.
> refactor(intervals): conslidate interval conversion under `_make_interval` base compiler implementation

- ibis/backends/clickhouse/tests/snapshots/test_functions/test_timestamp_truncate/d/out.sql
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/tests/test_temporal.py
Support more units in clickhouse timestamp truncation
> feat(clickhouse): support ms/us/ns truncate units

- flake.nix
The script can be run using `nix run .\#gen-examples`. There is no real need to actually include this large derviation in the dev shell.
> chore(dev-deps): remove gen-examples script from dev-shell

- ibis/backends/polars/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/tests/test_dot_sql.py
- ibis/expr/types/relations.py
> fix(dot-sql): ensure that CTEs can be used in `.sql`

- ibis/expr/api.py
- ibis/expr/operations/udf.py
- ibis/expr/types/generic.py
- ibis/expr/types/geospatial.py
- ibis/expr/types/logical.py
- ibis/expr/types/pretty.py
- ibis/expr/types/relations.py
- ibis/expr/types/strings.py
- ibis/expr/types/temporal.py
Previously our interactive repr just called `str(value)` on scalars before passing off to `rich`. We now apply the same logic we do for columnar values to scalars as well. This provides a more uniform interactive repr experience, where scalars and columns have identical formatting rules.
Fixes #9820
> fix(repr): format scalar values with same logic as columnar values

- ibis/backends/tests/test_vectorized_udf.py
- ibis/expr/types/structs.py
- pyproject.toml
Deprecate `StructValue.destructure` in favor of `StructValue.lift` or `Table.unpack`.
> depr(api): deprecate `StructValue.destructure` API

- ibis/backends/impala/__init__.py
- ibis/backends/impala/ddl.py
- ibis/backends/impala/tests/test_partition.py
`TBLPROPERTIES` can be set on table creation. Exposing this lets us un-xfail a few tests by setting the required `TBLPROPERTIES` to make them work.
> feat(impala): add `tbl_properties` to `create_table`

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
Iterate rows directly without sorting by key.
Resolves #9846
> fix(mssql): remove sort key to keep order

- ibis/backends/duckdb/tests/test_datatypes.py
These are already supported automatically through sqlglot, just adding a test here. Fixes #7963.
One open question: currently these are cast to variable-length lists in `to_pyarrow` (matching the existing behavior of `dt.Array` types), but it could be argued that we should pass them through as fixed-length lists instead. This would require a bit of work, but nothing too tricky.
> test(duckdb): add test for supporting fixed-size array types

- ibis/backends/sql/datatypes.py
- ibis/backends/sql/tests/test_datatypes.py
This is a loose follow-up to #9576.
In that PR, I added support for falling back to `dt.unknown` when `sqlglot`
failed to parse a type string.  In that case, it was usually handling things
like user-defined types in Postgres.
This is a related change, where we mark a dtype as `unknown` if `sqlglot` _does_
parse it correctly, but we don't have support for the dtype.  The user can't
operate on the column in question, but at least the table will load.
A representative issue is loading a table in Clickhouse that has a `uint256` column
xref #9861
Closes #9869.
> feat(sql): load parsed but unsupported types as unknown

- ibis/backends/sql/compilers/exasol.py
- ibis/backends/sql/dialects.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_generic.py
In a previous PR I noticed that the exasol backend had a bunch of xfails with `strict=False` that were masking deeper weirdness in the exasol backend. This removes the `strict=False`, fixes some tests, and expands coverage of aggregations in exasol.
> feat(exasol): implement a bunch of missing aggs

- ibis/backends/exasol/converter.py
- ibis/backends/sql/compilers/exasol.py
- ibis/backends/sql/dialects.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_conditionals.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_join.py
This:
- Fixes a bug where returning `int64` values wasn't properly handled
- Based on this fix, implements `cov`/`corr`
Based on #9870.
> feat(exasol): implement `cov`/`corr`, fix int64 support

- pyproject.toml
> ci(snowpark): ignore warnings from the `logging` module

- ibis/backends/clickhouse/tests/test_functions.py
- ibis/backends/impala/tests/test_exprs.py
- ibis/backends/impala/tests/test_value_exprs.py
- ibis/expr/types/numeric.py
Partially addresses https://github.com/ibis-project/ibis/issues/9854
> refactor(api): make unit required in IntegerValue.as_timestamp

- docs/backends/snowflake.qmd
Document user-confirmed method of connecting to snowflake using a private key
instead of a password.
xref #9837
> docs(snowflake): document using private key to connect to snowflake

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
- ibis/backends/oracle/tests/test_client.py
> feat(mssql): support connecting with a url

- docs/_tabsets/install.qmd
- docs/backends/dask.qmd
- docs/backends/pandas.qmd
- ibis/backends/dask/__init__.py
- ibis/backends/pandas/__init__.py
- pyproject.toml
Deprecates the dask and pandas backends.
> depr(dask,pandas): deprecate the dask and pandas backends

- docs/posts/farewell-pandas/index.qmd
Blog explaining a bit of history and why we are dropping the pandas backend.
xref #9888
> docs(blog): post on why we are dropping the pandas backend

- ibis/expr/types/core.py
- ibis/expr/types/generic.py
~Remove~ Deprecate a method that apparently has no effect anymore since every operation has a name since 9.0.
> depr(expr-api): deprecate useless `has_name` method

- ibis/common/tests/test_deferred.py
- ibis/expr/types/generic.py
- ibis/selectors.py
- ibis/tests/expr/test_selectors.py
Test method calls in across selector; allow naming to work in across calls.
Closes #9900.
> feat(selectors): allow naming in the `across` selector and support non-expression methods

- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_approx_quantiles/array/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_approx_quantiles/complete-array/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_approx_quantiles/scalar/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_approx_quantiles/shuffled-array/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_approx_quantiles/tricky-scalar/out.sql
- ibis/backends/bigquery/tests/unit/test_compiler.py
- ibis/backends/clickhouse/tests/test_aggregations.py
- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/exasol.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/risingwave.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/tests/test_aggregation.py
- ibis/expr/operations/reductions.py
- ibis/expr/tests/test_reductions.py
- ibis/expr/types/generic.py
- ibis/expr/types/numeric.py
This adds a new `approx_quantile` method for computing approximate quantiles. Like the corresponding exact version, it can take:
- A single quantile (`col.approx_quantile(0.5)`), returning a single scalar result
- An array of quantiles (`col.approx_quantile([0.25, 0.75])`), returning an array of results
Unlike `col.quantile`, this is only implemented for numeric types (for now). Most backends support only numeric values for the approximate version, as the algorithms don't easily adapt to non-numeric types. If needed, we _could_ move this to be on a generic type, but most implementations would error for other dtypes.
Fixes #9541.
> feat(api): approximate quantiles

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
Closes #9879. Not a huge amount of effort to thread these through since they are already supported in `clickhouse-connect` query methods.
> feat(clickhouse): partition kwargs for compile and execution in `to_pyarrow` and `to_pandas`

- ibis/backends/tests/test_aggregation.py
Test added in #9881 now passes since #9884.
> chore(datafusion): unxfail passing `approx_quantile` test

- ibis/expr/types/generic.py
- ibis/tests/expr/test_literal.py
- ibis/tests/test_strategies.py
Allow passing deferred inputs to `literal`.
> feat(api): support deferred objects in `literal`

- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/pandas/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/tests/test_client.py
- ibis/backends/trino/__init__.py
This requires a test and implementation for other backends, but I wanted to get some feedback before I went for it.
Currently, you have to pass a real ibis.Schema to create_table(). Now it supports dicts and iterables of (name, type) pairs.
This is now consistent with `ibis.table()`.
Example usage:
```python
import ibis
db= ibis.duckdb.connect()
db.create_table(
"t",
{"x": []},
schema={"x": "string"},
)
```
currently, this errors. With this change, it works.
> feat(api): support `SchemaLike` in `Backend.create_table()`

- ibis/backends/datafusion/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/tests/test_client.py
- ibis/selectors.py
This change intends to support scenarios where a user needs to insert into a table where a table contains DEFAULT values on columns, meaning the incoming object may have fewer columns than the target table schema. 
It's common to insert into tables with DEFAULT constraints; in many cases, these are sequences, and it is a bit tricky to provide the sequence "nextval" approach today. 
This topic was initially brought up in [Zulip](https://ibis-project.zulipchat.com/#narrow/stream/405263-general/topic/insert.20with.20default.20columns.20on.20target.20table).
Here is an example of this in practice:
```py
import ibis
import pandas as pd
con = ibis.duckdb.connect()
con.raw_sql("CREATE TABLE example (a INTEGER DEFAULT 1, b VARCHAR NOT NULL);")
df = pd.DataFrame(
{
"a": [1, 2, 3],
"b": ["foo", …
```
> feat(sql): support inserts with default constraints

- ibis/backends/sql/compilers/oracle.py
Remove a duplicate `ops.Hash` mapping in the Oracle backend `SIMPLE_OPS` mapping.
> chore(oracle): remove duplicate `ops.Hash` specification

- docs/posts/farewell-pandas/index.qmd
- update date to today
- "Pandas" -> "pandas" per style guide
- add "to and from" Ibis for the format sentence
> docs(blog): minor edits to pandas blog

- ibis/backends/bigquery/tests/unit/test_compiler.py
- ibis/backends/sql/compilers/bigquery/__init__.py
> fix(bigquery): disallow column names longer than 300 characters

- ibis/backends/__init__.py
This PR removes circular references to backends `TablesAccessor`.
> refactor(internals): remove `cached_property` on the `tables` accessor to avoid a reference cycle

- ibis/backends/clickhouse/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
If you tried
```python
import ibis
conn = ibis.duckdb.connect("with space.duckdb")
conn.create_table("foo", {"a": [0,1,2]})
```
then you would get the DDL `CREATE TABLE with space.main."foo" ("a" BIGINT)`. Now, the database name is quoted.
I went through the create_table() method in all the backends and looked for where we forgot to use "quoted", but I almost definitely missed some cases.
I need to add a test for this, but I would love your help with this:
- should it add/modify a create_table() test to check for a database with spaces in the name?
- should it go somewhere near other tests that check for spaces? I think we have those?
- or should we go larger, and modify the `con` fixture to sometimes be a database with spaces in the name?
> fix(duckdb): fix create_table() in databases with spaces in the name

- ibis/backends/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/tests/test_api.py
- ibis/backends/tests/test_client.py
Fixes some hacks around `current_catalog` and `current_database` for the Oracle backend
> fix(oracle): implement current_catalog and current_database correctly

- ibis/backends/polars/__init__.py
- ibis/backends/polars/tests/test_client.py
- ibis/backends/tests/errors.py
Fixes an issue in the polars backend where tables were still visible in SQL queries after being dropped. Ripped out of #9903.
> fix(polars): use `drop_table` when cleaning the cache and remove duplicated `_remove_table` method

- ibis/backends/tests/tpc/ds/test_queries.py
This PR adds query 82 for tpc ds, the query on duckdb returns empty. Please double check the ibis code, as this is my first one converting to ibis. 
```bash
D load tpcds;
D call dsdgen(sf=0.45);
100% ▕████████████████████████████████████████████████████████████▏ 
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows  │
└─────────┘
D pragma tpcds(82);
┌───────────┬─────────────┬─────────────────┐
│ i_item_id │ i_item_desc │ i_current_price │
│  varchar  │   varchar   │  decimal(7,2)   │
├───────────────────────────────────────────┤
│                  0 rows                   │
└───────────────────────────────────────────┘
D 
```
> test(tpcds): add query 82

- ibis/common/selectors.py
- ibis/expr/types/relations.py
- ibis/selectors.py
- ibis/tests/expr/test_selectors.py
This is a refactor of selectors internals.
The disparity between the `Predicate` class and the `Selector` has always
bothered me, because not every selector can be easily made into a predicate.
And, for the ones that can, there are some often-used ones that are really
awkward to express as predicates, like the `c` selector, which expressed as
a predicate led to performance problems and IMO unnecessarily complex solutions
to that performance problem.
I thought to myself, "What are selectors doing fundamentally?"
And the answer I came up with is that they are producing a sequence of column
names that can be used to subset columns in a table.
Set operations ended up being a much more natural way to model the problem, while
allowing subclasses of `Selector` to customize operations for …
> refactor(selectors): remove janky `Predicate` class and unify `Selector`s under a single interface

- ibis/backends/sql/dialects.py
- ibis/backends/sql/tests/test_compiler.py
Fixes an issue discovered in #9933 where my failing to remove a workaround caused a bug in transpilation joins.
> fix(trino): remove hack that silently breaks join transpilation

- ibis/backends/tests/test_generic.py
- ibis/expr/types/relations.py
Fixes an issue with handling simpler cases of `Table.pivot_wider` where you want to take two columns and use one as the header and one as the first and only row.
> fix(pivot-wider): handle the case of empty `id_cols`

- ibis/backends/tests/tpc/ds/test_queries.py
- ibis/backends/tests/tpc/queries/duckdb/ds/72.sql
Trino syntax error on the join chains, and datafusion doesn't have date delta
> test(tpcds): add queries 72-74

- ibis/backends/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/dask/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
- ibis/backends/oracle/__init__.py
- ibis/backends/pandas/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/tests/test_expr_caching.py
- ibis/common/caching.py
- ibis/expr/types/relations.py
This:
- Simplifies the implementation of `.cache()`. Abstracting things out to a general `RefCountedCache` led to some hard-to-follow code paths for no added benefit (we weren't using that class anywhere else, and there were no isolated tests for the functionality). Moving to a mixin in the `BaseBackend` made the methods required a lot easier to follow.
- Given the simpler code path, I was able to find a bug in the `mssql` implementation that was preventing support. `.cache()` now fully works with `mssql`.
Net decrease in LOC, while adding functionality and tests.
This change was motivated by #6195, which I'll add as a follow-up.
> refactor: simplify cache, add support for `mssql`

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
The initial deprecation PR for `read_in_memory` suggested passing data to
`create_table`, but that _will_ create a copy of in-memory data, which is
different than the existing behavior of `read_in_memory`
Updating the message to suggest `memtable` instead, which does _not_ create a copy (on DuckDB).
xref #9666
> chore(duckdb): update alternative method for in-memory data registration

- ibis/backends/tests/tpc/conftest.py
- ibis/backends/tests/tpc/ds/test_queries.py
Should fix the upstream flakiness
> test(tpcds): increase timeout marker for trino

- ibis/backends/datafusion/tests/test_select.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_join.py
- ibis/backends/tests/test_map.py
- ibis/backends/tests/test_string.py
- ibis/backends/tests/test_temporal.py
- ibis/backends/tests/test_vectorized_udf.py
- ibis/backends/tests/test_window.py
Remove some test decorator clutter that is no longer required.
> test(cleanup): remove dead `xfail_version` clutter

- ibis/backends/tests/tpc/conftest.py
- ibis/backends/tests/tpc/ds/test_queries.py
- ibis/backends/tests/tpc/h/test_queries.py
Adds a test for tpch and tpcds to verify that all queries are written, and to list all the ones that are not, when run with `--runxfail`
> test(tpc): add test to verify and list all queries are written

- ibis/backends/tests/tpc/ds/test_queries.py
76 and 78 are passing, 77 requires rollup, but I tried to write it so it would pass when `rollup` exists, but no promises.
> test(tpcds): add queries 76-78

- ibis/backends/postgres/__init__.py
Fixes doctests of the postgres backend. I couldn't help but notice that the `run doctests` [step](https://github.com/ibis-project/ibis/actions/runs/10617401640/job/29430553173) of CI is not running for this file and others. I can be overlooking something or is that expected ?
There's no open issue for this. Let me know case this doesn't make any sense.
> docs: fix doctests for postgres backend

- ibis/backends/sql/dialects.py
- ibis/backends/tests/tpc/ds/test_queries.py
- ibis/backends/tests/tpc/queries/duckdb/ds/87.sql
Add query 87 and workaround a bug in sqlglot (fixed upstream in https://github.com/tobymao/sqlglot/pull/4007)
> fix(clickhouse): workaround `EXCEPT` and `INTERSECT` generation in sqlglot; add tpcds query 87

- ibis/backends/duckdb/tests/conftest.py
- ibis/backends/tests/tpc/ds/test_queries.py
- ibis/backends/tests/tpc/queries/clickhouse/ds/64.sql
- nix/ibis.nix
So this should probably not get merged yet?  Or we can merge it and mark the
DuckDB failure and investigate further.
My notes so far:
There is some _weird_ stuff happening _only_ inside Pytest when running
this query on DuckDB.  This doesn't happen with any other tpc-ds
queries, and the query in question seems to run without issue on the
other backends that can run the tpc-ds queries.
If I generate sf=1 tpc-ds data in the DuckDB CLI, then run the included
sql file (which is the SQL generated by Ibis for this query), it runs in
about half a second.
If I `%load ibis_tpcds_64_local.py` and then run the `expr` there (which
is a copy-paste of the test code), it takes about half a second.
If I remove the `pytest.timeout` from the `tpc_test` decorator, this
same query, even at sf=.45 (which is …
> test(tpcds): add query 64

- ibis/backends/polars/__init__.py
- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_generic.py
- ibis/expr/operations/relations.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
- ibis/formats/pandas.py
- ibis/formats/polars.py
- ibis/formats/tests/test_polars.py
- ibis/tests/expr/test_table.py
Removes some code for renaming, which we were only doing because of `ops.DummyTable` and was ultimately unnecessary if we unalias its operations like we are doing elsewhere.
> refactor(aliasing): remove the need for renaming after execution

- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/tests/test_array.py
Works around a bug in the datafusion implementation of `ArrayFlatten` where a flattened `NULL` value returns an empty array instead of `NULL`.
> fix(datafusion): handle `NULL`s in array `flatten`

- compose.yaml
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_window.py
I noticed we had a very old version of RisingWave, and bumped it to the latest release, which fixed a number of bugs and added support for `RANGE` window function frames, which caused a number of tests to start XPASS-ing.
> test(risingwave): bump to latest risingwave release and enable now-passing tests

- ibis/backends/trino/__init__.py
> feat(trino): wrap `auth` strings with `BasicAuthentication`

- ibis/backends/polars/compiler.py
- ibis/backends/polars/tests/test_client.py
- ibis/backends/tests/test_array.py
> fix(polars): use `flatten` API for `ArrayFlatten` implementation to avoid large string upcast

- ibis/expr/types/core.py
Based on #9811, I removed the code (`_repr_mimebundle_`) that was causing duplicated tracebacks. Instead I implemented `_repr_pretty_` (for the consoles) and `_repr_html_` for the notebook.
Closes #9990.
> fix(ux): get rid of duplicated tracebacks

- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/sql/rewrites.py
- ibis/backends/tests/sql/snapshots/test_compiler/test_column_distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_compiler/test_table_distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct-filter-order_by/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct-filter/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct-non-trivial-select-distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct-non-trivial-select/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct-select-distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct-select/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/non-trivial-select-distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/order_by-distinct-drop/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/order_by-distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/order_by-drop-distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_fuse_distinct/select-distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_distinct/projection_distinct/out.sql
- ibis/backends/tests/sql/snapshots/test_sql/test_distinct/single_column_projection_distinct/out.sql
- ibis/backends/tests/sql/test_select_sql.py
- ibis/backends/tests/test_generic.py
This generates more concise SQL when chaining relational operations with `.distinct()`.
Fixes #9905.
> feat(sql): fuse `distinct` with other select nodes when possible

- docs/concepts/datatypes.qmd
Cleans up the exception printing for the datatypes.qmd file showing invalid mixing of unrelated columns.
> docs(datatypes): install rich traceback handler for prettier exception tracebacks

- ibis/backends/polars/tests/test_client.py
- ibis/formats/polars.py
- ibis/formats/tests/test_polars.py
> fix(polars): support polars `Enum` type

- ibis/backends/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
The original `kwargs` are not passed to the `backend._from_url()` if `scheme != "file"`
> fix(backends): pass kwargs to _from_url() in every case

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
- ibis/backends/tests/test_dot_sql.py
> fix(mssql): ensure that dot-sql can be executed when column names are not provided

- ibis/backends/impala/__init__.py
- ibis/backends/impala/tests/snapshots/test_string_builtins/test_string_builtins/lstrip/out.sql
- ibis/backends/impala/tests/snapshots/test_string_builtins/test_string_builtins/rstrip/out.sql
- ibis/backends/impala/tests/snapshots/test_string_builtins/test_string_builtins/strip/out.sql
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/flink.py
- ibis/backends/sql/compilers/impala.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/dialects.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_string.py
BigQuery:
-   `rstrip` and `lstrip` are broken because of a SQLGlot bug, already fixed upstream.
Snowflake:
-   `rstrip` and `lstrip` are broken because of a SQLGlot bug, already fixed upstream.
MSSQL:
-   `contains` might work, but requires &ldquo;fulltext index&rdquo; and I can&rsquo;t be bothered
-   `rpad` not defined
-   `lpad` not defined
-   `find_in_set` not defined
Oracle:
-   Treats `len(🐍) == 2`, should be able to use `LENGTHC` instead
-   `strip` maps to `trim`, but `TRIM` doesn&rsquo;t accept custom characters, unlike `RTRIM` and `LTRIM`
Flink:
-   Treats `len(🐍) == 2`
-   `strip` maps to `trim`, but `TRIM` doesn&rsquo;t accept custom characters, unlike `RTRIM` and `LTRIM`
There is a function in the docs called `BTRIM` but maybe it&rsquo;s only in dev?  But that should work? …
> test(strings): improve selected string tests

- ibis/backends/impala/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/sql/rewrites.py
- ibis/backends/tests/sql/snapshots/test_compiler/test_subquery_where_location/decompiled.py
- ibis/backends/tests/sql/snapshots/test_sql/test_binop_with_alias_still_parenthesized/out.sql
- ibis/backends/tests/sql/test_compiler.py
- ibis/backends/tests/sql/test_sql.py
- ibis/expr/operations/relations.py
- ibis/expr/types/relations.py
- ibis/formats/pandas.py
- ibis/formats/tests/test_pandas.py
Fixes #9975.
In the long run the best fix is probably something like #8135 (except for `Alias`) so we could automatically coerce aliases to their core values within `Value.__coerce__` (except for the very few ops where we care about preserving them). For now though this is a pragmatic fix that resolves the issue.
> fix(sql): properly parenthesize binary ops containing named expressions

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
This:
- Fixes a bug introduced in #10016 where bigquery wasn't handling column name mismatches in results
- Also fixes a longstanding bug where `_TABLE_SUFFIX` wasn't being handled in `to_pyarrow`/`to_pyarrow_batches`
- Refactors `__pyarrow_result__`/`__pandas_result__` to have more uniform args. I intended on also using this in more places to avoid redundant `convert_table` calls, but due to dtype inconsistencies this proved to be a :rabbit: :hole:. Punting on that for now, but leaving the plumbing in place since it's used by the bigquery backend.
> fix(bigquery): fix column name mismatches and support `_TABLE_SUFFIX` in all `to_*` methods

- jupyter-lite.json
In #10046, our robot overlords determined that we should upgrade jupyterlite,
but that is not tenable for us until the next release of Pyodide.
So, until that happens, we need to disable the insecure extensions.
Users will lose the ability to display math in our web console for now.
> docs(jupyterlite): disable insecure extensions

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
> fix(duckdb): free memtables based on operation lifetime

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
Fixes translation of the `columns` argument to `read_json`. Reported in [this Zulip thread](https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/Specifying.20the.20schema.20when.20reading.20JSON.20and.20DLQs).
> fix(duckdb): allow setting `auto_detect` to `False` by fixing translation of columns argument

- ibis/backends/sqlite/__init__.py
- ibis/backends/sqlite/tests/test_client.py
List temporary tables in sqlite by default when `database` is `None`.
> fix(sqlite): list temporary tables by default

- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/datatypes.py
- ibis/backends/sqlite/__init__.py
- ibis/expr/datatypes/tests/test_core.py
- ibis/expr/schema.py
- ibis/util.py
Consolidate code to turn Ibis schemas into sqlglot objects under a `Schema.to_sqlglot` method.
> feat(api): add `to_sqlglot` method to `Schema` objects

- ibis/backends/datafusion/__init__.py
Avoid clobbering and reinitializing memtable data on every execute call.
> refactor(datafusion): avoid reinitializing memtables on every execute call

- ibis/backends/polars/__init__.py
- ibis/backends/polars/compiler.py
Handle memtables the same way in the Polars backend as every other backend, which is to say by storing them as named tables and only storing them if they do not already exist.
> refactor(polars): handle memtables like every other backend

- ibis/backends/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/druid/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/tests/test_client.py
- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/conftest.py
First of ~two~ a few PRs to implement #10044. This one factors out memtable existence checks to allow a generic implementation of register-only-if-not-exists, as well as to allow improvement over time of this check as we discover faster existence check implementations.
> refactor(backends): split memtable existence check out

- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/tests/test_dataframe_interchange.py
These assertion methods give slightly more useful information about the call
> test(backends): use slightly more useful assertions for call count

- ibis/backends/bigquery/__init__.py
- ibis/backends/tests/test_client.py
For now, this just allows the bigquery test to non-strictly xfail.
> test(bigquery): make test non-strict xfail

- ibis/backends/sql/compilers/mssql.py
- ibis/backends/tests/test_string.py
- ibis/backends/tests/test_temporal.py
I noticed that MSSQL was the only backend missing lpad and rpad, so I wanted to add support for these. 
The LPAD operation was a bit tricky. I'm wondering if there might be a more straightforward way, but after several attempts, this seemed to handle all of the cases well.
> feat(mssql): add lpad and rpad ops

- ibis/backends/sql/compilers/mssql.py
Simplifying the previous implementation from `sge.Case(ifs...)` per https://github.com/ibis-project/ibis/pull/10060#discussion_r1752665235.
> refactor(mssql): simplify lpad and rpad ops

- ibis/expr/types/generic.py
- ibis/tests/expr/test_analytics.py
- ibis/tests/expr/test_table.py
- ibis/tests/expr/test_value_exprs.py
This adds a new `name` argument to `topk` & `value_counts`. Fixes #9948.
I think adding a `name` arg to these helpers makes sense. For other builtin aggregate methods you can chain a `.name("myname")` call on the end, but in these cases the return type is a `Table`. Adding an option to specify the name of the new column is nice for ux.
I opted to go for a simple `name: str | None` version, rather than supporting format strings/callables like `rename`. If a user wants to programmatically generate the name then they can do so themselves outside of this method. Keep it simple.
One open question is whether this argument should be keyword only. I went with positional or keyword for now, no strong thoughts.
Also added a docstring example for `topk` while I was at it.
> feat(api): add `name` argument to `topk`/`value_counts`

- ibis/backends/polars/tests/conftest.py
Tackling a couple TODOs to replace the `con.register` and `con._add_table` methods for the Polars tests.
> test(polars): replace register with create_table

- docs/how-to/input-output/duckdb-parquet.qmd
I noticed the link for `read_parquet` on https://ibis-project.org/how-to/input-output/duckdb-parquet was no longer valid. This change repoints to this link to the `read_parquet` method for DuckDB.
> fix(docs): update invalid read_parquet link

- ibis/backends/clickhouse/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/trino/__init__.py
Adds some slightly faster checks for memtable existence. At some point we may want to expand this to non-memtables, but for now these are only implemented for memtables.
> perf(backends): speed up most memtable existence checks

- .github/workflows/ibis-backends.yml
- ibis/backends/clickhouse/__init__.py
- ibis/backends/dask/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/test_connect.py
- ibis/backends/druid/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/pandas/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/trino/__init__.py
- justfile
Run backend doctests in CI during the usual backend test suite.
> ci(backends): run backend doctests in CI

- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/test_register.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_string.py
This reverts commit 1cf54399c94849cf27782b2446efe3c2e31e2467.
The Datafusion temporary table aren't temporary tables in the sense of where they are registered in the `information_schema`, but they are definitely ephemeral.  Also, removing this broke a bunch of stuff that our CI didn't catch (yikes), so reverting while we sort that out.
> revert: fix(datafusion): raise when attempting to create temp table (#10072)

- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends.yml
- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/test_register.py
We were not testing examples in CI because we did not install the `examples` extra. Now we are.
> ci: test examples

- ibis/backends/tests/test_temporal.py
Unxfails some polars timestamp truncation tests that were passing but for the dtype.
> test(polars): unxfail polars timestamp truncation tests by casting the expected result dtype

- docs/_quarto.yml
- docs/backends/support/operations.qmd
Because we include a generated file, this forces developers to render API docs, or delete the file that references the generated file. This PR fixes that by deleting the file using the include, and referencing the included file directly in `_quarto.yml`
> docs: avoid needing to render API docs for any preview/render invocation

- ibis/backends/__init__.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/datafusion/tests/test_register.py
- ibis/backends/duckdb/tests/test_client.py
Replacing a few additional existing "register" methods from the 9.1 deprecation.
> refactor(backends): replace register usage with read

- ibis/backends/conftest.py
- ibis/backends/tests/signature/tests/test_compatible.py
- ibis/backends/tests/signature/typecheck.py
- ibis/backends/tests/test_signatures.py
Opening this in favor of #9383 -- that PR also included all of the breaking changes to unify function signatures and it was too much at once.  This PR adds only the signature checking mechanism, plus the requisite xfails to lay out which inconsistencies are currently in Ibis.
We want to ensure that, for a given backend, that the argument names, plus usage of positional, positional-only, keyword, and keyword-only arguments match, so that there is API consistency when moving between backends.
I've grabbed a few small parts of some of the utilities in Scott Sanderson's
`python-interface` project (https://github.com/ssanderson/python-interface).
While the upstream is no longer maintained, the goal of that project
aligns quite well with some of the issues we face with maintaining
consistent …
> test(sigcheck): check function signature parity across backends

- docs/how-to/timeseries/ffill_bfill_w_window.qmd
* Fix the Quarto Markdown syntax (it looks like it wasn't ported over from the previous syntax)
* Blacken some code
* Provide a more useful (non-self-referential) link to the blog
> docs(how-to): fix the `ffill`/`bfill` how-to guide

- SECURITY.md
Updating the reporting mechanism for security reports -- now there's an email that points to a private Zulip channel.
> docs(security): update security report address to point to private Zulip channel

- CODE_OF_CONDUCT.md
The instructions for reporting CoC violations are out-of-date, as are the
members of the committee to review any violations.
I've updated the page so the email goes to a private Zulip channel with only the
committee members in it, and the names of those members.
> docs(code_of_conduct): update committee members and reporting email

- ibis/backends/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/impala/tests/test_ddl.py
- ibis/backends/impala/tests/test_exprs.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_examples.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_join.py
- ibis/backends/tests/test_set_ops.py
- ibis/expr/types/dataframe_interchange.py
- ibis/expr/types/relations.py
- ibis/selectors.py
- ibis/tests/benchmarks/test_benchmarks.py
- ibis/tests/expr/test_analysis.py
- ibis/tests/expr/test_analytics.py
- ibis/tests/expr/test_relocate.py
- ibis/tests/expr/test_selectors.py
- ibis/tests/expr/test_table.py
This PR changes the `Table.columns` property to return the underlying
`tuple` of names from the operation's `schema` attribute.
Right now, every `.columns` access incurs the overhead of creating a `list`,
which remained for backwards compatibility.
I was refactoring selectors in #9917, and noticed some performance differences
that boiled down to accessing this attribute many times in the case of
selectors operating on very wide tables.
The other approach I considered was t continue returning a `list`, and speed up
the access using `functools.cached_property`.
While this doesn't break the API, it seemed incredibly wasteful to store two
copies of every table's columns, especially in these slower cases where
tables have a ton of columns.
BREAKING CHANGE: `Table.columns` is now a `tuple` …
> perf(dot-columns): speed up heavily used `.columns`

- ibis/backends/sql/compilers/bigquery/__init__.py
> refactor(bigquery): remove unnecessary and misspelled bigquery string find implementation

- ibis/expr/tests/test_newrels.py
- ibis/expr/types/joins.py
A user on Zulip
https://ibis-project.zulipchat.com/#narrow/stream/405265-tech-support/topic/Creating.20a.20new.20column.20from.20a.20numpy.20array.3F/near/470013765
reported an error about a missing `predicate` argument when trying to
chain positional joins.
This allows chaining the join types that don't have
predicates (`positional` and `cross`).
> fix(joins): allow chaining positional and cross joins

- .github/workflows/docs-preview.yml
- .github/workflows/ibis-docs-main.yml
- .github/workflows/ibis-docs-pr.yml
Try to speed up docs build by caching notebooks.
> ci: use jupyter cache in docs ci builds to speed up docs builds

- .github/workflows/ibis-docs-main.yml
- .github/workflows/ibis-docs-pr.yml
Fix reference of the `before` field in the push event payload.
> ci: `before` is a top level field

- ibis/backends/tests/test_interactive.py
- ibis/expr/types/generic.py
There is some deeper work in this area to audit the places where we are doing this and 1) remove it and possibly 2) figure out a way to turn off interactive mode whenever an Ibis exception is raised. Closes #10124.
> fix(repr): remove expression printing from exception message

- ibis/backends/bigquery/tests/system/test_connect.py
Small adjustment to bigquery tests after unifying table exceptions in #9695.
> test(bigquery): check the correct exception for missing tables

- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/flink.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/tests/test_aggregation.py
- ibis/expr/operations/reductions.py
- ibis/expr/tests/test_reductions.py
- ibis/expr/types/generic.py
This adds a new `distinct` option to `collect` (defaulting to `False`). When True, only distinct elements are collected.
Depending on the backend calling `x.collect(distinct=True)` may be more efficient than `x.collect().unique()`, and has the added benefit of not disrupting array ordering for backends where `unique` may not respect ordering.
> feat(api): add `distinct` option to `collect`

- ibis/common/deferred.py
Addresses a warning shown by `quartodoc` about a missing parameter.
> docs(api): avoid quartodoc warning about missing parameter

- ibis/common/dispatch.py
- ibis/common/tests/test_dispatch.py
This was used in the pandas/dask backends, but is no longer used.
> chore: remove unused `Dispatched` utility

- ibis/expr/types/relations.py
Consider this code:
```python
import ibis
t = ibis.table({"x": int})
t[ibis._.x]
```
Before this change, I see a warning such as
```
/Users/nc/code/ibis/ibis/expr/types/relations.py:686: FutureWarning: Selecting/filtering arbitrary expressions in `Table.__getitem__` is deprecated and will be removed in version 10.0. Please use `Table.select` or `Table.filter` instead.
warnings.warn(
```
After this change, the actual offending code is highlighted:
```
/var/folders/0b/tpgpsvx54f9g1gg1lkq45syc0000gp/T/ipykernel_2186/2779650478.py:4: FutureWarning: Selecting/filtering arbitrary expressions in `Table.__getitem__` is deprecated and will be removed in version 10.0. Please use `Table.select` or `Table.filter` instead.
t[_.x]
```
> chore: show deprecation warning at caller level

- .github/workflows/ibis-backends.yml
- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/pyspark/tests/test_client.py
- justfile
- poetry-overrides.nix
If we don't do this, sometimes the jar ends up as `remotecontent` instead of a basename like `iceberg-spark-runtime-3.5_2.12-1.6.1.jar`.
Fixes #10148.
> ci(pyspark): name the output path when downloading jar

- ibis/backends/bigquery/tests/system/test_connect.py
We do this for other bigquery tests, to avoid failures like this: https://github.com/ibis-project/ibis/actions/runs/10921405259/job/30313419648.
> ci(bigquery): avoid race condition in create table by using a dataset scoped to a specific user and python version

- docs/presentations/datafusion-meetup-nyc-2024/talk.qmd
I forgot to add this reference and I wanted to make sure people had access to (more or less) what I typed during the live demo.
> docs(datafusion): add imdb live demo reference to end of presentation

- docs/_quarto.yml
I just noticed that `to_polars` and `to_pyarrow` weren't showing up in
searches, that's because we aren't including methods from the
`_FileIOHandler` mixin in the reference docs.  Now we do.
> docs(table-expr): include inherited methods (all `to_*` methods)

- .github/workflows/algolia/configure-algolia-api.py
We get a list of "missed searched" from Algolia and we can add synonyms
that will point to "better" search terms.  Some times we can't know the
right context for the missed searches, but these two seemed obvious and
the list can grow with time.
Fixes #10084.
> docs(synonyms): add synonym list to redirect searches with no results

- ibis/backends/tests/test_client.py
Apparently today is hit-all-the-create-table-race-conditions day.
> test(bigquery): avoid trying to clobber existing tables by generating a name during create memtable tests

- ibis/expr/datatypes/parse.py
- ibis/expr/datatypes/tests/test_parse.py
> fix(datatype-parsing): ensure that geospatial types are round trippable through the data type parser

- ibis/backends/sql/compilers/mssql.py
- ibis/backends/tests/snapshots/test_sql/test_rewrite_context/mssql/out.sql
- ibis/backends/tests/snapshots/test_sql/test_selects_with_impure_operations_not_merged/mssql-random/out.sql
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_numeric.py
> fix(mssql): ensure `ibis.random()` generates a new value per call

- .github/workflows/docs-preview.yml
- .github/workflows/ibis-docs-main.yml
- .github/workflows/ibis-docs-pr.yml
- docs/tutorials/browser/repl.qmd
- justfile
While we cannot yet upgrade to using python3.12, we can clean up the current jupyterlite build a bit
> chore(docs): clean up current pyodide build

- docs/backends/_utils.py
- ibis/backends/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/conftest.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/exasol/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
- ibis/backends/mysql/__init__.py
- ibis/backends/mysql/tests/test_client.py
- ibis/backends/oracle/__init__.py
- ibis/backends/oracle/tests/test_client.py
- ibis/backends/postgres/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
- ibis/backends/sql/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_signatures.py
- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/test_client.py
BREAKING CHANGE: Removed hierarchical usage of schema. 
Ibis uses the following naming conventions:
- schema: a mapping of column names to datatypes
- database: a collection of tables
- catalog: a collection of databases
> refactor(api): remove schema

- ibis/backends/bigquery/tests/unit/test_datatypes.py
- ibis/backends/sql/datatypes.py
Bigquery supports embedded non-nullable checks inside bigquery schemas, allowing any non-nullable fields in the schema to persist down into bigquery.
Override _from_ibis_Struct for bigquery to allow the adding of a non-nullable field constraint
Resolves #10188, at least for bigquery. There might be opportunities to implement this change in other backends as well.
> feat(bigquery): non-nullable schema support for embedded fields in struct

- .github/labeler.yml
No sense in adding the nix label for all `poetry.lock` updates.
> chore: remove `poetry.lock` from nix label patterns

- ibis/backends/polars/__init__.py
- ibis/backends/polars/tests/test_client.py
Modeled after support for "streaming" kwarg, but I have a couple questions:
1. I don't see any tests for "streaming", so I didn't add any for "engine"; is this fine?
2. I didn't see any attempt to support older Polars versions that didn't accept "streaming", so I didn't try to do that for "engine", either. However, Polars is technically stable now; should we not force people to get latest?
> feat(polars): allow user to specify "engine" kwarg

- ibis/backends/polars/compiler.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_array.py
> fix(polars): use elementwise flatten to flatten nested arrays

- ibis/backends/tests/test_interactive.py
- ibis/expr/types/pretty.py
> fix(api): use `to_pyarrow()` instead of `execute()` when pretty printing scalars

- ibis/backends/snowflake/converter.py
Fixes the failing Snowflake test on `main`.
> fix(snowflake): apply casting logic for json output to scalars

- ibis/expr/api.py
- ibis/expr/types/generic.py
Removes top-level `ibis.where`, the top-level `ibis.geo_*` functions,
`ibis.negate`, and `least` and `greatest` methods on `Value`
Each commit has the (I think) appropriate `BREAKING CHANGE` marker.
> chore(removals): remove a bunch of deprecated stuff

- ibis/formats/pyarrow.py
No reason to construct an entire array just to access the first and only element; pyarrow has APIs for handling scalars.
> refactor(pyarrow-format): avoid constructing unnecessary array to produce a scalar

- .github/workflows/algolia/upload-algolia-api.py
I wrote some hacky stuff a while back to add the various methods to the
Algolia index so that they would show up in search.
This is basically the same thing again, except it grabs the top-level
anchored functions that are generated by `quartodoc` (and which are not
included in the quarto-generated `search.json` file).
I've run this already to populate the index manually, and now functions
like `ibis.get_backend` and `ibis.set_backend` show up in search.
> docs(algolia): also add functions to algolia index

- docs/backends/duckdb.qmd
Noticed the conda/mamba install commands for geopspatial tools was missing ibis-framework
> docs: geospatial install

- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/tests/snapshots/test_sql/test_sample/snowflake-table/block.sql
- ibis/backends/tests/snapshots/test_sql/test_sample/snowflake-table/row.sql
- ibis/backends/tests/test_generic.py
In #10207 an xpassing test for snowflake was introduced. Instead of fixing the test marker, this expands our support for `sample` in snowflake by only compiling it to `TABLESAMPLE` on physical tables. Snowflake's `TABLESAMPLE` does work on subqueries, but only if `method="row"` and `seed=None`. At the physical plan this should be identical to filter with `random`; I don't anticipate a perf difference here (and it's a lot easier to avoid adding a snowflake-specific rule to handle this case).
> fix(snowflake): only compile `sample` to `TABLESAMPLE` on physical tables

- ibis/expr/datatypes/cast.py
- ibis/expr/datatypes/tests/test_cast.py
Before, this would error with a KeyError
> fix(datatypes): give a more useful error message when trying to cast structs with different fields

- ibis/backends/clickhouse/tests/snapshots/test_functions/test_timestamp_truncate/d/out.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_timestamp_truncate/w/out.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_timestamp_truncate/y/out.sql
- ibis/backends/clickhouse/tests/test_functions.py
- ibis/backends/sql/compilers/clickhouse.py
> fix(clickhouse): fix truncating to date from a timestamp

- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/druid.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/exasol.py
- ibis/backends/sql/compilers/flink.py
- ibis/backends/sql/compilers/impala.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/mysql.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/sqlite.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/tests/test_aggregation.py
- ibis/expr/types/generic.py
This standardizes the NULL handling behavior of `argmin`/`argmax` to better match user expectations and the common implementation of the SQL `min_by`/`max_by` methods.
Previously some backends would jump through hoops to avoid returning `NULL` values from these methods, even if the value that minimized the column was `NULL`. We now no longer do this (and workaround the compatibility issues in a few backends that did this by default). Fixes #10193.
> fix(sql): standardize NULL handling of `argmin`/`argmax`

- ibis/backends/tests/test_generic.py
- ibis/expr/api.py
- ibis/expr/operations/udf.py
- ibis/formats/pandas.py
This PR converts scalar numpy objects into their non-numpy Python equivalents for consistent scalar return types for all backends.
BREAKING CHANGE: `execute` now returns non-numpy objects for scalar values.
> chore(backends): convert scalars to non-numpy python objects

- ibis/backends/tests/test_api.py
- ibis/expr/types/core.py
> feat(api): add `get_backend` to expr

- docker/postgres/Dockerfile
- flake.lock
- nix/quarto/default.nix
> chore(deps): bump postgis, nixpkgs, poetry2nix and quarto

- docs/concepts/who.qmd
SuperDuperDB was renamed to Superduper in July 2024.
> docs: superduperdb name change

- ibis/expr/types/core.py
Remove the `has_name` method entirely.
BREAKING CHANGE: `has_name` has always returned `True` since 9.0. It is safe to remove any calls to `has_name`.
> refactor(api): remove `has_name`

- README.md
Removing pandas from the list of backends in the README and adjusting the phrasing around the count. 
I wasn't sure whether to say "15+ backends" or "nearly 20," so I opted for the latter, which was closer to the actual number, 18.
> docs: update README backends

- ibis/formats/polars.py
- ibis/formats/tests/test_polars.py
> fix(polars): handle `pl.Array`

- nix/overlay.nix
> chore(dev-tools): temporarily disable tests on duckdb aarch64 builds

- ibis/backends/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/polars/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/tests/test_client.py
- ibis/backends/trino/__init__.py
Fixes an issue with memtable name reuse where we were never overwriting
memtable data in the backend, even if the data changed and the name remained
the same.
The solution I came up with here was to add a `weakref.WeakSet` to track
memtable ops, which are hashed based on the data-containing object.
The reason a `WeakSet` is necessary is to preserve the drop-on-unreachable
semantics of memtable.
Closes #10131.
> fix(memtables): track memtables with a weakset to allow overwriting tables with the same name but different data

- ibis/backends/tests/test_client.py
Fix failing BigQuery test due to overlapping names across different tests
> test(memtables): use a unique name in each memtable test

- ibis/expr/types/strings.py
Ironically, the word string was misspelled in the docstring of a method in the strings file. 😄 
I opened https://github.com/codespell-project/codespell/pull/3565 so that this may be automatically caught in the future (if approved).
> docs: fix typo in query docstring

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_array.py
Adds the ArrayIndex operation to the Polars backend. 
I also fixed one of the markers for the DataFusion backend as well, it looks like the `array_types` tables gets created in the conftest.
https://github.com/ibis-project/ibis/blob/f817a7ad6ed5ba02afa5e1208896ba8e03439858/ibis/backends/datafusion/tests/conftest.py#L32
> feat(polars): add ArrayIndex operation

- ibis/expr/types/core.py
I noticed that the documentation for the `pipe` method on table expressions was raising the following error: 
`IbisError: Expression contains unbound tables and therefore cannot be executed. Use `<backend>.execute(expr)` to execute against an explicit backend, or rebuild the expression using bound tables instead.`
I rewrote this example to use a memtable instead so that it will render correctly. 
Reference URL: https://ibis-project.org/reference/expression-tables.html#ibis.expr.types.relations.Table.pipe
> docs(api): use memtable for pipe docstring

- ibis/backends/mssql/tests/snapshots/test_window/test_rank_no_window_frame/out.sql
- ibis/backends/mssql/tests/test_window.py
- ibis/backends/sql/compilers/mssql.py
Resolves an error where the RANK window function added a `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING` window frame, which is unsupported by MSSQL. 
> The <rows or range clause/> of the OVER clause cannot be specified for the RANK function. For more information, see [OVER Clause (Transact-SQL)](https://learn.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver16).
Resolves #10291
> fix(mssql): exclude window frame from rank

- docs/backends/_utils.py
- ibis/expr/types/core.py
Fix rendering of docstring sections in backend method docs. Closes #10312.
> docs(render): fix rendering of backend method docstrings

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_array.py
Adds support for ArraySlicing by pushing down `pl.list.slice` methods on the array following the Python style of slicing. 
I wasn't sure if it was best to include an inner function, but it seemed to help avoid a bit of redundancy.
> feat(polars): add ArraySlice operation

- ibis/backends/datafusion/__init__.py
- ibis/backends/datafusion/tests/test_register.py
- ibis/backends/tests/test_signatures.py
Enables `read_csv` from a list of paths in the DataFusion backend
Resolves #9866
> feat(datafusion): enable reading multiple paths in `read_csv`

- ibis/backends/tests/tpc/ds/test_queries.py
Make TPC-DS query 66 not flaky for DataFusion
> test(datafusion): ensure that tpc_66 is not strict for datafusion

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_array.py
Adds ArrayContains support for the Polars backend via [polars.Series.list.contains](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.list.contains.html#).
> feat(polars): add ArrayContains operation

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_array.py
Adds ArrayRemove support for the Polars backend via [polars.Series.list.set_difference](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.list.set_difference.html#).
I didn't `translate` `op.other` this time around, I was having issues when doing that (it wasn't returning anything for some reason). Happy to make any changes if it is necessary to do the `translate` or otherwise adjust.
> feat(polars): add ArrayRemove operation

- flake.lock
Bump nix flakes to pick up the duckdb 1.1.2 CLI.
> chore(deps): bump nix flakes

- ibis/backends/clickhouse/__init__.py
- ibis/backends/clickhouse/tests/test_client.py
- ibis/backends/flink/__init__.py
- ibis/backends/sql/__init__.py
- ibis/backends/tests/test_client.py
A user reported this issue on Zulip.
We weren't passing `catalog.database` information to `get_schema` inside
of `_build_insert_from_table` which caused inserts to fail if user had
specified a `database` argument, because we were looking in the wrong db
for the existing table to pull the `schema` from.
Resolves #10281.
> fix(insert): user can specify insert table in specified database

- flake.nix
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_geospatial.py
Adds an experimental `to_geo` method to the duckdb backend.
Closes #10296.
> feat(api): add `to_geo` methods for writing geospatial output

- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/druid.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/exasol.py
- ibis/backends/sql/compilers/flink.py
- ibis/backends/sql/compilers/impala.py
- ibis/backends/sql/compilers/mssql.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/sqlite.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/tests/test_temporal.py
- ibis/expr/operations/temporal.py
- ibis/expr/types/strings.py
* Adding `as_time` method that converts string to TimeValue based on a formatted. By default converts to timestamps and casts to time
* Implements `parse_time` for BigQuery and `to_date` for Snowflake
* Closes #8908
I find it kinda tricky to setup the tests/dev environment e.g. the docker postgres database always collides with my own local postgres so I have to shut it down in order to run the tests. There are also a lot of errors in the VSCode test discovery, I think its because of the two environments with and without Flink on Mac.
For pyspark I am getting this
```
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
```
For duckdb
```
duckdb.duckdb.IOException: IO Error: No files found that match the …
```
> feat(api): add `StringValue.as_time` for parsing strings into times

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
`dm_exec_describe_first_result_set` can return error codes and error messages.
In order to better handle invalid SQL being passed to `.sql`, we check that the
`err_num` isn't NULL (NULL indicates success (because of course it does)) and
then raise the corresponding error message.
Fixes #10331
> fix(mssql): catch and bubble up exceptions from .sql

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_array.py
Implements ArrayUnion with [pl.Series.list.unique](https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.list.unique.html).
Similar to what I was experiencing when implementing `ArrayUnion`, I'm getting nan/floats when there is a None in the `array<int64>` column. Here is some of the code I was using to test this behavior:
```pycon
In [1]: import polars as pl
...: from ibis.interactive import *
In [2]: d_con = ibis.connect("duckdb://")
...: p_con = ibis.connect("polars://")
In [3]: df = pl.DataFrame({"a": [[1, 3, 3], [], [42, 42], [], [None], None]})
...: t = ibis.memtable(df)
In [4]: expr = t.select("a", uniqued=_.a.unique())
In [5]: d_con.execute(expr)
Out[5]: 
a uniqued
0  [1, 3, 3]  [3, 1]
1         []      []
2   [42, 42]    [42]
3         []      []
4     [None] …
```
> feat(polars): add ArrayDistinct operation

- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/tests/test_array.py
Adds support for the ArrayDistinct operation on the DataFusion backend.
https://datafusion.apache.org/user-guide/expressions.html#array-expressions
I was running into an issue where if a nan was present, the row count being returned was different. It was raising the following:
```
Exception: Internal error: UDF returned a different number of rows than expected. Expected: 6, Got: 5.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
I hope I marked this correctly in the test; this may require an upstream issue.
```pycon
In [1]: from ibis.interactive import *
In [2]: t = ibis.memtable({"a": [[1, 3, 3], [], [42, 42], [], [None], None]})
In [3]: con = ibis.connect("datafusion://")
In [4]: expr = t.select("a", …
```
> feat(datafusion): add ArrayDistinct operation

- docs/backends/support/matrix.qmd
The [operation support matrix](https://ibis-project.org/backends/support/matrix) has links to each operation, but they don’t work. This fixes that by updating the link to the current address of those operations.
- Resolves #10270
> docs: correct link generated in operations matrix

- ibis/backends/duckdb/tests/test_geospatial.py
- ibis/backends/sql/datatypes.py
Ensure compatibility with DuckDB's implementation of geospatial types.
I would love to add tests. Which is the appropriate test file?
In https://github.com/ibis-project/ibis/issues/10324 the temporary table generated the incorrect SQL definition of `GEOMETRY(POINT)` instead of the simple `GEOMETRY`. This ensures that the simple `GEOMETRY` will be used for all geospatial types.
* Resolves #10324
> fix(duckdb): use simple GEOMETRY type for all geospatial data (#10324)

- ibis/expr/types/temporal.py
Adding examples for TimestampValue and DateValue `strftime` methods. 
I wanted to cover what I felt like were common usage patterns.
Resolves #10354 
^^ I intend to keep adding more of these, but don't know it it's worthwhile to keep that issue open.
> docs(examples): add temporal `strftime` examples

- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/flink.py
- ibis/backends/tests/test_numeric.py
Consider `ibis.literal(6) // (1 / ibis.literal(2))`.
Before, this compiled to `6 / 1 / 2 -> 3`, when we really want `6 / (1 / 2) -> 12`.
This fixes that.
Found in https://github.com/NickCrews/mismo/issues/74
> fix(compiler): respect order of ops in FloorDivide

- docs/backends/druid.qmd
Fix the incorrect kwarg in the docs for connecting to Druid
Resolves #10368
> docs(druid): fix connect kwarg example

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_udf.py
The backend-specific kwargs were not forwarded during udf registration. Now they are.
I discovered this when I hit an error just like the test shows.
I also did a little refactoring beforehand, I can remove that commit if you want.
I think a lot of the other backends also suffer from this bug, jusdging by how I don't see their registration hooks using `udf_node.__config__` at all. But this is a tricky thing to test, since the args are backend-specific.
If you can think of a better way to test this I'm open to it, the way I did here seems sort of brittle, dependent on implementation details of duckdb?
> feat(duckdb): forward UDF configuration dict as kwargs during registration

- ibis/expr/types/temporal.py
This adds a temporal example for `day_of_year` to include a demonstration of leap year behavior (365/366).
> docs(examples): add temporal `day_of_year` example

- ibis/backends/clickhouse/tests/snapshots/test_functions/test_translate_math_functions/round/out.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_translate_math_functions/round_0/out.sql
- ibis/backends/clickhouse/tests/snapshots/test_functions/test_translate_math_functions/round_2/out.sql
- ibis/backends/impala/tests/snapshots/test_unary_builtins/test_numeric/round_no_args/out.sql
- ibis/backends/impala/tests/snapshots/test_unary_builtins/test_numeric/round_zero/out.sql
- ibis/backends/sql/compilers/base.py
- ibis/backends/sql/compilers/oracle.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/tests/test_numeric.py
- ibis/expr/operations/numeric.py
- ibis/expr/tests/snapshots/test_format/test_aggregate_arg_names/repr.txt
- ibis/expr/types/numeric.py
- ibis/tests/expr/test_sql_builtins.py
Fixes #10262.
BREAKING CHANGE: `None` is no longer allowed as the `digits` argument to `round`. Use `0` instead. Default behavior is unchanged.
> fix(api): ensure consistent typing in `round` output type

- ibis/expr/api.py
Adds an example showing what the output of `ibis. interval` looks like, adding and subtracting ten days from a timestamp and gets a bit more granular with a defined interval. 
I feel like it's particularly important to have an example for `interval` because I often find myself trying to figure out how to express the equivalent of the SQL `DATEADD` operation.
> docs(examples): add temporal interval examples

- docs/tutorials/ibis-for-sql-users.qmd
Expanding upon the `UNION` and `UNION ALL` examples in [Tutorial: Ibis for SQL users](https://ibis-project.org/tutorials/ibis-for-sql-users)
to include coverage for `INTERSECT` and `EXCEPT`.
Many dataframe APIs do this differently (e.g., [snowflake.snowpark.DataFrame.minus](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/1.23.0/snowpark/api/snowflake.snowpark.DataFrame.minus),
[pyspark.sql.DataFrame.exceptAll](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.exceptAll.html#)), so I'm hoping this will help clarify things for how to perform these ops in Ibis for SQL users.
> docs: expand ibis-for-sql-users set operator examples

- ibis/expr/types/temporal.py
Add examples for the remaining non-TimeValue-only temporal operations. This time, I opted not to use memtable examples and used the scalar options to demonstrate functionality. 
There's a lot here, so I broke them into separate commits if we wanted to pluck any out that seemed self-explanatory. Admittedly, many of these did feel self-explanatory, but I didn't know if it was still better to have examples for all of them for completeness. I am okay with squashing all of these commits if we want to proceed with these examples if that is better. 
I also used `ibis.date` and `ibis.timestamp` rather than `datetime.date` or `datetime.datetime`. It might be worth standardizing all these examples to use one or the other, but I figured we could discuss that or pick it up in a different PR.
> docs(examples): add remaining non-TimeValue temporal examples

- ibis/expr/types/strings.py
I am never sure if the pattern needs to match the ENTIRE string, or only part of it. This makes that clear.
> docs(api): indicate that `re_search` need only match part of a string

- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/tests/test_temporal.py
- **fix(snowflake): adjust `array_contains` invocations for use of `dialect` in `sg.func`**
- **test(snowflake): enable xpassing test**
- **fix(bigquery): ensure that delta function `part` argument is not compiled as a string**
> fix(snowflake, bigquery): minor adjustments for passsing in `dialect` to `sg.func`

- ibis/backends/sql/compilers/flink.py
- ibis/backends/tests/test_numeric.py
I can file an issue to track the actual flink fix for this if you want.
> test: add test that `/` performs true division, not floor division

- ibis/expr/types/numeric.py
Adds examples for using `bit_and`, `bit_or`, and `bit_xor` to add more example coverage on [Numeric and Boolean expressions](https://ibis-project.org/reference/expression-numeric).
I demonstrated the `where` usage here because I think it's super convenient for working with these aggregate functions.
> docs(examples): add IntegerColumn bitwise aggregegate examples

- ibis/expr/types/numeric.py
Examples for `as_interval` and `as_timestamp` for more coverage on [Numeric and Boolean expressions](https://ibis-project.org/reference/expression-numeric).
> docs(examples): add `as_timestamp` and `as_interval` IntegerValue examples

- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/tests/test_array.py
If I do something like `some_really_complex_array_expression.unique()`, then the SQL for `some_really_complex_array_expression` was duplicated 4 times. Now it is only duplicated 3 times.
This is important for perf, because duckdb sometimes appears to not be smart, and actually does a computation for each time a subexpression appears.
See https://github.com/duckdb/duckdb/discussions/14649.
So this can reduce the computation time to 3/4 of what it was.
I want to go through our other compilation steps and do similar optimizations whenever possible.
> perf(duckdb): reduce branching factor for generated ArrayDistinct code

- ibis/backends/sql/compilers/duckdb.py
- poetry.lock
- pyproject.toml
Similar rationale to https://github.com/ibis-project/ibis/pull/10410
> perf(duckdb): use builtin negative array slicing in newer duckdbs

- ibis/expr/types/generic.py
Adds a few examples given different data types and the the output of `column.type`. I wanted to include the timestamp here since it shows the output class of that type with more than nullable. 
Here's a doc preview:
> docs(examples): add type example

- ibis/selectors.py
This adds examples for the remaining selectors except `s.none()`. I need to brainstorm for a good example of that one, unless anyone has ideas off the bat.
Selectors may still be my favorite Ibis feature, so I am happy to provide direct examples for using them. 😎
> docs(examples): add remaining selectors examples

- .github/workflows/ibis-backends-cloud.yml
Testing tends to be much more helpful when it is actually enabled.
> ci(databricks): enable databricks ci job

- ibis/backends/sql/compilers/base.py
Fixes an issue with sqlglot backwards compatibility, where we were somehow catching AttributeError instead of ImportError.
> fix(compiler): use the correct exception type for a failed import

- ibis/expr/types/generic.py
Adds examples for `count`, `percent_rank`, `cume_dist`, and `ntile`. This tackles more of the examples on the [Generic expressions](https://ibis-project.org/reference/expression-generic) page.
> docs(examples): `count`, `percent_rank`, `cume_dist`, `ntile` example usage

- ci/schema/databricks.sql
- ibis/backends/databricks/__init__.py
- ibis/backends/databricks/tests/conftest.py
This PR moves the test volume in Databricks to be tied to the user and python version with which the volume is being created. Additionally, this PR does something similar for the memtable volume to avoid a similar problem with concurrent modification of memtable files.
> feat(databricks): isolate volume creation

- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/duckdb.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/tests/test_array.py
- ibis/expr/types/arrays.py
Fixes a bug in NULL handling of our DuckDB implementation of `ops.ArrayConcat`. Previously NULL concatted with non-null returned the non-null value. This PR changes the behavior to return NULL if any of the lists being concatenated are null.
> fix(duckdb): handle null propagation correctly in array concatenation

- ibis/backends/clickhouse/tests/test_client.py
- ibis/backends/impala/tests/test_client.py
- ibis/backends/postgres/tests/test_functions.py
- ibis/backends/tests/test_interactive.py
- ibis/config.py
Removes code for contextually setting options that is only used in testing.
BREAKING CHANGE: `option_context` is removed. Use `contextlib.contextmanager` to create your own version of this functionality if necessary.
> refactor(config): remove `option_context`

- ibis/backends/duckdb/__init__.py
In DuckDB this has been fixed in
https://github.com/duckdb/duckdb/pull/6840#issuecomment-1481387587. This PR is to remove the warning about DuckDB size restriction.
Would it be welcome for me to add tests for use of `chunk_size` with DuckDB `to_pyarrow_batches`?
Resolves #10443
> docs(duckdb): remove warning of duckdb not supporting chunk_size param

- ibis/expr/types/groupby.py
This adds a [`having`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.groupby.GroupedTable.having) example for usage on a `GroupedTable`. I followed it up with an `aggregation` to show the removal of the "a" rows. 
It could be useful also to show the `having` method without aggregation results in a `GroupedTable,` but I wasn't 100% sure if that would be worth showing.
> docs(examples): add `having` example for GroupedTable

- docs/reference/cursed_knowledge.qmd
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/sql/datatypes.py
Postgres has a wacky unsigned integer dtype called `OID` that's only used internally.  It's technically a 4-byte UINT, but I'm mapping it to a signed int64 because that's accurate enough to capture the valid values.
Resolves #10456
> fix(postgres): add dtype mapping for postgres OID type

- ibis/expr/types/core.py
- ibis/expr/types/relations.py
Adds examples by creating a table using an in-memory duckdb connection for [`get_backend`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.get_backend) and [`get_name`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.get_name). 
I did `backend.name` to get "duckdb" in the example for `get_backend` rather than `backend` to avoid getting something like "<ibis.backends.duckdb.Backend at 0x7fffd919b470>".  I'm not sure if both that and the `type` usage are necessary; maybe we could use one or the other if we don't want to use both.
> docs(examples): add usage examples for `get_backend` and `get_name`

- ibis/expr/types/core.py
Adds an example demonstrating that given a table in both DuckDB and Polars, we can take the table from DuckDB, unbind it, and then execute it using the Polars backend.
> docs(examples): add unbind example

- ibis/backends/sql/compilers/duckdb.py
I want these changes to eventually make it in
> chore: add todos on switching to newer duckdb list_concat() syntax

- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/trino.py
- **style(trino): dedent**
- **fix(snowflake): make semantics of array filtering match everything else**
Fixes snowflake failures on `main`, caused by slightly different behavior around `NULL`s used in array filtering.
This PR ensures that behavior is the same for all backends that support array
filtering with an index.
Snowflake is a bit more complex because its higher order functions only accept
a single argument, so before we compile we run a rewrite rule (the use of
a rewrite is **not** new in this PR) to extract the field being referenced in
the body of the function.
The changes here are only relevant for the case of array filtering with an
index. If an index isn't used, then the behavior is the same as before.
This changes here are effectively making the snowflake backend implement …
> fix(snowflake): make semantics of array filtering match everything else

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_register.py
Let's make the pass-through from ibis to duckdb more transparent, so you get closer to the same behavior as when using `import duckdb; duckdb.connect()`.
I considered also removing the nicety of creating the temp_dir for users, but decided to keep it.
Now, we only create parent. duckdb will make dir itself only if it needs. This means that for low-memory loads,
a dir might never be needed. This better matches duckdb's behavior.
Also, adjust our test to really check for the end desired behavior, not an implementation detail
of if WE create the dir.
Related to https://github.com/ibis-project/ibis/issues/6974
BREAKING CHANGE: Special handling of the `temp_directory` argument passed to Ibis is removed in favor of passing the argument through directly to `duckdb.connect`. Interior nodes of …
> refactor(duckdb): pass `temp_directory` through as-is to `duckdb.connect`

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
I found the error 
```
'IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)'
```
Because the password of mssql includes special characters like `{R;3G1/8Al2AniRye` that start with `{` or include `;`.
It should be covered by `{` and `}` and replace `}` with`}}`.
Reference:
https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-databases
https://stackoverflow.com/questions/78531086/pyodbc-connection-string-correctly-escaping-password-with-special-characters/78532507#78532507
> fix(mssql): escape special characters in passwords

- ibis/backends/tests/test_generic.py
Fixes the recently added multi-decimal-column-describe test to work with bigquery, which only supports precision 38 and precision 76.
> test(bigquery): xfail bigquery when testing decimal column describe due to limited decimal type support

- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_generic.py
- ibis/expr/api.py
~Two changes here:~
- ~Support `__arrow_c_schema__` in `ibis.Schema` objects~
- Support objects implementing `__arrow_c_stream__` as inputs to `ibis.memtable`
Fixes #9660.
> feat(pyarrow): support arrow PyCapsule interface in more places

- ibis/backends/tests/test_generic.py
> test(flink): disable pyarrow c stream test

- ibis/backends/bigquery/converter.py
- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_binary/difference/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_binary/intersection/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_binary/union/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_point/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_simplify/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/buffer/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/centroid/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/end_point/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/point_n/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary/start_point/out.sql
- ibis/backends/bigquery/tests/unit/snapshots/test_compiler/test_geospatial_unary_union/out.sql
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/expr/types/pretty.py
Fixes some issues discovered while attempting to address https://github.com/ibis-project/ibis/discussions/10209. Will expand with more detail later today.
> fix(geometry): make output handling robust to text or bytes

- ibis/backends/tests/test_generic.py
- ibis/expr/api.py
Passing a `geopandas.GeoDataFrame` directly to `memtable` will yield a bunch of
errors because our various `to_arrow` and other proxy methods don't know how to
handle the bundled geo data.
As an intermediate bit of functionality until things like `geoarrow` are more
widely supported, this PR adds an extra dispatch to the `memtable` constructor
to cast geometry columns to WKB, which allows most backends to ingest the
resulting data with the geo columns as binary, which can then be cast to
`geometry` columns in backends that support that.
Resolves #10453
> feat(geospatial): accept geopandas GDFs in `memtable`

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
In MSSQL, if the column name is non-ASCII, it will be a question mark when getting schema by `sys.dm_exec_describe_first_result_set`
```python
con = ibis.mssql.connect(...)
expr = con.sql("SELECT 1 AS [калона]")
schema = expr.schema()
names = schema.names
assert len(names) == 1
assert names[0] == "калона"
```
```
E    AssertionError: assert '??????' == 'калона'     
E    - калона
E    + ??????
```
We should make the sql string be a `nvarchar` for Unicode.
> fix(mssql): use nvarchar to avoid non ascii be question mark

- ibis/backends/duckdb/tests/test_client.py
Added test to finish off https://github.com/ibis-project/ibis/pull/10445
> test(duckdb): add test for chunk_size param in to_pyarrow_batches

- ibis/backends/tests/test_numeric.py
Fixes upstream cloud test failures.
> test(snowflake,bigquery,databricks): xfail test for pyarrow decimal memtable construction with ints

- ibis/expr/types/numeric.py
Adds examples for [std](https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericColumn.std), [var](https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericColumn.var), [corr](https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericColumn.corr), and [cov](https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericColumn.cov) to finish off [NumericColumn](https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericColumn) method example coverage.
I used "pop" with correlation as DuckDB only implements `pop` correlation coefficient.
> docs(examples): add `std`, `var`, `corr`, and `cov` usage examples

- ibis/expr/api.py
Adds a docstring example for [ibis.get_backend()](https://ibis-project.org/reference/connection.html#ibis.get_backend), fixes parameter block, and links to the `Table.get_backend()`.
> docs(examples): add ibis.get_backend examples

- ibis/expr/types/generic.py
Adds the section header for the examples for [null](https://ibis-project.org/reference/expression-generic#ibis.null). 
I added the expected failure annotation, but the `# quartodoc: +EXPECTED_FAILURE` comment still shows up in the render. 
I wasn't sure if there was something special I needed to do for it not to show up, like how this is here but the # doesn't show up in the [pivot_longer examples](https://ibis-project.org/reference/expression-tables.html#examples-28). 
https://github.com/ibis-project/ibis/blob/4d9901897fbcb4a480bafda3f98d85a9a32f9ed6/ibis/expr/types/relations.py#L3807-L3811
> fix(docs): add null examples header and expected failure

- ibis/expr/types/core.py
This makes the example more concise and similar to the `ibis.get_backend()` example. That `# doctest: +ELLIPSIS` usage comes in handy. 
Adds the "See Also" to link to the other `ibis.get_backend` method.
> docs(examples): align Table.get_backend with ibis.get_backend examples

- .gitattributes
- .gitignore
- ibis/backends/tests/test_export.py
- ibis/expr/types/generic.py
Implement `Column.to_list()` convenience method to avoid having to do `Column.to_pyarrow().to_pylist()` manually.
* Resolves #10102
> feat(export): implement the `Column.to_list()` API

- ibis/expr/types/relations.py
While reviewing the remaining table expression methods that needed examples, I noticed that [`to_array`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.to_array) did not include the deprecation docstring. The added deprecation note is similar to that of [`dropna`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.dropna) and [`relabel`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.relabel).
> docs(api): deprecate `to_array` in favor of `as_scalar` in docstring

- ibis/expr/types/relations.py
Sets up a scenario for an example of using [`asof_join`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.asof_join) using weather data, including sensor data collection and various weather events.
> docs(examples): add `asof_join` weather example

- pyproject.toml
`target-version` is duplicative/unnecessarily-overriding `requires-python`; see https://docs.astral.sh/ruff/settings/#target-version.
> build(ruff): remove unnecessary target-version use

- ibis/backends/pyspark/__init__.py
Small little improvement I found while doing something else
> chore(pyspark): use normalize_filenames() from util

- ibis/expr/sql.py
- ibis/expr/types/core.py
Adds Examples section and See Also reference for [`Table.compile()`](https://ibis-project.org/reference/expression-tables.html#ibis.expr.types.relations.Table.compile) and [`ibis.to_sql()`](https://ibis-project.org/reference/expression-generic.html#ibis.to_sql)
Adds return type information for `Table.compile()`. 
There might be an opportunity to improve the wording of `to_sql` regarding the usage of the word "formatted - I will add suggestion if we think this is something we want to do.
> docs(examples): add example and see also ref for `compile` and `ibis.to_sql`

- ibis/expr/types/core.py
Adds examples of [`Table.execute()`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.execute) usage and references [`Table.to_pandas`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.to_pandas) and [`Value.to_pandas`](https://ibis-project.org/reference/expression-generic#ibis.expr.types.generic.Value.to_pandas) for "See Also". 
It might be worthwhile to "See Also" `backend.execute`, but I wasn't sure how to create the link there as it seems to correspond to respective backends. 
(e.g., https://ibis-project.org/backends/duckdb#ibis.backends.duckdb.Backend.execute)
> docs(examples): add example and see also ref for Table.execute

- README.md
- docs/how-to/extending/unbound_expression.qmd
- docs/index.qmd
- docs/why.qmd
Back in https://github.com/ibis-project/ibis/pull/10259, I adjusted the messaging around the backend count in the README to represent the changes after removing the pandas and Dask backends. This PR applies this fix in more locations. I did not adjust any presentations or previous blog posts, as the count was correct then.
> docs: reword backend counting to nearly 20 from 20+

- .github/workflows/nix-skip-helper.yml
Adding one more entry to the nix skip helper so we aren't waiting forever for a job that will never run
> chore(ci): skip nixos on mac-14, python3.12 for docs only prs

- ibis/backends/tests/test_string.py
I'm cherry-picking some of the changes that I have in https://github.com/ibis-project/ibis/pull/9473/ that are still useful without the rest of that PR.
> test: use more precise marker for backends that don't support arrays

- ibis/backends/sql/rewrites.py
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/bigquery/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/clickhouse/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/databricks/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/datafusion/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/druid/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/duckdb/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/exasol/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/flink/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/impala/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/mssql/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/mysql/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/oracle/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/postgres/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/pyspark/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/risingwave/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/snowflake/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/sqlite/out.sql
- ibis/backends/tests/snapshots/test_sql/test_order_by_no_deference_literals/trino/out.sql
- ibis/backends/tests/test_sql.py
Remove literals in `ORDER BY` when sorting tables. Fixes #10428.
> fix(sql): remove constants in `order_by` calls during select merging

- docs/backends/impala.qmd
Followup to #9840 -- updates the Impala backend docs to remove references to the (now removed) table methods.
> docs(impala): remove table methods from backend docs

- docs/backends/_utils.py
Fixes the way we render docstrings in the docs so that we show the argument
names, and keyword defaults, as they should be entered, and not as a list of
strings.
Fixes #10558
> fix(docs): render func args as args, not list of args

- docs/posts/classification-metrics-on-the-backend/index.qmd
I accidentally left two precision score prints, one of which was the recall score.
> docs(blog): fix metric print output in classification blog

- .github/workflows/nix-skip-helper.yml
This PR should allow jobs to complete again.
> ci(nix): make skip helper python version match the non-skipped job

- ibis/backends/polars/__init__.py
- ibis/backends/tests/test_signatures.py
Accept `database` in the `PolarsBackend.table()`, but error if it's not `None`.
Also, do a bit of standardization.
* Resolves https://ibis-project.zulipchat.com/#narrow/channel/405263-general/topic/Are.20there.20any.20restrictions.20around.20.60Backend.2Etable.60.20signature.3F/near/486191725
> chore(polars): add `database` arg, for consistency

- ibis/expr/api.py
- ibis/expr/types/relations.py
Adds documentation examples to demonstrate `rest` and `distinct` usage for [`Table.intersect`](https://ibis-project.org/reference/expression-tables#ibis.expr.types.relations.Table.intersect) and [`ibis.intersect`](https://ibis-project.org/reference/expression-tables#ibis.intersect).
I don't think I realized until today that `intersect`, `union`, and `difference` can handle more than two table expressions at once. This is super convenient. I can add `rest` examples for the other two soon.
I'm not sure about putting together a `distinct` example for `difference` and `union` already has one.
> docs(examples): add distinct and rest arg examples for `ibis.intersect` and `Table.intersect`

- .devcontainer/Dockerfile
- docs/contribute/01_environment.qmd
Update devcontainer through build (.devcontainer/Dockerfile) to name the virtual environment using the default uv virtual environment name ('venv') and activate it.
Resolves #10575
> fix(deps): enable running uv lock command in devcontainer

- docs/contribute/01_environment.qmd
- nix/quarto/default.nix
Bump quarto the latest version.
> chore(deps): bump quarto version

- .devcontainer/Dockerfile
- docs/contribute/01_environment.qmd
Bump the devcontainer python version to 3.13 and update dev env matrices for accuracy
> docs(development): update dev env matrices for accuracy

- .github/workflows/check-generated-files.yml
- .github/workflows/ibis-backends-cloud.yml
- .github/workflows/ibis-backends.yml
- .github/workflows/ibis-main.yml
- .github/workflows/pre-release.yml
- flake.lock
- ibis/backends/sql/compilers/bigquery/udf/core.py
- ibis/backends/sql/compilers/bigquery/udf/rewrite.py
- requirements-dev.txt
- uv.lock
Bumps most usage of 3.12 to 3.13
> chore(deps): bump 3.12 usage to 3.13

- ibis/backends/duckdb/tests/test_io.py
- ibis/backends/sqlite/tests/test_types.py
Observed in the wild here: https://github.com/ibis-project/ibis/actions/runs/12373195788/job/34533064464?pr=10589
> test(sqlite): use context managers for sqlite connections to avoid `ResourceWarning` in python 3.13

- ibis/backends/impala/tests/test_bucket_histogram.py
- ibis/backends/postgres/tests/test_functions.py
- ibis/backends/risingwave/tests/test_functions.py
- ibis/expr/types/numeric.py
Closes #9612.
BREAKING CHANGE: `IntegerValue.label` is redundant with the `IntegerValue.cases` method, use that instead. Replace `expr.label(labels)` with `expr.cases(*enumerate(labels))`
> refactor(api): remove `IntegerValue.label`

- .releaserc.js
- flake.nix
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_io.py
- ibis/expr/types/generic.py
- ibis/expr/types/strings.py
- ibis/tests/expr/test_value_exprs.py
Remove remaining 10.0 deprecations and re-enable deprecation checks in CI. Closes #10110.
> refactor(api): re-enable deprecation checks

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/duckdb/tests/test_io.py
- ibis/backends/sqlite/tests/test_client.py
- ibis/backends/sqlite/tests/test_types.py
Continued to observe this, so I took a closer look and it turns out that the context manager does not close the connection, it only handles transaction behavior. This PR fixes the resource warnings that show up only in Python 3.13
> test(sqlite): fix test flakiness caused by failing to close `sqlite3.Connection` objects

- compose.yaml
- docker/postgres/Dockerfile
Fixes the failing build of pgvector discovered here: https://github.com/ibis-project/ibis/actions/runs/12497126794/job/34884330638?pr=10613
> chore(dev-deps): bump pgvector, clang and llvm versions

- .github/renovate.json
Would like to bring this back in order to see what is currently outdated.
> chore: re-enable the dependency dashboard

- ibis/backends/duckdb/__init__.py
- ibis/expr/api.py
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
fixes https://github.com/ibis-project/ibis/issues/10535
Other things I considered:
like https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded
but I don't think our doc system uses sphinx. So I think we are limited to using quarto's constructs?
[There is warning, tip, etc](https://quarto.org/docs/authoring/callouts.html#callout-types). I thought note made the most sense.
Similar to the `@experimental` and `@deprecated` decorators in util.py. But I thought adding them inline like this wasn't that hard.
eg further up, where it might be more obvious. [But the official python docs put them down at the bottom](https://docs.python.org/3/library/enum.html#enum.Enum.__format__), so I chose to follow that convention. I think that future-proofs us if …
> docs: add callout notes for some APIs changes and additions

- ibis/expr/api.py
- ibis/expr/tests/test_api.py
Before this change, if you pass a `SchemaLike` that isn't actually a `Schema`, it won't automatically rename the auto-generated pandas column names. For example:
```python
import pandas as pd
df = pd.DataFrame([[1, 2], [3, 4]])
schema = {"a": "int64", "b": "int64"}
t = ibis.memtable(df, schema=schema)
t.a.execute()  # Raises a KeyError
```
This PR goes ahead and constructs the `Schema`, if passed—work that was going to be done anyway. That way, `getattr(schema, "names")` finds the passed names, and the rename is performed.
> fix(api): ensure memtable schema and columns match

- .github/workflows/ci-data.yml
- .github/workflows/ibis-benchmarks.yml
Set the correct permissions for generating a request token for accessing google cloud.
> ci: fix google cloud wif token permissions

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_string.py
Adds the [`StringFind`](https://ibis-project.org/reference/operations#ibis.expr.operations.strings.StringFind) operation for the Polars backend using [`pl.Expr.str.find`](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.find.html#).
> feat(polars): add `StringFind` operation

- .github/workflows/docs-preview.yml
- .github/workflows/ibis-docs-main.yml
- .github/workflows/ibis-docs-pr.yml
- flake.lock
- flake.nix
- nix/overlay.nix
- requirements-dev.txt
- uv.lock
Bump nix flakes and move uv derivation to vendored version from uv2nix to track updates to uv at a faster pace.
> chore(deps): move `uv` in nix environment to vendored version from `uv2nix`

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_set_ops.py
Adds support for [`Intersection`](https://ibis-project.org/reference/operations.html#ibis.expr.operations.relations.Intersection) and [`Difference`](https://ibis-project.org/reference/operations.html#ibis.expr.operations.relations.Difference) operations for the Polars backend. The approach uses pl.SQLContext to register the dataframes and query using [INTERSECT](https://docs.pola.rs/api/python/stable/reference/sql/set_operations.html#intersect) and [EXCEPT](https://docs.pola.rs/api/python/stable/reference/sql/set_operations.html#except), respectively. 
I saw that a few other functions used a `ctx` argument which might be using `pl.SQLContext` in a similar manner, I wasn't sure if that argument could be used here to avoid some of the boilerplate. Here are some of those functions I am …
> feat(polars): add `Intersection` and `Difference` ops

- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_parse.py
Noted in #10243, passing `nullable` to `ibis.dtype` when using a string name for
the dtype leads to an unhelpful error.  Instead, we should just support this.
This adds support for 'primitive' dtype specifications -- there's no defined
behavior for how to specify nested nullable types with a single keyword
argument, but this should cover most cases.
xref #10243 but doesn't close it
> feat(dtypes): allow passing `nullable` kwarg to string parsed dtypes

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_aggregation.py
Add support for [`bit_and`], [`bit_or`], and [`bit_xor`] for the Polars backend. This uses [`bitwise_and`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bitwise_and.html#), [`bitwise_or`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bitwise_or.html#), and [`bitwise_xor`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bitwise_xor.html#) Polars expression methods. 
The `is_in` tests are failing still:
FAILED ibis/backends/tests/test_aggregation.py::test_reduction_ops[polars-is_in-bit_xor] - AssertionError: 
FAILED ibis/backends/tests/test_aggregation.py::test_reduction_ops[polars-is_in-bit_and] - AssertionError: 
FAILED ibis/backends/tests/test_aggregation.py::test_reduction_ops[polars-is_in-bit_or] - …
> feat(polars): add bitwise operations (`bit_and`, `bit_or`, `bit_xor`)

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_temporal.py
Adds [`ops.TimeFromHMS`](https://ibis-project.org/reference/operations#ibis.expr.operations.temporal.TimeFromHMS) support for the Polars backend using [`pl.time`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.time.html).
I tried adding this to the `_date_methods` and even `_binops` dictionaries, but it
wasn't taking, so I split out a new function.
> feat(polars): add `TimeFromHMS` op

- ibis/backends/polars/compiler.py
- ibis/backends/tests/test_string.py
Adds support for the [`ArrayStringJoin`](https://ibis-project.org/reference/operations#ibis.expr.operations.strings.ArrayStringJoin) operation for the Polars backend. 
I tried my initial implementation using [`polars.Expr.str.join`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.str.join.html#), but it seemed it needed [`polars.Expr.list.join`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.list.join.html#) instead.
> feat(polars): add ArrayStringJoin op

- ibis/backends/tests/test_generic.py
> test(druid): xfail because druid cannot sort by anything but timestamps

- ibis/backends/risingwave/__init__.py
Decouple the risingwave backend from the postgres backend to allow use of `psycopg` (not `psycopg2`) with the postgres backend in #10659.
> refactor(risingwave): decouple the risingwave backend from the postgres backend

- docs/_tabsets/repl_warning.qmd
- docs/tutorials/browser/repl.qmd
- flake.lock
Removes now-unnecessary pip installs of some dependencies, since `%pip install ibis-framework[duckdb]` "just works" now thanks to the hard work of many people.
> chore(docs): simply pip install ibis-framework instead of pre-installing a bunch of requirements

- ibis/backends/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
- ibis/expr/types/core.py
Fixes https://github.com/ibis-project/ibis/issues/10413
I didn't bother adding this to any of the other backends. There is no handy pyarrow.to_json() function that can save the day here. I think we would need to to backend-specific implementations.
Open todos that could come later, but I don't think should be blocking for this PR:
- Consider taking some of the [duckdb-specific config options](https://duckdb.org/docs/sql/statements/copy.html#json-options), and hoisting them to be "official" options across all backends. I could see a `format=Literal["array", "jsonl"] = "array"` being the most likely choice, but not needed until we survey the other backends.
- For dates/datetimes/decimals, where there is no corresponding JSON type, we need to decide what to do.
- Once we decide, implement …
> feat(duckdb): add to_json() to Table and duckdb backend

- ibis/backends/clickhouse/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/converter.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/exasol/__init__.py
- ibis/backends/flink/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_export.py
- ibis/backends/tests/test_numeric.py
- ibis/backends/trino/__init__.py
- ibis/expr/schema.py
- ibis/expr/tests/test_schema.py
- ibis/formats/pyarrow.py
Address all-NULL column handling in the DuckDB backend. `null` pyarrow Arrays are returned (previously int32), and it is now an error on the Ibis side to create all null columns with `create_table` in the DuckDB backend. Fixes #9669.
> fix(duckdb): return null typed pyarrow arrays and disable creating tables with all null columns in duckdb

- ibis/backends/clickhouse/tests/conftest.py
- ibis/backends/conftest.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/duckdb/tests/conftest.py
- ibis/backends/mssql/tests/conftest.py
- ibis/backends/mysql/tests/conftest.py
- ibis/backends/oracle/tests/conftest.py
- ibis/backends/polars/tests/conftest.py
- ibis/backends/postgres/tests/conftest.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/risingwave/tests/conftest.py
- ibis/backends/snowflake/tests/conftest.py
- ibis/backends/sqlite/tests/conftest.py
- ibis/backends/tests/base.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_struct.py
- ibis/backends/trino/tests/conftest.py
Clean up test sessions using disconnect, to avoid leaking resources, and resource warnings
> test(fixtures): ensure that most connections are cleaned up when the session ends

- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/rewrites.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_impure.py
- ibis/expr/decompile.py
- ibis/expr/operations/generic.py
- ibis/expr/operations/udf.py
Related to https://github.com/ibis-project/ibis/issues/8921,
trying to write down exactly what the expected behavior is.
I figure we can use this PR to hash out exaclty what we want the semantics to be, and then the other discussions might be easier because our goal is written down precisely somewhere. Please let me know if you agree or disagree with this behavior, or if there are other tests we should add.
Need to fix the UDF test case in a followup. Also wasn't sure where to put these tests, I put them in their own little file but if you point me elsewhere Iwill move them.
> test: add test for impure function correlation behavior

- ibis/backends/clickhouse/tests/conftest.py
- ibis/backends/conftest.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/duckdb/tests/conftest.py
- ibis/backends/mssql/tests/conftest.py
- ibis/backends/mysql/tests/conftest.py
- ibis/backends/oracle/tests/conftest.py
- ibis/backends/polars/tests/conftest.py
- ibis/backends/postgres/tests/conftest.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/risingwave/tests/conftest.py
- ibis/backends/snowflake/tests/conftest.py
- ibis/backends/sqlite/tests/conftest.py
- ibis/backends/tests/base.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_struct.py
- ibis/backends/trino/tests/conftest.py
This was apparently more trouble than it was worth.
> revert: test(fixtures): ensure that most connections are cleaned up when the session ends (#10693)

- ibis/formats/pandas.py
Fixes upstream snowflake test that was not properly converting pandas Timestamps using its preferred `tz_*` methods
> fix(snowflake): ensure that timestamps are properly timezoned

- ibis/backends/clickhouse/tests/test_datatypes.py
- ibis/backends/duckdb/tests/test_datatypes.py
- ibis/backends/duckdb/tests/test_udf.py
- ibis/backends/sql/datatypes.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/parse.py
- ibis/expr/datatypes/tests/test_core.py
- ibis/tests/strategies.py
Add `length` field to `Array` datatypes to support fixed-length arrays.
Closes #10719.
> feat(datatypes): add support for fixed length arrays

- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_functions.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/risingwave/converter.py
> fix(postgres): fix insertion of `NaT`/`None` into timestamp columns

- ibis/backends/athena/__init__.py
- ibis/backends/tests/errors.py
- ibis/backends/tests/test_client.py
> fix(athena): implement proper support for inserting data

- ibis/backends/athena/tests/conftest.py
- ibis/backends/clickhouse/tests/conftest.py
- ibis/backends/conftest.py
- ibis/backends/datafusion/tests/conftest.py
- ibis/backends/duckdb/tests/conftest.py
- ibis/backends/flink/tests/conftest.py
- ibis/backends/impala/tests/conftest.py
- ibis/backends/mssql/tests/conftest.py
- ibis/backends/mysql/tests/conftest.py
- ibis/backends/oracle/tests/conftest.py
- ibis/backends/polars/tests/conftest.py
- ibis/backends/postgres/tests/conftest.py
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/risingwave/tests/conftest.py
- ibis/backends/snowflake/tests/conftest.py
- ibis/backends/sqlite/tests/conftest.py
- ibis/backends/tests/base.py
- ibis/backends/trino/tests/conftest.py
Redo of a previous PR to clean up connection resources in testing, hopefully as a way to avoid hanging in the postgres backend.
> test: clean up connections

- flake.lock
- nix/quarto/default.nix
- requirements-dev.txt
- uv.lock
> chore(deps): bump to latest quarto and also bump other deps and regen lockfiles

- ibis/expr/visualize.py
Make sure the last lines of multi-line labels are left-justified (not centered) by adding a trailing left-aligned break.
Solution: https://stackoverflow.com/q/49568399
> fix(graphviz): ensure all lines are left-justified

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_ddl.py
We were using the wrong keyword in `sqlglot` for this so it was being
swallowed silently.
xref #10749
> fix(pyspark): generate `IF NOT EXISTS` if `force=True`

- ibis/backends/mysql/__init__.py
- ibis/backends/mysql/tests/test_client.py
Same bug as #10782, but MySQL edition.
> fix(mysql): generate `IF NOT EXISTS` if `force=True`

- ibis/backends/clickhouse/__init__.py
- ibis/backends/snowflake/__init__.py
> fix(snowflake): use `as_posix` instead of `as_uri` to avoid escaping special characters

- ibis/backends/duckdb/tests/test_datatypes.py
- ibis/expr/types/generic.py
- ibis/expr/types/pretty.py
- ibis/tests/strategies.py
> fix(interactive-repr): ensure that null scalars can be repr'd interactively

- ibis/backends/bigquery/tests/unit/test_compiler.py
- ibis/backends/druid/tests/conftest.py
- ibis/backends/flink/tests/test_compiler.py
- ibis/backends/tests/test_temporal.py
- ibis/expr/types/numeric.py
- ibis/tests/expr/test_temporal.py
The final pre-10.0 API changes: change `as_timestamp` and `as_interval` to be positional-only.
> refactor(api)!: make `as_timestamp` and `as_interval` positional-only

- docs/release_notes_generated.qmd
`semantic-release` seems to have added an extra trailing space when generating release notes. HOW DARE IT!
> chore: remove trailing whitespace from release notes

- ibis/backends/mssql/__init__.py
- ibis/backends/mssql/tests/test_client.py
> fix(mssql): ensure that we only escape passwords if the password is not `None`

- ibis/backends/postgres/__init__.py
Avoid hard failure when `hstore` cannot be loaded.
xref #10804.
> chore(psycopg): allow `hstore` type registration to fail

- docs/tutorials/ibis-for-pandas-users.qmd
This is a very minor update. In the [Pandas Tutorial](https://ibis-project.org/tutorials/ibis-for-pandas-users#filtering-rows), there's a reference to an expected "6" True rows that should be "300" True rows, based on the screenshots and executing the code:
> docs: fix reference to incorrect value

- ibis/backends/duckdb/__init__.py
- ibis/backends/tests/test_export.py
- pyproject.toml
- uv.lock
Switch to use the DuckDB `delta` extension for reading deltalake data.
Closes #10829.
> fix(duckdb): use the `delta` extension for reading deltalake data

- ibis/backends/snowflake/__init__.py
- ibis/backends/snowflake/tests/test_client.py
> fix(snowflake): use `get` instead of `get_path`; `get_path` does not support columns with spaces

- docs/posts/ibis-duckdb-geospatial/index.qmd
Apparently the original URL that served the DuckDB database no longer exists.
This changes the geospatial blog to use upstream data from the postgis website, which
I then used to create a new duckdb database that I then uploaded to our ibis-blog-data-public
GCS bucket.
> docs(blog): use more reliable URL for geospatial data

- conda/environment-arm64-flink.yml
- conda/environment-arm64.yml
- conda/environment.yml
- docs/backends/duckdb.qmd
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_io.py
- pyproject.toml
- requirements-dev.txt
- uv.lock
Remove DuckDB fallback for reading from S3 using PyArrow. After this PR, users may need to use the DuckDB secret management mechanism to read from S3.
> refactor(duckdb): remove the pyarrow `read_parquet` fallback

- .github/workflows/check-generated-files.yml
- justfile
- pyproject.toml
- requirements-dev.txt
- uv.lock
Per discussion on Zulip, in this PR I re-enable installation of Ibis using
Python 3.9.
I think this approach might be a workable hybrid of NEP 29 and the Python
release cycle.
The approach here is effectively:
1. Continue to follow NEP 29 for CI testing.
1. Provide best-effort support for 3.9 on a case by case basis, avoid adding
any new Python 3.9-specific code.
In any case if this PR turns into a mess I'll likely close it out and things
will remain as they were, following NEP 29.
> feat(python): allow python 3.9 installations

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_client.py
- ibis/backends/pyspark/tests/test_import_export.py
- ibis/backends/tests/test_export.py
- Enabled partitioning in `create_table` and `to_parquet` methods for pyspark backend (already existed for `to_delta`)
- Added `partition_by` argument to `create_table` method for PySpark backend
- Overrode `to_parquet` method for PySpark backend to leverage [pyspark.sql.DataFrameWriter](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrameWriter.html) using a similar pattern as [`to_delta`](https://github.com/ibis-project/ibis/blob/c34ab76e86ca3120321ae553cc8403f8d8278105/ibis/backends/pyspark/__init__.py#L918) override, enabling corresponding kwargs for partitioning
- Added corresponding tests to ensure partitioning behaves as expected
* Resolves #8900
> feat(pyspark): support partitioning in PySpark backend file writes

- ibis/expr/types/json.py
The Examples section of JSONValue.__getitem__ is not published by Quartodoc because it does not publish private methods. They are great examples that help understand how to use JSON columns. Moving them to the class docstring should ensure that they are also published to the docs.
The issue in which I mentioned this is already closed, the part solved by this PR is mentioned in this message:
https://github.com/ibis-project/ibis/issues/10721#issuecomment-2624174148
> docs: move __getitem__ docs so that quarto publishes them

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
Closes #10861. The alias munging is no longer needed, so passing `params` to BigQuery `raw_sql` gets more convenient after this PR.
> fix(bigquery): allow sane use of `params` with `raw_sql`

- ibis/backends/pyspark/__init__.py
- ibis/backends/pyspark/tests/test_client.py
> fix(pyspark): avoid potentially different field names produced by SQL by using python-native APIs

- ci/release/bump_version.py
This fixes an issue with `bump_version.py` where we were originally bumping to major, but that results in an incorrect ordering when the next release after a pre-release is not a major release. 
For example,
Let's say the current version is 10.0.0, and the next release will be 10.1.0--a feature release. If the **pre**-release is published as 11.0.0.devNNN then the 10.1.0 release will sort before the pre-release, which is incorrect.
The solution is to always bump the pre-release by only its minor version.
> fix(dev-tools): ensure that bump is minimal so that later release sort properly

- ibis/common/deferred.py
Fixes https://github.com/ibis-project/ibis/issues/10887
Without this change, running `pytest --collect-only --doctest-modules --full-trace` on https://github.com/NickCrews/mismo takes 2.5 seconds. With this change, it takes 1.6 seconds
> perf: disallow __dunder__ attributes on Deferred

- docs/posts/ibis-duckdb-geospatial/index.qmd
Looks like https://github.com/duckdb/duckdb-spatial/issues/506 might be the culprit. Disabling extension optimizers for the ibis-duckdb-geospatial blog at least gets builds passing again.
> docs(build): disable misbehaving duckdb spatial optimizer

- ibis/backends/sql/compilers/oracle.py
- ibis/backends/tests/test_export.py
- ibis/formats/pyarrow.py
> fix(pyarrow-conversion): ensure that non-nullability is preserved

- ibis/backends/snowflake/converter.py
Follow-up PR to #10897, to address the same thing for the Snowflake backend.
> fix(snowflake): use schema when constructing pyarrow table

- pyproject.toml
It turns out that some tools that detect licenses do not understand license expressions. This change should make the PyPI package compatible with all systems.
> fix(build): ensure that legacy tools can recognize the validity of the Ibis license

- ibis/backends/mssql/tests/test_client.py
- ibis/backends/tests/test_examples.py
- ibis/examples/__init__.py
Let's see whether we can get examples working on mssql. Closes #9095.
> fix(examples): ensure that examples work on mssql and avoid using overwrite

- ibis/backends/bigquery/tests/system/test_client.py
- ibis/backends/sql/compilers/bigquery/__init__.py
Allow bigquery count distinct in window functions if window is the whole table. Closes #10390.
> fix(bigquery): ensure that count distinct can be used in window functions without a specified window

- docs/tutorials/getting_started.qmd
Add an example with `ibis.literal` in the "Tutorial: getting started" part of the docs.
* Resolves #10899
> docs: add an example with `literal` in "Getting started"

- ibis/backends/athena/__init__.py
- ibis/backends/athena/tests/conftest.py
Ensure that Athena test runs do not clobber each other by creating a database per user+python-version pair.
> ci(athena): use a different database for each python version to avoid clobbering data

- README.md
- docs/backends_sankey.py
Adds Theseus--the Voltron Data query engine--to a couple places that list our backends.
> docs: mention theseus in the readme and docs landing page diagram

- .github/workflows/ibis-backends-cloud.yml
Fix a hiccup from reverting to allow python 3.9 again
> ci: fix incorrect cloud ci yaml spec

- .devcontainer/Dockerfile
- docs/contribute/01_environment.qmd
- justfile
Hi! This PR addresses https://github.com/ibis-project/ibis/issues/10554 by adding an entry for `uv` to the "Setting up a development environment" tab panel.
It also adds a new `just sync <backend>` recipe, where `<backend>` is optional,  to make installing the adequate dependencies easier. Better names are of course welcome!
* Resolves #10554
> docs(setup): add `just` recipe and setup entry for `uv`

- ibis/backends/athena/__init__.py
- ibis/backends/databricks/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/tests/test_array.py
- ibis/util.py
Fix running cloud backends against python 3.9
> chore: fix running clouds on 39 due to use of 310-only tempfile features

- ibis/backends/conftest.py
- ibis/backends/postgres/__init__.py
- ibis/conftest.py
- ibis/tests/benchmarks/test_benchmarks.py
This adds a specific `to_pyarrow_batches` implementation to the PostgreSQL backend, which uses server side cursors. This allows ibis to allocate memory needed only for `chunk_size` results of the query instead of the whole set.
Resolves #10938
> perf(postgres): improve `to_pyarrow_batches` by using server-side cursors

- .github/workflows/ibis-benchmarks.yml
Fix benchmarks in CI by spinning up postgres before running them.
> ci(bench): spin up postgres for benchmarks

- ibis/backends/sql/compilers/bigquery/__init__.py
Fixes issue on `main` where codegen is incorrectly quoted due to incorrect use of `GroupConcat`
> fix(bigquery): adjust codegen for newer version of sqlglot

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_io.py
- ibis/expr/types/core.py
Fairly straightforward PR adding a `read_xlsx` function to the duckdb backend.
I tried to make the API generic enough that in case other backends support something similar they can use the same API. I also put the `test.xlsx` file in the general backends test folder. This was because I thought this might want to get shared by other backends. But let me know, I can put it some where else. I opted to just inline it into the source code because it is 6kb, I didn't want to go through the hassle of putting it in the test data repo, but let me know how to do that and I will :)
OR, if we expand the scope of this PR to include `to_xlsx()` function, then we would not commit the test file to git, and instead just test both read and write with a round trip of `assert original = …
> feat(duckdb): add `read_xlsx` and `to_xlsx`

- ibis/backends/sqlite/__init__.py
- ibis/backends/sqlite/tests/test_client.py
- ibis/backends/tests/test_client.py
This PR is the result of going through our test suite with `-W always::ResourceWarning` and `PYTHONTRACEMALLOC=20` and finding the places where `sqlite3.Connection`s are not being cleaned up.
> test(sqlite): squash remaining resource warning failures from unclosed connections

- .github/workflows/ibis-backends.yml
- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/conftest.py
- ibis/backends/postgres/tests/test_client.py
- ibis/backends/tests/test_client.py
This PR is the result of going through our test suite with `-W always::ResourceWarning` and finding places where we were not cleaning up postgres connections. I also attempted to fix the test hang, since I was able to reproduce it locally, and observed that some operations were idle in a transaction. The fix for that was to use `con.transaction()` instead of managing rollbacks/commits ourselves.
> fix(postgres): use `.transaction` method instead of managing our own

- docs/tutorials/coming-from/pandas.qmd
ibis generally follows pandas syntax for mutating columns, with the exception of adding string columns where `ibis.literal` is needed. `ibis.literal` is not mentioned yet in the pandas' user introductions, so it would be helpful to include this as it's not clear to the user why adding a float column or summing two columns together uses the same syntax as pandas, while a adding a single-valued string column does not. 
This is the reason https://github.com/ibis-project/ibis/discussions/11009 was opened (as a q&a link to send to new users).
Including it in the pandas introduction docs would reduce friction for switching to ibis for pandas users.
> docs: add introduction to pandas users for adding columns with single text values (literal)

- ibis/backends/postgres/__init__.py
- ibis/backends/postgres/tests/test_client.py
Related to, but not a full implementation, for https://github.com/ibis-project/ibis/issues/10991.
Just curious @cpcloud, is there a reason why we build up these schema queries using sqlglot instead of just raw SQL? Since we know this will only ever run on postgres, the portability/translation benefits of sqlglot are wasted. It seems like just writing the raw SQL string will be faster to execute, more stable, more familiar to more maintainers, and is easier to edit with LLMs (what I did here was compile this to SQL, ask an LLM to adjust it, and then translated the response back to sqlglot).
> feat(postgres): add support for reading enum types as strings

- ibis/backends/postgres/__init__.py
Based on @NickCrews comment [here](https://github.com/ibis-project/ibis/pull/11028#issue-2937753446). Using raw SQL here simplifies the code.
> refactor(postgres): use raw sql for `get_schema` invocation to simplify code

- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/bigquery/__init__.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/sql/compilers/datafusion.py
- ibis/backends/sql/compilers/mysql.py
- ibis/backends/sql/compilers/postgres.py
- ibis/backends/sql/compilers/pyspark.py
- ibis/backends/sql/compilers/snowflake.py
- ibis/backends/sql/compilers/trino.py
- ibis/backends/sql/datatypes.py
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_string.py
ArrayStringJoin for polars now returns None when the array is empty
* Resolves #10910
> fix(backends): array string join on empty array now consistently returns `None` across all supported backends

- ibis/backends/polars/compiler.py
- ibis/backends/tests/sql/snapshots/test_select_sql/test_chain_limit_doesnt_collapse/result.sql
- ibis/backends/tests/sql/snapshots/test_select_sql/test_topk_operation/e2.sql
- ibis/expr/types/generic.py
- ibis/expr/types/relations.py
This PR changes many things. I bet we don't want all of them, but I thought it would be easiest to just put up a laundry list and then I will prune out the things we don't like.
- Add a Table.topk(). I want this frequently to check for duplicates. I don't think it makes sense to provide a `by` argument here?
- Add "See Also" links to the docstrings
- made the "k" param to topk() be optional. If you don't supply one, it just ranks the values in descending order without limiting them. I do this often in interactive analysis, I like less typing, the .head(10) during the repr in interactive mode takes care of it for me. This isn't breaking for anyone.
- Makes the default column name for Column.topk() be `{column_name}_count`, which is the same as for Column.value_counts(). This default is …
> feat(api): make topk() and value_counts() more flexible

- ibis/expr/types/structs.py
Small tweak. the function isn't generic, so we don't need to be use TypeVars. Also add in the `Any` so that its consistent with being able to pass in python literals.
> fix(typing): remove unnecessary generics in `ibis.struct()` typing

- .github/workflows/docs-preview.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .releaserc.js
- ci/release/publish.sh
- ci/release/verify_conditions.sh
Move our CI to use trusted publishing to PyPI for releases.
> ci(publishing): use oidc for publishing to pypi and test pypi

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
fixes https://github.com/ibis-project/ibis/issues/11091
> fix(duckdb): always create temp tables in `temp.main`

- .devcontainer/Dockerfile
- Added `openjdk-17-jdk` dependency in Dockerfile to enable development with pyspark backend in devcontainer dev environment
N/A
> chore(devcontainer): add openjdk to devcontainer for pyspark dev

- ibis/expr/sql.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_join_subquery/decompiled.py
- ibis/expr/tests/snapshots/test_sql/test_parse_sql_limited_join/decompiled.py
- ibis/expr/tests/test_sql.py
When parsing SQL to Ibis using `parse_sql`, neither limit nor select statements contained in the sqlglot output were interpreted when parsing joins.
I've refactored both limit and projections into a helper function to limit duplicated code, and call them at the end of a join operation.
- Added `test_parse_sql_limited_join` to test the implementation of a limited join
- Changed expected output of `test_parse_sql_scalar_subquery`: The SQL from the test **does not** select the aggregated mean from the sub query, so it mustn't be included after the join
- Added a new test `test_parse_sql_join_subquery`  that actually selects the aggregated mean from the sub query to replicate the desired output  from the previous `test_parse_sql_scalar_subquery` implementation
- Changed SQL of …
> fix(ir): make ibis.to_sql() parse join limits and projections

- .github/workflows/ibis-backends.yml
- compose.yaml
- docker/spark-connect/conf.properties
- ibis/backends/pyspark/tests/conftest.py
- ibis/backends/tests/test_export.py
1. Upgrade `delta-spark` from v3.2.1 to [v3.3.0](https://github.com/delta-io/delta/releases/tag/v3.3.0) for pyspark backend testing in github actions
2. Upgrade `delta-spark` [maven package](https://mvnrepository.com/artifact/io.delta/delta-spark) from v.2.1.0 to v3.3.0 in spark-connect container :whale:  
- Ensure consistency w/ local pyspark testing & [compatibility](https://docs.delta.io/latest/releases.html#compatibility-with-apache-spark) with pyspark v3.5.5
3. Upgrade spark-connect configuration to enable proper delta & catalog functionality 
----
- **2** + **3** together resolved spark-connect testing issues from #11120
> chore(deps): update delta-spark to 3.3.0 for local and remote pyspark

- ibis/backends/tests/test_dot_sql.py
- ibis/expr/operations/subqueries.py
> fix(scalar-subquery): ensure that scalar subqueries `value` is resolvable with no underlying projection

- ibis/backends/sql/datatypes.py
- ibis/common/bases.py
- ibis/common/collections.py
- ibis/common/deferred.py
- ibis/common/numeric.py
- ibis/expr/datatypes/core.py
- ibis/expr/schema.py
- ibis/formats/numpy.py
- ibis/formats/pandas.py
I particularly wanted it for Schema.values() and .keys(), but then I just kept going
> chore(types): add type hints to lots of core stuff

- ibis/backends/databricks/__init__.py
- ibis/backends/databricks/tests/conftest.py
- ibis/backends/databricks/tests/test_datatypes.py
- ibis/backends/tests/test_client.py
Fix databricks datatype parsing using `DESCRIBE EXTENDED … AS JSON`. Closes #11130.
> fix(databricks): use `AS JSON` for programmatic output of schema information

- ibis/backends/clickhouse/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_catalog.py
- ibis/backends/mysql/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/tests/test_client.py
This started with fixing duckdb to support `.drop_database("mydb", catalog=self.current_catalog)`, but then when I added a test it revealed that many backends didn't implement this correctly.
> feat(backends): fixup drop_database() when passing a specific catalog

- ibis/expr/api.py
- ibis/expr/datatypes/core.py
It's nice to be able to just `import ibis; ... ; isinstace(x, ibis.DataType)`
> feat(api): expose DataType publicly at ibis.DataType

- ibis/backends/athena/tests/test_client.py
- ibis/backends/sql/compilers/athena.py
- ibis/backends/tests/snapshots/test_sql/test_isin_bug/athena/out.sql
- ibis/backends/tests/snapshots/test_sql/test_to_sql_default_backend/athena/to_sql.sql
- ibis/backends/tests/test_temporal.py
Fix athena naming such that everything except commas are allowed. Closes #11136.
> fix(athena): only replace commas instead of all special characters in column names

- ibis/expr/types/generic.py
- ibis/expr/types/numeric.py
Fixes (partially or fully, let's decide in the linked issue) https://github.com/ibis-project/ibis/issues/11029
for the examples, I had to do the weird construct a memtable with strings, then convert to floating inside the backend, as a workaround for https://github.com/ibis-project/ibis/issues/11075.
> docs: clarify NULL/NaN/inf distinction in docstring and examples

- ibis/backends/tests/test_client.py
- ibis/backends/tests/test_io.py
Verify that backends that load data statefully only do so once across all processes
> ci(data-loading): add a test to verify stateful loading

- ibis/util.py
- remove unused functions
- we can put the unicode characters directly in source code, don't need to do `"\u22ee"` indirection
- fix typing of `promote_util` and `promote_tuple`
> chore: cleanup util.py

- .github/workflows/pr-title.yml
- update comment when the commitlint now passes
- echo the output for easier debugging
- improve title of the comment job
> chore: improve conventional commits check

- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/druid/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/pyspark/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/trino/__init__.py
Before, if you did `ibis.postgres.connect("postgresql://user:password@host/my_db", schema="my_schema")`, then the schema in the url (in this case, it is blank) took precendence, and the backend would get a schema argument of "". Now, we consistently use the url as the defaults, but then always override them with what you pass explicitly as a kwarg.
This also just is a refactor and cleans up many implementations.
For example, it now makes it so that if a section of the url is missing, such as the password, then do_connect() is simply called without a "password" param. Before, for some backends, it was called with a default. This made it brittle in case we ever changed the default, or renamed params.
It also removes some unneeded boilderplate for snowflake, that is taken care of inside the …
> feat: make Backend._from_url() consistently use kwargs as overrides

- ibis/backends/oracle/__init__.py
- ibis/backends/oracle/tests/test_datatypes.py
The type mapping for Oracle number type can't handle the number type with precision and scale.
For example, given a table like
```sql
CREATE TABLE "number_table" ("number_8_2" NUMBER(8, 2))
```
In the Ibis side, we will get `Number('8', '2')`, we should cast them to int from string.
No corresponding issue currently.
> fix(oracle): cast string to int for the precision and scale of decimal

- ibis/backends/bigquery/__init__.py
- ibis/backends/snowflake/tests/test_client.py
Ignore a character that is not roundtripable. Also avoid a bigquery warning due to (incorrect) use of `page_size`.
> test(snowflake): ignore non-reproducible character

- ibis/backends/risingwave/__init__.py
It is now possible to specify some INCLUDEs statements when using create_source.
https://docs.risingwave.com/sql/commands/sql-create-source
> feat(risingwave): add support for include in create_source

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_client.py
Add the ability to specify a bigquery job ID in a query, and when specified, ensure bigquery creates a job with that ID.  It does this by using `.query` when a job ID is specified, which takes a job ID to use in creating the bigquery job, versus `.query_and_wait` which does not because it may not create a job.
* Resolves #11229
> feat(bigquery): Add the ability to specify a bigquery job ID

- docs/backends/databricks.qmd
Add missing backend documentation page.
I wasn't sure about support for `ibis.connect()` (I can try to test it later?), so I left it out for now. Athena also doesn't have `ibis.connect()` docs (which I was using as the initial reference, although I then looked across more for consistency).
> docs(databricks): add a backend documentation page

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/test_connect.py
Fixes resolution order of project id during `connect()`/`do_connect()` when a custom BigQuery Client is provided. Previously, if only a `client` was provided, the system default project id was used by Ibis instead of the one provided with the `client`.
Project id resolution order now makes intuitive sense when providing any combination of `client`, `credential`, and `project_id`.
1. `client.project` (if defined)
2. `project_id` (if provided)
3. `default_project_id` (acquired during credential creation)
* Resolves #11230
> fix(bigquery): maintain custom client project id when provided

- ibis/backends/duckdb/tests/conftest.py
Avoid consuming all resources when running the duckdb test suite parallelized across processes
> ci(perf): reduce threads to 1 when running duckdb test suite in parallel to avoid consuming all resources

- ibis/backends/sql/datatypes.py
Fixes https://github.com/ibis-project/ibis/issues/11191
I'd like to add a test for this. I think checking for roundtripping ibis.string -> sqglot.DataType -> ibis.string across all backends sounds like the best approach.
> fix(datatype): convert from sqlglot VARCHAR(MAX) correctly

- ibis/backends/tests/conftest.py
- ibis/backends/tests/test_array.py
- ibis/backends/tests/test_json.py
- ibis/backends/tests/test_map.py
- ibis/backends/tests/test_struct.py
Now tests can reference these easily if they rely on one of these datatypes
I wanted to use this in https://github.com/ibis-project/ibis/pull/11314 to mark the test case that relies on .collect()
> refactor(test): centralize marks for no array, struct, etc support

- .github/workflows/ibis-backends.yml
Seeing some timeouts in the mysql CI jobs; this should at least help rule out parallel test runs
> ci(mysql): run mysql tests serially to debug timeouts

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/duckdb/tests/test_datatypes.py
- ibis/backends/duckdb/tests/test_geospatial.py
See the added test, and the comment.
I'm not sure if this approach, of `pa_table.cast(ibis_table.schema().to_pyarrow())`, is too broad.
Instead of casting the entire pyarrow table to the expected schema, we could look for the specific case of
when the ibis type is `string` and the pyarrow type is `dictionary<values=string, indices=[intlike]>)`, and just convert those columns. For instance, this approach could be masking some other semantic mistake that we are making. I assume that pyarrow is smart enough to not actually perform computation unless the cast is really required, so I don't think this should be computationally wasteful.
This also makes it much more explicit that to get to pandas, we first convert to pyarrow, then to pandas, further cementing pyarrow as our first-class citizen, …
> fix(duckdb): support materializing enum types to pyarrow

- ibis/backends/tests/test_array.py
Enable some passing array-of-struct tests in Amazon Athena (c.f.: https://github.com/ibis-project/ibis/actions/runs/15582598162/job/43881199943).
> test(athena): enable xpassing tests

- ibis/backends/flink/tests/test_compiler.py
- ibis/backends/sql/compilers/flink.py
When string like '2025-04-28 00:00:00' cast to dt.timestamp.from_unit('s'), the unit is ignored, sql is like:
``
TO_TIMESTAMP(COALESCE('2025-04-28 00:00:00','yyyy-MM-dd HH:mm:ss.SSS')
``
Fix it when unit is second:
``
TO_TIMESTAMP(COALESCE('2025-04-28 00:00:00')
``
the default value of the format string is 'yyyy-MM-dd HH:mm:ss' .
> fix(flink): unit is ignored when str cast to timestamp

- ibis/backends/bigquery/__init__.py
- ibis/backends/bigquery/tests/system/conftest.py
- ibis/backends/bigquery/tests/system/test_client.py
I realized that my changes in https://github.com/ibis-project/ibis/pull/11233 and https://github.com/ibis-project/ibis/pull/11237 I completely focused on directly-created query jobs and completely overlooked functions which create bigquery load jobs and other queries, mainly in the process of uploading data.  Granted, the directly-created query jobs comprise the bulk of what I am concerned with, but it seemed proper to include other types of queries in this feature.
However, this has proved a bit stickier than anticipated.  The main situation I wasn't quite sure how to address was where one function call potentially creates several bigquery jobs, such as a job to truncate or drop a table if it already exists, a job to upload the data to a (temporary?) table in bq, and a job to select …
> feat(bigquery): add job_id_prefix to functions that produce bigquery loadjobs

- ibis/expr/types/generic.py
Related to https://github.com/ibis-project/ibis/issues/11153
Also adds examples for .notin(<contains NULL>)
> docs: add examples of .isin(<contains NULL>)

- ibis/backends/bigquery/__init__.py
Fixes the failing bigquery tests related to adding a `job_id` prefix. There was just a small spot where an upstream merge clobbered previous work. Thankfully, we had tests for this!
> fix(bigquery): undo removal of `job_id_prefix` functionality from `raw_sql`

- ibis/backends/tests/test_generic.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
>  fix(distinct): allow deleting rows when `on` is unspecified 

- docs/_quarto.yml
- ibis/backends/__init__.py
- ibis/expr/types/core.py
This is mostly an ergonomics thing.
I don't want to have to `import ibis; ibis.to_sql(e)`, I want to just do `e.to_sql()`
This also makes the docstring to compile() less confusing, and adds these methods to Columns and Values in the docs.
> feat: add Expr.to_sql()

- ibis/backends/duckdb/converter.py
- ibis/backends/snowflake/converter.py
DuckDB and Snowflake are backends that have both Pandas and PyArrow converters. Catching their import errors allows each to be used without the other dependency. The behavior will remain same - whether installed or not - because the upstream imports of PandasData and PyArrowData are already lazy.
fixes #11430, refs #10166
> fix(duckdb/snowflake): decouple Pandas and PyArrow backend converters

- ci/schema/trino.sql
- ibis/backends/sql/compilers/trino.py
Fixes failing Trino and Athena CI due to reversed operands in `DateDiff`
> fix(trino/athena): ensure that `DateDiff` operands are in the correct order

- ibis/backends/sql/compilers/trino.py
Fix spelling of athena and trino regular expression extraction method
> fix(trino/athena): ensure that regex extract compiler dispatch method is spelled correctly

- ibis/backends/tests/test_struct.py
- ibis/expr/types/relations.py
Previous the behavior of overlapping column names was to error when an unpacked struct field clashed with an existing column. This PR changes the behavior to always overwrite existing columns.
> feat(api): always prefer overwriting existing fields when unpacking with overlapping column names

- ibis/backends/tests/test_struct.py
> test(snowflake): relax the dtype check on `test_single_field` struct test

- ibis/backends/athena/__init__.py
- ibis/backends/bigquery/__init__.py
- ibis/backends/clickhouse/__init__.py
- ibis/backends/databricks/__init__.py
- ibis/backends/datafusion/__init__.py
- ibis/backends/duckdb/__init__.py
- ibis/backends/exasol/__init__.py
- ibis/backends/impala/__init__.py
- ibis/backends/mssql/__init__.py
- ibis/backends/mysql/__init__.py
- ibis/backends/oracle/__init__.py
- ibis/backends/postgres/__init__.py
- ibis/backends/risingwave/__init__.py
- ibis/backends/snowflake/__init__.py
- ibis/backends/sqlite/__init__.py
- ibis/backends/trino/__init__.py
- ibis/backends/trino/tests/conftest.py
- ibis/expr/schema.py
- ibis/expr/tests/test_schema.py
I renamed the `to_sqlglot` method to `to_sqlglot_columns_definition` and updated backend implementations to use the new name. I also added a test for this as I did not see one for `to_sqlglot`. 
I deprecated the old with the note that we will likely still keep it and change to be a SQLGlot schema, but wanted to be sure that was the intention. 
Closes #11310
> refactor: rename `to_sqlglot` to `to_sqlglot_columns_definition`

- ibis/backends/duckdb/tests/test_client.py
- ibis/backends/sql/compilers/sqlite.py
- ibis/backends/sqlite/__init__.py
Addresses issues with using marimo and importing sqlite3. xref: https://github.com/marimo-team/marimo/issues/5738
> refactor(sqlite): move sqlite3 imports local to avoid pyodide import issues with non-sqlite backends

- ibis/expr/types/relations.py
Adds docstrings to the named join methods (`table.left_join`, `table.anti_join`, etc) to provide more guidance on how to use these with references to the alternative ways.
Resolves #11364 
We still do not list out all of the possible join types ("inner","left","outer","right","semi","anti","any_inner","any_left") in [join](https://ibis-project.org/reference/expression-tables.html#ibis.join) docs, but this PR should be of value for those who provide the specific `*_join` method.
> docs: add join method docstring templates for various join types

- ibis/common/typing.py
- ibis/expr/datatypes/core.py
- ibis/expr/datatypes/tests/test_core.py
- ibis/tests/expr/test_udf.py
Fixes https://github.com/ibis-project/ibis/issues/11420
I'm not sure if this has other implications, @cpcloud would need to chime in if this messes up the semantics of things. My intention is this mostly just makes thing more lax.
> feat: allow dtype(Union[T, None])

- ibis/backends/clickhouse/tests/snapshots/test_select/test_array_join_in_subquery/out.sql
- ibis/backends/polars/compiler.py
- ibis/backends/sql/compilers/clickhouse.py
- ibis/backends/tests/snapshots/test_sql/test_isin_bug/clickhouse/out.sql
- ibis/backends/tests/test_generic.py
- ibis/backends/tests/test_struct.py
Add support for isin-style queries on unrelated dataframes. I could not figure out a way to do this that does not trigger computation. Definitely open to alternative implementations here. cc @MarcoGorelli.
> feat(polars): support is_in queries from uncorrelated tables

- ibis/backends/pyspark/__init__.py
- ibis/backends/tests/test_aggregation.py
- ibis/backends/tests/test_vectorized_udf.py
- ibis/backends/tests/test_window.py
- nix/pyproject-overrides.nix
Closes #11485.
BREAKING CHANGE: Type annotations using `pd.Series`/`pd.DataFrame` are now required per the non-deprecated PySpark Pandas UDF API.
> fix(pyspark): only register json unwraps if they are being used

- ibis/backends/duckdb/__init__.py
- ibis/backends/duckdb/tests/test_client.py
A bug was introduced in #11290 where specifying the `columns` parameter in `sge.insert` (line 226) leads to unquoted column names in the generated SQL query. As a result, if any column name coincides with a SQL keyword, the query fails with the following error:
```
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "SQL_KEYWORD"
```
This change updates the insert logic to ensure all column names are properly quoted.
> fix(duckdb): allow creating tables with columns containing sql keywords

- ibis/expr/rewrites.py
- ibis/expr/tests/test_dereference.py
- ibis/expr/types/groupby.py
- ibis/expr/types/joins.py
- ibis/expr/types/relations.py
- ibis/tests/expr/test_table.py
Refactor DerefMap traversal to be lazy
> refactor(binding): make DerefMap computation lazy and support multiple value inputs

- ibis/backends/duckdb/__init__.py
- use DuckDbPyRelation.to_arrow_table() instead of .arrow() to get a pyarrow.Table result from DuckDbPyRelation
- this is to add compatibility for duckdb 1.4.0 which changed the return type of DuckDbPyRelation.arrow() to RecordBatchReader (from Table)
* Resolves #11621
> feat(deps): support duckdb 1.4.0
